### ISSUE TITLE
Importer: Import meshes to appear smooth depending on normal

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#10]

**Comment by ciwolsey** [comment]
For me objects appear to be flat shaded and I can't set them to smooth.

**Comment by julienduroure** [comment]
Hello, 
This is a known issue, currently objects are created only with flat shaded durint glTF2.0 import. 
This is the purpose of this bug report to say that we need to create objects flat or smooth, depending of normals data included in glTF file.

**Comment by donmccurdy** [comment]
Note there is a similar issue in the exporter as well; custom normals are not written to the glTF file: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/122

**Comment by julienduroure** [comment]
Done in 70ddb0de4797e4484872419aa93366862752cb3c

Now, shading is an option in importer:  
*  Use normal data from file
*  Force smooth shading
*  Force flat shading

**Comment by marcatec** [comment]
I know this issue is closed, but does it create custom normals?
My testcase for a file that has per face vertex normals:
- import GLB into Blender -> no custom normals
- import GLB into Three.js Editor and save as OBJ
- import OBJ into Blender -> has custom normals

**Comment by julienduroure** [comment]
Can you please share your glb file?

**Comment by marcatec** [comment]
Sure.
I used this model of the Windows Mixed Reality VR controller from A-Frame:
https://github.com/aframevr/assets/blob/gh-pages/controllers/microsoft/default/right.glb

**Comment by julienduroure** [comment]
I can confirm that something goes wrong.
Discussion will continue on #79

**Comment by UX3D-nopper** [comment]
Adding auto smooth does not solve the issue.
Actually, during import, the indices have to be analyzed. If a normal is shared, it is smooth, if not, it is flat.

**Comment by julienduroure** [comment]
Can you please provide a glb that failed?
Problem is quite complex, because blender override custom normals in most cases

**Comment by UX3D-nopper** [comment]
Following ZIP-File contains the "smooth" Suzanne Blender File plus glTF:
[Suzanne.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2660649/Suzanne.zip)

After export, the asset is rendered correctly with smooth surfaces:
![grafik](https://user-images.githubusercontent.com/27856744/49699057-7d5dce80-fbcc-11e8-95e4-6f616bdbb73f.png)

Not included in the ZIP file, but Suzanne exported right after the creation:
![grafik](https://user-images.githubusercontent.com/27856744/49699106-4e942800-fbcd-11e8-9aa6-5fce03f3e123.png)

The information is available in the glTF file.

**Comment by julienduroure** [comment]
Are you sure you are using the "Use normals data" importer option?
Development note about blender API: use_auto_smoothing has 2 differents meaning, depending of existence of custom normal split:
- If no custom normals provided : use_auto_smooth is auto smoothing
- If custom normals provided : use_auto_smooth is a flag to force use of existing custom normals

**Comment by UX3D-nopper** [comment]
Original file:
![grafik](https://user-images.githubusercontent.com/27856744/49699480-20fdad80-fbd2-11e8-81e2-5c5b1c65290e.png)

After import:
![grafik](https://user-images.githubusercontent.com/27856744/49699496-4c809800-fbd2-11e8-8f6e-8bfe4ec6ae4e.png)

The importer is just setting auto smooth to true.

A glTF file has all information included, if a normal has to be shared or not. If the normals are shared the same way, the smooth shading then happens "automatically" in Blender.

**Comment by julienduroure** [comment]
use_auto_smooth is used here to force using the custom normal split layer defined from normals from glTF, it is not used for auto_smoothing

![capture du 2018-12-09 17-38-37](https://user-images.githubusercontent.com/1696020/49700019-578af680-fbd9-11e8-9201-7e6ebd986e67.png)

If you uncheck "use_auto_smooth"  (that, again, is very not well named when you are using custom normals), you are no more using custom normals from file.

Then, you can choose flat or smooth shading in blender. But because data are still triangulated, you have to remove double vertices to be able to interpolate vertices normals.

I can add an option to remove double automatically if needed

**Comment by julienduroure** [comment]
Example of custom normals that is not only flat  / smooth : https://github.com/aframevr/assets/blob/gh-pages/controllers/microsoft/default/right.glb

**Comment by julienduroure** [comment]
Not sure about final status on this issue. Did you find any bug in importing normals here?
