### ISSUE TITLE
Camera orientation node

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#1004]
I would like to know why the exporter is generating a Camera_Orientation node when Y_Up is selected instead of just applying the orientation fix directly on the node.

**Comment by scurest** [comment]
See #604.

It's possible to do without an extra orientation node (the importer does it) but as UX3D-nopper says "as soon as this node is animated and/or does have children with meshes, the whole thing gets complicated."

**Comment by jjcasmar** [comment]
Yep, Im seeing that. I guess the problem is that the mesh is adapted to match the Y_Up, so when you have a mesh as a children of the camera node, you need to separate into two branches, one for the mesh, which has already been transformed (by modifying the positions directly) and one for the camera, which needs to be transformed. 

Since a Blender object can only have a camera or a mesh, would it makes sense to change the naming of the nodes? Instead of Camera and Camera_Orientation, have an unnamed node and Camera. That way, when you look for the Camera node by name, you get the correct node with the camera component

**Comment by scurest** [comment]
For that, see #18.
