### ISSUE TITLE
T75132: draco compression not including multiple materials

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1006]
See https://developer.blender.org/T75132

**Comment by julienduroure** [comment]
@McNopper Can you please assign to someone of your team?

**Comment by castelblends** [comment]
Hi,

You can see here, just one of the materials is applied correctly. The difference between the two screenshots is the position of the material in the material stack.

![Screenshot from 2020-04-18 18-04-05](https://user-images.githubusercontent.com/61828683/79672391-81760500-819f-11ea-8559-c7b293abe69e.png)
![Screenshot from 2020-04-18 18-03-30](https://user-images.githubusercontent.com/61828683/79672395-8dfa5d80-819f-11ea-985b-baed1b54cf9b.png)

**Comment by LorenzWieseke** [comment]
Im having the same problem in blender 2.82 with the addon on version 1.2.33

I exported 3 glb verisons included in the glb folder. Without draco works perfect, with draco exporting all objects fails, exporting only one object with draco works.

![image](https://user-images.githubusercontent.com/29607121/81925048-40c3ad00-95e0-11ea-91b5-8f612c9ab50e.png)

![image](https://user-images.githubusercontent.com/29607121/81925089-50db8c80-95e0-11ea-8fc1-9fb0d6313df2.png)

![image](https://user-images.githubusercontent.com/29607121/81925114-5df87b80-95e0-11ea-8870-c8984ac5bce2.png)

[Scan_Test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4627699/Scan_Test.zip)

**Comment by LorenzWieseke** [comment]
Just in case anyone has the same problem, for me the workaround was to export without draco and then do compression manualy.

Unpack, run npm install, put your model in models folder and run compress.bat.

[Draco.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4627861/Draco.zip)
