### ISSUE TITLE
Materials of text objects or objects without mesh are not exported

### ISSUE THREAD

**Issue by feiss** [KhronosGroup/glTF-Blender-IO#1008]
When exporting an object that has no mesh data (no vertices, no faces), its material is not exported. This also happens with Text objects (curves with no mesh).

>side note: you can have an object with no mesh by entering edit mode (tab) and delete all vertices.

I can understand the decision (if the object has no mesh, there's no point into exporting the material), but I can imagine many scenarios where one may want to export the material even if there's no mesh. 

For example, for procedural geometry. You could use Blender for positioning (rotating/scaling..) an empty object and design its material. This information (transform & material) would be applied to the procedural object that is created on run time. (Yeah, you could use an Empty as a reference, but Blender doesn't let you apply materials to empties)

Another use for this would be to export material libraries, or materials not used (that will be used on run time)

So, my proposal would be to also export materials of text objects or objects with no mesh data (no vertices).

**Comment by donmccurdy** [comment]
Would https://github.com/KhronosGroup/glTF-Blender-IO/issues/231#issuecomment-591809329 provide what you need? I think an option to include all materials in the scene — regardless of whether they're attached to anything — could be reasonable.

But it isn't really possible to _associate_ the material with a particular object in the scene, unless that object has a mesh.... glTF does not let you put materials on a light, for example. So you would have to use the material's name to load and apply it in your application.

**Comment by feiss** [comment]
sure! that could work I guess. The user can rely on a naming convention to link materials to objects with no mesh 👍

You can close this issue, Thanks!
