### ISSUE TITLE
Always import with Yup2Zup

### ISSUE THREAD

**Issue by ptasev** [KhronosGroup/glTF-Blender-IO#1010]
**Is your feature request related to a problem? Please describe.**
I am importing 2 models. One has an animation across multiple nodes. The other is just a single mesh with no animation, and one node.

When I import the first one, I get all the nodes in a container called Yup2Zup.
When I import the second one, I just get the single node with the mesh on it's own with a rotation applied. 
I understand that this is to account for the difference in coordinate frames between Blender and gltf.

However, now when I parent the second gltf's node to one of the first gltf's nodes, the orientation is completely wrong because they use different methodologies to account for the coordinate frame.

How come one has the Yup2Zup, and the other doesn't?

This causes interoperability issues if you want to mix and match the 2 types of imports because now you have to remove the rotation of single objects before parenting them to Yup2Zup based nodes.

It was really frustrating trying to figure out what was wrong with my files before realizing that there was a rotation applied to the single node.

**Describe the solution you'd like**
To me this causes confusion, and I think it would make more sense to be consistent and always import with a Yup2Zup node as the parent.

**Describe alternatives you've considered**
Remove rotation from single nodes before parenting to objects under a Yup2Zup node.

**Comment by scurest** [comment]
@ptasev The importer never inserts a Yup2Zup node anymore. Try with the latest version of this addon.

**Comment by ptasev** [comment]
Where can I find the latest version? I wasn't able to find any links from the README.md.

**Comment by scurest** [comment]
Yeah, use master. Alternatively, you can download a 2.83 alpha of Blender from https://builder.blender.org/download/.

**Comment by ptasev** [comment]
Thanks, that seems to solve the problem. Now there is an issue where all the nodes in Blender take on the name of the underlying mesh.
