### ISSUE TITLE
Import GLB from Tiltbrush - Geometry not double sided

### ISSUE THREAD

**Issue by SamuelAB** [KhronosGroup/glTF-Blender-IO#1013]
**Describe the bug**
When I import a GLB from Tiltbrush into Maya and export it as an FBX, the geometry comes out double sided, as I would like.

When Maya is unable to import the GLB, I open the GLB file in Blender and then export it to FBX to 3ds Max. When

**To Reproduce**

1. Go to IMPORT
2. Click on GLtf 2.0
3. Select the file to import
4. Export to FBX
5. Import FBX into 3ds Max
6. Apply materials, unwrap UVs (bake lightmaps in Octane Render)
9. Export FBX to Unity
10. Geometry in only visible on one side

**Expected behavior**
Geometry should be visible on each side. Since I ma baking the lighting, both sides should be different. This is how it works if I use Maya instead of Blender. Some files cannot be opened by Maya and must be processed in Blender.

[Test files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4433938/Test.files.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.82a

**Additional context**
The geometry looks two sided in Blander and 3ds Max, but it is only apparent in Unity that it is one sided.

**Comment by julienduroure** [comment]
Hello,
I want to be sure to understand: the only step that is glTF related is the first 3 steps, importing the glb file into Blender ?
I can't see any issue here, the material is created in Eevee with option "backface culling" unchecked.

If the issue come from FBX export, please report here: https://developer.blender.org/
If the issue come from 3DS Max, please contact corresponding support.
If the issue come from Unity, please contact corresponding support.
