### ISSUE TITLE
Maximum Recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Dragoncraft89** [KhronosGroup/glTF-Blender-IO#1015]
When attempting to export this file [model.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4440350/model.zip), I get a `Recursion Error: maximum recursion depth exceeded while calling a Python object`

It seems like the problem is that there are many different objects in the scene, as it works, when I combine them into one object

Full stacktrace: 
[blender.log](https://github.com/KhronosGroup/glTF-Blender-IO/files/4440353/blender.log)

Blender version: 2.82a

**Comment by scurest** [comment]
The cause appears to be that a mesh is both (a) parented to a bone of the armature, and (b) skinned by that armature with an Armature modifier.

The exporter creates a cycle in this case (the arms mesh is skinned by the armature; the skin contains all descendants of the armature, including (say) buttons; buttons is skinned by the armature; the skin contains all descendants of the armature, including (say) buttons; etc...) and then gets stuck in a loop when it tries to recursively __traverse the cyclic graph.

**Comment by scurest** [comment]
Simpler test case: the cube is parented to the bone and also has an Armature modifier

[iss-1015.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4445482/iss-1015.zip)

![1015](https://user-images.githubusercontent.com/11024420/78687228-9312ff00-78b9-11ea-8fcd-07e97a098d44.png)
