### ISSUE TITLE
Export/Perf: use foreach_set/foreach_get for manipulating image data

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1017]
2.83 will include faster methods for getting/setting `image.pixels`: https://developer.blender.org/D7053

We should try these out and see how we can best make use them. If they're fast enough we might even be able to get rid of the compositor hack...

**Comment by scurest** [comment]
> If they're fast enough we might even be able to get rid of the compositor hack...

Looks like they are :DDD

**Comment by julienduroure** [comment]
This is a very good news :)
I saw the commit on blender repo, but didn't get time to test it yet.
