### ISSUE TITLE
Exporting gltf with draco compression messes up the vertex color

### ISSUE THREAD

**Issue by jespertheend** [KhronosGroup/glTF-Blender-IO#1019]
**Describe the bug**
When exporting a mesh with vertex colors as glb with draco compression enabled. The exported vertex color is different from what it should be. I haven't been able to import the exported glb into blender to check if this is a bug with blender or if it's an issue with three.js. But my exported mesh fails to render correctly both in https://threejs.org/editor/ as well as on https://gltf-viewer.donmccurdy.com/ and on https://sandbox.babylonjs.com/

**To Reproduce**
-Create a simple mesh with vertex colors (see attached blend file)
-Export as glb
-Export again as glb but with draco mesh compression enabled
-Notice how vertexColorTest.glb works fine on the websites mentioned above, but how vertexColorTestCompressed.glb doesn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/2737650/78997456-e51c8480-7b46-11ea-9915-d0a662c1e0e1.png)
no compression (left) vs draco compression (right)

**.blend file/ .gltf**
[vertexColorTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4461887/vertexColorTest.zip)

**Version**
Operating system: Darwin-19.4.0-x86_64-i386-64bit 64 Bits
version: 2.83 (sub 13), branch: master, commit date: 2020-04-08 21:23, hash: rB1239cab11ff9

**Additional context**
https://gltf.insimo.com/ has an implementation of draco mesh compression with working vertex colors. Notice how 'vertexColorTest insimo.glb' works on all sites mentioned above.

**Comment by julienduroure** [comment]
@McNopper Can you please assign to someone of your team?

**Comment by BenCidPerez** [comment]
Any news on this? The bug persists and makes using the exporter's draco compression unusable for all projects that rely on the vertex color data to be accurate.

**Comment by jespertheend** [comment]
In case it helps anyone, for the time being we ended up using https://github.com/CesiumGS/gltf-pipeline to compress all our assets in bulk.

**Comment by UX3D-eckerlein** [comment]
With the PR #1268, the compressed models are properly exported, though not all viewers display it correctly, such as Babylon (https://sandbox.babylonjs.com). Don McCurdy's viewer (https://gltf-viewer.donmccurdy.com) for instance does it right.

**Comment by jespertheend** [comment]
Thanks! Looking forward to this :)
