### ISSUE TITLE
lights and camera's not exporting?

### ISSUE THREAD

**Issue by spiraloid** [KhronosGroup/glTF-Blender-IO#102]
I've created a simple test scene for blender2.8 with three primitives and a skinned meshed with textures on a principled BRDF material with an HDR environment.

when I export the .glb file, I am only getting the meshes and textures.  no camera or lights.

![screen shot 2018-11-27 at 3 39 09 pm](https://user-images.githubusercontent.com/36362743/49118809-a68c6f80-f25a-11e8-841f-5217001d148c.png)

[simple_test_2.8.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2622238/simple_test_2.8.blend.zip)
[simple_test_2.8.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2622239/simple_test_2.8.glb.zip)

**Comment by donmccurdy** [comment]
I'm having issues with the latest build for some reason (https://github.com/KhronosGroup/glTF-Blender-IO/issues/103) and can't test this, but, what settings are you enabling in the exporter? Note that both cameras and lights need to be enabled.

Environments are not exported at this time.

**Comment by donmccurdy** [comment]
Ok I got the latest version of Blender and I'm able to test things again. Enabling both lights and cameras in settings with this model, I get the following error:

<img width="992" alt="screen shot 2018-11-28 at 6 19 09 pm" src="https://user-images.githubusercontent.com/1848368/49195015-5fce7080-f353-11e8-9988-ba585d299b2e.png">

**Comment by donmccurdy** [comment]
Ok, finally got my installation issues sorted out. Had two copies of the addon installed :/. This is working for me with the following settings:

<img width="235" alt="screen shot 2018-11-28 at 6 59 51 pm" src="https://user-images.githubusercontent.com/1848368/49196457-d497af80-f33f-11e8-8307-bbe889cf6de6.png">

**Comment by julienduroure** [comment]
I confirm that I don't have any error either. @spiraloid: Did you use settings like in screenshots from previous comment ?

**Comment by spiraloid** [comment]
Looks like I had an install problem on my PC.  Old version didn't ave the KHR Lights punctual option etc.  latest works fine on MAC.  Thanks for getting back to me.

**Comment by JonnyBlackburnCore** [comment]
I'm having problems with cameras using the latest Blender 2.8 and it's built-in gltf exporter.
It seems to create a new camera at 0,0,0, and changes my cameras into plain 3DObjects.

**Comment by julienduroure** [comment]
Yes, please open a new bug report, 
Don't forget to share your blend file and the glb file exported

Thanks !
