### ISSUE TITLE
traceback error on exporting to glTF 

### ISSUE THREAD

**Issue by kishorefdo** [KhronosGroup/glTF-Blender-IO#1024]
<img width="1440" alt="Screenshot 2020-04-13 at 1 14 59 AM" src="https://user-images.githubusercontent.com/59173663/79079058-451f5080-7d2a-11ea-831d-db27a7f16359.png">

**Comment by julienduroure** [comment]
Hello,
As requested in template you deleted, please provide the .blend file.
But first, please test with:
*  Current stable version, that is 2.82a, not 2.81
* If error still occurs in 2.82a, please test with a recent build, 2.83alpha:  you can download it on builder.blender.org

**Comment by julienduroure** [comment]
4 months without any answer. I'm going to close this ticket.
Don't hesitate to comment/reopen if you still have the issue with recent blender version
