### ISSUE TITLE
Remove +Y up export option?

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF-Blender-IO#1033]
Hello, I'm just curious why the +Y up setting is there.
GLTF has only _one_ coordinate system, so it seems clear to me that you should _always_ use +Y as up, as not doing so would lead to an incorrect export. So why have the option to turn it off? I feel like removing it would benefit the project.

**Comment by emackey** [comment]
Closing, to keep the discussion going in #348.
