### ISSUE TITLE
Export: When using multiple UVs on the same texture, all UVs are set to the first.

### ISSUE THREAD

**Issue by Zundrium** [KhronosGroup/glTF-Blender-IO#1037]
**Describe the bug**
It's currently not possible to use multiple UVs on the same texture.

I'm using one texture, red channel for AO, green channel for roughness and blue channel for metallic.
Metallic and roughness use **UV1**, and AO uses **UV2**.
When exporting, AO is using **UV1** as well.

When changing the AO to **another texture**, the export is perfect.

**Screenshots**
![blender_PA8rstia1M](https://user-images.githubusercontent.com/4927792/79700649-85854e00-8297-11ea-995b-b8c0587f2aa5.png)
![Code_C0TtvWqfNQ](https://user-images.githubusercontent.com/4927792/79700652-8918d500-8297-11ea-82ee-46fa64512b38.png)

**.blend file/ .gltf**
[cubes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4500354/cubes.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 2.82.7

**Comment by marcatec** [comment]
I can confirm this bug. I had the same issue, but didn't investigate further.
Three.js complains about the missing second UVs for AO.

**Comment by LorenzWieseke** [comment]
In my case disabling the draco compression fixed the problem

**Comment by julienduroure** [comment]
@marcatec Can you confirm that you also used Draco?

**Comment by marcatec** [comment]
Sorry, didn't see the question earlier.
No, I don't use draco.
In my case I have only two materials.
In the first one the ao-texture has a different size and it works.
In the second case metall, roughness and ao are all the same size. The exporter combines them all into one image, although ao uses a different uv-channel.

**Comment by julienduroure** [comment]
@marcatec Can you please provide your blend file please?

**Comment by marcatec** [comment]
I would like to test the latest version first.

**Comment by marcatec** [comment]
Now I've created a simple test scene:
[multi-uv.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4615922/multi-uv.zip)

The UV map "UVMap0" is used by Base Color, Metallic and Roughness.
The other one named "aoMap" is used by Occlusion.

In the exported gltf file texCoord 0 is used only by baseColorTexture (and not metallicRoughnessTexture), texCoord 1 is used by occlusionTexture **and** metallicRoughnessTexture.

The *irrigating* fact is, that Three.js complains about some UV mismatch, but corrects it by itself. I didn't notice that in the first place.
Other viewers (Babylon or Gestaltor) don't do the magic and show it wrong.

**Comment by julienduroure** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/1696020/81718939-adbe3200-947c-11ea-92ed-01d341c1881e.png)

![image](https://user-images.githubusercontent.com/1696020/81718909-9f701600-947c-11ea-8e52-dd9689709674.png)

**Comment by julienduroure** [comment]
@scurest
Problem come from here:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/90579852a469d4d616c10dd0f6bae076b6f3d1d9/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py#L102

The first socket is used, but the first socket is occlusion here, when we are managing metallic roughness. This is defined here:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/90579852a469d4d616c10dd0f6bae076b6f3d1d9/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L187-L193

**Comment by scurest** [comment]
The texture transform is also gathered from the first socket. So it looks like the intended API is that the caller should rearrange the sockets so that the one they want the texcoord/KHR_texture_transform to come from is first. However if that's the case, then __gather_index should also sort the tuple before passing it to gather_texture (so that, say, caching will work between gather_occlusion_texture/gather_metallic_roughness_texture).

So we could rearrange the orm_texture tuple in __gather_metallic_roughness_texture so that a metal/rough socket comes first and also sort the tuple somehow in gather_texture_info's __gather_index function.

Or we could add a new argument to gather_texture_info that basically tells it where to get the texcoord/textransform from (unfortunately it can't be a default argument so all callers would need to be updated).

**Comment by julienduroure** [comment]
Think I prefer the second proposition (passing a new argument)
