### ISSUE TITLE
master branch now requires Blender 2.90

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1040]
Upstream changes in 5c9f574 (namely the new `heading=` arg to `layout.column()`) require Blender 2.90. This only affects the exporter UI, so automated tests still work in 2.83 for the moment though.

This is a bit involved to change since `blender-28` is hardcoded in a lot of places involving tests

1. ~~update CI to remove hardcoded `28` references~~
2. ~~update CI to download the 2.90 alpha (cf #873)~~
3. ~~update tests/package.json to remove `28` references~~
4. ~~update tests/test/test.js to remove `28` references~~
5. ~~update test instructions in readme that talk about `blender-28`~~
6. ~~update readme to say master will become 2.90~~
7. ~~bump Blender version in bl_info to (2, 90, 0)~~

Not sure how exactly you'll want to do all this. Since 2.79 support is gone and since Blender is going to move to more frequent version bumps, it would be nice if some of this could be "generified" so that maybe only (2), (6), and (7) would be necessary for the next version bump (to 3.0).

cc @emackey

**Comment by scurest** [comment]
Also what's with the Docker files? Looks like they haven't been updated since 2.80.

**Comment by emackey** [comment]
> Also what's with the Docker files? Looks like they haven't been updated since 2.80.

I just bumped them from Node 8 to Node 12.  Since testing happens against downloaded nightly builds, the Docker images got neglected for a long time.

**Comment by julienduroure** [comment]
I did the last 2 points, seems we can close this ticket

**Comment by scurest** [comment]
@julienduroure Thanks. I noticed that the [blender-v2.83-release branch has gotten the `heading=` arg](https://github.com/KhronosGroup/glTF-Blender-IO/blob/blender-v2.83-release/addons/io_scene_gltf2/__init__.py#L563) though. Does it work with the latest 2.83? (Go to Export, then open the Include box.)

blender-v2.83-release has also gotten [the CI script for 2.90](https://github.com/KhronosGroup/glTF-Blender-IO/blob/blender-v2.83-release/.circleci/config.yml).
