### ISSUE TITLE
alphaMode not set on transparent materials

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#105]
When setting the alpha value of a material's baseColor to <1, I think we should default to `alphaMode=BLEND`. Currently the opacity value is written, but alphaMode is left blank, and defaults to OPAQUE. I can't see any equivalent to MASK on the Principled BSDF node, so I guess we can ignore that for now.

**Comment by donmccurdy** [comment]
Oops I missed the dropdown heh. Presumably this is what we should be using. 😅

<img width="247" alt="screen shot 2018-11-28 at 9 38 05 pm" src="https://user-images.githubusercontent.com/1848368/49201565-6834a480-f36f-11e8-9eab-b2628969bf83.png">

**Comment by UX3D-nopper** [comment]
Did have a look at it. The entry exists in both versions, maybe assigned to different objects.

**Comment by donmccurdy** [comment]
Looks like a couple material properties currently not implemented: https://github.com/KhronosGroup/glTF-Blender-IO/blob/a05af66333f508bc00e307af99be9beb9f2e968a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L78-L88

- alpha_mode
- alpha_cutoff
- double_sided
- extras
- name

**Comment by julienduroure** [comment]
Is now merged with blender 2.8 repo
