### ISSUE TITLE
This blender file has some animation issues and won't even export with the latest 2.83 nightly

### ISSUE THREAD

**Issue by jitspoe** [KhronosGroup/glTF-Blender-IO#1050]
**Describe the bug**
I've had a lot of trouble with this file.  It uses rigify and has 2 armatures and 3 meshes.  Worked fine with the Better Collada exporter for Godot, but support for that was dropped for 2.8x.  In older versions of 2.8, the TurnAndCrouch animation in particular is broken, and I couldn't get the armatures to sync up.  The feet should stay on the ground, but instead they rise up and the butt stretches down.  Also, the mesh seemed to export in a distorted state.  Now, I just get an error exporting.

**To Reproduce**
Simply export the file below as gltf.

**Screenshots**
![image](https://user-images.githubusercontent.com/7751182/80950611-2f022e80-8dc4-11ea-9255-c430690d26ac.png)

**.blend file/ .gltf**
[cinematic_character1e_b28.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4573700/cinematic_character1e_b28.zip)
(Yes, the character has no head, and there's a tall pair of triangles floating in front of it -- that's expected)

**Version**
 - OS: Windows 8.1
 - Blender Version 2.83 2020-04-02

**Additional context**

Note: I may not have set everything up correctly.  With the better collada exporter, the actions just exported.  With GLTF, they have to be stashed or something.  Not entirely sure how to get the animations for the photos and the character to work together.  In any case, it shouldn't completely error out the exporter.

**Comment by julienduroure** [comment]
I confirm that there is a typo in code source that causes the traceback. (jointb instead of join)
I will have a deeper look on it soon

note: For animations, some better explanations will be added soon on documentation/description here: #880 1036

**Comment by julienduroure** [comment]
@jitspoe This will be fixed in tomorrow' build

For animations, if you want to merge animations from different objects into a single glTF animation, you have to name correctly the tracks (not the strip), like this:

![image](https://user-images.githubusercontent.com/1696020/80987684-b1c1d280-8e32-11ea-8112-e93f4edaae48.png)
