### ISSUE TITLE
Exporting glb or glTF from blender creates heavy files

### ISSUE THREAD

**Issue by MaMOgithub** [KhronosGroup/glTF-Blender-IO#1051]
**When I export light files from blender they become very heavy in glb and glTF format**

**To Reproduce**
1. Press F4 inside blender
2. Click on 'Export'
3. Scroll down to 'glTF 2.0'

**Expected behavior**
I expect a 5 MB file not a 28 MB Glb for a small file

**Screenshots**

**Version**
 - OS: [Windows 10 Pro]
 - Blender 2.82

**Comment by julienduroure** [comment]
Hello,
Well, without any information about your file, we can't do anything with your report :
* Please provide a sample .blend file. Is there some textures in it? Animations? Are animation sampled?
* How do you estimate that the file size must be 5 Mb?

Without these informations, we can't analyse your issue, or explaining why the result is correct.

Thanks!

**Comment by donmccurdy** [comment]
@MaMOgithub we'll need  more information to know if this is expected behavior or a bug. Please let us know if you are able to provide the information above, thanks.

**Comment by timurshel** [comment]
I imported Flamingo.glb (76 kb) from three js examples. Then I exported it to f.glb and got 610 kb size.
When I remove flags from exporting animation , I got 68 kb. When I put some more animations - size became 5 Mb.

Is threre a way to make low recource models with animations using blender (latest version)?
[Flamingo.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5904670/Flamingo.zip)

**Comment by donmccurdy** [comment]
^Following up in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1322#issuecomment-771032229.
