### ISSUE TITLE
Import: turn on KHR_mesh_quantization?

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1053]
[KHR_mesh_quantization spec](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_mesh_quantization)

This got ratified I guess so we could support it in the importer.

AFAICT we don't actually have to change anything, just turn it on by adding it to the [`extensions_managed` array](https://github.com/KhronosGroup/glTF-Blender-IO/blob/7c5f0d54ea1e44258dd354c61eb3e73dd1a6bc8b/addons/io_scene_gltf2/io/imp/gltf2_io_gltf.py#L44-L49) (and the docs).

**Comment by donmccurdy** [comment]
Agreed — most likely it doesn't actually require any code changes.

**Comment by scurest** [comment]
Soooo....
