### ISSUE TITLE
"Include" settings on export panel are gone

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#1054]
The export settings panel for "Include" is empty

**Screenshots**
![Screenshot_2020-05-05_22-25-17](https://user-images.githubusercontent.com/5787647/81099185-bc0dca80-8f1f-11ea-9e65-8033cc1ec318.png)

**Version**
 - OS: linux
 - Blender Version  2.82
- Addon version 1.2.74 (installed manually)

Can you please confirm if this is happening for you as well?

**Comment by scurest** [comment]
Yeah, I noticed too: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1040#issuecomment-623584276. For now you can fix it by updating to Blender 2.90.

Note that you'll still need at least 2.83.9 for addon version 1.2.74 though:

**Comment by julienduroure** [comment]
Well, I probably fail a merge somewhere. I will fix the 2.83 branch

**Comment by julienduroure** [comment]
OK, I just committed the fix.
This should be available in next build, probably tomorrow.
Thanks !

**Comment by Ali-RS** [comment]
Great, it was fast. 
Thanks so much :)

**Comment by scurest** [comment]
@julienduroure blender-v2.83-release is still using 2.90's CI script though.

I think it would probably be easier to use git cherry-pick instead of merging branches. So if a PR is against master and you want the change in 2.83, instead of switching the PR's base branch to 2.83, merge the PR into master normally, then cherrypick the commits you want into the 2.83 branch.

**Comment by julienduroure** [comment]
@scurest In Blender repo, the process is to merge, not using cherry-pick. This is why I'm trying to have the same process here to detect merge issue (Well, seems I failed for this one...).

https://github.com/KhronosGroup/glTF-Blender-IO/blob/f72e57ffdde87995e4f31501e783b45a56e1c560/.circleci/config.yml#L9

Is that the only line to change to get 2.83 tests back on blender-v2.83 branch?

**Comment by scurest** [comment]
@julienduroure Oh, okay.

> Is that the only line to change to get 2.83 tests back on blender-v2.83 branch?

Yeah.
