### ISSUE TITLE
Generate orm texture if separate textures are present

### ISSUE THREAD

**Issue by makitsune** [KhronosGroup/glTF-Blender-IO#1058]
When creating models in Blender, most people use separate occlusion, roughness and metallic textures. This makes it easy to edit each one separately especially when using tools like substance painter or even procedurally generating textures to be baked.

However, when you export to gltf, those 3 textures are ignored and it's a pain to manually convert everything to orm just for gltf. I even made a tool to make this easier: https://makitsune.github.io/orm
Once I've converted all my textures to orm, then I suddenly cant export to any other formats anymore because gltf is the only one that utilizes this format for now.

My proposal is simply, make an orm texture at export! Perhaps find the maximum texture size between each 3 and generate a new texture just for exporting.

I've been dying for this, together with my friends since the release candidate of 2.8 in ~July 2019. It's also been complicated working with freelancers who don't create their own orm textures.

**Comment by donmccurdy** [comment]
From the docs:

> If images are connected to the Blender node in a manner that does not follow this convention, the add-on may attempt to adapt the image to the correct form during exporting (with an increased export time).

We've spend significant time on this and the addon does attempt to combine images, but it's only able to do so much.  In particular, I think that your images will need to be the same size. It should also be possible to use a separate occlusion texture, and to keep it separate, but roughness/metallic must be packed in the final glTF file.

Could you confirm if any part of that behavior is not working as expected for you?

Note that exports merging ORM textures will be significantly slower.

**Comment by scurest** [comment]
So can this be closed?

**Comment by makitsune** [comment]
Oh I never knew a pr was merged for this. I'll take a look today and reply back asap. This is a really awesome addition, thank you so much. It'll make things much less complicated for so many people and artists

**Comment by makitsune** [comment]
I was able to test this and I came across a different problem...

When I don't apply a metallic texture, the metallic value doesn't get converted to a gray scale image.

Here's an example principled shader setup with base color, roughness and normal:

<img width="400" src="https://user-images.githubusercontent.com/8362329/89568889-dc4d6e00-d81b-11ea-8e38-4956b8ae2b86.png"/>

This exports the textures like this:

<img width="400" src="https://user-images.githubusercontent.com/8362329/89569118-29314480-d81c-11ea-88c4-a24de87445b2.png"/>

![image](https://user-images.githubusercontent.com/8362329/89569202-4534e600-d81c-11ea-8150-3a5a2a01e5e5.png)

When decomposing the ORM texture in GIMP, the metallic is 100% white:

![image](https://user-images.githubusercontent.com/8362329/89569277-63024b00-d81c-11ea-9b4d-ed8a5c687ddd.png)

I tried changing the metallic value to different values, but I always get 100% white.

**Comment by donmccurdy** [comment]
@makitsune if the value is constant (e.g. 0.5), you will get a white metallic texture and the `metallicFactor` value will be 0.5. The two get multiplied together when rendering, so that's `0.5 x 1 = 0.5`.

**Comment by makitsune** [comment]
I tested the original issue combining a 2048x2048 jpg roughness with 16x16 png metallic and it worked perfectly! 
Thank you so much for fixing this. :heart: 

@donmccurdy Ah I see, thank you. I missed that.

Awesome! I'll close the issue. Thanks again!
