### ISSUE TITLE
Numpy dependency missing on 2.82a on Ubuntu 20.04

### ISSUE THREAD

**Issue by Utopiah** [KhronosGroup/glTF-Blender-IO#1063]
**Describe the bug**
Trying to use the exporter fails with a missing numpy error

**To Reproduce**
1. Install Blender from Ubuntu Discover
2. Click on File/Export/glTF 2.0
3. See error

**Expected behavior**
Being able to export

**Version**
 - OS: Linux (Ubuntu focal 20.04)
 - Blender Version 2.82a

**Additional context**
Installing numpy via `pip3 install numpy` fixed it.

**Comment by julienduroure** [comment]
Hello,
Can you please try using the zip file from https://www.blender.org/download/ ?
Seems that the Ubuntu version is not package correctly :-/

Thanks!

**Comment by Utopiah** [comment]
Ah you are correct, thanks will see how I can notify the package owner!
