### ISSUE TITLE
Remove references to dupli_type and dupli_group.

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#107]
* [ ] layer system is now removed. In addon, option is now commented, but corresponding code is still active in code. Maybe we should avoid dead code, and remove code linked to layers

* [x] We have to check code about dupli_group, because API changed, and obj.dupli_type & obj.dupli_group are removed from API

**Comment by donmccurdy** [comment]
I think we're tracking collections vs layers in #109, is the only remaining work here to remove references to "dupli_group"? I'll rename this issue.

**Comment by emackey** [comment]
Let's track collections vs layers in #193.

**Comment by julienduroure** [comment]
Seems we can close this one, reference to layers are removed, and dupli_group is now managed in 2.8 too, with dupli_collection
