### ISSUE TITLE
"Latest compatible with 2.79" ZIP version isn't

### ISSUE THREAD

**Issue by jvraines** [KhronosGroup/glTF-Blender-IO#1070]
Downloaded and installed to add-on directory. Upon activation in 2.79, get warning that add-on is not compatible, was written 2.81.6. Export produces non-working GLB file. Same problem with GZ archive.

**Comment by julienduroure** [comment]
The source code had double compatibility. 
The warning is not a blocking error, so ou don't have to care about it.

Please provide your blend file you are trying to export. Without it, we can't say anything.

**Comment by scurest** [comment]
I downloaded 2.79b and installed the addon from the `2.79` tag. I can confirm export works for me. In the absence of further details I'm assuming this is just some bug in the 2.79 version that never got fixed.

Can this be closed?

**Comment by jvraines** [comment]
Yes.
