### ISSUE TITLE
Wrong parenting on export

### ISSUE THREAD

**Issue by Gpinchon** [KhronosGroup/glTF-Blender-IO#1071]
When attempting to export simple parenting with various transforms to gltf, the result is wrong.

**Screenshots**
What I want :
![The expected](https://user-images.githubusercontent.com/8039212/82098518-64344800-9705-11ea-84a8-dec663bcaebd.PNG)
What I get :
![The result](https://user-images.githubusercontent.com/8039212/82098295-f8ea7600-9704-11ea-9b8f-647240893bcd.PNG)

**.blend file/ .gltf**
[BLEND](https://github.com/KhronosGroup/glTF-Blender-IO/files/4637206/CubeParentingTest.zip)
[GLTF](https://github.com/KhronosGroup/glTF-Blender-IO/files/4637216/CubeParentingTest.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.82a

**Comment by scurest** [comment]
This does happen in the 2.82 branch, but it works in master.

**Comment by julienduroure** [comment]
Because this is already working on current master version --> closing. Thanks!
