### ISSUE TITLE
Draco Binary Absent from Blender 2.82

### ISSUE THREAD

**Issue by Bug-Reaper** [KhronosGroup/glTF-Blender-IO#1074]
**The bug**
Draco Binary Absent from Blender 2.82

**To Reproduce**
1. Download Blender 2.82 on the latest Arch Linux release
2. Export any model as .gltf/.glb
3. Receive Error/Warning:
```'/usr/bin/2.82/python/lib/python3.8/site-packages/libextern_draco.so' does not exist, draco mesh compression not available```

If I'm not mistaken this should be installed by default. Anyway I can build it manually to fill in that gap? Sorry for posting this here but I couldn't find anyone with this exact issue.

I have a 50mb FBX file I'm loading into blender. Then exporting it to .gltf and it's 500mb. Presumably this is (at least in part) because I'm missing draco?

**Comment by julienduroure** [comment]
Hello,
Did you use the version provided by Archlinux?
Can you please test with official release on http://blender.org/download 
This should work here. And then contact the maintener of blender on Archlinux ans open an issue about the blender packaging.

**Comment by Bug-Reaper** [comment]
Hey @julienduroure, Yea I'm using the official Blender package maintained specifically for Arch.


```sudo pacman -S blender```
https://www.archlinux.org/packages/community/x86_64/blender/


I'll give the one from the website a shot as well

**Comment by Bug-Reaper** [comment]
The one from your website worked! Amazing!

```'/home/saint-llama/Downloads/blender/blender-2.82a-linux64/2.82/python/lib/python3.7/site-packages/libextern_draco.so' exists, draco mesh compression is available```

I'm going to just move that `libextern_draco.so` from that portable Blender to the directory my packaged manager Blender is complaining about in my first post.


I'll also try to let the maintainers of the Arch Linux Blender package know about the issue.


Thanks a gazillion

**Comment by iamsuz** [comment]
I am facing the same issue with blender 3.0.1 and i was not able to find the `libextern_draco.so` anywhere
