### ISSUE TITLE
Draco UV Issue

### ISSUE THREAD

**Issue by Mykita** [KhronosGroup/glTF-Blender-IO#1079]
Hi,
We've previously operated a `3dsMax -> glTF` workflow but changed to `Blender` recently. The Draco compression that came with the `Babylon exporter for 3dsMax` produced a working and optimized result, however the `in-built glTF exporter for Blender` is not working for us when we check the "`Draco mesh compression`" box in the glTF export UI. We can't open the model due to various errors.

We're therefor very curious about what Draco version that's being used with Blender 2.8 so that we can add support for it with our app.

**Comment by donmccurdy** [comment]
There have been no breaking changes to the Draco specification, so if the model produced does not load in your viewer (perhaps also test https://sandbox.babylonjs.com/ to be safe?) then it's likely that this a bug in export, rather than a version mismatch.

Could you share a model for which exporting with Draco doesn't work? And could you confirm that export works correctly when Draco compression is not enabled?

**Comment by Mykita** [comment]
Hi @donmccurdy . Thank you for your reply.

It seems like the problem has to do with UVs. Kindly see the attached examples files:

This version was exported with these settings (No UVs enabled - **working in viewer** but not the desired result as UVs are left out): 
https://www.dropbox.com/s/drxqui1jqg318nn/With_noUV_test.gltf?dl=0
![image](https://user-images.githubusercontent.com/18099703/83301820-9318e680-a1fa-11ea-9e70-71030e995295.png)

This version was exported with these settings (UVs enabled - **not working**):
https://www.dropbox.com/s/adoq8d7ihed35qj/With_UV_test.gltf?dl=0
![image](https://user-images.githubusercontent.com/18099703/83301962-ceb3b080-a1fa-11ea-92fb-5e317bd59e9b.png)

**Comment by Mykita** [comment]
Info: the tests above is done with` Blender 2.82a`

**Comment by Mykita** [comment]
This version was exported with these settings (UVs enabled + Draco deactivated: result is great - but Draco optimization isn't done here, which is what we would like to include):

**Comment by Mykita** [comment]
https://www.dropbox.com/s/praihltu2vck0ev/With_UV_noDraco_test.gltf?dl=0
![image](https://user-images.githubusercontent.com/18099703/83303375-3f5bcc80-a1fd-11ea-876b-a2ff98664185.png)

**Comment by Mykita** [comment]
@donmccurdy we did some more research. Do you think out problem can be related to this?
https://github.com/KhronosGroup/glTF-Blender-IO/issues/993

**Comment by donmccurdy** [comment]
That seems likely to be the cause, yes.

**Comment by Mykita** [comment]
So based on the error;
![image](https://user-images.githubusercontent.com/18099703/83515533-d1055b80-a4d5-11ea-890e-2d96bb73e105.png)
Do you know if there's currently any solution? I tried to research but sadly couldn't find any

**Comment by Mykita** [comment]
@donmccurdy do you happen to know what version of Draco your r116 viewer is using? I think that's interesting in regard of the bug i am pursuing, as r117 and the newest version of Draco might have these bugs fixed. Thank you so much

**Comment by donmccurdy** [comment]
I don't think the version of Draco is related here. The Draco file specification is standardized, and does not simply change without warning. The decoder in my viewer is pretty old, too, and wouldn't have any recent bug fixes. It sounds to me like https://github.com/KhronosGroup/glTF-Blender-IO/issues/993 is causing your issue.
