### ISSUE TITLE
Export gltf cause error with rigify and shape key

### ISSUE THREAD

**Issue by wijat** [KhronosGroup/glTF-Blender-IO#1084]
I use 2.83, I just export gltf file, Once i add shape key in my rigify character, it will cause error.

**To Reproduce**
1.add shape key
2.export gltf

**Expected behavior**
cause error and can not export gltf

**Screenshots**
![101788309_578931262759852_1883272850681364480_n](https://user-images.githubusercontent.com/8220843/83714957-d80ba580-a65e-11ea-8eeb-0684b709d1fc.png)

**.blend file/ .gltf**
[blender_file.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4727535/blender_file.zip)

**Version**
 - Win 10
 - Blender Version 2.83

**Comment by julienduroure** [comment]
Investigation is still in progress, but seems that:
* You assigned an armature action on a mesh object
* Some checks are already done to avoid any issue in this case
* Except when the mesh has also some shapekeys, and no shapekeys are keyed

So, I will add some more checks to avoid traceback, but here is how to avoid the issue:
* remove the armature action from the mesh object

**Comment by wijat** [comment]
>     * remove the armature action from the mesh object

I do it by your said, It work!!
Great thanks!
