### ISSUE TITLE
Multi-scene export fails

### ISSUE THREAD

**Issue by spiraloid** [KhronosGroup/glTF-Blender-IO#1086]
**Describe the bug**

a gltf exported from a .blend file that has multiple scenes in it will export every scene into the gltf, regardless if any objects are active.  This will cause it the be larger file and cause it to not load correctly with three.js GLTFLoader. etc.    Note: The export problems will only occurs when the active scene in blender is not the first scene.    

it's also compounded by the fact that some gltf viewers will error and some will load just first scene, so you can think it's working when it's not.

also, there are bunch of secondary issues that seem related to this.

an assert when combining NLA strips
export_nla_strips=False will cause an assert when I have a blend file with multiple scenes and one of the scenes has no action associated with any of it's objects.  I shored up this edge case and found other issues all stemming from this central issue.

an assert when applying modifiers
export_apply=True causes an assert.  if only one scene is present, this works.   if two scenes are present, and any scene but first scene is set to be the active scene,  the crash on export will happen.

**To Reproduce**
load the attached blend file and run the script in the text editor.  there are 4 scenes in the file.  the first has no animation.  the gltf gather action script is failing, likely because it wasn't expecting multiple scenes.

note the line comment at:

export_nla_strips=False  # <-- Set False will crash or produce duplicate actions

you can also get it to happen in the GUI if you try and export from a scene  and uncheck "Group by NLA Track" (same bool)

**Expected behavior**
I expect to be able to export all scenes and have only action per .glb file, and not have the hidden data from every other scene in the .blend file cluttering up the gltf file.

if no animated elements exist for one of the scenes, I expect it to still export without animation, or create an empy action animation.  I do not expect it to crash.   I'm writing a hack workaround to save a single keyframe in each scene before export to avoid this error.  Be good if it were fixed properly given the awesomeness of GLTF and its likely ubiquity.

**.blend file/ .gltf**
[gltf_crash.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4743748/gltf_crash.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.90.0 alpha

**Additional context**
I also note that I get the same error with apply modifiers.  (see comment in text text editor of the blend file to make it happen)

note, if you animate anything in the cube scene (the fist scene, without any animation), the scenes will export and the error will not happen.  however, if you inspect in the exported GLTF files, there will be 4 duplicate actions all named "action" instead of just the one action as expected.

**Comment by spiraloid** [comment]
The error in case you want to jump right to line 506.
```
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 506, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 42, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 55, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 64, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 39, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 100, in __gather_animations
    animations[merged_tracks[merged_anim_track][0]].name = merged_anim_track
IndexError: list index out of range

location: C:\Program Files\Blender Foundation\blender-2.90.0-c7329da14b22-windows64\2.90\scripts\modules\bpy\ops.py:201


Error: Python script failed, check the message in the system console
```

**Comment by spiraloid** [comment]
in case it's usefull, whoever fixes this might need this to manage scenes and collections:

```
            # turn off all collections in all scenes.
            for scene in bpy.data.scenes:
                bpy.context.window.scene = scene
                scene_collections = scene.collection.children
                for col in scene_collections:
                    col_name = col.name
                    bpy.context.view_layer.layer_collection.children[col_name].exclude = True

            # turn on this scene export collection for export.
            for scene in bpy.data.scenes:
                bpy.context.window.scene = scene    
                scene_collections = scene.collection.children
                for col in scene_collections:
                    col_name = col.name
                    if "Export" in col_name:
                        bpy.context.view_layer.layer_collection.children[col_name].exclude = False

```

**Comment by spiraloid** [comment]
the oddest part about this bug is if I delete all the other scenes from the blender file, then purge all orphan data,  and then export with the exact same settings, the exported glb file loads fine....

**Comment by spiraloid** [comment]
interesting.   it looks like every scene is writing out in the GLTF file regardless if it's the active scene.  I think might explain the chaos I'm seeing when I load the glb files.   perhaps an "export only active scene" option might be worth considering.

![image](https://user-images.githubusercontent.com/36362743/84667103-c46e0380-aed6-11ea-8ada-05a832f459c8.png)

**Comment by spiraloid** [comment]
here's the ascii gltf comparison between the exact same scene exported once from a blend file with only one scene present in the file.  and once exported from a blend file with multiple scenes present.   what's interesting is that both files look identical in https://gltf-viewer.donmccurdy.com/ and https://threejs.org/editor/, but the multi scene exported file will not load in the three GLTFLoader.

[single_vs_multi_scene_export.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4780759/single_vs_multi_scene_export.zip)

**Comment by javagl** [comment]
It's not *strictly* related to the Blender IO, but there has been some discussion about "Multiple Scenes" in general at https://github.com/KhronosGroup/glTF-Sample-Models/pull/242#issuecomment-564769202 , also pointing to https://github.com/KhronosGroup/glTF/issues/1542 (I'm just mentioning this to avoid putting too much effort into something that *might* become obsolete at some point, but I'm not up to date with the latest discussions here, admittedly...)

**Comment by julienduroure** [comment]
Well,

The crash is not linked to multiscene...
Open default cube, export gltf unchecking "group by NLA" --> crash

A check is missing...
