### ISSUE TITLE
Triangulate Faces on non square faces with Square UVS breaks the UV's. Related to glTF export

### ISSUE THREAD

**Issue by tripdragon** [KhronosGroup/glTF-Blender-IO#1091]
**Describe the bug**
The default export of Quads triangulation is distorting the UVs when the mesh is non square

**To Reproduce**
+ Make a plane
+ scale up one of its edges
+ unwrap all faces with option "Lightmap Pack" or Just "Reset"
+ add an image
+ Triangulate Faces

Or in attached blender file
+ Select the left most mesh that still has quads in edit mode
+ Press Ctrl + t or find the "Triangulate Faces" function via search tool
You'll notice the faces distort the mapping.
+ Select the "Fixed" option in the new options menu in the 3d view to fix

If you export the left most quads mesh to glTF and view in glTF viewer you will see how the AO map looks like the tris version in the screen shots

**Screenshots**
before
![before tris](https://user-images.githubusercontent.com/21336/84454424-5512be00-ac0f-11ea-9562-42cecaf33f7c.JPG)
after
![after tris](https://user-images.githubusercontent.com/21336/84454425-56dc8180-ac0f-11ea-9aac-1b06b0f7b6d6.JPG)
workaround
![using fixed option](https://user-images.githubusercontent.com/21336/84454429-58a64500-ac0f-11ea-8360-9cdcf5e9177f.JPG)

**Version**
OSX Windows

**Additional context**
If I can patch the addon code I will try. I did search for "quad" and quads_convert_to_tris but found nothing of value I could flip a toggle on

Blender file
[debuggingbox02.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4768127/debuggingbox02.zip)

**Comment by scurest** [comment]
IIUC the issue is that the appearance of a poly depends on how the poly is triangulated, and the exporter doesn't always pick the same triangulation that's shown in the viewport?

I have this patch lying around that appears to fix it. It does `calc_loop_triangles` to get a mesh's tris instead of doing `tesselate_polygon` on each poly ourselves. (I originally wrote it just for code simplicity.)

<details>

<summary>Patch</summary>

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
index e2d224c..261f2f5 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
@@ -17,7 +17,6 @@
 #
 
 from mathutils import Vector, Quaternion, Matrix
-from mathutils.geometry import tessellate_polygon
 from operator import attrgetter
 
 from . import gltf2_blender_export_keys
@@ -285,7 +284,10 @@ def extract_primitives(glTF, blender_mesh, library, blender_object, blender_vert
     #
     # Convert polygon to primitive indices and eliminate invalid ones. Assign to material.
     #
-    for blender_polygon in blender_mesh.polygons:
+
+    blender_mesh.calc_loop_triangles()
+
+    for loop_tri in blender_mesh.loop_triangles:
         export_color = True
 
         #
@@ -303,6 +305,7 @@ def extract_primitives(glTF, blender_mesh, library, blender_object, blender_vert
 
         attributes = primitive[ATTRIBUTES_ID]
 
+        blender_polygon = blender_mesh.polygons[loop_tri.polygon_index]
         face_normal = blender_polygon.normal
         face_tangent = Vector((0.0, 0.0, 0.0))
         face_bitangent = Vector((0.0, 0.0, 0.0))
@@ -319,29 +322,7 @@ def extract_primitives(glTF, blender_mesh, library, blender_object, blender_vert
 
         indices = primitive[INDICES_ID]
 
-        loop_index_list = []
-
-        if len(blender_polygon.loop_indices) == 3:
-            loop_index_list.extend(blender_polygon.loop_indices)
-        elif len(blender_polygon.loop_indices) > 3:
-            # Triangulation of polygon. Using internal function, as non-convex polygons could exist.
-            polyline = []
-
-            for loop_index in blender_polygon.loop_indices:
-                vertex_index = blender_mesh.loops[loop_index].vertex_index
-                v = blender_mesh.vertices[vertex_index].co
-                polyline.append(Vector((v[0], v[1], v[2])))
-
-            triangles = tessellate_polygon((polyline,))
-
-            for triangle in triangles:
-
-                for triangle_index in triangle:
-                    loop_index_list.append(blender_polygon.loop_indices[triangle_index])
-        else:
-            continue
-
-        for loop_index in loop_index_list:
+        for loop_index in loop_tri.loops:
             vertex_index = blender_mesh.loops[loop_index].vertex_index
 
             if vertex_index_to_new_indices.get(vertex_index) is None:
````

</details>
