### ISSUE TITLE
Importer: Add helper node for camera and lights

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#11]
Because of different coordinate system, a helper node is required.

Recommend, that there is an import option, where one can optionally resolve the orientation of the coordinate system.
Keep in mind, that this should be optional, as any possible animation on this node causes a domino effect of data conversions.

**Comment by donmccurdy** [comment]
Couple thoughts:

1. Does import of a light or camera currently give the wrong orientation?

2. Let's ensure that when a helper node is added, another helper node is not inserted on export, such that repeated import->export->import results in cascading wrappers. This could be accomplished with a fixed naming scheme or custom properties on an object.

3. Per https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/134, I still think it's unfortunate that we must have options at import/export to "opt out" of doing what the glTF specification requires. I don't know the full complexity of the domino effect you mention, but if it's _technically possible_, in theory, to implement a proper conversion (and probably include rigorous unit tests of that code), I think we should at least consider it a highly valuable feature request that we eventually do so. We could then remove the opt-out setting.

**Comment by julienduroure** [comment]
Not sure it need any helper node.
Seems https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cameras
import correctly

**Comment by julienduroure** [comment]
Based on PR #173, import seems to work for lights & camera, still & animation.
If you validate, I will close this issue
