### ISSUE TITLE
'Include' sub-menu not available anymore with latest plugin on 2.82 and 2.83

### ISSUE THREAD

**Issue by mcdev** [KhronosGroup/glTF-Blender-IO#1101]
**Describe the bug**
When exporting data from Blender, the 'include' sub-menu on the right of the export window is empty.

**To Reproduce**
1. Open Blender
2. Choose File/Export/GLTF 2
3. Try to unroll the 'Include' section on the right of the window: should be empty

**Expected behavior**
Prior to the current master version of the plugin, one could choose amongst various settings in the include sub-menu: selected objects, custom properties, cameras, Punctual lights
 
**Version**
 - OS: macOS
 - Blender Version  2.82 & 2.83

**Comment by julienduroure** [comment]
Hello,
Master branch of this repository is aimed to work with master branch of blender (currently 2.90 alpha).
Because of some changes in Blender API, we cannot keep retrocompatibility.
