### ISSUE TITLE
Cannot Load More than 4 animations of a GLTF model

### ISSUE THREAD

**Issue by jewel998** [KhronosGroup/glTF-Blender-IO#1102]
I recently was testing my model and it turned up that it is only able to export 4 animations for my model, even when I added more than 4 NLA in my model, it's not even showing on the controls menu. I hope you can help me out with this.

And I would be very thankful if you could help me out with rendering a terrain along with my GLTF model. Thank You!

**Comment by donmccurdy** [comment]
Could you share the `.blend` file to reproduce this issue? Do you see all of the animations present when loading the model in a viewer like https://gltf-viewer.donmccurdy.com/? If you can see all animations correctly there, the issue may be in the software you're using to load this model.

**Comment by jewel998** [comment]
Actually, I tried using https://gltf-viewer.donmccurdy.com and also the AnimationMixer and Clip functions in Three.JS.
I wasn't able to get more than 4 animations.

The file was actually pretty large so, here is the link for the file: https://drive.google.com/file/d/1y8FN51gU6wB7vP-38OdLVPb7puLPyiCI/view?usp=sharing

Thank you so much. I'm a huge fan. @donmccurdy

**Comment by donmccurdy** [comment]
Hm, yes it looks like the `Taunt` animation is completely missing from the exported file, for me. There's no limit at four specifically (in three.js, Blender, or glTF) so maybe something about this specific animation causes its export to fail? I don't see anything obviously wrong though.

**Comment by scurest** [comment]
The problem is with the Taunt action. All the fcurves are bad. They target non-existent bones. It won't play in Blender either. Check out the Action Editor. See the red lines?

![bad](https://user-images.githubusercontent.com/11024420/85616821-e3317000-b623-11ea-87c0-d71d40ce6585.png)

The names of the bones are using `mixamorig:...`. But the bones are really named `mixamorig9:...`. Put this in the Python Console to fix it. After that, Taunt will both play in Blender and export correctly.

```py
for f in D.actions['Taunt'].fcurves: f.data_path = f.data_path.replace('mixamorig', 'mixamorig9')
```

**Comment by jewel998** [comment]
Thank you, and I'm sorry I might've overlooked the animation errors. And I would be grateful if you also could suggest some study materials for Blender and WebGL. I'm a Computer Science Student and haven't been able to explore the Graphics Libraries that well and it took me 4 months to understand the mesh and PlaneBuffer System.

**Comment by donmccurdy** [comment]
I think the Blender forums can probably give much better advice on Blender resources than I could. If you're using three.js for WebGL, then https://discoverthreejs.com/ would be a good place to learn.
