### ISSUE TITLE
Allow empty extensions

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#1103]
I think this was discussed some months ago when the user extensions where added, but I dont know if we reach some solution. 
I am adding an extension to specify if a light should or not cast shadows, and for that I have added a KDAB_cast_shadows extension to the lights. 

```
"KHR_lights_punctual" : {
            "lights" : [
                {
                    "type" : "point",
                    "name" : "Light",
                    "extensions" : {
                        "KDAB_cast_shadows" : {
                            "cast_shadows": true
                        }
                    }
                }
            ]
        }
```

Although this works perfectly, the appearance of KDAB_cast_shadows should be enough, I dont really need the boolean property. 

But if I leave the dictionary empty, the KDAB_cast_shadows is removed from the list of extensions, so its not possible. 
Is there some solution for this?

**Comment by scurest** [comment]
Oh, that was #870.

Right now you can actually do

```py
extensions['KDAB_cast_shadows'] = {'dummy': None}  # dummy key gets removed
```

**Comment by jjcasmar** [comment]
Great, thanks!
