### ISSUE TITLE
Export a custom type made of blender types

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#1104]
Lets say I have a prefab to represent in blender something that my engine can do. In particular in this case I want a prefab to represent a particle system. As the blender particle system is much more complex that what I support in my engine, I was planning to create a prefab blender particle system made and provide a custom panel to modify the properties. That custom prefab would be made of some blender types, like a mesh, an empty with a scale to represent the output velocity and things like that. 

The issue is that when I export this, the exporter assumes that all in that prefab are valid things to be exported. For example, all my blender nodes are exported as gltf nodes, but I dont really want that. 

Is there anyway to constraint what nodes is the exporter exporting?

![image](https://user-images.githubusercontent.com/2644001/85863613-b5832d00-b7c3-11ea-8231-fa35964289a7.png)

For example, in that example, the exporter is generating a glTF.Node for the kuesa internal node, and I would like to avoid that.

**Comment by julienduroure** [comment]
I think you can probably use extension system to achieve what you want.
Maybe a solution is to use custom properties instead of new object creation to store custom data.

**Comment by julienduroure** [comment]
With #1378 , a virtual tree that can be filtered is generated before starting to export.
A hook is created just after official filtering, so addon developer can now create an addon to add additional filter

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
