### ISSUE TITLE
T78459 : glTF Exporter won't properly export linked collections if 'Selected objects' option is toggled

### ISSUE THREAD

**Issue by HumanRobot3D** [KhronosGroup/glTF-Blender-IO#1109]
**Describe the bug**
glTF Exporter won't properly export linked collections if 'Selected objects' option is toggled and those collections are selected. This use to work as intended before 2.83. The .glb do get exported but the objects in linked collections are not in the file.

**To Reproduce**
Create a .blend with any object under a collection and save. 
Create new blend, link the previous collection, try to export it with 'Selected objects' option toggled. "
Test the .glb in a viewer like this one https://gltf-viewer.donmccurdy.com/
(Note that I've only tested for .glb, this might still work for .gltf)

**Expected behavior**
The objects under a linked Collection should be exported like any other object.

**Version**
 - OS: Windows 10
 - Blender Version: 2.83.1 and daily build 2.90

**Comment by HumanRobot3D** [comment]
One workaround if you have objects in your scene that you doesn't want exported is simply to put them in a disabled collection before the export.

**Comment by zauberparacelsus** [comment]
Are Linked Collections the same as Collection Instances?  (IE: where you hit Shift-A and select something from the Collection Instance submenu)

I'm asking because I'm encountering an issue with those not being exported as well, except they don't get picked up regardless of what `Selected Objects` is set to.

**Comment by LorenzWieseke** [comment]
Having the same Issue, linked collections don't get exported, no matter if "selected objects" option is checked or not.

**Comment by KannebTo** [comment]
I found another workaround:
* right click on linked collection > `ID Data` > `Add Library Override Hierarchy`
* delete the linked collection and keep the override

Now everything seems to work as expected with or without `Selected Objects` option.

**Comment by julienduroure** [comment]
I confirm that it will be solved by #1378 #1472 #1494

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
