### ISSUE TITLE
glTF exporter crashes when including modifiers (Curve)

### ISSUE THREAD

**Issue by barafo** [KhronosGroup/glTF-Blender-IO#1112]
The Blender always crashes when I try to export the object into the GLTF format with included modifiers. 

1. Open folded.blend
2. Click on Export - glTF.
3. Choose format 'glTF Embedded'.
4. In Geometry, choose 'Apply modifiers'
4. See how Blender crashes.

I have attached the blend file that causes the issue.
[folded.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4883025/folded.zip)

Version
 - OS: Windows 10
 - Blender Version 2.83

**Comment by scurest** [comment]
folded.blend exports for me, though it takes about 11 minutes and 3.2 GB peak mem. Are you running out of memory?

(#1023 takes the export time down to 5 minutes, but 3.4 GB peak mem.)

**Comment by barafo** [comment]
That shouldn't be a problem as I have a 32 GB memory...whenever I looked into the process it never peaked to 3.2, it just crashed. Isn't there a problem with the settings/should I try to simplify the model?

I will try the suggested advice, thank you 👍

**Comment by scurest** [comment]
You could try using a [2.90 alpha](https://builder.blender.org/download/), though I don't really think it will help, because I just tried with the 2.83 branch and that worked for me too.

Does blender write a `crash.txt` log file on windows? If it doesn't, can you run Blender from the command line with the -d flag and see if it prints out anything useful when it crashes?

**Comment by barafo** [comment]
I have tried your advice and it has successfully finished its process. However, the object is not folded, so I'm not sure if the one you have exported is right? Could you please share the gltf that exported on your computer?
[folded_gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4883900/folded_gltf.zip)

**Comment by scurest** [comment]
No, it's like, 200 megs.

**Comment by barafo** [comment]
Oh, sorry about that. And does it work as in the Blender? Are the socks folded?

**Comment by scurest** [comment]
Not sure what you mean. This what it looks like when I open folded.blend. On bottom is what it looks like after an export and re-import.

![orig](https://user-images.githubusercontent.com/11024420/86766571-57024e00-c010-11ea-8a19-0aa97450fc30.png)

**Comment by barafo** [comment]
Sadly the gltf export didn't export as the one you have sent..I'm going to try different ways to at least achieve your result.

**Comment by EvanAW** [comment]
> You could try using a [2.90 alpha](https://builder.blender.org/download/), though I don't really think it will help, because I just tried with the 2.83 branch and that worked for me too.
> 
> Does blender write a `crash.txt` log file on windows? 

Starting with version 2.90, Blender now writes a [crash log](https://docs.blender.org/manual/en/dev/troubleshooting/crash.html#crash-log) on Windows.  (The manual still needs to be updated.)

**Comment by julienduroure** [comment]
Confirmed that I can't reproduce either.
Tested with 2.90 alpha: exported in 118s, memory picked around 2.3 Go (didn't check exactly).

**Comment by julienduroure** [comment]
Is there someone that can reproduce the issue?
