### ISSUE TITLE
Export is not creating a sampler with Extend/CLAMP_TO_EDGE extension

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/glTF-Blender-IO#1113]
When exporting gltf with a material that has Linear Interpolation and Repeat Extension, no sampler is exported, which I don't think is desired but I suppose is fine assuming those are the default values.
But when exporting with Linear Interpolation and Extend Extension, no sampler is exported. This seems like a bug.
Exporting with Closest Interpolation and Extend Extension does export a sampler with the expected NEAREST filters and CLAMP_TO_EDGE wraps.
Exporting with Linear Interpolation and Clip Extension does export a sampler with LINEAR filters and REPEAT wraps. Which I suppose is ok since Clip doesn't seem to translate to an allowed wrap value, but I think it should be CLAMP_TO_EDGE.

This is somewhat related to issue #307 

**Version**
 - OS: macOS
 - Blender 2.83.0 2020-06-03

**Comment by scurest** [comment]
Should have been fixed by #1082. Try with a 2.90 alpha from https://builder.blender.org/download/.

**Comment by DiegoAce** [comment]
Yeah 2.90 alpha is good. Thanks!
