### ISSUE TITLE
Bone rotation and scale issues after import of previously exported glTF file from 3ds Max

### ISSUE THREAD

**Issue by thlorenz75** [KhronosGroup/glTF-Blender-IO#1115]
Hi. I could not find any solution in the previous issues which where already discussed, so I hope you can help:

Problem:
After I exported a biped-character from 3ds Max as glTF file and imported it in blender 2.82 (sub 7 build date: 2020-03-12, 15:41:08) by using the glTF importer 1.1.46 I get the following result. 
![image](https://user-images.githubusercontent.com/68046344/87002488-00387800-c1ba-11ea-9d37-109fb1503e7f.png)
The bones are to big and the orientation is wrong.

I would expect, that the bones have the same length and orientation as in the original file.

![image](https://user-images.githubusercontent.com/68046344/87006365-d6368400-c1c0-11ea-903d-f619a17e4d2b.png)
This is the original in 3ds Max.

Is there a way to solve this problem? I attached the glTF file below.

Thank you in advance

 blender 2.82 (sub 7 build date: 2020-03-12, 15:41:08, windows 10; 3ds Max 2018)

[glTF_export.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4895018/glTF_export.zip)

**Comment by scurest** [comment]
You didn't include the .bin file so I can't test it, but the situation should be better if you upgrade to [Blender 2.83](https://www.blender.org/download/) or a [2.90 alpha](https://builder.blender.org/download/).

**Comment by thlorenz75** [comment]
Thanks for the fast reply. Here is the new zip file with the bin file.
[glTF_export.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4895182/glTF_export.zip)
