### ISSUE TITLE
Add an option to import empty nodes as cubes/arrows

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1118]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Make it possible to import empty nodes as cubes or arrows. It can be a combo-box like it's done with Bone Dir in 2.83 version.

**Comment by julienduroure** [comment]
Hello,
This request is not really linked to glTF import, and can be easily done outside of importer. This is a quite specific request, not sure this can be useful for everyone. What is your usecase?

**Comment by vergol** [comment]
I have a scene with 1'000 empty nodes and each one is not just a point, but also has rotation/scaling.
I can't see the rotation/scaling right after the import.

**Comment by julienduroure** [comment]
Hello,
No need to add anything for that.
Select all your empties, and change the "display as" property (use Alt to change for all your selection)

![image](https://user-images.githubusercontent.com/1696020/88459583-ca241500-ce96-11ea-92fc-9e03eca9adfb.png)

If more modification are needed, I don't think this should be part of the importer process. Any debug feature must probably done as separated script.
Closing, as standard Blender already has the feature
