### ISSUE TITLE
Question: Why not just use mesh.loops[i].normal?

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1119]
There's [a bunch of logic](https://github.com/KhronosGroup/glTF-Blender-IO/blob/blender-v2.83-release/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py#L368-L380) to get the normal for a loop, depending on if the poly is smooth etc etc.

What bad thing happens if we just always call `blender_mesh.calc_normals_split()` beforehand and always read it from `blender_mesh.loops[i].normal`?

Also, same question for tangents.

**Comment by scurest** [comment]
Specifically, what breaks with this patch? All the tests still pass

<details>

<summary>Patch</summary>

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
index 5fe719e..95c446f 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
@@ -144,9 +144,7 @@ def extract_primitives(glTF, blender_mesh, library, blender_object, blender_vert
 
     use_normals = export_settings[gltf2_blender_export_keys.NORMALS]
     if use_normals:
-        if blender_mesh.has_custom_normals:
-            # Custom normals are all (0, 0, 0) until calling calc_normals_split() or calc_tangents().
-            blender_mesh.calc_normals_split()
+        blender_mesh.calc_normals_split()
 
     use_tangents = False
     if use_normals and export_settings[gltf2_blender_export_keys.TANGENTS]:
@@ -242,21 +240,6 @@ def extract_primitives(glTF, blender_mesh, library, blender_object, blender_vert
             prim = Prim()
             prims[material_idx] = prim
 
-        if use_normals:
-            face_normal = None
-            if not (blender_polygon.use_smooth or blender_mesh.use_auto_smooth):
-                # Calc face normal/tangents
-                face_normal = blender_polygon.normal
-                if use_tangents:
-                    face_tangent = Vector((0.0, 0.0, 0.0))
-                    face_bitangent = Vector((0.0, 0.0, 0.0))
-                    for loop_index in blender_polygon.loop_indices:
-                        loop = blender_mesh.loops[loop_index]
-                        face_tangent += loop.tangent
-                        face_bitangent += loop.bitangent
-                    face_tangent.normalize()
-                    face_bitangent.normalize()
-
         loop_index_list = []
 
         if len(blender_polygon.loop_indices) == 3:
@@ -290,21 +273,11 @@ def extract_primitives(glTF, blender_mesh, library, blender_object, blender_vert
             vert += ((v[0], v[1], v[2]),)
 
             if use_normals:
-                if face_normal is None:
-                    if blender_mesh.has_custom_normals:
-                        n = blender_mesh.loops[loop_index].normal
-                    else:
-                        n = vertex.normal
-                    if use_tangents:
-                        t = blender_mesh.loops[loop_index].tangent
-                        b = blender_mesh.loops[loop_index].bitangent
-                else:
-                    n = face_normal
-                    if use_tangents:
-                        t = face_tangent
-                        b = face_bitangent
+                n = blender_mesh.loops[loop_index].normal
                 vert += ((n[0], n[1], n[2]),)
                 if use_tangents:
+                    t = blender_mesh.loops[loop_index].tangent
+                    b = blender_mesh.loops[loop_index].bitangent
                     vert += ((t[0], t[1], t[2]),)
                     vert += ((b[0], b[1], b[2]),)
                     # TODO: store just bitangent_sign in vert, not whole bitangent?
````

</details>

**Comment by scurest** [comment]
Does this interact with the importer using the normals to detect whether a poly should be flat/smooth?

@julienduroure I also don't understand why the importer has to set smooth/flat on faces. What's wrong with setting all faces from a primitive with a NORMAL attribute to smooth and just letting any "flatness" come from the custom normals? This seems to me to always give the right appearance? I have never been able to see a visual difference between "Use Normal Data" and "Smooth Shading".

I saw #10 but I don't really get it.

**Comment by julienduroure** [comment]
@scurest The attached file was created in blender with:
- 5 faces with smooth shading on +Y face
- some custom normals 

The importer 3 options give 3 differents results.

Yes, maybe we can simplify code, and always set custom normals, including when normals are smooth

[untitled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4930921/untitled.zip)

**Comment by scurest** [comment]
Thanks for the file. Okay, yeah, they are different. I thought that Smooth Shading set custom normals too but it doesn't. Let me try some things out...

**Comment by scurest** [comment]
I'll come back to the importer stuff. Returning to the original question...

I put the above patch on a branch, export-loop-normals, and ran some tests. Report on my findings follows.

### Visual Comparison Test

So I made a script that would create a Suzanne, mess with her normals, export, re-import, and take a screenshot showing the original and the reimported version. This is basically a "picture" of our normal pipeline. If the left and right look different, that's a roundtrip failure.

![example](https://user-images.githubusercontent.com/11024420/87707820-5af84380-c767-11ea-8971-63acdc92c777.png)

Now as you vary the "mess with normals" part, you get a series of these pictures, which you can arrange into a matrix that shows how the export->import pipeline handles various different normal situations. Here's the matrix using master. (You can spot four roundtrip failures here.)

![master-matrix-out](https://user-images.githubusercontent.com/11024420/87707843-6186bb00-c767-11ea-8aa0-8cd485cd5d7e.png)

Specifically, what varies is

* whether Auto Smooth is on or off
* the Auto Smooth angle (0 or 45 degrees)
* all polys flat vs random mix of flat and smooth
* no split normals vs split normals (rotated by a fixed value from the regular vertex normals)

This should covers everything the exporter branches on (has_custom_normals, use_smooth, use_auto_smooth).

(Note that the matrix contains duplicates since these are not all orthogonal options.)

Now we can compare two different configurations of the addon by comparing these matrices. For example, here's a comparison of master using "Use Normal Data" vs master using "Smooth Shading". Red pixels show a difference. (So they never look the same after all lol.)

![usenormals-vs-smooth](https://user-images.githubusercontent.com/11024420/87707868-6ba8b980-c767-11ea-9bd8-aa058eccad51.png)

Alright, so here's a comparison of master vs export-loop-normals

![vs-simplified](https://user-images.githubusercontent.com/11024420/87707884-71060400-c767-11ea-96a4-74deca2d5674.png)

There are four difference, conspicuously in the same spots master had a roundtrip failure. All four are basically all the same: create Suzanne and turn on Auto Smooth. We can verify the problem is in the exporter and not the importer by comparing how it looks in Blender, vs how it looks in the Three.js viewer after export

![comp2](https://user-images.githubusercontent.com/11024420/87707938-89761e80-c767-11ea-95c7-bb1826234c5c.png)

Same file after export from export-loop-normals

![comp3](https://user-images.githubusercontent.com/11024420/87707952-8e3ad280-c767-11ea-84e3-b5b806542266.png)

Btw, I can confirm this problem as far back as 2.82.

### Conclusion

export-loop-normals agreed with master in all but one case. In that one case, export-loop-normals was correct and master was wrong. So I'mma PR this.
