### ISSUE TITLE
`Apply modifiers` has no effect in Blender 2.8

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#112]
Checking `Apply modifiers` in the exporter seems to have no effect in Blender 2.8 Beta.

![image](https://user-images.githubusercontent.com/4733018/49254670-cad18300-f3f7-11e8-9e13-bb26e7a03eed.png)

**Comment by julienduroure** [comment]
Is now merged with blender 2.8 repo
