### ISSUE TITLE
Camera FoV mangled.

### ISSUE THREAD

**Issue by will-ca** [KhronosGroup/glTF-Blender-IO#1125]
**Describe the bug**
Cameras FoV is mangled on export.

**To Reproduce**
1. Export the default scene using default settings, but including the Camera object.

**Expected behavior**
Exported camera has same FoV as camera in scene, and can be imported using same add-on or external tools, with the same FoV.

**Actual behaviour**
Exported camera has different FoV from camera in scene.

The new FoV seems to be approximately numerically equivalent to the old camera with radians substituted for degrees. E.G., The default camera has a focal length of 50mm with a sensor size of 36mm, for a FoV of 39°— the exported camera has an FoV of around (but not exactly) 0.39 radians. That's probably a coincidence, though.

**Version**
 - OS: Linux
 - Blender Version 2.83.2, official Blender.org download. (GLTF add-on version 1.2.75.)

**Comment by will-ca** [comment]
Wait, is it clipping the FoV to that along the shortest dimension of the camera's aspect ratio, in order to account for differences between Blender and GLTF FoV interpretation by aspect ratio?

**Comment by julienduroure** [comment]
Linked to #1111 ?

**Comment by julienduroure** [comment]
@will-ca Can you please test again with a recent test build that you can download on builder.blender.org ?

**Comment by will-ca** [comment]
@julienduroure Ah, yeah. It's working now, I think, with `.aspectRatio` being exported.

Actually, the `yfov` values seem to be the same, and now I'm having difficulty reproducing the original issue using a clean Blender file. I think maybe my model viewer was assuming a 1:1 aspect ratio and then letterboxing the camera vertically, or something.
