### ISSUE TITLE
KHR_texture_transform support?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#113]
It seems that this code has disappeared: https://github.com/KhronosGroup/glTF-Blender-IO/search?q=KHR_texture_transform&unscoped_q=KHR_texture_transform

https://github.com/KhronosGroup/glTF-Blender-IO/commit/2786bbd8de72f48bf66189bca09956b24494f818

**Comment by UX3D-nopper** [comment]
It just has been moved:

![image](https://user-images.githubusercontent.com/27856744/49281362-a96ea680-f48c-11e8-8a82-35492b273bd9.png)

**Comment by donmccurdy** [comment]
I mean that the term, "KHR_texture_transform" no longer appears anywhere in this codebase, except in the description of that checkbox — the code has accidentally been removed, I think. A test export confirms this isn't working:

![screen shot 2018-11-30 at 9 41 35 am](https://user-images.githubusercontent.com/1848368/49305449-277a7f80-f484-11e8-8863-fb978e571688.png)

**Comment by dsinni** [comment]
Would definitely love to see this feature. IMHO, if the transforms are displaying in the renderer, it would be amazing (and would make the most sense) if they where exported.

The `Texture Coordinate` + `Mapping` + `Image Texture` configuration seems to be fairly common (so common in fact that `Ctrl + T` does this automatically with Node Wrangler), so holding out hope that this can be translated effectively in export.

Keep up the great work!

**Comment by emackey** [comment]
@julienduroure Can you push the latest?  Thanks!

**Comment by donmccurdy** [comment]
From Gitter, it sounds like KHR_texture_transform was working for @dsinni. @EtagiBI could you share a screenshot of the material configuration as well, and ensure you've enabled the `Texture Transforms` export option?

**Comment by EtagiBI** [comment]
> @EtagiBI could you share a screenshot of the material configuration as well, and ensure you've enabled the `Texture Transforms` export option?
Works fine with todays build of Blender. Thanks.
