### ISSUE TITLE
Incorrect rotation when exporting bones with "Inherit Rotation" disabled.

### ISSUE THREAD

**Issue by ASavchenkov** [KhronosGroup/glTF-Blender-IO#1130]
According to an answer I got [here](https://blender.stackexchange.com/questions/186730/gltf2-0-export-ignores-inherit-rotation-property-changes) "Always Sample Animations" (enabled by default) should take care of this, but it doesn't in my case.

Blender version: 2.83.1

.blend and .glb file below:
[Inherit Rotation Issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4939833/Inherit.Rotation.Issue.zip)

In this particular case, the movement of the foot in the .glb file does not match the movement of the foot in the .blend for the animation "CombatStance"

**Comment by ASavchenkov** [comment]
My bad. A bit embarrassing how I missed that issue...

**Comment by scurest** [comment]
No sweat lol. I tested your file and #880 does appear to fix it.
