### ISSUE TITLE
Addon with multiple extensions

### ISSUE THREAD

**Issue by VitusW42** [KhronosGroup/glTF-Blender-IO#1135]
Hi folks,

I'm not really used to the gitHub format, so please excuse me if I'm out of place here. @julienduroure suggested to open a ticket to get some advice and I hope this is what he meant :)

I’m writing a Python addon which will extend the glTF format using extensions and extras. Ideally, I’d like my addon to hook into the existing glTF exporter that comes with Blender 2.8x.

My question is what the right approach for this would be. I took the example init.py from gitHub, and I found a way to add it to my existing project. What I am trying to figure out though is some sort of best practice to add multiple extensions that affect different aspects of the scene.

The extensions I am using, set up some shader properties and thus should be controlled by the different materials and hook into the material definitions of the glTF file.

Some other are used for animations and such and need to be on the object layer.

I would appreciate any pointers on how to set up this project properly.

**Comment by VitusW42** [comment]
Some thoughts after dealing with this for a couple of days:
The documentation on how to use extensions/extras is essentially non-existent yet - or I haven't found it yet, in which case it's not very visible.
The sample code under <example-addons> is very simplistic and attaches only one extension to the <nodes>-node of the glTF file. It took me a while to find out how to change that.

From what I can gather, the glTF Blender exporter is calling various _gather_<something>_hook_ functions from the extending addon. I found those in the exp folder of the Khronos Blender addon.
So, if you want to extend the material, you implement a _gather_material_hook_ function, but you need to make sure to give it the right parameters, which can be found with a bit of digging in the _gltf2_blender_gather_materials.py_.

Cool. But some of those functions have quite a list of parameters (9 for the gather_mesh_hook function), so it'll be a bit of trial and error to get it right. So if someone here has some insights, please share it.

One thing I need, and haven't found yet, is an extension of the first node "assets" in the glTF file. Any idea what gather_hook function to use for that?

**Comment by VitusW42** [comment]
Since no one found the time to help out yet, I started digging through the code of the gltf exporter/importer. It's honestly a shame that so little of the functionality is documented, because it looks like you guys coded this things extremely versatile!

That being said, it looks to me (and correct me, if I'm wrong) as if it's not possible to add an extension to the asset node of the file using an external addon. Since I really need to add an extension to that node, I copied the source of the glTF exporter and started to play around a bit to solve this. And just to preface this: I am not at all experienced with Python and the code of your exporter is extremely complex - so my approach might be foolish.

I modified the _exp.gltf_blender_gltf_exporter.py_ by adding this import:
`from io_scene_gltf2.io.exp.gltf2_io_user_extensions import export_user_extensions`

and then added a call to the __init__ function:
`    def __init__(self, export_settings):
        self.export_settings = export_settings
        self.__finalized = False

        copyright = export_settings[gltf2_blender_export_keys.COPYRIGHT] or None
        asset = gltf2_io.Asset(
            copyright=copyright,
            extensions=None,
            extras=None,
            generator='Khronos glTF Blender I/O v' + get_version_string(),
            min_version=None,
            version='2.0')

        export_user_extensions('gather_asset_hook', export_settings, asset)
`

With this, the exporter will search for the function 'gather_asset_hook' in other addon's glTF2ExportUserExtension classes.

It looks good at first glance, but this is causing a string of error messages that I can't understand:

>   File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 46, in from_union
    return f(x)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 427, in <lambda>
    result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 61, in from_dict
    return {k: f(v) for (k, v) in x.items()}
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 61, in <dictcomp>
    return {k: f(v) for (k, v) in x.items()}
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 107, in from_extension
    assert isinstance(x, dict)
00:05:32 | ERROR: An error occurred on line 46 in statement return f(x)
00:05:32 | ERROR: An error occurred on line 427 in statement result["extensions"] = from_union([lambda x: from_dict(from_extension, x), from_none],
00:05:32 | ERROR: An error occurred on line 61 in statement return {k: f(v) for (k, v) in x.items()}
00:05:32 | ERROR: An error occurred on line 61 in statement return {k: f(v) for (k, v) in x.items()}
00:05:32 | ERROR: An error occurred on line 107 in statement assert isinstance(x, dict)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 46, in from_union
    return f(x)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 38, in from_none
    assert x is None
00:05:32 | ERROR: An error occurred on line 46 in statement return f(x)
00:05:32 | ERROR: An error occurred on line 38 in statement assert x is None
Traceback (most recent call last):
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\__init__.py", line 513, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 1191, in to_dict
    result["asset"] = to_class(Asset, self.asset)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 66, in to_class
    return x.to_dict()
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 428, in to_dict
    self.extensions)
  File "C:\Users\o-nit\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_extended_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError



Any ideas?

**Comment by scurest** [comment]
That usually happens when you put some data into one of the gltf2_io classes whose type it didn't like. If I add it like you did and use it like

```py
    def gather_asset_hook(self, asset, export_settings):
        asset.extensions['foo'] = {'a':'b'}
```

it appears to work.

**Comment by VitusW42** [comment]
I followed the structure of the sampleExtensions file. Here's the implementation in my addon:

```
    def gather_asset_hook(self, gltf2_asset, export_settings):
        if self.properties.enabled == True:
            if gltf2_asset.extensions is None:
                gltf2_asset.extensions = {}
            gltf2_asset.extensions["EXT_normal_map_convention"] = self.Extension(
                name="EXT_normal_map_convention",
                extension={"tangent_space_convention": "DirectX"},
                required=False
            )
```

**Comment by scurest** [comment]
Ahhh, the Asset isn't being `__traverse`d. Stick this at the bottom of the \_\_init\_\_ function

````diff
@@ -104,6 +106,8 @@ class GlTF2Exporter:
             gltf2_io.MaterialOcclusionTextureInfoClass
         ]
 
+        self.__traverse(asset)
+
     @property
     def glTF(self):
         if not self.__finalized:
````

`__traverse` does stuff like replace Extensions with an actual dict and mark the extension as used/required in the extensionsUsed/extensionsRequired arrays.

**Comment by VitusW42** [comment]
Fantastic, that worked! You're a wizard!
May I suggest to add this change in future versions to support asset extensions?

**Comment by scurest** [comment]
Sure, you can send a PR. I don't decide what gets merged, but I don't see why it wouldn't be.

**Comment by VitusW42** [comment]
OK done. I hope I did this correctly. It's my first time ever....

**Comment by scurest** [comment]
You did it correctly :)

**Comment by VitusW42** [comment]
Yeeha! Thanks for your help!
