### ISSUE TITLE
T79104: Exporting a valid GLTF (was valid before import) causes GLTF validation errors

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1138]
See https://developer.blender.org/T79104
On 2.83

**Comment by julienduroure** [comment]
Linked to #372 ?

**Comment by julienduroure** [comment]
Confirmed that using "Degenerative dissolve" solve the issue.
No issue when importing with "merging vertices" too

**Comment by scurest** [comment]
Yeah, there are tris with collinear verts.

There are two solutions I can think of...

We could just write some fixed value (say, (0,1,0)) whenever we have a zero normal. This would satisfy the validator and it shouldn't matter since degenerate tris are invisible.

Or we could try to filter out any tris that have at least one zero normal.

**Comment by julienduroure** [comment]
Filtering will probably be more time consuming that writing some fixed value, doesn't it?

My vote goes for writing some fixed value, since tris are invisible, no matter the value

**Comment by scurest** [comment]
Fixed value would be easier to code :)

Can this wait until after #1120? I think setting a fixed value would just be

````py
# Change all zero normals to [0,1,0]
is_zero = ~normals.any(axis=1)
normals[is_zero, 1] = 1
````

**Comment by julienduroure** [comment]
Yes, sure, let's wait after #1120 

(BTW, test are in progress, i will batch merge lot's of PR after 2.90 release)

**Comment by scurest** [comment]
Patch I guess (I didn't test it)

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
index ca38aa7..19d3b35 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
@@ -348,6 +348,12 @@ def __get_normals(blender_mesh, key_blocks, armature, blender_object, export_set
             ns[:] = __apply_mat_to_all(normal_transform, ns)
             __normalize_vecs(ns)
 
+    for ns in [normals, *morph_normals]:
+        # Replace zero normals with the unit UP vector.
+        # This happens (only?) for degenerate tris.
+        is_zero = ~ns.any(axis=1)
+        ns[is_zero, 2] = 1
+
     # glTF stores deltas in morph targets
     for ns in morph_normals:
         ns -= normals
````

**Comment by julienduroure** [comment]
Do you plan to open a PR, or do you want me to to it?

**Comment by scurest** [comment]
I can do it.
