### ISSUE TITLE
Appending "images", refence in material extension, through an addon

### ISSUE THREAD

**Issue by VitusW42** [KhronosGroup/glTF-Blender-IO#1140]
I ran into another problem creating an addon that hooks into the Blender glTF exporter. As I'm figuring out how to get my extension inserted into the glTF file (see here: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1135), I'm having some trouble appending the material section.
Some of the extensions I am using are using additional texture maps. They should be referenced by the material extension in this way:
`    "materials": [
        {
            "pbrMetallicRoughness": { "baseColorTexture": { "index": 0 }, "metallicRoughnessTexture": { "index": 1 } },
            "normalTexture": { "index": 2 },
            "occlusionTexture": { "index": 1 },
            "name": "standard_opaque",
            "extensions": {
                "EXT_material_detail_map": {
                    "UVScale": 2.0,
                    "blendThreshold": 0.7,
                    "detailColorTexture": { "index": 3 },
                    "detailNormalTexture": { "index": 4 },
                    "detailMetalRoughAOTexture": { "index": 5 },
                    "blendMaskTexture": { "index": 6 }
                }
            }
        }
`
Essentially, I need to add new texture maps to the "images" section, which are then referenced by number in the extension section of the material.

Any idea how to accomplish that?

**Comment by VitusW42** [comment]
This is still a burning question for me. Any ideas?

**Comment by scurest** [comment]
>  Essentially, I need to add new texture maps to the "images" section, which are then referenced by number in the extension section of the material.

Put a TextureInfo object in your extension. `__traverse` will move the Image/Texture/Sampler to the top-level arrays and replace them with an index.

You can look at how the addon does it, say [here](https://github.com/KhronosGroup/glTF-Blender-IO/blob/6786505ebfda3587f3e735591f7341ec1a5909d3/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials_pbr_metallic_roughness.py#L94).

**Comment by VitusW42** [comment]
Sorry for being so useless, but I can't figure this out.
How do I initialize the TextureInfo object and fill it with life?

```
                         albedo_detail_texture = TextureInfo()
                         my_extension["detail_map"] = albedo_detail_texture
                         gltf2_material.extensions["EXT_material_detail_map"] = self.Extension(
                             name="EXT_material_detail_map",
                             extension=my_extension,
                             required=False
                         )
```

**Comment by scurest** [comment]
The easiest way is to reuse the gather_texture_info function

````py
    def gather_material_hook(self, mat, bmat, export_settings):
        # Find a node named 'FOO' and export the texture from its Color socket
        try:
            foo_node = bmat.node_tree.nodes['FOO']
            inputs = (foo_node.inputs['Color'],)
        except Exception:
            return

        from io_scene_gltf2.blender.exp.gltf2_blender_gather_texture_info import gather_texture_info
        tex_info = gather_texture_info(inputs, export_settings)
        if tex_info is None:
            return

        from io_scene_gltf2.io.com.gltf2_io_extensions import Extension
        mat.extensions['foo'] = Extension(
            'foo',
            {'foo_color': tex_info},
            required=False,
        )
````

If that doesn't work, you just fill out the fields yourself. They match the glTF spec except there's eg. a Texture/Image/Sampler object wherever there would have been an index into the textures/images/samplers array.

You can just keep following the code to see how the fields get filled out by the exporter. [Here](https://github.com/KhronosGroup/glTF-Blender-IO/blob/6786505ebfda3587f3e735591f7341ec1a5909d3/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py#L33)'s where TextureInfo gets filled out, etc.

**Comment by VitusW42** [comment]
That works! Thank you again for your help!

Is there another function that's more direct? I.e. I'd like to pass the texture node directly and get the TextureInfo back?

**Comment by scurest** [comment]
I don't think so, no. You'll have to write one.

**Comment by VitusW42** [comment]
I think I'll pass on that opportunity. Most of the coding in the exporter is way above my head.

**Comment by julienduroure** [comment]
Hello,

You can now include unused images in exported glb file

![image](https://github.com/user-attachments/assets/d7d6c951-4fe0-4e07-8c57-a3dab4d42c04)

If you want to export "texture" data instead of "image" data, the exporter will prepare you the needed data, but as there is no root key in json to add them, you will have to create a hook addon to add them where you want in the file.
See an example here: https://github.com/julienduroure/gltf-hooks-examples/blob/main/gltf_export_unused_textures.py

Closing the (old) ticket, as this is solved now \o/
