### ISSUE TITLE
NodeGroups in Materials are not traversed on export

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#1141]
**Describe the bug**
We have some cases where NodeGroups are reused between objects and where it would be great to directly export GLB files from. However, currently NodeGroups are not traversed (even if they contain just a single BSDF node); not sure if that counts as bug or feature request though.

**To Reproduce**
1. Create monkey
2. Create material
3. Export
3. Wrap BSDF node in NodeGroup (Ctrl + G)
4. Export

**Expected behavior**
Same result for both cases above, NodeGroup is "unrolled" on export to best-guess properties

**Actual behaviour**
Materials with NodeGroup always export as default white material

**Screenshots**
![image](https://user-images.githubusercontent.com/2693840/88293887-df187100-ccfb-11ea-82cf-9a2eaec7c73e.png)

**.blend file/ .gltf**
[GLB-NodeGroup-Issues.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4966295/GLB-NodeGroup-Issues.zip)

**Comment by julienduroure** [comment]
Hello,
Confirmed, this is something not implemented yet, setting as enhancement.
We need to check if there are some API utils to be able to manipulate nodegroup easily

**Comment by pepperoni505** [comment]
Really late to this, but I've made a PR that fixes this issue. #1536

**Comment by julienduroure** [comment]
We forget to close this ticket, as NodeGroups are now managed correctly
