### ISSUE TITLE
Export to older specification of glTF

### ISSUE THREAD

**Issue by McallyD74** [KhronosGroup/glTF-Blender-IO#1143]
I'm trying to use Helixtoolkit.sharpdx in WPF to import glTF models that I exported from blender. I get unhandled exceptions or a blank scene. But I am able to import some of the models from https://github.com/KhronosGroup/glTF-Sample-Models. For instance, the damaged helmet imports just fine. (https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet/glTF-Embedded)

I took a look at the differences between my embedded glTF from blender, and the damaged helmet file, and I see that my export from blender has "Khronos glTF Blender I/O v1.3.30" for a generator, whereas the damaged helmet is declared as "Khronos Blender glTF 2.0 exporter". Additionally, my file is missing the "samplers" block found in the damaged helmet, and the sequencing of the blocks of information in the files are not the same (Idk if that's an issue). I am fairly certain that the file types are using a different specification of glTF.

Helixtoolkit uses assimp.net which is using at least a 5 month old version of assimp, so I'm sure the issue could be fixed by updating assimp.net. But I'm not sure how long it will be till that happens.

Am I off base? Is there an older version of the exporter out there that can export to the same file specification as damaged helmet? the latest compatible with 2.79 addon doesn't seem to work either.

**Comment by julienduroure** [comment]
glTF 2.0 is the specification version
v1.3.30 is the version of the addon (that export  glTF 2.0)

Can you please share any .blend file (and corresponding .glb or .gltf files), to be able to understand your issue more precisely?
Thanks!

**Comment by McallyD74** [comment]
Thank you for your help! I noticed the damaged helmet file has separate buffers for image textures, whereas my file references a byte offset in a single buffer that contains the model data as well. I don't know much about glTF, is there some sort of logic involved with determining the buffer arrangement?

Here is a file of mine exported via the v1.3.30 exporter to embedded glTF:
https://drive.google.com/file/d/1t1oNSe4mdU3sluysDOvNagDM_ssbzOR-/view?usp=sharing

Here is the same file exported using the current v1.4.1 exporter:
https://drive.google.com/file/d/109g9JFVAN8Fr_9r4bsXvKt_tLxViNVT9/view?usp=sharing

And while it's not directly relevant, here is a zip containing a compiled example of a file loader "FileLoadDemo" based on assimp.net which treats is happy with the example models from Khronos Group, but dislikes anything I export:
https://ci.appveyor.com/api/buildjobs/dub1oovx0n06f4r9/artifacts/Source%2Fdist-examples%2FHelixToolkit-Examples-WPF-SharpDX-2.13.0-alpha.51.zip

**Comment by donmccurdy** [comment]
> I noticed the damaged helmet file has separate buffers for image textures, whereas my file references a byte offset in a single buffer that contains the model data as well. I don't know much about glTF, is there some sort of logic involved with determining the buffer arrangement?

Either is acceptable in the current version of glTF (v2.0), but most files have only a single buffer.

The glTF file exported by v1.4.1 is completely valid according to https://github.khronos.org/glTF-Validator/, and works correctly in https://gltf-viewer.donmccurdy.com/ and https://sandbox.babylonjs.com/. If you aren't able to load the file in other tools, I think you may need to report a bug on those tools — the model itself is OK.

Possibly related: there's some _very_ dense geometry at a few points in this model, which increases the size a lot but isn't adding any visual detail. The screenshot below is in wireframe mode, and note how these meshes look completely solid:

![Screen Shot 2020-07-26 at 5 24 00 PM](https://user-images.githubusercontent.com/1848368/88493262-0625ab80-cf65-11ea-839e-de8284e2b715.png)

Simplifying those meshes may help some tools, or would at minimum reduce the size of the file. :)

**Comment by McallyD74** [comment]
Thanks for the insight, I was really hoping I had made a silly mistake somewhere, I was afraid of it being an issue with the toolkit. I've tried several attempts with lowpoly meshes ( even just cube) but had no luck. Oh well. Thank you guys for putting in all the effort you do to make the exporter for us!

**Comment by julienduroure** [comment]
Seems we answer the question. Can this ticket be closed?
