### ISSUE TITLE
Specular on export is always 0.5

### ISSUE THREAD

**Issue by wkeisari** [KhronosGroup/glTF-Blender-IO#1145]
When I export a model, specular value is always 0.5, no matter what is set in the material setting. This results always a bit shiny material. Same result with Babylon.js sandbox and when the model is imported back to Blender.

Windows 10, Blender 2.83.3

**Comment by julienduroure** [comment]
Hello,
glTF 2.0 use Metallic / Roughness PBR values, so there is no specular data directly in glTF file.
Can you please share a .blend file and corresponding .glb or .gltf file, as requested in issue template?
Thanks

**Comment by fire** [comment]
The gltf2 specification does not define PBR specular (1 channel). It could be an extension, but it's not required to be implemented.

**Comment by wkeisari** [comment]
Thanks, I think I get it now. I'm coming from "traditional" materials, so PBR is a bit new to me. So I need to set roughness to 1, if I want to get completely matte material.

**Comment by julienduroure** [comment]
Seems we answer the question. Can this ticket be closed?

**Comment by kokotron** [comment]
This is kind of relevant: While "specular" doesn't exist in gltf metallic workflow, in BabylonJS PBR material's metalic workflow there are a couple of values that directly affect the specular effect. They are "F0 Factor" and "indexOfRefraction". But changing the ior in blender's principled shader has no effect in the exported gltf ior. Maybe connecting these would help?

**Comment by julienduroure** [comment]
Hello,
See #1646 
This is currently in development
