### ISSUE TITLE
Pre-apply subdivision modifiers on export

### ISSUE THREAD

**Issue by Peach1** [KhronosGroup/glTF-Blender-IO#1149]
The GLTF exporter requires the user to manually apply subdivision before export,
but Blender's obj and fbx exporter applies subdivision modifiers on export by default.

This is a huge workflow benefit for iteration,
you can do easy edits without extra steps.

How can this exporter pre-apply modifiers like subdivision on export?

**Comment by scurest** [comment]
Turn on "Geometry > Apply Modifiers" in the export options.

The same option exists for FBX/OBJ, but they have it on by default. Being consistent would be nice...

**Comment by julienduroure** [comment]
Maybe we can considerate to activate "Apply Modifiers" by default, like in other exporters... (even if this break shapekeys)

**Comment by julienduroure** [comment]
Closing this (old) ticket, as there is no bug here.
All default values will be discussed with Khronos & Blender devs
