### ISSUE TITLE
Discussion: for skinning, verts not assigned to a bone are exported wrong

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1151]
In Blender, vertices that aren't assigned to any bones act as if they weren't skinned. In glTF however, every vert needs to be assigned to at least one bone. Currently these verts are being exported with zero weights, which is invalid. #1150 adds a stopgap against invalid files by assigning them to the 0th joint, but doesn't fix the real issue.

[UnassignedVertTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4989214/UnassignedVertTest.zip)

![cc](https://user-images.githubusercontent.com/11024420/88684337-5bbf9c80-d0ba-11ea-8122-f77e690bdc61.png)

^^^ The two lower verts on the quad are unassigned.

### Solution

To really fix this, we need to insert a new bone into the armature at the root with the default TRS. Any vert assigned to this bone would act as if it weren't skinned, so let's provisionally call this a "neutral bone". Then we just need to treat unassigned verts as if they were assigned to the neutral bone.

![dd](https://user-images.githubusercontent.com/11024420/88685701-d5a45580-d0bb-11ea-9f63-16ac1387d13b.png)

We also only want to insert the neutral bone when necessary, ie. when there are unassigned verts.

### Alternatives

I believe this (or minor variations on this) are the only possible solution. We obviously need a new bone to assign these verts to. The only real variation is where to put the neutral bone (as a new root of all the other bone trees, as the root of a new parallel one-bone tree).

We could also try to detect if an existing bone could serve as the neutral bone. This would be nice because files that happened to be fixed by #1150 like the tree from #308 wouldn't need to get a new bone. It's kind of ambitious though, so maybe a future enhancement.

The other thing we could do is declare this unsupported and print a warning for unassigned verts. We could probably avoid the warning in some cases (again, assuming we can detect an existing neutral bone). This is nice because its simpler.

**Comment by scurest** [comment]
So, how to actually implement the solution?

I have a branch with a prototype: [`neutral-bones`](https://github.com/KhronosGroup/glTF-Blender-IO/compare/6786505...scurest:neutral-bones)

The implementation is kind of strange though.

We find out if we need a neutral bone in extract_primitive. We can't add the neutral bone there though, so we just put a mark (`__needs_neutral_bone`) on the skin that we needed it and go ahead and act if it were there.

Then after a whole scene has been collected, we make a second pass over the nodes with add_neutral_bones_to_node_tree. It looks for skins with that mark and their armature nodes. Then it creates a new Node for the neutral bone, inserts it into the arma node's child list, inserts it into the skin's joint list, and adds a new inverse bind matrix for it to the skin.

This is kinda unusual and nothing else in the exporter works like this, but I can't really think of how else to do it.

What does everyone think?

**Comment by julienduroure** [comment]
Approve #1150 for 2.90, and let's discuss the solution for 2.91
Your solution about creating a neutral bone when needed was what I had in mind when discussing #308, so let's go with this solution.
I will test your prototype soon. Thanks!

**Comment by fire** [comment]
Poke. What is the status of this?

**Comment by scurest** [comment]
I'm not planning on working on this.

**Comment by scurest** [comment]
Think it would be better to add the armature node to the skin.joints array as the "neutral bone" (when necessary) and not add a new node. But I have no idea how to do this because the gather_node code is so incredibly convoluted.

**Comment by fire** [comment]
@julienduroure Can you prioritize this? I guess for 3.2? I don't know the roadmap.
