### ISSUE TITLE
What happened to "Selected Objects"

### ISSUE THREAD

**Issue by VitusW42** [KhronosGroup/glTF-Blender-IO#1154]
Hi folks,

I was wondering why there is no "selected objects" export option in the Khronos exporter. It's a feature that I find absolutely essential and yet, it seems to be missing in the current version. I often need to check out just some aspects of my model and ordinarily, I would just select what I need to inspect and export those parts.

What's the reason for that? What would I need to do to get that feature into the exporter?

**Comment by donmccurdy** [comment]
It should still be there, see https://github.com/KhronosGroup/glTF-Blender-IO/blob/6786505ebfda3587f3e735591f7341ec1a5909d3/addons/io_scene_gltf2/__init__.py#L225. What version of Blender are you using where you don't see it? Are you using the default Exporter addon from that version, or have you reinstalled a newer version from this repository?

**Comment by VitusW42** [comment]
> Are you using the default Exporter addon from that version, or have you reinstalled a newer version from this repository?

Both. I am using Blender 2.83 and the exporter that comes with it doesn't have this option available. I also had to fork the version here on gitHub to enable [asset extensions](https://github.com/KhronosGroup/glTF-Blender-IO/pull/1146).

It's the same for both of those:
![image](https://user-images.githubusercontent.com/68594560/88963427-1cef3980-d2a8-11ea-9340-616166b4c860.png)

**Comment by donmccurdy** [comment]
The option should be under the *Include* dropdown – it looks like nothing at all is appearing there for you?

**Comment by VitusW42** [comment]
Ooooh man... I know what it is and now I feel really stupid.

I am using Blender 2.83, but I got the repository for 2.9x. One of the changes that came with the 2.90 API is that the layout.col() is now taking 2 parameters - heading and align. The whole column wasn't drawn, because of this change.

Now I have to figure out why the default glTF exporter still seem to take its __init__.py from my module.... 

Thank you Don for all your great work here!

**Comment by donmccurdy** [comment]
Good to know that's the issue! A fresh download of 2.83 (with the stock exporter) does work OK for me. Blender 2.9x will be available soon so hopefully the confusion is minimal after that. :)
