### ISSUE TITLE
Questions about roundtrip tests

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1156]
What's the reason for the validator reports being checked into this repo? Versus generating a report for both the original and roundtripped file at test time.

Also, is there a way to run just a specific test?

**Comment by emackey** [comment]
Validation reports fixed in #1168.

I don't know of a way to run a test just on a specific model, but that would be a nice feature to add.

**Comment by emackey** [comment]
Oh I stand corrected!  The `-g` flag works on model names.

```
$ ./node_modules/.bin/mocha -b --reporter mochawesome -g metallic


  Exporter
    blender_export
      01_metallic_sphere (670ms)
      05_metallic_sphere_light (619ms)
    blender_export_glb
      01_metallic_sphere (590ms)
      05_metallic_sphere_light (623ms)

  Importer / Exporter (Roundtrip)
    blender_roundtrip
      01_metallic_sphere (597ms)
      05_metallic_sphere_light (645ms)
    blender_roundtrip_glb
      01_metallic_sphere (474ms)
      05_metallic_sphere_light (593ms)

```

**Comment by scurest** [comment]
Cool, thanks!
