### ISSUE TITLE
Axis confusion, breaking specification

### ISSUE THREAD

**Issue by jaw** [KhronosGroup/glTF-Blender-IO#1171]
**Describe the bug**
According to the gltf spec, what is put in Y should be what is percieved as "Up". 
Right now blender's notion of XYZ is used which is not correct.
What blender considers to be "Up" should remain so; so that viewport view from "Front" "Left", "Top" etc still works and the artists does not have to rotate in blender.

When this is fixed:
The "+Y Up" checkbox  should be removed and all axes set according to the specification.

But right now, the "+Y Up" option is has at least the following bugs:
- inverse bind matrices are not rotated making the mesh turn into triangle soup
- translated point lights get an unnecesarry parent/child relation where translation and rotation is split between the 2 gltf nodes
- the mesh data is rotated, but the translations of objects (in gltf nodes) does not get translated

This, forgive my assumption, looks (without looking at the code) as a clear example of regressions caused by having too much stuff to maintain. If that is the case, removing the code path and simlpifying will also make it easier to maintain and extend.

**To Reproduce**
I'll be more than happy to show devs over screen share what is wrong.
The test files are rather big and proprietary so don't want to share.

Here is my list of things that need rotation (some already do):
- for all nodes:
  - transforms:
    - rotation
    - translation
    - scale
    - matrix
- for all meshes
  - primitives: 
    - position
    - normal
    - tangents
    - joints
- for all skins:
  - all inverse bind matrices
- for all animation samplers:
  - translation
  - rotation 
  - scale

There could be more things to rotate also, only extension I've implemented is the lights one.

**Expected behavior**
The plugin should deliver files that follow the specification.

**Version**
 - Blender 2.83

I'd love to help out fixing this, but probably need someone to collaborate with who knows the code and Python better than I do.

**Comment by donmccurdy** [comment]
Are you able to create (smaller, non-proprietary) `.blend` files that still reproduce the issues you're seeing? 

We expect that models are correctly converted from Blender's +Z Up to glTF's +Y Up at export, when the +Y Up is enabled (and it should usually be enabled). This has been tested with skinned mesh data as well, so if you have skinned mesh data that "turn into triangle soup" we will need examples to test.

The +Y=Up checkbox exists because that conversion is complex, and we want people to have the option of disabling it for debugging purposes.

**Comment by jaw** [comment]
Here's one (the 2nd bug in my listing).

If you compare the light nodes, I'd expect just the xyz of the translation of the nodes to be shifted around. Not a node tree being created for the light. The file contains with and without +y up.
[gltf_weird_light_transform_tree.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5037847/gltf_weird_light_transform_tree.zip)

**Comment by scurest** [comment]
If you're talking about the `_Orientation` nodes, the reason they exist is to correct for the different conventions of the direction lights/cameras point, see #604 

...Although for point lights specifically that's not actually necessary since they emit light uniformly in all directions.

**Comment by jaw** [comment]
The direction is a vector, if said vector is rotated it can still be just a vector?

**Comment by scurest** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/issues/604#issuecomment-517387307

**Comment by jaw** [comment]
Right, but why only when "+Y Up" is  selected?

**Comment by scurest** [comment]
In Blender a (say) spot light points along the (Blender -Z) axis.  
In glTF a spot light points along the (glTF -Z) axis.

When "+Y Up" is off, (Blender -Z) = (glTF -Z) so the conventions match and we don't need to change.
But when it's on, (Blender -Z) = (glTF -Y) so the conventions don't match and we need to insert a correction.

**Comment by jaw** [comment]
Did a new test of exporting a character, inverse bind matrices seem OK and lighting works well when following the node matrix stack. Closing this issue for now.
