### ISSUE TITLE
Bake shape keys controlled by drivers?

### ISSUE THREAD

**Issue by will-ca** [KhronosGroup/glTF-Blender-IO#1178]
I believe it's fairly common and pretty useful to have shape keys animated via drivers tied to armature bones' transforms.

When this is the case, the NLA tracks corresponding to the shape key are those of the armature, not those of the shape key itself.

From a quick test in Blender 2.83.4, it doesn't seem that the shape key's animations get exported usefully in this case.

**Comment by julienduroure** [comment]
Hello,

Please provide a test case in order to check.
The only case that _should_ be taken into account for now is shapekey driven by a bone transformation from an armature that deforms the mesh, where the armature is parent of the mesh.

**Comment by will-ca** [comment]
@julienduroure 

Ah, cool. Setting a parenting relationship to the armature seems to make it work perfectly.

My test case file just didn't have any parenting, modifier, or any kind of dependency relationship between the armature and the mesh aside from the shape key, but let me know if I should still post it.

**Comment by julienduroure** [comment]
Well, seems you can export properly. Closing the ticket.
Thanks !

**Comment by will-ca** [comment]
Hm. For future reference for anyone finding this, it seems to work even when the armature doesn't deform the mesh, as long the armature is the parent of the mesh— I.E., with "Parent" set, but with "Parent Type" set to "Object" and with no Armature modifier.
