### ISSUE TITLE
Process for contributing

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#118]
Now that this addon is in the Blender 2.8 beta (🎊🎊🎊), I'm not sure how to develop against the GitHub repository. The addon folder created by Blender 2.8 seems to be readonly, and on my work computer I cannot remove it. At the moment I am:

1. Copy GitHub folder to a folder with a different name, 'io_scene_gltf2_custom'
2. Edit `__init__.py` and give a different name than the existing addon.

Is there a better way to contribute? Just disabling the official extension doesn't seem to do it. We should probably add this to the documentation for would-be external contributors.

**Comment by donmccurdy** [comment]
Hm, unfortunately the steps above aren't working for me well — when making changes, it seems like the official code is still interfering, even though the addon is disabled.

**Comment by UX3D-nopper** [comment]
In Blender 2.8 - for developers - first I completely delete the current glTF I/O scripts. Then, like before, I point to the Khronos GitHub repository.

**Comment by donmccurdy** [comment]
Ok, I was able to get this working on my personal machine at least. Will write up some docs for contributors later.

**Comment by donmccurdy** [comment]
Ed's documentation in https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/DEBUGGING.md is great. Closing this issue.
