### ISSUE TITLE
Child of bone with zero scale at rest pose doesn't get exported visibly?

### ISSUE THREAD

**Issue by will-ca** [KhronosGroup/glTF-Blender-IO#1181]
**Describe the bug**
In a Blender file with one armature containing one bone and a mesh object which is a child of that bone, the mesh object does not get exported correctly if the export is run while the active NLA track has the bone at zero scale.

Distinct from #1087, I think, because the export does run correctly and the file does contain most of the expected data— I think something's just wrong with the transforms in it?

**To Reproduce**
1. Get a fresh file.
2. Delete everything.
3. Add an armature.
4. Add a Suzanne.
5. Parent the Suzanne to the armature's single bone.
6. Create an NLA track on the armature pose with bone scale keyframes and no changes.
7. Create a second NLA track on the armature pose with the bone at zero scale.
8. Solo the second NLA track on the armature pose with the bone at zero scale.
9. Export with default settings.

###### (Zero-scale state at export.)
![image](https://user-images.githubusercontent.com/37680486/90223163-13fc7d00-ddfd-11ea-8d9d-c8096ed12d3b.png)

###### (Default-scale NLA.)
![image](https://user-images.githubusercontent.com/37680486/90223185-19f25e00-ddfd-11ea-8acd-845f1de09357.png)

**Expected behavior**
The mesh object is invisible in the zero-scale animation and visible in the one-scale animation, like when the export is run from the default-scale state:

![image](https://user-images.githubusercontent.com/37680486/90223270-460ddf00-ddfd-11ea-8779-d5716a61ba44.png)
![image](https://user-images.githubusercontent.com/37680486/90223276-49a16600-ddfd-11ea-80c1-cae6ed076dff.png)

**Observed behaviour**
The mesh is invisible in both animations:

![image](https://user-images.githubusercontent.com/37680486/90223284-4e661a00-ddfd-11ea-8343-fcdc50736fe1.png)
![image](https://user-images.githubusercontent.com/37680486/90223290-502fdd80-ddfd-11ea-885f-a5c4fff21a1a.png)

**.blend file/ .gltf**
`.blend` file.
[GLTF_ZEROVIS.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5073132/GLTF_ZEROVIS.blend.zip)

`.gltf` export from zero-scale NLA (failure case).
[GLTF_ZEROVIS.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5073134/GLTF_ZEROVIS.gltf.zip)

`.gltf` export from default-scale NLA (working case).
[GLTF_ONEVIS.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5073135/GLTF_ONEVIS.gltf.zip)

**Version**
 - Blender Version 2.83.4.
 - `three.js` r116.

**Additional context**
Does GLTF store bone orientation separately from head and tail position?

I encountered this while trying to make a smaller reproducer for a similar apparent issue where the child meshes are visible but have wrong rotations.

**Comment by scurest** [comment]
Are you sure the Three.js viewer just isn't centering the camera wrong? You can test it by sticking some Cube nearby in the scene to use as a reference.

If I add a cube to your .blend and export I get this

![v](https://user-images.githubusercontent.com/11024420/90224902-07186300-ddd6-11ea-9413-cf937b0ba93c.png)

**Comment by will-ca** [comment]
@scurest

Ah, oops. 😅

In my defence, I was trying to narrow down another apparent issue that seems to happen with zero-scale bones (where rotation rather than visibility gets messed up), so I figured broken visibility might be a special case that happens when there's nothing else in the scene. Although, I probably should have at least opened the exported file in Blender to double-check that something was wrong.
