### ISSUE TITLE
Export/UI: "Animation" section of export screen should be reorganized

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1189]
The "Animation" panel when exporting looks like this

![animpanel](https://user-images.githubusercontent.com/11024420/91360922-ef20e600-e7bc-11ea-8e79-845b50621c05.png)

Shape keys and skinning have nothing to do with animation so they shouldn't be under the "Animation" section. And having a subsection of "Animation" that is also named "Animation" is dumb.

**Comment by donmccurdy** [comment]
How about a new "Armatures" section, and moving Shape Keys under "Geometry" section? On that note, I think the Materials/Images options might make more sense under "Include" than "Geometry".

**Comment by scurest** [comment]
Mockup:
![out](https://user-images.githubusercontent.com/11024420/91375970-a6c7ef00-e7e1-11ea-97b7-364ded42e35f.png)

**Comment by scurest** [comment]
What does "Use Current Frame" do?

**Comment by donmccurdy** [comment]
The mockup looks great to me. :)

**Comment by julienduroure** [comment]
Not sure about "Export Deformation bone only", if this should be in Animation or in Armature
