### ISSUE TITLE
Export/UI: turn on "Include Cameras" and "Include Lights" by default?

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1190]
Is there a reason these are off by default? They are enabled by default for FBX and I don't think Collada even has an option not to export them.

**Comment by emackey** [comment]
In the case of lights, they depend on a glTF extension that's not well-supported yet (outside of Blender).  In general I'd like there to be no use of extensions unless the user takes some action (such as adding a clearcoat layer, or checking a box) that requires it.

Cameras are also not common in the glTF ecosystem, although they at least are a core feature of the format.  Even so, I'd prefer not to see a bunch of default lights/cameras entering the glTF ecosystem.  Blender includes them in the default scene automatically, and I'm sure I'm not the only one who ignores them while building a model for glTF.  I fear we'd end up with a bunch of un-edited Blender-default lights and cameras strewn across glTFs in the wild, without any action on the part of the user to request them.  So for me at least, I'd prefer to keep them as opt-in.

**Comment by emackey** [comment]
One more angle to consider: glTF is a delivery format, while these others (FBX, Collada, USD) are interchange formats.  In an interchange format, you want to preserve as many details as possible between two different parts of the content creation pipeline.  But for glTF, it's the last-mile format, and you want to make sure the exported model is ready for shipment to clients and end users.

So it may be fine for lights/cameras to be along for the ride during interchange, but the user should take some care in shipping such things to an end user application.

**Comment by scurest** [comment]
Ok.
