### ISSUE TITLE
Rotating a node in the glTF

### ISSUE THREAD

**Issue by VitusW42** [KhronosGroup/glTF-Blender-IO#1191]
Hello again,

I have a little problem exporting lights. The engine I export to, requires an extension to define parameters of a light and it's using the "nodes" node for the positioning. Unfortunately, it looks like it has a different convention when it comes to the direction of the lightsource. The spotlight gets rotated -90 degrees around the z axis.
I figured the easiest way to fix that is by manipulating the transform of the light-node when it gets written into the glTF file. My question is which function is responsible for this? I.e. which exporter function do I need to change to rotate my spotlights back 90 degrees?

**Comment by scurest** [comment]
It's pretty easy to find out where the exporter writes stuff. Look in the [blender/exp](https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/addons/io_scene_gltf2/blender/exp) folder. The file that makes Xs is usually going to be named gltf2_blender_gather_X.py. You're looking for a node's rotation property, so look in [gltf2_blender_gather_nodes.py](https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py) and grep for "rotation".

Note that lights are written with [two nodes](https://github.com/KhronosGroup/glTF-Blender-IO/blob/fdce5bcf687f3d0dd9b0ec5a4e74faf9f267745c/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py#L81) to correct for the different convention in which way they point in Blender vs glTF.

**Comment by VitusW42** [comment]
Thanks, I'll have a look!
Unfortunately I can't use the light routine out-if-the-box - it seems that the nesting of the light-node in another node is not compatible with the engine I work with.

**Comment by VitusW42** [comment]
Yep, that did the trick! Thanks a lot!
