### ISSUE TITLE
GLTF Exporter: Index data should be in a separate buffer to vertex data

### ISSUE THREAD

**Issue by rishflab** [KhronosGroup/glTF-Blender-IO#1193]
**Is your feature request related to a problem? Please describe.**
I want to load gtlf scene/model data to render using Vulkan. Vulkan distinguishes between index and vertex buffers but blender concatenates the index and vertex data. This means I have to do a bunch of clunky operations to extract the index data so I can load it into a index buffer and the vertex data into a vertex buffer.

**Describe the solution you'd like**
It would be great if blender produced gtlf files where the index data was in a seperate buffer to the vertex data. This makes it really easy to load a model into gpu memory as the buffers specified in the gtlf match the layout in gpu memory. 

Example gtlf showing how the index and vertex data should be exported as seperate buffers:

```
 "meshes" : [
        {
            "name" : "Cube",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2
                    },
                    "indices" : 3,
                    "material" : 0
                }
            ]
        }
    ],
    "accessors" : [
        {
            "bufferView" : 0,
            "componentType" : 5126,
            "count" : 24,
            "max" : [
                1,
                1,
                1
            ],
            "min" : [
                -1,
                -1,
                -1
            ],
            "type" : "VEC3"
        },
        {
            "bufferView" : 1,
            "componentType" : 5126,
            "count" : 24,
            "type" : "VEC3"
        },
        {
            "bufferView" : 2,
            "componentType" : 5126,
            "count" : 24,
            "type" : "VEC2"
        },
        {
            "bufferView" : 3,
            "componentType" : 5123,
            "count" : 36,
            "type" : "SCALAR"
        }
    ],
    "bufferViews" : [
        {
            "buffer" : 0,
            "byteLength" : 288,
            "byteOffset" : 0
        },
        {
            "buffer" : 0,
            "byteLength" : 288,
            "byteOffset" : 288
        },
        {
            "buffer" : 0,
            "byteLength" : 192,
            "byteOffset" : 576
        },
        {
            "buffer" : 1,
            "byteLength" : 72,
            "byteOffset" : 0
        }
    ],
    "buffers" : [
        {
            "byteLength" : 768,
            "uri" : "cube_vertices.bin"
        },
        {
            "byteLength" : 72,
            "uri" : "cube_indices.bin"
        }
    ]

```

**Comment by donmccurdy** [comment]
Hi @rishflab, thanks for this suggestion. The glTF spec requires that index data be written to a separate _buffer view_ from the vertex data, to assist with cases like you describe, but not a separate _buffer_. Is using the buffer view workable for the Vulkan loader you're trying to create? 

I think that writing those separate buffers is probably too low-level of a setting to include on this exporter — the three export settings we have (.glb, .gltf, and .gltf + .bin + .textures) already create confusion sometimes. But it would be fairly easy to write a post-processing script that reformats the buffers in the way you want. For example, using Node.js:

```js
const fs = require('fs');
const path = require('path');
const { NodeIO } = require('@gltf-transform/core');

// Read file.
const io = new NodeIO(fs, path);
const doc = io.read('input.glb');

// Create a 2nd buffer to store indices.
const indexBuffer = doc.createBuffer('IndexBuffer').setURI('indices.bin');

// Move indices to 2nd buffer.
for (const mesh of doc.getRoot().listMeshes()) {
  for (const prim of mesh.listPrimitives()) {
    prim.getIndices().setBuffer(indexBuffer);
  }
}

// Write file.
io.write('output.gltf', doc);
```

**Comment by rishflab** [comment]
> Hi @rishflab, thanks for this suggestion. The glTF spec requires that index data be written to a separate _buffer view_ from the vertex data, to assist with cases like you describe, but not a separate _buffer_. Is using the buffer view workable for the Vulkan loader you're trying to create?
> 

Yes, that is what I am doing at the moment. I thought it was a bit strange that the glTF files didn't split the buffers my default given that most renderering engines would like it split. After further reading it seems like glTF is not really meant to be that sort of a format. It seems like most users create their own engine specific format from the glTF file.

Thanks for the response.

**Comment by donmccurdy** [comment]
>  I thought it was a bit strange that the glTF files didn't split the buffers my default given that most renderering engines would like it split. 

The bufferView, not the buffer, is the unit of organization you're looking for here. Additional buffers create additional files on disk, which has more to do with resource transmission than rendering engine mesh layouts.
