### ISSUE TITLE
2.90 release notes missing glTF header

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#1196]
https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/IO

^the glTF release notes are there, but as a subheader under "Instances", so they don't appear in the table of contents. Is that easy to fix? I can't seem to sign in to the wiki with my developer account. :/

**Comment by julienduroure** [comment]
Fixed!
Thanks :)

**Comment by donmccurdy** [comment]
Thank you!
