### ISSUE TITLE
Add support for KHR_materials_sheen

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#1197]
The spec for [KHR_materials_sheen](https://github.com/KhronosGroup/glTF/pull/1688) is nearing completion, and could use Blender import and export implementations.

**Comment by shaykh-qasim** [comment]
> The spec for [KHR_materials_sheen](https://github.com/KhronosGroup/glTF/pull/1688) is nearing completion, and could use Blender import and export implementations.

Hi, is the sheen from blender now supported in GLTF import export? I am not related with coding/webgl but I have a project where a velvet shader is to be used in GLTF, I searched and saw ur post from Nov 2019 where u added KHR_materials_sheen extension manually in GLTF using json pretty, but I am still having a problem, I want to use the sheen tint as well and control the roughness of sheen. How can I do all of it directly from blender nodes and no need for manually editing GLTF

**Comment by shaykh-qasim** [comment]
Plus, I also want to control the sheen intensity, I may want to overuse it as well as it is currently very weak in brightness and colour.
Also, can you please explain the process to be in a beginner-friendly method.

**Comment by emackey** [comment]
Hi @shaykh-qasim, the sheen extension for glTF is believed to be stable now, but not yet implemented in Blender.  This issue is to track the feature request for implementing it.  We do rely on outside contributions, so there's no firm roadmap for when this might become available.

**Comment by shaykh-qasim** [comment]
> Hi @shaykh-qasim, the sheen extension for glTF is believed to be stable now, but not yet implemented in Blender. This issue is to track the feature request for implementing it. We do rely on outside contributions, so there's no firm roadmap for when this might become available.

Thanks for the update, I have managed to create the shader thanks to you. I have to report one issue, or I don't know whether it is an issue or something else:

When I input the sheenColorFactor values as 

"sheenColorFactor": [0.1, 0.4, 1] 

It does not correctly transfer the RGB value to Babylon, the value changes to some other parameters, I manually eye-balled and adjusted the value to match with the Babylon one for my velvet model, just wanted to bring this into your notice if this is a bug or something.

**Comment by emackey** [comment]
All of glTF's color factors are expressed in linear space, not sRGB.  You might need a [color conversion](https://github.com/KhronosGroup/glTF-Blender-IO/blob/27bb8521cd5bb2b1e3e76eef4db701d3126ee57d/addons/io_scene_gltf2/io/com/gltf2_io_color_management.py#L16-L25).

**Comment by shaykh-qasim** [comment]
> All of glTF's color factors are expressed in linear space, not sRGB. You might need a [color conversion](https://github.com/KhronosGroup/glTF-Blender-IO/blob/27bb8521cd5bb2b1e3e76eef4db701d3126ee57d/addons/io_scene_gltf2/io/com/gltf2_io_color_management.py#L16-L25).

Hi, How do I control the SHEEN INTENSITY from GLTF? I see there is a factor for controlling roughness and colour but I can't control the intensity, how do I do that? 
![image](https://user-images.githubusercontent.com/57045910/97086018-554dac00-163a-11eb-8e33-4507e6ce8ae0.png)

Here I have tried to use this factor, which is not working : 
![image](https://user-images.githubusercontent.com/57045910/97086067-8f1eb280-163a-11eb-82e7-d7bbd625783a.png)


Thanks,

**Comment by emackey** [comment]
Hi @shaykh-qasim, this GitHub issue tracker isn't really the right place for tech support, it's reserved for tracking bugs and features in the Blender glTF addon.

That said, the glTF sheen extension doesn't separate out the intensity, it's blended with sheenColor.  Darker colors are the same as lighter colors with less intensity.  A sheenColor of black (the default) disables the sheen effect completely, as no light is returned from the sheen.

**Comment by shaykh-qasim** [comment]
@emackey Sorry for commenting here, I am new to GitHub and don't know where and how to post. Can you link me to a specific forum for GLTF tech support?

That being said, I have a query of using video/gif/image sequence as textures/material in GLTF, do you know or can you link me to a related solution?

Thanks again and sorry for commenting here as I don't know where else to post.

**Comment by donmccurdy** [comment]
The glTF forums (https://community.khronos.org/c/gltf-general/45) or Slack (https://khr.io/slack) are good options for technical support.

**Comment by julienduroure** [comment]
Well, seems I forgot to close this ticket, now that sheen is supported... 
Closing
