### ISSUE TITLE
Noise with Principled BSDF exports to blank material.

### ISSUE THREAD

**Issue by FrankenApps** [KhronosGroup/glTF-Blender-IO#1200]
**Describe the bug**
The material is blank / white.

**To Reproduce**
With any such Node layout:
![sc](https://user-images.githubusercontent.com/17967303/92576093-6492b900-f289-11ea-9c2f-664a94241bd5.png)

**Expected behavior**
The material should look like in blender.

**.blend file/ .gltf**
[sample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5193837/sample.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.90

**Additional context**
I know the goal of this project is not to support any possible material, but the goal is to maybe at least support Principled BSDF? If not, the Issue can be closed.

**Comment by emackey** [comment]
Hi @FrankenApps,

The glTF format offers specific PBR material properties, but not a system of arbitrary shader nodes.  It's intended to be a runtime format, supplying ready-to-render textures that are easy to use even on mobile devices.

Blender offers a Bake tool that can take a node graph like this and convert it to a final, baked texture that can be shipped as part of a glTF file.  There's a [video tutorial](https://www.youtube.com/watch?v=TNE3z424YpM&list=PLvdhJ__UbhZ6mst0xgd_S3oSmdRcEiKCp&index=7&t=989s) on the topic.

For reference, the [Blender Manual](https://docs.blender.org/manual/en/2.90/addons/import_export/scene_gltf2.html) describes glTF material output properties in detail.
