### ISSUE TITLE
Der macht super quatsch !

### ISSUE THREAD

**Issue by LorenzWieseke** [KhronosGroup/glTF-Blender-IO#1203]
Hab den Master midder 1.4.22 probiert, aba der macht echt super quatsch, Alles licht irjendwo rum un s file is och viel größer als vorher. Junge, das jeht jahrniche !

Un jez is o noch so e rechtes viereck da wenn ich of export drücke, das jeht erst weg wemma mit dor maus übern outliner hoovert.

**Comment by LorenzWieseke** [comment]
Scheiße is das

**Comment by LorenzWieseke** [comment]
ach ja un dann kommt och noch der mist hier wenn ich so kurven drinne hab
![image](https://user-images.githubusercontent.com/29607121/92925299-97c87a00-f43a-11ea-8b9d-977f18ba6754.png)

**Comment by LorenzWieseke** [comment]
das versteht keen mensch

**Comment by LorenzWieseke** [comment]
![image](https://user-images.githubusercontent.com/29607121/92926760-d19a8000-f43c-11ea-96b3-29ab624a61db.png)

**Comment by scurest** [comment]
Need a .blend to debug.

About the mouse turning into a black square: I noticed that with the OBJ addon too, it's reported in [T80656](https://developer.blender.org/T80656). Maybe we could see if that gets patched and then do the same thing here.

**Comment by julienduroure** [comment]
As requested by scurest, please provide the .blend, it will help!
To be sure to have a smooth support, can you please write in English? We are an international team :)

**Comment by LorenzWieseke** [comment]
[
[Spline_Bug_Report.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5214079/Spline_Bug_Report.zip)

](url)

**Comment by julienduroure** [comment]
Seems to be solved by #1378

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
