### ISSUE TITLE
Add ability to export meshes with defined but empty material slots

### ISSUE THREAD

**Issue by samdze** [KhronosGroup/glTF-Blender-IO#1205]
**Is your feature request related to a problem? Please describe.**
I can't properly configure my meshes in Godot when I export them from Blender without materials.

**Describe the solution you'd like**
An option to export empty placeholder material slots instead of the real ones would be the perfect solution.
I could then populate those slots properly with my customized Godot materials later on.

**Describe alternatives you've considered**
Other alternatives would require Godot doing the work of discarding real materials and only keeping the slots.
But I see this feature in the Blender exporter better.

**Comment by julienduroure** [comment]
This is an interesting enhancement.
#1206 can do the job

**Comment by mindinsomnia** [comment]
I'm currently developing a web based 3D product customisation system and this would be a great enhancement for me too, currently I have to use grey materials as placeholders to keep material slots in place.
