### ISSUE TITLE
"NoneType" error in lights export code

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#121]
When trying to export a default scene, with the `Punctual Lights` option _disabled_, I get the following error:

![screen shot 2018-12-01 at 4 35 56 pm](https://user-images.githubusercontent.com/1848368/49334319-d2c02d00-f587-11e8-954c-e10184c9e6bd.png)

Testing current master branch.

**Comment by UX3D-nopper** [comment]
Fixe here:
https://github.com/KhronosGroup/glTF-Blender-IO/commit/422b15b835f5a63b7c76377d78a87972f7ebd86b

**Comment by donmccurdy** [comment]
Thanks!
