### ISSUE TITLE
Text not exported correctly

### ISSUE THREAD

**Issue by LorenzWieseke** [KhronosGroup/glTF-Blender-IO#1210]
**Describe the bug**
Exporting text objects that are parented to an empty get exported weirdly. Some are transformed, some left out on export.
I think the transforms should be applied before exporting.

**Expected behavior**
Blender Scene and Three.js viewer shoul produce the same outcome.

**Screenshots**
![image](https://user-images.githubusercontent.com/29607121/93071662-b5872080-f680-11ea-8eb6-9c5f35986d0c.png)
![image](https://user-images.githubusercontent.com/29607121/93072279-76a59a80-f681-11ea-83e6-1ac9a55ad303.png)

**.blend file/ .gltf**

[Convert_Text_Bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5217615/Convert_Text_Bug.zip)

**Version**
 - OS: Windows
 - Blender Version 2.9

**Additional context**
First of all, thanks for working on that topic. I programmed an add-on to convert curves to meshes to be able to export annotations to gltf. Maybe with your changes I don't need it anymore in the future.

![image](https://user-images.githubusercontent.com/29607121/93072130-465dfc00-f681-11ea-810a-aec177d4a6d0.png)

**Comment by scurest** [comment]
This happens because the `@cached` stuff caches meshes by their name.

So for example, your file has a _mesh_ named `Text.008`, and a _text_ named `Text.008`. When the text named `Text.008` is converted to a temporary mesh, the temporary mesh is named `Text.008`. The cache thinks this is the same as the _mesh_ named `Text.008` and mixes them up somehow.

You can check that its fixed with this patch: it passes the object type down through the all the `@cached` functions starting at gather_mesh so the cache can tell apart `'Text.008', 'MESH'` and `'Text.008', 'FONT'`.

<details>

<summary>Patch</summary>

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py
index d3f950b..2693e3f 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py
@@ -25,6 +25,7 @@ from io_scene_gltf2.io.exp.gltf2_io_user_extensions import export_user_extension
 
 @cached
 def gather_mesh(blender_mesh: bpy.types.Mesh,
+                object_type: str,
                 library: Optional[str],
                 blender_object: Optional[bpy.types.Object],
                 vertex_groups: Optional[bpy.types.VertexGroups],
@@ -41,7 +42,7 @@ def gather_mesh(blender_mesh: bpy.types.Mesh,
         extras=__gather_extras(blender_mesh, library, vertex_groups, modifiers, export_settings),
         name=__gather_name(blender_mesh, library, vertex_groups, modifiers, export_settings),
         weights=__gather_weights(blender_mesh, library, vertex_groups, modifiers, export_settings),
-        primitives=__gather_primitives(blender_mesh, library, blender_object, vertex_groups, modifiers, material_names, export_settings),
+        primitives=__gather_primitives(blender_mesh, object_type, library, blender_object, vertex_groups, modifiers, material_names, export_settings),
     )
 
     if len(mesh.primitives) == 0:
@@ -120,6 +121,7 @@ def __gather_name(blender_mesh: bpy.types.Mesh,
 
 
 def __gather_primitives(blender_mesh: bpy.types.Mesh,
+                        object_type: str,
                         library: Optional[str],
                         blender_object: Optional[bpy.types.Object],
                         vertex_groups: Optional[bpy.types.VertexGroups],
@@ -128,6 +130,7 @@ def __gather_primitives(blender_mesh: bpy.types.Mesh,
                         export_settings
                         ) -> List[gltf2_io.MeshPrimitive]:
     return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
+                                                             object_type,
                                                              library,
                                                              blender_object,
                                                              vertex_groups,
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
index 1a1abcd..91804ce 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
@@ -326,6 +326,7 @@ def __gather_mesh(blender_object, library, export_settings):
                 blender_object_for_skined_data = blender_object
 
     result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
+                                                   'MESH',
                                                    library,
                                                    blender_object_for_skined_data,
                                                    vertex_groups,
@@ -368,6 +369,7 @@ def __gather_mesh_from_nonmesh(blender_object, library, export_settings):
         blender_object_for_skined_data = None
 
         result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
+                                                       blender_object.type,
                                                        library,
                                                        blender_object_for_skined_data,
                                                        vertex_groups,
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py
index 4fe498e..0cbb690 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py
@@ -33,6 +33,7 @@ from io_scene_gltf2.io.com.gltf2_io_debug import print_console
 @cached
 def gather_primitives(
         blender_mesh: bpy.types.Mesh,
+        object_type: str,
         library: Optional[str],
         blender_object: Optional[bpy.types.Object],
         vertex_groups: Optional[bpy.types.VertexGroups],
@@ -47,7 +48,7 @@ def gather_primitives(
     """
     primitives = []
 
-    blender_primitives = __gather_cache_primitives(blender_mesh, library, blender_object,
+    blender_primitives = __gather_cache_primitives(blender_mesh, object_type, library, blender_object,
         vertex_groups, modifiers, export_settings)
 
     for internal_primitive in blender_primitives:
@@ -81,6 +82,7 @@ def gather_primitives(
 @cached
 def __gather_cache_primitives(
         blender_mesh: bpy.types.Mesh,
+        object_type: str,
         library: Optional[str],
         blender_object: Optional[bpy.types.Object],
         vertex_groups: Optional[bpy.types.VertexGroups],
````

</details>

I'm not sure that's the only way for two mesh names to be non-unique though, so maybe we should try to think of a more robust way of identifying datablocks than their name.

**Comment by scurest** [comment]
I checked and you can also create two meshes with the same name by linking a mesh with the same name as a mesh in the file. That also gets mixed up when exporting.

**Comment by scurest** [comment]
Okay, the `library` argument should prevent that because they have different libraries, but for some reason the `library` arg to __gather_mesh is `None` both times for me.

**Comment by scurest** [comment]
Oh, the `library` parameter to __gather_mesh is the library of the _object_, not the library of the _mesh_. I think that's a bug.

**Comment by scurest** [comment]
Anyway, I guess the object_type parameter is consistent with how the library parameter solves the same non-unique-name problem, so I guess its okay. I also looked in the FBX exporter and saw that it uses (name, library, type) as a unique key, so maybe this even covers all cases.

**Comment by julienduroure** [comment]
Great you checked what FBX does.
I may have an issue with recursive linking. See #1049

**Comment by LorenzWieseke** [comment]
Sorry but I can't really follow your code, I would need to clone the repo to debug in vs code. For me it seems like you described it, you just need to check the type, eg. generating a unique key containing the type and key :
![image](https://user-images.githubusercontent.com/29607121/93108044-a6b96180-f6b2-11ea-96cb-cb329e761ac0.png)

**Comment by LorenzWieseke** [comment]
I tried to rename all the meshes of the underscores but now I just get this 

![image](https://user-images.githubusercontent.com/29607121/93108859-a1a8e200-f6b3-11ea-9715-87df0ce483b5.png)

**Comment by scurest** [comment]
Renaming with

````py
for o in bpy.data.objects:
    if o.name.startswith('Under'):
        o.data.name = o.name
````

makes the export work for me.

**Comment by LorenzWieseke** [comment]
Thanks, that worked

**Comment by donmccurdy** [comment]
This issue seems to be covered by https://github.com/KhronosGroup/glTF-Blender-IO/issues/1211 and https://github.com/KhronosGroup/glTF-Blender-IO/issues/1245 now.
