### ISSUE TITLE
Bones - Inherit rotation not respected on export

### ISSUE THREAD

**Issue by Flavelius** [KhronosGroup/glTF-Blender-IO#1223]
**Describe the bug**
Exported animations do not respect toggled off 'Inherit Rotation' in Bone settings. This means rotations are different in exported files than in blender if it is toggled off for some bones.

**To Reproduce**
Open the attached blend file, notice the deformation when playing the timeline or scrubbing it.
Compare it to the attached example gltf export or export it again if desired. 
The deformation looks different as the rotation inheritance has been kept even though disabled in blender.

**Expected behavior**
The animation should export the same way it looks in blender.

**Screenshots**
Blender:
![grafik](https://user-images.githubusercontent.com/8841352/94201253-0d612b00-febc-11ea-953a-3ca7ab39fd1e.png)
gltf result (reimported into blender, but it's the same result in godot):
![grafik](https://user-images.githubusercontent.com/8841352/94201429-44374100-febc-11ea-95ae-a1cfc59df33c.png)

**.blend file/ .gltf**
[InheritRotationBug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5279250/InheritRotationBug.zip)

**Version**
Windows 10, Blender 2.83.0 (gltf addon: v1.2.75)

**Comment by scurest** [comment]
Try with Blender >=2.90.

**Comment by Flavelius** [comment]
2.90.1 (non-LTS) exports correctly.
