### ISSUE TITLE
Importing meshes without materials causes exporting issues

### ISSUE THREAD

**Issue by gabriel-dev** [KhronosGroup/glTF-Blender-IO#1224]
**Describe the bug**
When importing a scene with a mesh that doesn't contain materials, the add-on ignores the first material object linked to the mesh when exporting the scene to GLTF. If you add a single texture/material to the imported mesh, it won't show up in the exported file.

**To Reproduce**
1. Import a GLTF scene that contains a mesh with UV coordinates but no materials (import configurations don't matter);
2. Add a single material to the imported mesh;
3. Export the scene to GLTF (make sure to include materials, images, and UV coordinates);
4. The exported mesh should contain no materials whatsoever, even though we added it in Blender.

**Expected behavior**
It's expected that the output GLTF file contains the material added in Blender.

**Files**
[Here](https://gist.github.com/gabriel-dev/04dd558deaf4d65fc9e03f0b0b9cbbf8) is a GLTF file with a mesh without materials to reproduce the issue.

**Version**
- Blender:
    - version: 2.90.0, branch: master, commit date: 2020-08-31 11:26, hash: 0330d1af29c0, type: Release
    - build date: 2020-08-31, 10:00:13
- Platform: Windows 10 (2004 - 19041.508)

**Additional context**
After some debugging, it seems that the problem comes down to the following code ([check the original code here](https://github.com/KhronosGroup/glTF-Blender-IO/blob/3de6de2b995028ccd62e0fd63feacc71a105d270/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py#L327)):
```python
# gltf2_blender_mesh.py
def create_mesh(gltf, mesh_idx, skin_idx):
    ...
    # Assign materials to faces

    # Initialize to no-material, ie. an index guaranteed to be OOB for the
    # material slots. A mesh obviously can't have more materials than it has
    # primitives...
    oob_material_idx = len(pymesh.primitives)
    material_indices = np.full(num_faces, oob_material_idx)
```
The `oob_material_idx` variable is initialized with `len(pymesh.primitives)`, which, in the case of a simple mesh, is `1`. When the imported GLTF meshes are linked to some material, the loop just below the code snippet sets `material_indices` with the right values. However, when the imported meshes don't have a material, `oob_material_index` stays equal to `1`. This causes the first material (index zero) added to the mesh through Blender not to be found, thus causing the issue when exporting the scene to GLTF.

Wouldn't it be the case to default it to `0` (first material), which is the default value for [`MeshPolygon.material_index`](https://docs.blender.org/api/current/bpy.types.MeshPolygon.html?highlight=material_index#bpy.types.MeshPolygon.MeshPolygon.material_index)? After manually changing it to `0`, everything works as expected, though I didn't do extensive tests to cover other scenarios.

**Comment by scurest** [comment]
Nice issue.

So I checked, and if the material_index of a poly is >= the number of material slots, Blender will use the last material slot for that poly.

So on the importer side...

* if there are no materials used at all, then the polys can all have material_index = 0 and there can be zero material slots, just like you said. That is, the whole `# Assign materials` block can be skipped.
* if there are primitives both with and without a material though, always using 0 would make no-material faces take on a material. Instead we can add an empty material slots (with `mesh.materials.append(None)`) and assign its index to any polys without a material.

And on the exporter side....

* [this](https://github.com/KhronosGroup/glTF-Blender-IO/blob/5d976d3642b5ce885719a29976b83f8d6562713b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py#L59) needs to be updated to take into account material_index >= number of material slots.
