### ISSUE TITLE
[Bug] .GLTF files are displayed when GLB format is selected

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1227]
When you export to gltf, there's an option to select which format you want to use: GLTF or GLB.
But no matter which one you choose, the explorer will always show both GLTF and GLB files.
![img](https://i.imgur.com/9Pz6ZNJ.png)
**Expected behavior:** show only .glb files when expoting to GLB;
show only .gltf files when exporting to GLTF

**Comment by julienduroure** [comment]
Dynamic filtering is not implemented yet.
Set it as enhancement
