### ISSUE TITLE
delta transformation - exporting with armature change the scale!

### ISSUE THREAD

**Issue by mshamaseen** [KhronosGroup/glTF-Blender-IO#1228]
**Describe the bug**
It has been a full day now trying to export gltf object with armature, gltf exporter always makes it insanely huge, I've tried everything but it ain't work!

**To Reproduce**
1. Just install the blend file and try to export glb file.
2. go to threejs.com/editor and test the exported glb file (or just make a new blender file and import it there), you will find that the dimension of the object is increased in a huge way

**Expected behavior**
to match the scale.

**.blend file/ .gltf**

here is the blend file
https://drive.google.com/file/d/1_8SuvIerOYu5Uch4aEJ3HstCGpJZRaMD/view?usp=sharing

and the glb file:
https://drive.google.com/file/d/1fAB6k4b37LqFaw2ZN3z-PjiWKIN61qmc/view?usp=sharing

**Version**
 - OS: [Linux, ubuntu]
 - Blender Version: 2.9

**Comment by mshamaseen** [comment]
ok so I found something after all these hours, there was a delta transformation in the blender file and it was not taking into account when exporting to glb!

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
