### ISSUE TITLE
Merging color and alpha to one texture when they use different UV channels

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1229]
Texture merging will cause problems if color texture and alpha texture use different UV channels.
![img](https://i.imgur.com/xgiCaj6.png)

**Comment by julienduroure** [comment]
As requested in issue template, please indicate what version you are testing?
Some recent fix has been merge, so it may be solved in recent builds.

Also providing a test case file will help saving time. I know that we can recreate it from you screenshot, but having a test case directly usable same time :)

**Comment by scurest** [comment]
Cf #1068

**Comment by vergol** [comment]
So it could be a problem with channel split?
I will try to make some tests later...

**Comment by j-conrad** [comment]
Possibly related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/1219?

**Comment by scurest** [comment]
Oh, different _UV maps_. I thought the problem was the channel splitting.

It isn't possible to use different UV maps (or samplers, or texture transforms) for base color and alpha in glTF. There was another issue about this today: #1230.

A warning is already printed to the console about the sampler bit:

    WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.

**Comment by vergol** [comment]
```
A warning is already printed to the console about the sampler bit:
```
So it gives a warning and generates a wrong texture?
Maybe just export single color texture?

**Comment by scurest** [comment]
Do what?

**Comment by julienduroure** [comment]
No answer from the user since 1 month
Maybe we can add a more visible warning (in popup like suggested in another ticket for another warning)?

**Comment by donmccurdy** [comment]
I don't think there is any way for the exporter to fix this — in general it would be nice if we could show more user-visible warnings when we detect that something won't export correctly, but (without a clear mechanism to do that) I'm not sure we need to keep this issue open.

**Comment by julienduroure** [comment]
Closing this ticket, as there is no bug here.
About better warning, this will be handled somewhere else. No need to keep this ticket open for that
