### ISSUE TITLE
Material order inside "mesh"?

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1231]
I've just noticed that this order:
![img](https://i.imgur.com/93TBdyW.png)
is not saved during gltf export.
Is it a normal behavior?

![img](https://i.imgur.com/EntfmUR.png)

![img](https://i.imgur.com/mDuwnuo.png)

**Comment by scurest** [comment]
What version are you using? I think this was changed by #1120 and the primitives should go in the same order as the material slots now.

**Comment by vergol** [comment]
I'm using 2.90.0, but also tried with 2.90.1
Was #1120 already included there?
