### ISSUE TITLE
KTX / DDS support

### ISSUE THREAD

**Issue by ArneDJ** [KhronosGroup/glTF-Blender-IO#1234]
Currently only JPG and PNG are supported, this is a problem for games due to the long loading times and memory that it takes in.

It would be nice if GPU compressed images like KTX or DDS would be supported. Artists could simply export the glTF files with image data embedded without having to manually convert them to a GPU compressed format.

**Comment by donmccurdy** [comment]
Blender itself doesn't support these formats (or at least, [doesn't support DDS well](https://blender.stackexchange.com/questions/111115/can-blender-open-dds-files)?) and adding KTX with Basis would require native dependencies that need to go into Blender core. This could be a good feature request for Blender, but it's not an easy fix.

It's also unfortunately the case that compressing textures (1) is slow and (2) requires some tuning to avoid compression artifacts. Because of that, you may have a better time adding compression after exporting with something like [gltfpack](https://github.com/zeux/meshoptimizer#gltfpack) or [gltf-transform](https://gltf-transform.donmccurdy.com/cli.html). More feedback on good workflows here would be welcome.

**Comment by ArneDJ** [comment]
Thanks for the fast answer, I'll give gltfpack and gltf-transform a try.

**Comment by UltraEngine** [comment]
> Blender itself doesn't support these formats (or at least, [doesn't support DDS well](https://blender.stackexchange.com/questions/111115/can-blender-open-dds-files)?) and adding KTX with Basis would require native dependencies that need to go into Blender core. This could be a good feature request for Blender, but it's not an easy fix.

Blender doesn't need to support DDS files for this feature, and it's better to leave the original images in PNG format. The glTF exporter could compress the image files into the optimal format:

| Name | Format | R | G | B | A |
|---|---|---|---|---|---|
| base | BC7 | base red | base green | base blue | base alpha |
| normal | BC5 | nx | ny | -- | -- |
| occlusion / metallic / roughness | BC7 | ambient occlusion | metalness | roughness | -- |
| emission | BC6H or BC7 | emission red | emission green | emission blue | -- |
| occlusion (alone) | BC4 | ambient occlusion | -- | -- | -- |

> It's also unfortunately the case that compressing textures (1) is slow and (2) requires some tuning to avoid compression artifacts. Because of that, you may have a better time adding compression after exporting with something like [gltfpack](https://github.com/zeux/meshoptimizer#gltfpack) or [gltf-transform](https://gltf-transform.donmccurdy.com/cli.html). More feedback on good workflows here would be welcome.

1. This is not true. [Intel's ISPC texture compression library](https://github.com/GameTechDev/ISPCTextureCompressor) encodes BC7 images in seconds.

2. Never once in my life have I had to "tune" DDS compression to adjust an image. Any image that default BC7 compression doesn't work for should not use compression at all.

**Comment by donmccurdy** [comment]
Replying to both this thread and your comment in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1294 – 

I agree that compression speed is not necessarily an obstacle to adding support in Blender. We support Draco compression, for compressing mesh geometry, which is similar in cost.

But MSFT_texture_dds is not a ratified glTF extension. We've historically made a policy in this addon of:

1. Avoiding single-vendor extensions like `MSFT_*`
2. Adding multi-vendor extensions (`EXT_*`) on a case-by-case basis
3. Supporting ratified Khronos extensions (`KHR_*`) when possible

Most glTF loaders do not support MSFT_texture_dds, and I do view exporting non-standard files as a risk for the glTF ecosystem... I should also note that the channels for roughness/metalness do not match your table, that would need to be occlusion / roughness / metalness (RGB) instead.

This Blender addon does have a plugin API, to support custom use cases like vendor extensions when needed.

> Never once in my life have I had to "tune" DDS compression to adjust an image.

I'm referring to KTX2 compression here, with Basis Universal (based on ASTC and ETC1). Historically I have certainly had to tune compression settings for different texture types and different projects, but I can't comment on DDS.

The other factor is that this is a Python addon. When Draco compression support was added, it required putting the Draco C++ library into the Blender itself, first. If that's still a requirement, it would mean the upstream Blender developers need to be interested in DDS as well.

**Comment by donmccurdy** [comment]
For what it's worth – I'd be very excited to get KTX2 support in this addon as well, which is a ratified extension. But that hasn't been possible so far, and (to my understanding) it's because of the requirement for support in Blender.

**Comment by UltraEngine** [comment]
> Most glTF loaders do not support MSFT_texture_dds, and I do view exporting non-standard files as a risk for the glTF ecosystem... I should also note that the channels for roughness/metalness do not match your table, that would need to be occlusion / roughness / metalness (RGB) instead.

Thank you for pointing that out. I always get those confused! Table is corrected.
