### ISSUE TITLE
export keyframed force animations

### ISSUE THREAD

**Issue by jbixon13** [KhronosGroup/glTF-Blender-IO#1235]
**Describe the bug**
I am trying to export an animated object that has forces applied to it. I have been able to do this with rigid body physics by baking to keyframes and would like to do the same with forces baked to an object's action (or keyframes). 

**To Reproduce**
1. Select sphere object
2. Go to animation tab
3. Inspect dope sheet: there should be a single action keyframed from 1 to 120 titled `rolling sphere`
4. Select sphere and plane objects
5. Export as `.glb`
6. Upload to https://gltf-viewer.donmccurdy.com/
7. I can see the action is imported correctly as "rolling sphere" but will not play.

**Expected behavior**
I expect that when I load the `.glb` file into a viewer its action plays and the sphere drops and rolls off the plane. The action is composed of X, Y, Z Location transforms which the exporter should be able to handle.

**Screenshots**
![image](https://user-images.githubusercontent.com/32110237/95687353-1991fb80-0bd1-11eb-885e-8726eb8091cb.png)

**.blend file/ .gltf**
`.blend` and `.glb` included here: https://gofile.io/d/EFE6Tt 

**Version**
 - OS: Windows 10
 - Blender Version 2.91

**Comment by jbixon13** [comment]
I was able to resolve this by using rigid body physics and baking to keyframes. I'm not sure why baking to an action didn't work, but that resolved my issue.

**Comment by julienduroure** [comment]
glTF can store only keyframe animation, so you need, as you said, to bake animation.
If some baking are not working, I suggest you to open a bug report on blender side directly : https://developer.blender.org/
