### ISSUE TITLE
Errors importing vertex colors

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#124]
On a couple models, I see errors when importing that appear to stem from Vertex Color code:

[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2636622/Archive.zip)

![screen shot 2018-12-01 at 9 52 17 pm](https://user-images.githubusercontent.com/1848368/49336267-a1f5ed00-f5b3-11e8-98e5-da262d1c9be6.png)

![screen shot 2018-12-01 at 9 52 41 pm](https://user-images.githubusercontent.com/1848368/49336268-a3271a00-f5b3-11e8-88a6-458508f31373.png)

**Comment by julienduroure** [comment]
Confirmed.
Linked on API change on 2.8

**Comment by donmccurdy** [comment]
Thanks!
