### ISSUE TITLE
Exported GLTF model has black textures when imported in Three.js

### ISSUE THREAD

**Issue by ilovemilk** [KhronosGroup/glTF-Blender-IO#1241]
**Describe the bug**
I have these objects in Blender, that look like this:
![blender](https://user-images.githubusercontent.com/7439455/96479919-d6bbcd80-1239-11eb-9735-d16b3a7412cd.PNG)
But when I import these objects in the [Babylon.js Sandbox](https://sandbox.babylonjs.com/) it looks like this:
![threejs](https://user-images.githubusercontent.com/7439455/96479996-efc47e80-1239-11eb-994a-d1fd3113a7ab.PNG)
Im new to Blender and Three.js so I don't now if it's a problem with the exporter or I did something wrong.

Thanks in advance.

**Expected behavior**
The textures should look the same.

**.blend file/ .gltf**
[test_texture.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5403373/test_texture.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.90.1

**Comment by donmccurdy** [comment]
This material uses a complex node setup plugged in, much more than just a texture:

![Screen Shot 2020-10-19 at 9 56 54 AM](https://user-images.githubusercontent.com/1848368/96485612-7bfe8380-11f1-11eb-8d94-6518ba17b074.png)

The result in https://gltf-viewer.donmccurdy.com/ shows that the texture is being included...

![Screen Shot 2020-10-19 at 9 57 38 AM](https://user-images.githubusercontent.com/1848368/96485825-87ea4580-11f1-11eb-9003-a4fc157be4df.png)

... but the rest of the node setup cannot be exported outside of Blender to any format. To address that you'll need to ensure the material follows the guidelines provided here: https://docs.blender.org/manual/en/2.90/addons/import_export/scene_gltf2.html

**Comment by ilovemilk** [comment]
Thanks! For the quick response, I give it a try.
