### ISSUE TITLE
Unable to import VC sample

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#1247]
**Describe the bug**

When importing VC.glb from the glTF sample repository, I see an error message.

**Screenshots**

![Screen Shot 2020-10-21 at 8 37 55 PM](https://user-images.githubusercontent.com/1848368/96821775-7796be00-13dd-11eb-90e5-c9cac74b1bfb.png)

**.blend file/ .gltf**

[VC.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5419886/VC.glb.zip)

**Version**
 - OS: macOS
 - Blender Version 2.90.0 Beta, latest master branch of glTF-Blender-IO.

**Additional context**

Note that there is a known issue in the model itself, it contains flying boxes where there should be cameras. :)

**Comment by scurest** [comment]
> Blender Version 2.90.0 Beta, latest master branch of glTF-Blender-IO.

The master branch requires 2.91.

**Comment by donmccurdy** [comment]
Yep, that was it thanks!
