### ISSUE TITLE
Ability to detect "is_active_output"on OUTPUT_MATERIAL node

### ISSUE THREAD

**Issue by Vinc3r** [KhronosGroup/glTF-Blender-IO#1248]
It could be useful to have multiple Material Outputs on our materials. One node tree for Cycles, another for glTF, another one for texture baking, etc.

I've notice that the glTF exporter doesn't care about the `is_active_output` and/or `mute` property of an OUTPUT_MATERIAL node, and just take the first in the material nodes list.

A nice feature would be to take into account only node tree linked to the current active output.

Screenshot below, from the .blend in attachment, give you an example. My active output use an UVGrid texture, my inactive output use a ColorGrid texture. The exported node tree is the one which is inactive.

![image](https://user-images.githubusercontent.com/3873421/96869881-63e86780-1470-11eb-9f89-dd31a39261d1.png)

[material-output.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5422567/material-output.zip)

**Comment by julienduroure** [comment]
Hello,
This is quite the similar request than #1213
