### ISSUE TITLE
Child Of Constraints not exported

### ISSUE THREAD

**Issue by rodstafford** [KhronosGroup/glTF-Blender-IO#1251]
**Describe the bug**
"Child of" Constraints not recognized in exported gITF

**To Reproduce**
1. Create Armature parented to mesh.
2. Add Child of Constraints to separate meshes and create 'child of constraints' to Armature bones
3. Create animated action "action"
4. Export to gITF

**Expected behavior**
The meshes should be constrained and move in the export same as in blender.  Best to take a look at the attached sample files, 

**Screenshots**
blender.JPG shows correct constraint behavior, sandbox.JPG is a screen capture of the exported model in the babylon sandbox
![blender](https://user-images.githubusercontent.com/6014335/97059825-a046c100-155f-11eb-98a5-1fca9cb2ba10.JPG)
![sandbox](https://user-images.githubusercontent.com/6014335/97059826-a046c100-155f-11eb-8240-8f89b55d1aa3.JPG)

**.blend file/ .gltf**
Zipped file contains both the .blend and .glb files
[Constraints Not Working.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5432058/Constraints.Not.Working.zip)

**Version**
 - OS:Windows 10
 - Blender Version 2.90

**Additional context**

**Comment by julienduroure** [comment]
Object Constraints is not something that can be expressed in glTF specification.
You first need to bake animation on constraint objects before exporting (bake with visual keying)

![image](https://user-images.githubusercontent.com/1696020/97069386-46caaa80-15d0-11eb-9dd4-6dc18657f4a2.png)

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
