### ISSUE TITLE
Type of empty objects is lost after export and import

### ISSUE THREAD

**Issue by valeev-iv** [KhronosGroup/glTF-Blender-IO#1259]
**Describe the bug**
Exported glTF file did not contains property for empty object type. Imported empty objects loaded as empty plain axis.

**To Reproduce**
1. Create empty object (sphere or cube)
2. Export to glTF file
3. Import from glTF file
4. All empty objects becomes empty plain axis

**Expected behavior**
After import empty objects (cube, sphere, ...) should have initial types

**Screenshots**
Before export
![Export](https://user-images.githubusercontent.com/6941132/98088816-ad53a080-1ecd-11eb-9d45-0db3f5e647d9.PNG)

After import
![Import](https://user-images.githubusercontent.com/6941132/98088838-b17fbe00-1ecd-11eb-9fff-1669df108b5c.PNG)

**.blend file/ .gltf**
[Empty_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5486537/Empty_test.zip)

**Version**
 - OS: Windows 10
 - Blender 2.90.1

**Additional context**
Empty cube in *.gltf now:
```
"nodes" : [
    {
        "name" : "EmptyCube "
    },
```

Maybe it should be something like this?
```
"nodes" : [
    {
        "name" : "EmptyCube ",
        "extras" : {
            "empty_draw_type" : "CUBE"
         },
    },
```

**Comment by donmccurdy** [comment]
I'm not sure it's a good idea for us to write `.extras` with implicit behavior effects like this. If Godot is interested in supporting a collision shape workflow through Blender, the better option would be to define a simple extension (`GODOT_collision_shapes`?) and use an addon to enhance glTF-Blender-IO with that capability:

https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/example-addons/example_gltf_extension

There have been some suggestions for a general-purpose physics extension in glTF (https://github.com/KhronosGroup/glTF/issues/1135) but I don't see strong signs of consensus on how to do that, so it may be more practical to "pave the way" with a good implementation in Godot first.
