### ISSUE TITLE
[Regression] Morph targets cause splotchy materials in exported glTF

### ISSUE THREAD

**Issue by mattrossman** [KhronosGroup/glTF-Blender-IO#1262]
**Describe the bug**
I'm getting splotchy material artifacts on models with active morph targets exported from 2.90+ versions of Blender. The issue does not occur when exporting from Blender 2.83. The issue may have to do with either import or export, I'm not sure.

**To Reproduce**
1. Download and extract my sample files here: [sample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5550888/sample.zip)
2. Open the latest version of blender (2.90.1)
3. Import `sample.glb`
4. Export the file with .glb defaults (see `sample-export.glb`)
5. Open the exported file in https://gltf-viewer.donmccurdy.com/
6. Adjust the morphTarget in the panel on the right

**Expected behavior**
The exported file will morph the same as the imported file.

**Screenshots**
Here is how the original file appears when morphed:
![image](https://user-images.githubusercontent.com/22670878/99338785-e3d8d600-2852-11eb-8d43-66a799fe61b0.png)

And here is how the exported file appears, notice the dark splotches covering the face after the morph target is applied:
![image](https://user-images.githubusercontent.com/22670878/99338471-454c7500-2852-11eb-8463-b238c16c4957.png)

**.blend file/ .gltf**
[sample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5550888/sample.zip)

**Version**
 - OS: Windows
 - Blender Version 2.90.1

**Additional context**
On my Macbook with Blender 2.83, the exported model morphs just fine.

**Comment by scurest** [comment]
I can reproduce with the blender-v2.90-release branch, but it works in master (bisect indicates it was fixed by 11dac91b). Try with the 2.91 beta from https://builder.blender.org/download/.

**Comment by j-conrad** [comment]
I’ve had this happen before, but I always have turned off ‘Shape Key Normals’ to avoid it. Didn’t occur to me that it might actually be a bug.

**Comment by julienduroure** [comment]
@mattrossman Can you please confirm that this is fixed in a recent build?

**Comment by mattrossman** [comment]
Yes, it is fixed in the 2.91 beta 👍
