### ISSUE TITLE
GLB with blend shape animations is jittery in Windows and WEB viewers

### ISSUE THREAD

**Issue by lue** [KhronosGroup/glTF-Blender-IO#1263]
**Describe the bug**
I export animation with blend shapes that looks smooth in Blender. When I open this animation with a Windows viewer or with an online viewer ( https://gltf-viewer.donmccurdy.com/ ) the animation is jittery. However, if I reimport it back into Blender it is smooth again.

I tried different settings in the animation export with no effect.

See this gif:
![](https://media.giphy.com/media/IN7J8bfdQVB9AIapiy/giphy.gif)

**To Reproduce**
In Windows or a WEB viewer it is jittery. In Blender it is OK.

**Expected behavior**
Smooth animation everywhere.

**.blend file/ .gltf**
Here is a link to this GLB file: 
https://drive.google.com/file/d/1z-3LNgP2e3mT1TPCK3gsDzvMLU3HINq1/view?usp=sharing
Blend file:
https://drive.google.com/file/d/1fxcs8rNU5mcp1gK8T0eR-0CHvuNj-vuy/view?usp=sharing

**Version**
 - OS: Windows
 - Blender Version 2.90.1

**Additional context**

**Comment by donmccurdy** [comment]
Most realtime 3D engines can support only a limited number of active blend shapes / morph targets at a time. In my viewer above, that limit is 8 when shape key normals are omitted (as in your example) and 4 when shape key normals are included. As you can see when scrolling through the morph target UI, the number of active morph targets is much higher here, as the list continues offscreen:

![Screen Shot 2020-11-19 at 12 11 20 PM](https://user-images.githubusercontent.com/1848368/99719186-d729cd00-2a60-11eb-8d6b-0a595ecc8917.png)

When more than 8 morph targets are active, only the 8 with the highest weights are used — this causes the jitter you are seeing. There may exist viewers that can handle more: Sketchfab would be my first guess, but I'm not sure.

**Comment by lue** [comment]
Thank you a lot, @donmccurdy !

We will continue thinking how to do facial animations playback on the web.

**Comment by julienduroure** [comment]
Seems the problem doesn't come from blender exporter. Closing this ticket.
Don't hesitate to comment if you need.
