### ISSUE TITLE
T82974 : gltf file imported but no principled material created KHR_materials_pbrSpecularGlossiness

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1269]
See https://developer.blender.org/T82974

**Comment by donmccurdy** [comment]
There is no perfect way to convert a spec/gloss material to a metal/rough material (like Principled BSDF). I've implemented an [offline CLI conversion](https://gltf-transform.donmccurdy.com/cli.html), but it relies on the newer IOR and Specular glTF extensions, so it will be some time before that becomes a reasonable round-trip option with wide support. It involves setting IOR to an extreme value, which feels a bit weird but seems to work OK if the engine supports both extensions. See https://github.com/KhronosGroup/glTF-Blender-IO/issues/899#issuecomment-701561810.

Moving forward, new material features in glTF will be added only for metal/rough workflows, and features like Sheen, Clearcoat, IOR, SSS, etc. will *not* be added to the spec/gloss workflow. So I think I would vote against going to a lot of trouble to roundtrip `KHR_materials_pbrSpecularGlossiness` from a complicated node graph in Blender, where Principled BSDF is already such a good fit for the metal/rough workflow. But if we could figure out a way to convert spec/gloss to metal/rough during import (at least in a "good enough" way, similar to the CLI conversion above) that might be worth considering.
