### ISSUE TITLE
T82968 : gltf/glb imported with skinning/rigging artifacts

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1270]
See https://developer.blender.org/T82968

**Comment by scurest** [comment]
The problem is the algorithm that tries to guess the original bind pose. Turning off the "Guess Original Bind Pose" option on the import screen works much better (even the edit bones come out well)

![girl](https://user-images.githubusercontent.com/11024420/100233669-ab3e9980-2eef-11eb-9a28-40e6d4a42959.png)

It's possible the algorithm could be changed to work better on this model (I haven't investigated at all), but in the general case I doubt this problem will ever completely go away; glTF does not store the "bind pose" so we have to guess no matter what we do and sometimes we will be wrong.

**Comment by julienduroure** [comment]
Thanks for the analysis!
Closing, will do the same in original ticket on dev.b.o

**Comment by scurest** [comment]
A better "Guess Original Bind Pose" algorithm would still be nice. Or at least an analysis of why it fails in this case. This is the bind pose it guesses. You can see it's supposed to be an A-pose but obviously it messes up the hands.

![bind](https://user-images.githubusercontent.com/11024420/100235535-2903a480-2ef2-11eb-85c5-5ba53e843143.png)

**Comment by julienduroure** [comment]
@scurest yes, we can have a better algorithm, let's put it on TODO list, as we have a workaround for this particular model

**Comment by scurest** [comment]
More info:

Generator is `FBX2glTF v0.9.7`

The file contains multiple overlapping skins. Each part of the mesh has its own skin and the skin contains only the joint nodes needed for that mesh (which is perfectly logical).

I think the "Guess Original Bind Pose" algorithm is confused by the overlapping skins. It tries to grab the IBMs for all the nodes, then computes the bind TRS from the IBM of a node and the IBM of its parent node, irrespective of if those two IBMs came from the same skin. If I compute bind TRS on a per-skin basis instead, like this

<details>

<summary>Patch</summary>

````diff
diff --git a/addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py b/addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
index ade1d95d..fd3385a4 100644
--- a/addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
+++ b/addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py
@@ -362,11 +362,13 @@ def pick_bind_pose(gltf):
     Pick the bind pose for all bones. Skinned meshes will be retargeted onto
     this bind pose during mesh creation.
     """
+    bind_tr = {}
     if gltf.import_settings['guess_original_bind_pose']:
         # Record inverse bind matrices. We're going to milk them for information
         # about the original bind pose.
-        inv_binds = {'root': Matrix.Identity(4)}
         for skin in gltf.data.skins or []:
+            inv_binds = {'root': Matrix.Identity(4)}
+
             if skin.inverse_bind_matrices is None:
                 continue
 
@@ -383,25 +385,30 @@ def pick_bind_pose(gltf):
             for i, joint in enumerate(skin.joints):
                 inv_binds[joint] = skin_inv_binds[i]
 
-    for vnode_id in gltf.vnodes:
-        vnode = gltf.vnodes[vnode_id]
-        if vnode.type == VNode.Bone:
-            # Initialize bind pose to default pose (from gltf.data.nodes)
-            vnode.bind_trans = Vector(vnode.base_trs[0])
-            vnode.bind_rot = Quaternion(vnode.base_trs[1])
-
-            if gltf.import_settings['guess_original_bind_pose']:
-                # Try to guess bind pose from inverse bind matrices
+            # Try to guess bind pose from inverse bind matrices
+            for vnode_id in gltf.vnodes:
+                vnode = gltf.vnodes[vnode_id]
+                if vnode.type != VNode.Bone: continue
                 if vnode_id in inv_binds and vnode.parent in inv_binds:
                     # (bind matrix) = (parent bind matrix) (bind local). Solve for bind local...
                     bind_local = inv_binds[vnode.parent] @ inv_binds[vnode_id].inverted_safe()
                     t, r, _s = bind_local.decompose()
-                    vnode.bind_trans = t
-                    vnode.bind_rot = r
+                    bind_tr[vnode_id] = (t, r)
+
+    for vnode_id in gltf.vnodes:
+        vnode = gltf.vnodes[vnode_id]
+        if vnode.type == VNode.Bone:
+            if vnode_id in bind_tr:
+                t, r = bind_tr[vnode_id]
+            else:
+                # Initialize bind pose to default pose (from gltf.data.nodes)
+                t, r = Vector(vnode.base_trs[0]), Quaternion(vnode.base_trs[1])
+            vnode.bind_trans = t
+            vnode.bind_rot = r
 
             # Initialize editbones to match bind pose
-            vnode.editbone_trans = Vector(vnode.bind_trans)
-            vnode.editbone_rot = Quaternion(vnode.bind_rot)
+            vnode.editbone_trans = Vector(t)
+            vnode.editbone_rot = Quaternion(r)
 
 
 def prettify_bones(gltf):
````

</details>

Then this bind pose is guessed:

![fixed](https://user-images.githubusercontent.com/11024420/100243540-99fb8a00-2efb-11eb-9d70-342d1d7a9bf4.png)

The A-pose is correctly reconstructed and there's no artifacts in pose mode. The model is face-down in edit mode, but that's a common issue, Brainstem is like that too.

Maybe I'll try testing this on more models and PR it if I don't find any problems.

**Comment by scurest** [comment]
Above patch doesn't work well for Alicia model from #967

![alicia](https://user-images.githubusercontent.com/11024420/100277926-9c74d880-2f29-11eb-9888-8d21dda28a9a.png)

Left is with master (edit mode/pose mode), right is in edit mode with that patch (no artifacts in pose mode, but the bone lengths are bad).
