### ISSUE TITLE
Show clear error on import with missing resources

### ISSUE THREAD

**Issue by cravisjan97** [KhronosGroup/glTF-Blender-IO#1278]
Hi

I am trying to import a gltf file and export it to obj format. I am facing a buffer key error in ```addons/io_scene_gltf2/io/imp/gltf2_io_binary.py``` at line 54: ```buffer = gltf.buffers[buffer_view.buffer]
KeyError: 0```. How do I solve this? I am using Blender 2.91.

**Comment by donmccurdy** [comment]
Hi @cravisjan97, could you share an example of a glTF file that you're not able to import correctly?

> **NOTE:** I've moved this issue from the glTF repository to the glTF-Blender-IO repository.

**Comment by scurest** [comment]
This happens when there is a missing .bin file. A more helpful error in that case would be nice.

**Comment by donmccurdy** [comment]
@cravisjan97 in this case, your `.gltf` file should also have come with a `.bin` file. They need to be kept together, so that Blender can find the `.bin` when trying to import the file.

**Comment by cravisjan97** [comment]
Should the .bin and .gltf files be in the same folder? Is there a way to include the bin file path in bpy.ops.import_scene.gltf()

**Comment by donmccurdy** [comment]
The `.gltf` file contains a relative path to the `.bin` file. Usually that would expect them to be in the same folder, but technically it's possible to use a different location. Or you could pack them into a GLB using something like glTF-Pipeline or https://glb-packer.glitch.me/.

**Comment by scurest** [comment]
@donmccurdy There really should be a readable error message showing the uri when this happens. Otherwise you have no hope of knowing what to do unless you know how glTF works.

**Comment by donmccurdy** [comment]
Good point - renamed the issue and reopened.

**Comment by donmccurdy** [comment]
Opened https://github.com/KhronosGroup/glTF-Blender-IO/pull/1289.
