### ISSUE TITLE
cannot export transparent textures (nor select png)

### ISSUE THREAD

**Issue by coderofsalvation** [KhronosGroup/glTF-Blender-IO#1279]
I cannot seem to export transparent png's in my gltf, NOR select PNG as export option

1. create a mesh
2. apply a material using a transparent png in the shader editor:

![image](https://user-images.githubusercontent.com/180068/100746336-dbe76d00-33e0-11eb-8b9e-58946dcee466.png)

3. set blend mode to 'alpha blend' in material properties
4. now export the gltf (**NOTE**: for some reason, you can't select png)

![image](https://user-images.githubusercontent.com/180068/100746516-18b36400-33e1-11eb-887e-a7c9b7c6c378.png)

5. test the model at https://gltf-viewer.donmccurdy.com

**Expected behavior**
transparent textures

**.blend file/ .gltf**
https://filebin.net/3ab7vwn9httastq1/theme.gltf?t=v81o3lxp

**Version**
 - OS: windows
 - Blender Version 2.83 + 2.91

**Comment by scurest** [comment]
File looks okay to me. It seems only Three has an issue.

In Three

![three](https://user-images.githubusercontent.com/11024420/100756328-be031380-33b2-11eb-8c9e-dffe59ba9406.png)

Others

![bab](https://user-images.githubusercontent.com/11024420/100756348-c2c7c780-33b2-11eb-8a31-5f9ebfcb8923.png)
![blend](https://user-images.githubusercontent.com/11024420/100756355-c4918b00-33b2-11eb-87c9-d16d73a9d932.png)
![rs](https://user-images.githubusercontent.com/11024420/100756575-f60a5680-33b2-11eb-8204-68d93acc7866.png)

@donmccurdy Can you look?

**Comment by donmccurdy** [comment]
This was fixed in https://github.com/mrdoob/three.js/pull/20376 – my viewer is behind, but it should work fine in newer versions of three.js.

**Comment by coderofsalvation** [comment]
Ah Ok, so it's not the exporter.
Thanks a lot, wasn't really sure how to test it.
Next time I'll try to import the exported gltf with blender to test (no idea why I didn't think of that).
