### ISSUE TITLE
glTF-IO v1.4.40 Causing Failure to Load Scenes on Oculus Quest Home Environment

### ISSUE THREAD

**Issue by Rovai211** [KhronosGroup/glTF-Blender-IO#1284]
You'll have to forgive me, this is my first bug report ever.

Long story short, something changed between glTF-IO versions 1.3.48 and 1.4.40 that causes any glTF file exported with a rig to failed to load on my glTF viewer.

To elaborate, the glTF viewer in question is the Oculus Quest (1) Home Environment, which behaves as a simple model viewer, displaying meshes with only albedo textures and transparency (blend/clip) supported. This viewer does and has always supported basic translation/rotation/scale animations and rigged animation/figures. This has worked most recently as of Blender version 2.90.0 (which included glTF-IO version 1.3.48)

As of Blender 2.91.0 with glTF-IO version 1.4.40, when any exported glFT file (regardless of complexity) containing a rigged mesh was loaded into the Quest viewer environment, the entire file would simply fail to load, leaving a blank, all-black void. I have tried with new Blender files, old scenes that were known to have worked, pre-rigged assets (Mixamo), and even a basic scene with two cubes attached to a simple two-bone rig (using Ctrl+P>Aautomatic Weights). All scenes worked by themselves, but failed to load once the rigs were added.

I have tried using the previous Blender 2.90.0 build to export the all the same scenes, which all worked, with or without rigs included. I then took the glTF folder from the 2.90.0 build's program folder, which I used to replace the same folder in the 2.91.0 build. The resulting exported files were all successfully exported and viewed on the Quest, which leads me to believe that the only possible source for the issue is the updated version 1.4.40 glTF-IO  add-on itself.

I apologize if this isn't very helpful, but I tried to be as clear as I could. I am an engineer, not a programmer, so the most I can do is document, explain, and follow up if needed. I have troubleshot only enough to identify the source, but lack the expertise to root out the cause.

1. Go to 'File>Export>glTF 2.0'
2. Set Format to 'glTF Seperate'
3. Leave all other options as default
4. Export glTF file
5. ... load to Oculus Quest home environment
6. No scene loads :c

**Expected behavior**
With that the same steps, the scene contained in the exported file should load, with the user placed at the scene's origin point (0,0,0), and all animations playing on continuous loop.

**Version**
 - OS: [Windows 10]
 - Blender Version [2.91.0]
 - glTO-IO Version [1.4.40]

**Additional context**
Please help?

**Comment by donmccurdy** [comment]
The first thing to check, I think, would be whether the glTF files that are failing in Oculus Home are valid files. A few quick steps to try for that:

1. Are there any errors from the official glTF validator? (https://github.khronos.org/glTF-Validator/)
2. Does it load in three.js? (https://gltf-viewer.donmccurdy.com/)
3. Does it load in babylon.js? (https://sandbox.babylonjs.com/)

If it's OK in all of those, then it's more likely the file is correct and Oculus Home has a bug in its glTF loader. Unfortunately, if Oculus only implemented partial glTF support, it is hard for us to know what that is. If the model fails in one or more viewers above, or has significant validation errors, that may be something we can fix.

**Comment by donmccurdy** [comment]
And, congrats on the first bug report! The detailed explanation is appreciated. ☺️

**Comment by scurest** [comment]
I ran [CesiumMan](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan) through an export with both 1.3.48 and 1.4.40 and diffed the .gltf files. Ignoring changes in accessor counts, buffer lengths/offsets, here is a list of all changes:

<details>

<summary>List of changes (expand to see)</summary>

* JOINTS_x accessors are stored as UBYTEs instead of USHORTs

    ```diff
             {
                 "bufferView" : 3,
    -            "componentType" : 5123,
    -            "count" : 4771,
    +            "componentType" : 5121,
    +            "count" : 4680,
                 "type" : "VEC4"
             },
    ```
* Some material property are omitted in 1.4.40 when they have the default value

    ```diff
         ],
         "materials" : [
             {
    -            "emissiveFactor" : [
    -                0,
    -                0,
    -                0
    -            ],
                 "name" : "Cesium_Man-effect",
                 "pbrMetallicRoughness" : {
                     "baseColorTexture" : {
                         "index" : 0,
                         "texCoord" : 0
                     },
    -                "metallicFactor" : 0,
    -                "roughnessFactor" : 1
    +                "metallicFactor" : 0
                 }
             }
         ],
    ````
* texture's now always have a sampler

    ```diff
         "textures" : [
             {
    +            "sampler" : 0,
                 "source" : 0
             }
         ],
    +    "samplers" : [
    +        {
    +            "magFilter" : 9729,
    +            "minFilter" : 9986
    +        }
    ```

</details>

I think the JOINTS_x accessor storing UBYTEs in 1.4.40 instead of USHORTs in 1.3.48 is most likely to be the culprit since only skinned meshes are affected.

Here's a .zip: [CesiumManUbytesVsUshorts.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5643053/CesiumManUbytesVsUshorts.zip). CesiumMan_ubytes.gltf is exported with 1.4.40, and CesiumMan_ushorts.gltf is exported with 1.4.40 with one change: joints are always exported as USHORTs.

If CesiumMan_ushorts works in your viewer, that would confirm the UBYTEs joints accessor is the problem.

**Comment by Rovai211** [comment]
Just tried loading both CesiumMan files into the Quest, and can confirm that the -ubytes version failed to load, whereas the -shorts version loads instantly as expected.

... I have no idea what that means, but it 100% worked using USHORTS...

So like, this completely halts my workflow when using rigged meshes. Is there _anything_ I can do going forward? Or do I have to rely on a version that will one day become obsolete? :c

**Comment by Rovai211** [comment]
Also, the validator mostly just told me all my textures were missing. 'xD

**Comment by scurest** [comment]
I don't know what Oculus Quest Home Environment is, but ideally the bug would get reported there and fixed.

In the meantime, you can workaround the issue in Blender 2.91, but you'll need to modify a file. You already found the `io_scene_gltf` folder I believe, so go there, then `blender/exp/gltf2_blender_gather_primitive_attributes.py`. Open it in a text editor and look for these two lines near the bottom (there's a line that says `# joints` a bit above them in case that helps)

https://github.com/KhronosGroup/glTF-Blender-IO/blob/5c0bc25d44d13eaf3e901e801c9a1642ada80423/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitive_attributes.py#L185-L186

Delete those two lines. Close Blender and re-open it, and the glTFs you export should now work.

**Comment by donmccurdy** [comment]
I'd recommend reporting a bug to Oculus if possible.

Another workaround would be to patch the file itself with a script, like:

```js
// convert_joints_ubyte_to_ushort.js
const { NodeIO } = require('@gltf-transform/core');

const INPUT = 'CesiumMan_ubytes.glb';
const OUTPUT = 'CesiumMan_ushorts.glb';

const io = new NodeIO();
const doc = io.read(INPUT);

for (const mesh of doc.getRoot().listMeshes()) {
	for (const prim of mesh.listPrimitives()) {

		let joints, i = 0;
		while (joints = prim.getAttribute(`JOINTS_${i++}`)) {
			joints.setArray(new Uint16Array(joints.getArray()));
		}

	}
}

io.write(OUTPUT, doc);

```

```
npm install @gltf-transform/core
node ./convert_joints_ubyte_to_ushort.js
```
