### ISSUE TITLE
Custom metal/rough node (legacy) does not export alpha

### ISSUE THREAD

**Issue by davidfrerichs** [KhronosGroup/glTF-Blender-IO#1287]
Exporting material glTF 2.0 from Blender always results in an alpha value in BaseColorFactor of 1 in the glTF file even though alpha is set to 0.7 in the BaseColorFactor of the glTF Metallic Roughness node material.

1. Create an object
2. Append reference materials from glTF2_Principled.blend (version attached)
3. Assign material with translucency to object
4. In material Settings > Viewport Display > Settings, set Blend Mode to Alpha Blend
5. Export glTF 2.0 with materials included

Sample .blend file attached.

Expected output:
`{
            "alphaMode" : "BLEND",
            "doubleSided" : true,
            "name" : "cubematerial",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    1,
                    0.015001913532614708,
                    0.012381547130644321,
                    0.7
                ],
                "metallicFactor" : 0.800000011920929,
                "roughnessFactor" : 0.5
            }
        }
`

Actual output:
`{
            "alphaMode" : "BLEND",
            "doubleSided" : true,
            "name" : "cubematerial",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    1,
                    0.015001913532614708,
                    0.012381547130644321,
                    1
                ],
                "metallicFactor" : 0.800000011920929,
                "roughnessFactor" : 0.5
            }
        }
`

[cube_material_test.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5648013/cube_material_test.blend.zip)
[glTF2_Principled.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5648014/glTF2_Principled.blend.zip)

**Version**
 - OS: Mac OS Mojave
 - Blender Version 2.91 with manually updated glTF exporter version 1.5.6

**Comment by donmccurdy** [comment]
Note that in all versions of this exporter 2.80+, we recommend using the Principled BSDF material that is included with Blender. This workflow supports alpha. We are maintaining support for the older custom nodes (as in your example here) to help with backward-compatibility for older scenes, but will not be adding [new material features](https://www.khronos.org/news/press/khronos-releases-wave-of-new-gltf-pbr-3d-material-capabilities) to it moving forward.

@emackey any thoughts on this? It does seem like a regression in support for the older materials, seems reasonable to fix?

**Comment by davidfrerichs** [comment]
it was not clear to me from the documentation that Principled BSDF is now the preferred material method. very good to know. a bit of a bummer, though, because i had just finished migrating all the materials in a big project away from Principled BSDF to glTF Metallic Roughness based on various articles I found addressing the topic. if the bug for glTF Metallic Roughness could be fixed such that it does pick up the alpha channel value from BaseColorFactor, that would be super helpful.

**Comment by donmccurdy** [comment]
Ouch, I'm sorry for the confusion! The Principled BSDF was added in Blender 2.79 I think, we switched shortly afterwards for a number of reasons. If you can point us to the outdated articles we may be able to help get those updated for the next reader. We also maintain [Blender's docs for this addon](https://docs.blender.org/manual/en/2.91/addons/import_export/scene_gltf2.html), so those are a reliable source of information that can be helpful if/when you get into more complex materials.

I do think we should be able to fix the regression on the custom node, though, we'll look into that.

**Comment by davidfrerichs** [comment]
Thank you very much for your hard work on this project!

Looking back, the core problem was confusion between documentation for the outdated "glTF-Blender-Exporter" vs. the current "glTF-Blender-IO." Google searches trying to figure out why alpha wasn't exporting in glTF from Blender ended up deep linking into [the Exporter documentation](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/docs/user.md#alpha). 

As such, I didn't immediately realize that there was a new glTF-Blender-IO project. Although the README for the Exporter project says it is depreciated, I didn't end up there until later due to the deep linking. This problem might be mitigated with a few more alerts sprinkled around the older docs about the depreciation of Exporter along with a "what's different about materials for glTF in Blender 2.8+" callout in the [new IO documentation on Blender.org](https://docs.blender.org/manual/en/2.91/addons/import_export/scene_gltf2.html) In addition to talking about Principled BSDF materials, it could specifically say that glTF Metallic Roughness materials used for Blender 2.7x are no longer the recommended path.

Thanks!

**Comment by julienduroure** [comment]
This ticket is quite old, and seems that it not based on recent version using Principled Shader.
So, I will close this ticket.
If you have any issue with last versions, don't hesitate to open a new ticket.
Thanks!
