### ISSUE TITLE
Improve handling of missed textures?

### ISSUE THREAD

**Issue by vergol** [KhronosGroup/glTF-Blender-IO#1296]
When textures are stored externally, and when some of them are not available (i.e. not present in the dir with .gltf), the importer will remove the reference to this texture completely.
Can we change this, so when texture is not available, the texture slot will be still there? (and the texture will be displayed as pink by default, then)

I'm currently on 2.90.1 with unmodified gltf addon.

**Comment by scurest** [comment]
+1, this would be consistent with .obj importer too. bpy_extras.image_utils.load_image has [some code to create a placeholder image](https://github.com/dfelinto/blender/blob/eb7550a861724db537764080fe79405566445c89/release/scripts/modules/bpy_extras/image_utils.py#L90-L94) we could reference.
