### ISSUE TITLE
Export: emission materials export too bright

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1301]
A basic emission material like this

![emis](https://user-images.githubusercontent.com/11024420/103050211-698a2880-4559-11eb-9640-ea226cd6c7d8.png)

exports as

```
  "materials": [
    {
      "emissiveFactor": [1, 0, 0],
      "pbrMetallicRoughness": {},
      ...
    }
```

Since pbrMetallicRoughness is omitted, the defaults are baseColor=[1,1,1,1], metallic=1, roughness=1. This is much too bright.

![out](https://user-images.githubusercontent.com/11024420/103050596-4f9d1580-455a-11eb-9cfa-5138d02b1cca.png)

Messing around in Blender to find an equivalent-looking Principled node, baseColor=[0,0,0,1], metallic=(anything), roughness=1 is much better.

> _Note:_ This material setup was discussed at https://github.com/KhronosGroup/glTF-Blender-IO/pull/1209#issuecomment-693649108.

**Comment by emackey** [comment]
Good catch, the exporter should produce `baseColor: [0, 0, 0, 1]` for materials like this.

**Comment by julienduroure** [comment]
@scurest @emackey Can you please have a look on #1569 ?
