### ISSUE TITLE
Children Instancing not supported

### ISSUE THREAD

**Issue by zauberparacelsus** [KhronosGroup/glTF-Blender-IO#1303]
**Describe the bug**
Objects in blender, if a parent of a child object, can produce instances of that child object at either vertices or faces.  The GLTF exporter in blender appears to ignore these instanced objects and excludes them from the export.  What winds up being exported is the original instance of the child object, and instead of exporting its parent object an empty gets exported

**To Reproduce**
1. Download and open this file: [ChildInstancingBug.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5752599/ChildInstancingBug.blend.zip)
2. Export as GLTF
3. Open new scene, then import the GLTF

**Expected behavior**
All instances of the child object should be exported as instanced objects.

**Screenshots**
Before Export:
![image](https://user-images.githubusercontent.com/548168/103321940-05a8a980-4a0a-11eb-9648-4fd6cb7da1b6.png)

After Import:
![image](https://user-images.githubusercontent.com/548168/103321948-10633e80-4a0a-11eb-8ec7-102b89b8e586.png)

**Version**
 - OS: 64bit Manjaro Linux, kernel 5.7.19
 - Blender Version: 2.91, build hash b50598bc78c7

**Comment by emackey** [comment]
I wonder if this would be a good way to hook up support for [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_mesh_gpu_instancing)?

**Comment by julienduroure** [comment]
This will be fixed on #1378

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
