### ISSUE TITLE
Export: skin weights not normalized when using "Include All Bone Influences"

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1304]
The WEIGHTS_n arrays are normalized [only if "Include All Bone Influences" is off](https://github.com/KhronosGroup/glTF-Blender-IO/blob/04e26bef903543d08947c5a9a5fea4e787b68f17/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitive_attributes.py#L197-L203). If "Include All Bone Influences" is on, and a mesh has non-normalized weights in Blender, the exported .gltf will have non-normalized weights and be invalid.

**Comment by ninjz** [comment]
I see that there is a warning in there that says "WARNING There are more than 4 joint vertex influences. The 4 with highest weight will be used (and normalized)." 

Shouldn't that mean if there are say 8 bone influences, when `gltf_all_vertex_influences` is off then it should take the 4 of the 8 highest weights and then normalize them? According to the code here I think in this case it's just ignoring the rest of them in the break statement and then just normalizing the first 4.

**Comment by julienduroure** [comment]
At this stage of code, weights are already sorted, so first 4 are the 4 highest.
