### ISSUE TITLE
GLTF export *always* changes original texture names

### ISSUE THREAD

**Issue by Sand3r-** [KhronosGroup/glTF-Blender-IO#1311]
**Describe the bug**
GLTF export **always** changes original texture names

**To Reproduce**
1. Export a GLTF scene
2. Verify if the image names have been altered to `Image-1`, `Image-2,` etc.

**Expected behavior**
If possible, the texture images shouldn't have their names changed after exporting

**Version**
 - OS: Windows 10
 - Blender Version 2.83

**Additional context**
The bug is caused by `instanceof` not properly detecting that `fill` is of a `FillImage` class type:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/36007185e69b271e8343960e71330b449a7f090c/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py#L115

No idea what's the cause of this issue. I have temporarily fixed it locally by substituting the line with
```python
if str(type(fill)) == str(FillImage):
```

**Comment by scurest** [comment]
I can't reproduce. It doesn't seem like it should matter, but can you test with a 2.92 alpha downloaded from https://builder.blender.org/download/?
