### ISSUE TITLE
Unselected objects get exported

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#1313]
Hi!

I am encountering a model exporting issue.

**Describe the bug**
I have a scene with one tree model and one animated horse model. I want to export only the tree model, so I select it only and upon export, I enable the "**Selected Objects**" option but it also exports an empty node for each bone of the horse.

**To Reproduce**
1. Open the attached file with blender **2.91.0**
2. Select tree model and export it to gltf (with "**glTF Separate**" format and "**Selected Objects**" enabled)
3. Open the exported gltf file and you will notice it contains extra nodes with the name "Bone0XX" which belong to the horse rig.

**Expected behavior**
It should only export the selected tree model.

**.blend file/ .gltf**

[model.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5824220/model.zip)

**Version**
 - OS: linux mint
 - Blender Version 2.91.0

**Comment by Ali-RS** [comment]
Anyone can confirm this, please?

**Comment by scurest** [comment]
This is #1298.

**Comment by Ali-RS** [comment]
Ok, thanks. For now, going to put them in separate blend files, until this bug is fixed.

**Comment by julienduroure** [comment]
Merged
