### ISSUE TITLE
Emissive color export does not work when exporting to glTF2.0

### ISSUE THREAD

**Issue by Geomazzix** [KhronosGroup/glTF-Blender-IO#1315]
Description:
When exporting a glTF model with an emissive color the color that is specified in blender doesn't get taken into account when reading from the exported glTF file.

1. Import a model that uses the full glTF PBR specification.
2. Implement the nodes as shown in the blender gltf 2.0 [manual](https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html).
3. Change the color of the emissive texture by adding an extra color multiply node in between the texture and the emission shader node.
4. Export the model and notice that it did not change the color in the glTF file at all. Instead it just sets the value to (1,1,1)

Expected result
I expect after the model is exported that the emission factor has changed to the values I specified it.

Context screenshot:
![image](https://user-images.githubusercontent.com/21193712/104937668-54fd4c80-59ae-11eb-90ae-40529ae0ae8d.png)

Software:
 - OS: Windows 10 Pro v.19042.685
 - Blender Version: 2.90.1, branch: master, commit date: 2020-09-23 06:43, hash: 3e85bb34d0d7, type: Release
build date: 2020-09-23, 08:36:20

**Comment by scurest** [comment]
This was fixed in Blender 2.91. Also you don't need the Emission and Add Shader nodes, just plug the emission color into the Emission socket on the Principled node.

**Comment by Geomazzix** [comment]
Checked and works, thanks for the heads up, I did not realize there was a new blender version out yet. Sorry for the troubles.

**Comment by emackey** [comment]
@Geomazzix No worries! Also make sure you're using a modern link to the [Blender Manual](https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html).  The one you quoted is for 2.80 and is dated.
