### ISSUE TITLE
Shader Editor nodes are not included for export to glp/gltf file?

### ISSUE THREAD

**Issue by FabiDau** [KhronosGroup/glTF-Blender-IO#1319]
Hey,

Im trying to export my new created Leek. I used this Settings: 

![1](https://user-images.githubusercontent.com/26712329/106059824-9058f300-60f3-11eb-9b84-fbc846444e2e.PNG)

I tried mutlible times to export it in different ways as glpt or glb. I think it is just not possible to export it with the color ramp..
If i test the file on https://gltf-viewer.donmccurdy.com/ it looks like this: 

![1](https://user-images.githubusercontent.com/26712329/106060377-44f31480-60f4-11eb-9cbd-3d423eefdc8d.PNG)

Is this a Bug or just not intendet. Is there a better way to add the textures? This was a pretty easy way and I'm still a beginner in Blender. I'm planing to use these assets with Three.js GLTFLoader.

![2](https://user-images.githubusercontent.com/26712329/106060453-63591000-60f4-11eb-90b0-1d42f7e224a2.PNG)

Greetings and sorry for wasting your time :)

**Comment by donmccurdy** [comment]
Hi @FabiDau — Blender's shading nodes cannot be exported to any standard format I'm aware of, including glTF/GLB. They exist only in Blender. To create materials that can be exported and supported in other software you'll need to structure materials as shown in the Blender glTF addon documentation:

https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html

Notably, the inputs to most Principled BSDF sockets should be either a number, a solid color, or a texture. For your color ramp shown above, it should be possible to bake that into a diffuse texture using Blender, or to paint it as vertex colors. But you'd need to do that conversion before exporting to glTF. This tutorial might help:

https://www.youtube.com/watch?v=o0lTz25xcx0

**Comment by emackey** [comment]
Oh hey if we're plugging YouTube videos that cover glTF creation in Blender, I'll shamelessly promote my own here:

[![The glTF Authoring Pipeline](https://user-images.githubusercontent.com/1235080/106181576-c76aeb00-616b-11eb-880e-d55620857e79.jpg)](https://www.youtube.com/playlist?list=PLvdhJ__UbhZ6mst0xgd_S3oSmdRcEiKCp)

**Comment by hichemfantar** [comment]
commenting to mark this because i have a similar use case with color ramps that need to be exported
