### ISSUE TITLE
All export formats are embedding texture buffers

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#132]
It appears that all export format options, including `JSON (.gltf + .bin + textures)`, are embedding texture buffers in the `.gltf` or `.bin` file, even when the textures are exported separately and called externally.

I'd mostly expect the buffers to be embedded for `.glb`, but there doesn't appear to be a way to _not_ embed them in `.gltf` or `.bin`.

![image](https://user-images.githubusercontent.com/4733018/49409145-464f6f00-f72d-11e8-9a3d-24cb05f1073a.png)

My guess is that the now removed `Embed buffers` option might now be automatically defaulting to true regardless of whether or not the buffers are used, but you folks would know better than I.

![image](https://user-images.githubusercontent.com/4733018/49409315-1d7ba980-f72e-11e8-87ba-b297bb61e94e.png)

**Comment by donmccurdy** [comment]
Hm, yeah textures were meant to be separate for the `JSON (.gltf + .bin + textures)` option, and embedded in the other two. Sounds like a bug in my earlier PR.

**Comment by UX3D-schmithuesen** [comment]
Just for documentation purposes: Not only do both **gltf** variants export image data twice (as image file and as part of the binary buffer), but they also reference **both** representations in the json (see below).
```
{
    "bufferView" : 4,
    "mimeType" : "image/png",
    "name" : "UVdark.tga",
    "uri" : "UVdark.png"
}
```
