### ISSUE TITLE
Blender 2.91 on Pop OS 20.10 crashes on export

### ISSUE THREAD

**Issue by Dorro101** [KhronosGroup/glTF-Blender-IO#1321]
**Describe the bug**
Blender 2.91 on Pop OS 20.10 crashes on export

**To Reproduce**
Go to File>Export>glTF 2.0 (.glb/gltf)
Crashes on select

**Expected behavior**
Export dialog to open

**Screenshots**
Pretty simple crash, explanation is clearer

**.blend file/ .gltf**
It happened the first time I tried to export a test file, same happened in 2.90.1, and 2.83.9, I haven't downloaded latest LTS release yet. Update: Same for 2.91.2 and 2.83.12

**Version**
OS: linux

![Screenshot from 2021-02-01 11-05-09](https://user-images.githubusercontent.com/54166678/106410366-abbe5800-647d-11eb-8124-3254d2ee12eb.png)

 Blender Version: 2.83.9, 2.83.12, 2.90.1, 2.91.0 and 2.91.2 standalone versions from blender.org with separate .config folders.

**Additional context**
I found a solution for the problem, fixed it by editing a python __init file in my .config folder, dialogue popped up and I was able to export my test file. 

From : https://developer.blender.org/T83685...

"We have a identified a potential cause in T84752. Given that the provided stack trace here also goes through ctypes and has similar symptoms, I believe this is the same problem. This might be caused by the function CFUNCTYPE(c_int)(lambda: None) called by _reset_cache in 2.9x/python/lib/python3.7/ctypes/__init__.py which has been removed in newer versions of Python.

Could you please create a copy of the __init__.py file and rename it to have a copy of the original. Then edit the __init__.py and remove the line from the file, then check if the crash still occurs? It should be line 273. Afterwards you can remove the edited file rename the copy back to __init__.py."

**Comment by julienduroure** [comment]
As you said, this problem come from Blender API, and need to be fixed on Blender side, not on this addon side.

For any news from Blender, please follow https://developer.blender.org/T84752

**Comment by Dorro101** [comment]
I reported the crash to blender as well, I will follow up in the thread provided. Thank you!

**Comment by mshibili** [comment]
Same issue after few time working with blender.

**Comment by julienduroure** [comment]
https://developer.blender.org/T84752 is now solved in Blender, so the next stable version (2.93) will work as expected
