### ISSUE TITLE
Background node

### ISSUE THREAD

**Issue by mohsen123** [KhronosGroup/glTF-Blender-IO#1324]
Hi
once I add a background node to my materials I get this error in export:
I'm using the last code here and Blender 2.90
:/ 

thanks

> bpy.ops.mesh.primitive_torus_add(align='WORLD', location=(0, 0, 0), rotation=(0, 0, 0), major_radius=1, minor_radius=0.25, abso_major_rad=1.25, abso_minor_rad=0.75)
bpy.ops.transform.translate(value=(-0, -3.04025, -0), orient_type='GLOBAL', orient_matrix=((1, 0, 0), (0, 1, 0), (0, 0, 1)), orient_matrix_type='GLOBAL', constraint_axis=(False, True, False), mirror=True, use_proportional_edit=False, proportional_edit_falloff='SMOOTH', proportional_size=1, use_proportional_connected=False, use_proportional_projected=False, release_confirm=True)
bpy.ops.material.new()
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=570, mouse_y=328, extend=False, deselect_all=True)
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=617, mouse_y=250, extend=False, deselect_all=True)
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(-108.732, -3.40393, 0), "orient_type":'GLOBAL', "orient_matrix":((1, 0, 0), (0, 1, 0), (0, 0, 1)), "orient_matrix_type":'GLOBAL', "constraint_axis":(False, False, False), "mirror":True, "use_proportional_edit":False, "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "use_proportional_connected":False, "use_proportional_projected":False, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "cursor_transform":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":False, "use_accurate":False, "use_automerge_and_split":False}, NODE_OT_attach={}, NODE_OT_insert_offset={})
bpy.ops.node.delete()
bpy.ops.node.add_file(filepath="F:\...\Image.jpg")
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=619, mouse_y=173, extend=False, deselect_all=True)
bpy.ops.node.link(detach=False)
bpy.context.space_data.system_folders_active = 3
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 561, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1204, in to_dict
    self.materials)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: <unknown location>:-1

bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=685, mouse_y=258, extend=False, deselect_all=True)
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=512, mouse_y=198, extend=False, deselect_all=True)
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(-221.711, 24.6785, 0), "orient_type":'GLOBAL', "orient_matrix":((1, 0, 0), (0, 1, 0), (0, 0, 1)), "orient_matrix_type":'GLOBAL', "constraint_axis":(False, False, False), "mirror":True, "use_proportional_edit":False, "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "use_proportional_connected":False, "use_proportional_projected":False, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "cursor_transform":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":False, "use_accurate":False, "use_automerge_and_split":False}, NODE_OT_attach={}, NODE_OT_insert_offset={})
bpy.context.object.active_material_index = 0
bpy.ops.node.select(wait_to_deselect_others=False, mouse_x=635, mouse_y=250, extend=False, deselect_all=True)
bpy.ops.node.clipboard_copy()
bpy.ops.node.clipboard_copy()
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=524, mouse_y=156, extend=False, deselect_all=True)
bpy.ops.node.clipboard_paste()
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=564, mouse_y=247, extend=False, deselect_all=True)
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(-16.1399, 64.6747, 0), "orient_type":'GLOBAL', "orient_matrix":((1, 0, 0), (0, 1, 0), (0, 0, 1)), "orient_matrix_type":'GLOBAL', "constraint_axis":(False, False, False), "mirror":True, "use_proportional_edit":False, "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "use_proportional_connected":False, "use_proportional_projected":False, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "cursor_transform":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":False, "use_accurate":False, "use_automerge_and_split":False}, NODE_OT_attach={}, NODE_OT_insert_offset={})
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=532, mouse_y=320, extend=False, deselect_all=True)
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(0.849469, -21.2746, 0), "orient_type":'GLOBAL', "orient_matrix":((1, 0, 0), (0, 1, 0), (0, 0, 1)), "orient_matrix_type":'GLOBAL', "constraint_axis":(False, False, False), "mirror":True, "use_proportional_edit":False, "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "use_proportional_connected":False, "use_proportional_projected":False, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "cursor_transform":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":False, "use_accurate":False, "use_automerge_and_split":False}, NODE_OT_attach={}, NODE_OT_insert_offset={})
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=335, mouse_y=254, extend=False, deselect_all=True)
bpy.ops.node.link(detach=False)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 561, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1204, in to_dict
    self.materials)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: <unknown location>:-1

bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=729, mouse_y=322, extend=False, deselect_all=True)
bpy.ops.node.link(detach=False)
bpy.context.space_data.shader_type = 'OBJECT'
bpy.context.space_data.shader_type = 'WORLD'
bpy.ops.node.select(wait_to_deselect_others=False, mouse_x=575, mouse_y=179, extend=False, deselect_all=True)
bpy.ops.node.clipboard_copy()
bpy.ops.node.clipboard_copy()
bpy.context.space_data.shader_type = 'WORLD'
bpy.context.space_data.shader_type = 'OBJECT'
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=511, mouse_y=301, extend=False, deselect_all=True)
bpy.ops.node.clipboard_paste()
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=581, mouse_y=174, extend=False, deselect_all=True)
bpy.ops.node.translate_attach(TRANSFORM_OT_translate={"value":(13.9529, 155.906, 0), "orient_type":'GLOBAL', "orient_matrix":((1, 0, 0), (0, 1, 0), (0, 0, 1)), "orient_matrix_type":'GLOBAL', "constraint_axis":(False, False, False), "mirror":True, "use_proportional_edit":False, "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "use_proportional_connected":False, "use_proportional_projected":False, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "cursor_transform":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":False, "use_accurate":False, "use_automerge_and_split":False}, NODE_OT_attach={}, NODE_OT_insert_offset={})
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=415, mouse_y=116, extend=False, deselect_all=True)
bpy.ops.node.link(detach=False)
bpy.ops.node.select(wait_to_deselect_others=True, mouse_x=653, mouse_y=271, extend=False, deselect_all=True)
bpy.ops.node.link(detach=False)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\__init__.py", line 561, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1204, in to_dict
    self.materials)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: <unknown location>:-1

**Comment by mohsen123** [comment]
[any.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5921262/any.zip)

**Comment by julienduroure** [comment]
Hello,

I can't reproduce for now.

This repository is tested and works with current master of blender. I can see that you are using 2.90, and maybe some API changes makes this current master addon version incompatible with 2.90
I can also see some "undefined" nodes in your tree when I open with 2.92, that let me know that this is maybe a version problem.

Can you please test with a recent build? (https://builder.blender.org/download/)

Thanks!

**Comment by mohsen123** [comment]
Thank you so much, In the new version I can export the Background node! and about the last one, It was one of the blander files I tested, I just opened the scene put texture and Background,
the Issue with the new Blander is that I Cant find the MOZ_Lightmap Settings node to use two UVs!
while the addon installed without any problem.
![error3](https://user-images.githubusercontent.com/5547808/106862128-ef160200-66db-11eb-8cb3-affa92ba9b16.jpg)

thanks

**Comment by mohsen123** [comment]
Solved, I just needed to press that load setting button at the start!
thank you so much!

**Comment by julienduroure** [comment]
Seems that MOZ_Lightmap is an extension that you need to reinstall on your new blender version : https://github.com/MozillaReality/hubs-blender-exporter

**Comment by mohsen123** [comment]
[Error.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/5926169/Error.txt)

What about Still having this issue with 2.92? could it be something from my file? I can't see any error in textures, nodes, etc...
:/

**Comment by scurest** [comment]
Does it still happen if you disabled the "Hubs Blender Exporter" add-on?
