### ISSUE TITLE
Increase Draco Compression

### ISSUE THREAD

**Issue by Piflyer** [KhronosGroup/glTF-Blender-IO#1325]
**Is your feature request related to a problem? Please describe.**
I'm trying to model a very large building, but the file output size is pretty large. I want to make it accessible to all users, therefore a higher compression limit for Draco would be great.

**Describe the solution you'd like**
Higher Draco compression limit.

**Comment by donmccurdy** [comment]
@UX3D-eckerlein if the Draco encoder supports values 0-10, do you know why this addon is currently limited to 0-6? Is there some difference with enabling the remaining four levels?

@Piflyer note that in the meantime you can also add Draco compression after exporting, using tools like glTF-Pipeline or glTF-Transform.

**Comment by UX3D-eckerlein** [comment]
I will have a look at it.

**Comment by UX3D-eckerlein** [comment]
I've just opened a PR #1336, which makes all compression levels Draco offers available to the user.
