### ISSUE TITLE
Animation with rotation around z-axis in Blender does not convert to y-axis in GLTF-export

### ISSUE THREAD

**Issue by rienheuver** [KhronosGroup/glTF-Blender-IO#1330]
**Describe the bug**
I have an object which has an animation with rotation around the z-axis and that scene is exported to GLTF, the scene will be converted to Y-up, but the animation appears not to. "Y-up" is enabled during export and the scene, except for the door, appear normally when exported. In fact, the door appears just fine as well, until the animation is started.

**To Reproduce**
1. Open the attached .blend-file
2. Play the animation for "Right.door"
3. Export to GLTF
4. Upload the .glb-file to https://gltf-viewer.donmccurdy.com/ and see the door animation being faulty.

**Expected behavior**
The door should animate as it does in Blender, instead of wrongly as shown in the gltf-viewer.

**.blend file/ .gltf**
https://we.tl/t-8hiGgS9rsY

**Version**
 - OS: Ubuntu 20.04 LTS, 64-bit X11
 - Blender Version: 2.91.2

**Comment by julienduroure** [comment]
Confirmed.
File provided is huge. I removed non needed data (texture, not needed objects, etc...).
Here is a simplier file : 
[texture-testing.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5990837/texture-testing.blend.zip)

As you can see, I created a new animation on the other door --> Same issue
I created a new animation on a newly added object --> No issue

Bug seems to be linked to the object?

**Comment by rienheuver** [comment]
I didn't know what in the scene was relevant and what wasn't, so thanks for thinning out the file. I found the same problem with new objects.
If it is of any help: I created the door by first extracting a face from the Wall-object and then modelled it using Auto-mirror. Don't know if that is of any importance. If there's anything else I can do to help please let me know.

**Comment by scurest** [comment]
The doors have a matrix_parent_inverse. Checking with the Python console, Blender seems to apply that only when the object has a parent. The exporter applies it even if the object doesn't have a parent. So this appears to fix it. 

<details>

<summary>Patch</summary>

```diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_samplers.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_samplers.py
index c3913367..46b083c9 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_samplers.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_samplers.py
@@ -57,6 +57,10 @@ def gather_animation_sampler(channels: typing.Tuple[bpy.types.FCurve],
                                                  driver_obj,
                                                  export_settings)
 
+    if blender_object.parent is not None:
+        matrix_parent_inverse = blender_object.matrix_parent_inverse.copy().freeze()
+    else:
+        matrix_parent_inverse = mathutils.Matrix.Identity(4).freeze()
 
     sampler = gltf2_io.AnimationSampler(
         extensions=__gather_extensions(channels, blender_object_if_armature, export_settings, bake_bone, bake_channel),
@@ -64,7 +68,8 @@ def gather_animation_sampler(channels: typing.Tuple[bpy.types.FCurve],
         input=__gather_input(channels, blender_object_if_armature, non_keyed_values,
                              bake_bone, bake_channel, bake_range_start, bake_range_end, action_name, driver_obj, export_settings),
         interpolation=__gather_interpolation(channels, blender_object_if_armature, export_settings, bake_bone, bake_channel),
-        output=__gather_output(channels, blender_object.matrix_parent_inverse.copy().freeze(),
+        output=__gather_output(channels,
+                               matrix_parent_inverse,
                                blender_object_if_armature,
                                non_keyed_values,
                                bake_bone,
```

</details>

But like I've said before, the exporter should just bake things, not attempt to replicate (poorly) everything Blender does to compute the world position.

**Comment by julienduroure** [comment]
I just created PR #1334 

I agree that we need to refactor heavily matrix data management.
My thought is that we first need to manage Virtual Tree for 2 passes export (#1244) first

**Comment by rienheuver** [comment]
Thanks both for finding the problem and working on it! I'd be glad to use this on Blender. Is there a workaround in the meantime? Or some way I can apply the patch and rebuild the plugin temporarily for example?

**Comment by scurest** [comment]
The addon doesn't have a build step. Just apply the patch to the right file. The addon that ships with Blender is located at (assuming Blender 2.91) `<your blender install dir>/2.91/scripts/addons/io_scene_gltf2`.

You could also run this script from the Text Editor and then export normally

```py
import bpy, mathutils
for ob in bpy.data.objects:
    if not ob.parent:
        ob.matrix_parent_inverse = mathutils.Matrix.Identity(4)
```

**Comment by rienheuver** [comment]
Ran your code in the text editor, worked like a charm. Thanks a lot @scurest!
