### ISSUE TITLE
Image URI not being exported when using images: 'automatic' option

### ISSUE THREAD

**Issue by dasco597** [KhronosGroup/glTF-Blender-IO#1331]
When selecting 'automatic' as shown in the following screenshot, the image URI fields are not getting filled.
![Capture (Small)](https://user-images.githubusercontent.com/44878819/108046260-51f08d00-703c-11eb-98a8-40bf90930c5c.PNG)

The reason is because the __gather_uri has an if statement that only exports the URI when export_settings[gltf2_blender_export_keys.FORMAT] == 'GLTF_SEPARATE' and when the 'automatic' option is chosen it is equal to 'gltf_format'.

Function in question:
io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py line 139
```
@cached
def __gather_uri(image_data, mime_type, name, export_settings):
    if export_settings[gltf2_blender_export_keys.FORMAT] == 'GLTF_SEPARATE':
        # as usual we just store the data in place instead of already resolving the references
        return gltf2_io_image_data.ImageData(
            data=image_data.encode(mime_type=mime_type),
            mime_type=mime_type,
            name=name
        )

    return None
```

How I fixed it:
```
@cached
def __gather_uri(image_data, mime_type, name, export_settings):
    # as usual we just store the data in place instead of already resolving the references
    return gltf2_io_image_data.ImageData(
        data=image_data.encode(mime_type=mime_type),
        mime_type=mime_type,
        name=name
    )
```
I have no idea what the intention of the if statement was, I don't see a scenario where you'd want to skip the URI field. But I'm not at all familiar with this project though, I'm sure there's a reason.

 - OS: Windows 10
 - Blender 2.91.2
 - glTF-Blender-IO master commit cb4b0e4a5b0e9dc263bc2cc30c9534cc1b1fe7a4

**Comment by scurest** [comment]
> I have no idea what the intention of the if statement was, I don't see a scenario where you'd want to skip the URI field.

If the export format is .glb or .gltf+embedded, the image data is put in the buffer embedded in the file and referenced by a bufferView instead of a URI.

https://github.com/KhronosGroup/glTF-Blender-IO/blob/cb4b0e4a5b0e9dc263bc2cc30c9534cc1b1fe7a4/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py#L81-L84

**Comment by dasco597** [comment]
ah I see, I just realised my screenshot has .glb selected instead of .gltf which is what I was trying to export. I just tried again to double check gltf embedded is selected as the format and gltf2_blender_export_keys.FORMAT is again equal to 'gltf_format' which appears to be the default value. So I geuss the bug is that gltf2_blender_export_keys.FORMAT isn't getting set properly?

**Comment by scurest** [comment]
gltf2_blender_export_keys.FORMAT is a constant.

https://github.com/KhronosGroup/glTF-Blender-IO/blob/cb4b0e4a5b0e9dc263bc2cc30c9534cc1b1fe7a4/addons/io_scene_gltf2/blender/exp/gltf2_blender_export_keys.py#L36

**Comment by dasco597** [comment]
oh whoops sorry I get it now so the URI only gets set when exporting as gltf separate. ok I'll close this. sorry for wasting your time
