### ISSUE TITLE
Import draco compressed gltf/glb

### ISSUE THREAD

**Issue by danielsegertun** [KhronosGroup/glTF-Blender-IO#1333]
Blender is able to export the models to draco compressed .glb files but not able to import them.
Not sure why this is like this but I guess since draco destroys the model it is hard to import. 

What I would like to do is to import the draco model into blender again to use blender as a rendering engine for some nicer lights shadows using cycles.

But this is a feature that I think alot of people want since they want to be able to use modes from the web. More and more 3D are coming to the web and its nice to download models and import them into blender.

If the models are draco then you first need to use a draco decompress and then import them. An extra step that is kinda boring.

**Describe the solution you'd like**
If I import a gltf or glb I would like it to get into blender. There are simple draco concerter 

**Describe alternatives you've considered**
Now I am solving it by using two types of models, draco and nondraco.

**Additional context**
Just love BLENDER and all good people that are contributing!

**Comment by scurest** [comment]
It should already work with latest 2.92/2.93. https://builder.blender.org/download/

**Comment by emackey** [comment]
@danielsegertun Let us know if you find problems importing Draco into 2.92+.  Thanks!

**Comment by danielsegertun** [comment]
Draco import seems to work excellent! Good work team!

**Comment by emackey** [comment]
Thanks especially to UX3D and Google, for Draco import.

**Comment by danielsegertun** [comment]
It worked! Thanks!

/Daniel
