### ISSUE TITLE
Docker: Outdated Blender Version

### ISSUE THREAD

**Issue by pepperoni505** [KhronosGroup/glTF-Blender-IO#1341]
It appears that the Dockerfile is using an outdated Blender version. Please consider updating it to the latest version. 

This issue possibly relates to #1320

**Comment by scurest** [comment]
Is the docker stuff even being used? Can it just be deleted?

**Comment by donmccurdy** [comment]
I'm not aware that the Docker containers are still needed for anything, no. I think it was part of the CI at some point, but isn't anymore. I don't expect that running this addon in Docker is particularly different from running any other part of Blender in Docker, so I don't see much point in trying to keep Docker files up to date and tested here.

@julienduroure @emackey any concerns if we remove these files?

**Comment by julienduroure** [comment]
No problem on my side, I never used it.
I don't know if this is used by someone.
