### ISSUE TITLE
Optionally merge opacity map with albedo on export

### ISSUE THREAD

**Issue by yehoshuaviles** [KhronosGroup/glTF-Blender-IO#1348]
**Is your feature request related to a problem? Please describe.**
This feature would eliminate needing to manually / programmatically edit materials later when a material must share an alpha channel separately from the albedo. This is to allow a dedicated alpha texture projecting on to a different UV channel.

**Describe the solution you'd like**
The ability to export the model without merging the dedicated alpha and albedo, thus being able to use another UV set.

**Describe alternatives you've considered**
Manually doing this.

**Additional context**
Say you have an unlit tree. You bake lighting on to the albedo. However, you want to maintain a detailed alpha. You would need a separate alpha texture with it's own UV coordinates.

**Comment by donmccurdy** [comment]
Sorry, the glTF format itself does not allow albedo and alpha to be split into separate textures. This is not something we can fix within the Blender addon. 

I think there might be some value in allowing textures that are not used by the glTF exporter to still be included in the file on export. i.e. this would allow you to reconnect the alpha texture in other software, or include textures meant for more custom things like lightmaps or animation. But that is the only option I can see here.
