### ISSUE TITLE
Export then import glb, not same data (skinning)

### ISSUE THREAD

**Issue by Snouf-ID** [KhronosGroup/glTF-Blender-IO#1349]
Hello,

When I export this model to glb and re-import it, if I delete armature, I observe that the mesh is no longer in its standard correct position.
If I export / import in fbx for example it works as expected.

Green : mesh when I delete armature
Red : mesh when I delete armature after export/import in glb

![bug_a_1](https://user-images.githubusercontent.com/47319640/110486088-97a8ee80-80ec-11eb-9c50-72b5fcf0fa05.png)

https://drive.google.com/file/d/1R31zmWWK6gdUfLsTCSPOzDqcbUV_vd3I/view?usp=sharing

**Comment by julienduroure** [comment]
This is now solved by using rest pose as default values for joint nodes
