### ISSUE TITLE
Strange skinning based issue I think...

### ISSUE THREAD

**Issue by Chadt54** [KhronosGroup/glTF-Blender-IO#1350]
**Describe the bug**
The geometry becomes stretched.

**To Reproduce**
1. Import into blender.

**Expected behavior**
Drag and drop the gltf into this web page (https://sandbox.babylonjs.com/) to view what it's supposed to look like. In Blender, the geometry gets stretched super far away for some reason.
![image](https://user-images.githubusercontent.com/1322965/110577730-3e16e300-8131-11eb-8485-ba1caa0abf98.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1322965/110577563-e0829680-8130-11eb-8a14-80b0af9fd8cf.png)

**.blend file/ .gltf**
[chn_flagA_all04.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6113221/chn_flagA_all04.zip)

**Version**
 - OS: Windows 10
 - Blender Version [all versions up to current (2.92)]

**Additional context**
None

**Comment by scurest** [comment]
The file has a bunch of validation errors. Can you fix those first?

**Comment by Chadt54** [comment]
Oh yeah, I see it does. Yeah, I can look into these first.

**Comment by julienduroure** [comment]
More than a year without any update. Closing this ticket
