### ISSUE TITLE
Exporting duplicate meshes causes exporter to fail when DRACO is enabled

### ISSUE THREAD

**Issue by ironvelvet** [KhronosGroup/glTF-Blender-IO#1351]
**Describe the bug**
I'm working on a very simple scene with 4 meshes, 1 of which is a duplicate of another one. Whenever I try to export that scene, I get an error in Blender 2.92 (see screenshots).

To make sure my scene is not the problem, I tried creating a brand new "General" scene in Blender, and simply duplicated the default cube. Sure enough, the same error shows up.

This happens only when the two items are exported together. Individually, they're fine. I haven't tried to play around with the settings too much apart from the Compression. I can confirm that without DRACO compression, the issue isn't happening.

**To Reproduce**
1. Create a default Blender project
2. Duplicate (SHIFT+D) default cube and move it anywhere
3. File > Export > glTF 2.0 (.glb/.gltf)
Options :

- Include : Selected Objects / Custom Properties
- Transform : +Y Up
- Geometry : Apply Modifiers / UVs / Normals / Materials : Export / Images : Automatic / Compression (default settings)
- Animation : nothing.

**Expected behavior**
An output gltf file, no error.

**Screenshots**
![blender_292_error](https://user-images.githubusercontent.com/58460073/110920701-fd2ff180-831d-11eb-818a-f6b8cfc275ed.png)

**Version**
 - OS: Mac OS 11.1 on a Mac Mini M1 (could this be an issue? I know everything is not perfect yet in this regard)
 - Blender 2.92

**Comment by scurest** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/issues/445#issuecomment-789283685

**Comment by UX3D-eckerlein** [comment]
Fixed by #1352
