### ISSUE TITLE
export gITF with not animate object parented to animated armature from mixamo

### ISSUE THREAD

**Issue by JoeJoeMango** [KhronosGroup/glTF-Blender-IO#1355]
I have a rigged body from mixamo and I am parenting some objects to the figure's head so that it animates with it. When I export gITF or GLB it only animates the figure. 

I have been trying many different combinations b object constraints but no luck. 

I am a bit of a noob when it comes to blender BTW

Any help would be appreciated
Thanks

**Comment by donmccurdy** [comment]
Would you be able to share a `.blend` that reproduces this issue?

Generally constraints cannot be exported unless they are baked into animation, but I'm surprised that parented objects are not animated with the parent in this case.

**Comment by julienduroure** [comment]
More than a year without any answer.
Closing this ticket
