### ISSUE TITLE
unable to export gltf file 

### ISSUE THREAD

**Issue by senciria** [KhronosGroup/glTF-Blender-IO#1356]
Hi, I downloaded the new version(2.92) and founds out that I am not able to export gltf file.
I imported the obj file into blender, without applied any texture on it, then I clicked export gltf, and error occurred after. This shows it's not able to export as gltf from blender.
I am still new in blender, but it didn't happen in the previous version(with the same obj file), does anyone know how to resolve this problem? Any information would be appreciated, thank you!

![blender](https://user-images.githubusercontent.com/81218429/112110287-5b30c480-8bbb-11eb-8801-7d81f6ced722.png)

**Comment by donmccurdy** [comment]
Could you share the `.blend` or the `.obj`? You can attach .ZIP files to GitHub comments. Without this it is very difficult for us to identify the issue.

**Comment by scurest** [comment]
#1351
