### ISSUE TITLE
Support multiple inteprolation methods in a single animation

### ISSUE THREAD

**Issue by dnachmanfx** [KhronosGroup/glTF-Blender-IO#1357]
If a single complex animation utilizes multiple interpolation methods, for example:

- keyframe 1->2 set to Lienar
- keyframe 2->3 set to Step

seems like the blender exporter will "give up", and instead:
- "presamle"/bake all the keyframes
- set interpolation to "Linear"

```
    "animations" : [
        {
            "channels" : [
                {
                    "sampler" : 0,
                    "target" : {
                        "node" : 0,
                        "path" : "translation"
                    }
                }
            ],
            "name" : "EmptyAction.002",
            "samplers" : [
                {
                    "input" : 0,
                    "interpolation" : "LINEAR",
                    "output" : 1
                }
            ]
        }
    ],
    "accessors" : [
        {
            "bufferView" : 0,
            "componentType" : 5126,
            "count" : 100,
            "max" : [
                4.166666666666667
            ],
            "min" : [
                0.041666666666666664
            ],
            "type" : "SCALAR"
        },
        {
            "bufferView" : 1,
            "componentType" : 5126,
            "count" : 100,
            "type" : "VEC3"
        }
    ],
```

This happens even if baking keyframes is disabled:
![image](https://user-images.githubusercontent.com/67193288/112345788-05990c80-8cce-11eb-9e96-61376c65e791.png)

As a result, we have to bake keyframes for all animations that utilize multiple interpolation methods.
Solving this could reduce size of exported gltf.

**Comment by donmccurdy** [comment]
To my understanding, the ability to set different interpolation modes on specific keyframes is a capability that exists in authoring software like Blender, but is not as common in realtime viewers for 3D files. Probably for that reason, the glTF format does not allow different interpolation methods on individual keyframes of the same animation channel, and so the animation must be baked.

If your main concern is reducing the size of the file, it's possible to resample the animation (after Blender bakes it) and this should reduce the size of the Step portions of the animation curve quite a bit. Resampling is not supported in Blender currently, but you can do it offline after export:

```
npm install --global @gltf-transform/cli 
gltf-transform resample input.glb output.glb --tolerance 0.0001
```

**Comment by julienduroure** [comment]
Seems we can close this ticket, as what is requested is now allowed by specification
