### ISSUE TITLE
GBL model will not display correctly when exported from blender.

### ISSUE THREAD

**Issue by Avallone92** [KhronosGroup/glTF-Blender-IO#1359]
I have a project where I need to get this watch into a functioning glb file, however the model becomes all distorted when exported. (Pictures below)

Does anyone have any idea why this might be happening? 

The shape is modified with armature/skeleton, However I do have another watch model that works perfectly with a skeleton, so I have trouble understanding why this model won't work.

Any tips/suggestions would help tremendously! 

![Watch_blender](https://user-images.githubusercontent.com/81451518/112706560-4f881b00-8ea5-11eb-97ab-5b8a4ee72e93.jpg)
![Watch_GLB](https://user-images.githubusercontent.com/81451518/112706562-52830b80-8ea5-11eb-8a08-a9c2d34160dd.jpg)

**Comment by julienduroure** [comment]
Hello,
Can you please share to .blend file?
We can't see what's wrong without some test cases.
Thanks!

**Comment by julienduroure** [comment]
We can't debug without the .blend file.
Closing this ticket.
Don't hesitate to comment if you have some news
