### ISSUE TITLE
Gltf format does not export any animation

### ISSUE THREAD

**Issue by wedoalargeamountoftrolling** [KhronosGroup/glTF-Blender-IO#1360]
**Describe the bug**
trying to export a animation on gltf format but no animation is exported apart from the model and armature

**To Reproduce**
1. export the model & armature with animations
2. import the gltf file on blender
3. there's absolutely no animations

**Expected behavior**
no animations are included in the armature, but when i select 1 action only the selected one gets exported with it

**.blend file/ .gltf**
here: https://www.mediafire.com/file/fbl4k9kkdvhpsbc/gun_animatiooons.blend/file

**Version**
 - OS: windows 8.1
 - Blender Version 2.9.2

**Comment by donmccurdy** [comment]
Related discussion: https://blenderartists.org/t/gltf-format-does-not-export-any-animation/1294112/2

**Comment by julienduroure** [comment]
Seems to be a duplicate of #763
