### ISSUE TITLE
Export: light intensity animation

### ISSUE THREAD

**Issue by Alexeyt89** [KhronosGroup/glTF-Blender-IO#1368]
Hello,
After creating light property animations (intensite, color, cone angle...) and exporting the model to glTF all the animations are lost.  Should some checkboxes be set to have such animations exported?
If it is not supported, it would be nice to have this feature in future Blender releases.

Best Regards

**Comment by donmccurdy** [comment]
Hi,

Sorry, the glTF format itself does not provide a way to include this type of animation at present. Feel free to comment on https://github.com/KhronosGroup/glTF/pull/1301 if you'd like to see that happen.

**Comment by julienduroure** [comment]
Let's keep this repository for Blender implementation only.
So closing this ticket, on continue discussion on glTF repository about this feature.
