### ISSUE TITLE
Blender 2.8 GLTF exports both URI and Bufferview for Images

### ISSUE THREAD

**Issue by viperscape** [KhronosGroup/glTF-Blender-IO#137]
The specification states only Bufferview or URI should be supplied in the gltf file, but both are present.
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/image.schema.json
This is a GLTF+Textures+Bin export I'm using in Blender 2.8 Beta (Dec 3), the bin file is big too so I wonder if the textures are being packed anyways. The gltf loader library I'm using won't work in this case, it causes a validation failure.

```json
"images" : [
        {
            "bufferView" : 5,
            "mimeType" : "image/png",
            "name" : "rock-mat_normal.bmp",
            "uri" : "rock-mat_normal.png"
        },
        {
            "bufferView" : 6,
            "mimeType" : "image/png",
            "name" : "rock-mat_diffuseOriginal.bmp",
            "uri" : "rock-mat_diffuseOriginal.png"
        },
        {
            "bufferView" : 7,
            "mimeType" : "image/png",
            "name" : "rock-mat_orm.png",
            "uri" : "rock-mat_ormrock-mat_orm.png"
        }
    ],
```

**Comment by emackey** [comment]
I'm seeing this too.

**Comment by donmccurdy** [comment]
Should have been fixed by https://github.com/KhronosGroup/glTF-Blender-IO/pull/133, which is not in the Beta release yet.

**Comment by julienduroure** [comment]
Is now merge in blender 2.8. Should be available in next build
