### ISSUE TITLE
Duplicate meshes upon export, and original model is shifted back

### ISSUE THREAD

**Issue by manglemix** [KhronosGroup/glTF-Blender-IO#1373]
**Describe the bug**
When trying to export the attached project file, the meshes of the three-part barrel and the shell container on the back are duplicated. The copies are resized and do not have the same parent as the original. The original model is also shifted along the y axis, but none of the objects show any change in their actual coordinates

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the project file given
2. Export as gltf (you will see the model shift)
3. Re-import the exported file (you will see the duplicate meshes)

**Expected behaviour**
I just want the exported file to represent the model completely, and not have the original model be altered

**Screenshots**
The original model, notice in the inspector the armature has no translation
![image](https://user-images.githubusercontent.com/38180553/114527874-0abcfc00-9c7b-11eb-9613-a532200d95d9.png)
After export, the model is shifted. Notice that the inspector still shows no translation
![image](https://user-images.githubusercontent.com/38180553/114527965-23c5ad00-9c7b-11eb-8c83-7d452e19f56e.png)
The exported model. The meshes are duplicated and are outside of the armature in the scene tree
![image](https://user-images.githubusercontent.com/38180553/114528068-3b9d3100-9c7b-11eb-9692-50eee76e6dd3.png)

**.blend file**
[turret_drone_1_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6302563/turret_drone_1_bug.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.92.0
 
Thank you guys in advance

**Comment by manglemix** [comment]
Also I should point out that there are animations for the barrel meshes. In the exported model, the animations are re-assigned to the duplicated meshes, not the original. So when I use this model, I have to not only delete the duplicated meshes, I also have to re-assign the re-assigned animations

**Comment by manglemix** [comment]
After some experimenting, I've determined that the animation is what's causing the problem. Delete the animations for the afflicted meshes in the NLA editor and you will see that the meshes are not duplicated anymore. The whole model still shifts after export though. Even remaking the meshes does not fix the problemd

**Comment by scurest** [comment]
Duplicate nodes when animating mesh parented to a bone is #1275.

**Comment by julienduroure** [comment]
This seems to be fixed in #1378

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
