### ISSUE TITLE
Importer add-on support (Import hooks)

### ISSUE THREAD

**Issue by Benjamin-Dobell** [KhronosGroup/glTF-Blender-IO#1377]
**Is your feature request related to a problem? Please describe.**
It's currently not possible (without resorting to hacks) to write a companion add-on (implementation of a GLTF extension) which supports round-tripping from Blender to GLTF and back again. 

**Describe the solution you'd like**
A reciprocal `glTF2ImportUserExtension` API which provides similar, albeit opposite, hooks to `glTF2ExportUserExtension`.

**Describe alternatives you've considered**
- Monkey patching.
- Provide a separate import feature which duplicates the GLTF parsing and inserts nodes derived from custom GLTF extensions into the appropriate place within the scene.
- Add the functionality to `io_scene_gltf2` directly.

**Additional context**
I've written a very basic add-on which exports lightmaps from Blender into GLTF, represented by a custom material extension. The lightmap is picked up from the `glTF Settings` pseudo-group i.e. same workflow as occlusion maps.

I'd like to be able to import lightmaps back into Blender.

**Comment by MeFisto94** [comment]
I want to bump that, are there any opinions on this?
What work is required? Could this be done relatively simple by starting off from the export extension?

**Comment by julienduroure** [comment]
I forgot to close this ticket, there is now an import addon extension system
