### ISSUE TITLE
there are some missing animations

### ISSUE THREAD

**Issue by mrParabol** [KhronosGroup/glTF-Blender-IO#1381]
I check the animations list and find out that there are some missing animations. my character has a total of 110 animations but only 15 animations exported. Is 15 the maximum number when exporting animation? what can I do?

**Comment by donmccurdy** [comment]
Hi! There is no maximum number of animations. There are certain requirements (e.g. that actions should be attached to an object by stashing or creating an NLA Track) and certain types of animations that are supported; these are documented in the Blender addon documentation: https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#animation

If you've reviewed those docs and feel that something is not being exported that should be, please share a `.blend` (you can attach ZIP files to github comments) and we will try to help debug the issue.

**Comment by mrParabol** [comment]
my problem is solved. resources that I have used:
https://www.versluis.com/2020/03/using-non-linear-animation-nla-features-in-blender-2-8/

https://blenderartists.org/t/gltf-format-does-not-export-any-animation/1294112/3
