### ISSUE TITLE
Wrong child transform exported

### ISSUE THREAD

**Issue by pkowal1982** [KhronosGroup/glTF-Blender-IO#1384]
**Describe the bug**
Exporting node tree with parent of type empty outputs wrong child transform.

**To Reproduce**
Open provided example scene.
Export both nodes to gltf file.
Import back gltf file.

**Expected behavior**
Imported nodes should look exactly the same as original ones.

**Screenshots**
![original](https://user-images.githubusercontent.com/19764492/116218498-dfdaa980-a74a-11eb-9300-290856575fee.png)
![roundtrip](https://user-images.githubusercontent.com/19764492/116218500-e0734000-a74a-11eb-8b5a-4a70f145b869.png)

**.blend file/ .gltf**
[hierarchy_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6383414/hierarchy_bug.zip)

**Version**
 - OS: Ubuntu 20
 - Blender Version 2.92.0 stable

**Comment by scurest** [comment]
This is #1083.

**Comment by julienduroure** [comment]
Closing this ticket, as we now have an option to export flatten tree (all object at root of scene), avoiding this issue
