### ISSUE TITLE
NLAs of multiple armatures not grouped together?

### ISSUE THREAD

**Issue by will-ca** [KhronosGroup/glTF-Blender-IO#1388]
**Describe the bug**
NLAs of different objects are sampled together by name, but NLAs of armatures aren't.

This creates problems when armatures depend on other armatures per NLA name through bone constraints.

![image](https://user-images.githubusercontent.com/37680486/116626097-3e19af00-a93a-11eb-8705-d3b3b68a4be7.png)

ConstrainedTrans is a mesh that has a constraint which depends on its parent, RealTrans. Sampled animations on ConstrainedConstraint for both GoUp and GoDown include the effects of that constraint given the matching action on RealTrans.

ConstrainedArmature has a bone constraint which depends on a bone in RealArmature. Instead of sampling GoIn and GoOut for ConstrainedArmature using that constraint with the matching action on RealArmature, both GoIn and GoOut for ConstrainedArmature are sampled with the currently active action on RealArmature, which is GoIn.

**To Reproduce**
Download, export, and view the actions from the attached .BLEND file.

**Expected behavior**
NLAs for different armatures are sampled together by name.

**.blend file/ .gltf**

[MultiNLATest1.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6401993/MultiNLATest1.blend.zip)
[MultiNLATest1.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6401994/MultiNLATest1.glb.zip)

**Version**
 - Blender 2.92

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

You now have an option to bake all object animation at export. It will take into account non directly object animated (animated via constraints instead of directly animated)
