### ISSUE TITLE
Confirm roughness channel

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#139]
I haven't fully debugged this yet, but it looks like the exporter may be placing the roughness image in the red channel, not the blue channel of the output.

I'll have more time to investigate tomorrow, sorry for the half-written issue here.

**Comment by UX3D-nopper** [comment]
Could reproduce it ... we have a look at it later.

**Comment by dsinni** [comment]
FWIW, I've been having a lot of issues trying to get `Metallic` and `Roughness` to work with `Principled BSDF`.

What's strange/interesting is that wiring up a texture through a `Separate RGB` node seems to generate/bake a new texture on export. Problem is that it doesn't seem to be utilized for `Metallic` or `Roughness`.

For instance, doing something like this:
![image](https://user-images.githubusercontent.com/4733018/49471298-815bac00-f7da-11e8-8d07-424f4dde2eb0.png)

Results in a new texture in export (`Rock_colRock_col.png`):
![image](https://user-images.githubusercontent.com/4733018/49470980-a865ae00-f7d9-11e8-91df-be37e0932f60.png)

This is the original/diffuse texture (`Rock_col.png`):
![image](https://user-images.githubusercontent.com/4733018/49471417-d8fa1780-f7da-11e8-9033-2890e3eeee09.png)

And this is the overall result (complete glossiness):
![image](https://user-images.githubusercontent.com/4733018/49471544-2bd3cf00-f7db-11e8-8f9c-3a28292fa6b9.png)

I've tried switching around some of the RGB channels, switching between `Color` and `Non-Color Data`, and duplicating textures to single-user with no luck so far.

I'm not exactly a Blender nodes guru, so I may be missing something, but I hope this helps in some way.

**Comment by UX3D-nopper** [comment]
Fixed here https://github.com/KhronosGroup/glTF-Blender-IO/commit/847703a1860dd18ed269ec821eaf76a335cc30ce
