### ISSUE TITLE
"Apply Modifiers" option only applies to main scene

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [KhronosGroup/glTF-Blender-IO#1391]
**Describe the bug**
With the "Apply Modifiers" option selected, only objects in the current scene will have their modifiers applied, while objects in other scenes will not have any modifiers applied.

**To Reproduce**
1. Create two scenes: "Scene 1" and "Scene 2".
2. Create one object in each scene. Apply an obvious modifier to the object in Scene 2.
3. Switch to scene 1 and export.
4. Preview the GLTF file.

**Expected behavior**
Modifiers in all scenes are applied

**Screenshots**
N/A

**.blend file/ .gltf**
N/A

**Version**
 - OS: Windows 10
 - Blender Version: 2.92.0

**Additional context**
None

**Comment by ColonelThirtyTwo** [comment]
Looks like in gltf2_blender_gather_nodes.py __gather_mesh: the depsgraph in `bpy.context.evaluated_depsgraph_get()` is somewhat specific to the current scene, and objects outside of the scene won't have their modifiers applied in `to_mesh`. So arguably a blender bug.

**Comment by ligaofeng0901** [comment]
same problem. and #1393 has not been merged

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
