### ISSUE TITLE
Importing glb loses armature

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#1392]
**Describe the bug**
When I export a glb from my blender file it fails to reimport the glb.

**To Reproduce**
1. Go to blend file
2. Click on export glb.
3. Open glb.
4. See invalid transforms in blender.

**Expected behavior**
Proper import.

**Screenshots**

![image](https://user-images.githubusercontent.com/32321/118414362-e7f67c80-b658-11eb-8585-095785fd9928.png)

![image](https://user-images.githubusercontent.com/32321/118414478-9ef2f800-b659-11eb-935b-de917ad82836.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

[[No Logic David] Banyan Dance - PartyWave (krump)-VNfYmEU4IvM.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6490124/No.Logic.David.Banyan.Dance.-.PartyWave.krump.-VNfYmEU4IvM.zip) glb.

[[No Logic David] Banyan Dance - PartyWave (krump).zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6490128/No.Logic.David.Banyan.Dance.-.PartyWave.krump.zip) Blend file.

**Version**
 - OS: win10
 - Blender Version 2.92.

**Additional context**
This is motion capture data.

**Comment by scurest** [comment]
The model spazzes out for a few frames at the beginning in the source .blend too. If I open the .blend, import the .glb, seek to frame 3, and do _Frame All_, the original and imported models are right on top of each other (in a nonsense pose), which means it roundtripped correctly.

**Comment by fire** [comment]
So you're saying I picked a bad frame to photograph and this issue can be closed.

**Comment by scurest** [comment]
Yes.
