### ISSUE TITLE
Import: bone rotates wrong way with Temperance (bug)

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1396]
This was reported at https://devtalk.blender.org/t/gltf-export-issue-upd-import-issue/18970.

In this [bed model](https://github.com/KhronosGroup/glTF-Blender-IO/files/6541389/bed.zip), the leg part of the bed rotates down in Blender. In Three and Babylon, it rotates up instead.

![out](https://user-images.githubusercontent.com/11024420/119546211-4ad2cc80-bd59-11eb-941e-fc2be363c494.jpg)

edit: only happens with "Temperance"
edit: think "Temperance" might just be a coincidence, it seems to be triggered by very specific numeric values

**Comment by scurest** [comment]
Update: So it works with Fortune but not Temperance.

The difference is not the imported keyframes (they are identical), the difference is the Edit mode Roll of Bone.002. With Temperance it is 0, but with Fortune it is 180 deg.

**Comment by scurest** [comment]
More weirdness: after importing, turn on Viewport Display > Axes and In Front for the arma so you can see the bone axes. Run this script

````py
import bpy
ebone = bpy.data.armatures[0].edit_bones['Bone.002']
ebone.length = 0.11045359214368487
````

Every time you run it, Bone.002's Z axis flips direction :o Why?!

**Comment by scurest** [comment]
More weirdness: If you set the editbone length first

````diff
diff --git a/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py b/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
index ef410ad5..041bf1eb 100644
--- a/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
+++ b/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py
@@ -145,8 +145,8 @@ class BlenderNode():
             arma_mat = vnode.editbone_arma_mat
             editbone.head = arma_mat @ Vector((0, 0, 0))
             editbone.tail = arma_mat @ Vector((0, 1, 0))
-            editbone.align_roll(arma_mat @ Vector((0, 0, 1)) - editbone.head)
             editbone.length = vnode.bone_length
+            editbone.align_roll(arma_mat @ Vector((0, 0, 1)) - editbone.head)
 
             if isinstance(id, int):
                 pynode = gltf.data.nodes[id]
````

The model is fixed! The roll is calculated as 180 deg.

**Comment by scurest** [comment]
Filed a Blender issue about the weirdness: https://developer.blender.org/T88581

**Comment by scurest** [comment]
I tracked this down, it's an issue with ill-conditioned numerical code in the bone matrix calculation (lots of previous tasks about it on d.b.o). I think #1397 is a good fix.

**Comment by julienduroure** [comment]
Note that original bug in blender should be fixed now.
No impact here, as glTF python code already use a workaround (#1397)
