### ISSUE TITLE
Incorrect export of cubicspline tangents.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#140]
This example shows four cases:

- STEP
- LINEAR
- CUBICSPLINE
- CUBICSPLINE + custom tangents

[InterpolationComparison.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2646315/InterpolationComparison.zip)

The first three look right, but the fourth is not giving the right result on export. Note that in https://gltf-viewer.donmccurdy.com you'll want to press "Play All" in the animation settings. Expected result: https://twitter.com/donrmccurdy/status/1070072979059466240.

**Comment by donmccurdy** [comment]
This seems highly likely to be part of what's breaking our skinning export, so I'm moving it to MS VII for triage. If it is unrelated, feel free to remove it.

**Comment by UX3D-becher** [comment]
fixed with #396
