### ISSUE TITLE
ShapeKeys on Character animation not exporting correctly.

### ISSUE THREAD

**Issue by shaykh-qasim** [KhronosGroup/glTF-Blender-IO#1404]
Hello,

I have a character animation based on ARMATURE and SHAPEKEYS(for eyelids, facial expressions, etc.) When I export it to GTLF, the armature animation works well, but the shape keys don't work (the eyelids not blink, the expression doesn't change).

I am attaching the blender file, and gtlf:
https://drive.google.com/drive/folders/1QIXlqVYGJXM6VmARLe7ERWmxhwtnBrcX

Please help. Stuck in a project.

Thanks

**Comment by julienduroure** [comment]
Hello,
I can't see any error here.
Viewing in https://gltf-viewer.donmccurdy.com/, you can see armature animation, but also other ones, that are shapekey animations.
Don't hesitate to refer to documentation (https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html) if you want to merge all animations into a single one, using NLA

Closing. Don't hesitate to comment and reopen if I miss something
