### ISSUE TITLE
No KHR_texture_transform when exporting.

### ISSUE THREAD

**Issue by jovcem** [KhronosGroup/glTF-Blender-IO#1406]
I have searched far and wide but cant get to export the texture mapping of the material textures to the glb/gltf.
I have found this [issue](https://github.com/KhronosGroup/glTF-Blender-IO/issues/113) which talks about some Texture Transforms checkbox which does not exist in the current blender version 2.93. I also found some information that all textures need to have the same transform but that does not work either.

Exported material in babylonjs
![The exported material rendered in babylon](https://user-images.githubusercontent.com/16411618/120791089-094dd880-c534-11eb-9269-d540ec4220a6.png)

Material in blender
![The material in blender](https://user-images.githubusercontent.com/16411618/120791142-1b2f7b80-c534-11eb-9339-e15bbff6ee05.png)

Material graph
![The material graph in blender](https://user-images.githubusercontent.com/16411618/120791189-2c788800-c534-11eb-916b-48d70bd305df.png)

**Comment by scurest** [comment]
Check the console for warnings. Looks like

https://github.com/KhronosGroup/glTF-Blender-IO/blob/6e90fb2facf0f9be2d3970d525c58f8fb3847b99/addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py#L144-L151

**Comment by jovcem** [comment]
Thanks, that seems to solve it.

**Comment by julienduroure** [comment]
Seems that there is no bug here in code, so closing
Don't hesitate to comment if you think there is still an issue
