### ISSUE TITLE
Object with bone parenting disappears at certain camera angles.

### ISSUE THREAD

**Issue by castelblends** [KhronosGroup/glTF-Blender-IO#1412]
**Describe the bug**
An object parented to an armature suddenly disappears when the armature is displaced from (0,0,0) on any direction. Box helpers, one  for the object and one for the armature indicates the reference point used by the camera frustum to cull the object is somewhere in between the two box helpers.
This is the example for the .blend file attached:
An object with armature and a red arrow used as origin reference.
![Screenshot from 2021-06-10 16-05-29](https://user-images.githubusercontent.com/61828683/121598496-dca43000-ca0f-11eb-9682-02ca03a4132f.png)

Here is the armature displaced 5m to the right. As you can see the green box helper belonging to the cube object is correctly in place while the armature helper (yellow) moved farther away than 5m.
![Screenshot from 2021-06-10 16-06-49](https://user-images.githubusercontent.com/61828683/121598600-fa719500-ca0f-11eb-9a16-68940bb96106.png)

When the camera is placed there the cube disappears right where the purple line is.
![Screenshot from 2021-06-10 16-06-50](https://user-images.githubusercontent.com/61828683/121598829-37d62280-ca10-11eb-924d-90b114fc62b5.png)

This is the scene made for testing.
![Screenshot from 2021-06-10 16-09-42](https://user-images.githubusercontent.com/61828683/121599031-81267200-ca10-11eb-977d-880c3ad77904.png)
Front view
![Screenshot from 2021-06-10 16-09-20](https://user-images.githubusercontent.com/61828683/121599012-79ff6400-ca10-11eb-8e65-2f8c30889365.png)

**To Reproduce**
On a new scene
1. Add a cube
2. Add an armature
3. Parent object to armature using  active weights
4. Displace armature from (0,0,0) on any direction. 
5. Export as GLB with default values.
6. Open in any viewer and move around until you hit the angle where the object disappears near the edge of the screen.

**Expected behavior**
Cube will disappear suddenly at certain camera positions.

**Screenshots**
This is the cube in don's viewer where If you move to the left just a little bit it will disappear completely. 
![Screenshot from 2021-06-10 17-13-30](https://user-images.githubusercontent.com/61828683/121598149-7fa87a00-ca0f-11eb-892a-045fbd1a8519.jpg)

**.blend file/ .gltf**

[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6634523/test.zip)

**Version**
 - OS: Ubuntu 20.04.2 LTS
 - GPUs:  780Ti / rtx3090
 - Nvidia driver metapackage from nvidia-driver-460 (proprietary, tested)
 - Blender Version 2.93

**Comment by donmccurdy** [comment]
This is related to https://github.com/mrdoob/three.js/issues/14499, and can occur in three.js-based viewers. The file itself is OK, though.

**Comment by castelblends** [comment]
Hi Don, thanks for the answer, much appreciated. 

Work had me putting out fires here and there and today I was able to dig into this again. 

I realized the test environment I was using was a clone from a folder using r120 and updated to r129 which improved the sudden disappearance  when location transforms are applied to the armature, so now if I want to have the armature moving around I parent it to an empty. Please note "improved", after testing the project's environment it still happens but not enough to bother the 
user. 

Frustum culling btw does work as a workaround but not in all cases. One of my clients has a platform where performance is the most important factor and as far I understand, not being able to cull objects keep the GPU/CPU running full. 


Again, thanks for your time.
