### ISSUE TITLE
Add a way so an extra add-on could provide engine specific material extensions.

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/glTF-Blender-IO#1413]
**Is your feature request related to a problem? Please describe.**

Godot users often request that we export materials as-is from Blender, including the whole node shader graph. For the most part this is now not so necessary given #1409 happened, but often users will do manual texture blending based on vertex colors and other techniques that require some material logic. 

As there is not really a standard way to export these types of more complex materials, we at some point created such a converted in our [Blender to Godot exporter](https://github.com/godotengine/godot-blender-exporter), but then again keeping an entire exporter just for this is overkill. The converter is there already and it works fine, though.

Given GLTF2 supports extensions, it would be great if we could somehow do a very simple modification to the GLTF2 exporter in a way where an add-on could supply custom material data. This way, our add-on would take the Blender material at the time of export, convert it to a Godot shader and export it in an extension tag in the JSON.

**Describe the solution you'd like**

I am not sure how this would work. While I know we could possibly do an add-on ourselves that converts this and saves them into a custom property, usability for this is kind of limited, as the conversion would need to be carried away manually every time the material is modified (in exchange to just when exporting, so user has to remember converting it manually before exporting), and also custom tags export would need to be switched on, whereas its off by default.

I can think of a few ways on how this could work:

* Ideally our add-on should be able to hook up to the GLTF2 exporter somehow and tell it "let me know when you are about to export a material, and I will give you some Python dictionary to blit into your file as JSON in the Material", besides your own export.
* Worst case, GLTF2 should just have some hook to let our add-on know that its about to export, so we convert the materials we want and put them as custom properties. This is simpler but a bit less ideal as we cant really create a proper Godot extension and we rely on parsing what Blender exports. Also it relies on users turning on custom property export.

**Describe alternatives you've considered**

As mentioned, having a tool to manually convert and save to custom properties, or export materials independently, although this is more cumbersome to the user.

**Additional context**
--

**Comment by julienduroure** [comment]
Do you check all the hook we already have to add some extra data during export?
There is a 
> gather_material_hook

that seems to be what you are looking for.
See 
* https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/example-addons/example_gltf_extension for more information.
* An example of implementation : https://github.com/takahirox/glTF-Blender-IO-materials-variants

**Comment by reduz** [comment]
wow, I can believe you already support this, you rock!

will get to work on this ASAP then, thanks hugely again!
