### ISSUE TITLE
Constant keyframes in animations

### ISSUE THREAD

**Issue by oallouch** [KhronosGroup/glTF-Blender-IO#1425]
Hi,

I'm quite new to Blender, but I've faced this issue.
I've put some constant keyframes, but I still see linear animations.
I have tried to check/uncheck the "Always Sample Animations" parameter, without success.
![image](https://user-images.githubusercontent.com/2777369/123526043-91f40a80-d6d5-11eb-8042-784898924dd0.png)

Thx in advance,

Olivier

_Originally posted by @oallouch in https://github.com/KhronosGroup/glTF-Blender-IO/issues/842#issuecomment-869063568_

**Comment by julienduroure** [comment]
In glTF specification, you can not mix multiple interpolation type.
A channel can be step (constant in Blender) or linear (as in Blender) or cubispline ( bezier in Blender), but you can not mix more that 1 type in a channel (and in animated property : only 1 type for translation, 1 for rotation, 1 for scale).

What you show in your screensot can not be converted as-is in glTF

**Comment by oallouch** [comment]
Aahhhh, ok.
So what can I do ? Do I change the mesh visibility ?

**Comment by julienduroure** [comment]
Not sure what you are trying to do, but I suggest to request some help directly on user forum / site like blenderartists (for example)
