### ISSUE TITLE
Tests: PulseAudio install failed

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1427]
Not sure why installation of PulseAudio failed

**Comment by scurest** [comment]
Dunno why it failed but the reason it's there is in the comment

https://github.com/KhronosGroup/glTF-Blender-IO/blob/0ccb1ae99da9382c96a3562d22e82828f2cbc45c/.github/workflows/ci.yml#L58-L60

Since that issue seems to have gotten fixed, try just deleting that block.

**Comment by julienduroure** [comment]
Seems to be solved by removing the installation. Upstream T88387 fixes the problem here --> PulseAudio no more needed
