### ISSUE TITLE
Un-pinning `Save Settings` throws `KeyError: 'key not found'`

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#143]
If you click `Save Settings` once to save, and again to un-pin the settings (presumably), `KeyError: 'key not found'` is thrown.

This happens every other time it is clicked.

![image](https://user-images.githubusercontent.com/4733018/49536765-48ccd880-f895-11e8-94b5-7300c3bc9d4a.png)

![image](https://user-images.githubusercontent.com/4733018/49536779-55e9c780-f895-11e8-86ff-80392b049801.png)

**Comment by UX3D-becher** [comment]
@UX3D-schmithuesen We should replicate the behaviour of the .fbx exporter.

**Comment by donmccurdy** [comment]
By that do you mean a "Presets" dropdown?

![screen shot 2018-12-11 at 12 36 17 pm](https://user-images.githubusercontent.com/1848368/49828715-6db3c680-fd41-11e8-838f-966f00748ecd.png)

**Comment by emackey** [comment]
I haven't been able to confirm this one as fixed.  If I toggle the pushpin on and off, I still see this error pop up.

**Comment by donmccurdy** [comment]
^The toggle has been removed entirely in https://github.com/KhronosGroup/glTF-Blender-IO/commit/cfe7f534db41c771a02a3dd7538600bd12130a29, I'm assuming @UX3D-becher means we'll refactor it to save a list of presets.

**Comment by emackey** [comment]
@donmccurdy Are we OK with per-project settings going away?  Some of my projects use "Apply Modifiers", some don't, some of them have individual Copyright banners that I would like to preserve, some have animations turned off intentionally, etc.

**Comment by donmccurdy** [comment]
While there are cases where per-project settings are helpful, I am OK with removing the current mechanism and using customizable presets, yes. Blender's existing OBJ, FBX, and COLLADA exporters have this same preset-based system. Moreover, the implementation is provided by Blender: https://docs.blender.org/api/blender_python_api_2_64_release/bpy.types.Operator.html#bpy.types.Operator.

**Comment by emackey** [comment]
Ok.  Consistency is good for Blender users, so I guess I'll start using the preset system when it arrives.
