### ISSUE TITLE
Support drag & drop

### ISSUE THREAD

**Issue by marcofugaro** [KhronosGroup/glTF-Blender-IO#1430]
Would be much quicker if .gltf and .glb files could be just dragged and dropped into blender, without doing all the importing stuff.

This is a feature that concerns the importer, not blender itself. Hence I am filing it as a feature request here.

**Comment by julienduroure** [comment]
This importer is an addon of Blender, that can use API provided by Blender.
I don't think this is something that is currently supported by Blender and its API, so this is not possible to implement it for now.
Only .blend file are currently able to open, link or append by Drag&Drop.

**Comment by marcofugaro** [comment]
Oh okay, thank you for the info!

**Comment by donmccurdy** [comment]
Related: https://developer.blender.org/T44670
