### ISSUE TITLE
Export with Translation, Rotation and Scale values rounded 

### ISSUE THREAD

**Issue by TBAndrade** [KhronosGroup/glTF-Blender-IO#1434]
This is a very specific request to reduce the size of the glb file. Is it possible to use this export script and set the number of decimal cases we export? Going from 1.25485246841... to 1.254. This will help in cases where the geometry has a lot of vertices and we need the file size to be small.

**Comment by julienduroure** [comment]
Hello,
This is a very specific request, and rounding values is not what we want for all users. 
I also don't think this is something we can enable via an option (too many option is always bad).

I think this is something you can perform by an external tool like https://github.com/donmccurdy/glTF-Transform

**Comment by TBAndrade** [comment]
Hi,

Thank you so much, ended up finding another solution to the
specific problem I had.
So happy to close that issue.

Best,
Tiago

>
