### ISSUE TITLE
Missing TEXCOORD_0 when exporting meshes with textures to GLTF

### ISSUE THREAD

**Issue by grzechog** [KhronosGroup/glTF-Blender-IO#1438]
Hi All,
I have been trying to export my torus mesh with a texture on it to GLTF (embedded or separate). The two objects (torus and plane) from my scene get exported into the file with textures, but the torus's texture does not show up. The [GLTF Viewer](https://gltf-viewer.donmccurdy.com/) throws error MESH_PRIMITIVE_TOO_FEW_TEXCOORDS, about the missing TEXCOORD_0 attribute in the material - "Material is incompatible with mesh primitive: Texture binding '/materials/1/pbrMetallicRoughness/baseColorTexture' needs 'TEXCOORD_0' attribute."

The scene and the texture renders correctly in Blender. Halp!

**Comment by julienduroure** [comment]
Hello,
Please provide your test file, as explained in ticket template.
We really need it in order to help you!

**Comment by grzechog** [comment]
Please find attached the test file.
[donut-with-filling.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6857984/donut-with-filling.zip)
Thank you in advance for your help!

**Comment by scurest** [comment]
He means the .blend file, not the .gltf file.

Make sure your mesh actually has a UV Map (you can't use generated or object texture coordinates or anything), and you didn't turn off the _Geometry > UVs_ checkbox on the export screen.

**Comment by grzechog** [comment]
Yup, creating the UV map helped. It works now. 

I'm sorry for wasting your time. I'll donate 10$ to the project immediately.

Thank you for your help.
