### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by pafurijaz** [KhronosGroup/glTF-Blender-IO#1446]
**Describe the bug**
I attached the file that I cannot export and it took me 3 hours to find the problem because the script does not indicate the object that creates problems.  but it generates a generic report, this is something that is not a big problem with a few objects but with my file with over 1700 objects it was difficult to locate the object.

```
Python: Traceback (most recent call last):
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/__init__.py", line 626, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 109, in __fix_json
    fixed[key] = __fix_json(value)
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 113, in __fix_json
    fixed.append(__fix_json(value))
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 109, in __fix_json
    fixed[key] = __fix_json(value)
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 113, in __fix_json
    fixed.append(__fix_json(value))
  File "/home/root/Software/blender-2.93.3/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 116, in __fix_json
    if int(obj) == obj:
ValueError: cannot convert float NaN to integer

location: <unknown location>:-1
```

**.blend file/ .gltf**
[Nan-float.blend.tar.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/6978810/Nan-float.blend.tar.gz)

**Version**
 - OS: Linux
 - Blender Version LTS 2.93.2 and the latest under development v3.00 daily build

**Comment by julienduroure** [comment]
Hello,
Confirmed, but not sure this is something we can work on.
The problem come from the mesh that is corrupt inside blender itself.
How to fix it:
* go to edit mode
* select all visible vertices
  * with Box or Circle selection, on wireframe mode
  * do not use A to select all
  * do not use L to selected linked vertices
* Invert selection by Ctrl+I
* You should now have 91 vertices selected
* Delete them ( X )
* You should now by able to export

If you now how you was able to produce this corrupt file don't hesitate to open a ticket on https://developer.blender.org/

**Comment by pafurijaz** [comment]
With OBJ exporter works well
![OBJ-saved](https://user-images.githubusercontent.com/11751383/129350600-e8f14ac4-f2fa-47e6-98c3-7a3d080d936b.png)

**Comment by pafurijaz** [comment]
Anyway thanks for the suggestion I will test your solution

**Comment by julienduroure** [comment]
I confirm that you mesh is corrupt, you can see it in UI :
![image](https://user-images.githubusercontent.com/1696020/129350947-16bb5ba7-4283-490d-8998-967614f14489.png)

**Comment by pafurijaz** [comment]
OK I try to make a bug report on Blender developer, I saw the nan number also in the new spreadsheet windows thanks, but why this with obj works?
![image](https://user-images.githubusercontent.com/11751383/129351626-dbcb7e7e-e4b6-4de3-beeb-423af400e96a.png)

**Comment by julienduroure** [comment]
Obj are exported but contains NaN values:
![image](https://user-images.githubusercontent.com/1696020/129559917-bf3fa35d-dab8-4d73-af7f-f849e17a2d7c.png)

Means that maybe other softwares are not able to import it correctly.

glTF specification enforces to write min/max values in json. Having NaN  values is not authorized in JSON

**Comment by lexaknyazev** [comment]
Besides JSON not supporting NaN values, glTF forbids them in binary mesh data as well. The IO plugin should probably either reject export operation until such vertices are removed or gracefully skip them.

**Comment by pafurijaz** [comment]
Well, if the exporter does not support this exception, it should be reported in the report which object or mesh contains the particular problem this could help when there are many objects, so as to be able to quickly identify the problem.

**Comment by pafurijaz** [comment]
By exporting this model in PLY format I can correct the problem by easily deleting the corrupted vertices, I have only deleted the vertices outside the model, and after this fix the exporter works.
Maybe can be useful for a fix inside the exporter.
![PLY-exported-model](https://user-images.githubusercontent.com/11751383/129720855-424ca700-581a-4822-8edf-b2b980de19f0.png)

**Comment by pafurijaz** [comment]
I got an answer, from the developers, and with this command executed in the python console in object mode **C.active_object.data.validate(verbose=True)** I was able to solve the problem by identifying the problem and eliminating the vertices which are actually very few (14)
Maybe this could be useful to create a solution in these cases.
![image](https://user-images.githubusercontent.com/11751383/130678562-c884f8f4-979a-4364-a58b-3a254dfa1a84.png)

**Comment by julienduroure** [comment]
@pafurijaz Thanks a lot. It seems to solve the issue
