### ISSUE TITLE
Conflict name of Object Data proprieties 

### ISSUE THREAD

**Issue by pafurijaz** [KhronosGroup/glTF-Blender-IO#1447]
I found another bug, I often duplicate parts of mesh to create curves from it, and this once converted they keep the same geometry name in the data properties, and I add files from external scenes and in this case I encountered a strange conflict error of names, I created a curve from a cube and in Blender two different geometries can have the same name in the **Object Data Proprieties**, but not the same object name, this somehow generates a strange error that occurs in the export of instances all with the same geometry of the mesh, as can be seen from the attached images below.  I have also attached a simple example file of this problem.

**Source geometry with same name of Object Data Proprieties in blender visible on the *Outliner***
![Source-geomtry](https://user-images.githubusercontent.com/11751383/129323162-d06e3a75-e47f-486f-be9e-14f0ddeae280.png)

**Exported geometry with same name of Object Data Proprieties has the same mesh geometry**
![exported_result](https://user-images.githubusercontent.com/11751383/129323317-8fd71925-dc8a-4f82-b296-faca39f974c8.png)

**.blend file/ .gltf**
[Name-conflict-blend-glb.tar.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/6980759/Name-conflict-blend-glb.tar.gz)

**Version**
 - OS: Linux
 - Blender Version 2.93.2-lts

**Comment by scurest** [comment]
This is fixed by #1378.

**Comment by pafurijaz** [comment]
Oh sorry, but when but when this fix will be implemented on master, I checked in the underdevelopment version and many fix aren't yet available such as for instanced collections, I have the same issue, like months ago.
Thanks

**Comment by scurest** [comment]
No idea, but nothing ever happens very fast.

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
