### ISSUE TITLE
Auto-Bake PBR Materials

### ISSUE THREAD

**Issue by padreputativo** [KhronosGroup/glTF-Blender-IO#1449]
**Is your feature request related to a problem? Please describe.**

Using 3D in a game engine is frustrating but even more when you are using an original Blender project and then you are still unable to export the materials to the Godot engine properly... I thought i should need to "made my own 3d" instead using other people assets but surprise... i cant make it works even using the main project...

**Describe the solution you'd like**

Auto bake PBR Materials should the way to go...

**Describe alternatives you've considered**

Stop trying to use materials at all and focus in low poly + godot materials becasue "realism" doenst seems to be an option

**Additional context**

This was the file i was trying to export. And even with plugins to bake PBRs been able to make it looks good...

https://www.poliigon.com/model/plant-succulent-echeveria-001

**Comment by LorenzWieseke** [comment]
I made an add-on to do just that:
https://blendermarket.com/products/glb-texture-tools

**Comment by whatisor** [comment]
Without hard manual baking, this exporter is no meaningful

**Comment by julienduroure** [comment]
Closing this ticket, as we will not add texture baking directly into this addon.
There is already some operator in Blender, and addons that can handle that

**Comment by padreputativo** [comment]
https://youtu.be/89tb2rjJ3-0?si=7elJ2x_9taFHN8hT&t=42
