### ISSUE TITLE
Incorrect export when using multiple Python export calls

### ISSUE THREAD

**Issue by paulmelis** [KhronosGroup/glTF-Blender-IO#1452]
**Describe the bug**

Okay, this is going to take some explaining. This is a reduced test case from a workflow in which we have a single blend file that contains a scene with lots of different objects, sorted into several collections. We use a custom Python script to export several GLB files, each holding different sets of objects (this is not an addon, but a script we execute with `blender ... -P export.py ...`). During the execution of this script, certain objects also get joined before exporting. All in all, quite a few things happen during this export process, but we noticed an issue, which I have hopefully reproduced in this simple test case. I haven't put my finger on it yet, but it feels like repeated calls to `bpy.ops.export_scene.gltf()` messing up the state in some way.

**To Reproduce**

1. Load `t_export_bug_racks_only2.blend`
2. Notice that the scene consists of 25 objects, each of which are instances of the same mesh `Cube.011`. As noted this is a simplified scene, which was originally partly generated using Animation Nodes to do mesh duplication.
3. The Text block visible contains a simplified export script that basically does two things: 1) it exports one of the 25 objects (`instance_bowxt_0`) to a GLB file `/tmp/single_rack.glb`, 2) it then joins all the 25 objects into a single mesh object and exports that to `/tmp/phase1.glb`. In both cases the call to `bpy.ops.export_scene.gltf()` only exports selected objects
4. Execute the Python script (with `Alt-P` in the Text block)
5. Notice that both exported files in `/tmp` are the same size (41,592 bytes in my case). Checking their sha256 sums or using diff shows the files to be exactly the same, which should not be, as one file only should contain a single object, while the other should contain all objects in a single mesh. 
6. Load in `/tmp/phase1.glb` in a new Blender session (keep the current session open!) and it shows only a single object:

![image](https://user-images.githubusercontent.com/1408287/129958865-820a6b86-5315-4b78-9d15-97148f0d95cb.png)

7. Close the 2nd Blender session and go back to the first one.
8. One of the things the export script did was join the objects into a single mesh object `instance_bowxt_0`, select this object
9. Export the selection to a new GLB file called `/tmp/test.glb`, with `Limit to: Selected Objects` selected in the export options
10. On my system `/tmp/test.glb` is *also* equivalent to the two GLB files exported above, which, again, is incorrect
11. Save the current blender scene to a new file, say `scene.blend`
12. Open the `scene.blend` file to make sure the session is refresh
13. Repeat step 9 (export the single joined object), this time to `/tmp/test2.glb`
14. Notice that `/tmp/test2.glb` is much larger (987992 bytes on my system) and correctly exports the joined objects when loading it into a fresh Blender session:

![image](https://user-images.githubusercontent.com/1408287/129959507-836ee107-8da5-431e-9f2b-8273299d5f39.png)
15. Open the original scene `t_export_bug_racks_only2.blend`
16. Remove the first call to `bpy.ops.export_scene.gltf()` in the Python script
17. Execute the script 
18. As expected only the file '/tmp/phase1.glb' is now produced, but it contains the correctly joined geometry. I.e. by removing the 1st export call the results become correct.

**Expected behavior**

The joined mesh should export correctly, instead of only one of the objects, even when the export script is used. Saving and reloading the scene should not be necessary for correct operation, nor should the first export call interfere with the second one.

**.blend file/ .gltf**

[t_export_bug_racks_only2.blend.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/7009693/t_export_bug_racks_only2.blend.gz)

**Version**
 - OS: Arch Linux
 - Blender Version 2.93.1

**Comment by julienduroure** [comment]
Thanks for your report.
It looks like a free caching issue than is not done automatically when calling export form command line. 
I will have a look on it

**Comment by julienduroure** [comment]
Ok, found the issue.
This is not an issue in this IO addon, but directly in blender.
Exactly same but than this one : https://developer.blender.org/T81136
but after joining instead of after apply modifier.
I will open a bug report in dev.blender.org

**Comment by julienduroure** [comment]
Blender bug : https://developer.blender.org/T90798

**Comment by paulmelis** [comment]
Nice catch!

**Comment by julienduroure** [comment]
Blender bug is now fixed.
This ticket should be now solved. 
Let's wait tomorrow build to check everything is OK

**Comment by julienduroure** [comment]
@paulmelis Did you test with a recent build that your bug is now gone?

**Comment by julienduroure** [comment]
@paulmelis any news?

**Comment by paulmelis** [comment]
Yes, with a recent 3.0.0 alpha build it works correctly now

**Comment by julienduroure** [comment]
Great!
