### ISSUE TITLE
Rigify-animated cat animation broken when trying to export inside Blender 2.93 as GLTF / GLB

### ISSUE THREAD

**Issue by VansonLeung** [KhronosGroup/glTF-Blender-IO#1457]
Hi. When trying to export an rigify-animated cat inside Blender 2.93 as GLTF / GLB, the animation is broken.

**To Reproduce**
1. Open "lowpoly_cat_base_2x.blend"
2. Select "rig" and "Cube"
3. Select rig -> Pose, Skeleton -> select "Pose position"
4. Action Editor -> Select action: "Idle"
5. File > Export > GLTF / GLB (2.0)
6. Check "Selection Only", "Animation", "UV Maps", "Normals", "Materials"
7. Upload and test in "http://gltf-viewer.donmccurdy.com/"
8. Try to play animation: "Idle"

**Expected behavior**
The cat should perform sitting and licking its arm.

**Actual behavior**
The cat is deformed.

**Screenshots**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1129695/130740126-54bc384c-6313-4251-a972-9208213e6d72.png">
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/1129695/130740218-abda17bc-6659-4a24-bc2b-424f941840a1.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1129695/130740464-ac045f6d-bb5d-4dc9-a49e-3fd397883f3b.png">

**.blend file/ .gltf**
[cat_blend_gltf_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7044310/cat_blend_gltf_glb.zip)

**Version**
 - OS: [macOS]
 - Blender Version [2.93]

**Comment by julienduroure** [comment]
Confirmed.
Exporting without animation seems to be OK.
I suspected that BBone animation are the root cause of weird deformation during animation.
BBones are not something that can be exported, there is no equivalent in glTF specification

**Comment by 3dcinetv** [comment]
Hi @VansonLeung , I've rigged a couple of things using Rigify. You need the addon called [GAME RIG TOOLS ADDON](https://www.youtube.com/watch?v=iZBx1I7vmQ0), which is super awesome for your case, all though I personally have not tried rigging bendybones. You need to add more sections to your bones in rigify, that should work fine.
Let me know if this works for you. Your GLTF needs to be rigged with a simple hierarchy.

**Comment by VansonLeung** [comment]
@julienduroure @3dcinetv   thanks for your help!  I will try the game rig tools addon. I may close this issue now.
