### ISSUE TITLE
Saved export format setting seems broken

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#146]
In a blend file I made to test something unrelated, I ended up with this as a custom scene property:

```
glTF2ExportSettings

{'export_format': 1, 'export_selected': 1}
```

With that in place, if I file -> export glTF, I see this error before I even get to the export settings UI.

```
Traceback (most recent call last):
  File "..\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 272, in invoke
    setattr(self, k, v)
  File "..\2.80\scripts\modules\bpy_types.py", line 662, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: expected a string enum, not int
```

/cc @donmccurdy

**Comment by UX3D-becher** [comment]
Does this also happen in blender 2.79?
At first glance this seems to be a bug in blender

**Comment by willstott101** [comment]
I've also stumbled into this issue. I didn't really know hoe to debug it though and ended up just making the patch at https://github.com/KhronosGroup/glTF-Blender-IO/pull/149

**Comment by EJTH** [comment]
Hi! I made a fix that seems to work. The problem is that EnumProperties are not stored/read properly depending on what was intended.

**Comment by emackey** [comment]
Further discussion in #148.
