### ISSUE TITLE
Linked object proxy nodes are not exported

### ISSUE THREAD

**Issue by KyleNBurke** [KhronosGroup/glTF-Blender-IO#1462]
**Describe the bug**
Linked object proxy nodes are not being exported.

**To Reproduce**
1. Open a new empty blender scene
2. Create a cube mesh
3. Save the blender file
4. Open a new empty blender scene
5. Click File > Link... > blender file from step 3 > Link > Object > object from step 2 > Link
6. Select the object in the viewport
7. Click Object > Relations > Make proxy
8. Your scene hierarchy should look like this
![image](https://user-images.githubusercontent.com/11780151/132404008-f4f986b4-a51f-4213-8648-0f369419f39c.png)
9. Click File > Export > glTF 2.0 (.glb/.gltf)
10. Change format to gltf Embedded (.gltf)
11. Click Export glTF 2.0
12. Open .gltf file and observe the node for the linked object proxy node was not exported. The nodes json array looks like this.
```json
"nodes" : [
    {
        "mesh" : 0,
        "name" : "Cube"
     }
],
```

**Expected behavior**
The proxy node should be exported as the linked object's parent.

**Version**
 - OS: Windows 10
 - Blender Version: 2.93.3

**Additional context**
You cannot transform a linked object so in blender you have to create a proxy which you can then transform. Transforming the proxy then transforms the linked object, as a parent-child relationship would. If the proxy node is not exported then that transformation is lost because it's part of the proxy node not the linked object node.

I'm no blender expert but I believe the use case for this type of thing would be a situation where you have all your modeled assets in a single blender file. Then you have separate blender files for each "world" you're building where you link the assets from the other blender file, create a proxy and transform those assets around your "world". Linking would allow you to change the assets and have that change reflected across all the "worlds" you've built.

**Comment by julienduroure** [comment]
Hello,
Proxy is now replaced in Blender by override system, so I probably won't investigating how to export proxy nodes.
There are some tools in Blender to convert proxy to override.

**Comment by KyleNBurke** [comment]
Oh I see, I didn't realize the override system can accomplish this. Thanks for the help.
