### ISSUE TITLE
Make glTF Settings (for AO) available by default

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1465]
Currently, people that want to export AO need to manually create the glTF Settings node.
This can be done automatically.

Some notes:
- Code for creation is already done, as the node is created at import when needed (when AO in glb file imported)
- Not sure every Blender user when the node to be displayed in UI, so maybe we need to add this option behind an addon parameter?

**Comment by emackey** [comment]
Maybe add a Blender command, so the user can trigger the node creation as needed?

Also, in `KHR_materials_volume` we've added a "thickness map" that is basically the inverse of AO, showing average thickness of the mesh below any given texel.  Blender has no such thing that I know of, and I was pondering whether it belongs on the Settings node once Blender supports `KHR_materials_volume`.

**Comment by gnat** [comment]
Yes please. Would be a big help to make this easier or seamless. I want to move us over to a glTF based workflow, and this is confusing many of my fellow artists during export.

It's just a file format.. should be simpler.

**Comment by optimus007** [comment]
Yes...  When I'm importing/appending multiple gltf files into the same scene there's multiple instances of that node group (glTF Settings.001 , glTF Settings.002 ...etc ) maybe this could solve that somehow

**Comment by emackey** [comment]
> When I'm importing/appending multiple gltf files into the same scene there's multiple instances of that node group (glTF Settings.001 , glTF Settings.002 ...etc )

If true, that would be a bug, separate from this feature request.  But I just tried loading the WaterBottle & FlightHelmet samples into Blender 3.0, and I don't see this issue.  With the pair of glTF models loaded, I see "glTF Settings" has 7 references, but not any separate instances like .001, .002, etc.  Maybe you clicked the "Make single-user" indicator by accident?  Or is there some other way that the importer could get this wrong?

**Comment by optimus007** [comment]
> > When I'm importing/appending multiple gltf files into the same scene there's multiple instances of that node group (glTF Settings.001 , glTF Settings.002 ...etc )
> 
> If true, that would be a bug, separate from this feature request.  But I just tried loading the WaterBottle & FlightHelmet samples into Blender 3.0, and I don't see this issue.  With the pair of glTF models loaded, I see "glTF Settings" has 7 references, but not any separate instances like .001, .002, etc.  Maybe you clicked the "Make single-user" indicator by accident?  Or is there some other way that the importer could get this wrong?

True, does happens on import !

But if I copy paste meshes with gltfSettings across multiple blender instances the .001 gets created ...

So this is how I was sometimes ending up with many glTF settings ...
