### ISSUE TITLE
.glb export error - wrong animation target node number

### ISSUE THREAD

**Issue by newillusion** [KhronosGroup/glTF-Blender-IO#1469]
Hello!

There are .glb export error with targer node number on animation channel. Exporter set the target node number as 39, but it is incorrect, here in file node 39 not exits. Correct node is 8. Pls, see a attachments.

![glb export error (wrong node number)](https://user-images.githubusercontent.com/13040758/134272448-e74e5e93-246c-4940-ac7e-233718960fcb.jpg)

When the wrong number is 39, left head keep eyes open constantly. When number is right (8), left head close eyes for 1 second.

![glb export error (before improve)](https://user-images.githubusercontent.com/13040758/134272527-e8302724-d3a5-4d87-be29-f20f734db6cf.jpg)

![glb export error (after improve)](https://user-images.githubusercontent.com/13040758/134272611-f432bc8c-bfc2-4345-8d07-2d5214f18aa1.jpg)

During my working on different projects, this error happened permanently, very often. I try look to exporter source code, but it written very complexly and i can't found point of error.

Source project and two .glb - exported and corrected:
[Project (.blend) and exported and corrected .glb files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7207291/Project.blend.and.exported.and.corrected.glb.files.zip)

Version of IO plugin used is (1, 6, 16), supplied with blender 2.93.5 Release condidate.

**Comment by julienduroure** [comment]
Confirmed.
This is a missed cache.
Investigation in progress

**Comment by julienduroure** [comment]
OK, bug found.
Only happen for objects parented to bone

**Comment by newillusion** [comment]
Look like the last fix improved error.

**Comment by julienduroure** [comment]
Hello @newillusion 
I am not sure to fully understand your answer.
Does it solve the issue ?
Does it make it worse ?
Does it solve a part of the issue, but is still not fully solved?

**Comment by newillusion** [comment]
@julienduroure, big thanks!
The fix #1469 fully solve the issue, described above. Very fast response!

But behavior of the exported .glb model is slightly different from expected. I think, that difference can be caused by other reason, and i try to investigate it. In any case, that will be another issue.
