### ISSUE TITLE
Exported animations don't work correctly

### ISSUE THREAD

**Issue by dadmancat** [KhronosGroup/glTF-Blender-IO#1476]
**Describe the bug**
I tried to export a .glb from .blend, but it missed some animation.
I referred to case #756 and #891 and unchecked "always sample animation" but did not work for me.

**.blend file/ .gltf**

[animation sample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7319925/animation.sample.zip)

Version

OS: Win10
Blender 2.93.1

**Comment by julienduroure** [comment]
Hello,
Can you please tell more precisely what animation are missing?

Regarding actions, seems all are exported:
![image](https://user-images.githubusercontent.com/1696020/137016388-b34ea530-2c4a-4bc3-bdd6-10c4cc5f7172.png)

Some errors occurs, linked to negative keyframes. This is not allowed on glTF specification.
We should probably add a warning or error message.

Grabbing all keyframes and move +5 keyframes to have only positive keyframe will solve that.

Don't hesitate to comment if I missed something else.

**Comment by julienduroure** [comment]
Hello,
2 months without any answer. I am going to close this ticket.
Negative frames will be handle in #387

Don't hesitate to comment if you have some new info to share
