### ISSUE TITLE
Crash in 3.0 & 3.1 exporting glb of animated model

### ISSUE THREAD

**Issue by NickHoath** [KhronosGroup/glTF-Blender-IO#1482]
**Describe the bug**
Crash exporting to gltf with animated rigged model.

**To Reproduce**
Animate a rigged model (Minion model from turbosquid: https://www.turbosquid.com/3d-models/3d-model-minion/1005881)
Export as glb
Blender crashes

**Expected behavior**
GLB is created

**Version**
blender-3.0.0-beta+v30.945a99386b8c-linux.x86_64-release
Also happens on Windows 3.0beta & 3.1alpha

[minionrig_anim.crash.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/7449937/minionrig_anim.crash.txt)

**Comment by julienduroure** [comment]
Hello,
The model is a non free model from turbosquid, so we can't use it to reproduce the error.
Seems this is a blender crash, not a python error, so it may make it difficult to find the root cause.
So, some question to help find where is the issue:
* Did you try to export from another computer, with another installation of Blender?
* Do you have issue when trying to export another model (for example the Robot from this ticket: 
* Did you try to export with 2.93 version?

**Comment by NickHoath** [comment]
Hi,
   I can probably get you a copy of the model for debugging purposes. How best to contact you?
1) I've tried it under Windows and Linux. It also happens on another PC.
2) Exporting RobotExpressive works ok
3) I get the issue as mentioned here: https://blender.stackexchange.com/questions/207840/export-to-gltf-fails-due-to-child-data-shape-keys-path-resolve-error - which is fixed (if I understand correctly) in 3.0.0 (https://github.com/KhronosGroup/glTF-Blender-IO/issues/310)
Thx!

**Comment by julienduroure** [comment]
Hi,

> How best to contact you?

Please send me the file or a link on the following email: contact (AT) julienduroure [DOT] com

**Comment by julienduroure** [comment]
You have a non valid driver on the model:

![image](https://user-images.githubusercontent.com/1696020/140061072-0619604a-83a8-4705-9215-d9624a51766e.png)


Remove it, and export is no more crashing.
I will add a check to avoid crash on invalid drivers.

Here is a simple file to reproduce on 3.0+
[bug_invalid_driver.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7467543/bug_invalid_driver.blend.zip)


Note that there is no crash on blender 2.93 with current master branch

**Comment by NickHoath** [comment]
Thankyou for looking in to this. Really appreciate your help and time!
