### ISSUE TITLE
gather_gltf_hook doesn't work properly

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#1501]
`gather_gltf_hook` acts as a way to add new content to already finalized scenes. If the hook adds for example a new Animation with extensions (for example, for implement EXT_property_animation), the exporter will fail. 

`gather_gltf_hook` should be called before finalizing the scenes and animations

**Comment by julienduroure** [comment]
Well, we already tweak few time this hook past few months.
We have to be careful about it. I will try to prepare some test cases for all changes we did

**Comment by jjcasmar** [comment]
So the issue is that the scene is finalized before the `gather_gltf_hook`, so if the hooks adds new stuff, that part is not going to be finalized

**Comment by julienduroure** [comment]
__gather_gltf_hook__  should be used only for modifying/adding extension at root of glTF.
You can't modify data already in glTF json, except in "extensions" at root of file

Maybe we have to rename this hook...

**Comment by julienduroure** [comment]
Merge done
