### ISSUE TITLE
Circle meshes are not exported

### ISSUE THREAD

**Issue by teoking** [KhronosGroup/glTF-Blender-IO#1503]
**Describe the bug**
There's no meshes node for the circle mesh in the exported glTF file.

**To Reproduce**
1. Click on 'Add -> Mesh -> Circle'
2. Select the 'Circle' in the 'Scene Collection'
3. Goto 'File -> Export -> glTF 2.0'
4. Select format as 'glTF Embedded'
5. Check on 'Include -> Selected Objects'
6. Check the exported glTF file.

**Expected behavior**
Circle mesh could be exported.

**.blend file/ .gltf**
```json
{
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v1.6.16",
        "version" : "2.0"
    },
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                0
            ]
        }
    ],
    "nodes" : [
        {
            "name" : "Circle"
        }
    ]
}

```

**Version**
 - OS: macOS
 - Blender Version 2.93.5

**Comment by scurest** [comment]
A circle has no faces. A mesh with no faces isn't exported. This is probably what you want, but if it isn't, you can turn on Mesh>Loose Edges in the export options to get a mesh for it.

**Comment by teoking** [comment]
@scurest Thanks, I can see a mesh now.
'A circle has no faces. A mesh with no faces isn't exported' that is said if I did some 2d animations, I cann't get those draws as meshes in the glTF?
Or do you know some tutorials about exporting 2d animation as a glTF?
