### ISSUE TITLE
Armature not export in animation

### ISSUE THREAD

**Issue by Snouf-ID** [KhronosGroup/glTF-Blender-IO#1506]
On Blender 2.80 and 2.90, when I export a gltf, track use the Armature node.
On Blender 3.0 the Armature node is no longer present in the animation track.

To Reproduce
1. Open Blender project in 3.0 or 2.90
2. Export

Is there a way to have the old behavior? Is there a doc / issue that explains this change?
I guess it's an optimization but I can't find anything on it.

Screenshots
![image](https://user-images.githubusercontent.com/47319640/146588609-9f20e3ce-4a82-4eff-ba76-c6e33e89d140.png)
[testA.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7737047/testA.zip)

**Comment by julienduroure** [comment]
Confirmed.
For optimization reason, objects that are not animated are no more exported. So with only 1 keyframe on your armature object, this will not be exported, as the property doesn't change.
For bones, we export it anyway, with only 1 key, if the bone property is animated
But this is not the case for objects.

What is your use use to really need to have a single keyframe for not animated armature?

**Comment by julienduroure** [comment]
I confirm the regression.
