### ISSUE TITLE
Blender doesn't export textures correctly to gltf

### ISSUE THREAD

**Issue by hasnainv** [KhronosGroup/glTF-Blender-IO#1518]
**Describe the bug**
 Blender is not exporting textures for certain gltf files, when they contain multiple maps (e.x. a roughness map and a texture map). 

**To Reproduce**
Check the .blend file attached. Try exporting the model as gtlf

**Expected behavior**
We would expect textures to be exported, but we don't see any in the exported file.

**Screenshots**
Input: Textures in input
![image](https://user-images.githubusercontent.com/979383/147438210-ae7024b1-3dd3-4de6-9b19-ecbc8f5e0685.png)

Output: No textures in output
![image](https://user-images.githubusercontent.com/979383/147438630-4c8a2c43-3d4b-4c77-9171-ba56708d04e3.png)

**.blend file/ .gltf**
https://drive.google.com/file/d/1j-FoT3Ca-_--k3rO-5mr4STfwDkCvRny/view?usp=sharing

**Version**
 - OS:  Windows
 - Blender Version 3.0.0 

**Additional context**
This issue doesn't happen always, but I noticed that this issue happens when there are multiple maps attached to a mesh (e.x. a roughness map and a texture map or multiple texture maps)

**Comment by julienduroure** [comment]
Hello,
glb specification use PBR materials, so you have to use Principled Shader in Blender if you want to export materials from Blender to glTF or glb.

You can find documentation here : https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.htm

And a complete example here : https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#example

**Comment by padreputativo** [comment]
My question is... Why doesn't Blender automatically convert all materials to that type of material when exporting to glTF, instead of setting everything to white and not displaying any kind of error or warning?

**Comment by julienduroure** [comment]
Blender does export materials trying to keep what is possible (for example, AO in this example).
What is not possible to get, we keep the default value, that is white for baseColorFactor
