### ISSUE TITLE
Check if Principled BSDF node is connected to output

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#152]
This is low priority, but following these comments:  https://github.com/KhronosGroup/glTF-Blender-IO/issues/111#issuecomment-444990360

It would be nice if the exporter would check to see if the Principled BSDF node is connected to the shader output (and additionally, which Principled node, if there are more than one).  Sometimes artists will keep several in the node tree, for easy swapping around of the outputs.

**Comment by scurest** [comment]
@emackey Is this fixed?

**Comment by emackey** [comment]
I didn't test it, but it looks like copies of this have already been tested and closed.  Thanks!
