### ISSUE TITLE
Use action.frame_range ?

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1520]
Currently, we are not using action.frame_range or action.curve_frame_range.
See if we can use it/them

> Action.frame_range will now return the manually set frame range if available. Add-ons are advised to evaluate whether this is appropriate for their use case, or whether they need to switch to Action.curve_frame_range which always returns the range computed from the keys

**Comment by schroef** [comment]
isnt this linked to you #1517 issue?

**Comment by julienduroure** [comment]
Hello,
This is not directly linked (even if this is a really close related subject). Currently in master, we are using fcurve min and max to retrieve range of keyframe timing, where we can use action.frame_range (in 3.0) or action.curve_frame_range (in 3.1 alpha)
#1517 is only take care of custom range set by user (accessible by action.frame_range in 3.1 alpha)

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

frame_range is now used
