### ISSUE TITLE
Reset pose at end of each animation export

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1532]
For armature, when switching animation, if some bones are not keyed in newly active action, value of last action is kept. Need to reset pose?
See https://github.com/KhronosGroup/glTF-Blender-IO/issues/1386#issuecomment-998458145
What about objects animation?

**Comment by scurest** [comment]
Isn't this #1047?

**Comment by julienduroure** [comment]
You're right. Closing this ticket, discussion can continue on #1047 (That talks about import & export issue linked to default pose)
