### ISSUE TITLE
Bake node-adjusted textures?

### ISSUE THREAD

**Issue by willstott101** [KhronosGroup/glTF-Blender-IO#1533]
I like to work with simple black-white pattern textures, which I can apply to roughness/specular/transmission or even base color by using Blender's nodes. This gives me flexibility and very fast iteration times with lookdev by editing node parameters rather than phaffing around in something like photoshop.

When exporting to GLTF it's frustrating that the original texture is exported, rather than the modified texture which Eevee sees.

Is it possible to query blender for a "baked" version of this texture and include that instead? The particular case that's got me today is a simple color `Invert` on a B&W Non-Color texture to adjust transmission amount.

![image](https://user-images.githubusercontent.com/335152/149132017-edc60601-ccf4-4133-8bd9-30c007c4bd54.png)

In this example I'm able to use the same texture with different settings - saving me tonnes of time. I had expected the GLTF to end up with two textures - one of which had been fed through the Invert node.

Apologies if this has already been requested.

**Comment by julienduroure** [comment]
Closing this ticket, as there is no plan to implement bake into this addon.
This is a huge task, that should be done on Blender side, or by another addon
