### ISSUE TITLE
Invalid `joints` array in exported GLTF when mesh object is not parented to the armature and there are empties parented to bones

### ISSUE THREAD

**Issue by rafalh** [KhronosGroup/glTF-Blender-IO#1538]
**Describe the bug**
When there is a non-bone node (e.g. empty) parented to a bone and another node with a mesh and armature modifier that is *not* parented to the armature, exported `joints` array in GLTF skin contains reference to the non-bone node. At the same time `inverseBindMatrices` points to an accessor that has a proper count (not including non-bone node) making GLTF file invalid (`inverseBindMatrices` accessor should have at least as many values as there is elements in `joints` array)

**To Reproduce**
1. Create a box
2. Create an armature
3. Set box parent to armature with automatic weights
4. Create empty
5. Switch to pose mode and set empty object parent to an armature bone
6. Clear parent reference of the box object making it a top level node
7. Export GLTF file

**Expected behavior**
In exported GLTF file `Skin.joints` array should contain only 1 element (the only bone of created armature) but it contains 2. There is index of empty object which is not a bone and shouldn't be there.

**.blend file/ .gltf**
[bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7877953/bug.zip)

**Version**
 - OS: Linux Mint 20.3
 - Blender Version: 3.0.0

**Comment by julienduroure** [comment]
Hello,
Confirmed.

Not setting the mesh as child of the armature is not the proper way to skin in Blender. 
See https://docs.blender.org/manual/en/latest/animation/armatures/skinning/parenting.html

This bug is already solved in current refactoring of the exporter (see #1378)

**Comment by rafalh** [comment]
> Not setting the mesh as child of the armature is not the proper way to skin in Blender.
> See https://docs.blender.org/manual/en/latest/animation/armatures/skinning/parenting.html

Well, it may be non-standard approach but it works in Blender 2.82/3.0.0 (armature modifier still works on the mesh). It is also the only way I know to make skinned mesh a top level node in exported GLTF. I needed it for my custom tool which does not support node hierarchy. It's worth noting that gltf-validator recommends having skinned meshes as top-level nodes. Currently I get the following warning if the mesh is a child of the armature: `Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.glTF Validator(NODE_SKINNED_MESH_NON_ROOT)`. So perhaps GLTF exporter should apply transforms and clear skinned mesh parent during export.

**Comment by julienduroure** [comment]
Unfortunally, there is no 100% coverage on Blender / glTF. What is a best practice on one side is not recommanded in other side, and vice-versa. (This ticket is an example, but this is not the only one). We need to find for every case the best way.

> So perhaps GLTF exporter should apply transforms and clear skinned mesh parent during export.

This is not possible with current master architecture, but I will have a look with new vtree architecture. Seems this should be possible

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
