### ISSUE TITLE
Checking `Double Sided` doesn't export as double-sided geometry

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#154]
Checking the `Double Sided` checkbox under `Object Data` doesn't export a double-sided geometry.

![image](https://user-images.githubusercontent.com/4733018/49692709-3ff73380-fb2f-11e8-96e6-081c59b0bbf0.png)

Is this the preferred method for doing so, or is there another way?

![image](https://user-images.githubusercontent.com/4733018/49692722-72089580-fb2f-11e8-8b65-adf82a593e18.png)

**Comment by mholthausen** [comment]
Will this option be supported in near future? Is there currently a workaround to export double sided meshes properly? I currently duplicate the mesh and flip the normals of the copy, but this is very data intensive.

**Comment by dsinni** [comment]
@mholthausen I'm not sure if this will work for your use case, but in some cases I was able to use the `Solidify` modifier with `Thickness` and `Offset` set to `0` and every other option turned off. Maybe you can get some use out of that until the feature is available.

![image](https://user-images.githubusercontent.com/4733018/51422051-31f8f180-1b76-11e9-84b0-a02101f8eac5.png)

**Comment by mholthausen** [comment]
> @mholthausen I'm not sure if this will work for your use case, but in some cases I was able to use the `Solidify` modifier with `Thickness` and `Offset` set to `0` and every other option turned off. Maybe you can get some use out of that until the feature is available.
> 
> ![image](https://user-images.githubusercontent.com/4733018/51422051-31f8f180-1b76-11e9-84b0-a02101f8eac5.png)
> 
> Just be sure to remember to check the `Apply Modifiers` option in the exporter settings if you don't want to apply the modifier to the actual mesh in Blender.

Thanks. But this modifier makes no difference in the file size when duplicating the layer and flip normals, because the modfier duplicates the triangles and faces, too.

**Comment by dsinni** [comment]
> Thanks. But this modifier makes no difference in the file size when duplicating the layer and flip normals, because the modfier duplicates the triangles and faces, too.

Hmm. I could be wrong, but I was under the impression that duplicated geometry and flipped normals is the expected result after exporting when trying to achieve a double-sided mesh. Does the older workflow with the glTf nodes not result in a larger file size?

**Comment by donmccurdy** [comment]
The `doubleSided` flag doubles the number of faces that are rendered, so there's a performance cost there, but the filesize remains the same.

Note that with https://github.com/KhronosGroup/glTF-Blender-IO/pull/255, you can use the old glTF PBR nodes to set the double sided flag (while still using Principled BSDF for the rest of the material).

**Comment by dsinni** [comment]
Ah, good to know. I guess I had the wrong impression. Thanks, @donmccurdy.

**Comment by emackey** [comment]
> The doubleSided flag renders each face twice

Technical nitpick, it's not actually rendering each face twice.  What happens in most engines is that "backface culling" is disabled for double-sided materials.  At the same time, back-facing fragments have their normal vectors automatically flipped (this is sometimes called "double-sided lighting").  For reference, glTF doesn't offer a single-sided lighting mode, but Blender does.  In glTF you either get double-sided lighting (when `true`), or the back faces are culled away (when `false`).

But the rest of what @donmccurdy wrote is correct: The file size is unchanged, and there can be a (usually minor) performance hit from rasterizing all the backfaces.  It's much better than using the solidify modifier, in terms of file size and memory footprint.

**Comment by emackey** [comment]
Fixed in #304.
