### ISSUE TITLE
Animation bone channel is not exported if a deforming bone is a copy constraint of another none-moving bone.

### ISSUE THREAD

**Issue by tobymckoi** [KhronosGroup/glTF-Blender-IO#1541]
**Describe the bug**
In some armature setups (such as rigify), you have a set of Deform bones and a set of other bones that control the deforming bones. When you key an animation, you will animate only the control bones, and when the animation is exported you only want the deform bone channels to be present in the 'baked' output.

This process of exporting a baked animation worked in 1.6.16, but fails in 1.8.6 when deform bones do not move during the animation. In the case where this condition is met, the produced GLTF has no channel at all for the deform bone, which is incorrect because there should be a channel with the initial transform of the deform bone.

**To Reproduce**
One simple armature setup that produces the error is a deform bone with a 'Copy Transforms' contraint to a control bone. Then a static animation action that doesn't do anything other than defines the initial transform of the control bone.

**Expected behavior**
In 1.6.16 it worked as expected - none moving deform bones in such a setup produced a channel in the exported animation.

**.blend file/ .gltf**
Basic reproducible animation setup: [no_channel_gltf_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7885807/no_channel_gltf_bug.zip)

In ZIP, bug_on_gltf_anim_export.blend has a mesh and armature with 3 deform bones with 'Copy Transforms' constraints to 3 control bones. It defines 3 actions which deforms the mesh into letters of the alphabet. The export settings are: 'Include Selected Objects' , 'Geometry Materials: No export', and 'Animation Export Deformation Bones Only'.

The .blend file demonstrates the lose of information caused by this bug. The mesh deformations are present in 1.6.16 but are lost in 1.8.6.

ZIP also contains 'export_1.6.16.gltf' and 'export_1.8.6.gltf' which are the exported outputs from the different versions.

Screenshot of animation with all channels present in 1.6.16:
![gltf_bug_ss_01](https://user-images.githubusercontent.com/707519/149862113-0ae5163a-bc66-4856-914b-f6e6e18d9721.png)

Screenshot of animation with missing channels and lost information in 1.8.6:
![gltf_bug_ss_02](https://user-images.githubusercontent.com/707519/149862192-0125c9ed-8738-42eb-af09-b85a4c74337b.png)

**Comment by tobymckoi** [comment]
Looked through the commits, and guessing that this regression may be caused by #1433 which might need to check if the bone has constraints before culling the channel.

**Comment by julienduroure** [comment]
Confirmed.
Need to think about the smartest way to detect this cases, beeing sure that animation is correctly exported, but that some not needed channels are deleted (for example, if we detect that DEF bone has a constraint, all 3 channels TRS will be kept, even if this is maybe not needed)

**Comment by tobymckoi** [comment]
I think it's difficult to be smart about this case. You could probably solve it for simple cases by inspecting the referenced bone and determining if it has animation keys and what channels the constraint can modify, but I think that none trivial cases will need to default to including all channels.

My opinion about this is that I do not expect an Export tool to solve this problem for me. Baked deform bones channels should only be excluded if it's very clearly the intent of the animator that the channel should be excluded from the output. In the case where it's not obvious, it's the responsibility of the importer to ignore channels if that kind of animation blending is desired.

**Comment by julienduroure** [comment]
Fixed by #1575
