### ISSUE TITLE
"compression" option missing in the export dialog (Blender 3.0 on manjaro)

### ISSUE THREAD

**Issue by gtnbssn** [KhronosGroup/glTF-Blender-IO#1542]
According to what i see elsewhere online, this option should be under geometry in the export dialog, however i cannot find it anywhere.

Here is a screenshot:

![blenderglTFexport](https://user-images.githubusercontent.com/10359074/149896685-39b54cf6-9c2d-4a9f-9865-1508444fe4cc.png)

**To Reproduce**
1. Install Blender from pamac `sudo pamac install blender`
2. Click on file > export > glTF 2.0
3. Settings do not include compression

**Version**
 - Manjaro linux
 - Blender 3.0 (installed from pamac)

Apologies if this is Manjaro related and does not belong here! Just not very sure what to do about this now.

**Comment by julienduroure** [comment]
Hello,
This is probably linked to your Blender installation.
When you open the export windows ( file > export > glTF 2.0 ), you should be able to see in console something like that:
![image](https://user-images.githubusercontent.com/1696020/149898547-c4b5cd99-b22a-4ea5-85c9-ec6c7d94bb54.png)

If you have an error message instead of this success one, Manjaro didn't package Blender with Draco compression available

**Comment by gtnbssn** [comment]
Indeed, this is what i see in the console:
```
'/usr/bin/3.0/python/lib/python3.10/site-packages/libextern_draco.so' does not exist, draco mesh compression not available, please add it or create environment variable BLENDER_EXTERN_DRACO_LIBRARY_PATH pointing to the folder
```

I'll see where i can get this reported for Manjaro. Thanks for the crazy fast answer!

**Comment by gtnbssn** [comment]
In case someone with the same issue finds this, the easiest solution seems to be to just use the flatpak version.

See this also: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1074

I created an issue for arch maintainers here: https://bugs.archlinux.org/task/73415

**Comment by svenstaro** [comment]
I fixed this in Arch Linux. It would have been helpful if Manjaro would have provided a patch.

**Comment by scurest** [comment]
A search through getsitepackages() if it's not at any of the other places could probably be upstreamed.

The function is currently called constantly from UI code though; it only needs to be called at most once per export. Also not sure if there's versioning considerations for a nonbundled lib.

**Comment by svenstaro** [comment]
@scurest Would you mind upstreaming that then? I might not have enough time to deal with that right now but I would appreciate the effort.
