### ISSUE TITLE
wrong orientation when model is animated

### ISSUE THREAD

**Issue by Qiweih** [KhronosGroup/glTF-Blender-IO#1544]
**Describe the bug**

When I import a model with multiple animations and export it with blender gltf exporter, the exported model has the wrong direction. the model is reversed.

**To Reproduce**
1. Download this file (if you open it in a viewer it's fine)
2. Open blender and import this model
3. Export it with blender
4. The model is reversed in the viewer

**Expected behavior**
Expected that the model is in the right direction

**Screenshots**
https://github.com/Qiweih/test/blob/main/test.PNG

**.blend file/ .gltf**
https://github.com/Qiweih/test/blob/main/template.gltf

**Version**
 - Blender Version 3.0
 - Khronos glTF Blender I/O v1.7.33

**Comment by julienduroure** [comment]
Confirmed
(Note this is solved in #1378 )

You said in ticket title that there are multiple animation. But not sure this is linked. Did you try with only one animation?

**Comment by Qiweih** [comment]
Yes, i did it with one, it's the same problem. But if I don't export it with animation it's normal.

**Comment by Qiweih** [comment]
> Confirmed (Note this is solved in #1378 )
> 

You said it's solved in #1378 so i can download the code in this branch and fix my issue ?

**Comment by julienduroure** [comment]
@Qiweih No, this branch is not ready to merge yet. The branch is a refactoring, and does not include only your fix

**Comment by Qiweih** [comment]
@julienduroure  I tested this branch and it seems to work, but it's becoming very slow to export (think it's because your refactoring is not ended yet), did you have any date for the merge of this branch ? It would be great to know more about that thanks.

**Comment by julienduroure** [comment]
About planning: Nothing is decided yet, but maybe included in Blender v3.2
About export time :
- To be sure to export correct data, we baked TRS from world matrix, so we need run frame by frame. (It was already the case for armature, now this is also for objects). 
- Your case is the worst : Lost of objects, and lots of action on each objects. Even if there is a cache to be able to store matrix for each objects, we need to switch actions for each objects to get data.
- So at short term, I don't know how we can improve performance (switching all objects actions at same to avoid more and more frame change ? It can help, but will stay longer than current)

**Comment by Qiweih** [comment]
I see, thanks for the help and explanation

**Comment by Qiweih** [comment]
Hi @julienduroure , i don't know if i need to ask the question here, for the same model above, when i export from Blender and put it in model viewer or any other 3d viewer, the model origin is not at origin. Do you know which can be the reason of this kind of problem ? At position y = 32, you can test it here https://modelviewer.dev/editor/ (There is a target point value at right, you can see that the target point is not at origin of the world)

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Comment by Qiweih** [comment]
@julienduroure I downloaded https://builder.blender.org/download/experimental/ to test, however when i try to export my model below, it didn't export it, seems like it enters in infinite loop or something like that.

**Comment by Qiweih** [comment]
After 10 min it finally ended
