### ISSUE TITLE
Instance of unlinked collection not exported

### ISSUE THREAD

**Issue by Borck** [KhronosGroup/glTF-Blender-IO#1548]
**Describe the bug**
If I export a scene with instances of an unlinked collection, I get empties when reimporting.

**To Reproduce**
1. I started with a new emptied scene
2. I created a collection A with some primitives (for instancing)
3. I created instances of collection A in the scene collection
4. I unlinked collection A (required for script), instances are still existing.
5. I exported the scene to .glb with default settings
6. I reimported this file and only got empties.

**Expected behavior**
The instances are in the exported file (like in FBX/OBJ)

**Screenshots**
![UnlinkedInstanceCollection](https://user-images.githubusercontent.com/10433707/151574425-c93d88ac-42c8-4f0d-aa42-bbabb6006247.jpg)

**.blend file/ .gltf**
[UnlinkedInstanceCollection.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7959833/UnlinkedInstanceCollection.zip)

**Version**
 - OS: Windows 10 Pro 21H2
 - Blender Version 3.0.1

**Comment by julienduroure** [comment]
This is fixed in #1378 
This is not yet merged in master. This will probably come with Blender 3.2

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
