### ISSUE TITLE
clearcoatRoughnessFactor  value not exported from multiply node if image is present

### ISSUE THREAD

**Issue by optimus007** [KhronosGroup/glTF-Blender-IO#1549]
**Describe the bug**
image + math multiply node 
exports as 
texture + clearcoatRoughnessFactor =1  
If image is not there , it exports the value from the principled bsdf slider correctly 

**Expected behavior**
Similar to roughness and metalness the math multiply value should act as clearcoatRoughnessFactor value in case of clearcoat

**Screenshots**
![err](https://user-images.githubusercontent.com/6885294/151600996-aef2bc21-1297-498c-9bae-f55efcad77c6.png)
![gltf](https://user-images.githubusercontent.com/6885294/151601004-967d8586-73c4-4958-babf-340e184d0166.png)

**Version**
 - OS: Windows
 - Blender Version [3.2.0]

**Comment by j-conrad** [comment]
I think it's because it's expecting you to Multiply using a MixRGB node.

**Comment by optimus007** [comment]
> I think it's because it's expecting you to Multiply using a MixRGB node.

Tried it , does not export .

Color seems to have no influence on the roughness. 
Also the value is saved as a single digit , so it's seems like it needs a single math multiply node and not a mix RGB multiply node
