### ISSUE TITLE
problems with exporting one frame animations

### ISSUE THREAD

**Issue by weckr** [KhronosGroup/glTF-Blender-IO#1559]
I have a character file with skeleton. Exporting "normal" animation like a walkcycle works fine, but I want to have some one frame long animations/poses, and those just do not work. I thought it might be godot engine problem but they do not work after reimporting the exported glb back into blender, the animation is just not there. 

I thought its a sampling issue and tried to get around it by duplicating the keyframes and making it several frame long animations, but that also doesnt work, i suspect because there is no delta detected. Only when i put keyframes in the middle that i move and rotate a bit, it exports mostly properly - but for example in "slide" animations, there are some differences in the export from the original file. 

I try to hard keyframe every bone at the beginning of animation. Im at my wits end with this one, spent hours. Alternatives (even paid fbx plugin), also dont really work with godot. Also this is rather complex rig, but I had this exact issue with extremely simple 10-or so bone rig with basic IK.

Also tried every possible export setting combination possible i think.

**To Reproduce**
1. Export glb file with static or one frame animations

**Expected behavior**
Correct keyframes will be sampled and exported

**.blend file/ .gltf**
[ronin.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8010733/ronin.zip)

**Version**
 - OS: manjaro linux
 - Blender Version 3.0

**Comment by julienduroure** [comment]
Related to #1541

**Comment by weckr** [comment]
Thank you so much, got it working by deleting the if clauses in https://github.com/KhronosGroup/glTF-Blender-IO/pull/1433/commits/22df001409f94a19b37e1f9a70fbd68d61d65c59  and just always returning the keyframes. It might be good idea to put toggle in the export settings for this, in the game engine case, they almost always have compression settings for imported animations, and could save somebody some time. I could do pull request for this but it would be my first and dont know if you already have proper solution planned for next release.

**Comment by julienduroure** [comment]
Hello,
Please be free to propose a PR, I didn't started to work on it yet.
Deadline is to merge it before end of February, to get it into 3.1

**Comment by julienduroure** [comment]
Fixed by #1575
