### ISSUE TITLE
Classic Stretched Bone issue when exporting animation.

### ISSUE THREAD

**Issue by enzyme69** [KhronosGroup/glTF-Blender-IO#156]
I am trying to pose and make a simple animation using "Spiderman Amazing Rig" below that hopefully works as GLTF anim:
[Spiderman Amazing Rigged 2 2 CYCLE 009.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2660557/Spiderman.Amazing.Rigged.2.2.CYCLE.009.blend.zip)

I am using Blender 2.79 and 2.8. So far 2.8 GLTF is giving a weird stretched bone animation and totally out of whack. I have seen similar issues posted in the past. There is no proper solution.

[Screen Recording 2018-12-09 at 11.44.53 pm.mov.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2660568/Screen.Recording.2018-12-09.at.11.44.53.pm.mov.zip)

<img width="619" alt="screen shot 2018-12-10 at 12 21 00 am" src="https://user-images.githubusercontent.com/3952687/49697983-16fb9f00-fc12-11e8-837c-820dc79e19ad.png">
<img width="538" alt="screen shot 2018-12-10 at 12 20 49 am" src="https://user-images.githubusercontent.com/3952687/49697984-16fb9f00-fc12-11e8-82e6-d8a8f33e1348.png">

However, **KUPOMAN GLTF** export is the only add-on known out there that can export the animation above properly:
https://github.com/Kupoman/blendergltf

I tested it many times. It's not the problem if IK or FK, but sometimes if weight is abnormal it can cause error. Also the way Blender Rig sometimes is made without proper ROOT or non-connected bones... I don't know ¯\_(ツ)_/¯ 

I did convert the IK to FK using this add-on: 
https://github.com/chinedufn/blender-iks-to-fks

It might be the way the rig was done causing the export to give weird stretching bones etc, but Kupoman GLTF export manage to export it even without me baking the IK.

**Comment by donmccurdy** [comment]
Thanks for reporting this! The issue has been fixed.
