### ISSUE TITLE
Generated image size changes in `_make_temp_image_copy`

### ISSUE THREAD

**Issue by josuemtzmo** [KhronosGroup/glTF-Blender-IO#1564]
**Describe the bug**
When a generated image is used as a image texture of an object with dimensions other than default (1024x1024), the function `_make_temp_image_copy` crashes as the tmp_image has a different dimension than the original image:
```
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_image.py", line 254, in _make_temp_image_copy
    tmp_image.pixels.foreach_set(tmp_buf)
TypeError: expected sequence size 4194304, got 4147200
```
For example, if the generated image is 1440x720 (src_image), the 
```
>>> src_image.size[0]
1440
>>> src_image.size[1]
720
```
after copying the image (using ID.copy()), the dimensions of the image are set to default. 
```
>>> guard.image = src_image.copy()
>>> tmp_image = guard.image
>>> tmp_image.update()
>>> tmp_image.size[0]
1024
>>> tmp_image.size[1]
1024
```
an easy fix, that I've submitted as a PR is to update the scale with the src_image.size:
```
tmp_image.scale(*src_image.size)
```

**To Reproduce**

1. Run the following code in the blender text editor:
```
import bpy
import numpy as np

img = bpy.data.images.new('testimage',1024,1024)
rand_data = np.array(np.random.randn(1440,720,4)*255,dtype=np.float32).ravel()
img.scale(1440, 720)

img.pixels.foreach_set(rand_data)

print(img.size[0],img.size[1])

tmp_image=img.copy()

print(tmp_image.size[0],tmp_image.size[1])

#bpy.context.area.ui_type = 'ShaderNodeTree'
material= bpy.data.materials['Material']

imagetex = material.node_tree.nodes.new("ShaderNodeTexImage")
imagetex.location = (-280, 250)
imagetex.interpolation = "Smart"

imagetex.image = img

BSDF = material.node_tree.nodes['Principled BSDF']

material.node_tree.links.new(BSDF.inputs[0],imagetex.outputs[0])
```
2. Then export the file as an glTF 2.0 format; on the top menu File > Export > glTF 2.0 (.glb/gltf) 

**Expected behavior**
The tmp_image should have the same dimensions as the src_image. This can be solved by adding the line: 
`tmp_image.scale(*src_image.size)` in the `gltf2_blender_image.py` file.

**Version**
 - OS: macOS, linux
 - Blender Version >2.9

**Comment by julienduroure** [comment]
Confirmed.
Any image created with a given size, and then change the size using img.scale(...) --> When you copy the image, the destination image take the original size, not the copied one.

Ok for the work arround, but I will probably open a ticket on Blender side to track that

**Comment by julienduroure** [comment]
For info, Blender ticket : https://developer.blender.org/T95616

**Comment by josuemtzmo** [comment]
Thanks! It will be great if it's fixed in the next release of Blender.

**Comment by julienduroure** [comment]
Sure, I will commit the workaround for 3.1, in case the original one is not fixed in Blender
