### ISSUE TITLE
T59127 Importer error

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#157]
https://developer.blender.org/T59127

Maybe linked to null value in json?

**Comment by julienduroure** [comment]
I can confirm that the problem is _null_ that are not well parsed by gltf_io
@McNopper @donmccurdy Are _null_ values allowed in glTF specification?  
In this case, _null_ are somewhere in extension objects

**Comment by donmccurdy** [comment]
Null values are disallowed by the schema and validator: https://github.com/KhronosGroup/glTF/issues/646. It may be that the validator does not look inside of unknown extensions, if they aren't seeing errors on validation.

**Comment by lexaknyazev** [comment]
Yep, The validator ignores values of unknown extension objects. This will be fixed in the next release.

**Comment by julienduroure** [comment]
OK, thanks, I will close the issue, here & in blender repo
