### ISSUE TITLE
Ability to expose filter to extensions

### ISSUE THREAD

**Issue by pepperoni505** [KhronosGroup/glTF-Blender-IO#1578]
In an addon I'm working on, I create temporary blender objects that I do not want to get exported, and unfortunately there is no good way of telling the exporter not to export said object. You aren't able to set the node to `None`, so you're left with looping through the finalized scene.

Currently, the filter node function checks for a few things in the export settings. https://github.com/KhronosGroup/glTF-Blender-IO/blob/0f35b51ca30cee5cbecd87ee5b2986f4c9e5100e/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py#L121
I've tried adding a hook in this function, but unfortunately it does not work as passing a boolean does not return any updates from the hook call. I see a few ways to implement this properly:

- Change `export_user_extensions` to be able to return a value
- Create a temporary object/class with the filtered variable
- Add something in `export_settings`

I would like some feedback on this, as I want to figure out the best way to move forward with a proper implementation.

**Comment by julienduroure** [comment]
Quick note: __filter_node will disappear in a few days, because of merge of #1378 
Now, nodes will be filtered in a virtual tree. It should be easier to find a way to filter a node (even if there is no simple hook for that yet, I think)

**Comment by pepperoni505** [comment]
Would you mind outlining the process for filtering a node in your vtree branch?
