### ISSUE TITLE
Multiple curves exported with Loose Edges seem to share geometry

### ISSUE THREAD

**Issue by ffdead** [KhronosGroup/glTF-Blender-IO#1583]
**Describe the bug**

When exporting a model with multiple Curves and "Loose Edges" - all curves seem to share lines from the curve furthest down (last) in the Outliner. 

**To Reproduce**
1. Add two or more BezierCurves
2. Export as GLTF
3. Enable "Loose edges"
4. Drop .gltf into https://gltf.report/ - the curve shapes are all the same instead of unique

**Expected behavior**
I was expecting each curve to retain its individual shape from Blender.

**Screenshots**

Four unique curves added in Blender:
<img width="1040" alt="Screenshot 2022-03-04 at 21 01 42" src="https://user-images.githubusercontent.com/420472/156833380-01bfe0da-6b79-49cb-99f2-d189a0775e25.png">

What it looks like after exporting:
<img width="1514" alt="Screenshot 2022-03-04 at 21 09 21" src="https://user-images.githubusercontent.com/420472/156834325-00917852-2b72-41af-83e8-1aef1f05efe9.png">

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

[multiple-curves.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8188468/multiple-curves.zip)

**Version**
 - OS: macOS Monterrey 12.0.1 (Apple M1 Max)
 - Blender Version: 3.0.0, 3.0.1

**Comment by julienduroure** [comment]
Confirmed for 3.0 and 3.1 RC
But this is solved in current master branch, this will be solved in 3.2
