### ISSUE TITLE
Instance collection from other scene

### ISSUE THREAD

**Issue by morganbengtsson** [KhronosGroup/glTF-Blender-IO#1600]
**Describe the bug**
I might be missing something, but instancing a collection from another Blender scene does not seem to work as intended. On export the instanced node is empty.

**To Reproduce**
1. Add a new scene named "Objects"
2. Add Suzanne to the new scene
3. Move Suzanne to a new collection named "Monkey"
4. Go back to the original "Scene"
5. Add -> Collection Instance -> Monkey
6. Move the Monkey instance a bit
7. Export to glTF

**Expected behavior**
I would have expected that in the resulting file there would be one original "Monkey" and one instanced "Monkey".  One in each scene. Instead the instanced node is empty. I would have expected this node to reference a mesh or have a child node. 

A somewhat more correct behaviour can be achieved by keeping everything in the same scene in Blender:

Steps to reproduce the correct behavior:
1. Add Suzanne to the default scene
3. Move Suzanne to a new collection named "Monkey"
5. Add -> Collection Instance -> Monkey
6. Move the Monkey instance a bit
7. Export to glTF

**Expected behavior**
In this case both monkeys show up in the file correctly. One original and one "instance".

**.blend file/ .gltf**
The zip file contains one working and one non working *.blend file. Also corresponding *gltf files:

[Blender bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8355636/Blender.bug.zip)

**Version**
 - OS: Linux
 - Blender Version: 3.1

**Comment by julienduroure** [comment]
Hello,

Please test with 3.2 alpha. There is big refactoring between 3.1 and 3.2 to manage collection instance correctly.

**Comment by julienduroure** [comment]
I confirm that the problem is already solved:

![image](https://user-images.githubusercontent.com/1696020/160245149-3ea2c09c-875d-401e-8ad2-e556c4fe0bc6.png)

**Comment by morganbengtsson** [comment]
Indeed works as intended now. Thanks for the response.
