### ISSUE TITLE
Trouble working on adding extensions support and hooks

### ISSUE THREAD

**Issue by elmajime** [KhronosGroup/glTF-Blender-IO#1604]
Hi,

I'm currently working on adding :
- KHR_materials_transmission export
- KHR_materials_pbrSpecularGlossiness import
- adding the ability to use import/export hooks for extras and extensions.

But I'm having some difficulty with the export process for the transmission: the addon crashes in from_extension because it can't convert my Extension to a dict. 

The thing is, on this particular use case it only contains the TransmissionFactor as a number.

My current code for the export is as follows:

    def __gather_transmission_extension(blender_material, export_settings):
    transmission_enabled = False
    has_transmission_texture = False

    transmission_extension = {}
    transmission_slots = ()

    transmission_socket = gltf2_blender_get.get_socket(blender_material, 'Transmission')

    if isinstance(transmission_socket, bpy.types.NodeSocket) and not transmission_socket.is_linked:
        transmission_extension['transmissionFactor'] = transmission_socket.default_value
        transmission_enabled = transmission_extension['transmissionFactor'] > 0
    elif __has_image_node_from_socket(transmission_socket):
        transmission_extension['transmissionFactor'] = 1
        has_transmission_texture = True
        transmission_enabled = True

    if not transmission_enabled:
        return None

    # Pack transmission channel (R).
    if has_transmission_texture:
        transmission_slots = (transmission_socket,)

    if len(transmission_slots) > 0:
        combined_texture = gltf2_blender_gather_texture_info.gather_texture_info(
            transmission_socket,
            transmission_slots,
            export_settings,
        )
        if has_transmission_texture:
            transmission_extension['transmissionTexture'] = combined_texture

    return Extension('KHR_materials_transmission', transmission_extension, False)

Would anyone know what is wrong with it ?

Thanks a lot.
PS: I'll make it public in the weeks to come

**Comment by julienduroure** [comment]
Hello,
Before checking your problem, I want to let you know that exporting KHR_materials_transmission is already part of this addon (without use of user extensions) :
https://github.com/KhronosGroup/glTF-Blender-IO/blob/c2188bab7f68a2597109e0e4ae2d9bd5d07f0c6d/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L431

**Comment by elmajime** [comment]
@julienduroure  Ok my bad I added the import of the transmission (it's been too long I worked on this code ^^")
But the addon fails to export the transmission with a value of 1

**Comment by julienduroure** [comment]
I don't have any issue with latest master to export transmissionFactor of 1. Please share your .blend file if we are able to reproduce with current master code.
![image](https://user-images.githubusercontent.com/1696020/160788688-26e79a70-c0fb-471c-9ca2-29bdb9de4ab3.png)

**Comment by julienduroure** [comment]
BTW, importing / exporting official ratified KHR extensions should be done in core glTF-Blender-IO addon, not in user extensions, to be available for everyone.

**Comment by elmajime** [comment]
@julienduroure yes of course, I handle transmission import and SpecularGlossiness export in the addon itself and all other extensions using another addon.

ps: seems that it was a problem with Blender python cached classes because after restarting it I don't have the problem anymore. Closing the issue, sorry for the inconvenience.
