### ISSUE TITLE
Model gets corrupted after export and import

### ISSUE THREAD

**Issue by nnpa** [KhronosGroup/glTF-Blender-IO#1607]
**Describe the bug**
Model gets corrupted after export and import

**To Reproduce**
1. Download model https://disk.yandex.ru/d/zngGFeFtGNykFg
2. Open model in blender
3. Export to gltf (glb) 
4. Open new blender project
5. Import glb model
6. See corrupted model

**Expected behavior**
expected import without error

**Screenshots**
https://www.youtube.com/watch?v=OJj_EGvkGM0&feature=emb_logo

**.blend file/ .gltf**
https://disk.yandex.ru/d/zngGFeFtGNykFg

**Version**
 - OS: Ubuntu 20.04
 - Blender Version 2.7

**Comment by scurest** [comment]
This is an export problem. Note that this model has unweighted vertices, so it will need #1552, which went in three days ago. It currently results in this:

**Comment by scurest** [comment]
Based on manual testing, the exact threshold appears to be 0.0001. Weights <= 0.0001 have no effect. (Still couldn't find it in the Blender source code though.)

**Comment by nnpa** [comment]
For the model to work correctly, do I need to add a neutral bone and a weight of 0.0001 to it?

**Comment by julienduroure** [comment]
@nnpa Hello,

I am not sure what exact version of Blender we are using, because 2.7x series is very old and no more supported. We will need 3.2 alpha. 

We will fix the problem in the code. 
Except if you need a way to fix the problem in next very days, I suggest you to wait we fix the bug, and we will be able to use Blender 3.2 alpha to export your model.

**Comment by nnpa** [comment]
@julienduroure 
Ok Thanks how do i know when the problem is fixed?

**Comment by Ali-RS** [comment]
>Ok Thanks how do i know when the problem is fixed?

Just keep track of this page, when it is fixed, this issue will be closed.

>And how to install 3.2 alpha on ubuntu?

https://github.com/KhronosGroup/glTF-Blender-IO#installation

**Comment by julienduroure** [comment]
@nnpa 
When fixed, you will be able to download 3.2 alpha here : https://builder.blender.org/download/daily/
There is no need to install on Ubuntu. Just unzip and run.

I will let you know here when it will be fixed

**Comment by julienduroure** [comment]
@nnpa 
This bug is now fixed here.
You will be able to test in Blender 3.2 alpha, starting tomorrow.
You have to check that date of 3.2 build is after April 4th
