### ISSUE TITLE
Save/load presets for export settings

### ISSUE THREAD

**Issue by UX3D-schmithuesen** [KhronosGroup/glTF-Blender-IO#161]
Instead of the Save Settings button, add a preset selection and save/load mechanism like in the .fbx exporter.

_Originally posted by @UX3D-becher in https://github.com/KhronosGroup/glTF-Blender-IO/issues/143#issuecomment-444795372_

**Comment by emackey** [comment]
Is there a timeframe on this?  The previous saved settings feature was removed, and there are a lot of different settings to keep track of.

**Comment by UX3D-schmithuesen** [comment]
> 
> 
> Is there a timeframe on this? The previous saved settings feature was removed, and there are a lot of different settings to keep track of.

I might have underestimated the importance of this, but I can simply re-introduce the old button (into the new style) and add removing it as part of this issue.
