### ISSUE TITLE
Sub-Group also for internal collection

### ISSUE THREAD

**Issue by pafurijaz** [KhronosGroup/glTF-Blender-IO#1617]
I noticed one useful thing, now linked collections create groups of sub-assemblies but this unfortunately only works with external collections and does not create sub-groups of normal collections, too bad, because it would also be useful to have internal collections sub-assemblies.

As you can see from the attached image there are sub-assemblies in the tree of objects with CAD Assistant, as happens for the STEP files with the various sub-assemblies, but the groups of the internal collections are missing.

Thanks

**Additional context**
![image](https://user-images.githubusercontent.com/11751383/162291558-9cbe6262-8f4d-4418-a601-250349c4ab5c.png)

**Comment by julienduroure** [comment]
Hello,

Collections are not part of the dependency graph (except when instanced), so there is no easy way to get them.
An object can be put into several collections too, so we can't use collection as an empty node in glTF.

Not sure this is something we can/want to implement

**Comment by pafurijaz** [comment]
Hi and thanks for your attention, I understand that this cannot be simple to implement, but this feature would be very useful for sharing mechanical models, because this would allow you to be able to transpose the organization of the scene, even on the GLB file, with assemblies and sub-assemblies and single objects, however I have noticed that this can be done with Empty  objects as a parent. 

![ScreenShoot](https://user-images.githubusercontent.com/11751383/162408045-c5e29eb4-06f1-463a-8eb3-bf14f5addf0e.png)


But for example you cannot create a parent with an empty object and the parental link of internal collections and linked from external files.


This can only be done if I also connect the parent collection in a new scene as you can see from this screen shot where I also connected the Tables collection which is the collection where I put all types of objects, Tables is now the parent of the various sub-assemblies.
![ScreenShot-Linked-Tables-collettion](https://user-images.githubusercontent.com/11751383/162407888-edd360c9-dd36-4447-ac1d-7454af0e82a1.png)

I attach all the files both GLB and the various scenes in the zip archive; 
which contains in detail: the scene with the single table (**ASM-Table.blend**), and also the one with an internal and external connected collection (**Table-with--append_and-linked-Collection.blend**) and finally also the one with the link to the parent of the scene present in the file (**Linked-Collection-Tables.blend**).
[Table.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8450650/Table.zip)


Thank you and greetings.

**Comment by pafurijaz** [comment]
Heck I noticed that in the screenshot above I lost an object in the export as you can see from this Blender screenshot of the file (**Table-with--append_and-linked-Collection.blend**)   Is this a bug?

![Lost-a table](https://user-images.githubusercontent.com/11751383/162411510-2346acba-2106-4972-b3f9-c99f13db5533.png)

Greetings

**Comment by julienduroure** [comment]
Closing this ticket, as there is now an option to export collections as empty node
