### ISSUE TITLE
RuntimeError: Could not parse python long as longdouble

### ISSUE THREAD

**Issue by yusufk** [KhronosGroup/glTF-Blender-IO#1628]
**Describe the bug**
I'm using Blender Version 3.1.2 (3.1.2 2022-04-01) on MacOS Montery. When I attempt to export to GLTf, I get a Runtime Error, seems related to Numpy.

**To Reproduce**
1. Go to Blender
2. Click on export
3. Keep default options and click export

**Expected behavior**
The objects are exported to GLTf

**Screenshots**

**.blend file/ .gltf**
I can't I'm afraid.

**Version**
 - OS: MacOS Montery
 - Blender Version3.1.2

**Additional context**

**Comment by yusufk** [comment]
![Screenshot 2022-04-14 at 16 27 46](https://user-images.githubusercontent.com/404139/163413761-e91689d4-8632-4936-a737-5771a88a850d.png)

**Comment by julienduroure** [comment]
Hello,

Seems this is not linked to glTF exporter, but how python is packaged into Blender.
Can you please :
- Test with Blender 3.2 alpha ( https://builder.blender.org/download/daily/ )
- If error is still there, please test the following :

- Open Blender
- Open Python Console Editor in Blender
- run "import numpy as np"

If you have the same error, please open a ticket on https://developer.blender.org/
