### ISSUE TITLE
'gather_material_hook' callback failed to call after generating unlit material

### ISSUE THREAD

**Issue by kongxiaojian123** [KhronosGroup/glTF-Blender-IO#1630]
https://github.com/KhronosGroup/glTF-Blender-IO/blob/9d9d47a0a93e014f1f0c2918e23bf1033eedaeef/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L54-L55

Normally, the 'gather_material_hook ' callback is performed after any material is generated, but when the material is unlit material, the callback does not work.
https://github.com/KhronosGroup/glTF-Blender-IO/blob/9d9d47a0a93e014f1f0c2918e23bf1033eedaeef/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L132

**Comment by julienduroure** [comment]
Confirmed, there was not hook in case of unlit materials.
Fixed in #1631

**Comment by scurest** [comment]
There's a [`gather_material_unlit_hook`](https://github.com/KhronosGroup/glTF-Blender-IO/blob/9d9d47a0a93e014f1f0c2918e23bf1033eedaeef/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L516), do you want to delete that?

**Comment by julienduroure** [comment]
Not sure what is best for extension developers:
- Having 2 different hooks if he/she want to change all materials (current master)
- Having a general hook for all materials + a specific for unlit (current PR)
- Having only 1 hook, but if dev want to modify only unlit materials, more checks are needed (current PR + deletion of gather_material_unlit_hook )
