### ISSUE TITLE
File with multiple scenes does not export the current scene as the main view

### ISSUE THREAD

**Issue by pafurijaz** [KhronosGroup/glTF-Blender-IO#1632]
**Describe the bug**
Hi, I have a file that I tried to make with internal scenes and when I export I don't have the possibility to see the main scene.
  I noticed the problem because I have a file I'm working on and with CAD Assistant I get an error so I tried with the online viewer [glTF Editor](https://www.gltfviewer.com/) to check if the problem persisted.

Trying with the viewer I could see that in fact the add-on exports all the scenes inside, but the one I'm interested in is not displayed as the main one, but I can nevertheless select it and save the file, with the [glTF Editor](https://www.gltfviewer.com/) and work around the problem temporarily.  

This is a problem though because I would just like to export the selected objects without having multiple scenes in a glb file.

**To Reproduce**
1. Select collection on 00 Main scene (ASM Table) 
2. Export to glb
3. select option only selected and apply modifiers
4. and Open with a viewer (maybe [Cad Assistant](https://www.opencascade.com/products/cad-assistant/))

**Expected behavior**
I would like to be able to export only selected objects without internal scenes

**Screenshots**
This is my main scene which contains objects in other scenes, some are linked from an external file and some are internal.
![Main scene objects](https://user-images.githubusercontent.com/11751383/163971915-011cb626-2282-4044-9a88-f24cb3ae90a0.png)

This image shows that various interior scenes are present but however there is also an error because an object is missing from the vase present in that interior scene in the .blend file
![Export_main_result](https://user-images.githubusercontent.com/11751383/163971561-435a4503-8498-4a98-ac65-a7c67e685004.png)

Here instead I have selected with the glTF editor the scene that interests me and I can also save it correctly and open it with Cad Assistant, and the vase that is in the same scene as the monkey is also visible.
![Main-Scene-on glTF-Editor](https://user-images.githubusercontent.com/11751383/163972507-c4e8f09d-4a39-46f4-a225-7b0a89a07917.png)

And lastly what I see in Cad assistant.
![CAD-Assitant missing obj](https://user-images.githubusercontent.com/11751383/163973027-e61d481c-421d-4066-8fa5-69208123143a.png)

**.blend file/ .gltf**
File for Blender
[Multiple_Scene.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8511730/Multiple_Scene.zip)
But I avoid to attach the glb file because is a bit heavy

**Version**
 - OS: [Linux]
 - Blender version: 3.2.0 Alpha, branch: master, commit date: 2022-04-17 22:21, hash: bf80dc2bd4ac, type: release
build date: 2022-04-17, 23:54:23

**Additional context**
It's complex to report bugs, however I have another problem but I cannot share the file, I hope to be able to reproduce the problem in another way, Regards

**Comment by julienduroure** [comment]
I can confirm that all scenes are exported, but the default scene (gltTF root->scene) is not set correctly

**Comment by pafurijaz** [comment]
> I can confirm that all scenes are exported, but the default scene (gltTF root->scene) is not set correctly

Hi, very good that this has been corrected, but perhaps we should also add a new option that gives the possibility to choose whether to export only the current scene instead of all of them.  
Greetings

**Comment by julienduroure** [comment]
Hello,
Good idea. I added this option. Off by default, this way this doesn't change the default export
