### ISSUE TITLE
Exporting mirrored objects (scale ne 1) results in displacement

### ISSUE THREAD

**Issue by moonphone** [KhronosGroup/glTF-Blender-IO#1635]
NOTE i am in use of a [fork of this repo](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS) but reporting here since i think this issue might be discussed at "center" to reach the whole community.  

I designed a mechanical rig (landing gear). The root node is an armature. All parts are parented to the corresponding bone or object.
![image](https://user-images.githubusercontent.com/104312523/164982672-30e6c903-c569-4698-865f-c513df3186f1.png)

To keep the model "clean" i want to mirror the animated mechanics to the opposite side. So far, all my attempts have been missed. 

1. Add collection instance (of LandingGear) 
2. Make instance real
3. Mirror armature (X-Global) => since all parts are parented, they are placed correct after this step.
4. Whitin Blender everything seems fine 
5. Export glTF

Another attempt:
1. Symmetrize armature (so one rig for left and right)
2. Duplicate link from all gear parts
3. Mirror duplicates
4. Reparent duplicates to symmetrized bone
5. Do the animation stuff for the new bones/parts
6. Export glTF

Both attempts failed, because parts/objects in the exported glTF are misplaced in comparison to the blender scene.

Expected behavior would be to have the same orientation of objects and animation working after the export.

Blender scene...
![image](https://user-images.githubusercontent.com/104312523/164982472-cfb58245-036b-42a0-a690-0d657fbb735f.png)
export...
![image](https://user-images.githubusercontent.com/104312523/164982427-7a084d2c-a2f1-42ed-bd85-37f9d1778601.png)

**Version**
 - OS: Windows 10
 - Blender Version 3.1
 - https://github.com/AsoboStudio/glTF-Blender-IO-MSFS

**Files**
I uploaded 3 samples to reproduce...

- symmetrized armature and mirrored objects
- just mirrored the instanced collection
- made the instanced collection real and mirrored just the root (armature)

[issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8554006/issue.zip)

**Comment by julienduroure** [comment]
Hello,
As requested, can you please upload a test file?
A big refactoring happen between 3.1 and 3.2, so test only with 3.2 alpha version.
I don't know what version is used by the fork repo.

**Comment by moonphone** [comment]
Thanks for the hint @julienduroure. I will try it on 3.2

**Comment by moonphone** [comment]
So now i am really confused. I opened the exported glTF (created with Blender 3.1 and mentioned fork) with 3D-Viewer (Windows 10 includes)

As you can see, the glTF seems to be ok.
![image](https://user-images.githubusercontent.com/104312523/165149110-55eb7a7f-542c-4d46-8eba-412b850e4b70.png)

**Has to be an issue in the build workflow within the MSFS 2020 SDK.**

And after investigating the logs from the build...
![image](https://user-images.githubusercontent.com/104312523/165160405-2931b111-ce3e-4a0b-8643-f461f99d56f0.png)

So, this is not an issue with the export at all.
