### ISSUE TITLE
POSITION min max values not Consistent between mesh and skin when have scale

### ISSUE THREAD

**Issue by YongGame** [KhronosGroup/glTF-Blender-IO#1637]
**Describe the bug**
I use blender 3.1.2 import Duck.gltf and Fox.gltf,  And re-export them . 
Duck.gltf is a static grid, and the min and Max of Position are not affected by the hierarchy transition after export  .
Fox.gltf is a skinned grid, and when set the root zoom to 0.1 and re-export, i find that the min and Max values are affected by the root zoom .

the assets from here: 
duck.gltf: https://github.com/KhronosGroup/glTF-Sample-Models/tree/df4031bebc452b9de73e21050b95530624ae89f6/2.0/Duck/glTF
fox.gltf: https://github.com/KhronosGroup/glTF-Sample-Models/tree/df4031bebc452b9de73e21050b95530624ae89f6/2.0/Fox/glTF

**To Reproduce**
1. use blender import Duck.gltf and Fox.gltf
2. Export duck.gltf directly 
3. Scale fox.gltf root 0.1 and export 
4. For the two exported GLTFS, they both contain only one mesh and are at a similar level ,However, the min and Max of POSITION are applied and the other is not.  

**Screenshots**

fox.gltf  Node hierarchy scaling takes effect  for min max values
![fox](https://user-images.githubusercontent.com/13655373/165064760-c945d3fc-1d8d-425c-84f4-3a3f5f87e8de.png)
duck.gltf  Node hierarchy scaling does not take effect for min max values
![duck](https://user-images.githubusercontent.com/13655373/165064795-0ecaaf0e-47cc-4fe0-a0f1-e928f09f3056.png)

**Comment by julienduroure** [comment]
Hello,
Don't think there is a bug.
Accessor of mesh are expressed in local, so scale  has not to be taken into account 
But for skinned meshes,  meshes will be transform by IBM. That explains why this is not directly local data in accessor.

**Comment by YongGame** [comment]
Thanks for your reply, I understand.
