### ISSUE TITLE
Use 3.2 color attribute API for linear color conversion

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#1648]
3.2 adds a new color attribute system, basically superseding vertex colors. There's several things to consider for glTF support, but one thing that can be done right away is accessing colors through the new `mesh.color_attributes` API, because that always uses linear space. That means the addon can get rid of its own color conversion code, which will be simpler and faster.

Example:

```py
# old
colors = lin2srgb(colors)
mesh.vertex_colors["Col"].data.foreach_set("color", colors)

# new (lin2srgb done for you)
mesh.color_attributes["Col"].data.foreach_set("color", colors)
```

**Comment by julienduroure** [comment]
Thanks!
It seems I missed this update :)
