### ISSUE TITLE
Crash when scene contains a Bezier curve on 3.2 beta

### ISSUE THREAD

**Issue by KyleNBurke** [KhronosGroup/glTF-Blender-IO#1650]
**Describe the bug**
I'm using the 3.2 beta and if you simply add a Bezier curve to the scene then export the scene using the gltf exporter with the default configuration, blender will crash. This does not happen with 3.1.2.

**To Reproduce**
1. Open application
2. Add a Bezier curve
3. Export the scene with default settings

**Expected behavior**
I'm not sure what should happen with the curve, I'd imagine it would just get ignored during the export. Surely, the application shouldn't crash though.

**Version**
 - OS: windows
 - Blender Version: 3.2 beta, the exact build is `blender-3.2.0-beta+v32.018acc568893-windows.amd64-release`.

**Comment by julienduroure** [comment]
Confirmed.
Seems this is from Blender core code, not from this addon, because exporting with Blender 3.1 and addon master --> exports OK.
See https://developer.blender.org/T98237

**Comment by julienduroure** [comment]
Seems the original bug is now fixed in Blender.
Waiting until tomorrow to test on a build that includes the fix

**Comment by julienduroure** [comment]
Confirmed that problem is now solved on Blender side, so this bug is also fixed.

Note : Curves are not ignored if we choose option to export loose edge and loose vertices. Curve are converted to mesh and exported.

**Comment by KyleNBurke** [comment]
That was quick, thanks!
