### ISSUE TITLE
GLTF import alters scene hierarchy for skinned items

### ISSUE THREAD

**Issue by Mondkalb1** [KhronosGroup/glTF-Blender-IO#1652]
**Describe the bug**
**When importing a GLTF file in Blender, it forces all objects that are skinned to a specific Armature to be children of that Armature in the hierarchy.**

Contextual image:
The left side shows the scene how it was constructed in blender natively.
The right side shows that same scene after being saved to gltf, and then imported again into a new empty scene in Blender.
![issue](https://user-images.githubusercontent.com/67538733/169964230-284cc59e-fc70-4cb9-b402-27701d568073.jpg)

**To Reproduce**
1. Download the attached cubeBones.zip and extract it
2. Open the cubeBones.blend file in Blender
3. Observe the hierarchy. We have "Cube" under LOD_0 node, and "Cube.001" under LOD_GEO node.
4. Export this complete scene as .gltf
5. Clear the workspace so that you have an empty scene without default cube
6. Import that newly saved .gltf file
7. Observe the hierarchy. We now have both "Cube" and "Cube.001" under the "skel" armature. They don't belong there.

**Expected behavior**
The scene hierarchy of the objects shall be preserved. They must not be force-moved to be in the hierarchy under the skeleton, but remain where they were.

**.blend file/ .gltf**
[cubeBones.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8760016/cubeBones.zip)

**Version**
 - OS: Win 10
 - Blender Version 3.1.0

**Additional context**
This may be by convention and design, as we noticed the FBX import does this also. However, it is critical for us that the actual structure is maintained. We were also able to determine that the gltf export accurately writes this hierarchy correctly, only during the import into blender does this reshuffling happen.

Ideally this would be an optional boolean toggle to disable this default behaviour.

**Comment by Mondkalb1** [comment]
@julienduroure Thank you for the insight. I has a suspicion it would by convention.

We might look into a small modification ourselves, would _imp\gltf2_blender_node.py_ the place to start looking? Any recommendations/suggestions? Thanks again.

If we get anywhere we'll shoot a PR back for review.

**Comment by julienduroure** [comment]
No issue here, not sure there is something that can be done. Closing. Don't hesitate to comment if you want to add some extra infos.
