### ISSUE TITLE
Strange bone displacement when exporting deformation only bones

### ISSUE THREAD

**Issue by antourenein** [KhronosGroup/glTF-Blender-IO#1659]
**Describe the bug**

In Blender 3.2 RC, exporting a model rigged with a rigify rig and checking the option Export Deformation Bones Only causes some unexpected displacement of certain bones.

How the model looks and animates originally:

https://user-images.githubusercontent.com/79013106/171981310-fb34b39f-7fc5-4ce5-8590-bdc7ee309fae.mp4

How the model looks after being exported and then re-imported:

https://user-images.githubusercontent.com/79013106/171981548-b2948769-120c-4cf5-abcc-2c724d5babac.mp4

(The hands are the main strange point here. It also looks like this in every other viewer I tested, which were Godot Engine and Sketchfab.)

In Blender 3.1 exporting with the same settings looked fine, even if the bone ordering was shuffled around in the gltf file at each export:

https://user-images.githubusercontent.com/79013106/171981844-fb8467df-cf38-4b6c-8698-c892a1e7a2cd.mp4

**.blend file/ .gltf**

[dummy-blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8836984/dummy-blend.zip)

**Version**
 - OS: Windows 10
 - Blender Version: blender-3.2.0-candidate+v32.2d9c5f3dcf2e

**Comment by julienduroure** [comment]
Confirmed.
Fixed in 65e2df6aa1459c213fa76a471abfe671185ee126

**Comment by QuePasitos** [comment]
@antourenein Shame on you Julien you worthless loser slave. Shame on you cheap loser slave for openly promoting those stupid clown daft idiots (I am referring to that disgusting red 8-letter word which is pinned on the building in your trashy "Earthbound Dimensions Godot 4 Port" game ). Death to you and death to every loser slave supports those stupid slaves. 

You're an open promoter of racism and stupidity by promoting those idiots. Death to the stupid "health" and every dumb loser idiot slave who works for that trashy area. You showed nothing other that how stupid and cheap you mainstream propaganda clowns area. Death to "universities". Death to every low life lower clown who uses those stupid and childish and pathetic "prefixes" when mentioning first names. Death to open source. Hope you have a tragic life and painful death.

**Comment by QuePasitos** [comment]
@antourenein Shame on you Julien you worthless loser slave. 

Shame on you cheap loser slave for openly promoting those stupid clown daft idiots (I am referring to that disgusting red 8-letter word which is pinned on the building in your trashy "Earthbound Dimensions Godot 4 Port" game ). 

Death to you and death to every loser slave supports those stupid slaves. 
You're an open promoter of racism and stupidity by promoting those idiots. Death to the stupid "health" and every dumb loser idiot slave who works for that trashy area. You showed nothing other that how stupid and cheap you mainstream propaganda clowns area. Death to "universities". Death to every low life lower clown who uses those stupid and childish and pathetic "prefixes" when mentioning first names. Death to open source. Hope you have a tragic life and painful death.

**Comment by QuePasitos** [comment]
Mechanical Engineering is the ONLY ENGINEERING
