### ISSUE TITLE
Shape keys break normals on exported mesh

### ISSUE THREAD

**Issue by and-rad** [KhronosGroup/glTF-Blender-IO#1660]
**Describe the bug**
Normals appear wrong on a smooth-shaded mesh that was exported via the GLTF exporter if the mesh contains any shape keys that significantly alter its shape.

**To Reproduce**
1. Load the default scene, subdivide the cube a couple of times, apply the **Shade Smooth** operator
2. Create a shape key and deform the mesh significantly
3. Reset the shape key value to 0 and export the mesh as .glb file, limiting the export to selected objects only but leaving all other parameters at their default values.
4. Import the exported file and notice how the shading differs from the original. It looks like the normals that belong to the shape key are applied to the base morph.

**Expected behavior**
The normals of the imported mesh should appear identical to the original when all shape key values are set to 0.

**Screenshots**

https://user-images.githubusercontent.com/8700280/172047917-90cc49e6-2bcf-4eec-bd03-723b9ef31f1b.mp4

The effects of the shape key on the cube mesh.

![gltfbug](https://user-images.githubusercontent.com/8700280/172046981-d4f2af40-00d0-4f46-bf91-400d767af592.PNG)
Original mesh in the back, imported mesh in the front. The mesh is not deformed, yet the normals clearly belong to the shape key.

**.blend file/ .gltf**
[GLTFBug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8839812/GLTFBug.zip)
Included are .blend, .glb, and .gltf files

**Version**
 - OS: Windows 10
 - Blender Version: 3.1.2

**Additional context**
This is very likely an export problem because the normals appear broken in external GLTF viewers as well as in [Godot 4.0](https://github.com/godotengine/godot). I provided the minimal steps necessary to cause the bug to happen, but I checked different export parameters and mesh configurations extensively. The bug happens for meshes with or without custom split normal data and checking/unchecking various export parameters relating to normals and tangents doesn't make any difference either.

**Comment by julienduroure** [comment]
Thanks for the report.
I can confirm on 3.1, but problem is already solved in 3.2 (that is currently in Release Candidate state, release is planned next week).
Closing this report. Don't hesitate to comment, I will reopen it if I missed something.
