### ISSUE TITLE
Exported glb shows texture material as white

### ISSUE THREAD

**Issue by anixan** [KhronosGroup/glTF-Blender-IO#1675]
**Describe the bug**
I have a material that is generated from a Substance Material and applied to my model, looks fine in Blender, however when I export into blb format and load in a viewer the texture material just shows as white.

**Expected behavior**
I would expect that the texture material gets exported and is useable and viewable from the glb file.

**Screenshots**
![Texture/Material showing in blender](https://user-images.githubusercontent.com/2204895/175781288-c69d3d58-eec0-41bb-b3b4-489d96cb662c.png)

![The Material properties](https://user-images.githubusercontent.com/2204895/175781271-3311012d-13e4-48a1-b7ec-c1851dbaa76b.png)

![GLB File loaded in a Babylon viewer](https://user-images.githubusercontent.com/2204895/175781297-e18b7a3b-c7c1-4169-b911-7e41ac062a12.png)

**.blend file/ .gltf**
[GLB & Blend Files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8985136/GLB.Blend.Files.zip)

**Version**
 - OS: MacOS
 - Blender Version 3.1.2

**Additional context**
You may need the Substance 3D Blender Addon installed to replicate this I am not sure, only just started to look at getting sbs materials into blender and then out exported out in glb format.

**Comment by julienduroure** [comment]
Hello,
This setup use a custom node group. 
This is not something we support for now.
You can refer to documentation to see how you can create your node tree. :
https://docs.blender.org/manual/en/3.2/addons/io_scene_gltf2.html

**Comment by julienduroure** [comment]
See some tests done here: #1536

**Comment by julienduroure** [comment]
Closing this ticket, as now NodeGroups are handle correctly
