### ISSUE TITLE
Every object of the armature gets an animation track after export.

### ISSUE THREAD

**Issue by AsuraSloth** [KhronosGroup/glTF-Blender-IO#1681]
Hi all,

I'm sorry if this isn't the right place to ask but I haven't received any replies on my post at blender stack exchange. My issue is that I only need to export one animation from the blender file. But each object from my armature is getting a blank animation track. **Im on blender version 3.2.0**

Before Export
![Annotation 2022-07-03 182152](https://user-images.githubusercontent.com/85283488/177368418-487dd58e-6a94-4c34-a074-e5d3aeb21684.png)

After Export
![Annotation 2022-07-03 182328](https://user-images.githubusercontent.com/85283488/177368450-200cd53e-6846-43cc-a50d-ef742b49ca25.png)

Here's my outliner. The objects are parented to my armature.
![Annotation 2022-07-03 182400](https://user-images.githubusercontent.com/85283488/177368555-3021d661-581b-4069-b300-398367133c38.png)

This is my animation export settings. I assure you I am have enabled the apply modifiers settings as well.
![Annotation 2022-07-03 182458](https://user-images.githubusercontent.com/85283488/177368636-83c83347-b414-4a98-a1fa-73e4d3da0b3f.png)

Again I'm sorry if this isnt the right place to ask. But I would like to know how to fix the issue if its possible

**Comment by julienduroure** [comment]
Hello,
Can you please upload your test case?
Probably related to #1680

**Comment by AsuraSloth** [comment]
I downloaded a Mixamo Model to replicate my issue. Notice the Beta_Joints and Beta_Surface animation tracks. They are empty tracks that were exported. Thank you for your time.

[Mixamo Test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9051416/Mixamo.Test.zip)

**Comment by julienduroure** [comment]
Hello,
No bug here.
Seems your exported with option "Limits to selected objects". 
That means that every objects will be baked and exported, including their baked animation.

2 possibilities for your:
- Don't use limits to selection
- Use "Optimize Animation Size", that will remove animation that are constant (this is the case for your meshes)
Thanks !
