### ISSUE TITLE
Major bone distortion when exporting with Spline IK bone constraint.

### ISSUE THREAD

**Issue by jitspoe** [KhronosGroup/glTF-Blender-IO#1683]
**Describe the bug**
If you use the Spline IK bone constraint and then export an animation with GLTF, the bones are squashed, as though scaled on the wrong axis.

**To Reproduce**
1. Create an armature with chain of bones.
2. Add a bezier curve
3. On the last bone in the chain, add a "Spline IK" bone constraint.  Set the chain length to the number of bones in the chain.
4. Create a new action.
5. Select all bones.
6. Press I and select "Location, Rotation & Scale" to insert a keyframe.
7. Stash the action
8. Export to GLTF
9. Import the GLTF file and note the distortion.

**Expected behavior**
The bone positions should be the same as they were in the original animation keyframe.

**Screenshots**
Before export:
![image](https://user-images.githubusercontent.com/7751182/179174476-ba2a26f3-772a-4e6e-802f-2c5fe2e5a63a.png)
After import:
![image](https://user-images.githubusercontent.com/7751182/179174572-a9db2c99-5c31-4612-9657-a9d777aa5d7e.png)

Bones are also scaled wrong in Godot, so this leads me to believe it is purely an export issue, not an import issue.

**.blend file/ .gltf**
[spline_ik_gltf_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9118865/spline_ik_gltf_bug.zip)

**Version**
 - OS: Windows 10
 - Blender Version 3.2.1

**Comment by julienduroure** [comment]
Confirmed

**Comment by julienduroure** [comment]
Seems this is same that #1083 
at some point of animation, matrix can not be decomposed into TRS.
One solution, if we want to export this animation anyway, is to flatten the hierarchy tree of bones.
Some tests are done in this branch https://github.com/KhronosGroup/glTF-Blender-IO/tree/experiment_hierarchy

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

For non decomposable matrix into TRS, we added an option to flatten the bone hierarchy at export.

**Comment by jitspoe** [comment]
Oh, nice.  Does this also fix https://github.com/KhronosGroup/glTF-Blender-IO/issues/1083 ?

**Comment by julienduroure** [comment]
Hello,
No. This option is only for bones.
We may have to implement it for objects too, at some point
