### ISSUE TITLE
Blender Export to Godot Import bone deformation in animations

### ISSUE THREAD

**Issue by Nekuromu** [KhronosGroup/glTF-Blender-IO#1684]
When I finish designing animations for my current rig, and then export from Blender; Importing into Godot everything seems to be working fine until I view the animations to which I can see some have deformities compared to the blender versions.

![image](https://user-images.githubusercontent.com/30809120/179405764-79693e92-24ea-41e8-b549-145def461c15.png)
![image](https://user-images.githubusercontent.com/30809120/179405773-b700aec9-08d6-423d-8ac5-6f9dfd16292c.png)

 - OS: Windows 10
 - Blender Version 3.0.0
 - Godot Version 3.4.4

**Comment by julienduroure** [comment]
Hello,
Please test with a more recent version : 3.2.1
Version 3.0 is no more supported.
If problem is not solved, please provide the .blend file
Thanks!

**Comment by Nekuromu** [comment]
Just made the troubleshooting rounds, and updating Blender to 3.2.1 seems to have fixed the animation oddities. Thanks for reaching out! I was hopeful the problem could be solved easily. Always nice when the first few troubleshooting steps take it out!

![image](https://user-images.githubusercontent.com/30809120/179418947-060fe11c-acf3-460b-b100-a6e4a7b284d4.png)
