### ISSUE TITLE
Index of refraction for transmission not exported

### ISSUE THREAD

**Issue by danielseow** [KhronosGroup/glTF-Blender-IO#1689]
Documentation: https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html?#inputs
Blender version: 3.2.1
IOR
Index of refraction for transmission.
![image](https://user-images.githubusercontent.com/55088114/180224807-ae08c068-b32a-456b-9897-f26fedddba83.png)

So I have a glb file provided by 3D designer with one of a material with the configuration above, so the problem now I have from my designer is that the IOR value in subsurface is not exported and the value is remaining at 1 using BabylonJS sandbox to view the properties of the material of exported glb file as the image below

![image](https://user-images.githubusercontent.com/55088114/180224851-f291e458-d93b-49fb-b006-1e463d2f2a69.png)

**Comment by julienduroure** [comment]
What version are you using?
Please test with 3.3 alpha

**Comment by danielseow** [comment]
> What version are you using? Please test with 3.3 alpha

I'm so sorry that I forgot to mention the version of Blender I'm using, I was using 3.2.1. I'm going to test with 3.3 alpha as you mentioned, Hopefully it will return the result that I wanted, thanks!

**Comment by julienduroure** [comment]
Hello,
Subsurface import/export is not implemented on Blender, so corresponding IOR is not taken into account. 
IOR is exported/importing based on IOR in Blender, and using KHR_materials_ior on glTF
