### ISSUE TITLE
assert gltf2_io.py line 52 - accessors

### ISSUE THREAD

**Issue by KammutierSpule** [KhronosGroup/glTF-Blender-IO#169]
First time I am using glTF, with Blender,
I got hit error but I don't know it meaning:
https://i.imgur.com/PthUBnv.png

The file is validated with glTF validator without errors.

Any guideline?

**Comment by julienduroure** [comment]
Hello,
Can you please share the gltf or glb file?

It is probably a problem in one of the extension used in your file. Non standard extensions are not checked with current version of glTF validator.

**Comment by KammutierSpule** [comment]
I didn't get a chance yet to send you a file.
It is generated with project cqparts. I opened a cross issue there:
https://github.com/cqparts/cqparts/issues/132

**Comment by fragmuffin** [comment]
`cqparts` author here... I don't know exactly which model @KammutierSpule is loading, but everything from
[this examples page](https://cqparts.github.io/examples/) is exported from `cqparts`.

Simple geometry: [`Plank`](https://cqparts.github.io/examples/export/helper/Plank/)
- https://cqparts.github.io/model/Plank/out.gltf
- https://cqparts.github.io/model/Plank/out.bin

Complex geometry: [`Rover`](https://cqparts.github.io/examples/export/showcase/Rover/)
- https://cqparts.github.io/model/Rover/out.gltf
- (too many `bin`s to list here)

**Comment by julienduroure** [comment]
@fragmuffin Original Error reported (see screenshot in first comment) seems to be in json content. That's why I really need the gltf file that have the issue.

**Comment by KammutierSpule** [comment]
I got a chance to generate a file, please find the toycar glft files attached.
I used Blender 2.79 and latest glFT addon version from repository.
[toy_car_gltf.tar.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/2685805/toy_car_gltf.tar.gz)
I appreciate if you can point us for where the issue is.

**Comment by julienduroure** [comment]
You have an accessor.count value of 708.0, but accessor.count must be an integer
(cf specification https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessor)
So your gltf file is not valid.
Seems the current version of validator don't check that, I will open an issue

**Comment by fragmuffin** [comment]
Thanks @julienduroure ; that's a good find.
Will be fixed in `cqparts` as part of cqparts/cqparts#132 's closure.
