### ISSUE TITLE
Does exporting a scene to a GLTF involve any compute?

### ISSUE THREAD

**Issue by HabibSlim** [KhronosGroup/glTF-Blender-IO#1691]
I would like to understand what exporting a scene in a GLTF format entails. I have a 3D model with high-definition texture maps, materials, yadee yadee yada, and I'm exporting a scene to a GLTF file.

During this process, is there actually any **compute** involved? What I mean by that is, does exporting the scene to the GLTF format actually involve any rendering, or any computation similar to rendering, or does it just basically bundle the 3D model with embedded textures in JPEG/PNG?

Will it speed up somehow **future rendering**, or does it not make any difference?

**Comment by donmccurdy** [comment]
I assume you are the author of https://stackoverflow.com/questions/73109473/exporting-a-scene-as-a-gltf, but just CC'ing the thread for future readers.

**Comment by julienduroure** [comment]
Closing this ticket, as answer and discussion can take place on stackoverflow (see link above)
