### ISSUE TITLE
Suggestion: "glTF Settings" cleanup

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#1694]
The addition of the "glTF Settings" node to the "Output" dropdown is helpful, but does expose a couple small consistency/naming/docs issues —

![Screen Shot 2022-07-26 at 11 27 37 AM](https://user-images.githubusercontent.com/1848368/181047791-b9aa9a19-de2b-4545-8523-d7edc59fbff0.png)

1. Note the missing tooltip for this item, replaced by "(undocumented operator)". All the other nodes say, "Add a node to the active tree", which is not terribly helpful but okay.
2. Should we consider renaming this "glTF Output" or "glTF Material Output" rather than "glTF Settings" for consistency? Or supporting both, with Output as the default? The node is effectively an output for export purposes.

![Screen Shot 2022-07-26 at 11 40 39 AM](https://user-images.githubusercontent.com/1848368/181049825-cceea714-4ca9-4487-872d-d4b94c4b8178.png)

I'm not feeling so confident about the "glTF Original PBR Data" node. Its name does not match the button shown in the UI, possibly it should just be part of the other glTF Settings/Output node. And Blender 3.3 is the upcoming LTS release, which means we might want to be careful about adding features in that release. Especially with the upcoming Principled BSDF v2 work (which sounds very promising!) I'm not sure we should be planning to maintain this additional node in an LTS release. I'd be inclined to remove it from the menu until a later date.

Thank you, and let me know if PRs would be welcome for any of these changes.

/cc @emackey

**Comment by donmccurdy** [comment]
Points from @emackey  in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1686 is also good. 👍🏻

**Comment by julienduroure** [comment]
> undocumented operator

Will fix it after my holidays

> glTF Material Output

Ok to rename. I will included it in 3.3  ( but I find a  way to keep compatibility with older files, created with old name)

> glTF Original PBR Data

I will fix name consistency between node and menu. 
I disagree about remove it from 3.3
People need a way to export exactly what they want about specular textures/data. I already spend so much of my time explaining why some features are not 1 to 1 between Blender and glTF. This will be the case for specular too.
 Basic users will not use it, but having a way to export exactly needed data for advanced users is a good feature I think. 
Principled v2 will of course not be part of 3.3, so using this node is for me the way to go until v2 is ready (not planned yet I think)

**Comment by donmccurdy** [comment]
Thank you @julienduroure — please enjoy the holidays, my questions can certainly wait until afterward. :)

What is the difference between the "glTF Material Output" and "glTF Original PBR Data" nodes, from your perspective? To me they are both output nodes to ensure that the user's glTF-specific data is included at export — so perhaps they should just be combined into "glTF Material Output"?

Similarly, I think we could allow the "glTF Material Output" node to always take precedence over Principled BSDF, so we would not require an "Export original PBR Specular" output checkbox.

**Comment by julienduroure** [comment]
> What is the difference between the "glTF Material Output" and "glTF Original PBR Data" nodes, from your perspective? To me they are both output nodes to ensure that the user's glTF-specific data is included at export — so perhaps they should be combined into "glTF Material Output"?

My goal was to differentiate these 2 cases:
- Data that are not available in Blender, but can be exported, like AO or thickness. In that case, no choice, we need to use custom socket to export these data.
- Data that are available in Blender, but not fully compatible with glTF, like specular. In that case, the user has the choice at export of using Blender data, with loosing conversion, or using glTF data (not displayed in Blender, but fully compliant exported)

Not sure if we have to have an option at export (this has the advantage to let the user decide exactly what he want at export), or take precedence of original data over Principled Shader ( has to pro to have one less export option, but the con to not let user decide exactly what he want. He will need to remove some socket links - or reset to default - if he want to test exporting both cases).

**Comment by emackey** [comment]
> Data that are available in Blender, but not fully compatible with glTF, like specular.

It's possible that this second option may be temporary.  There's an effort underway to overhaul Blender's Principled BSDF shader, and bring it more in line with glTF's own PBR material model:  https://developer.blender.org/T99447

Of course there's no guarantee when this work might be done or whether it will fully replace all incompatible options.  But to me this is an exciting and hopeful sign that we might not need this second option long-term.

**Comment by donmccurdy** [comment]
At least in my opinion, the cases of "Blender doesn't have this" and "Blender has this, but different" do not require two different nodes. It feels more understandable to present the additional inputs the Blender exporter accepts in one place. Similarly I'd say that, if a socket is connected to this custom node, we can simply assume the user wants these inputs to be exported. But I'm happy to defer to your preference here. :)

**Comment by julienduroure** [comment]
I merged the 2 nodes into a single one here: #1702

**Comment by julienduroure** [comment]
Committed, I think we can now close this ticket

**Comment by donmccurdy** [comment]
Agreed, thank you @julienduroure!

**Comment by julienduroure** [comment]
Hello,

You can check the code used to create the custom group node:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/7b3928dfba4396aafe50405e3ec467c3a1993b21/addons/io_scene_gltf2/blender/com/gltf2_blender_material_helpers.py#L24

https://github.com/KhronosGroup/glTF-Blender-IO/blob/7b3928dfba4396aafe50405e3ec467c3a1993b21/addons/io_scene_gltf2/blender/com/gltf2_blender_ui.py#L27
