### ISSUE TITLE
Animation export/import ?

### ISSUE THREAD

**Issue by motorsep** [KhronosGroup/glTF-Blender-IO#17]
Do you plan on adding animation (skeletal, non-skeletal) export/import to your add-on?

If so, could you please make it in non-convoluted way (without a need in using NLA Editor) with support of multiple Actions ?

Thanks beforehand

**Comment by donmccurdy** [comment]
This project is a combination of [KhronosGroup/glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) and [julienduroure/gltf2-blender-importer](https://github.com/julienduroure/gltf2-blender-importer) — we are not starting from scratch. Animation should work both for import and export already, as it does in the respective projects.

I would welcome suggestions for less convoluted ways of handling Action export, but there must be some way to associate actions with objects, and Blender's APIs do not make this easy. Are you hoping for an option to export a copy of every action for every object? That's a reasonable feature request, but I don't think it can or should be the default behavior.

**Comment by motorsep** [comment]
Oh, heh.. I thought it was whole new add-on :)

I wish I knew how to program and knew Blender's API.. I only dealt with Doom 3 MD5 exporter for Blender and from user perspective it was just that - have Actions in your scene and in the UI of the export check whether to export all of available Actions or have a list where one could select which ones to export. I have the add-on in on my github repo, if you want to see it.

**Comment by donmccurdy** [comment]
At some point we'll archive glTF-Blender-Exporter, and I'll try to move the relevant issues over to this repository. In the meantime feel free to open a new issue with a suggestions. Selecting actions from a list in the export menu does sound really nice. :)
