### ISSUE TITLE
Blender keeps crashing gltf 2.0 on export with this animation

### ISSUE THREAD

**Issue by Nats582** [KhronosGroup/glTF-Blender-IO#1704]
When I try to export this animation it crashes blender

![Broken Anim Screenshot](https://user-images.githubusercontent.com/110804817/183347619-631c6df3-fd69-495e-88cd-35cdcbfb04eb.png)

I was working on this Idle animation I wanted to export to godot

It was just supposed to work I guess, that didn't really happen

blend file: https://drive.google.com/drive/folders/1CABFUhDjxh0qLKUeWAlARUbWrLeAdNyV?usp=sharing

Windows 10
Blender 3.0

Help Much Appreciated!

**Comment by julienduroure** [comment]
Hello,
I can not reproduce crash with recent version.
Please test with current 3.4 alpha or 3.3 beta (https://builder.blender.org/download/daily/)

BTW, there are still some issue not solved about negative frame. You should have to move your keyframes to start at 0.
Keeping this ticket open for now, to keep info about other errors, but initial report is solved on recent versions.

**Comment by Nats582** [comment]
WOW, what do you know the problem really does not exist on newer versions. I tested on 3.2 and this problem is not a problem anymore huh... Thank you soo much tho man, I appreciate the help
