### ISSUE TITLE
Option to choose weight influences at export

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1709]
Requested by Godot Engine team here: https://github.com/godotengine/godot/issues/64275#issuecomment-1213052478

Currently, default is limited to 4, and we can, by checkbox, export all influences.

By glTF specification => Must be N % 4 == 0.

So, what are the solution?
- Replace a checkbox by a dropdown list with 4 / 8 / (12?) / all ?
- Replace by a dropdown list ( Default 4 / Custom / all), and display a slider when custom (+ automatic change value if not a multiple of 4)

Any thoughts?

**Comment by fire** [comment]
I think Maya has a limit of 32, but on a conceptual level..

A display with a slider when custom (+ automatic change value if not a multiple of 4) seems a better fit than say the enum of 4,8,12.
