### ISSUE TITLE
Codify ordering of joints in skins

### ISSUE THREAD

**Issue by spindlebink** [KhronosGroup/glTF-Blender-IO#1712]
I can't find rules anywhere in the spec for the ordering of joints in a skin's `joints` array. From a tentative first look, it seems they're ordered in descending hierarchy (i.e. parent joints always come before children). If the exporter always orders things like this, that'd make a decent number of checks/sorting routines unnecessary on the loader/engine-side. But I feel leery about assuming so without having this information codified, either in the exporter or in the spec itself.

If this isn't currently codified, it'd be nice to have it codified.

**Comment by julienduroure** [comment]
Hello,
There is nothing in glTF specification that restrict order of nodes.
I suggest you to explain more deeply (with an example) how you would like to see it ordered, and how it save time on glTF readers (with some example too).
Not sure this repository is the best place to discuss it, maybe the best place is on glTF repository itself (https://github.com/KhronosGroup/glTF)

**Comment by spindlebink** [comment]
Thanks for pointing me to the spec repo--I asked here because I wasn't sure whether this is more of an exporter-specific question (what order does the exporter export joints in) vs. a spec question. I'll close and re-ask there.
