### ISSUE TITLE
Meshes parented to bones inherit initial (first frame) scale of parent bone

### ISSUE THREAD

**Issue by olliebarbs** [KhronosGroup/glTF-Blender-IO#1714]
When animating the scale of a bone, the initial scale of the bone is propagated to its child meshes. This results in double scaling of the mesh, once by its own scale factor, then again by the animated influence of its bone parent.  

For example, if the bone parent animates from a scale of 0.5 to 1, the scale of the child mesh itself will be set to 0.5. Visually this results in the mesh animating from 0.25 to 0.5 of its indented scale

**To Reproduce**
Create an armature and mesh.
Parent the mesh to a bone in the armature.
Animate the scale of the bone such that the scale of the bone on the first frame of the animation is anything but 1.
Optionally, push this down / stash this animation.
Export using default settings (I have also tried multiple combinations of settings to no avail)

The mesh will be scaled to the same scale factor as its parent bone on the first frame, resulting in a double scaling.

**Expected behavior**
The mesh level scale of any child meshes to be unchanged by the scale of its parent bone/

This expected behaviour was the case in previous versions of gltf exporter up to and including 1.8

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - Windows 11
 - Blender Version 3.2

[scaleTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9416896/scaleTest.zip)
[scaleTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9416902/scaleTest.zip)

**Comment by julienduroure** [comment]
Hello,
This is a duplicate of #1677 
(you can use "use current frame" as workaround until this bug is fixed)

**Comment by olliebarbs** [comment]
Ah perfect, indeed it is. And the "use current frame" solution does indeed solve it. Nice!
