### ISSUE TITLE
Help please: How to install the example export extension

### ISSUE THREAD

**Issue by RaiNova** [KhronosGroup/glTF-Blender-IO#1718]
How can the [example export extension](https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/example-addons/example_gltf_exporter_extension) be installed in Blender 3.2.1?

I copied the init file to a local directory and the selected in in Blender via Edit > Preferences > Add-ons > Install > Install Add-on.

The info window shows 
```
Modules Installed () from 'C:\\Users\\rnova_ebav3ic\\OneDrive\\Daten\\Programme\\HTM\\blenderAddOn\\__init__.py' into
 'C:\\Users\\rnova_ebav3ic\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
```

but nothing is changed in the addons folder, and the addon is not shown in in the list or in the Dialog at File > Export > gltf 2.0

Do I need to package the __init__.py file from the example? I packed it into a zip file and selected the zip file in the install dialog. Same result.

What's the correct installation process?

Thanks in advance
Rai

**Comment by julienduroure** [comment]
Hello,

You should either:
- rename the __init__.py file to example.py
- create a zip of the directory that includes __init__.py
but, you can't install __init__.py directory

Then, you have to activate the addon (checkbox)
![image](https://user-images.githubusercontent.com/1696020/187984991-731379c5-6ae7-4052-91f7-baf1cbb7c47a.png)

Then you can see the UI in glTF 2.0 exporter
![image](https://user-images.githubusercontent.com/1696020/187985162-9a7e22bb-4d96-4880-a246-aea4ee5fbf40.png)

Tagged this ticket as documentation, that need to be updated to add details about addon installation

**Comment by RaiNova** [comment]
It works - thanks a lot Julien!!!

**Comment by julienduroure** [comment]
You are welcome!
I want to keep this ticket open, to be sure not to forget to update the doc

**Comment by julienduroure** [comment]
Fixed !
