### ISSUE TITLE
glTF exporting collections excluded from view layer

### ISSUE THREAD

**Issue by lharrington13** [KhronosGroup/glTF-Blender-IO#1721]
**Describe the bug**
I upgraded to Blender 3.2.2 from 3.1.2 and found that when exporting my scene to glTF, I'm no longer able to exclude collections from the export that have the check box for Exclude From View Layer unchecked. This was possible in the previous blender version I was using. To test this I created a new blend file and added a cube to Collection and a sphere to Collections 2. I unchecked the box next to Collection 2 in the hierarchy but the sphere still exported. When uploaded to a glTF viewer, both the cube and sphere are present. I'm using the same export setting I was in the previous blender version. 

**To Reproduce**
1. Uncheck Exclude From View Layer Box within the scene collection hierarchy 
2. Go to File > Export > .glTF 2.0
3. Choose the format: glTF Separate
4. Leave all options as the default glTF settings
5. Export

**Expected behavior**
A glTF export that doesn't include objects in collections with the Exclude From View Layer box unchecked

**Screenshots**
![CheckBox](https://user-images.githubusercontent.com/79859922/188738207-c0e76184-8213-4187-bc33-0d69f65ff6de.PNG)
![ExporterOptions](https://user-images.githubusercontent.com/79859922/188738232-12ed7119-e242-437a-9c6d-7dc278ca452c.PNG)

**Version**
 - OS: Windows 10
 - Blender Version 3.2.2

**Comment by julienduroure** [comment]
Hello,
You need to use the option "limit to visible objects" to not export excluded collections:

![image](https://user-images.githubusercontent.com/1696020/188796680-100dd6c1-5e39-4dd0-9bb6-3e0e6289e510.png)

**Comment by julienduroure** [comment]
So ... Why not sharing a file that really reflects your use case?
Seems "limit to active collection" should be what you are looking for (as far as I understand)

**Comment by lharrington13** [comment]
Thanks for the input! I attached the files I've been using (they are work files so I had to wait for permission from the company although I did have to remove several objects). It's one of our character models with equipment, armature, animations, and shapekeys. Ideally I would like everything in the Main collection to be exported and the Reference Geometry collection to be excluded from that export. I make sure the setting are correct (checking limit to active collection in the export setting and unchecking the box next to the collection I don't want exported) but it's still exporting the inactive collection. 

[Stephen Export Testing.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9508158/Stephen.Export.Testing.zip)

I did discover that the Limit to Active Collection option does work in the testing files I create with blender 3.2.2 (a clean blend file I tossed a few cubes into) but not for our character model files which were created using previous versions. Any idea why this would happen? Thanks again for your help!

**Comment by marksteward** [comment]
Limit to Active Collection works if you only want to export a single collection. It doesn't work for complex projects where you might have multiple collections that shouldn't be included in the export.

Visible collections doesn't work in my case because the plugin doesn't seem to think linked collections are visible, selectable, or renderable, so currently my options are "export everything" or 4 different options that are effectively "export only local objects".
