### ISSUE TITLE
Crash on export glTF 2.0 if the animation include delta location

### ISSUE THREAD

**Issue by turing-system** [KhronosGroup/glTF-Blender-IO#1722]
**Describe the bug**
The exporter crash when attempt to export a model with animation, when the animation include delta location keyframe.

**To Reproduce**
1. File > Export > glTF 2.0
2. Ensure to export a model that have an animation with a delta location animation, and your exporting the model with animations
3. Click on "Export glTF 2.0"

**Expected behavior**
To have the model exported.

**Screenshots**
![bug export deltalocation](https://user-images.githubusercontent.com/106758490/189218322-fa5096f4-5520-43f7-a0ae-44a1e6782205.png)

**.blend file/ .gltf**
Here a simple model with animations that include a delta location animation that cause the crash [blender bug report export crash.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9530364/blender.bug.report.export.crash.zip)

**Version**
 - OS: Windows 10 (21H2 build 16044.1889)
 - Blender Version 3.3.0

**Comment by julienduroure** [comment]
Confirmed

**Comment by turing-system** [comment]
By the way : I don't know if glTF 2.0 standard include delta location animation.
I cloned the glTF-Blender-IO and (dirty) fix the key error on "addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_sampler_keyframes.py" line 377
![image](https://user-images.githubusercontent.com/106758490/189292404-29de86c9-b511-40ea-b962-76e1af8c6bb8.png)

I'm importing it on Three.js and the delta location seem to be treated as location.
But from my lack of knowledge on the subject, I don't know if it's that glTF 2.0 shouldn't have this kind of animation in first place, or if it's the Three.js importer that is just simplify " 'delta_location' ? meh, it's an absolute location animation"

**Comment by julienduroure** [comment]
glTF doesn't have delta transform concept.
adding delta_* to this dict will solve first part of the bug.
But: A second part is needed, in case both T or R or S is keyed, and corresponding delta is also keyed. This will lead to a double channel target in exported animation, so a bad glTF file.
So we also need to avoid this situation as the second step of this bug fix.

Dev in progress
