### ISSUE TITLE
Incorrect location of some exported actions

### ISSUE THREAD

**Issue by Joe-Kerr** [KhronosGroup/glTF-Blender-IO#1732]
**Describe the bug**
Please find enclosed all necessary files.

The blender file (HumanoidDefault.blend) contains a model and a couple of actions. Animations come from Mixamo and are stored separately in a blend file each. The final HumanoidDefault.blend is generated via script from the indiviudal files.

If you have a look at the exported file HumanoidDefault.glb, you will notice that the running animations ("JustSprintWithNone", "JustSprintWithRifle") - or if you use the Win10 Viewer Animation 3, Animation 4 - are displaced from the TPose by about 1 unit in the forward direction.

This does not happen in the blend file.

The issue does not occur if I export one of individual blender files. So something must go wrong within the merging process; maybe? 

If have tried the Win10 3D viewer as well as Babylon.js.

See also the python script for how I merge the animations.

**To Reproduce**
Open the attached glb file and compare TPose with any of the "*Sprint*" animations. 

**Expected behavior**
The sprint animations be in the same location as the TPose.

**.blend file/ .gltf**
[HumanoidDefault.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9591276/HumanoidDefault.zip)

**Version**
 - OS: Win10
 - Blender 3.1

**Additional context**
Coypright:
Animations by Mixamo https://mixamo.com
Model by Quaternius CC0 (https://quaternius.com/packs/ultimatemodularcharacters.html)

**Comment by julienduroure** [comment]
Hello,
Please test with current stable version 3.3
A big refactoring happen for 3.2, that solved lots of this kind of issues.

**Comment by Joe-Kerr** [comment]
Hi,

oh oops, forgot to update. 

**But no luck; same issue:**

[savedWithBlender33.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9591461/savedWithBlender33.zip)

Best wishes
Joe

**Comment by julienduroure** [comment]
Hello,
No bug here, but I think you have a misunderstanding how Blender works when switching from one action to another.
Not keyed bones (channel) are not reset, and values are kept.
Try this in Blender (not talking about exporting here, only Blender) :
- from Tpose, switch to JustDieForwardWithAny
- play the animation until this end (frame 104)
- switch to JustSprintWithNone
You can see that location Z value of mixamorig:Hips bone value is not keyed, and value is kept from previous action

You can keyed all channels of your bones if you want to avoid this.
Some discussion are in progress to reset bone values between each action at export. See https://github.com/KhronosGroup/glTF-Blender-IO/issues/1047

**Comment by Joe-Kerr** [comment]
> you have a misunderstanding how Blender works when switching from one action to another

Indeed. 

Apologies for the false bug report :(

**Comment by julienduroure** [comment]
Don't worry, this is a very common issue, you're not the first one ;-)
