### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'joints'

### ISSUE THREAD

**Issue by jitspoe** [KhronosGroup/glTF-Blender-IO#1738]
**Describe the bug**
Getting a failure to export with the message "AttributeError: 'NoneType' object has no attribute 'joints'".

Full output:
```
02:32:28 | INFO: Draco mesh compression is available, use library at C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\extern_draco.dll
02:32:29 | INFO: Starting glTF 2.0 export
02:32:29 | INFO: Extracting primitive: main_character_(makehuman)
02:32:29 | INFO: Primitives created: 1
02:32:29 | WARNING: There are more than 4 joint vertex influences.The 4 with highest weight will be used (and normalized).
02:32:29 | INFO: Extracting primitive: main_character_(makehuman).001
02:32:29 | INFO: Primitives created: 1
02:32:29 | INFO: Extracting primitive: main_character_(makehuman).004
02:32:29 | INFO: Primitives created: 1
02:32:29 | INFO: Extracting primitive: main_character_(makehuman).003
02:32:29 | INFO: Primitives created: 1
02:32:29 | INFO: Extracting primitive: main_character_(makehuman).005
02:32:29 | INFO: Primitives created: 1
02:32:29 | INFO: Extracting primitive: Cylinder
02:32:29 | INFO: Primitives created: 1
02:32:29 | INFO: Extracting primitive: Plane
02:32:29 | INFO: Primitives created: 1
02:32:29 | INFO: Extracting primitive: Cube
02:32:29 | INFO: Primitives created: 1
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 30, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 74, in __gather_scene
    vtree.add_neutral_bones()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_tree.py", line 442, in add_neutral_bones
    n.node.skin.joints.append(neutral_bone)
AttributeError: 'NoneType' object has no attribute 'joints'
```

**To Reproduce**
Open example .blend file below.  Try to export as gltf (default settings).

**Expected behavior**
The file exports. :D

**Screenshots**
![image](https://user-images.githubusercontent.com/7751182/191402369-95c6d184-c0e2-4ea6-8be2-75078fae4a60.png)

**.blend file/ .gltf**
https://github.com/godotengine/godot/files/9612467/main_character_gltf_export_fail.zip

**Version**
 - OS: Windows 10
 - Blender Version 3.3.0

**Additional context**
Not sure why this error started happening.  The only thing I did was duplicate the strap on the wrist to add a couple straps to the boot.  Nothing major.

Also, there are some linked .blend files, but they're in disabled collections so they shouldn't impact the export, but let me know if they're needed to reproduce the issue.

**Comment by jitspoe** [comment]
Ok, I'm not sure what exactly changed to cause this issue.  I reverted my changes tho the .blend file to what I THOUGHT was a working version, but I'm still getting the error.  I also tried on blender 3.2.1 for kicks and got a slightly different error (note: I might have had an updated exporter script in there, not the vanilla 3.2.1 version).

`AttributeError: 'module' object has no attribute 'ShaderNodeSeparateColor'`

Call stack is massive, so I won't paste it unless needed.

**Comment by julienduroure** [comment]
Confirmed. 
Root cause is some objects (hidden in your scene) that have armature modifier, but all weights are 0
Fix in progress


Notes About this error:
> AttributeError: 'module' object has no attribute 'ShaderNodeSeparateColor'

You can't use  master version in 3.2 Blender. As you can see in __init__ file, the minimum version of Blender needed to run the addon is 3.3 (because of changes in Blender) :

![image](https://user-images.githubusercontent.com/1696020/191412789-5e093bb1-128e-4847-8dd7-9fb434ef4f9c.png)

**Comment by jitspoe** [comment]
Thanks for looking into this so quickly!  I was able to work around it by deleting the objects I had cloned and separated.  Kind of interesting that it tries to do things with stuff in disabled collections -- don't suppose there's any early out optimizations that can be done to completely disregard that stuff?

**Comment by julienduroure** [comment]
You can use "Limit to visible objects" option at export to restrict objects export.

**Comment by jitspoe** [comment]
The objects were in a collection which was unchecked, so they don't actually export, but they still caused the error.  Since they don't export, I was wondering if there was some processing going on that didn't need to be.

**Comment by jitspoe** [comment]
Ah, I see, the disabled collections actually export, now.  I feel like that should not be the default behavior.  Also, for some reason, even if I set Godot 4 to import visible only, it still seems to import the disabled collections, though exporting directly from blender as gltf seems to not export those disabled collections.

Since collections are so frequently used for things to generate geometry, booleans, etc., exporting the disabled ones by default seems like it will have undesired results.

So the export visible option now takes into account both disabled collections (via check box) and hidden object/collections (via eye con).  Is it possible to export hidden stuff but NOT export disabled collections?
