### ISSUE TITLE
gtLF settings node disappeared

### ISSUE THREAD

**Issue by polguiu** [KhronosGroup/glTF-Blender-IO#1750]
Hi,

I'm trying to export a 3D model and I want it without specularity. When I export it has 0.5 specularity as default value. That's why i'm trying to use the gtLF settings node, to give specularity 0.0 value. The problem is that this feature doesn't exist in my node editor, so I can't add it. I have the addon turned on in my preferences, so I don't know what's going on.

![Captura de pantalla 2022-10-05 145021](https://user-images.githubusercontent.com/115086043/194066141-7230a89f-ef0c-47c4-8bad-fc895511c2ce.jpg)

**Version**
 - Windows 10
 - Blender Version 3.1.2

**Comment by julienduroure** [comment]
You have to update to Blender 3.3 version to have the glTF Material output node (and activate UI in glTF add-on preferences)

Anyway, you should not have any specular data exported in 3.1.2, because the feature was added on 3.3 version.
