### ISSUE TITLE
Export Keyframed Shapekey Animation

### ISSUE THREAD

**Issue by vin-ni** [KhronosGroup/glTF-Blender-IO#176]
Hello,
I created two different Shape Keys and set them to `non-Relative` in Blender so they play one after another. I tried to get them exported into a glb or gltf but they wouldn't appear connected. Only as usual as two morphTargetInfluencers.

My second thought was to keyframe the animation into the animationtimeline which might make them appear as `animation` in the gltf but it also doesn't work.  

In blender 2.79 the gltf exports without any issues (just without the animation) and in blender 2.8 it throws the following error:

<img width="1036" alt="bildschirmfoto 2018-12-18 um 23 22 28" src="https://user-images.githubusercontent.com/9806572/50186663-d8ee3180-031b-11e9-815a-6348d5c33e8a.png">

Here's a basic animation of a cube via two Shape Keys that produces the error:
[animationTest.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2692489/animationTest.blend.zip)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9806572/50186827-5ade5a80-031c-11e9-94e9-9a515636473a.gif)

Thanks!

**Comment by donmccurdy** [comment]
I've moved this issue to the glTF-Blender-IO repository, as we won't be adding new features in the older one.

**Comment by donmccurdy** [comment]
Here's another example, without anything eval-time related, that ideally should work but doesn't:

[CurveMod.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2976544/CurveMod.blend.zip)

It exports without error, but the shape keys all seem to be identical, and the animation only cycles between the first two of them.

![FC734BFB-DFE3-4D5D-8C84-F5992C221828-40267-000681A8B75545A7](https://user-images.githubusercontent.com/1848368/54509933-98955400-4908-11e9-9304-545f6ecdaaa7.gif)

I've created this model by applying a "Curve Modifier" to animate a cylinder along a path, exporting that animation to MDD, then importing it back in. This creates one shape key per keyframe, and an animation cycling through them. There's no reason that final result shouldn't be able to be exported to glTF, but something isn't working correctly.

**Comment by donmccurdy** [comment]
^If I select *Animation* --> *Always Sample Animations* the file above does export correctly. I don't think that should be necessary, so this is probably still a bug, but that workaround may help others.

**Comment by julienduroure** [comment]
The second case ( tube on curve modifier --> MDD) seems to export correctly. Closing this ticket.
I will open a new one for enhancement about evaluation time
