### ISSUE TITLE
zero-vidivion caused by ior = 0

### ISSUE THREAD

**Issue by khanhha** [KhronosGroup/glTF-Blender-IO#1761]
**Describe the bug**
The zero division crashing happens when ior value of material equal to zero. 
![image](https://user-images.githubusercontent.com/2276264/195482831-4e7c513e-0a09-4cf5-8ccd-74128406d2da.png)

Checking the code, it's obvious that the boundary case where ior =0 is not handled yet
![image](https://user-images.githubusercontent.com/2276264/195482993-477768d3-4c16-4e93-81e9-92de93b43c76.png)

**To Reproduce**
1. create a BSDF with IOR = 1, Specular = 0
![image](https://user-images.githubusercontent.com/2276264/195487507-b0788432-90b5-4899-9d31-7894075ef6ba.png)

2. export glb file
3. crash

**Version**
 - OS: Windows 11
 - Blender Version: 3.3

**Comment by julienduroure** [comment]
Thanks for the report.
This bug is already fixed in current master.
The fix is already on Blender 3.4 alpha, and will be backported (at an unknown date) on a future 3.3.2 version.
Thanks !
