### ISSUE TITLE
Trouble with double-sided textured mesh export

### ISSUE THREAD

**Issue by olekboshkin** [KhronosGroup/glTF-Blender-IO#1763]
Hi
I have trouble with export my mesh in gltf 2.0.
I scanned the drawing through 3DZephyr, then in blender I made backfacing with simple metallic properties, put hdrs on the world, and when exporting to glb gltf, the object is obtained without any texture. looks like the preview in solid blender mode. Is it possible to export objects with two sides to this format?

![image](https://user-images.githubusercontent.com/114691234/196008390-6a115ae9-d431-475f-9434-c2c9e7203658.png)
![image](https://user-images.githubusercontent.com/114691234/196008401-0180e0ce-c539-496d-80eb-24e1a173fb56.png)
![image](https://user-images.githubusercontent.com/114691234/196008424-8741346c-52ce-40b8-ad54-839a6b3003a3.png)
![image](https://user-images.githubusercontent.com/114691234/196008527-526b1a6d-3965-4044-80df-9814382ce44e.png)
![image](https://user-images.githubusercontent.com/114691234/196008444-66aa1ef1-d8bc-4398-916f-a3b1c51991ec.png)

Blender 3.2.1

**Comment by will-ca** [comment]
Your shader tree is way too complicated.

The GLTF format can take textures, but not arbitrary nodes.

You should basically have only a single Principled BSDF node, with your texture connected directly to it:

https://docs.blender.org/manual/en/3.3/addons/import_export/scene_gltf2.html#base-color

**Comment by olekboshkin** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1763#issuecomment-1279867761

> You should basically have only a single Principled BSDF node, with your texture connected directly to it:

so it's impossible? you can only create a mesh with a drawing on both sides and a metal texture at the same time, as I understand it?

**Comment by julienduroure** [comment]
> so it's impossible? you can only create a mesh with a drawing on both sides and a metal texture at the same time, as I understand it?

You can refer to the documentation to see what are not node tree you can setup for compatibility with glTF:
[https://docs.blender.org/manual/en/3.3/addons/import_export/scene_gltf2.html](https://docs.blender.org/manual/en/3.3/addons/import_export/scene_gltf2.html)

Your problem here is not double-sided, but the node tree that you are using to export is not compatible with glTF specification
Closing this ticket
