### ISSUE TITLE
Why does a node without animations export with animations? (by design?)

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#1764]
**Describe the bug**
A node without any animations will show animations with the same name as the node.

**To Reproduce**
1. make a nodeA and NodeB
2. Add animation to NodeB and name it NodeA (yes name the animation the same as the name of the other node)
3. export as gltf + bin and selected objects
4. export gltf
5. open gltf in notepadd++

**Expected behavior**
don't export the node without animations as a node with animations.

**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: win 10
 - Blender Version 3.3.1

**Additional context**
MSFS allows for animation names the same as node names. but does not allow two animations with the same name.
[test_Cube_3.3.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9793277/test_Cube_3.3.zip)
[untitled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9793278/untitled.zip)
![DA40CGDFQ_03_2022 10 15_19h07m42s](https://user-images.githubusercontent.com/19254353/196010794-b32f29e7-f359-4496-8cdf-0c692bf6e57b.png)
![DA40CGDFQ_02_2022 10 15_19h04m38s](https://user-images.githubusercontent.com/19254353/196010796-4e192a1b-6369-4926-a892-b7ebb59567ed.png)
![DA40CGDFQ_04_2022 10 15_19h10m44s](https://user-images.githubusercontent.com/19254353/196010820-175d4eff-99f7-4bde-9ab4-b91b35b1d21c.png)

**Comment by julienduroure** [comment]
Hello,
Some objects without any animation can be "animated", because of constraints.
Or because you selected only some children, not animated, of a parented animation.
So we need to bake all object animation, even if object is not animated.
If you want to avoid not needed animation, you can use "Optimize animation size", that should delete animation when animation is not needed.

**Comment by ronh991** [comment]
Thank you checking "Optimize a fixed my issuenimation size"
