### ISSUE TITLE
Error while trying to export from blender to glTF

### ISSUE THREAD

**Issue by asvpage** [KhronosGroup/glTF-Blender-IO#177]
Screenshot 
https://ibb.co/0rZJ7tB
https://ibb.co/DRshdtq

**Comment by donmccurdy** [comment]
This seems like the same model and error as https://github.com/KhronosGroup/glTF-Blender-IO/issues/178, right?

**Comment by donmccurdy** [comment]
Closing as duplicate.

**Comment by donmccurdy** [comment]
Closing as duplicate.
