### ISSUE TITLE
No refraction with Transmission and IOR extensions enabled

### ISSUE THREAD

**Issue by EdwHopper** [KhronosGroup/glTF-Blender-IO#1778]
Even if the exported glb contains Transmission and IOR extension through maps or changed values in the principled shader
there are no glass like refraction as users intuitively can expect. The materials will be just like a transparent plastic foil.

I discovered empirically after various trials that a Thickness value>0 in the glTF Material Output node group activates the refractive distortion effect. This works similarly to the "Refraction depth" option in EEVEE material settings, 
(Maybe the values even overlap without any conversion - that would help with preview in blender.)
The issue is that this dependence  is hard to discover and it's not mentioned in the addon documentation, in blender's manual.

This is the case for all blender versions since Transmission and IOR are supported by the exporter.

**Comment by julienduroure** [comment]
Documentation need to be updated, as the refraction is depending on KHR_material_volume extension, not not KHR_material_transmission, used to manage transparency and reflection.
When you set a non default thickness value, KHR_material_volume will be exported, and you will be able to see refraction on your viewer.
