### ISSUE TITLE
Unable to export correct camera orientation and keep original rotation in .blend scene

### ISSUE THREAD

**Issue by HarrievG** [KhronosGroup/glTF-Blender-IO#1779]
**Describe the bug**
gltf2 exporter changes camera orientation in scene.

**To Reproduce**
just export

**Expected behavior**
a functional exporter
**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: Windows
 - Blender Version 3.3.1

**Additional context**

https://user-images.githubusercontent.com/1131446/199015947-f71e14f2-4136-4b8c-a116-5a15d44db865.mp4
[char_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9901370/char_test.zip)

**Comment by julienduroure** [comment]
Hello,
Please provide the blend file you are using.
Seems, in your video, that the UI for choosing the name of exported file is not pop up.
Please try to reset your factory settings before export.

**Comment by HarrievG** [comment]
Zip updated.

The popup does show because it will not be recorded with screen record, but as you can see that i move the mouse and click.
This is also with a fresh install to 3.3.1 LTS

**Comment by HarrievG** [comment]
I restate the problem:

When exporting a .blend with camera's in it, the camera orientation will change upon exporting.
It will be wrong in the export, and wrong in the scene of the current blend file after exporting.

**Comment by HarrievG** [comment]
Is the current description precise enough?

**Comment by julienduroure** [comment]
Here is a simple test case file.
- No active action
- But a deactivated NLA track.

So at end of export, object (or camera) are at TRS of the action, not at initial TRS without action.
This will be fixed by #1780 

I didn't check yet if there is still an issue at export

**Comment by HarrievG** [comment]
Yep, that did it.
Cameras are all at their original positions after export. 
Thx for the quick fix!

**Comment by julienduroure** [comment]
Keeping this ticket open until the PR is merge into master and in Blender Repo
