### ISSUE TITLE
Export error Trackback 

### ISSUE THREAD

**Issue by asvpage** [KhronosGroup/glTF-Blender-IO#178]
If you try to export a model from blender 2.79 to glTF, you receive an error. Please tell me what the problem

screenshot
http://uploads.ru/Sv8fc.jpg

**Comment by donmccurdy** [comment]
I've transferred this issue to the new repository. We can't support all of the materials in this thread, but I do think there's a bug happening because deleting all materials and adding Principled BSDF gives an export crash.

**Comment by julienduroure** [comment]
Unfortunally ,the .blend file is no more accessible. Closing this report.
Don't hesitate to comment, and we will reopen it again, if error still occurs, and you can provide the original .blend file
