### ISSUE TITLE
"Animation channel cannot target WEIGHTS when mesh does not have morph targets." when exporting from Blender

### ISSUE THREAD

**Issue by khalleu** [KhronosGroup/glTF-Blender-IO#1785]
Hey! I'm fairly new to GitHub, please forgive me.

I posted [this](https://blender.stackexchange.com/questions/278529/unable-to-export-as-gltf-mesh-does-not-have-morph-targets?noredirect=1#comment478428_278529) thread on Stack Exchange and it was suggested that I report a bug here.

To give a rundown of the issue, my .glTF exports cause Microsoft's 3D Viewer to crash before I'm even able to view the file. I opened the file in [this](https://gltf-viewer.donmccurdy.com/) online .glTF viewer to try to pinpoint the issue, and got the error message

`Animation channel cannot target WEIGHTS when mesh does not have morph targets.`

I converted every object into a mesh and ensured that each object had at least one shape key, but the issue prevailed. Is this a bug?
You can find the project files [here](https://github.com/KhronosGroup/glTF-Blender-IO/files/9944749/project.zip).

**Comment by willstott101** [comment]
I'm also having trouble.
I don't think I can share the blender file I'm having trouble with.
But I can say that using Blender `append` from the troublesome file, of one mesh, allows me to export morph targets OK.
Exporting that same mesh from the troublesome file (and only that mesh, using `Export Selected`) the `targets` attribute on the primitive in the JSON GLTF file is missing...

**Comment by willstott101** [comment]
Ok, here is:
* A blender file exhibiting my problem
* A GLTF export from that file missing the `meshes[].primitives[].targets` key
* A fresh 3.3.1 blender file with the object I am testing with appended into it
* A GLTF export from that file with working morph targets

https://drive.google.com/drive/folders/1m1Ng4aFuSYsRCCKyqZRV5wSnaTd7fK_F?usp=share_link

I'm piggy-backing on this issue as I'm seeing a very similar symptom, I apologise if it turns out to be unrelated.

**Comment by julienduroure** [comment]
Can you please also make screenshots of options you are using at export?

**Comment by julienduroure** [comment]
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

Because of are not exporting actions library, you can use "Scene" animation option at export
