### ISSUE TITLE
Roughness automatic texture packing

### ISSUE THREAD

**Issue by HumanRobot3D** [KhronosGroup/glTF-Blender-IO#1787]
**Describe the bug**
Roughness texture is packed with other empty channels (I'm guessing Metalness and AO?) and becomes pink at export with a **drastic** increase in weight (2.7Mo from 500Ko).
If forcing JPEG texture export, the texture is still pink and still receive a big increase in weight for no reason whatsoever.
The original roughness texture is a 8 bit grayscale image.

This is bizarre because I remember making a [bug report on a similar subject](https://github.com/KhronosGroup/glTF-Blender-IO/issues/1318) explaining exactly why automatic packing is a bad idea so I don't understand why this bug/feature made it's way into 3.3 (or 3.2 because I upgraded from 3.1)? A .glb that was exported at 1Mo a few months ago is now exported at 4Mo, you can see how bad this is for the web.

So is it just me missing a new export option or are we stuck with this unwanted behavior for now?

I don't want a gltf + bin + texture export by the way, no need to suggest the "Keep Original" option, I know about it but I need the same for .glb.

Thanks!

**To Reproduce**
Add grayscale roughness texture to material, export to gltf + bin + textures and see the roughness texture increase in weight as well as becoming RGB and pink and a PNG disguised as a JPG.

**Expected behavior**
Export textures as they are originally instead of forcing a packing of roughness with other (non-existing) textures.

**Screenshots**
![image](https://user-images.githubusercontent.com/28547693/200537396-219590ac-3a6c-42a6-9b2a-7759a8573fd4.png)
![image](https://user-images.githubusercontent.com/28547693/200537647-ae29b9ff-eb76-4b33-94ac-8338609948b9.png)
![image](https://user-images.githubusercontent.com/28547693/200537751-ba4887c6-4765-4e90-b726-3e83e8cf09ce.png)
![image](https://user-images.githubusercontent.com/28547693/200537780-bd0019cb-27dc-4b89-a07a-fbc35cd54984.png)
![image](https://user-images.githubusercontent.com/28547693/200537809-43679847-9874-4028-b3dc-038815d9e998.png)
![image](https://user-images.githubusercontent.com/28547693/200537877-905ecfea-6b8f-4ef2-ad6a-15a624a9d10f.png)

**.blend file/ .gltf**

[khronos_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/9960237/khronos_test.zip)

**Version**
 - OS: W10
 - Blender Version 3.3

**Comment by julienduroure** [comment]
Confirmed.
There is an issue with image size.
- No issue on 3.2.1
- Issue on 3.3.x
- No issue on 3.2.1 with addon code from master (modulo renaming ShaderNodeSeparateRGB/ShaderNodeSeparateRGB)

--> This let me think the problem may come from a change in Blender or Blender api, somewhere between 3.2 and 3.3

**Comment by julienduroure** [comment]
I am starting a git bisect to try to identify the Blender issue

**Comment by julienduroure** [comment]
Got it:
https://developer.blender.org/T102421

**Comment by julienduroure** [comment]
Problem is solved in https://developer.blender.org/rB5f4afecbf3559a7ddcc2621d1e863a5425859404
This should be backported in 3.3.2 (that will be released sometime in december).

I will also add an option (that is added for 3.4 in bpy) to choose the jpeg quality level at export
