### ISSUE TITLE
Animation channel cannot target WEIGHTS when mesh does not have morph targets.

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1789]
Ok, here is:
* A minimal blender file exhibiting my problem (only 1 object visible in the collections tree, this is my _very old and large_ private file with pretty much everything deleted apart from a single cube obejct, that being said when I append from it I see two other objects which is suspicious in itself).
* A GLTF export from that file missing the `meshes[].primitives[].targets` key
* A fresh 3.3.1 blender file with the object I am testing with appended into it
* A GLTF export from that file with working morph targets

https://drive.google.com/drive/folders/1m1Ng4aFuSYsRCCKyqZRV5wSnaTd7fK_F?usp=share_link

I'm piggy-backing on this issue as I'm seeing a very similar symptom, I apologise if it turns out to be unrelated.

_Originally posted by @willstott101 in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1785#issuecomment-1310438237_

**Comment by julienduroure** [comment]
Let's separate your test case from the original one.

**Comment by willstott101** [comment]
Thanks, sorry for the extra admin.

**Comment by willstott101** [comment]
ah interesting... thanks for digging. Would it be feasible to check if that specific object has modifiers, and allow the export if it has none?

**Comment by julienduroure** [comment]
@willstott101 Let's first fix this, as proposed in my PR.
Your suggestion looks interesting, I will investigate in a second time

**Comment by julienduroure** [comment]
Done!
Thanks :)
