### ISSUE TITLE
Export using ``use_active_scene=True`` fails with keyword unrecognized

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/glTF-Blender-IO#1795]
**Describe the bug**
Trying to export the active scene only as a glb using the following command
```
bpy.ops.export_scene.gltf(
            filepath=finalPath,
            check_existing=False,
            export_format='GLB',
            export_cameras=True,
            export_lights=True,
            use_active_scene=True,
```

**To Reproduce**
1. Create a new py script
2. run the command above

optionally create a blend file with two scenes

**Expected behavior**
glb gets exported and contains one scene

**Version**
 - OS: win10
 - Blender Version 3.1.2

**Additional context**
```shell
Traceback (most recent call last):
  File "C:\Users\marce\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender\__init__.py", line 49, in saved
    bpy.ops.scene.export("INVOKE_DEFAULT")
  File "c:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\marce\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender\operators_components.py", line 44, in execute
    exportScene(self, fileName="scene.glb")
  File "C:\Users\marce\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blender\blender_export.py", line 62, in exportScene
    bpy.ops.export_scene.gltf(
  File "c:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "use_active_scene" unrecognized

location: c:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py:130
```

i have seen that the bool is declared here: https://github.com/KhronosGroup/glTF-Blender-IO/blob/9be538a53c374b50e109022965886f49d1eb4806/addons/io_scene_gltf2/__init__.py#L359

exporting ``use_active_collection`` kind of works but then I get a glb file with the two scenes which is not what I want here unfortunately

also noteable is that the settings is not in the export window so maybe the blender version is too old?

![image](https://user-images.githubusercontent.com/5083203/203867580-17db65df-747f-469d-a1b3-db298cf15f0e.png)

**Comment by scurest** [comment]
> so maybe the blender version is too old

Yes, you are using 3.1. If you look at that file in [blender-v3.1-release](https://github.com/KhronosGroup/glTF-Blender-IO/blob/blender-v3.1-release/addons/io_scene_gltf2/__init__.py) you see `use_active_scene` does not exist.

**Comment by julienduroure** [comment]
Hello,
Yes, as scurest said, this option was not available on 3.1.
Please use a more recent version!

**Comment by marwie** [comment]
Thank you will do

**Comment by marwie** [comment]
Works perfectly on 3.3.1 - thanks again
