### ISSUE TITLE
Exporting results in error NoneType object has no attribute 'name'

### ISSUE THREAD

**Issue by kenshinee** [KhronosGroup/glTF-Blender-IO#1797]
**Describe the bug**

**To Reproduce**
1. Click on File -> Export -> GLTF
2. Enter desired filename and click EXPORT
3. Error popped up as attached.

**Expected behavior**
GLTF file to be generated when exporting

**Screenshots**

![image](https://user-images.githubusercontent.com/863148/204241732-f7de1b8f-d9ba-4d5d-be4a-9ff17351a0d4.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - Windows 10
 - Blender 3.3

**Additional context**
Apologies. I am very new to Blender and trying to learn the application.

**Comment by julienduroure** [comment]
Hello,
As requested in the bug template, can you please share the .blend file you are trying to export?

Thanks

**Comment by kenshinee** [comment]
@julienduroure thank you. As attached.

[blender.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10103342/blender.zip)

**Comment by julienduroure** [comment]
Hello,

Some weird / missing data / invalid file.
You have a material that is not really in a good state :
![image](https://user-images.githubusercontent.com/1696020/204295455-9fd503e4-f008-4e4b-a9a0-6f54308c9614.png)

I will add check to avoid crash.
(Note that lots of your materials are not compatible with glTF and will not be exported, or are using node groups inside node tree, that is not yet taken into account)

**Comment by kenshinee** [comment]
Noted with thanks.
