### ISSUE TITLE
"Correction_*" should be name of inserted parent, not the functional node.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#18]
When exporting cameras or lights, we have to inject a `Correction_` node as discussed elsewhere (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/265, https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/113). However, I think we could make this less confusing for users by putting the prefix on the wrapper, not on the node that references the camera or light. Current behavior:

<img width="522" alt="screen shot 2018-08-23 at 7 17 07 pm" src="https://user-images.githubusercontent.com/1848368/44561445-c5361400-a709-11e8-878e-7fbe0054b570.png">

Since the user knows they've created a light named "Spot", it would be nice if searching for the node named "Spot" in the loaded model would give them a light. This makes the wrapper less awkward, I think.

**Comment by donmccurdy** [comment]
Also, I think the default direction of the light's `correction_quaternion` is backwards —

| object | front / direction |
|--|--|
| model | +Z |
| light | +Z |
| camera | -Z |

**Comment by donmccurdy** [comment]
> The Correction_ nodes "are" the corrections, as any animations still target the original Light or Camera nodes with its original name. Furthermore, theCamera or Light still do have their original name. The correction is in "between" these two elements.

I think I disagree on this — my mental model is that a node referencing a camera _is_ a camera; it cannot also be a mesh, for example. From that perspective, it's much more intuitive to users if the name they put on the camera is applied to the node that references a camera. The "correction" is the fact that we need a wrapping node around the camera at all, otherwise there would only be one node. Practically, we've had users report confusion when they call `scene.getObjectByName('MyCamera')` and the result is not a camera.

> In glTF, by default, the light points to -z. Hower, the shader uses z for calculations. 

From the `KHR_lights_punctual` spec:

> ...emit light in the direction of the local +z axis.

I'm not sure what shaders you're referring to, but I've implemented the extension (https://gltf-viewer.donmccurdy.com/) and lights are facing the opposite way as I see in Blender. 🙃

**Comment by UX3D-nopper** [comment]
Regarding the light, the specification is wrong or not written correctly, as it should not conflict e.g. with OpenGL:
`As shown, you supply a vector of four values (x, y, z, w) for the GL_POSITION parameter. If the last value, w, is zero, the corresponding light source is a directional one, and the (x, y, z) values describe its direction. This direction is transformed by the modelview matrix. By default, GL_POSITION is (0, 0, 1, 0), which defines a directional light that points along the negative z-axis.`
https://www.glprogramming.com/red/chapter05.html

In Blender, the node name and the light/camera do both have names. The name of the camera/light is exported 1:1 to glTF (see lights and cameras JSON section). Also, the node name is exported 1:1 to glTF. And the correction node name is a modification of the node name - not from the light or camera.

A node referencing a camera or light is _not_ a camera, as it also can contain a mesh and also child nodes. Blender is naming the node and the light/camera in many cases the same.

**Comment by donmccurdy** [comment]
No worries about the name, then. Let’s follow up about the light direction on the PR.
