### ISSUE TITLE
Only one NLA animation exports properly

### ISSUE THREAD

**Issue by kungfooman** [KhronosGroup/glTF-Blender-IO#180]
Hi all,

I am trying to export multiple animation clips, but it currently isn't working so far. I don't know if my `door.blend` has a wrong setup or this needs some fixes in the exporter. For better illustration I made a short video:

[![nla bug video](https://img.youtube.com/vi/fxs9Z5iIyf8/0.jpg)](https://www.youtube.com/watch?v=fxs9Z5iIyf8)

If anybody wants to test this, I uploaded `door.gltf`, `door.bin` and `door.blend` here:

https://killtube.org/downloads/khronos/

I am currently using the latest version of the exporter.

**Comment by donmccurdy** [comment]
Transferring this to the new repository, i've confirmed the bug still appears in glTF-Blender-IO.

**Comment by donmccurdy** [comment]
@UX3D-nopper I believe this should be kept with a "bug" label. It's not a regression compared to the old exporter, the problem is pre-existing, but it is a bug from an external user's perspective. I would consider "enhancements" to be feature requests instead.

**Comment by julienduroure** [comment]
This is maybe link to NLA issue #461

**Comment by donmccurdy** [comment]
Model appears to be exporting correctly now, @kungfooman could you confirm with the latest Blender 2.8?

**Comment by kungfooman** [comment]
@donmccurdy I tested door.gltf and made new animated models to test around and couldn't reproduce this issue. Thanks a lot for everyone involved. 👍
