### ISSUE TITLE
*some* textures losing color-space info on import

### ISSUE THREAD

**Issue by elfprince13** [KhronosGroup/glTF-Blender-IO#1800]
**Describe the bug**
When importing a GLTF into Blender 3.3.1, some textures show up as "Non-Color" colorspace within the Shader editor, while others are correctly preserved as sRGB. Dumping the textures from the data URIs within the GLTF and using ImageMagick's `identify` command shows that color spaces are preserved within the embedded images.

**To Reproduce**
1. File -> Import -> GLTF
2. Keep Default Settings
3. Click around with the selector tool with 3D viewport in Object mode while Shader viewport is also set to Object mode
4. Notice that some image texture nodes say the colorspace is sRGB but most say "Non-Color".
 
**Expected behavior**
The imported nodes should have the same colorspace as the stored image (in this case, all sRGB).

**Screenshots**
<img width="363" alt="Screen Shot 2022-12-01 at 2 41 18 PM" src="https://user-images.githubusercontent.com/2703145/205144861-c85a60bc-1a34-457f-a12b-224de5aa8a28.png">
<img width="373" alt="Screen Shot 2022-12-01 at 2 41 29 PM" src="https://user-images.githubusercontent.com/2703145/205144865-3baa5923-ce82-4e76-a4e8-1913b5baa046.png">
<img width="272" alt="Screen Shot 2022-12-01 at 2 41 35 PM" src="https://user-images.githubusercontent.com/2703145/205144873-efcba87c-a142-4695-8a79-ebdf52d321ea.png">

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

https://drive.google.com/file/d/1j4RjFzz6E6X-eOgFlgvLX3-DS2TWIdUF/view?usp=share_link

**Version**
 - OS: macOS Mojave 10.14.6
 - Blender Version 3.3.1

**Additional context**

**Comment by julienduroure** [comment]
Hello,
The glTF specification says what colorspace must be used for each texture type, so the colorspace of incoming texture should not have any impact on texture colorspace node value.

Seems in your example, same texture image is used for BaseColor (that is sRGB) and occlusion (that is linear).

Not sure how this is possible, but I think this case does not follow the glTF specification, as these 2 textures should not have the same colorspace.

**Comment by elfprince13** [comment]
We're not using the occlusion texture (its presence seems to be a bug introduced by `COLLADA2GLTF`). In any case there still seems to be a bug here as we have two different base color nodes that have been set with different color spaces (one sRGB, one Non-Color). Also would be a bit odd if diffuse isn't supposed to be sRGB...

**Comment by julienduroure** [comment]
> We're not using the occlusion texture

Your glb files contains some occlusion texture. You have to report a bug on COLLADA2GLTF project.

>  two different base color nodes that have been set with different color spaces (one sRGB, one Non-Color)

As explained, this is a problem on your input file. For example, your first material has 2 textures. One BaseColor (that should be sRGB), and one occlusionTexture (that should be linear). in the glTF file, these 2 textures uses the same image source. The Occlusion Texture override the colorspace of the Base Color colorspace. 
You don't have the issue for any material without occlusion texture using the same image. In that case, the BaseColor colorspace stays sRGB.

You really have to open a bug for COLLADA2GLTF, it generates weird glTF files.

**Comment by elfprince13** [comment]
There is still a problem on this end as for this screenshot in particular:
<img width="363" alt="Screen Shot 2022-12-01 at 2 41 18 PM" src="https://user-images.githubusercontent.com/2703145/205144861-c85a60bc-1a34-457f-a12b-224de5aa8a28.png">

No occlusion nodes were generated so it's not possible to discover through the UI the source of the problem.

**Comment by julienduroure** [comment]
This ticket is more than a month old, and didn't get any feedback on my last reply.
As already said, I think the input file is not fully glTF compliant.

If I miss something, please comment again with new information.
