### ISSUE TITLE
Validation Error when ORM textures is exported as jpeg

### ISSUE THREAD

**Issue by optimus007** [KhronosGroup/glTF-Blender-IO#1801]
**Describe the bug**
When i export models with ORM textures using "JPEG" mode, I'm getting a mime type error while using gltf validator .
Is this a case the validator needs to support, since ORM textures as jpeg was added later in blender ?
or is this a bug ?

![mime](https://user-images.githubusercontent.com/6885294/205983288-22b8c4f8-8f30-429e-a00a-b61824293652.png)
```
"issues": {
        "numErrors": 1,
        "numWarnings": 0,
        "numInfos": 0,
        "numHints": 0,
        "messages": [
            {
                "code": "IMAGE_MIME_TYPE_INVALID",
                "message": "Recognized image format 'image/png' does not match declared image format 'image/jpeg'.",
                "severity": 0,
                "pointer": "/images/0/bufferView"
            }
        ],
```

**To Reproduce**
1. Export model with orm textures with material>jpeg option
2. validate using https://github.khronos.org/glTF-Validator/

**Version**
 - OS: [win]
 - Blender Version [3.3]

**Comment by julienduroure** [comment]
Hello,
This bug comes from the Blender API, and is already solved. This will be included in Blender 3.3.2  / Blender 3.4 and upper.
See https://developer.blender.org/rB5f4afecbf3559a7ddcc2621d1e863a5425859404
Thanks!
