### ISSUE TITLE
glTF exporter no longer sets model in base pose from unmuted NLA channel

### ISSUE THREAD

**Issue by chris-metabi** [KhronosGroup/glTF-Blender-IO#1802]
**Describe the bug**
I'm not even 100% sure this is a bug and not desired behavior, but it is a change that is breaking my workflow so here we are.  :-) 

Problem: with ReadyPlayerMe full body human avatar models, we have imported the GLB file into blender and applied some Mixamo animations to it for character control. We would like the model to have idle, walk, run animations, and for the base pose of the model to be the first frame of its idle animation.

With Blender 3.0.1 and glTF-blender-IO plugin version 1.7.33, we can accomplish this simply by checking the "do channels contribute to result" box for the idle animation, and unchecking it for all the other anims, and then exporting. When the model is imported into our final application, in our case Mozilla Hubs, the preview of the model shows it standing in idle pose.

However, with Blender 3.3.1 and glTF-blender-IO plugin version 3.3.32, this behavior has changed. Now, whether or not we check the "do channels contribute to result" box, the resulting glb file shows up standing in a TPose when we preview it in Hubs, or bring it into the 3D world.

Just to clarify, because I myself was confused on this point until yesterday: by "base pose" I do not mean "rest pose". The rest pose for both of my output models is a TPose. However, the gltf file has rotations applied to the bones that sets them up in their default position - if all these rotations were zero then we would be standing in a TPose by default but my desired behavior is to have these rotations set up my model in the idle pose, as it used to do.

Attached is a screenshot from WinMerge, comparing the gltf output from the two versions of the exporter. On the left, you can see that the left forearm has a quaternion approximately (0,0,0.7,0.7), from the old exporter, whereas on the right, the newer exporter gives it a quaternion much closer (but not exactly equal to) (0,0,0,1).

To reproduce: Open the attached blend file in blender 3.3.1, note that the single animation has locking turned on and the "do channels contribute to result" box checked, and then export it as a glb. Bring this glb file into a viewer and observe that it is in a TPose by default.
Then, open up Blender 3.0.1 with gltf exporter version 1.7.33, do the same thing, and observe that the glb has a default pose matching the first frame of the runback animation.
 
 

**Version**
 -  We have observed the behavior in windows 10/11 environments as well as Ubuntu 22.04
 
![gltf_diff](https://user-images.githubusercontent.com/95891182/206268832-4ebc7b9d-bdb9-46b3-b7d8-a59adf1df91c.jpg)

[kiana_runback.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10179096/kiana_runback.zip)

**Comment by julienduroure** [comment]
Hello,
Starting 3.2, the exporter use the rest pose as base pose for armatures. This was a quite often requested feature. 
But you wan still use the current frame pose as base pose during export, using the "Use current Frame" option.

![image](https://user-images.githubusercontent.com/1696020/206278579-c975866c-9a78-4d48-a1ee-c5134f5d62aa.png)



With "Use Current Frame" off:

![image](https://user-images.githubusercontent.com/1696020/206278161-199d21c8-6374-43dd-ba60-a6cb7ef49ae0.png)


With "Use Current Frame" on:

![image](https://user-images.githubusercontent.com/1696020/206278349-f82b6b2f-5c79-444b-84a9-915d940040ab.png)

**Comment by chris-metabi** [comment]
Thank you for the quick response!!!
