### ISSUE TITLE
BaseColorFactor not exporting 

### ISSUE THREAD

**Issue by j-conrad** [KhronosGroup/glTF-Blender-IO#1804]
**Describe the bug**
When using the MixColor (which replaced MixRGB) node as outlined in the Blender documentation on glTF, the resulting exported mesh lacks any sort of BaseColorFactor.

**To Reproduce**

(Use the included file: [3.4Testing.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10189561/3.4Testing.zip), or:)
1. Make a material with and Image Texture node plugged into a MixColor node set to Multiply
2. Choose a bold color and raise the Factor to 1.0
3. Export the .glTF
4. Result: No baseColorFactor

**Expected behavior**
I would expect the color of the object to reflect what the MixColor node is doing.

**Screenshots**
![3point4BaseColorFactor](https://user-images.githubusercontent.com/31968496/206570515-a41605ad-ca99-4746-b4d7-a3b40a1da27c.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: Windows 11
 - Blender Version 3.4.0

**Comment by julienduroure** [comment]
Confirmed.
We missed some changes in Blender, probably this: https://developer.blender.org/rBbfa0ee13d5395fa2cf622b6808e93d0a7cd4f3ea
