### ISSUE TITLE
Possibility to export mesh animations

### ISSUE THREAD

**Issue by bayerlse** [KhronosGroup/glTF-Blender-IO#1808]
Hey there!

Is it possible to export mesh animations created via AnimateAll in blender?

Best regards, Sebi

**Comment by julienduroure** [comment]
Hello,
glTF specification can handle:
- Object TRS animations
- Bones TRS animations
- Shapekeys animations on mesh object.

I am not a user of animall addon. Can you please share an example .blend file that you wish to export?

**Comment by julienduroure** [comment]
Hello,
More than a month without any answer.
I am going to close this ticket.
Feel free to comment again if you have some information I requested, I will open the ticket again
