### ISSUE TITLE
Request for bone length to be exported

### ISSUE THREAD

**Issue by mjdave** [KhronosGroup/glTF-Blender-IO#181]
Bones have a concept of length in Blender, which currently is not exported. This is useful, particularly when trying to load another object in-game at a location relative to the end of a bone. You can parent an object to a bone in Blender, and it is rendered in Blender relative to the end of the bone. But there is no way to get it in the correct place after it has been exported without the offset along the length of the bone.

To get the data I needed in-engine I simply added the following to gltf2_generate.py at line 1913 in generate_nodes()

`node['length'] = blender_bone.length`

**Comment by donmccurdy** [comment]
I've moved this issue to the new repository as a possible future enhancement.

**Comment by setpixel** [comment]
Yes - this is a pretty important thing to visualize the bones. For now I'm just adding a bone to the end of every dangling bone.  +1 for leaf bones

**Comment by jjcasmar** [comment]
I have a fix for this issue. Im adding a new node to the nodes hierarchy for the bone tail. When an object is parented to a bone diretly, its parented to the tail node in gltf. The fix is for the old exporter (glTF-Blender-Exporter), but probably is easy to adapt.

**Comment by setpixel** [comment]
@jjcasmar could you send me a copy of your fixed exporter? I could really use leaf bone exports. Also, I will be your best friend!

**Comment by mjdave** [comment]
Hi just to follow up, I'm still requiring this, and as far as I can see there still isn't a solution in the exporter. Leaf nodes would work as a solution for me, though it feels maybe not quite the right fit for my specific use case. For now I've updated my exporter modification for 2.8 if anyone else is in need of a solution in the mean time. In gltf2_blender_gather_joints.py in gather_joint() I've added
```
extras = {
    'length' : blender_bone.length
}
```
and passed that to  gltf2_io.Node().

**Comment by mjdave** [comment]
In the latest exporter shipping with 2.8, nodes which are parented to bones are exported with the translation relative to the tail, and not the head of the bone. This is a nice solution for my use case here, so I think this bug could now be closed.
