### ISSUE TITLE
Exporting mesh with Vertex Color is broken

### ISSUE THREAD

**Issue by N-G-Neer** [KhronosGroup/glTF-Blender-IO#1815]
When exporting a mesh with Vertex Color in Blender 3.4.1 (Color Attribute, Face Corners, Color Byte), the resulting .glb file has garbled colors, as if the vertices IDs were shuffled around.

Using the exact same settings in a previous version of Blender (3.3.2 LTS here) does not produce such issues.
Exporting .glb in 3.4.1 :
![image](https://user-images.githubusercontent.com/15633807/209743612-581b0d9d-9c84-4414-bba4-0e00186794d5.png)

Exporting .glb in 3.3.2 (same exact settings) : 
![image](https://user-images.githubusercontent.com/15633807/209743744-fe77dd2b-a015-45c7-966d-9b77c527b1c8.png)

Buggy file header :
`{"generator":"Khronos glTF Blender I/O v3.4.50","version":"2.0"}`

Clean file header :
`{"generator":"Khronos glTF Blender I/O v3.3.35","version":"2.0"}`

**Comment by julienduroure** [comment]
Hello,
Thanks for the report, but this bug is already fixed in recent build.
See https://developer.blender.org/rBAd18a07f51404ff155de0c21ac1ea32e839e74d88

Thanks!
