### ISSUE TITLE
[Texture Factors] New Mix node (in 3.4) isn't exported like the old MixRGB node was.

### ISSUE THREAD

**Issue by HumanRobot3D** [KhronosGroup/glTF-Blender-IO#1816]
**Describe the bug**
Back in 3.3 (or maybe 3.2) you were able to add a MixRGB node to factor a color to any texture. It was especially useful for AO textures, you'd mix them with white to control their intensity. Since 3.4 MixRGB node became Mix node and it doesn't seem to work anymore (I'm just assuming this is due to the change to the MixRGB node but it could be unrelated). 

By the way the documentation is using the outdated MixRGB node, so this should be fixed as well. 
![image](https://user-images.githubusercontent.com/28547693/209836485-93c2be75-0177-4617-9dfe-59ca570188d6.png)

**To Reproduce**
Export the .blend I provided to .glb and open it in a threejs viewer, you'll see the AO texture is at full intensity (very dark) even though the Mix node is set to a factor of .5

**Expected behavior**
The AO texture should be exported at 50% intensity

**Screenshots**
This should work but does not:
![image](https://user-images.githubusercontent.com/28547693/209836520-ac5c4c48-8b44-4348-874e-4b26460bf3b6.png)

**.blend file/ .gltf**
[Sofa_Mood_NewYork.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10314965/Sofa_Mood_NewYork.zip)

**Version**
 - OS: Windows
 - Blender Version 3.4

**Additional context**
You can also try to Mix the basecolor with white and it still won't work (unlike what is stated by the documentation) so I'd say it's most likely something wrong with the new Mix node.

**Comment by scurest** [comment]
#1804.

Although for AO, it should switch to use a Mix Float node now instead of a Mix Color node (Color was only used because there wasn't a way to lerp floats before), with Mix Color still supported by the exporter for back compat.

**Comment by HumanRobot3D** [comment]
My bad I searched "MixRGB" in opened issues, not closed ones, rookie mistake. Glad this is taken care of already!
