### ISSUE TITLE
import KHR_materials_sheen - node link not created - ShaderNodeMix issue in blender >= 3.4?

### ISSUE THREAD

**Issue by timknip** [KhronosGroup/glTF-Blender-IO#1817]
**Describe the bug**
For some reason the node link is not created in Blender 3.4.

After some digging it seems `ShaderNodeMix` has _three_ outputs (?!).
Apparently separate outputs for 'Float', 'Vector' and 'Color'. Odd...

My guess is this is a Blender bug.

Linking to outputs[2] `mh.node_tree.links.new(sheenColor_socket, node.outputs[2])` seems to fix the issue.

See [io_scene_gltf2/blender/imp/gltf2_blender_KHR_materials_sheen.py#L60](https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/blender/imp/gltf2_blender_KHR_materials_sheen.py#L60)

Of course the same issue is at play whenever `ShaderNodeMix` is used. (sheen roughness for example).

**To Reproduce**
1. Import attached velvet.glb
2. Go to 'shading'
3. Select the object
4. Link between mix shader and velvet bdsf's inputs[0] is missing

**Expected behavior**
Link should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/48036/210598758-43d279c0-0513-4a17-9fe4-88c121c85fbe.png)
![image](https://user-images.githubusercontent.com/48036/210599598-05439d2e-6c6a-42ee-9248-5bfd16b3f949.png)

**.blend file/ .gltf**
[velvet.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10345640/velvet.zip)

**Version**
 - OS: win64 / windows 11
 - Blender Version 3.4.1

**Additional context**
As said: this is probably a bug of the newly introduced `ShaderNodeMix` in Blender 3.4 and up
Filed a bug at Blender https://developer.blender.org/T103642 (assuming it's a bug and not a feature)

**Comment by timknip** [comment]
It's a know issue [https://developer.blender.org/T103395](https://developer.blender.org/T103395)

Doesn't look like it's going to be fixed in the short term.

For reference:

| Data Type   | Output Socket index|Input Sockets indices|
|----------|:-------------:|------|
| Float |  0 | 0 factor, 2 A, 3 B |
| Vector | 1  |  0 factor, 1 non-uniform factor, 4 A, 5  |
| Color | 2 |    0 factor, 6 A, 7 B |

**Comment by julienduroure** [comment]
Yes, confirmed.
This is a know issue, that was partially fixed on glTF I/O between 3.4.0 and 3.4.1, but there are still some issues.
- When creating a node tree at import (your reported issue)
- For checking is a node is linked to active output node, at export (currently only using output[0])

**Comment by julienduroure** [comment]
This is now fixed
