### ISSUE TITLE
I have made an animation using armature and shape keys and like to export it in .glb format. At result animation of using armature exported correctly but animation of using shape keys not exporting at all. In NLA editor there are two tracks one for armature and one for body. armature animation is exporting but body animation is not exporting at all in .glb format. Thanks

### ISSUE THREAD

**Issue by Tahirkhansss** [KhronosGroup/glTF-Blender-IO#1818]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.82, 2.83, or build date]

**Additional context**

**Comment by julienduroure** [comment]
Hello,
Thanks for the report.
Please do not explain your entire problem in the title.
Also, as requested in body of template, please provide needed information (Blender version & the .blend file you are trying to export).
Without these data, I can't investigate your issue, and the problem will not be solved.

**Comment by julienduroure** [comment]
More than a month without any answer, I am going to close this ticket.
