### ISSUE TITLE
Please rename default branch from 'master' to 'main' per Khronos policy

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/glTF-Blender-IO#1824]
To repository owners: please rename the default branch of this repository from 'master' to 'main', using the [Github renaming tool](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch). This request is per policy set by the Khronos Promoters in May 2021, to follow Github community practice for respectful naming.

The Github renaming tool sets up URL redirections and retargets outstanding pull requests, so the impact on repository users is minimal. The most visible issue is that people with local repo clones will probably want to rename their clone's 'master' branch, following the popup instructions that will be seen when browsing the github repository after the change; or just delete 'master' and pull the new 'main', if it's purely a tracker with no local content.

You may wish to coordinate with @outofcontrol if you are doing auto-updates from this repository to another location, whether via push/pull mirroring or other mechanisms. The redirects setup by Github should accommodate most such uses transparently, but it's still good practice.

Based on experience with other KhronosGroup repositories which have undergone this renaming already, this is a reasonable approach:

* Agree on a date for the renaming within the Working Group or other owners of the repository, and document that date here.
  * Date can be adjusted to avoid interaction with major releases in flight.
* Provide notice to repository users outside Khronos, insofar as possible (adding a comment in the repo README with the switchover date is one way).
* Once the renaming is done, edit the new 'main' branch to replace hardwired references to 'master' with (preferably) 'default branch' or 'main'.
* Update the repo README to note the change.

If you have questions or issues about this, please raise them on Khronos internal gitlab 'khronos-general' issue 106 if possible. If not possible, you can @-tag me here.

While we will not force any WG into acting precipitously, this is our agreed policy. Please try to accommodate renaming relatively soon.

Note that this issue is automatically generated, due to the large number of KhronosGroup repositories it's being raised in.

**Comment by julienduroure** [comment]
I don't think I am admin of this repo.
Can someone ( @emackey @donmccurdy ?) either add me as admin, or find a slot with me to perform the change?

**Comment by emackey** [comment]
@julienduroure I can make the change.  Do you know how to update your local git repo after a rename like this?  I think the key command to run is `git remote set-head origin -a` to get the local repo to understand that the remote origin has been changed, then checking out the new `main` branch.

Do you want to coordinate on a particular time of day when this will happen?

**Comment by julienduroure** [comment]
@emackey Choose your time as it fit well for you. I will renaming my local branches as soon as I will see you performed it.
README should be updated too:
 - Reference to master in text
 - Add a § with date of change

I will follow the github doc for renaming local branches:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

**Comment by emackey** [comment]
OK, the rename has happened!  I updated CI and the main README in 81dc7f56ee2714.

I didn't update the *.rst manual, I know that needs to be synced between here and the blender docs repo.  Also @julienduroure I don't know if you have local python scripts for syncing between repos that need changing.  We should get that all settled before closing this issue.

**Comment by emackey** [comment]
CI Tests have passed on `main`.

**Comment by julienduroure** [comment]
Docs are now updated, here and in blender doc ([See here] https://developer.blender.org/rBM9883)
Seems we can close this issue now :)
Thanks !
Note: Not all Khronos repositories are up to date yet, so some external linked are not changed yet. Github redirects links from master to main, so when changed, links are still up.
In a few weeks, I will have a look and changes all the remaining master links
