### ISSUE TITLE
Where did compression go when exporting glb models?

### ISSUE THREAD

**Issue by inverser-pro** [KhronosGroup/glTF-Blender-IO#1826]
I currently have Blender 3.4.0 installed, which lacks the ability to compress the GLB model. Earlier versions had this feature. How can I turn it on now or where can I find it?
![2023-01-09_23-56_](https://user-images.githubusercontent.com/16818348/211618494-6ee78e51-a689-4c37-965b-4496adf1ca16.jpg)
![2023-01-09_23-56](https://user-images.githubusercontent.com/16818348/211618500-583c4d5a-0334-4399-827b-d6ffa07d116b.jpg)

**Comment by julienduroure** [comment]
Hello,
The "Geometry" tab is renamed "Data".
And then Compression is still there:

![image](https://user-images.githubusercontent.com/1696020/211742595-21be3056-7a69-402c-a668-e2fa248da00a.png)

**Comment by inverser-pro** [comment]
I used Manjaro Linux v22.0
[system-info.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/10393663/system-info.txt)
And in this version, there is no compression option in the Data drop-down list
![2023-01-11_17-53](https://user-images.githubusercontent.com/16818348/211843229-5d874fd1-d1ad-4061-84e3-b947fe33bd27.png)

**Comment by julienduroure** [comment]
Hello,

Official Blender version from https;//blender.org does have the compression option.
You probably have an ERROR if you run blender from console :

> Draco mesh compression is not available because library could not be found at ...

I suggest you to open a ticket on Manjaro assigned to the Blender packager

**Comment by inverser-pro** [comment]
When running Blender via console, I don't get any errors.
```
blender
Read prefs: /home/u/.config/blender/3.4/config/userpref.blend
```
I can also compress a GLB file with third-party resources, however, it was very convenient when this function was in it.
Thank you for your reply.
I'll try to write on the Manjaro forum, but they will most likely send me to you =))

**Comment by julienduroure** [comment]
Seems Manjaro is not using python (and all python libs) bundled with Blender, but python from system.

**Comment by inverser-pro** [comment]
Thanks.
