### ISSUE TITLE
Empty nodes exported when camera or lights are disabled

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#183]
With the camera or lights disabled, the exporter still writes empty nodes in their place:

![screen shot 2018-01-08 at 10 30 05 pm](https://user-images.githubusercontent.com/1848368/34707691-aa451356-f4c3-11e7-8115-f67c2e73b139.png)

[SmoothMorph.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1614107/SmoothMorph.zip)

Preferably these nodes would be ignored, if they have no children, so that it's possible to export simple models containing only a single node.

**Comment by donmccurdy** [comment]
Transferred to glTF-Blender-IO.

**Comment by YannKh** [comment]
Using the parameters from Python operator is also misleading as even if you use the bpy.ops.export_scene.gltf operator with "export_cameras=False" and "export_lights=False", you get these empty nodes.
