### ISSUE TITLE
When exporting vertex colors as GLTF, the imported result doesn't match the exported object

### ISSUE THREAD

**Issue by DavidArppe** [KhronosGroup/glTF-Blender-IO#1830]
**Describe the bug**
Hi, when I am exporting my model with vertex colors, it doesn't import with the same colors. I am not sure where the discrepancy is, or if it's a limitation and I should be adjusting my workflow to match the GLTF format. 

**To Reproduce**
1. Create a new scene, enable GLTF plugin
2. With the default cube, color 3 of the faces using the vertex paint view
    - Select a face in edit mode
    - Switch to vertex paint mode via the options wheel when holding ctrl+tab
    - Paint that face you've selected
3. Export as GLTF, including vertex color information in the data dropdown
4. Reimport, and notice that the vertex colors are present but, incorrect.

**Expected behavior**
I'd expect it to import as it was exported, and not switch/remove colors. To be clear, this isn't an issue with the auto-generated material and shader nodes. This is the actual vertex color data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9298898/212568615-89fdcedc-fe80-4d60-8bc9-7fa8219bfc94.png)
Here on the left is the incorrect, imported result. On the right is the original cube. A few things are strange to me: 
1) Where are the green and blue vertices? 
2) Why is the red face not on the top?

**.blend file/ .gltf**
[vertex-color-repro.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10421293/vertex-color-repro.zip)
I've attached the blender file containing the original cube and the incorrect cube. I've attached the gltf as well, which was just the original cube exported. This was imported again, and that's the second cube in the blend file.

I've even assigned the GLTF-generated material to my original cube for a direct comparison. So you just need to view materials in the viewport to see it side by side. 

**Version**
 - OS: Windows 11
 - Blender Version: 3.4.1
 - GLTF Version: v3.4.50 (default from blender, not built from source)

**Comment by scurest** [comment]
#1815

**Comment by julienduroure** [comment]
Hello,
This bug is already fixed in main branch.
Thanks!

**Comment by DavidArppe** [comment]
@julienduroure Thanks! I had a quick question, not specifically related to this issue but, the addon in general, since this vertex color issue is blocking me and my team (I've developed a GLTF extension addon for the tool).

When these changes are pushed to the official release, will that automatically be used by Blender? Does it auto-update addons? Blender and addons in general are new to me. Does Blender need to be re-installed or is there an updater for official addons?

And is there a roadmap, an estimate for when this branch will be stable? I tried installing the dev version and ran into an issue about a missing key, saying "KeyError: 'bpy_prop_collection[key]: key "io_scene_gltf2" not found'". Not sure if this is some user-install error on my end, or just an issue with 3.5.13

Thanks, in advance!

**Comment by julienduroure** [comment]
> When these changes are pushed to the official release, will that automatically be used by Blender? Does it auto-update addons? Blender and addons in general are new to me. Does Blender need to be re-installed or is there an updater for official addons?

Every fixes here are commited to Blender master branch a few minutes later. So this fix is already in Blender 3.5 alpha.
This 3.5 version will be release as stable on March 15, 2023
Any new version needs to be re-installed, there is no updater in Blender

> "KeyError: 'bpy_prop_collection[key]: key "io_scene_gltf2" not found'"
Not sure what you did, but seems you deleted the addon from Blender, and didn't install a new one.
The best way for you is to download a daily build here: https://builder.blender.org/download/daily/
These builds contains the latest version of the addon
