### ISSUE TITLE
Volume and Iridescence GLTF/GLB from glTF-Sample-Models do not display or import/export correctly 

### ISSUE THREAD

**Issue by ROBYER1** [KhronosGroup/glTF-Blender-IO#1838]
**Describe the bug**
The glTF Sample Models for [IridescentDishWithOlives ](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/IridescentDishWithOlives)and [IridescenceLamp](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/IridescenceLamp) do not display or import/export correctly in Blender 3.4.1 latest. 
In the Blender viewport in Material Preview mode the materials do not render correctly at all.

When the models are exported, they are missing their iridescence map, however this is known as  KHR_materials_iridescence isn't added to Blender yet via https://developer.blender.org/T99447

The real issue is that the materials do not look correct in the Blender viewport at all when imported into Blender, for a wysiwyg style look dev workflow it makes Blender unusable for material edits to these types of models in Blender when they render like this:
![image](https://user-images.githubusercontent.com/10745594/214363207-70db6f8c-5e63-489a-b120-fe8561c043dc.png)

**To Reproduce**
1. Open Blender 3.4.1
2. Import one of the sample models linked above

**Expected behavior**
Volume and iridescence should import and export correctly with the models via glTF

**Screenshots**
Fresh imports of the glb versions of the files above:
![blenderimport](https://user-images.githubusercontent.com/10745594/214361384-859d905f-6a4a-4c72-a13e-f02a82b3d2aa.jpg)

Left is original and right is exported from Blender as-is with default GLTF export options for GLB viewed with https://github.khronos.org/glTF-Sample-Viewer-Release/
![image](https://user-images.githubusercontent.com/10745594/214361845-f7a33728-7c7f-48ac-afb2-5d626fcc0318.png)
![image](https://user-images.githubusercontent.com/10745594/214362211-f008b713-f2e9-4719-b06f-5f9182d5e472.png)

Repro Files:
[Repro.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10492449/Repro.zip)

**Version**
 - OS: Windows 11
 - Blender Version 3.4.1

**Comment by ROBYER1** [comment]
I noticed the specular imports as infinite, reducing it fixes the bleached white colours of the bowl
![image](https://user-images.githubusercontent.com/10745594/214368789-acc42707-ac92-427d-99ed-0bd7e0126b47.png)

Then as per [here](https://blender.stackexchange.com/a/244792/89979) I enabled Screen Space Reflection and Refraction in Eevee but I also had to enable Screen Space Refraction on the materials themselves which I assume the GLTF importer should enable if those are per-material settings?

**Comment by julienduroure** [comment]
Confirmed.
There is a division by 0 because of specular. I will fix it.

Currently, there is no change of global Eevee option when importing. 
I don't think an importer should change global settings of Blender or Render Engine.

**Comment by julienduroure** [comment]
> Thickness using the Thickness map don't have an effect on anything in Eevee, is this expected?

Thickness in glTF has no equivalent value in any Eevee or Cycles node. They are not using same model for rendering. 
There is no 100% feature compatibility between Blender and glTF

**Comment by ROBYER1** [comment]
> > Thickness using the Thickness map don't have an effect on anything in Eevee, is this expected?
> 
> Thickness in glTF has no equivalent value in any Eevee or Cycles node. They are not using same model for rendering. There is no 100% feature compatibility between Blender and glTF

Understood, I am adopting Blender with a team and we are trying to establish workflows with GLTF so that is an issue for cross-software workflows.

**Comment by julienduroure** [comment]
Any glTF value/texture without any corresponding Blender data are plugged to the "glTF Material Output".
So at export, these data/texture can be exported, even if not displayed in Blender.
