### ISSUE TITLE
Blender 3.4: vertex colors look wrong after export (shuffled?)

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/glTF-Blender-IO#1841]
**Describe the bug**
Object with vertex colors does look correct in blender but colors are wrong in exported glb
It also seems like much more information is exported than is actually in the scene

**To Reproduce**
1. Open attached blend file
2. open in blender 3.4
3. export to glb
4. open in glb viewer: https://github.khronos.org/glTF-Sample-Viewer-Release/
5. see mixed colors

**Expected behavior**
exported glb looks like in blender

**Screenshots**
Blender
![image](https://user-images.githubusercontent.com/5083203/214711893-be9a31bc-5483-491f-a79a-3eac08180dac.png)

Exported, khronos viewer https://github.khronos.org/glTF-Sample-Viewer-Release/
![image](https://user-images.githubusercontent.com/5083203/214711940-3e668caa-c626-4d65-b9c0-6daea2621eae.png)

**.blend file/ .gltf**
[Needle.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10504497/Needle.zip)

**Version**
 - OS win 10
 - Blender Version 3.4.1

**Additional context**
- export works fine in 3.3
- it also seems like the exported glb does contain more info than it must - ive previously had a scene with more objects, deleted everything except the cactus and exported, opened in khronos viewer and saw more objects that were i9n the blender outliner and scene view. I then purged unused data after which only the cactus was left in the exported glb (attached)

**Comment by scurest** [comment]
#1815

**Comment by marwie** [comment]
thanks @scurest, here some more info, not sure if its related

this is what the khrones viewer showed when i only saw the big cactus in the blender scene view

![image](https://user-images.githubusercontent.com/5083203/214716873-99ffbde4-e760-44c9-b449-c45800d903d9.png)

here is the full scene
[scene.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10504618/scene.zip)

- imported into blender
- deleted objects in scene view except cactus, camera and directional light
- exported to glb
- produced screenshot above

**Comment by julienduroure** [comment]
Confirmed this is already solved in main branch.
This is available in Blender 3.5 (current alpha, will be beta next week)

**Comment by marwie** [comment]
Ok great! Thanks
