### ISSUE TITLE
Texture transforms fail to export with UV map modes and empty material slots

### ISSUE THREAD

**Issue by keianhzo** [KhronosGroup/glTF-Blender-IO#1846]
**Describe the bug**
Texture transforms fail to export if a material uses a uv_map node and there is an object with an empty material slot.

**To Reproduce**
1. Add and object with a material that has a texture with that has a uv_map node as vector input
2. Add a second object that has an empty material slot
3. Export the scene

**Expected behavior**
The scene should export correctly even if an object's has an empty material slot.

**Screenshots**
![Screenshot 2023-01-30 at 12 25 05](https://user-images.githubusercontent.com/837184/215465832-9d1724d5-00ae-48ee-83a4-f4ab43b42e86.png)
![Screenshot 2023-01-30 at 12 24 51](https://user-images.githubusercontent.com/837184/215465843-33dc0ddf-4c81-4839-80d9-748bea251279.png)

**.blend file/ .gltf**
[issue.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10535328/issue.blend.zip)

**Version**
 - OS: MacOS
 - Blender Version 3.4.1

**Additional context**
The culprit seems to be:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/03b62dc63139af85c9004fa3c305dd8e91d650ef/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py#L183
We are assuming that there is always a material in the slot.

**Comment by julienduroure** [comment]
Confirmed
