### ISSUE TITLE
Undesired edge splitting and re-ordering.

### ISSUE THREAD

**Issue by xb-nico** [KhronosGroup/glTF-Blender-IO#1849]
**Describe the bug**

Meshes exported to GLTF with Blender do not preserve index buffer ordering, and split some edges in undesirable ways.

**To Reproduce**
1. Open attached .blend file
2. Note that the plane model is fully triangulated, and all edges are connected.
3. Export model to .gltf
4. Import .gltf model
5. Imported model now has many split edges (try selecting and dragging several vertices until you find a disconnected edge).

**Expected behavior**
A pre-triangulated model, without UVs or discontinuous normals, should not change mesh connectivity on export/import to GLTF, and preferably should not change index buffer ordering either, or at least gate this behind an option.

**Screenshots**
Before export to .gltf:
![image](https://user-images.githubusercontent.com/98130284/215619987-face7984-9309-4e26-933a-bcc20e1dce72.png)

After export + re-import:
![image](https://user-images.githubusercontent.com/98130284/215619842-198f3484-c401-41fd-bbc4-abe1a17de7a1.png)

**.blend file/ .gltf**
[edge_split_repro.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10540863/edge_split_repro.zip)

**Version**
 - OS: Windows 11
 - Blender Version: Blender 3.4.1
 
**Additional context**
Note that this model is intentionally chopped into strange triangles as I wasn't sure of the topology that would cause this export issue. This is affecting me in a non-trivial model which I am unable to share here.

**Comment by xb-nico** [comment]
Update:

It appears this happens only when exporting with Normals included. I suspect blender is generating discontinuous normals, and the exporter is splitting on them. Not sure if this is desired behaviour, but I should be able to work around it for now by not exporting normals (my use case does not include or require them).

**Comment by scurest** [comment]
The reason the corners get split is the normals; there are tiny differences even when two corners "should" have the same normal.

```py
>>> D.meshes['Plane'].calc_normals_split()
>>> set(tuple(l.normal) for l in D.meshes['Plane'].loops)
{(0.0, 0.0, 0.9999999403953552), (0.0, 0.0, 1.0)}
```

Note that [the low digits vary even between platforms](https://developer.blender.org/rB6dd89afa966042f8ae402c848655ac0dc0d795fe) so you may get different results on your computer.

It's been [said before](https://github.com/KhronosGroup/glTF-Blender-IO/issues/1474) that normals should be rounded off when exporting.

As for the order of indices, IIRC I never even thought about it so I'm not surprised it isn't preserved.

**Comment by xb-nico** [comment]
Thanks! I believe the index ordering is preserved when normals are disabled, and this suits my purposes fine. 

It would be nice if it's possible to ensure that behaviour is preserved going forward, as I have some use cases that depend on it. It might also be useful to have a mode that merges split normals on export, but I don't personally require that.

Thanks for the help,
Nico.

**Comment by julienduroure** [comment]
Rounding at 6 digits seems to solve the issue. See #1851

**Comment by scurest** [comment]
The OBJ exporter uses four digits, see [link](https://developer.blender.org/rB6dd89afa966042f8ae402c848655ac0dc0d795fe) above.

**Comment by julienduroure** [comment]
Ok, let's keep the exporter consistant, let's set it to 4 on glTF too

**Comment by donmccurdy** [comment]
Perhaps this is something we could mention briefly in the manual as well? Some workflows will depend on being able to reliably export vertices in a particular order and without changing the count. For example, exporting to glTF and storing additional per-vertex animation data in an MDD file or texture. Disabling normals may fix the issue sometimes, but would something like `Mesh → Split → Faces & Edges by Vertices` be a more reliable workflow?

**Comment by xb-nico** [comment]
@donmccurdy good thought, in my case (for various reasons) I specifically need un-split triangles. So my ideal use would probably be the opposite, to merge all discontinuous normals (but don't merge vertices just by position, leave them split if they were in the input).

**Comment by scurest** [comment]
If you want the original vertex/poly indices from Blender, it will be way less fragile to store them on attributes. Then it doesn't matter what reordering or splitting occurs, you can always reconstruct original data afterward. This geo node setup would work (export with "Apply Modifiers" and "Attributes" on)

![geo](https://user-images.githubusercontent.com/11024420/217341445-e5004f40-566d-43f0-ab20-ed76f884a8c4.png)

**Comment by xb-nico** [comment]
That's an interesting idea, but certainly additional overhead over my use case. 

My (naive) expectation is that if I go from gltf -> blender -> gltf, I should end up with the same gltf (maybe there's some slight precision changes or something, but the ability to edit geometry without changing connectivity seems pretty important to me).

I have a non-traditional use case that I can't go in to too much detail on, but I imagine lots of game content has similar requirements where a simple modification is required to a model that's already in gltf format, and you don't want to invalidate any surrounding content.

To be clear I've got my use case fulfilled already just by disabling the normals, just want to give some context for my thinking on it.

**Comment by scurest** [comment]
> My (naive) expectation is that if I go from gltf -> blender -> gltf, I should end up with the same gltf

That is certainly impossible in general, for many reasons.

**Comment by xb-nico** [comment]
That's fair. I should be more clear also, I don't expect it to be bit-identical, or have the same headers or anything, but I would hope to keep the same mesh structures and instancing as the source gltf.

**Comment by scurest** [comment]
Neither of those is preserved. For example, whether vertices were shared between prims or not has no result on the import, so it can't be preserved. For instances, Blender has no notion of multiple instances of a mesh with different morph target weights, so instances which might have different weights are split up. Materials are also split up depending on if they need to used on a mesh with vertex colors or not. Etc etc.

**Comment by xb-nico** [comment]
I see, thanks for clarifying. I guess in my limited case it works fine, but I understand how it can't be guaranteed in general. 

Thanks again for all the help!
Nico.
