### ISSUE TITLE
Emissive factor missing?

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#185]
I downloaded this car model:  https://sketchfab.com/models/885d9f60b3a9429bb4077cfac5653cf9

After import/export trip through Blender, the emissive channel is not active.  Turns out that the exporter wrote an `emissiveTexture` but not an `emissiveFactor`.  The default `emissiveFactor` is `[0, 0, 0]` so as not to blast all models to full white.  But without the `emissiveFactor` being set, the `emissiveTexture` is multiplied by zero and has no effect.

(Also looks like blending may have been lost from the car windows, that's separate...)

**Comment by Cyp** [comment]
It looks to me as if it's assuming `[1, 1, 1]` is the default `emissiveFactor` here: https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/blender/imp/gltf2_blender_map_emissive.py#L43 I'd guess that the other `[1, 1, 1]`'s in that file are ok.

But that's in the importer, not the exporter, so I'm not sure that it's related to this bug.

**Comment by emackey** [comment]
I looked more closely at what was imported from this model into Blender.  The emissive map does appear to be hooked up correctly, and works in Eevee and Cycles.  I still need to dig into the code a bit more before I understand what that particular line is for.  But I'm pretty sure this issue is an export issue, since Blender has the right nodes for emission.

**Comment by julienduroure** [comment]
Regarding importer part, it may be a bug (have to have a deeper look on it). If I correctly understand the specification, having an emissiveTexture without any emissiveFactor is the same as having no emissiveTexture, because it will be multiply by [0.0,0.0,0.0] ?

**Comment by emackey** [comment]
> If I correctly understand the specification, having an emissiveTexture without any emissiveFactor is the same as having no emissiveTexture, because it will be multiply by [0.0, 0.0, 0.0] ?

Yes, that is a correct understanding of the glTF spec.

In this case, the original Sketchfab glTF does have the correct emissiveFactor, but the Blender exporter keeps only the texture and loses the factor, resulting in the situation described above.
