### ISSUE TITLE
glTF textures are incorrect after export

### ISSUE THREAD

**Issue by Bobenheim** [KhronosGroup/glTF-Blender-IO#1850]
Greetings,

I've been trying to export glTF following this guide:
https://www.youtube.com/watch?v=70LRKp54zIc

and this manual:
https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#example

I've tried many different settings, but always end up with the same result, having the textures displayed incorrectly.
This is the view in Blender:
![image](https://user-images.githubusercontent.com/109952699/216000821-1346f8d3-06ba-4f0b-a93a-b9f7c2cb53b5.png)

This is what I get after export:
![image](https://user-images.githubusercontent.com/109952699/216000973-54c4ffb8-da7e-4658-9993-855dcc2d1cc7.png)

Does anyone have idea what could be causing this?

**Comment by julienduroure** [comment]
Hello,

Currently, plug in a color socket ( from roughness texture) into a float socket (roughness input of Principled BSDF) is not taken into account.
You have to use separate node, to keep only green channel, as in documentation linked you mentioned.

![image](https://user-images.githubusercontent.com/1696020/216039527-814188e0-6d39-4c6b-b9c4-ea77ec8caad0.png)

It may be, in the future, be able to use directly image texture to flat socket, as it was in the video. See #1726 
(Not sure if this was OK at the time of the video ?)

**Comment by Bobenheim** [comment]
Hi,

thank you for your quick reply.

I've unfortunately already tried that, I've set it up like that on the "Brick" textures.
![image](https://user-images.githubusercontent.com/109952699/216055107-5a31ad32-289b-40fe-a852-9e7f8b1af4c6.png)

I am thinking if there may be any problem with the meshes, as the "grass" and "dirt" are displayed correctly, but the walls and roof are not.
This is how are the walls/roof made:
![image](https://user-images.githubusercontent.com/109952699/216056140-c92e6833-e38e-4570-840d-b61a244605ee.png)

"grass" and "dirt" are a single cube.

**Comment by julienduroure** [comment]
Hello,
Are you sure that normals are not inverted on your mesh?
I can't investigate without your blend file.
Please upload it.

**Comment by Bobenheim** [comment]
Hi,
sorry for not uploading it sooner:
https://drive.google.com/file/d/1Esf5lcPaJogW28_qxHtDMxtdd2Zw5x9e/view?usp=share_link

**Comment by julienduroure** [comment]
Hello,
Your file is 160 Mo, and does not contain the textures needed for reproducing the issue.
Can you please create a simple .blend file with only the needed mesh and the needed textures?
Don't forget to either pack the texture, or add them to a zip
Thanks!

**Comment by Bobenheim** [comment]
I am quite new to blender, sorry for the misunderstanding. Here's a link to a file with only needed meshes and with packed textures:
https://drive.google.com/file/d/1MWlEQ1nduTCfC98XhFZ1gE4MIshtsacu/view?usp=share_link

**Comment by julienduroure** [comment]
Exporting your file, and reimporting it in Blender does look right( even if we have lots of Z fight because of meshes on the same location)

I don't know what is Online 3D Viewer, but seems it is maybe the viewer that does not handle the glb correctly.

![image](https://user-images.githubusercontent.com/1696020/216070581-c5b13f3b-045a-4cb5-a907-13eb487a717c.png)

**Comment by julienduroure** [comment]
Some more input:
Seems this is KO on https://gltf-viewer.donmccurdy.com/ (importing only 4 meshes)

![image](https://user-images.githubusercontent.com/1696020/216075822-8feedb79-1f1b-44b8-87a8-4a0b01b33987.png)


can be seen in logs:

> WARNING: Skipping exporting texture transform because it had non-zero rotations in the X/Y direction; only a Z rotation can be exported!

> WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image

**Comment by julienduroure** [comment]
Seems the wrong UVMap is used somewhere. Investigation in progress

**Comment by julienduroure** [comment]
Ok, seems https://gltf-viewer.donmccurdy.com/ does not read the right UVMap @donmccurdy 
https://sandbox.babylonjs.com/ does read the right one

Here is a simple file to replicate.
[issue_uvmap.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10558589/issue_uvmap.blend.zip)



![image](https://user-images.githubusercontent.com/1696020/216086549-cd6bd383-d278-4427-a15f-fc58b79099e9.png)

So, for your file, you should delete other UVMaps, it should solve the issue (keep only the active one 'automap')
![image](https://user-images.githubusercontent.com/1696020/216087414-0c6ef4b0-c386-41f2-88e0-b6253aabdae2.png)

**Comment by Bobenheim** [comment]
Thank you so much! This has been bugging me for so long. Finally it works! Thank you again for your time, really appreciate it.

**Comment by donmccurdy** [comment]
three.js has a limitation here —

- the 2nd UV set is used for occlusion (AO) textures
- the 1st UV set is used for all other textures

any viewer built on three.js will likely share that limitation. It's something we'd like to fix, but if you're targeting three.js viewers or applications now, it's best to set the UVs up that way when exporting to glTF.
