### ISSUE TITLE
Triangle strips export option

### ISSUE THREAD

**Issue by SeleDreams** [KhronosGroup/glTF-Blender-IO#1854]
**Is your feature request related to a problem? Please describe.**
I am making a game engine for developping homebrews for older consoles which often run on fixed pipelines (dreamcast, psp, 3ds etc).
In those cases, triangle strips allow a huge boost in speed, triangle strips are also part of the gltf specification. However it doesn't seem like the blender addon has the ability to export with this setting.

for instance the PVR gpu of the dreamcast only natively supports triangle strips, which means normal triangles create big performance issues

**Describe the solution you'd like**
Adding an option to export the model as triangle strips.

**Describe alternatives you've considered**
I looked into other assimp and other ressources but i don't really see any option for this use case

**Comment by scurest** [comment]
I don't think this belongs in the Blender exporter. Calculating good strips is a hard problem that doesn't really have anything to do with Blender (and it would be horribly slow in Python anyway). If you need triangle strips it makes more sense to calculate them on your side.

**Comment by donmccurdy** [comment]
While glTF supports triangle strips, it disallows the primitive restart values that would probably be necessary for using triangle strips effectively. That could be enabled, but doesn't seem to be a priority on modern hardware. So I think this is probably best left as a post-optimization outside of Blender as well.

See:

- https://github.com/KhronosGroup/glTF/issues/1142

**Comment by julienduroure** [comment]
Hello,
As describe, this feature will unlikely happen in Blender.
If you really need it in your pipeline, it will better fit in a post-optimization step.
Closing this ticket
