### ISSUE TITLE
Animation cilp changes after exporting

### ISSUE THREAD

**Issue by xubury** [KhronosGroup/glTF-Blender-IO#1855]
Hi, I am developing my gltf parser but I ran into some problems about animations.
My program can't play some gltfs animation correctly .
However, it plays correctly after I import the gltf and export back to gltf using blender.

After debugging a little, I found some frames' translations have changed after exporting.
For example in the attached file:[low-poly_character.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10578493/low-poly_character.zip)
The first three frame of a node named `mixamorig:RightFoot_062`'s translation has change from
```
(1.0265402e-05, 3923.1528, -6.2052213e-06)
(1.0265402e-05, 3923.1528, -6.2052213e-06)
(1.0265403e-05, 3923.1528, -6.2052213e-06)
```
to
```
(0.19024743, 3923.1577, 0.06728477)
(0.19027266, 3923.1575, 0.067232735)
(0.19030312, 3923.1584, 0.067215264)

```
Heres' my questions:
Why does this gltf's animation changed after exporting from blender?
Why does the animation works correctly only after I exported it?
Did I not load the animation sampler correctly or is there something wrong with the original file that I need pay attention to?

Here's my code snippet for reading the translation data in case someone needed.
```
    template <typename T>
    T getBufferData(Index accessorIdx, size_t element = 0) const
    {
        const GLTF::Accessor &accessor = Accessors[accessorIdx];
        BD_ASSERT(element < accessor.Count);
        const GLTF::BufferView &bufferView = BufferViews[accessor.BufferView];
        const GLTF::Buffer &buffer = Buffers[bufferView.Buffer];
        size_t stride = math::max<size_t>(bufferView.Stride, sizeof(T));
        const char *ptr = buffer.Data.data() + bufferView.Offset + accessor.Offset;
        return *(T *)(ptr + element * stride);
    }

```

**Comment by xubury** [comment]
Here's a more complete debug info  of the node named `mixamorig:RightFoot_062`
original:
```
pos:(1.0265402e-05, 3923.1528, -6.2052213e-06)
pos:(1.0265402e-05, 3923.1528, -6.2052213e-06)
pos:(1.0265403e-05, 3923.1528, -6.2052213e-06)
rot:(0.852193, 0.5218879, 0.03671618, -0.007217273)
rot:(0.85310113, 0.5203972, 0.036796004, -0.0071592517)
rot:(0.8540047, 0.51891154, 0.036800355, -0.007246166)
```
exported:
```
pos:(0.19024743, 3923.1577, 0.06728477)
pos:(0.19027266, 3923.1575, 0.067232735)
pos:(0.19030312, 3923.1584, 0.067215264)
rot:(0.8520978, 0.52204347, 0.036704946, -0.007262041)
rot:(0.85323244, 0.5201817, 0.03678597, -0.0072257575)
rot:(0.85432506, 0.51838535, 0.036752265, -0.0074049723)
scale:(0.9999999, 0.9999998, 0.99999994)
scale:(0.9999999, 0.99999994, 0.99999994)
scale:(0.99999994, 0.99999994, 0.9999998)
```
Much appreciated for any helps!

**Comment by julienduroure** [comment]
Hello,
Some inputs to help you find your problem on your parser:

- Seems the original glTF has some errors, regarding the glTF validator : https://github.khronos.org/glTF-Validator/

> Why does this gltf's animation changed after exporting from blender?

- glTF joint & Blender bones are not exactly the same way of working. Than means, depending on your case, you have an option at import named "Bone dir", hat can convert data for joints. Exporter then exports Blender data. This may lead to differences for rest post / animation. Blender is not a glTF editor : We try as much as possible to not convert / change data. But sometimes this is not possible / not simple. 

> Why does the animation works correctly only after I exported it?
Did I not load the animation sampler correctly or is there something wrong with the original file that I need pay attention to?

I don't know. Seems Blender and https://sandbox.babylonjs.com/ are able to read it.
Unfortunately, https://gltf-viewer.donmccurdy.com/ still have the issue about camera that prevent to see the animation correctly. But as far as we can see, the animation is imported

**Comment by xubury** [comment]
Thanks for you detailed explaination! I managed to solve it. 
Turns out that my program has some bugs handling animated nodes that don't have all of the `TRS` channel.
And blender exported gltf fill the blank for me!
