### ISSUE TITLE
Vertex Color Export not working with 3.4

### ISSUE THREAD

**Issue by LorenzWieseke** [KhronosGroup/glTF-Blender-IO#1856]
I figured that exporting does work with 3.3 without any problem but gives weird results with 3.4

[Wrong_Vertex_Color.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10579214/Wrong_Vertex_Color.zip)

**Comment by julienduroure** [comment]
Hello,
Thanks for the report, but this bug is already known and fixed in main.
See #1815 #1841 
The fix will be in Blender 3.5, that will enter into Beta mid-february
