### ISSUE TITLE
Convert SpecGloass to MetalRough at import?

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#1857]
Would it make sense to perform a crude conversion of SpecGloss to MetalRough and import that instead? 
The tradeoff would be it wouldn't look as accurate inside Blender, but it would export the same way it imported, and we could get rid of all the poorly exercised code in gltf2_blender_KHR_materials_pbrSpecularGlossiness.py.

For example

```py
# Preserves only the diffuse and a constant glossiness
def specgloss_to_metalrough(specgloss):
    metalrough = {}

    metalrough["baseColorFactor"] = specgloss.get("diffuseFactor")
    metalrough["baseColorTexture"] = specgloss.get("diffuseTexture")

    if "specularGlossinessTexture" not in specgloss:
        glossiness = specgloss.get("glossinessFactor")
        metalrough["roughnessFactor"] = 1 - glossiness
    
    metalrough["extras"] = specgloss.get("extras")
    metalrough["extensions"] = specgloss.get("extensions")

    return metalrough
```

![new](https://user-images.githubusercontent.com/11024420/216659253-3ffd43a3-eb5e-42f8-9c64-6854c873739e.jpg)

_Originally posted by @scurest in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1853#issuecomment-1416127718_

**Comment by julienduroure** [comment]
Maybe we can add an option that let's choose if we want to 
- import native specGloss (accurate, but no roundtrip is possible)
- import converted specGloss (less accurate, but export a better way)

**Comment by scurest** [comment]
That would make the importer more complicated instead of more simple though.

**Comment by julienduroure** [comment]
Let's start pros/cons to help decide

Pros: 
- More simple importer

Con:
- Automatically convert (that will be not perfect) can be seen like a regression for people that want to see in Blender files with KHR_materials_pbrSpecularGlossiness.

**Comment by scurest** [comment]
Another way to think about it: replacing pbrSpecularGlossiness with a crude approximation is a slightly gentler way of dropping support for it. So in the first place, do you want to drop support?

**Comment by julienduroure** [comment]
> So in the first place, do you want to drop support?

I will ask the Khronos TSG working group members what is their point of view about dropping it or not

> this basically just replaces the Diffuse node in the current graph with the equivalent Principled node

Quite an interesting idea :)

**Comment by donmccurdy** [comment]
Won't it be possible to do a lossless conversion to metal/rough, with Principled BSDF v2? This would require altering input textures if we want the model to export correctly. But if that's an outcome we're happy with, maybe there's no need to reduce support between now and then.

**Comment by scurest** [comment]
Isn't it possible to do a lossless conversion with KHR_materials_specular now? It's all a question of how much effort you want to spend on it.

**Comment by donmccurdy** [comment]
Yes, it's just that we need the glTF Material Output node for KHR_materials_specular now, which doesn't render.

**Comment by julienduroure** [comment]
Hello,
Regarding this: https://devtalk.blender.org/t/2023-04-04-render-cycles-meeting/28766
Blender 3.6 should have Principled v1 and Principled v2
And Blender 4.0 will have only Principled v2

**Comment by julienduroure** [comment]
The new Principled v2 (including new specular model) is now in 4.0 beta.
We will now be able to convert SpecGloss to specular, and display it in Blender. No more glTF Material Output required
