### ISSUE TITLE
Round-trip import/export of model loses some Specular/Glossiness and Thickness textures/slots on export

### ISSUE THREAD

**Issue by ROBYER1** [KhronosGroup/glTF-Blender-IO#1858]
**Describe the bug**
This model was originally made in and exported from Blender, looks correct in all three.js model viewers we use. Once that same model is reimported into Blender either via a GLTF+Separate or GLB file and exported again, it loses the Specular texture and Thickness texture.

**To Reproduce**
1. Import the sample .GLB file from below into Blender
2. Open File > Export > glTF 2.0 and ensure Data > Material > PBR Extensions is set to Export original PBR Specular
3. Export the file to a new glb file
4. compare the two files in a viewer like here (https://gltf.report/) to see that the new export is missing these textures from material slots:
 -Thickness slot - light_v1_UV_3_light_glass_Thickness
 - Specular slot - light_v1_UV_3_light_glass_AlbedoTransparency

**Expected behavior**
Round-trip exported/imported then re-exported file should retain its maps and properties.

**Screenshots**
![image](https://user-images.githubusercontent.com/10745594/216958360-92e9b1b9-119d-44f3-8a35-c3085f192c9c.png)
![Missingmaps](https://user-images.githubusercontent.com/10745594/216958371-80a8d053-d041-438f-9c36-fea8aa4c1740.jpg)

**.blend file/ .gltf**
https://drive.google.com/file/d/1f1OdI2iXZeAgyZTloNuInDJ3KOO3WT7_/view?usp=share_link

**Version**
OS: Windows 11
Blender Version 3.4.1

**Comment by julienduroure** [comment]
More than a month without answer.
Closing this ticket.
Feel free to open a new one if you still have issue with 3.5
