### ISSUE TITLE
Option to export textures as they are.

### ISSUE THREAD

**Issue by skrichten** [KhronosGroup/glTF-Blender-IO#1859]
**Is your feature request related to a problem? Please describe.**
I import some nice optimized .webp textures into blender, but when I export I can only choose "jpg" or "automatic".  Both options lead to less optimized textures and a much larger file size.

**Describe the solution you'd like**
There should be an option to export the textures exactly as they are currently on disk.

**Comment by julienduroure** [comment]
Hello,
Webp is not allowed in core glTF specification, but is available via an extension. (  https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_texture_webp/README.md )
This extension is not implemented in Blender glTF I/O yet.
Mark as duplicated, as this request is already in various tickets ( #1308 )

**Comment by scurest** [comment]
This is different than #1308.

* #1308 asks for a new mode that converts images to WebP.
* This asks for "Automatic" to export WebP images as they are, the same way it exports PNG/JPEG as they are.
