### ISSUE TITLE
 I cant do export "GLTF 2.0" Blender 2.8 alpha

### ISSUE THREAD

**Issue by kone9** [KhronosGroup/glTF-Blender-IO#186]
I cant do export "GLTF 2.0" Blender 2.8 alpha

![2018-12-20 10_30_02-blender_ f__proyectos blender3d_gaucho_noel_papanuel_y_carruaje blend](https://user-images.githubusercontent.com/12847027/50287685-45635080-0442-11e9-928a-5b9f6ebcbbaf.png)
![2018-12-19 14_09_52-blender_ f__proyectos blender3d_gaucho_noel_papanuel_y_carruaje blend](https://user-images.githubusercontent.com/12847027/50287657-29f84580-0442-11e9-8ef4-dce115d968d0.png)
![2018-12-20 10_28_58-blender_ f__proyectos blender3d_gaucho_noel_papanuel_y_carruaje blend](https://user-images.githubusercontent.com/12847027/50287662-2ebcf980-0442-11e9-88fc-99e21e84b185.png)
![2018-12-20 10_29_20-blender_ f__proyectos blender3d_gaucho_noel_papanuel_y_carruaje blend](https://user-images.githubusercontent.com/12847027/50287665-32508080-0442-11e9-8f28-3c80e36355a2.png)

**Comment by julienduroure** [comment]
Please provide the .blend you are trying to export.

**Comment by julienduroure** [comment]
And please test it with a more recent build of blender, in order to know if problem is still there.

**Comment by kone9** [comment]
Here is the model, now I download the latest version of Blender3D and upload a video to youtube showing you the error.
![2018-12-20 12_37_28-greenshot](https://user-images.githubusercontent.com/12847027/50294146-0c33dc00-0454-11e9-87ed-6e907cd39950.png)


[papanuel_y_carruaje.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2699443/papanuel_y_carruaje.zip)
