### ISSUE TITLE
Python error when exporting in gltf2_blender_export.save()

### ISSUE THREAD

**Issue by jitspoe** [KhronosGroup/glTF-Blender-IO#1861]
**Describe the bug**
Trying to export and I get this error:
![image](https://user-images.githubusercontent.com/7751182/217426144-09c48558-cc3a-46b4-816a-3f40e1b3d15a.png)

**To Reproduce**
Open attached .blend file in blender 3.4.1.  Attempt to export to gltf with default settings.

**Expected behavior**
Export works.

**Screenshots**
![image](https://user-images.githubusercontent.com/7751182/217426144-09c48558-cc3a-46b4-816a-3f40e1b3d15a.png)

**.blend file/ .gltf**
[main_character.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10681460/main_character.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 3.4.1

**Comment by julienduroure** [comment]
Confirmed.
Name collision when an armature object is parented to a bone
