### ISSUE TITLE
Faces are imported incorrectly.

### ISSUE THREAD

**Issue by Woitek1993** [KhronosGroup/glTF-Blender-IO#1865]
For some reason for some of my objects, gltf can’t load the correct amount of the indices. In case of this file it loads only half of them. 
[drinkcup.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10700827/drinkcup.zip)
![image](https://user-images.githubusercontent.com/26350423/217917028-f18ff79c-6900-4fc6-ae44-0972675d874e.png)
![image](https://user-images.githubusercontent.com/26350423/217917264-8a3215fa-c736-4f6f-95e4-7ed307f86f65.png)

**Comment by scurest** [comment]
The indices list contains every tri twice, with opposite winding order each time (eg. 8 9 0 and 0 9 8).

In Blender a valid mesh has at most one tri on any given three vertices. So when we validate the mesh it deletes half the tris.

**Comment by Woitek1993** [comment]
> 

It explains a lot. Thank you for help.

**Comment by julienduroure** [comment]
Hello,
Seems we can close this ticket, as Blender valid mesh can not keep the mesh as it is on glTF file
Thanks to scurest for the investigation.
