### ISSUE TITLE
GLTF import appears to broken in the currently available version of bpy on pypi

### ISSUE THREAD

**Issue by taranlu-houzz** [KhronosGroup/glTF-Blender-IO#1885]
**Describe the bug**
It seems that the version of this add-on that comes with the `pypi` install of `bpy` has a bug related to the deprecated `np.bool` (I assume this is probably issue #1844).

It sounds like this issue is already fixed in the main branch of this add-on, and interestingly, when using the full, gui version of Blender 3.4.1, there does not appear to be an issue.

I am wondering if there is currently any work-around to get things working with the `pypi` installed version of `bpy`?

**To Reproduce**
1. Install `bpy` into a Python virtualenv.
2. Run Python, then attempt to import a gltf file: `bpy.ops.import_scene.gltf(filepath="path/to/my/file.gltf")`

**Expected behavior**
No `AttributeError` due to `np.bool`.

**Version**
 - OS: macOS
 - Blender Version: 3.4.0 (bpy)

**Comment by julienduroure** [comment]
Hello,

np.bool was deprecated in numpy 2.20 removed in 2.24

I supposed you can it work by downloading another version of numpy, that is < 2.24
(For example, Blender 3.5 will be shipped with numpy 1.23.5)
Anyway, Blender 3.5 will be release at end of the month, and I the package will be updated with the fix.
Closing this ticket, as there is no plan to backport fixes into 3.4

**Comment by taranlu-houzz** [comment]
@julienduroure Ah, perfect! Thank you! I misread the release notes for `numpy` and thought that `np.bool` was completely removed in version `>1.20.0`. I just changed out to the version you suggested and it appears to have resolved the issue. Thanks!
