### ISSUE TITLE
Is there a way to export poses in the asset library as 1-frame animations without having to move them to NLA?

### ISSUE THREAD

**Issue by ansonkao** [KhronosGroup/glTF-Blender-IO#1890]
On Blender 3.6, currently, the following option ignores animations that are marked as a pose in the asset library. Is that intended?

<img width="237" alt="image" src="https://user-images.githubusercontent.com/300092/228436691-9c542c8c-47e3-46a2-9e25-861daadacdeb.png">

I know there is demand for more options like this because someone has made a hacky script:
https://github.com/TokisanGames/blender-pushdownall

**Comment by julienduroure** [comment]
Hello,

Do you have more information about what you are talking about? Armature or object asset lib? Local or lib from another file?
In a first test, seems armature local pose asset is already taken into account if  the option "All armature action" is checked. (see simple file attached).

![image](https://user-images.githubusercontent.com/1696020/228602976-db298b21-93a0-4ad1-8fd7-aed6366c0f63.png)
[test_armature_pose_assets.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11103053/test_armature_pose_assets.blend.zip)

**Comment by julienduroure** [comment]
More than a month without any answer, closing this ticket
