### ISSUE TITLE
Random orientations and translations when exporting gltf files from Blender

### ISSUE THREAD

**Issue by jtragtenberg** [KhronosGroup/glTF-Blender-IO#1892]
I need to modify and save a gltf file of a 3d model of a hand from sketchfab (https://sketchfab.com/3d-models/female-hand-3e9b8ad1942048e3a267d92fb1124d46).
I used blender to import it, modified it and exported again as a gltf file. I needed to rotate and translate the model to match the coordinate system of a live sensor control of the model. The smartwatch IMU gave quaternions rotations that I only used the quaternions to rotate in real time the model. It was really important for me to match the angles of the hand to the smartwatch. I then used the 3d model in three.js 
I noticed sometimes when I rotated the model around one axis it exported with no change. Sometimes I exported the same model with the same orientation in blender and it gave different orientations outputs. It seemed completely random... Is there a way to force the exporter to match the orientation grid from blender? If I export the hand aligned with the Z axis it should be exported as such...

**Comment by julienduroure** [comment]
Hello,
I can't have enough information to be able to reproduce.
Can you please provide the .blend file (with modification you perform on original file) you are trying to export?
Do you use non default option at export?

**Comment by julienduroure** [comment]
More than a month without answer. Without test case, we can't analyze your problem. Closing this ticket
