### ISSUE TITLE
Some parts of model is lost after export to gltf on Version 3.4.1

### ISSUE THREAD

**Issue by damonsong** [KhronosGroup/glTF-Blender-IO#1894]
**Describe the bug**
Some parts are lost after export to glb format file.

**To Reproduce**
Open the blender file which is created by Blender version 3.0.1.
Go to File -> Export -> Gltf 2.0

Geometry - Apply Modifiers. Rest of settings are default.

Import the gltf file by using any online viewer, for example
https://gltf-viewer.donmccurdy.com/

or

https://threejs.org/editor/

Some parts of model are lost.

![image](https://user-images.githubusercontent.com/1516260/229755331-4024cc6d-3187-4a73-a7d9-21e7721cd780.png)

In the image, the paddles are lost.

**Expected behavior**
The model is complete.
Blew is the one which is exported by v3.0.1. It's normal
![image](https://user-images.githubusercontent.com/1516260/229755470-068d296c-f013-4368-97fa-771ba91e5b7a.png)

**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
Operating system: Ventura 13.2.1 (MacBook Pro 16-inch, 2021, Apple M1 Pro)
Graphics card: Apple M1 Pro

Blender Version
Broken: Version 3.4.1
Worked: Version 3.0.1

The gltf and blender files are shared at
[Google Driver](https://drive.google.com/drive/folders/1UJODZHtF7bxFVmw7gm6qRqDlvOPgDFkC?usp=sharing)

There are too big to upload here.

2 glb files, one is exported from v3.4.1 (aka v341) another one is exported from v3.0.1(aka. v301). The later is normal.
1 blender file is created by using blender v3.0.1.

**Comment by julienduroure** [comment]
Hello,
I can not reproduce in 3.5 or in main

![image](https://user-images.githubusercontent.com/1696020/230141071-1109e15f-b2be-47f9-ab06-28083326622b.png)

The paddles are here (I added a cube with SubSurf to be sure I am using "Apply Modifier" option)

Can you please test it on 3.5 or daily build ?

**Comment by damonsong** [comment]
> Hello, I can not reproduce in 3.5 or in main
> 
> ![image](https://user-images.githubusercontent.com/1696020/230141071-1109e15f-b2be-47f9-ab06-28083326622b.png)
> 
> The paddles are here (I added a cube with SubSurf to be sure I am using "Apply Modifier" option)
> 
> Can you please test it on 3.5 or daily build ?

Hi, I tried on v3.5. It's normal and thank you.
I update my Blender to v3.5
