### ISSUE TITLE
GLTF/GLB export options....

### ISSUE THREAD

**Issue by Carandiru0** [KhronosGroup/glTF-Blender-IO#1895]
Exporting .gltf or .glb seems to be missing a natural and most logical option.

Neither .gltf or .glb have the option to export with meshes, materials (not textures), animations embedded in the exported file. So the option to have everything embedded in the file, except textures are not. 

The *relative path* to the texture file(s) for instance would simply be stored 
in the uri for each mesh in the .glb.

This would be a more natural option to have would it not. I'm currently stuck because I need .glb files, and the associated textures to be separate.  Don't want to use any .bin files of any kind.

This model, if you will, for the mesh and other data to be in one file, and textures to be separate into there own files --- Is used everywhere! I'm surprised this option was missed! Isn't it supposed to be the default option?

Both .gltf text files and .glb binary files support uri's (relative path strings) for textures.

Thanks for your time and consideration!

**Comment by julienduroure** [comment]
Hello,
Thanks for your request.
I don't know if this is a very waited feature, as this is the first time someone request it.

We have to mitigate between adding more option, fine tuning the output file(s), and keeping a simple and comprehensive list of option, even for not so much used to 3D users. Not an easy task!

In a first step, you may have to have a look on post export step that can be achieved to convert of gltf files, like https://gltf-transform.donmccurdy.com/

@donmccurdy , does you tool manage this case?

**Comment by emackey** [comment]
Yeah, I would agree, sorry @Carandiru0.  By far the most common use of GLB is as a fully self-contained format, with no external references, and many users naturally expect that when receiving a GLB.  There's little practical advantage to using the GLB container (as opposed to *.gltf) if you're not making it self-contained.

If the textures are external, we recommend the bin file also be external.  This has advantages, for example the *.gltf file becomes editable plain JSON text, web browsers can cache the files and textures individually, and in advanced use cases there can be multiple meshes and/or multiple animations split across multiple .bin files that could be served, accessed, and cached individually.

By bundling only the binary portion without the textures, you end up in a grey area where the file is half-binary and not really editable, but still not usable on its own.  I don't think it's the sort of thing we want to export from here.

**Comment by Carandiru0** [comment]
ok fair enough, the current .gltf + .bin + textures export option works for me -- It's just a little different then the usual "model" + "textures" (separate files) idiom I've seen. I mean the data for the vertices, indices and what ever else is not usually exported alongside those two I mentioned.
I do see the advantage of the export all the data separately, as the .gltf is smaller to traverse, and generally more readable.

I do however think that .glb, being the binary option, could also have an option for export. That option being:

   All data except:
               - textures
   is in the .glb

or alternatively:

      All textures referenced with a relative uri in the .glb

That would be a relatively simple change or option to implement, as presented  ie.)  Textures:   [X] External  [  ] Internal
This I hope clarifies what I originally intended in op.

**Comment by emackey** [comment]
It would be an easy change, but unfortunately it's something that several members of the Khronos working group for glTF have expressed opposition to in the past.  We've built up a reputation for GLB as being self-contained, and we have *.gltf for when external references are wanted, and there are well-thought-out reasons for both to be that way.  The group is trying to do what's best for the glTF format, not just imitate common behaviors and patterns of other formats.  Sorry I don't have better news here.
