### ISSUE TITLE
KTX / KTX2 Support

### ISSUE THREAD

**Issue by Carandiru0** [KhronosGroup/glTF-Blender-IO#1896]
Currently .png and .jpeg are the only options supported on export.

I'm requesting that KTX2 be added to that list, which is the format to support/complete the gltf pipeline.

PNG's and JPEG's cannot be used in game development. The raw highest quality (including HDR formats) is used instead.

There would be no need for conversion or transcoding, as the textures should be natively supported for display and usage in Blender as a whole. Simply referencing the existing texture file (.ktx2) would be the most logical.

On export the .ktx2 textures that were referenced by the model in Blender should be the exact same textures used on .gltf or .glb export, referenced in the uri's of that format for example. The textures should be untouched.

Thanks! This is really needed for game-development pipeline, as there is currently no defined support for KTX/KTX2 files - anywhere! 

Khronos should weight in on this one, why the huge delay between supporting KTX or KTX2 with GLTF or GLB?
Your formats should work together! Which they would, if someone implemented it, can a developer at Khronos review this issue and then understand that for Khronos, this state is currently unacceptable. Huge opportunity!

Thanks again!

**Comment by julienduroure** [comment]
Hello,
This feature is definitively something we want to add.
For now, Blender does not manage KTX textures, so integrate it in this addon is not an easy task.
There are some discussion about the best way of doing.

**Comment by donmccurdy** [comment]
100% agree, I would like to see Blender support import/export of KTX2 textures.

That said, if you are doing game development: the ideal number of tools that should process your glTF files — after export from Blender and before the files arrive in the game runtime — is non-zero. Along the same lines as your request in #1895, we try to export Blender scenes to glTF as accurately as possible, and that alone is a huge task. Trying to not just export *accurate* 3D files, but also *fully optimized* 3D files is a much larger task, and ultimately not possible in any DCC tool or file format I'm aware of today.

glTF is different from most 3D formats for the simple fact that it *can* be optimized for use in a game runtime, but I'd encourage you to use at least one processing tool (in addition to Blender) for that purpose. Several options worth considering include:

- [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf#-gltfpack)
- [gltf-transform](https://gltf-transform.donmccurdy.com/)
- [RapidCompact](https://www.rapidcompact.com/)
- [Gestaltor](https://ux3d.io/gestaltor)

All of these support KTX2 compression in glTF 2.0 files.

**Comment by Carandiru0** [comment]
I was hoping to have no intermediate step between Blender exporting a .gltf to the game engine using it, which I have working with a simple workaround that replaces the extension to be the same filename + .ktx2 in the reading of the gltf model texture uri's.

I think that the most ideal pipeline is one that uses Blender and that's it! Efficient and simple, no file format conversion or other such nonsense. Complex Pipelines and using multiple different tools seems rather the opposite!

I do have a unique implementation however, the .gltf is voxelized in-engine, where voxels (tiny ones) are rendered rather than the polygonal model. This is cached to a .v1xa file, which is a internal engine format for voxels with animations / sequences.
With higher resolution voxels, rendering in game, well the end result is just awesome. 

Thanks again for looking into this.

**Comment by Carandiru0** [comment]
fair enough, thank you for the clarification.

**Comment by donmccurdy** [comment]
I do think it's worth keeping an issue open to track interest in this feature — similar to https://github.com/KhronosGroup/glTF-Blender-IO/issues/1308. Let's reopen if that's OK?

**Comment by Bug-Reaper** [comment]
KTX2 textures are huge boost for GLTFs especially for certain scenarios I have where loading-textures blocks the main-thread. 

Even something that used the opensource KTX2-CLI-tool to convert texture images as they're exported could be pretty nifty.

**Comment by Jeggery** [comment]
> so integrate it in this addon is not an easy task

Why is it not easy? Is there any difficulty

**Comment by tonis2** [comment]
I created extension for Blender gLTF that can help with KTX import/export.
https://github.com/tonis2/glTF-KTX-texture

Still in early development and feedback very welcome.

**Comment by walcht** [comment]
@julienduroure - So far, I managed to load glTF + KTX2 textures on Blender (and the whole usual workflow of displaying, editing, etc.).

I am currently working on the exporter which should *probably* be straightforward.

The fork of OpenImageIO that adds KTX support is here: https://github.com/walcht/OpenImageIO and I will open a PR to OpenImageIO once I complete the writer part (probably in 3-4 days).

Once that PR is merged, I will open a PR here as well that should (obviously) only be merged when Blender updates its OIIO lib version.

Note (to avoid confusion):
- I am **not** talking about adding native support to KTX within Blender (as @Carandiru0  is suggesting). That would probably require significant effort. I am mainly talking about adding the ability to import glTF + KTX textures (and also KTX textures directly; without gltf), work on them as you would work on any other format, then export them (same as original + modifications).

**Comment by jo-chemla** [comment]
Impressive progress on adding KTX support to OIIO here https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/2329#issuecomment-4299697780! 

For reference regarding the other bits, blender thread related to the ongoing effort of integrating `libktx` within blender for native KTX compression support is [here](https://projects.blender.org/blender/blender/issues/155432).

**Comment by julienduroure** [comment]
Draft PR of glTF-Blender-IO for KHR_texture_basisu are available here: #2698 #2696 

KTX integration in Blender will not happen in 5.2, but maybe in 5.3 (with direct integration).
When/if available in OIIO, Blender maybe decide to remove direct KTX support to manage it through OIIO.

I am not really aware of OIIO release cycles, do you have any info?

**Comment by sparazza** [comment]
Maybe this addon (that enables the ktx import and export) could be a temporary solution?
https://github.com/tonis2/glTF-KTX-texture

<img width="285" height="304" alt="Image" src="https://github.com/user-attachments/assets/18a982ed-dc7e-462c-ab43-5fcc7f9b480b" />

only perk, it requires KTX-Software tools (downloaded automatically on first use, can take few minutes ~7MB)

EDIT: Sorry but I haven't seen that the creator of the addon was here a few months ago (https://github.com/KhronosGroup/glTF-Blender-IO/issues/1896#issuecomment-3837558051), so this was already on the table ☮️  worth the reminder 😅

**Comment by Jeggery** [comment]
> <img alt="Image" width="285" height="304" src="https://private-user-images.githubusercontent.com/9979044/613613049-18a982ed-dc7e-462c-ab43-5fcc7f9b480b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODI0NzA0MDcsIm5iZiI6MTc4MjQ3MDEwNywicGF0aCI6Ii85OTc5MDQ0LzYxMzYxMzA0OS0xOGE5ODJlZC1kYzdlLTQ2MmMtYWI0My01ZmNjN2Y5YjQ4MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA2MjZUMTAzNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ2YTIxM2RkZDZjMjg2ZjE5ZDk3YjI4OWEwNTZhNDg3MWMwODQ3NWRjOThhNmZiOWJmZjQ1NjkyNGIxZDM5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.iY3uLGyly0oXmK2yCJUkr-ATcxeAuGQssGcHjKWMnmQ">

Looks good. I really didn't know this plugin existed before. It would be even better if the official version could integrate this feature.

**Comment by walcht** [comment]
Some updates:

- I received some initial review (finally) on my KTX2 addition to OIIO: the main maintainer stated that the target is to include KTX2 support in OIIO 3.2 release
- My KTX2 OIIO PR is almost finished (still have to work on Cubemaps support, image orientation, and a couple of other things)
- Getting reviews/responses from OIIO side takes some time (understandably, as they are probably dealing with huge amounts of security/bug patches)
- In the meantime, I added some stuff to libktx to bring it to parity with DDS (and significantly better, if you ask me): mainly BCn formats support, rate-distortion-optimization with up-to 50% filesize reduction, lossless DDS to KTX2 conversions, etc.

I will share updates once progress on KTX2 OIIO PR occurs.
