### ISSUE TITLE
 Importing a glTF model and exporting it without any modifications using Blender 3.5 on a Mac results in the model not being detected by raycasting in three.js. The original model can be detected

### ISSUE THREAD

**Issue by hangaoke1** [KhronosGroup/glTF-Blender-IO#1898]
**Describe the bug**
Importing a glTF model and exporting it without any modifications using Blender 3.5 on a Mac results in the model not being detected by raycasting in three.js. The original model can be detected, but not the one exported through Blender.

**To Reproduce**
https://codesandbox.io/s/xenodochial-euclid-6glof3?file=/index.html
stacy.glb is ok
stacy2.glb is not ok whitch is exports by blender

**Expected behavior**
stacy2.glb can detect click

**Screenshots**

**Version**
 - OS: macOS
 - Blender Version 3.5

**Comment by julienduroure** [comment]
Hello,
Not sure to understand what is your problem.
stacy2 is valid, can be correctly displayed on https://gltf-viewer.donmccurdy.com/, or imported back on Blender, with correct normals..
Not sure how your raycast works, but seems to have the same behavior with both files.
Please screenshot what you see.

**Comment by donmccurdy** [comment]
I think the cause here is some change in the skinning data. That some skinned meshes are missed by raycasting is a bug reported in three.js. Not a Blender bug, though skinning import/export without data change would be ideal (if understandably difficult).

**Comment by hangaoke1** [comment]
> Hello, Not sure to understand what is your problem. stacy2 is valid, can be correctly displayed on https://gltf-viewer.donmccurdy.com/, or imported back on Blender, with correct normals.. Not sure how your raycast works, but seems to have the same behavior with both files. Please screenshot what you see.

Thanks for reply，There are some questions that I am confused about and need some help.

1、When importing a glb model into Blender, the scaling and rotation information of the SkinnedMesh object is lost, but it appears to be fine.

2、Due to the loss of scaling and rotation information of the SkinnedMesh object, the vertex normals of the SkinnedMesh are abnormal after exporting.

3、when exports gltf without skin its ok

Unfortunately, I am not sure what happened during the import and export process.

you can test in https://threejs.org/editor/

### source file   https://hgkcdn.oss-cn-shanghai.aliyuncs.com/3d/stacy.glb
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/19623160/230696877-d816b7c2-fb5f-4115-879f-a575f2b5abe3.png">

### blender exports file https://hgkcdn.oss-cn-shanghai.aliyuncs.com/3d/stacy2.glb
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/19623160/230696916-b28812df-c5a9-4c3c-a723-043fb2be5032.png">

**Comment by hangaoke1** [comment]
### imports glb
<img width="528" alt="image" src="https://user-images.githubusercontent.com/19623160/230724777-bf3e58f3-1cbb-4136-8d0d-35ed03d96867.png">

### after apply all transforms
<img width="357" alt="image" src="https://user-images.githubusercontent.com/19623160/230724821-153728c4-97aa-438e-a20a-71f723745165.png">

### after exports
<img width="712" alt="image" src="https://user-images.githubusercontent.com/19623160/230725189-37fa6ea7-f288-4350-b122-1432712a0b56.png">


I found that after apply all transforms, the exported model can display vertex normals correctly in the three.js editor, but in Blender, the object origin changes and the animations are also incorrect. The weirdest thing is that after clicking "Export", the model's position will also change.

steps
1、import stacy.glb
2、apply all transforms（the orgin will change，and animate location is not right）
3、exports glb

**Comment by donmccurdy** [comment]
Unless there's anything we want to change about how Blender roundtrips skinning data, I believe this issue could be closed. three.js users can track improvements to raycasting of skinned meshes in https://github.com/mrdoob/three.js/issues/25859.
