### ISSUE TITLE
Remember Export Settings - Data>Lighting>Lighting mode is not saved. 

### ISSUE THREAD

**Issue by BlackBladeDesign** [KhronosGroup/glTF-Blender-IO#1899]
When exporting a model to GLTF or GLB, the lighting mode can be switched between Unitless, Raw, or Standard. 
This setting is not saved on export correctly; where while still using the same open instance of blender it will retain the setting, but saving and re-opening the blender instance will remove the saved selection. This is fine for small projects, but working with various GLB projects daily makes it more of an issue.

1. In a new instance of blender, or opening an old blend file, export to GLB and apply a variety of settings. Change the lighting mode via Data>Lighting.
2. Export the GLB. 
3. Re-export the model again, see that the new lighting mode is still selected.
4. Save the blend file and quit.
5. Re-open the blend file, and export again. Observe that all settings chosen are still set, but the lighting mode is not.

With 'Remember Export Settings' enabled, all settings available to the users should be retained if the blend file is saved and re-opened. 

 - OS: [macOS]
 - Blender Version [3.5]

**Comment by julienduroure** [comment]
Confirmed
