### ISSUE TITLE
Emissive factor default is [0.0, 0.0, 0.0]

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#190]
Currently in code, default is set to [1.0, 1.0, 1.0]

**Comment by emackey** [comment]
Some comments about this.  In Blender, if you build a node graph without multiplying by any "emissiveFactor" type node, you will get the effect of [1.0, 1.0, 1.0], not glTF's default of [0.0, 0.0, 0.0].  So if you find a glTF that doesn't specify `emissiveFactor`, the importer still needs to build an emissiveFactor node with all zeros, and multiply that in.

Conversely, given a glTF that manually specifies all ones for emissiveFactor, the importer has the option of leaving off the emissiveFactor node entirely, and just hooking up the emissiveTexture directly, even though that's not glTF's default.

**Comment by julienduroure** [comment]
Agreed.
That's exactly what I have in thought :)
