### ISSUE TITLE
Blender animation involving rotation values > 360° incorrectly exported to GLTF?

### ISSUE THREAD

**Issue by alikim-com** [KhronosGroup/glTF-Blender-IO#1908]
**Describe the bug**
I have a mesh rotating in Blender from 376° to 132°, when exported to .glb, the rotation looks like it goes from 16° to 132°, missing extra 360° and rotating CWW instead of CW.

**To Reproduce**
1. Open test.blend
2. Export to .glb
3. Run .glb

**Expected behavior**
The mesh should rotate in the different direction by 244°

**Screenshots**

**.blend file/ .gltf**
file attached

**Version**
 - OS: Win10
 - Blender Version 2.90.1

**Additional context**
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11238380/test.zip)

**Comment by julienduroure** [comment]
Hello,
2.90.1 is a (very) old release, not more maintained.
Can you please test on current stable 3.5 or 3.6 alpha?
I can't reproduce your issue with these 2 versions.

**Comment by alikim-com** [comment]
> Hello, 2.90.1 is a (very) old release, not more maintained. Can you please test on current stable 3.5 or 3.6 alpha? I can't reproduce your issue with these 2 versions.

I tried it in Blender 3.5.0 - I still have the issue, nothing changes.

Which part you can not reproduce?
Do you see the mesh rotating by 244 deg in Blender?
Do you see the mesh rotating differently in .glb file? (I use https://sandbox.babylonjs.com/ and THREE.js to check)
Are export settings included in .blend file or do I need to provide them separately?

**Comment by julienduroure** [comment]
- Open your .blend file
- Export to glb, without any change in settings, using only default export settings
- Import it back in Blender (without deleting your original object)
- I can see that both object are animated exactly the same way
- Import your test.glb ( from your zip, still without deleting the 2 existing objects)
- I can see the rotation is wrong

Here is my generated glb (with 3.6 alpha)
[test_3.6.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11238552/test_3.6.glb.zip)

**Comment by julienduroure** [comment]
Additional information, in case your are not using animation sampling:
Rotation more the 360° can not be represented with quaternion (used in glTF specification to express rotations) using only 2 keyframes. 

More information:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1253#issuecomment-716894375

**Comment by alikim-com** [comment]
Yes, I can see from your file that your export settings simply insert keyframe at each frame to keep the animation in quaternion mode.
Unfortunately, it won't work for me as it makes my files too big.
I though the exporter is smart enough to break long rotations and insert keyframes where needed and use quaternions in between, I'll have to use another way of exporting the animation.
I'm closing the issue, thank you for the fast reply!
