### ISSUE TITLE
Gltf vertex colors not imported correctly

### ISSUE THREAD

**Issue by JuliaSchubert** [KhronosGroup/glTF-Blender-IO#1911]
**Describe the bug**
At the moment we are working on a gltf/glb exporter. Since we move our data online, we make sure from the outset to use data types that allow minimum file sizes. Therefore, we have stored the vertex colours in our example as "unsigned char". The following lines are in the accessor:

componentType = 5121;
count = VertexCount x 4 x sizeof(unsigned char);
type = 4;

The whole thing is displayed correctly in various viewers, not only the MS 3D viewer. In Blender, however, we see the representation that can be seen in the "Blender" screenshots.

We have looked at the vertex colours in Blender and noticed that Blender displays the colours as floats in the range of 0.f - 1.f. The colours are not displayed in Blender. It occurred to us that Blender might be misinterpreting our input data. For further understanding, here are the colours we use.

from this colours:
1, 1, 1, 255
182, 178, 25, 255
0, 72, 42, 255
149, 136, 126, 255
149, 149, 149, 255
204, 204, 204, 255

Blender generate this colours:
1, 1, 1, 1
1, 1, 1, 1
0, 1, 1, 1
1, 1, 1, 1
1, 1, 1, 1
1, 1, 1, 1

Since all values are between [0,255] interpreted as float only 0 stays 0, all other values are larger or equal than 1 and are clamped to 1.

Would it be possible for you to check this. Of course we could also code the colours as floats. But this would result in an overhead of 12 bytes / vertex, which would mean ~ 1 MByte more data transfer for 100,000 vertices. And we have many files that hold several million vertices.

**To Reproduce**
1. Import the gltf in Blender
2. Switch the view port shading to display vertex colours 

**Expected behavior**
A correct display of the component

**Screenshots**
![Vertex_Colors_Displayed_In_Blender](https://user-images.githubusercontent.com/106814574/232984022-10f7c27b-8a96-4331-abb8-12b2eb20bc1e.JPG)
Vertex colours displayed in blender.

![Vertex_Colors_Displayed_In_Win_3D_Viewer](https://user-images.githubusercontent.com/106814574/232984027-5c69da8a-29be-4a95-9d40-839d0966673b.JPG)
Vertex colours displayed in the windows 3D viewer, correctly.

**.blend file/ .gltf**
[weraIn.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11269372/weraIn.zip)

**Version**
- OS: Windows 10, 11. Ubuntu 22.04
- Blender Version 3.41 Ubuntu
- Blender Version 3.3.1 and 3.5 Windows

**Additional context**
We have stored the blender vertex colours in the attached text file for personal checking. This represents the current situation.
[vertex_color.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/11269418/vertex_color.txt)

**Comment by julienduroure** [comment]
Hello,
Seems your gltf is not valid, you can't use {VEC4, UNSIGNED_BYTE} for vertex color

You can see it using https://github.khronos.org/glTF-Validator/

>  "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT",
                "message": "Invalid accessor format '{VEC4, UNSIGNED_BYTE}' for this attribute semantic. Must be one of ('{VEC3, FLOAT}', '{VEC3, UNSIGNED_BYTE normalized}', '{VEC3, UNSIGNED_SHORT normalized}', ..., '{VEC4, UNSIGNED_BYTE normalized}', '{VEC4, UNSIGNED_SHORT normalized}').",
