### ISSUE TITLE
Exporting Quads or Other Non-Triangle Topology Should Fail

### ISSUE THREAD

**Issue by effs** [KhronosGroup/glTF-Blender-IO#1912]
**Describe the bug**
GLTF does not support quads. Currently a model with quads can still be exported (and without an explicit warning to boot.)

Previous discussion converged around showing a warning, but I think failing is the correct option since the resulting GLTF is essentially undefined.

See #1273, #172 

**To Reproduce**
See previous tickets, or create a mesh with quad and export it. This also affects targets (shapekeys.)

**Expected behavior**
Attempting to export a model with meshes that have non-triangle topology should fail and inform/offer the solution of triangulation.

If for some reason this is not possible or desirable, a warning should be displayed with the default being to cancel the export.

**Screenshots**
N/A

**.blend file/ .gltf**
Excerpt from a .gltf - 

```json
	"meshes":[
		{
			"name":"submesh_07_LOD_1.002",
			"primitives":[
				{
					"attributes":{
						"COLOR_0":0,
						"POSITION":1,
						"TEXCOORD_0":2,
						"NORMAL":3,
						"JOINTS_0":4,
						"JOINTS_1":5,
						"JOINTS_2":6,
						"WEIGHTS_0":7,
						"WEIGHTS_1":8,
						"WEIGHTS_2":9
					},
					"indices":10
				}
			]
		},
		{
			"name":"submesh_07_LOD_1.003",
			"primitives":[
				{
					"attributes":{
						"COLOR_0":12,
						"POSITION":13,
						"TEXCOORD_0":14,
						"NORMAL":15,
						"TANGENT":16,
						"JOINTS_0":17,
						"JOINTS_1":18,
						"WEIGHTS_0":19,
						"WEIGHTS_1":20
					},
					"indices":21
				}
			]
		},
```

**Version**
 - OS: Windows
 - Blender Version 3.3.4, 3.5.0

**Additional context**
I'm not 100% the export is correct beyond the missing tangents. As far as I recall, _both_ of the above submeshes had quads but only the first is missing tangents. I did not have the chance to recheck yet.

**Comment by julienduroure** [comment]
Warning is now shown
