### ISSUE TITLE
Exporting children (paranted objects) of linked objects dosn't wokr

### ISSUE THREAD

**Issue by Gapi34** [KhronosGroup/glTF-Blender-IO#1914]
**Describe the bug**
If you have objectes (dosn't matter if they are linked, append or not eather) paranted to a linked object in the scene when you export it dosn't export them. It dosn't matter what check box you check for the "include" setting on export the same problem is present on all or non of them. I did notice that if the parent is an appended object it works as it should.

**To Reproduce**
1. Make a blend file with a cube in a collection.
2. Make another blend file and link that object.
3. Make a cube and parented it to that linked object.
4. Export the file as glTF and see that it only exports the linked object not it's child.

**Expected behavior**
I would expect for all the childer of a linked object to be exported, the same way is works if the object is appended.

**.blend file/ .gltf**
[BTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11404233/BTest.zip) i added some animation to the cubes, but the probelm is the same without it

**Version**
 - OS: Windwos 10
 - Blender Version 3.5.0 blendeer 3.5 relese version.

**Additionly information**
It dosn't exort consecituve childer eather, so if you have an object paranted to another object paranted to a linked one.

**Comment by julienduroure** [comment]
Confirmed.
I will check it soon
