### ISSUE TITLE
KHR extensions - ability to turn off exporting

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#1923]
I disagree with the current way KHR extensions are automatically added to the export if default values are changed.
If the specular value is changed from the default, then it will automatically add the KHR_materials_specular AND the KHR_materials_ior extensions. 
**Describe the solution you'd like**
A feature added to export dialog - checkbox and to turn off auto KHR extensions.

**Describe alternatives you've considered**
Returning specular and tint to default is not viable - no way to search for materials that have changed from default values.

**Additional context**
None
![DA40CGDFQ_2023 05 18_16h2m53s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/fbb9c649-fdfc-48b8-ab7a-95ce5929fc07)

**Comment by julienduroure** [comment]
Hello,
This addon is based on behavior to export as close as possible what the user see, including material nodes. If use changed the default value, it makes sense to include this information into the exported file.
I am not sure I want to add more UI option to be able to turn extension off, as these extensions are a great enhancement to PBR materials.
A solution should be to add some hooks to enable/disable extensions, and creating an hook-addon with UI to choose extensions to keep.

**Comment by ronh991** [comment]
Ok will try the route of adding a hook to block what I don't want. Closed
