### ISSUE TITLE
Export Window: Minor visual bug - preset selection

### ISSUE THREAD

**Issue by BlackBladeDesign** [KhronosGroup/glTF-Blender-IO#1924]
Visual exporter issue:

*Steps to reproduce*
- Steps to reproduce the behaviour:
- Navigate through File>Export> glTF 2.0 (glb/.gltf).
- Create a new preset using the '+' key in the top right of the export window.
- See that the selected preset does not display when selected.

**Expected behaviour**
- When a preset is selected, the dropdown should display it, or at least give some indication that it is using the preset.

**Screenshots**
![Screenshot 2023-05-22 at 4 06 11 pm](https://github.com/KhronosGroup/glTF-Blender-IO/assets/126746830/2068fccb-5820-42f3-8916-b230160430f4)

**Version**
 - OS: macOS
 - Blender Version [3.5]

**Comment by julienduroure** [comment]
Hello,
This behavior is inherit from Blender default operator preset.
Can you confirm you get the same behavior using other exporters? (for example exporting .obj)

This is not a bug, but a proposition of enhancement for Blender itself, not this specific addon. You should propose it on https://blender.community/c/rightclickselect/ or start a new discussion on https://devtalk.blender.org/

**Comment by BlackBladeDesign** [comment]
You are right, the functionality is the same with other exporters. My mistake. 
I'll propose it.
