### ISSUE TITLE
Breaking API change in Blender 3.6

### ISSUE THREAD

**Issue by RedMser** [KhronosGroup/glTF-Blender-IO#1928]
**Describe the bug**
#1832 removes the `export_nla_strips` from the Python API and replaces it with `export_animation_mode`. This is a breaking API change.

**To Reproduce**
View the diff of [addons/io_scene_gltf2/\_\_init__.py](https://github.com/KhronosGroup/glTF-Blender-IO/pull/1832/files#diff-fbece75f1c3a62b56fc875409a1c591583948b14e304f099c4d5887b12ecaa14)

**Expected behavior**
A backwards compatibility layer that gradually deprecates this property instead of a breaking API change.

**Version**
Blender Version 3.6

**Additional context**
This is relevant for Godot's glTF importer integration. See [this issue](https://github.com/godotengine/godot/issues/76416#issuecomment-1547274913) which likely stems from this change, as well as [the relevant implementation](https://github.com/godotengine/godot/blob/master/modules/gltf/editor/editor_scene_importer_blend.cpp#L155).

**Comment by julienduroure** [comment]
Confirmed that API changed.
I will add again export_nla_strips (with no UI) for backward compatibility.
Note that there are other options added on 3.6 that are not taken into account in Godot yet.
