### ISSUE TITLE
Exported animations are different than Blender Animations.

### ISSUE THREAD

**Issue by FackJox** [KhronosGroup/glTF-Blender-IO#1933]
**Describe the bug**
My exported animations look very different to how the animations look in blender.
There is some weird deformations. Please see a snap of the three different animations with issues:
https://imgur.com/a/r6yNcdz
On export I've tried sampling keyframes, not sampling keyframes, optimise animations not optimise animations. Export with shape keys, without shape keys. Basically everything I can think of and the issue is still presented on export.

**To Reproduce**
1. View beautifully working animation in blender
2. Export GLTF and cross fingers
3. Pop exported GLTF in DMc's GLTF viewer
4. Sigh in dismay

**Expected behavior**
I expect the animations to look the same or pretty much the same as they do in Blender.

**Screenshots**
https://imgur.com/a/r6yNcdz

**.blend file/ .gltf**
https://easyupload.io/1snife

**Version**
 - OS: Windows 10
 - Blender Version: 3.4.1

**Additional context**

**Comment by julienduroure** [comment]
I have an error 500 when trying to download your test file.
Can you please upload it somewhere else?
Did you test with a more recent version? 3.5 or 3.6 beta?

**Comment by FackJox** [comment]
Just tried in 3.5.1 and it was the same, here is a different download link:
https://easyupload.io/1snife
Many thanks !

**Comment by julienduroure** [comment]
Hello,
Here is multiple points:
- Seems you have multiple NLA Tracks that are combine together. If you want to export only a single animation, you will have to use the new export option "Scene mode", available in Blender 3.6 beta. This will export animation as seen in viewport, not trying to export each NLA track separatly. You should also disable the ''Split Animation by Object", to be sure to create a single animation


- Your skinning has more than 4 weights by vertex. By default, only the 4 first weights are exported. You can enable it here: 
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/a7c259e1-9bdb-443c-9e25-294a40b46d78)
Note that all viewers does not manage more than 4 weights.
But it seems to look good, when re importing to Blender

**Comment by FackJox** [comment]
As far as I'm aware the NLA tracks are the way to export multiple animations for use in three js /r3f so scene mode won't be suitable. Unless I'm mistaken and scene mode can export multiple animations??

Interesting point on the Skinning and Bone Influences - I've reexported with the Include All Bone Influences checked and indeed there are difference between the babylon viewer and Dom's GLTF viewer, as you can see in the screenshots the babylon viewer is more more reflective of blender and the gum from the teeth aren't clipping through. 

Hopefully three can handle more than 4 weights, or I can set it so at least!!

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/45740075/04bb9079-44f2-4d35-902e-40ac5c004b4e)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/45740075/fc614908-3a00-4e1e-8f08-bd5b09d1caf1)

**Comment by julienduroure** [comment]
Hello,
Not sure there is some vanilla operators to bake shapekeys.
I didn't test them, but seems there are some addons to perform it.

Regarding your original problem, seems we can now close this ticket. Can you confirm that there is no remaining bugs?
