### ISSUE TITLE
Question: did the importer change from using "Vertex Color" node to "Color Attribute"?

### ISSUE THREAD

**Issue by garyo** [KhronosGroup/glTF-Blender-IO#1934]
My old python code to create blender scenes from my gltf scenes stopped working sometime between 3.0 and 3.6 (I haven't been trying recent versions). It seems to be because when the importer imports my gltf scene, which includes vertex color data, it now creates a "Color Attribute" node rather than a "Vertex Color" node -- my (admittedly old) code expects to see "Vertex Color". 
Is this something I'm missing or is it just a deliberate change and I should adjust my code?

**Comment by julienduroure** [comment]
Hello,
This is a deliberate change, as there is no more Vertex Color node in Blender, replaced by Color Attribute node. (changed in Blender 3.2)
