### ISSUE TITLE
Add option to have separate buffers for textures in glTF Embedded

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glTF-Blender-IO#1935]
**Is your feature request related to a problem? Please describe.**
Currently, the exporter writes geometry data (indices and vertices) and textures into a single buffer for `glTF Embedded` and possibly `glTF Binary` exports. This can create an inconvenience for programs (custom engines, etc)  when loading the `gltf` files with something like [cgltf](https://github.com/jkuhlmann/cgltf). It makes sense to have the geometry data in a single buffer. In both Vulkan and Direct3D12, it's straight forward to read the entire buffer from the `gltf` file and upload/copy it to the GPU in one go without the need for unnecessary intermediates. This is very convenient since any buffer referenced by mesh geometry can be uploaded wholesale. Having textures in the same buffer as the geometry data can remove this convenience. For programs that do not use the same GPU allocation for geometry and texture data, the buffer can not be uploaded wholesale as easily. One now has to account for the start/end of geometry data and texture data. 

**Describe the solution you'd like**
An option to separate the geometry and texture data into different two different buffers. 

**Describe alternatives you've considered**
Making use of the `glTF Separate` export. While this works, it's less convient than the `glTF Embedded` export.

**Additional context**
Texture uploads in some cases require a staging buffer so there's additional work already.

**Comment by julienduroure** [comment]
Hello,
Even if this is supported by glTF specification, not sure Blender have to manage every single case about how buffer are split.
The best way is probably to use a post-export process, for example [glTF-Transform](https://github.com/donmccurdy/glTF-Transform)

**Comment by chaoticbob** [comment]
> Hello, Even if this is supported by glTF specification, not sure Blender have to manage every single case about how buffer are split. 

Hi - I'm not sure I understand this? The request is to simply have two buffers instead of one. I haven't looked through the exporter code exhaustively, but is there a reason why the exporter could not selectively target a different buffer for textures?

**Comment by julienduroure** [comment]
Your request is legit, and there is no obstacle to implement it.
But, at the same time you request to have a separated buffer for textures, someone else asked to have separated buffer for each meshes, and someone else want to stay with 1 buffer only.
There is already so much option that change the data themselves, I don't really agree to add (too much) more to manage every request by users.
If your pipeline really need this feature, my suggestion is to export from Blender, and them manage the split with another software.

**Comment by chaoticbob** [comment]
Thanks fo the clarifcation, I see where you're coming from. Can you share the issue id for the othe request?

**Comment by julienduroure** [comment]
For example #1775

**Comment by chaoticbob** [comment]
Thanks for the link. Solved my issue with some buffer copies.
