### ISSUE TITLE
Conversion from Bezier to Hermit Spline not correctly reflected

### ISSUE THREAD

**Issue by moritzpeter** [KhronosGroup/glTF-Blender-IO#1937]
Hi,

I think the calculation of hermit spline tangents is not covered correctly.
Blender uses Bezier control points. It is easily possible to generate cases where the given implementation yields "very" wrong results.
In what region is the given approximation valid?
Is there a better way to cover this?

Thanks,
Moritz

https://github.com/KhronosGroup/glTF-Blender-IO/blame/4115a53160fb56119c387ffe898c5641216d98da/addons/io_scene_gltf2/blender/exp/animation/fcurves/gltf2_blender_gather_fcurves_keyframes.py#L77

**Comment by scurest** [comment]
The only difference between Blender's Bezier mode and glTF's is in Blender both the X and Y directions do Bezier interpolation, while in glTF only the Y direction does Bezier interpolation and the X direction always lerps.

If Blender's control points are 1/3 of the way and 2/3 of the way along the interval between the keyframes on the X axis, the Bezier interpolation reduces to a simple lerp, so it should in principle be exportable exactly.

![](https://github.com/KhronosGroup/glTF-Blender-IO/assets/11024420/9bbe5181-a342-42df-a489-7c1dd24380cc)

**Comment by julienduroure** [comment]
Do you have an example where the conversion is not correct?

**Comment by moritzpeter** [comment]
Hi @scurest and @julienduroure,
I was not aware of this "1/3, 1/3, 1/3 rule". This is excatly the information regarding the vaild region I was looking for. Thanks.
All examples I was testing were violating this rule. Thus, the issue can be closed.

Thanks, Moritz
