### ISSUE TITLE
Exporting animation done using follow path - does not show if export setting "Always sample" unchecked

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#1939]
**Describe the bug**
I use a nurbs path to make an object follow a  path.  If I export this blend file in gltf 2.0 it will animate in MSFS if Always Sample Animation is checked.  The export time using this setting is 10 times more than with the setting unchecked.  All other anmations including bone animations, and other NLAs work.

**To Reproduce**  BLENDER 3.3.7
1. create a movable object using a nurbs curve.  Add a rotation animation NLA, 
2. Bake these two animations to a single animation
3. Uncheck the original animations - so they do not get exported.
4. export using "Always sample animations" checked - note the export time in blender system console
5. export with "Always sample animations" unchecked - not the export times

**Expected behavior**
Expectations are that the animation with using a curved path to follow works in both cases.
"always sample animations" checked and unchecked.

I am unsure of what to check and uncheck in Blender 3.6 to emulate this functionality so I can check if this is an issue in 3.6 also.

**Screenshots**
Blender 3.3.7
![DA40_CGDFQ_2023 06 13_9h32m32s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/42bfef2c-7ac8-4d6a-a71c-aa3f59a4d9a1)

**.blend file/ .gltf**
no animation
[SGS233AAircraft_Cockpit_LOD00_pathDoesnotwork.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11735410/SGS233AAircraft_Cockpit_LOD00_pathDoesnotwork.zip)

has animation
[SGS233AAircraft_Cockpit_LOD00_pathworks.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11735409/SGS233AAircraft_Cockpit_LOD00_pathworks.zip)
blender 3.3.7

[sgs-233a_148_Asobo_Blender3.3_testexportissue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/11735435/sgs-233a_148_Asobo_Blender3.3_testexportissue.zip)

**Version**
 - OS: windows 10
 - Blender Version 3.3.7

**Additional context**
Exporting using ASOBO exporter 1.3.1 (should not affect animation as it uses the core Khronbos code)

**Comment by julienduroure** [comment]
Hello,
I can't see any issue here.

- Note that, as is, your test file export nothing. You export only selection, and have nothing selected. I remove the "Selection Only" option to test.
- Open your file in 3.6 beta => Animation are exported
- Every animation that have tracks on NLA are exported, no matter if they are muted or not
- export time is not a good metrics for checking if animation are exported or not, as not sampled animations export quicker than when the exporter need to sample.

For example, seeing these animations on https://gltf-viewer.donmccurdy.com/ :
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/bcb831dc-2553-4640-ab7a-1294de0758a7)


Some general notes:
- We are talking here about action that are already baked. A follow path action, before baking, can't be exported withtout sampling, as there is no transformation fcurves on the object itself.

**Comment by ronh991** [comment]
The file I gave you is a stripped down example of my issue.

"Note that, as is, your test file export nothing. You export only selection, and have nothing selected. I remove the "Selection Only" option to test."
When I export my work flow is to select what I want exported using the A key and then export. so my saved file did not have things selected is all.

"Every animation that have tracks on NLA are exported, no matter if they are muted or not"
That is an interesting statement.  I mute the extar NLA and this works for what I need do with MSFS.

"We are talking here about action that are already baked. A follow path action, before baking, can't be exported withtout sampling, as there is no transformation fcurves on the object itself."
Then this is probably the reason for my issue.

 I shall try 3.6 and see.  
 
 My overall issue is that the export times is 5-10 times what it was before.  So export times is a concern when the work flow is 
 1. make mods in blender
 2. export (usually 10-20 seconds and now 100-200 seconds)
 3. build in sim
 4. test
 5. repeat
 
 "Always Sample animations" unchecked was a good way for me to reduce the export times.  So now if I have a path animation I need to check that box.
 
 Thankyou for you time and explanation.
 
 I will close this issue, if this is all we can do.

**Comment by ronh991** [comment]
I have found which I believe is the issue, am in the process of verifying with ASOBO.  The difference between the two export methods is that the one that does not work has an interpolation of CUBICSPLINE rather than LINEAR.  Is there anyway to have LINEAR interploation done for my folow path animation when I uncheck "Always Sample Animations"?

![DA40_CGDFQ_2023 06 16_9h41m56s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/939fe309-7479-4f73-a821-749fb1cedc4a)

**Comment by julienduroure** [comment]
You action has bezier curve for all the channels, so not sampling export will use CUBISPLINE interpolation.
If you want linear, you have to change your baked actions to be linearly interpolated.
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/df83d1a4-87d7-488a-b8b4-e3e22def4859)

For changing interpolation : Select all your keyframes on your actions -> T -> Linear (in Graph Editor)

**Comment by ronh991** [comment]
Thank-you for your response.  This is indeed the fix for my issue of exporting flow path animations and the fix for long export times.  This also works in Blender 3.6.  Uncheck "Sample Animations"
![DA40_CGDFQ_2023 06 16_13h9m53s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/71b6360b-318f-4da5-97b7-2cbf92d0bf3f)
