### ISSUE TITLE
Objects with semi-transparent PNGs are not semi-transparent

### ISSUE THREAD

**Issue by soadzoor** [KhronosGroup/glTF-Blender-IO#194]
Hi,

I'm trying to create a leaf, which is typically a rectangle with a semi-transparent PNG texture.
I have the following node setup:
![capture4](https://user-images.githubusercontent.com/10392261/50455403-1cfdb980-094e-11e9-9f82-4b196c9a93ab.PNG)

And while it looks correct within blender (with viewport alpha: alpha blend):
![capture5](https://user-images.githubusercontent.com/10392261/50455437-461e4a00-094e-11e9-8466-e63e229f2157.PNG)

It looks very strange after exported:
![capture6](https://user-images.githubusercontent.com/10392261/50455465-63531880-094e-11e9-9f39-fc6e7cf49e4e.PNG)

Not only it's not transparent where it should be, but my guess is that the R and G channels are swapped for some reason.

Am I doing something wrong with the node setup? Or is it something else?

Here's the blend file, if anyone wants to test:
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2710791/test.zip)

**Comment by AlexMuir** [comment]
Definitely a bug, but I don't think it's related to transparency.  I re-exported your PNG on a white background with no transparency, plugged it straight into the Base Color node and I still get funky colors.

![image](https://user-images.githubusercontent.com/352587/50476276-e2d0fe00-09c7-11e9-8b41-fc22cc5a70d2.png)


![image](https://user-images.githubusercontent.com/352587/50476380-3ba09680-09c8-11e9-8de0-2c7a3c11baec.png)


![image](https://user-images.githubusercontent.com/352587/50476362-29265d00-09c8-11e9-9a79-fd6e2f94ed23.png)

**Comment by soadzoor** [comment]
> Definitely a bug, but I don't think it's related to transparency. I re-exported your PNG on a white background with no transparency, plugged it straight into the Base Color node and I still get funky colors.

Oh, thanks for checking. This gradient color gave me an idea, it might have vertex colors, so I checked, and it does!

Removing the vertex colors solved this "funky-color-issue", but it's still not transparent where it should be. Any idea on that?

**Comment by AlexMuir** [comment]
Ah good. I've tried a few things but nothing working so far.  I think that the exporter only really works with the Principled BSDF node, and anything like a mix shader that comes after that isn't exported.  That's my understanding anyway.  I notice that the BaseColor input for the principled node accepts RGBA values, not just RGB.  I can't figure out how to recombine the RGBA from the Image Texture node using its 'Color' and 'Alpha' outputs. I might be heading in the wrong direction here anyway!

**Comment by soadzoor** [comment]
From the docs, here's an example for a basic node setup for gltf: https://gltf-blender-io-docs-gbueavkvns.now.sh/_images/addons_io-gltf2-material-principled.png

So I guess transparency should work in a similar way to emission. I know we still have problems with emission as well, so I guess we have to wait (or contribute) to get these things done.

**Comment by AlexMuir** [comment]
I hadn't seen this manual.  What route did you use to get to that image?  The addons -> glTF 2 section is a 404 at the moment.

**Comment by soadzoor** [comment]
> I hadn't seen this manual. What route did you use to get to that image? The addons -> glTF 2 section is a 404 at the moment.

I've found it among the issues, right here: https://github.com/KhronosGroup/glTF-Blender-IO/issues/97

This is the link for the current prototype of the docs: https://gltf-blender-io-docs-fuznnktuig.now.sh/addons/io_gltf2

**Comment by donmccurdy** [comment]
Docs are now live, here: https://docs.blender.org/manual/en/dev/addons/io_gltf2.html

Are you using the `Alpha Clip` mode on the material? I think you'll need that.

**Comment by donmccurdy** [comment]
Oops, should have said using `Alpha Clip` mode, and also setting a clip threshold >0. With 0.5, and vertex colors disabled, I see:

![screen shot 2019-02-14 at 9 48 49 am](https://user-images.githubusercontent.com/1848368/52806393-bfc4e100-303d-11e9-8602-e81f45eae370.png)

... the edges are  a bit rough, but adjusting the clip threshold should resolve that.

**Comment by soadzoor** [comment]
Oh, you're right, it works that way. So is it the correct behavior? I guess this method only works if I want fully opaque, or fully transparent pixels. But what if I want a semi-transparent look on some parts?

**Comment by donmccurdy** [comment]
If you want semi-transparent pixels, use the `Alpha Blend` mode instead. But note that semi-transparency will be subject to various limitations in realtime engines ([example](https://answers.unity.com/questions/609021/how-to-fix-transparent-rendering-problem.html), [example](https://doc.babylonjs.com/resources/transparency_and_how_meshes_are_rendered#things-to-do-and-not-to-do)) – for cutout/mask shapes like leaves on a tree, `Alpha Clip` will be much better.

This exporter cannot parse nodes like *Mix Shader*, so the alpha mode must be set appropriately.

**Comment by soadzoor** [comment]
Ok, thanks!
