### ISSUE TITLE
Massive increase in file size (and export time) after v3

### ISSUE THREAD

**Issue by Joe-Kerr** [KhronosGroup/glTF-Blender-IO#1946]
**Describe the bug**
Same exact .blend file produces 5x the file size compared to Blender version 3.0.1. The worst part though is the increase in export times!

Unfortunately, I did notice only now. The last files that are ok are dated 24-Mar-2023. 

**To Reproduce**
1. Load .blend file
2. Export gltf

**Expected behavior**
File size does not explode.

**.blend file/ .gltf**
See https://github.com/Joe-Kerr/BlenderGltfFileSize

**Version**
 - OS: Windows 10 (latest)
 - Blender Version 3.6

**Additional context**
Model in .blend file by https://quaternius.com/packs/ultimatemodularcharacters.html

Blender v3 here: https://download.blender.org/release/Blender3.0/

**Comment by julienduroure** [comment]
Hello,

To avoid some mixing issues in viewer, now Blender force keeping an animation for each bone channel, even if the bone channel is not animated.
You can de-activate it at export, if this is what you want, and the file size will be much better:

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/c6aa9a13-4811-4440-9b45-8152bd9723dd)

For your 70 actions to export:
With option enabled: 3.9 Mo on 4.16s
With option disabled: 626 Ko on 0.68s
