### ISSUE TITLE
Custom glTF Extension Export Won't Add Extension to Non Bone (Object Transform Animation) Animation Action

### ISSUE THREAD

**Issue by megumumpkin** [KhronosGroup/glTF-Blender-IO#1950]
**Describe the bug**
Custom glTF extension export won't add extension to non armature animation (object transform animation)  action through `gather_animation_hook(self, gltf2_animation, blender_action, blender_object, export_settings)` code.

**To Reproduce**
1. Create a blender addon with GLTF2 extension hook and add `gather_animation_hook(self, gltf2_animation, blender_action, blender_object, export_settings)` function to said hook like below
```
def gather_animation_hook(self, gltf2_animation, blender_action, blender_object, export_settings):
    print("MURAMASA_ANIMATION_EXPORT_ACT")
    if gltf2_animation.extensions is None:
        gltf2_animation.extensions = {}
    extdata_build = {}
    # Animation properties, e.g. autoplay opt.
    if blender_action.muramasa_action is not None:
        animex_flag_build = 0
        if blender_action.muramasa_action.autoplay is True:
            animex_flag_build = animex_flag_build | 1 << 0
        extdata_build["animation_extra"] = {
            "flags":animex_flag_build,
        }
    gltf2_animation.extensions[glTF_extension_name] = self.Extension(
        name=glTF_extension_name,
        extension=extdata_build,
        required=extension_is_required
    )
```
2. Export model through blender operator within the addon with the glTF2 addon function:
```
bpy.ops.export_scene.gltf(
                    filepath=file_collection+"/model.gltf",
                    export_format='GLTF_SEPARATE',
                    export_keep_originals=True,
                    use_selection=True,

                    # Export animation options for this 
                    export_animations=True,
                    export_animation_mode='NLA_TRACKS',
                    export_optimize_animation_keep_anim_armature=False,
                    export_optimize_animation_keep_anim_object=False,

                    export_skins=True,
                    export_morph=True,
                    export_lights=True,
                    export_attributes=True,
                    export_cameras=True,
                    export_apply=True
                )
```
3. Check the exported .gltf file and seek around the `animations` section of the gltf data in a text editor for the extension hook.

**Expected behavior**
Animation extension would be appended to the animation data on the gltf file.

**Screenshots**
Would provide if requested

**.blend file/ .gltf**
Would provide if requested

**Version**
 - OS: Linux
 - Blender Version: 3.6.0 (hash: c7fc78b81ecb) (Flatpak from Flathub)

**Additional context**
I've made a custom extension for gltf for a specific project, the extension hooks runs fine if I use it to export armature animations which the hook will be added, but something happens that for object transform animation the gltf exporter don't append the extension hook for said animation type.

This is the source code for said addon: [https://github.com/megumumpkin/Muramasa-Blender-SDK](https://github.com/megumumpkin/Muramasa-Blender-SDK)

Related source file is: 
 - `__init__.py`
 - `gltf_ext_assetsmith.py`
 - `operator.py`

**Comment by julienduroure** [comment]
Hello,
There is now different hooks for object type.

> gather_animation_hook

 is kept for compatibility and works for armature, and you can now use, for object:

> animation_gather_object_sampled

and, for shape keys:

> animation_action_sk_sampled

**Comment by megumumpkin** [comment]
For these two new functions: `animation_gather_object_sampled` and `animation_action_sk_sampled`
How can one append an animation extension the same as one that is in `gather_animation_hook`?

Currently there are four parameters for `animation_gather_object_sampled` which is `(self, blender_object, blender_action, export_settings)`.

Before, in `gather_animation_hook` I would use `gltf2_animation` parameter input to append my extension data to that action animation for both skeletal and object animation, how would one approach appending extension data to `animation_gather_object_sampled` function?

**Comment by julienduroure** [comment]
Hello,
You are right, parameter is missing. I fixed it here:
https://github.com/KhronosGroup/glTF-Blender-IO/commit/658e70283eb8fa22560b0bc74749f99b17881a65

I proposed to add this commit to back ported commits for 3.6.x here:
https://projects.blender.org/blender/blender/issues/109399

(Note I rename some hooks too, for consistency).

**Comment by megumumpkin** [comment]
For consistency, shouldn't `animation_action_object_sampled(self, animation, blender_object, blender_action, cache_key, export_settings)`
be this `animation_action_object_sampled(self, gltf2_animation, blender_object, blender_action, cache_key, export_settings)`

**Comment by julienduroure** [comment]
I changed it in documentation.
Note this is parameter of function, so naming doesn't really matter.
