### ISSUE TITLE
Export checkbox that removes underscore for custom attributes during export

### ISSUE THREAD

**Issue by bluediamond87** [KhronosGroup/glTF-Blender-IO#1953]
When exporting custom attributes, I need to remove the “_” to get a game engine to recognize the name of the custom attribute. 

I would like a checkbox to give the option of removing the underscore during export.  A more advance feature would be a “replace” system.  With the target token and the replacement token.  However, this is extra.  Just removing the “_” is enough driven by a checkbox option is enough. 

Investigating a solution that’s step before exporting to remove the name.  That only benefits me though where I think this can be a general problem.

I am looking through the code and I wouldn’t mind giving it a shot but I’m sure you can implement this much more quickly than myself. 

From:
					"attributes":{
						"COLOR_0":0,
						"_CUSTOM":1,
						"POSITION":2,
						"NORMAL":3,
						"TEXCOORD_0":4,
						"TANGENT":5
					},
					
To: 
					"attributes":{
						"COLOR_0":0,
						"CUSTOM":1,
						"POSITION":2,
						"NORMAL":3,
						"TEXCOORD_0":4,
						"TANGENT":5
					},

**Comment by julienduroure** [comment]
Hello,
We can't remove the underscore, because this is a requirement in glTF specification to start any custom attribute with underscore.

See https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes-overview


> Application-specific attribute semantics MUST start with an underscore, e.g., _TEMPERATURE.
