### ISSUE TITLE
Support for KHR_materials_anisotropy import/export

### ISSUE THREAD

**Issue by feuerste** [KhronosGroup/glTF-Blender-IO#1954]
Blender supports anisotropic materials as part of principled BSDF. glTF also has an [anisotropy](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_anisotropy)
 extension now. Are there already any plans to import/export anisotropy? Thanks a lot!

**Comment by julienduroure** [comment]
Hello,
Yes, anisotropy is on TODO list.
- First step is to check if physical models used by Blender & glTF are fully compatible (in current Principled BSDF, and in Principled v2)
- If fully compatible, implementation will be quite straightforward. Else, we need to find the best conversion/approximation to perform.
- Extension is currently RC, and support in this addon will be merged (in case code is ready before) when the extension will be officially ratified

**Comment by feuerste** [comment]
Thanks a lot @julienduroure for your detailed answer! The extension is now complete and ratified, see https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_anisotropy

**Comment by julienduroure** [comment]
Closing this ticket, as Anisotropy I/O is now implemented
