### ISSUE TITLE
gltf2_blender_KHR_materials_specular RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by Realistic3D** [KhronosGroup/glTF-Blender-IO#1957]
*gltf2_blender_KHR_materials_specular.py:225: RuntimeWarning: invalid value encountered in divide
  blender_specular_tint = luminance((normalize(buffers['speccolor']) - 1) / (normalize(buffers['basecolor']) - 1))*

**To Reproduce**
- blender python API to import **GLB/GLTF** models
`ops.import_scene.gltf(filepath=mesh_path)`

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/119076217/581665e7-1422-450c-9b07-aa043490a4c2)

**.glb/.gltf**

**Version**
 - OS: Windows 11
 - Blender Version 3.6
[gear.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12135600/gear.zip)

**Comment by julienduroure** [comment]
Hello,
I can not reproduce with your file, as your gear.gltf file doesn't has any specular data
Are you sure you have provided the right file?

**Comment by julienduroure** [comment]
More than a month without any answer => Closing this ticket.
Don't hesitate to comment again if you have some news information to share
