### ISSUE TITLE
Exporter Determinism

### ISSUE THREAD

**Issue by LPGhatguy** [KhronosGroup/glTF-Blender-IO#1958]
**Is your feature request related to a problem? Please describe.**
We're using the Blender glTF exporter as part of the asset pipeline in a game. We automatically export models as they're saved to glTF via the Blender CLI. We check exported glTF files into our game repository so that only artists and tech artists need Blender installed.

We've noticed that some models, when exported to GLB, don't always end up with the same bits. While we can work around it, a lot of things are easier if the Blender glTF exporter is deterministic.

**Describe the solution you'd like**
I'd like to help track down where nondeterminism might be coming from so that the glTF exporter can produce identical output when given the same `.blend` file.

**Describe alternatives you've considered**
Determinism might not be a priority for the glTF exporter. If so, that's alright. It can be a pain to maintain deterministic output and we can work around it in our pipeline.

**Comment by scurest** [comment]
Is it non-deterministic between two exports on the same machine or between exports on different machines? I am aware that some of Blender's algorithms (normals, vertex colors) differ slightly in the low bits on different machines, see eg [this commit to the OBJ exporter](https://github.com/sobotka/blender/commit/653100cd651d43daa1f814ef49d1f0d7a9a0ee52). I don't know if this "surfaces" in the glTF exporter or if there is a different reason in your case.

**Comment by LPGhatguy** [comment]
> Is it non-deterministic between two exports on the same machine or between exports on different machines?

This is on the same machine. Not every model is nondeterministic. With our exporter settings, this was a model that was nondeterministic for me: [wlof.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12138154/wlof.zip)

**Comment by scurest** [comment]
What's the difference between the two glTFs you get?

**Comment by LPGhatguy** [comment]
What's the best way to communicate those differences?

Here's a ZIP file containing both GLB files exported from `wlof.blend`, a hex dump of each generated with `xxd`, and the output of `diff a.hex b.hex`:
[glb-and-hex-and-diffs.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12207669/glb-and-hex-and-diffs.zip)

**Comment by scurest** [comment]
The JSON parts are identical. The difference is entirely in the TANGENT data. About 0.3% of the floats in the tangent array differ by very small amounts (never more than 1.2e-7).

You should be able to check if that's the only source of non-determinism by disabling export of tangents and seeing if you still get a difference.

AFAIK the exporter just asks Blender to calculate the tangents. Perhaps Blender's algorithm for tangents is non-deterministic. But it might be a good idea for the exporter to round off the tangents for the same reason it rounds normals anyway, which would have the side-effect of masking these tiny differences.

**Comment by julienduroure** [comment]
> But it might be a good idea for the exporter to round off the tangents for the same reason it rounds normals anyway, which would have the side-effect of masking these tiny differences.

Let's do that. Settings as enhancement for now
