### ISSUE TITLE
Research possibility to speed up import of KHR_materials_specular

### ISSUE THREAD

**Issue by timknip** [KhronosGroup/glTF-Blender-IO#1959]
Import of glTFs using the KHR_materials_specular extension is rather slow.

The zip available from https://www.dropbox.com/s/fg0bpd3yy7tnoc0/KHR_materials_specular_slowness.zip?dl=0 contains two GLBs, one with and one without KHR_materials_specular (each ~300MB).

-  file without KHR_materials_specular: 10.34s
-  file with KHR_materials_specular      : 48.55s

I guess this is expected due to the need to create in memory textures etc.
Still, it would be great if the import speed could be optimized if possible.

Specs:
-  Blender 3.6 - c7fc78b81ec
-  Windows 11 Pro
-  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
-  32.0 GB RAM

**Comment by julienduroure** [comment]
Blender 4.0 beta has now a totally new specular model, where conversion is no more needed.
So this bug/perf request is no more relevant.
Closing
