### ISSUE TITLE
Texture from imported object are not exported

### ISSUE THREAD

**Issue by edoaxyz** [KhronosGroup/glTF-Blender-IO#196]
Hello,
I imported in Blender 2.79 an object from a game using an add-on, and everything was showed correctly, even without the add-on, but when I tried to export it as a .gltf or a .glb file only shapes remained showed, while all the texture were missing. For importing them I needed to export the entire object, import it again in Blender, apply the texture and export it and finally the texture was there. Is it possible to export this object without doing all these actions?

[Here you have the zipped .blend file](https://github.com/KhronosGroup/glTF-Blender-IO/files/2716451/untitled.zip)

Thanks in advance

**Comment by julienduroure** [comment]
Seems you blend file is a node tree of Blender internal renderer, that is not supported in gltf addon (only Cycles & Eevee are supported, because of PBR workflow)

Can you please clarify how you apply the texture, and where you are trying to display your exported gltf file generated by our addon?

**Comment by edoaxyz** [comment]
I tried the method that I used last time but it didn't work. Basically what I've done is wrapping the UV mapped texture on every part of the 3d object, but I should have miss some steps this time.

For viewing those gltf file I've used the tools offered by https://gltf-viewer.donmccurdy.com .

**Comment by julienduroure** [comment]
@UX3D-nopper The provided blend file has some blender internal texture, so it can't be generated by importing some gltf file. I know the issue description is not really clear, so I removed any label until we really understand what part of addon is used here.

@edoaxyz Please clarify how you generated the provided blend file, and what part of glTF addon you are using: Import and/or export? If you try to use glTF import, please provide the .glb or .gltf used

**Comment by julienduroure** [comment]
Well, seems this ticket is quite old, and if I understand correclty, there is no bug here. 
Blender Internal render is not supported in glTF exporter addon, and will never supported (Blender Internal Render is no more supported by Blender itself since 2.80).
Closing this ticket.
Don't hesitate to comment if I missunderstood
