### ISSUE TITLE
Specular tint > 0 causes error in gltf export

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#1964]
**Describe the bug**
Setting the specular tint to a number > 0 with a textire input to base color causes an error.  Setting the Specular tint to zero, error disappears.

**To Reproduce**
open blend file - export

**Expected behavior**
A better error, or fix for specular tint (warning not compatible)
**Screenshots**
None
**.blend file/ .gltf**
[specular error.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12324326/specular.error.zip)

**Version**
 - OS: Windows 10
 - Blender Version 3.6.1

**Additional context**
None

**Comment by julienduroure** [comment]
Confirmed
