### ISSUE TITLE
Toggle Button For Baking Diffuse and Alpha Into Single PNG

### ISSUE THREAD

**Issue by Marlowmz** [KhronosGroup/glTF-Blender-IO#1967]
Hi there, I'm working as a TA for an XR company, where we often have to optimize filesize for mobile. One of the most common ways to do that is to create a separate alpha jpg and a separate diffuse jpg, because the compression of the color information can often offset the additional file required(sometimes by a factor of 10x). For example:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/6609245/59179480-8c15-4037-b014-c6b25997143b)
here is the filesize of a diffuse + alpha, 43kb total.

The problem comes when I go to export (blender 3.6.1), regardless of setting, it will always bake my diffuse + alpha to a transparent PNG. Here are my settings:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/6609245/e7a2e979-06ae-4049-9efe-456c816e6b34)

When this happens, the resultant transparent png file in the gltf (when exported as sep bin  + texture) is 364kb, so just under 10x the size of the original files
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/6609245/96369408-4943-4296-bcac-520f1032cbdb). 

This changes file size on a well-optimized model + textures from around 150kb to 1.5mb on this particular model, because there's a lot of color data where I'm missing out on the benefits of texture compression.
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/6609245/ddc9c7ac-a3dd-40b6-9774-fb53ecbf94c9)

My proposed solution is simply to have a toggle for the behavior where it bakes diffuse + alpha down to a transparent png for embedded textures. This makes sense in some scenarios, but ties your hands if you want to do any serious filesize optimization.

Another possibility would be having a 'texture passthrough' option in the dropdown on the material texture compression settings, where it simply uses the files as they are, and throws an error if you are using an incompatible filetype, ie TIFF.

Thanks for your time, I love using the embedded glb spec, and if I could have control over the texture compression, I could do a lot

**Comment by Marlowmz** [comment]
I was looking through the source code to see if there was something I could make a PR for this issue and I saw that there's a 'keep original textures' checkbox for gltf separate. Is there a way to include this same checkbox for the glb embedded?
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/6609245/0489058c-1bb3-452d-a098-a64271df980a)

**Comment by julienduroure** [comment]
Hello,

Having a separate alpha texture is not something that is allowed in glTF specification.
Closing this ticket, as we have to stay on specification :)

Note that the "Keep Original" will not handle it neither, as we can't generate a valid glTF file with this node tree
