### ISSUE TITLE
AssertionError when exporting with KHR_Texture_Trafsform

### ISSUE THREAD

**Issue by DolphinIQ** [KhronosGroup/glTF-Blender-IO#197]
Hello
I have a scene with around 20 meshes in Blender 2.80. Export works with default settings, but using KHR_texture_transform option seems to break it and after almost 10 minutes of lag, returns this error

![image](https://user-images.githubusercontent.com/34486337/50542356-5176ad00-0bbc-11e9-860c-1be1ba72496c.png)

This is my blender file

[blender_room.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2716747/blender_room.zip)

Is this a bug or did I do something wrong? Texture transform extension works for a simpler model, but not with this one, which is bigger.

**Comment by DolphinIQ** [comment]
Sorry for responding so late. Here they are

![redbricks2b-met-rough-gltf-2](https://user-images.githubusercontent.com/34486337/51078825-ecdb4800-16bb-11e9-833a-e5c09bc9163d.png)
![redbricks2b-normal](https://user-images.githubusercontent.com/34486337/51078826-ecdb4800-16bb-11e9-8263-381fd6a32f34.png)
![wood](https://user-images.githubusercontent.com/34486337/51078827-ed73de80-16bb-11e9-849d-a56a67e54b25.jpeg)
![wood](https://user-images.githubusercontent.com/34486337/51078828-ed73de80-16bb-11e9-8d60-d621945844b2.png)
![wood_nrm](https://user-images.githubusercontent.com/34486337/51078830-ed73de80-16bb-11e9-8831-bbf7e8c85b42.png)
![woodbox](https://user-images.githubusercontent.com/34486337/51078831-ed73de80-16bb-11e9-8dd9-e5b63b7a005b.png)
![barreltxt](https://user-images.githubusercontent.com/34486337/51078832-ee0c7500-16bb-11e9-8c7e-7c0b42a13968.png)
![barreltxt_nrm](https://user-images.githubusercontent.com/34486337/51078833-ee0c7500-16bb-11e9-89a3-1a47385e0666.png)
![box_wood_nrm](https://user-images.githubusercontent.com/34486337/51078834-ee0c7500-16bb-11e9-9466-030731966d21.png)
![redbricks2b-albedo](https://user-images.githubusercontent.com/34486337/51078835-ee0c7500-16bb-11e9-9aa5-4757aed752a1.png)

Size of the first file (metallic roughness of bricks) was above the 10MB limit of github so I halved the dimensions to 2048x2048

**Comment by UX3D-schmithuesen** [comment]
Thanks, I was able to reproduce and fix it!
