### ISSUE TITLE
Extension hook `gather_animation_hook` is not called for all animations

### ISSUE THREAD

**Issue by Fell** [KhronosGroup/glTF-Blender-IO#1971]
**Describe the bug**
It appears that since the animation refactor in https://github.com/KhronosGroup/glTF-Blender-IO/pull/1832 the extension hook `gather_animation_hook` is not properly called anymore. This breaks the possibility to add custom data like animation markers.

**To Reproduce**
1. Create an exporter extension using the example (or modify [WSG_animation_markers.py](https://github.com/Fell/WSG_animation_markers/blob/master/WSG_animation_markers.py))
2. Add `gather_animation_hook` like so:
```
def gather_animation_hook(self, gltf2_animation, blender_action, blender_object, export_settings):
    print(">>> gather_animation_hook");
```
3. Load the exporter extension in Blender 3.6.0
4. Create a simple animation with the default cube (or open provided .blend file in [gather_animation_hook.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12409496/gather_animation_hook.zip))
5. Ensure the console is visible by selecting Window → Toggle System Console
6. Export the scene as glTF using default settings
7. Observe that ">>> gather_animation_hook" did not appear in the system console. The function was not called.

**Expected behavior**
`gather_animation_hook` should be called for every `animations` entry in the resulting glTF file, just like it works for `gather_node_hook`.

**.blend file/ .gltf**
[gather_animation_hook.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12409496/gather_animation_hook.zip)

**Version**
 - OS: Windows 10 22H2 (19045.3324)
 - Blender Version 3.6.0

**Additional context**
Extensions which depend on this functionality are [blender_gltf_timeline_markers_addon](https://github.com/repalash/blender_gltf_timeline_markers_addon) and my fork [WSG_animation_markers](https://github.com/Fell/WSG_animation_markers)

I have browsed the code for an alternative way or hook to add extension data to animations, but other than abusing custom properties I couldn't find any.

I found out `gather_animation_hook` is called, but only from `gather_action_armature_sampled`. I think animation hooks should work for all animations, not only armatures.

Thanks in advance.

**Comment by julienduroure** [comment]
Hello,
There is now different hooks for object type.

> gather_animation_hook

is kept for compatibility and works for armature only now.

This is the same than (so for armature only)

> animation_action_armature_sampled

And you can now use, for object:

> animation_gather_object_sampled

and, for shape keys:

> animation_action_sk_sampled
