### ISSUE TITLE
export&import involving two UV maps malfunctions for any materials referencing the second UV map.

### ISSUE THREAD

**Issue by mutantbob** [KhronosGroup/glTF-Blender-IO#1975]
**Describe the bug**
The GLTF export that ships with blender 3.6.2 LTS malfunctions by using the first UV map for all materials, even when the shader nodes refer to the second UV map.

**To Reproduce**
1. export the scene from the attached .blend as a .glb.
2. create a new blend file and import the .glb
3. activate Material Preview shading in the 3D viewport.
4. Grumble about how the materials do not match the original.

**Expected behavior**
The GLTF exporter should create .glb files that reference the correct UV map.

**Screenshots**
original
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1143535/e51f6de4-eb64-4a61-8e67-ba6524cbace4)

after export/import
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1143535/3b63480e-533d-4ed0-9a87-6301ede2b4c4)

**.blend file/ .gltf**
attached

**Version**
 - OS: linux
 - Blender Version 3.6.2

**Additional context**
NA

**Comment by julienduroure** [comment]
Confirmed.
The root cause here is the fact that the same material is link to a mesh, and to another object too.
Investigation in progress to find how to manage it

**Comment by mutantbob** [comment]
In case it helps to understand my target use case:

I have a model with three UV maps.  The first two are used in the materials to determine its appearance.  The third is used for a texture bake.
I then create a spare scene using the source meshes, but use object-specific emission materials to reference the baked textures which are based on the 3rd UV mesh.  That is what I will export to gltf (and eventually into Godot).

What I want is that the exported gltf includes the 3rd UV map which is used by the baked textures.
