### ISSUE TITLE
-90 Degree Rotation Applied when Transform->+Y Up is Selected in Exporter

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [KhronosGroup/glTF-Blender-IO#1985]
**Describe the bug**
I am looking to use glTF as the intermediate format between Blender and a game engine that uses an axis system of +Y Up/-Z Forward. The glTF exporter offers an option to transform the exported scene from Blender's +Z Up system to +Y Up, but I notice that in addition to swapping the axes of vectors (`(X, Y, Z) -> (X, Z, -Y)` in most cases), an ["axis basis change" is applied](https://github.com/KhronosGroup/glTF-Blender-IO/blob/77801afb2fd7ca522463d761bebe2a15cfcaaeb4/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_tree.py#L194) to nodes in the scene hierarchy. What is the reasoning behind doing both the axis swap and the change of basis transform? Is there a way to avoid baking the change of basis into the node transforms?

**To Reproduce**
1. Export a scene with `Transform->+Y Up` checked.
2. Export a scene with `Transform->+Y Up` NOT checked.
3. Notice how the scene that was NOT transformed has no additional transformations applied, while the scene that WAS transformed does.

**Expected behavior**
When `Transform->+Y Up` is selected in the exporter, the scene is converted to a +Y Up system without any additional transformations.

**.blend file/ .gltf**
[This ZIP file](https://github.com/KhronosGroup/glTF-Blender-IO/files/12566647/y_axis_example.zip) contains two *.glb files, one that used the exporter's +Y transform option and one that did not. The *.blend file contains the model used to perform these exports.

**Version**
 - OS: Windows 10
 - Blender Version: 3.2.1

**Comment by julienduroure** [comment]
Hello,

Regarding glTF specification:
> glTF uses a right-handed coordinate system. glTF defines +Y as up, +Z as forward, and -X as right; the front of a glTF asset faces +Z.

See https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units

Blender is Right-handed Zup, -Yup front
In addition, Bone has some special axis system, where Y is along the bone.

So, all this conversions are needed to change from Blender axis to glTF axis

PS: Not using the option +Yup does generate not valid glTF file. You should probably delete it from UI.

**Comment by Sage-of-Mirrors** [comment]
I see. My target system is also right-handed, though -Z is forward instead of +Z. Is it mathematically possible to convert the node transforms so that they don't have any "additional" modifications? For example, in one of my testing models, the root joint should have no rotation; but when I export the model to glTF, the root joint gains a rotation of -90 degrees. That's the origin of this issue's title.

**Comment by julienduroure** [comment]
This "additional modifications", as you named them, are needed to get valid glTF file exported, with correct transforms for any object / joint-bone.
So, I am not sure there is something we can do here, in the glTF exporter.
Closing this ticket, as I don't think there is some issue here.

Some thoughts about your investigation : As TRS are stored in local coordinate in glTF files, if you decided to change the root joint, you will have to change all children TRS of that root joint, and corresponding IBM.
