### ISSUE TITLE
Python script to get glTF mesh index and primitive index of an object inside Blender

### ISSUE THREAD

**Issue by Trolli991** [KhronosGroup/glTF-Blender-IO#1988]
Hey everyone, I'm trying to write an addon to set dynamic and static hotspots for google model viewer directly in blender. Most of it works already, but for dynamic hotspots I need the glTF Mesh Index and Primitive Index of the object, the hotspot should be located on.

Is there a way to output the glTF mesh and primitive index of an object through python inside blender?

**Comment by julienduroure** [comment]
Hello,
Not sure there is a way to be sure at 100% of the index of object & primitive.
Could you use the name of object.
For primitive, meshes are split by material, so you can use the material name to get the right primitive?

**Comment by Trolli991** [comment]
Wow, thanks a million that actually helped a lot. I have never understood how the primitives are created. I reverse engineered the glTF importer/exporter to some extent to figure this out and always ended up with something to do with material indexing. I always thought I had made a mistake, but never got the idea that this is where the primitives come from.

I have now landed on a new problem. I hope it's okay to continue using this post. 

Let's say I export a Suzanne mesh from Blender which is half covered with one material and half covered with another material (Red and Blue in this example). Now if I place two hotspots in the Google Model Viewer Editor, one on the red half and one on the blue, I get different indexes for the face the hotspot is placed on than I do in Blender. 

Can you explain to me how this occurs?
Are mesh primitives treated as independent meshes with their own way of counting indexes?

![different_vertexpoints_primitive](https://github.com/KhronosGroup/glTF-Blender-IO/assets/46992900/208ae975-810d-4fc5-947c-0993c0c115e8)
