### ISSUE TITLE
Unapplied Subdivision Modifier + Secondary UV Map (AO) + Mesh>Apply Modifiers = Broken Secondary UV Map

### ISSUE THREAD

**Issue by hedgehog90** [KhronosGroup/glTF-Blender-IO#1991]
My AO UV map is getting distorted when I let the exporter apply the modifiers.
If I apply the modifiers manually before exporting then I don't get this issue.
In the following sample I am using just a Subdivision Modifier, but I would assume this problem is present with other modifiers.

I'm using the latest version of Blender and the GLTF exporter supplied within.

Blend:
[elephant-blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12587286/elephant-blend.zip)

Exported GLB with modifiers applied on export:
[elephant-glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12587287/elephant-glb.zip)
![chrome_TCf6qHR4bo](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5526342/19f6dc3f-6402-4ea0-8b52-aa01341cdb26)

Exported GLB with modifiers applied manually before export:
[elephant-applied.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12587441/elephant-applied.zip)
![chrome_vSAcQf7Izj](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5526342/258f2220-1a34-48b4-902a-0acc9b81553d)

**Comment by julienduroure** [comment]
Can you please provide the textures? They are not packed into the blend file, and it will help investigating to have them

**Comment by julienduroure** [comment]
Ok, so I tested with some blank images.
I can confirm the bug, but good news, it will be solved by #1989 that should land in 4.0
