### ISSUE TITLE
Exporting in NLA tracks mode modifies animation

### ISSUE THREAD

**Issue by jrjdavidson** [KhronosGroup/glTF-Blender-IO#1997]
**Describe the bug**
Exporting an animation in `NLA track` mode affects the animation in blender. Once the file has been exported, you are unable to play the animation in blender any longer.

**To Reproduce**
1. Load spray bottle.blend
2. go to export as gltf
3. set animation mode to `NLA Tracks` and export file
4. try and play the animation in blender - it doesn't play anymore.

**Expected behavior**
I would expect that the exporter would not modify the blender file.

**.blend file/ .gltf**
[spray bottle.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12602404/spray.bottle.zip)

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.82, 2.83, or build date]

**Additional context**
Blender 3.6.2 on windows 10

**Comment by julienduroure** [comment]
Confirmed.
The "mute" property of NLA track is not restored after export
Enable it again to get your animation back.

![Capture d’écran du 2023-09-14 03-43-57](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/a8424d66-49bd-4b26-bb30-40d273554df5)
