### ISSUE TITLE
Visible Only = true,  not working for invisible objects used in a Boolean modifier in 4.0 main branch

### ISSUE THREAD

**Issue by hedgehog90** [KhronosGroup/glTF-Blender-IO#1999]
I use cubes with boolean modifiers to non-destructively cut holes in meshes. I make sure to set the cubes to be hidden and set the relevant option in the gltf exporter to prevent them from being exported.
In previous versions it correctly applied the boolean modifier but did not export the invisible cube.
However in the latest version it's including the invisible cube in the export:

[bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12609144/bug.zip)

EDIT: After some further investigation I think the issue is specifically when a hidden object is parented to an object selected for export, the hidden object is exported no matter what.

**Comment by julienduroure** [comment]
[untitled.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12610398/untitled.blend.zip)

>  when a hidden object is parented to an object selected for export

Not exactly. >>> When a hidden object is parented to a linked collection selected for export

**Comment by julienduroure** [comment]
Hello,
Can you please open another ticket for this case, with your test case?
Thanks

**Comment by hedgehog90** [comment]
Done:
https://github.com/KhronosGroup/glTF-Blender-IO/issues/2011
