### ISSUE TITLE
New folder structure

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#2]
I think the folder structure proposed in README.md looks fairly close to right. How about renaming "generic" to "io"? I think that would more clearly communicate that it is the serialization/deserialization code, and can be used independently. Then:

- io_scene_gltf2
  - blender
    - common
    - export
    - import
  - io
    - ...

I leave the subfolders under `io/` blank because I think feature-related classes/files (similar to https://github.com/julienduroure/gltf2-blender-importer/tree/master/io_scene_gltf2_importer) may be wanted, but I don't have my mind made up on this.

**Comment by UX3D-nopper** [comment]
Good point, fixed here #519b11a
