### ISSUE TITLE
T60012: Incorrect metallicRoughnessTexture colour channels when exporting glTF

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#200]
Issue from blender tracker: https://developer.blender.org/T60012

**Comment by UX3D-nopper** [comment]
Should fix it: https://github.com/KhronosGroup/glTF-Blender-IO/commit/3b02643cb4700efd0054e8f004065cb840dc71c0

**Comment by julienduroure** [comment]
Now merge with blender repo
