### ISSUE TITLE
Documentation: gather import animation hooks

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/glTF-Blender-IO#2010]
Hello, it seems like the documentation of these two functions is not up to date 

https://github.com/KhronosGroup/glTF-Blender-IO/tree/main/example-addons/example_gltf_importer_extension

```
gather_import_animation_before_hook(self, gltf, anim_idx, gltf)
gather_import_animation_after_hook(self, gltf, anim_idx, track_name, gltf)
```

https://github.com/KhronosGroup/glTF-Blender-IO/blob/a4103305c47b500db76c76a9dd8b4bd92c336164/addons/io_scene_gltf2/blender/imp/gltf2_blender_animation.py#L35

and should be changed to
```
def gather_import_animation_before_hook(self, anim_idx, gltf);
def gather_import_animation_after_hook(self, anim_idx, track_name, gltf):
```

**Comment by julienduroure** [comment]
Thanks to pointing it out!
Fixed :)
