### ISSUE TITLE
Exporting Draco compressed normalized attributes results in a normalized flag of false in the Draco payload

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF-Blender-IO#2013]
**Describe the bug**
When exporting normalized vertex attributes with Draco compression turned on, the resulting Draco payload has `normalized` flag hard-coded to false. The accessor in the glTF JSON is written with the correct `normalized: true`. This will cause issues in glTF loaders that don't use the glTF JSON to decode the Draco payload.

**To Reproduce**
1. Create/load an asset with vertex colors or any other normalized vertex attribute.
2. Export to glTF with the `Compression` flag turned on in the `Data` dropdown.
    <img width="106" alt="image" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/19158740/2b89f5cc-3e1a-4a95-9896-e199aad0a5a5">
4. Export the asset.

**Expected behavior**
Load the exported asset in [the Babylon.js sandbox](https://sandbox.babylonjs.com/) and make sure the console log does not have:
> Normalized flag from Draco data (false) does not match normalized flag from glTF accessor (true). Using flag from glTF accessor.

**Screenshots**
N/A

**.blend file/ .gltf**
N/A

**Version**
 - OS: N/A
 - Blender Version: N/A

**Additional context**
I am the maintainer of the glTF loader in Babylon.js and I've recently updated the code to use the Draco attribute information directly from Draco's APIs, but the APIs are returning `normalized` as false when it should be true for a number of assets. Because of this issue, I have updated the Babylon.js code to log a warning to the console if there is a mismatch of the normalized flag between glTF accessor and Draco payload. If you take the resulting glTF exported from Blender and load it in Babylon.js sandbox, it will log the warning from above.

I have also traced the code to [the following line](https://github.com/ux3d/blender_extern_draco/blob/main/src/encoder.cpp#L235C85-L235C90
) which appears to have hard-coded the `normalized` flag sent to Draco's API. I didn't debug the code, so I'm not 100% sure this is the culprit.
```c++
attribute.Init(semantics, &*buffer, componentCount, getDataType(componentType), false, stride, 0);
```

Note that three.js is able to load the asset because the glTF loader in three.js always uses the glTF accessor information instead of what's in the Draco payload.

**Comment by julienduroure** [comment]
This bug needs first changes from Draco library.
See https://github.com/google/draco/issues/1023

**Comment by bghgary** [comment]
@julienduroure From my tracing of the code, it seems Blender is calling directly into the [Draco attributes' API](https://github.com/ux3d/blender_extern_draco/blob/main/src/encoder.cpp#L235C85-L235C90) as I mentioned in the additional context, assuming I traced it correctly. The issue for Draco is just for the emscripten path which I don't think is used here. Am I missing something?

**Comment by julienduroure** [comment]
Oh, my bad. Seems I mixed up the code or read the wrong. You're right
