### ISSUE TITLE
Exception on export with "KeyError: ..."

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#2020]
**Describe the bug**
When exporting as glTF, the following exception is logged and no file is exported:
<img width="914" alt="image" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/3de3e7f5-caba-421e-853a-e29b2d362aac">

**To Reproduce**
1. Download attached file
2. Open in Blender
3. Export as GLB (settings don't matter)

**Expected behavior**
When opening the attached file and exporting a GLB (independent of the chosen export settings) there's an exception; looks like something fails when filtering the scene down for export.

**.blend file/ .gltf**
[exportBug.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/12778165/exportBug.blend.zip)

**Version**
 - OS: latest MacOS
 - Blender Version 3.6.4

**Comment by marwie** [comment]
I think this has to do with our addon filtering some objects that might be animated in the tree - it doesnt happen without our addon in my test

**Comment by marwie** [comment]
Changed the code to the following and using the exporter to handle the filtering :)

```py
def gather_tree_filter_tag_hook(self, tree, export_settings):
    for key in tree.nodes:
        value = tree.nodes[key]
        blender_object = value.blender_object
        if blender_object and blender_object.hide_render:
            visibleInViewport = objectIsVisibleInViewport(blender_object)
            if not visibleInViewport:
                debug_log("Filtering out object because it's not visible in the viewport and render", blender_object.name)
                value.keep_tag = False
                pass
    pass
```

the issue can be closed :)

**Comment by hybridherbst** [comment]
I think one follow-up question would be "is `value.keep_tag = False` the right way to do this"
