### ISSUE TITLE
Remove "Embedded" export option for Blender 4.0.0

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#2025]
There are three export formats: Binary, Separate, and "Embedded."  The "embedded" form actually base64-encodes all binary assets onto single lines of text that can stretch millions of characters long.  This makes it the least efficient form with the most warnings and caveats upon it.

Large version numbers like 4.0.0 are usually a great place for a breaking change.  Let's remove "embedded" from the export options (but still allow import).

There are still [tools](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode) out there that can convert to and from the old embedded form, in case someone still needs it.

**Comment by julienduroure** [comment]
Done!

**Comment by donmccurdy** [comment]
Thank you for this change! I think it's the right one, and removes what has been a footgun for users publishing to the web or any filesize-sensitive application. Many users don't understand the limitations associated with "glTF Embedded" internal binary storage, and (IMHO) they should not have to.

If any users need help getting data into the old embedded form for whatever reason, I'm happy to discuss ways to do that, and the tradeoffs involved.

**Comment by julienduroure** [comment]
If you are reading this ticket and want to tell us why embedded is important in your pipeline/workflow, please comment this ticket: https://github.com/KhronosGroup/glTF-Blender-IO/issues/2148
