### ISSUE TITLE
v4.0 Second Basecolor texture node - Not be part of pbrMetallicRoughness - how to

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#2034]
This is more of a question: v4.0+ has added a "feature" that if you have a second BaseColor texture node combined with and primary BaseColor texture node.  The second Basecolor texture node becomes part of the pbrMetallicRoughness.  The node structure for the primary BaseColor texture node is empty.  What is happening is the second texture node is "found" as it is ultimately connected to the BaseColor input to the BSDF,  and the code places it into the pbrMetallicRoughness.  The ASOBO extension already puts this texture in it's correct place in the extensions.  So I now have a duplicate texture reference - one in the extension and one in the Khronos pbrMetallicRoughness section.

I am trying to figure out what hook to use to remove the texture node in the from pbrMetallicRoughness. The hooks I have tried have a blank Texture_info data.  I thought I could find data there to remove.

The resultant gltf files compared with winmerge have ver 3.3 and 3.6 without the BaseColor tetxure in the pbrMetallicRoughness, while the ver 4 gltf has the Basecolor.

I was hoping that this could work like normal and ORM does, as there is also second textures in my blend file for those and they do NOT get added and remain part of the ASOBO extension json node structure.

![DA40CGDFQ_2023 10 26_10h8m37s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/07d5f270-329f-4b1f-9c8b-f9b6393c5b6a)

![DA40CGDFQ_2023 10 26_10h9m2s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/83b590e2-2af3-4f6d-a698-9c7a5d083d6b)

![DA40CGDFQ_2023 10 26_10h23m53s](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19254353/14507afe-377e-46ef-9eef-37d6b77faae5)

[test_windshield.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13178833/test_windshield.zip)

with packed textures

[test40windshield.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13178896/test40windshield.zip)

**Comment by ronh991** [comment]
Additional information on this issue.  I found that the alpha link on the Detail BaseColor node was the cause of the node being "found" and then placed into the main BaseColor PBRMetallicRoghness section.  Removing the link to alpha helps as a workaround.  However this means that the detail BaseCOlor for ASOBO extension cannot have an alpha.

**Comment by julienduroure** [comment]
What hook did check already? is it _gather_material_hook_ ?

**Comment by ronh991** [comment]
I tried the following
`# blender 4.0 issue with detail textures added twice once correct and once as a regular basecolor texture
    # def gather_texture_info_hook(self, gltf2_io, blender_shader_sockets, export_settings):
        # print("gather_texture_info_hook - Started with ", blender_shader_sockets)
        # #print("exportsettings", export_settings)
        # print("io", gltf2_io.extensions, gltf2_io.extras, gltf2_io.index, gltf2_io.tex_coord)
        # #if self.properties.enabled:
            # #MSFSMaterial.export(gltf2_material, blender_material, export_settings)
        # print("gather_texture_info_hook - Done")

    # def gather_material_pbr_metallic_roughness_hook(self, gltf2_material, blender_material, orm_texture, export_settings):
        # print("gather_material_pbr_metallic_roughness_hook - Started with ", gltf2_material.base_color_texture)
        # #print("exportsettings", export_settings)
        # print("blender_material", blender_material, blender_material.msfs_base_color_texture, blender_material.msfs_detail_color_texture)
        # #if self.properties.enabled:
            # #MSFSMaterial.export(gltf2_material, blender_material, export_settings)
        # print("gather_material_pbr_metallic_roughness_hook - Done")

    # def gather_import_texture_before_hook(gltf, pytexture, mh, tex_info, location, label, color_socket, alpha_socket, is_data):
        # print("gather_import_texture_before_hook - Started with ", gltf)
        # #print("exportsettings", export_settings)
        # print("arg material", pytexture, mh, tex_info, location, label, color_socket, alpha_socket, is_data)
        # #if self.properties.enabled:
            # #MSFSMaterial.export(gltf2_material, blender_material, export_settings)
        # print("gather_import_texture_before_hook - Done")

    # def gather_import_texture_after_hook(gltf, pytexture, mh, tex_info, location, label, color_socket, alpha_socket, is_data):
        # print("gather_import_texture_after_hook - Started with ", gltf)
        # #print("exportsettings", export_settings)
        # print("arg material", pytexture, mh, tex_info, location, label, color_socket, alpha_socket, is_data)
        # #if self.properties.enabled:
            # #MSFSMaterial.export(gltf2_material, blender_material, export_settings)
        # print("gather_import_texture_after_hook - Done")

    # def gather_texture_hook(self, texture, blender_shader_sockets, export_settings):
        # print("gather_texture_hook - Started with ", blender_shader_sockets)
        # #print("exportsettings", export_settings)
        # print("texture", texture.name, texture.sampler, texture.extras, texture.source.name)
        # #if self.properties.enabled:
            # #MSFSMaterial.export(gltf2_material, blender_material, export_settings)
        # print("gather_texture_hook - Done")
`

I did not see gather_material_hook

**Comment by ronh991** [comment]
If I add the following code to the gather_material_hook, the texture info object contains extensions, extras, index and tex_coord.  

`
    def gather_material_hook(self, gltf2_material, blender_material, export_settings):
        print("gather_material_hook - Started with gltf2_material", gltf2_material, gltf2_material.pbr_metallic_roughness, gltf2_material.pbr_metallic_roughness.base_color_texture, gltf2_material.pbr_metallic_roughness.base_color_texture)
        #print("exportsettings", export_settings)
        print("gather_material_hook - blender material", blender_material, blender_material.msfs_detail_color_texture)
        if self.properties.enabled:
            MSFSMaterial.export(gltf2_material, blender_material, export_settings)
        print("gather_material_hook - Done")
`

this results in

`16:38:10 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
gather_material_hook - Started with gltf2_material <io_scene_gltf2.io.com.gltf2_io.Material object at 0x0000017913AE38B0> <io_scene_gltf2.io.com.gltf2_io.MaterialPBRMetallicRoughness object at 0x0000017913AE39D0> <io_scene_gltf2.io.com.gltf2_io.TextureInfo object at 0x0000017913AE0910> None
gather_material_hook - blender material <bpy_struct, Material("WINDSHIELD BUCKER") at 0x0000017907E2DF08> <bpy_struct, Image("GLASS_DetailMap01_mask - Copy.png") at 0x0000017907DB0108>
AsoboMaterialCommon - Started with  <io_scene_gltf2.io.com.gltf2_io.Material object at 0x0000017913AE38B0>
AsoboMaterialCommon - Done blender_material <bpy_struct, Material("WINDSHIELD BUCKER") at 0x0000017907E2DF08> None <bpy_struct, Image("GLASS_DetailMap01_mask - Copy.png") at 0x0000017907DB0108>
MSFSMaterial - texture_info (<io_scene_gltf2.io.com.gltf2_io.TextureInfo object at 0x0000017913AE1600>, {'type': 'Active'}, None)
gather_material_hook - Done
1`

Where/How do I get the BaseColor slot so I can remove it?
If i remove the alpha link then the texture does not show as a BaseColor.  This is strange , so why having a Color basecolor link back to the BSDF no do the same, and "find" my detail base color node?

**Comment by ronh991** [comment]
ok I did not think to look for texture data in the "index" field of Texture_Info. So I added

`        print("gather_material_hook - gltf2_material.index", gltf2_material.pbr_metallic_roughness.base_color_texture.index.name, gltf2_material.pbr_metallic_roughness.base_color_texture.index.source, gltf2_material.pbr_metallic_roughness.base_color_texture.index.sampler)
`
`gather_material_hook - gltf2_material.index None <io_scene_gltf2.io.com.gltf2_io.Image object at 0x0000028553F5FF10> <io_scene_gltf2.io.com.gltf2_io.Sampler object at 0x000002854A78DA20>
`

and I get a texture image.  How do I delete this reference? do I remove the sampler, or all the fields?

**Comment by julienduroure** [comment]
You can set the entire texture_info to None
> gltf2_material.pbr_metallic_roughness.base_color_texture = None

**Comment by ronh991** [comment]
That helped, thanks
close issue
