### ISSUE TITLE
Indices accessor contains primitive restart value (65535)

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#204]
Managed to create a file that throws this validation error: 

> Indices accessor contains primitive restart value (65535) at index 78974.

Maybe off-by-one on a check somewhere?

[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2726218/Archive.zip)

**Comment by lexaknyazev** [comment]
Looks like #56 got lost during refacroring. Compare:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/711779b04937deb20225a12c5360639801c9f046/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py#L75-L82

https://github.com/KhronosGroup/glTF-Blender-IO/blob/8b588c7ff95810cc7d57450872db6c527e6887cc/addons/io_scene_gltf2/blender/exp/gltf2_blender_generate.py#L1137-L1145

**Comment by emackey** [comment]
I also see a 16-bit limit here, that might need to be decreased by 1 as well:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/7b987b1b058bf7b3bafc616c13a9b428b02d3c0b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py#L978
