### ISSUE TITLE
Imported images should be set to "channel packed" alpha

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#2046]
**Describe the bug**
Seems "straight" alpha in Blender does something different than it should, the mode that should be used instead is "channel packed".

**To Reproduce**
1. Download 
[ChannelPackedImage.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13267186/ChannelPackedImage.zip)
2. Import into Blender
3. Enable viewport shading
4. See that it's black (incorrect)
5. In Shading, switch image alpha to "channel packed"
6. Cat's back

**Expected behavior**

**Screenshots**
| After Import | Manually switching alpha to "channel packed" |
| - | - |
| <img width="627" alt="image" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/d92b4e3a-8773-445c-91ed-ba1d453f5dfb"> | <img width="860" alt="image" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/a90c2c0f-1f7d-46d7-84b5-e0db6cb1fec5"> |

**.blend file/ .gltf**
[ChannelPackedImage.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13267186/ChannelPackedImage.zip)

**Comment by julienduroure** [comment]
Confirm this behavior. 
I will check with Blender developer why and best practices about this option

**Comment by scurest** [comment]
Cf https://blenderartists.org/t/textures-and-alpha-modes-oh-my/1161715.

AFAICT, when testing with a PNG file from disk...

* "Straight" means when used in a shader node...
    * In Eevee, the color socket emits premultipled color if the alpha socket is not connected (indirectly) to the output, and non-premultipled color if it is. (I had no idea this could happen. I reeeeeeally hate the fact that the value of a socket can be affected by the link topology.)
    * In Cycles, the color socket always emits premultiplied color.
* "Channel Packed" means when used in a shader node, the color socket always emits non-premultipled color.

I think hybridherbst is right, we should switch to "Channel Packed" for everything.

**Comment by scurest** [comment]
```diff
diff --git a/addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py b/addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py
index de42061d..0be9d2ac 100644
--- a/addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py
+++ b/addons/io_scene_gltf2/blender/imp/gltf2_blender_image.py
@@ -44,6 +44,7 @@ class BlenderImage():
             blender_image = create_from_data(gltf, img_idx)
 
         if blender_image:
+            blender_image.alpha_mode = 'CHANNEL_PACKED'
             img.blender_image_name = blender_image.name
 
         import_user_extensions('gather_import_image_after_hook', gltf, img, blender_image)
```

**Comment by julienduroure** [comment]
Let's use channel_packed, but let's also keep an eye on it, and I should ask Blender dev how we should manage it

**Comment by scurest** [comment]
Btw I was afraid the "Straight" behavior would happen with vertex colors too, but fortunately it has the "Channel Packed" behavior, so we don't have to worry about that.
