### ISSUE TITLE
Exception on export when adding joints to generated tree

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#2049]
**Describe the bug**
I was trying the "Sapling Tree Gen" addon which ships with Blender. It basically generates meshes with armatures for tree + leaves and animations for them.

I was able to export the leaves, but not the tree itself;
when enabling "Apply Modifiers" there's an export exception from glTF-Blender-IO.

**To Reproduce**
1. Download [animatedTree.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13308069/animatedTree.zip)
2. Open the file
3. Export as glTF with "Apply Modifiers" on

Alternatively, from scratch:
- in Preferences > Add-ons, enable "Add Curve: Sapling Tree Gen"
- Add > Curve > Sapling Tree
- in the creation popup, enable "Use Armature" and/or "Make Mesh"
- (optional) enable animations in the Animation section
- try to export

**Expected behavior**
Both leaves and tree root are exported and animate
Actual: 
- with "Apply Modifiers" == false: only the leaves (when selected) animate
- with "Apply Modifiers" == true: no export, exception

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/3c40e3c8-344a-4d5b-b81f-2d658803c7e4)

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/b5d2b615-e92b-49af-8cf6-98d314be0bc7)

**.blend file/ .gltf**
[animatedTree.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13308069/animatedTree.zip)

**Version**
 - OS: Windows
 - Blender Version: 4.1 / 4.0

**Comment by hybridherbst** [comment]
I'm not getting an exception when I use these settings in the tree generator:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/16b8dcb4-cd65-46f7-a8e3-eb29f60909f7)
and have "Apply Modifiers" on true
but the resulting file has bone animations but no skinning (the actual tree doesn't move, only the bones move)
(motion trajectories in color)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/87362e72-5ce2-462b-8eb7-1255d4fdc768)

So maybe there's two bugs here
1. the exception, wherever it comes from
2. skinned curves are correctly converted to geometry but don't retain their armature modifiers
  ![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/b11e7c3d-4aa2-425f-97e7-e18afc978eeb)

**Comment by julienduroure** [comment]
Can confirm.
Not sure we managed skinned data on curves yet, that should explain the crash. Investigation in progress.
