### ISSUE TITLE
Export ignores Image quality setting

### ISSUE THREAD

**Issue by dasfrodo** [KhronosGroup/glTF-Blender-IO#2055]
**Describe the bug**
The new gltf exporter in Blender 4.0 seems to ignore the Image quality setting. I get the same filesize and (visual) quality every time. It doesn't matter if the Image quality is set to 10, 90, 100, or anything else. However, the documentation suggests that it should influence the quality. Quote: 

> Image Quality: When exporting jpeg or WebP files, the quality of the exported file.

**To Reproduce**
1. Open any Blender file that will contain textures when exported via glTF Expoter.
2. Export via glTF Exporter with Data > Material > Image set to "JPEG" or "WebP Format" and chose any "Image quality"

**Expected behavior**
Visual quality of the textures and general file size change, depending on chosen "Image quality"

**Screenshots**
![blender_TFHMNDMoGB](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7696189/78785806-ffdf-4b80-9a7b-6a84199a47e5)
![vivaldi_knNuJSrmUx](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7696189/437898a0-e3f7-4fa2-ad8c-14679091d267)
![vivaldi_GA7Ap4QpXI](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7696189/775b567e-f2d6-484e-a366-879f7cec77db)

**.blend file/ .gltf**
[glbtest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13366342/glbtest.zip)

**Version**
 - OS: Windows 10 Pro
 - Blender Version 4.0.0

**Comment by julienduroure** [comment]
Confirmed.
Fixed here: 31166927e910be19040a819de2da2591ae060ef7

I will propose it for 4.0.x corrective release.

**Comment by julienduroure** [comment]
The fix will be available in 4.0.1
(Planned for tomorrow)
