### ISSUE TITLE
Importing Animated GLTF from Houdini Fails in Blender Versions Newer Than 3.2.2

### ISSUE THREAD

**Issue by FabeeoBreen** [KhronosGroup/glTF-Blender-IO#2058]
**Describe the bug**
When attempting to import an animated GLTF file exported from Houdini into Blender, the import fails in any version newer than 3.2.2.
I've encountered an issue where newer versions of Blender are unable to import packed animated geometry from GLTF files. This functionality works as expected in Blender 3.2.2, but fails in subsequent versions.

**To Reproduce**
1. Export an animated GLTF file from Houdini.
2. Open Blender (version newer than 3.2.2).
3. Attempt to import the exported GLTF file.
4. Observe the failure/error.

**Expected behavior**
The animated GLTF file should import successfully without errors, as it does in Blender version 3.2.2

**Screenshots**
![Blender_3 6 4_error](https://github.com/KhronosGroup/glTF-Blender-IO/assets/125922667/90ca992e-131d-4577-a2ec-db5642cdb543)

**.blend file/ .gltf**
[Bubbles_sim_GLTF.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13394725/Bubbles_sim_GLTF.zip)

**Version**
 - OS: Windows
 - Issue observed in Blender versions newer than 3.2.2

**Additional context**
- The same GLTF files import correctly in Blender 3.2.2.

Thank you for looking into this issue. I hope this information helps in diagnosing and resolving the problem.

**Comment by julienduroure** [comment]
Hello,
Seems the glTF file generated by Houdini is not a valid glTF file.
You can check this here: https://github.khronos.org/glTF-Validator/

- Custom attribute _numnonpacked uses a non valid type
- Some animations have negative time frame

**Comment by FabeeoBreen** [comment]
Hello @julienduroure !
It looks like any glTF animation exported with Houdini glTF exporter fails the check with the validator.
Houdini glTF exporter is built in (https://www.sidefx.com/docs/houdini/nodes/out/gltf.html)

The file plays correctly with windows 3D viewer, online glTF viewers and in Blender, untill version 3.2.2.
- Only way i found to forward this simulations to blender > 3.2.2,  is to re-export the glTF or glb from blender 3.2.2

Thanks for your reply!

**Comment by julienduroure** [comment]
I will add checks to avoid any crash during import

**Comment by FabeeoBreen** [comment]
Thanks a lot @julienduroure !!
