### ISSUE TITLE
Blender 4.0.1 - Attrubute Vertex Color

### ISSUE THREAD

**Issue by Mikez2015** [KhronosGroup/glTF-Blender-IO#2063]
Hello.

Attributes - vertex colors - are not saved correctly, when export file.
In Blender 2.83.10 everything works correctly.

Sorry for google translate.

**Comment by julienduroure** [comment]
As requested in template, please provide a .blend file, and explain what is broken

**Comment by Mikez2015** [comment]
1. I import glb file in Blender 4.0.1. You can see that the import is happening correctly, the colors of the vertices are correct:

![issue_1](https://github.com/KhronosGroup/glTF-Blender-IO/assets/10583925/1ae6d603-49ad-4d4e-ae39-4e7ecd507b11)

2. I export glb file (with include attributes).
3. Importing this file again and I see that the colors of the vertexes are lost:

![issue_2](https://github.com/KhronosGroup/glTF-Blender-IO/assets/10583925/a81bc33e-2561-4e07-87f8-33fd2c293cc4)

I attach both files in archive.
[both_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13433306/both_glb.zip)

**Comment by julienduroure** [comment]
@emackey 
We may forgot one case about the new way of exporting Vertex Color: When the mesh don't have any material.
In that case, there is no use of VertexColor in node tree (because no node tree, because no material). We don't export VC.

Proposed solution: If a primitive don't have any material, but some VC, export the rendered VC as COLOR_0

**Comment by emackey** [comment]
@julienduroure Yes, good idea.

@Mikez2015 Thanks for letting us know!

**Comment by beobf** [comment]
Sorry a related question: Vertex Color is not exported when there is some materials with texture even when Data > Mesh > Attributes is checked.
Is it possible to export both VC and texture?

**Comment by julienduroure** [comment]
The behavior will change (again) for 4.2, but Yes, this will be possible
See #2233 and #2240
