### ISSUE TITLE
Plugin not loadable with blender 4.0

### ISSUE THREAD

**Issue by CDaut** [KhronosGroup/glTF-Blender-IO#2064]
**Describe the bug**
The error message below occurs when attempting to enable the PlugIn with blender 4.0

**To Reproduce**
1. Disable the PlugIn (Edit > Preferences...)
2. Close Blender 4.0
3. Open Blender
4. Enable the PlugIn 
5. A PopUp wit the error message is displayed

**Expected behavior**
The PlugIn is enabled and available

**Error Message**
```
Exception in module register(): /usr/share/blender/4.0/scripts/addons/io_scene_gltf2/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/usr/share/blender/4.0/scripts/addons/io_scene_gltf2/__init__.py", line 1661, in register
    blender_ui.register()
  File "/usr/share/blender/4.0/scripts/addons/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 521, in register
    bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT'
```

**Version**
 - OS: Arch Linux x86, 64 bit
 - Blender Version 4.0 stable (newest from Package manager)

**Comment by julienduroure** [comment]
Hello.
I can not reproduce.
The string bpy.types.NODE_MT_category_SH_NEW_OUTPUT is not part of our source code,
As you can see here: https://github.com/KhronosGroup/glTF-Blender-IO/blob/230985d4aebc5ff82dc250cb42046a75c462eed8/addons/io_scene_gltf2/blender/com/gltf2_blender_ui.py#L608

I suggest you to contact the Arch maintainer of the package
