### ISSUE TITLE
io_scene_gltf2 in Blender 4.0.1 error

### ISSUE THREAD

**Issue by native-engine** [KhronosGroup/glTF-Blender-IO#2067]
I can't enable the glTF 2.0 import-export plugin in Blender 4.0.1
![Screenshot_20231129_024248](https://github.com/KhronosGroup/glTF-Blender-IO/assets/18296438/6cfcf7d5-f5c6-4d0c-ab05-3fcda1fd31fe)

**Comment by julienduroure** [comment]
Hello,
I guess you are an Arch user. 
Please contact the package maintainer, as it seems the package didn't update submodules correctly.
This error doesn't occur on official Blender download

**Comment by native-engine** [comment]
Yes, I'm using Manjaro Linux, how to write to this builder I don't know, I temporarily put a Blender build from the Flatpak repository, thanks for the tip.
