### ISSUE TITLE
Error when exporting vertex coordinates

### ISSUE THREAD

**Issue by native-engine** [KhronosGroup/glTF-Blender-IO#2069]
When exporting a model of type "Plane" GL-coordinates should be: (0.0, 0.0, 0.0) - (1.0, 1.0, 0.0), but the following are obtained (vertex coordinates are identical to these):

```
"max":[
   1,
   1,
   2.1855694143368964e-08   //   There should be a zero here
],
"min":[
   0,
   0,
   -2.1855694143368964e-08   //   There should be a zero here
],
```

by the way, when exporting this model to OBJ format, these coordinates come out as -0.0.

![Screenshot_20231203_075743](https://github.com/KhronosGroup/glTF-Blender-IO/assets/18296438/1a718372-3f7b-4cf9-932d-dc7388df75bc)

**Comment by julienduroure** [comment]
Hello,
Don't thing there is any "error" here. This is due to roundoff error in floating point arithmetic.
The json is still valid with this scientific notation, and glTF validator does not complain about it.

What kind of issue do you get because of that?
