### ISSUE TITLE
Animations not included if GPU Instances are enabled

### ISSUE THREAD

**Issue by lights0123** [KhronosGroup/glTF-Blender-IO#2071]
**Describe the bug**
When exporting a glTF or glb file, checking "GPU Instances" under <kbd>Data</kbd> → <kbd>Scene Graph</kbd> will fail to export any animations.

**To Reproduce**

Enable GPU Instances when exporting animations:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/3756309/e677bdfe-d99c-4f47-a73c-4cd8637d5b19)

**This occurs even if no meshes are shared—like with a scene consisting of a single cube.**

**Expected behavior**
Animations are included as they are when GPU instances is disabled.

**.blend file/ .gltf**

[gltfanim.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13565190/gltfanim.zip)

**Version**
 - OS: Arch Linux
 - Blender Version 4.0.1, commit date: 2023-11-16 16:40, hash: d0dd92834a08, type: Release
build date: 2023-11-29, 05:01:14
- io_scene_gltf2 (version: (4, 0, 44), path: /usr/share/blender/4.0/scripts/addons/io_scene_gltf2/__init__.py)

**Comment by julienduroure** [comment]
Confirmed.
Will check
