### ISSUE TITLE
Unexpected Sphere Artifacts Importing VRM 1.0 File In Blender 4.0

### ISSUE THREAD

**Issue by teresayawn** [KhronosGroup/glTF-Blender-IO#2073]
In the environment of Blender 4.0.1 (glTF 2.0 Add-on v4.0.44) and [VRM Add-on](https://vrm-addon-for-blender.info/en/) (v2.20.23), an issue has been observed when importing VRM 1.0 files, where ICO spheres appear in the viewport.

It is worth noting that in Blender 3.6.5 (glTF 2.0 Add-on v3.6.28), even with the latest VRM Add-on (v2.20.23), the mentioned issue does not occur.The first image below demonstrates the imported VRM 1.0 official model ([VRM1_Constraint_Twist_Sample](https://github.com/vrm-c/vrm-specification/tree/master/samples/VRM1_Constraint_Twist_Sample)) in the mentioned Blender environment, showing the screen in the pose mode. 

![Fig_1](https://github.com/KhronosGroup/glTF-Blender-IO/assets/146738533/8b264453-c9ee-441e-a89f-48f875200b2e)

Spheres are positioned instead of bones, and although the pose function seems to work when rotating these spheres, the bone connections are not clear in this state. Changing the viewport display does not affect this issue. However, in edit mode, bones are displayed correctly in their normal form.
Upon inspecting the outliner, a collection named "glTF_not_exported" is created, containing a mesh called "ICO_sphere" that seems to be replacing the bones. Deleting this collection restores the bones to their normal form, as shown in the second image, allowing normal operations.

![Fig_2](https://github.com/KhronosGroup/glTF-Blender-IO/assets/146738533/3c2fcf80-4fd9-423b-ae79-735f0d9474e9)

As an exception, when creating a new VRM 1.0 model within Blender 4.0.1 (verified with a simple model), ICO spheres are not generated. Additionally, if the file is of this type, even with Blender 4.0.1 and the latest VRM Add-on, ICO spheres do not appear upon import.
While the issue has been reported to the VRM Add-on development team, it is believed that the assistance of the glTF 2.0 Add-on development team is required, considering the occurrence of ICO spheres.

**Version**
 -Windows10
 -Blender Version [4.0.1]

**Comment by julienduroure** [comment]
This is not an artifact, these sphere are custom shapes of bones.
This is now the default behavior, using "Blender" import mode for armatures. 
Keep back to "temperance" if you don't want it, but this prevent good round-trip for bone orientation. See #1662 for the whole explanation.

**Comment by teresayawn** [comment]
Is it possible to achieve a screen display that is Temperance-like without reverting to 'Temperance'? 
While it might not be the most appropriate place for discussion, for VRM 1.0 models, the presence of nested bones complicates matters, making it difficult to paint weights with spherical shapes that lack clear orientation. 
It's worth noting that the details reported here have been shared with the developers responsible for the VRM Add-on.

**Comment by julienduroure** [comment]
Temperance was the default prior to 4.0 (so until 3.6 included).

You can remove custom shape view in Armature "Viewport Display" panel

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/9392dd87-0a19-442c-b5da-93a82facec5b)

**Comment by teresayawn** [comment]
If the FBX model or VRM model is older than version 1.0, even in Blender 4.0, the 'Viewport Display' settings will be properly reflected. 
Only when importing a VRM 1.0 model, the bones turn into ICO spheres, and the 'Viewport Display' settings are disabled.

**Comment by julienduroure** [comment]
I am not sure to understand your last comment.

Viewport Display for armatures is part of core Blender, not an option linked to any I/O.
The default "Shapes" option is ON, so bones will be displayed as custom shape, if there are some. If disabled, bones will be displayed as set in "Display As" option (so Octohedral by default).
Whatever comes from the armature (FBX, glTF, or created directly in Blender)

Feel free to ask some help on Blender community forums about these options, as this features are not linked to any I/O process

**Comment by teresayawn** [comment]
Thank you for the suggestion.
I will try asking on the Blender community forums.
