### ISSUE TITLE
Fox sample does not show bones, even in pose mode

### ISSUE THREAD

**Issue by lyuma** [KhronosGroup/glTF-Blender-IO#2074]
**Describe the bug**
When importing the fox sample model, Blender only shows the icosphere at 0,0,0 and bones cannot be clearly seen. See screenshot below.

If I uncheck "Shapes" in Armature Viewport Display, I get the result from previous blender versions, which is visible and easy to manipulate. 

**To Reproduce**
1. Import the fox gltf model with default settings
2. Click on the armature
3. Use ctrl-tab to enter Pose mode
4. Select the b_hip bone (or any other bone)
5. It is very difficult to see which bone is selected.

**Expected behavior**
Bones should be clearly visible and easy to manipulate while in pose mode, for example unchecking Shapes in Armature Viewport Display
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/39946030/b83cea2e-f1ff-4beb-a2d5-5326ee9bd9cc)
Yes, I know the bones are pointing X-positive in this import. That is really important information. I need to be able to see this. Otherwise I'm working blind.

**Screenshots**
Here's the example of the problem with the fox model in pose mode with poorly visible bones and an icosphere at 0,0,0:
![image](https://github.com/saturday06/VRM-Addon-for-Blender/assets/39946030/39015bc9-8904-4f44-bf93-14acf3496fac)

**.blend file/ .gltf**
Empty blender 4.0.2 instance (select all, delete), then importing with default settings the official Fox sample from:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb

**Version**
 - OS: Windows 10
 - Blender Version: 4.0.2

**Additional context**
Followup to #2073 . The previous issue was about the bone spheres being undesirable as a default.

This issue is taking the spheres as given, showing that the spherical bone feature does not work as intended.

**Comment by julienduroure** [comment]
Hello,
Agree that in some cases, the sphere size is not the best.
Let's try to continue the discussion in a single place. Let's close this issue, and continue in #2075, as it has many example
