### ISSUE TITLE
New default bone display unusable for many armatures

### ISSUE THREAD

**Issue by DoctorPresto** [KhronosGroup/glTF-Blender-IO#2075]
With 4.0 defaulting to blender for bone heuristic and using the iconosphere custom shape, while it's nice to not have to spend so much effort correcting the bone rotations, the visualization of the armatures themselves has become completely unusable for any of the armatures I work with in animation. It would be nice if a default size was used instead, with lines drawn between the bones in all views would be even nicer but not necessary.

To reproduce, either import one of the ..glb files or open one of the .blend files included
[human_armature.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13603136/human_armature.zip)
[vehicle_armature.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13603137/vehicle_armature.zip)
 or open one of the .blend files.

screenshots:
human_armature current: 
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/7b9e9dc6-f7bc-4982-9ea3-308edd2d5905)

human_armature temperance:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/e8fb603d-3cc6-4916-b4c5-e50a1783eb04)

vehicle_armature current front:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/45c19c5b-52d5-4f69-a40e-cc6970f7931b)

vehicle_armature current side:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/c0c5cf97-8c6f-4da9-907e-bc6159df94f4)

vehicle_armature temperance front:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/65b5d1d7-1c22-4638-8145-6d33d7f68c44)

vehicle_armature temperance side:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/a0f9f3a5-7739-45a8-92b8-3441ae00d0cf)

**Version**
 - OS: windows 11
 - Blender Version 4.0

**Comment by julienduroure** [comment]
Agree that the sphere size doesn't have an acceptable size in many cases.
Let's try to find a way to get it ok for all situation.

Currently, the sphere size is related to:
- the Complete Armature size
- The bone Size.

In some cases, the sphere is too large, in some others, it is too small.

See current here:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/348f0d812d57589acd9f0265e0b2ceb57be01c33/addons/io_scene_gltf2/blender/imp/gltf2_blender_node.py#L240

And see what options we can use:

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/c87da7d1-7d47-43ab-8d53-b3469db3c0db)

**Comment by manavortex** [comment]
+1, it's really annoying to have those huge spheres floating around everywhere. Unfortunately, I don't have a better formula, but I'm with OP on this one

**Comment by DoctorPresto** [comment]
![Uploading image.png…]()
Just changing your code to not use bone length scaling, to use armature_min_dim to and using .05 instead of .02 as a scale factor, gives this result, seems much better

**Comment by DoctorPresto** [comment]
Just to clarify I mean this ![image-8.png](https://github.com/KhronosGroup/glTF-Blender-IO/assets/111536029/ccb3463d-276a-413d-a700-fa91afc57576)

**Comment by julienduroure** [comment]
You mean like this?

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/464ed5bb-a9db-4375-a172-f7dc5204e43e)

For CesiumMan, I find the sphere a little too small

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/bb595d69-3258-4794-bdb0-fa787afb5552)

But if we make them bigger, we will have issue with bone that are close to each others (like in fingers of your humanoid example)

**Comment by DoctorPresto** [comment]
That's correct. Perhaps exposing the scale factor as a parameter on import and having .05 as the default would solve the issue? That way it can be adjusted easily by the end user if needed but uses a default factor which should lead to a reasonable import for most cases

**Comment by HypixelJacob** [comment]
Hello, currently working on a blender-gltf pipeline:
Are the custom shapes necessary?
For my use case, I know my bones are coming in with the correct blender dimensions, and the Icosphere is completely redundant next to the standard bone displays as far as i can tell. I'd like to keep the scene clear of any misc data like that.

Maybe auto-delete post import if a checkbox is checked?

**Comment by aaronfranke** [comment]
Is there a way to switch it back to the view of the armature like in older Blender versions? I agree the spheres are unusable.
