### ISSUE TITLE
UV problems on import

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#208]
Initial discussion in wrong issue tracker: https://github.com/julienduroure/gltf2-blender-importer/issues/26

   * Your archive contains 14 different glb files! Please tell us what file has problem
   * None of these files has some materials (no "material" in json), so you can't see any materials
   * Seems Facebook does not use glb in standard way
   * UV seems to be strange --> Will have a look on it

**Comment by itchyballsack** [comment]
Thanks, not too worried about materials/textures. just the UV scaling issue. Plus is there a way to import multiple glb?
