### ISSUE TITLE
.blend file produces invalid .glb/.gltf

### ISSUE THREAD

**Issue by trillioneyes** [KhronosGroup/glTF-Blender-IO#2086]
**Describe the bug**
When I export `bird.blend`, the output .glb/.gltf file fails validation. The issue is in the `Walk start` animation -- one of its samplers uses CUBICSPLINE interpolation, but contains only one keyframe.

**To Reproduce**
1. Export `bird.blend` as gltf or glb.
2. Optionally, inspect the exported gltf.
3. Run the gltf validator.

**Expected behavior**
The exporter produces a valid gltf, without any single-keyframe CUBICSPLINE samplers. In this case, maybe it could accomplish that by outputting a LINEAR interpolation?

**.blend file/ .gltf**
[bird-with-textures.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13699116/bird-with-textures.zip)

**Version**
 - OS: linux
 - Blender Version [4.0.2 release candidate]

**Additional context**
I can't figure out why this animation is being exported with a CUBICSPLINE-interpolated sampler. I've left all of the export settings at their defaults, and I thought that would involve sampling all the bezier curves and exporting them with linear interpolation.

**Comment by julienduroure** [comment]
Confirmed.
Investigation in progress
