### ISSUE TITLE
Wrong vertex color attribute is exported

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#2094]
**Describe the bug**
When multiple vertex color attributes are present, only the active/selected one is exported, not the one actually used in the material. Additional ones are not exported at all.

Potentially related issues:
- https://github.com/KhronosGroup/glTF-Blender-IO/issues/2091
- https://github.com/KhronosGroup/glTF-Blender-IO/issues/1740
- https://github.com/KhronosGroup/glTF-Blender-IO/issues/1765

**To Reproduce**
1. Download and open [multi-vertex-color-gltf.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13782114/multi-vertex-color-gltf.blend.zip)
2. Note that the third vertex color attribute is used in the material ("Color3")
3. Export to glTF
4. Note that the first vertex attribute is exported as COLOR_0 and the others are not exported.

**Expected behavior**
The vertex attribute declared in the material should be exported. 
I understand this can be problematic if instances of the mesh are used with different materials that would choose different color attributes (would require de-instancing the geometry on export, as only COLOR_0 will be used as multiplier according to the glTF spec).

**Screenshots**
<img width="1093" alt="image" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/e2ffc9f7-88f8-4198-ba72-68c0754ef7ca">

**.blend file/ .gltf (mandatory)**
[multi-vertex-color-gltf.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13782114/multi-vertex-color-gltf.blend.zip)

**Version**
 - OS: MacOS
 - Blender Version: 4.0.0

**Comment by julienduroure** [comment]
With your setup, no VC are exported. (I can't reproduce the wrong VC export, as no VC are exported)
Plugging Color Attribute directly to Base Color is not checked yet.

=> This should be added, PR is coming

=> Current workaround, adding a mix node setup

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/78afdf76-c905-4621-9aca-3eed683f8ddd)


About exporting multiple VC.
- Problem is that COLOR_0 must be applied when present in glTF file, and COLOR_1 can't exist if there is no COLOR_0
- Proposition : Add an option to force export VC
  - If VC is used in node tree, COLOR_0 is set from the node tree, and all others are from mesh list of VC
  - If no VC is used in node tree, create a fake "all 1.0" COLOR_0, and then export all others from mesh list

**Comment by pineapplemachine** [comment]
I was able to have my additional Color Attribute export by prepending an underscore "_" to the name and ensuring that "Attributes" is checked in the glTF export settings, but I still was not able to find a way to export the secondary color information specifically as COLOR_1. This shouldn't be a big obstacle for my use case, but it was surprising to find that my color attribute would not export unless specially named and exported as an attribute.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7266412/953b943e-1191-41cf-98e0-92069b104650)

This is with Blender 4.0.2. My addon settings show the `Import-Export glTF 2.0 format` addon as version 4.0.44.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7266412/6d4c9ac7-5c33-4915-b52c-1549cee160d5)
