### ISSUE TITLE
Can't export only one frame animation. (like "pose")

### ISSUE THREAD

**Issue by Skino1337** [KhronosGroup/glTF-Blender-IO#2095]
**Describe the bug**
I set limit playback with frames from 3 to 3, and сheck the same box when export. I also try unheck optimization box.
But exported file has standart pose without any animation.
I check the similar topics, and try custom fix (add "return keyframes" in .py files) but It did not help.
If i export from 3 to 4 frame is works well.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/84f0dd6b-e0f7-4ae9-8a07-24abc7b60cd3)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/41cf7771-b09c-48d5-b53a-cd67798585f4)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/aee5edc2-793f-4d75-801d-6cf8561d902e)

**.blend file**
[1h.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13800242/1h.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 4.0.2

**Comment by julienduroure** [comment]
Confirmed.
Some issue for 1 frame animation export when using bezier curves
