### ISSUE TITLE
Export - Import GLB -- Error Emission

### ISSUE THREAD

**Issue by blend3dweb** [KhronosGroup/glTF-Blender-IO#2097]
Good afternoon.
When exporting and re-importing GLB format, the emission data changes its value.

1. Add an object
2. Add material
3. Set the material - Emission color - RGB (1.0,1.0,1.0)
4. Strength emission - 0.5
5. GLB export (without animation)
6. Import the exported file
7. Emission color - RGB (0.5,0.5,0.5)
8. Strength emission - 1.0

Expected Behavior:
Emission:
   color - RGB (1.0,1.0,1.0)
   strength - 0.5

OS: Linux Manjaro
Blender version - 3.6.5 / 4.0.2

[test_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13826929/test_glb.zip)

https://github.com/KhronosGroup/glTF-Blender-IO/assets/43431061/fad06def-68c2-4887-ba7c-49eeabd97d81

**Comment by julienduroure** [comment]
I can confirm this behavior, but I don't think this is a bug.
glTF core specification has no color + Strength data for emission values, only color. 
So data are converted from Blender to fit glTF specification.

For Strength > 1.0, there is a glTF extension to handle it, but not sure we have to use it for strength <= 1.0

Do you have any issue with this behavior ?

**Comment by julienduroure** [comment]
More than a month without any answer.
Closing this ticket
