### ISSUE TITLE
GLTF export fails with ZeroDivisionError

### ISSUE THREAD

**Issue by audionerd** [KhronosGroup/glTF-Blender-IO#210]
Example `.blend` file which exhibits the issue:

https://github.com/wonderunit/shot-generator-models/blob/77f39c6eac764ace508f3bf718f5443ec45a0fc6/characters/base/male-youth/male-youth.blend

Fails on this line: https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py#L106

With the error `ZeroDivisionError: integer division or modulo by zero`

Using the nightly Blender 2.8 beta from today 7 Jan 2018.

**Comment by UX3D-schmithuesen** [comment]
The problem, for me at least, is that the referenced texture doesn't exist since only the blend file is provided. I improved the error message in #215, but didn't change the behaviour in any way.
