### ISSUE TITLE
Check EEVEE_NEXT

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#2106]
See this as an example: 
https://projects.blender.org/blender/blender-addons/commit/f0a0966688c0c1c07b24ba018eabed5291f355bf

**Comment by scurest** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/blob/2debd75ace303f3a3b00a43e9d7a9507af32f194/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py#L36-L37

Not sure what this is for. Maybe can just delete it.

**Comment by julienduroure** [comment]
Yes, I think this can be removed.
I think the code was here before 2.80, and was used to avoid importing was Blender Internal render engine was used, as there was no node for this render engine

**Comment by julienduroure** [comment]
Fixed by 72246390c7a73324aaeafd4acf16a449f207a87f
