### ISSUE TITLE
Export: cannot export baseColorTexture + baseColorFactor + COLOR_0

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#2110]
**Describe the bug**
When trying to export a material with a baseColorTexture, a baseColorFactor, and a COLOR_0, only one of the factor and COLOR_0 gets exported (the one closer to the Base Color socket).

This exports without the factor

![](https://github.com/KhronosGroup/glTF-Blender-IO/assets/11024420/f6d5c076-f15a-495b-9fb8-369f3a771f1d)

This exports without COLOR_0

![](https://github.com/KhronosGroup/glTF-Blender-IO/assets/11024420/956d73ed-024b-4236-8015-e6747d8bbdec)

This also means, of course, that a glTF that uses all three of these will not roundtrip.

**.blend file/ .gltf (mandatory)**
[Iss2110.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13909705/Iss2110.zip)
Open .blend, export (default settings), and reimport.

**Version**
 - OS: Linux
 - Blender Version: 4.0.0 Beta
 - Addon Version: main

**Comment by julienduroure** [comment]
I started implementation of this fix

**Comment by julienduroure** [comment]
I started an implementation with naive algo:

- Search some Multiple node from socket
- If no nodes => No VC, no Factor
- If 1 node => Checking that 1 input socket is linked to texture node. For the other socket:
   * If only 1 of the 2 socket is linked => Factor
   * If both are linked => Check if linked to an UV or Attribute => VC
 - If 2 nodes => Same than previous, but on each node. Also checking that we don't have 2 VC or 2 Factors
 - If more than 2 nodes => Ignore all or take only the first 2 ones into account ?

Do you think there is a better way of doing? Maybe using NodeNav can handle some part of the complexity on it?

Any thought @scurest ?

**Comment by scurest** [comment]
I'd do it like

```py
socket = base color socket on Principled node
factor = None
vc = None

for _ in range(2):  # twice, in case there's both a factor and vc
    if factor is None:  # no factor found yet?
        if socket is constant:
            factor = constant
            break
        elif socket connects to multiply by constant:
            factor = constant from multiply node
            socket = other socket on multiply node
            continue

    if vc is None:  # no vertex color found yet?
        if socket connects to vc node:
            vc = name from vc node
            break
        elif socket connects to multiply by vc node:
            vc = name from vc node
            socket = other socket on multiply node
            continue
```

**Comment by julienduroure** [comment]
Note: As describe in #2206, we need to check alpha VC too
