### ISSUE TITLE
Children of scale animated parent have their transforms reset and disappear from viewport when NLA animation export mode selected during glb export

### ISSUE THREAD

**Issue by kokotron** [KhronosGroup/glTF-Blender-IO#2114]
[anim_glb_export_children_scale_zero_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13939474/anim_glb_export_children_scale_zero_test.zip)

• Blender 4.0.2
• Placed 3 objects, one (torus) is parent, has scale animated (0 to 1), then pushed down as action
• .glb export, animation mode "NLA tracks"
• after export, children transforms reset and scale is zero, children disappear in the Blender viewport. Possible to revert with some "undos" and then "redos".

note: In this scenario, choosing "use current frame as object rest transformations" while in a suitable frame prevents this from happening. But if the hierarchy is more complex, like more children within children, I've experienced them getting all kinds of ways of screwed up. Unfortunately I couldn't easily reproduce and include such a scenario, but I thought I should mention it.

note 2: exporting in "actions" mode instead of "NLA" can also solve this, but it's not useful if you have actions placed at different times in the NLA.

**Comment by julienduroure** [comment]
Hello,
Thanks for the report

> choosing "use current frame as object rest transformations" while in a suitable frame prevents this from happening

Exporting scenes with objects scales at 0.0 at first frame is not possible without using the "use current frame as object rest transformations", as we can't manage local transforms of zero scaled objects. So using this option is the way of doing it. Unfortunately, your test case seems to work using this option, so without any test case that show the issue, I could not investigate.

Investigation in progress about children transforms staying at 0
