### ISSUE TITLE
"Export Deformation bones only ." exports rigify control bones (Which don't directly deform).

### ISSUE THREAD

**Issue by HypixelJacob** [KhronosGroup/glTF-Blender-IO#2115]
**Describe the bug**
I exported a Rigify armature to .glb with the  option checked under "Armature". 
Checking the result, I see that multiple IK control bones also got exported, despite them not having a direct influence on the mesh.
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/144714137/e6030bfa-01a0-413e-83f7-a0cb9714af44)

**To Reproduce**
1. Bind a Rigify Rig
2. Click on File > Export > GLTF 2.0
3. Select the Rig Object
4. Select "Limit to: [X] Selection Only"
5. Select the "[X] Export Deformation Bones Only"
6. Hit Export
7. Import the Resulting GLTF back into the scene.
8. Check the bone hierarchy under the Armature.

**Expected behavior**
I expect only bones that have influence on the mesh to be included in the export. 
None of the face controls, IK switches or IK target bones would be expected when selecting that option.

**Screenshots**
Control Rig / Current Export Hierarchy:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/144714137/335ffa02-5279-4be9-b89a-ab914c4b3912)

Expected Export hierarchy:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/144714137/6e421477-c877-4d10-959a-a302ba963b25)

**.blend file/ .gltf (mandatory)**
[ExportBones.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13981521/ExportBones.zip)

**Version**
 - OS: Windows 11
 - Blender Version 4.01

**Additional context**

**Comment by julienduroure** [comment]
Hello,
Thanks for the reporting.
"Deformation bone" is exported based on the "Deform" property of the pose bone in Blender.
As you can see, seems the poles and IK target are wrongly set as deform-enabled bones on your rig.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/8a805112-275b-4f38-ba23-be6082cd2711)


No bug here, export follow what is in the rig.
Closing

**Comment by HypixelJacob** [comment]
@julienduroure What do you think about updating the Export checkbox tooltip to something like: "Exports only bones with the Deform property checked"?

My confusion stemmed from the fact that the "Deformation bones, when imported into their target engine still did not actually deform any geometry, as they had no weights or bone groups despite being having this checkbox checked.

"Deformation Bones" are a common term typically used to describe bones that deform geometry, I could see this being confusing to others as well.
