### ISSUE TITLE
Error when exporting with custom UV attribute as the ImageTexture input in the shader node

### ISSUE THREAD

**Issue by nothke** [KhronosGroup/glTF-Blender-IO#2135]
**Describe the bug**
Attempting to export with custom shader UV attribute emits a "RuntimeError: Internal error setting the array"

I caught the bug live on stream, and you can see me trying to figure out the cause in this highlight: https://www.twitch.tv/videos/2059685759

**To Reproduce**
1. Create an object (with a UVMap uv layer, most primitives will have it by default) and with a new material
2. Assign an image as the base color in the material
3. In the shader node editor, attach an Attribute node to the "vector" input of the image texture, with UVMap as the name
4. Attempting to export this object as glb will emit an error

**Expected behavior**
No error, or at least a clear error message indicating the problem.

**Screenshots**
https://www.twitch.tv/videos/2059685759

**.blend file/ .gltf (mandatory)**
[gltf_error.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14232629/gltf_error.zip)
Assign any image to the image texture and try to export.

**Version**
 - OS: Windows 10
 - Blender 4.0.2 (error was also present in 4.0.1)

**Comment by julienduroure** [comment]
Can you please test with 4.1 alpha, I already fixed it

**Comment by nothke** [comment]
> Can you please test with 4.1 alpha, I already fixed it

I'm sorry, both latest blender 4.1 beta or 4.2 alpha daily builds crash on startup on my PC, so I can't test.

**Comment by julienduroure** [comment]
Confirmed that this is fixed on 4.1 beta already.
Closing this ticket.
Feel free to open a ticket on https://projects.blender.org/blender/blender for your Blender issue
