### ISSUE TITLE
Manage drag & drop

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#2144]
Cf https://docs.blender.org/api/master/bpy.types.FileHandler.html

**Comment by madjin** [comment]
wait, drag and dropping 3D files into blender? It's finally happening? YES!!

**Comment by julienduroure** [comment]
> You can add multiple extensions by seperating them with a semicolon, like this -> bl_file_extensions = ".gITF;.gltf;.glb"

**Comment by julienduroure** [comment]
https://projects.blender.org/blender/blender/issues/119488

**Comment by julienduroure** [comment]
Closing this ticket, Drag&Drop is now managed by #2193
