### ISSUE TITLE
Black meshes and broken vertices after export

### ISSUE THREAD

**Issue by Snouf-ID** [KhronosGroup/glTF-Blender-IO#2163]
I run blender 4.0.2 from steam.
I open my model, I export in gltf. After export is finished, the model is broken in view, with black parts and strange faces (see images)
Exported gltf has the same problem as the blender post export rendering. ctrl + z seems to resolve the problem in blender view.
This bug occurs even without material.
I tried quickly on another PC and strangely I had no problems.

I'm going to try to cut part of this proprietary mesh and add to the outcome to be able to reproduce as quickly as possible, if no one has an idea in the meantime already.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/47319640/804a5302-337a-41dc-a760-44eacf497d9e)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/47319640/0a5bbabf-7790-4be8-ab7d-3aeec8218e74)

 - OS: windows 10
 - Blender Version 4.0.2

**Comment by julienduroure** [comment]
Hello,
Waiting a file to be able to reproduce. 
If you have the same issue after rendering, the problem probably comes from your mesh, not from the glTF export.
Maybe report it on https://projects.blender.org/blender/blender will be a better place.
glTF I/O can't manage your export correctly if data are corrupts.

**Comment by julienduroure** [comment]
Confirmed that your mesh is not valid.
Check in export log : 

> WARNING: Mesh SM_Stone_Wall_Arc.054 is not valid, and may be exported wrongly

You can also check it by open your file, and type in blender console

> bpy.context.object.data.validate()

=> Return True, indicates that the mesh is not valid, and see that your mesh is now also broken in 3D View

Closing this ticket, as we can't export correctly a not valid mesh that Blender itself is not able to manage.

Please open a Blender ticket, explaining how you generated your mesh
