### ISSUE TITLE
Incorrect size of a (re)imported empty

### ISSUE THREAD

**Issue by The0Dev** [KhronosGroup/glTF-Blender-IO#2164]
After (re)importing an empty, its size is set to a random(?) value in the data tab.

1. Create a few empties
2. Move them in any direction from the origin
3. Export the scene
4. Import it back
5. See the result

**Expected behavior**
The size should remain equal to 1.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/56b29ed4-52f3-4085-9498-2b0f14929a12)

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/9ca88616-6b7f-4eb2-8da4-7e1fbee69878)

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/41e57353-7fb9-4070-9ba0-a5ce375a31db)

**.blend file/ .gltf **
[gltf_empty_node_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14615762/gltf_empty_node_bug.zip)

**Version**
 - OS: [Linux]
 - Blender Version [3.2.2, 3.6, 4.1]

**Comment by julienduroure** [comment]
Hello,
No bug here.
Size of an Empty is not part of the glTF specification, this is a specific Blender property.
Exporting Empties will not store this data into glTF.
So importing them back can not have this data, and will create empties with default values, that is 1 meter.


> The size should remain equal to 1.

This is the case, empties are created with size 1

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/a51fa38f-417c-4672-a515-6afe7ed72eeb)

**Comment by The0Dev** [comment]
Thank you for the response.

> This is the case, empties are created with size 1

For some reason, this is not the case for me. The size somehow changes depending on the position of an empty. I'm using the latest build of Blender. The version of the addon is 4.1.61

**Comment by julienduroure** [comment]
Oh, you're right.
My bad, we set the display size at import.
Let's investigate what's happen here

**Comment by The0Dev** [comment]
I see. Is there a reason for this? I use empties in my project to set spawn position of characters on a map. It ends up looking pretty messy in the viewport. I would greatly appreciate it if some adjustments were made. 
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/afb62f46-a589-4ce1-a2f3-deffac9e958b)

**Comment by julienduroure** [comment]
Hello,

I don't think there is a general formula that will fit every workflow.
We probably can add a hook for people that want to modify this value during import

**Comment by The0Dev** [comment]
Hi. Having more control over this would be great. However, I think something like this would suffice in my case. (If the size of an empty node is not 1 just leave its display size unchanged):
```
    def calc_empty_display_size(gltf, vnode_id):
        # Use min distance to parent/children to guess size
        vnode = gltf.vnodes[vnode_id]
        if vnode.trs()[2] != Vector((1, 1, 1)):
            return 1
```
