### ISSUE TITLE
The add-on fails to apply the modifiers during export

### ISSUE THREAD

**Issue by kursad-k** [KhronosGroup/glTF-Blender-IO#2166]
**Describe the bug**
It looks like the add-on is failing to export the mesh with modifiers during the export. I think this is some kind of edge case because I generally do not have this issue  with glTF exports.

**To Reproduce**
load the attached blend
select the object
export gltf seperate
enable "selected objects"
enable "apply modifiers"
export

**Expected behavior**

**Screenshots**

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/67970138/40d6a184-e85d-4d6c-9da9-b9a8851ef1c1)

**.blend file/ .gltf (mandatory)**
[bug_17032024_0031_41.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14626290/bug_17032024_0031_41.zip)

**Version**
Blender 4.2.0 Alpha
        build date: 2024-03-16
        build time: 19:49:28
        build commit date: 2024-03-16
        build commit time: 19:16
        build hash: 6768ded89586
        build platform: Windows

**Additional context**

**Comment by julienduroure** [comment]
Hello,
No bug here.
One of your modifier is Armature.
By default, armatures are exported in Rest pose.
If you want to export the mesh in pose mode, you have to uncheck the option "Use Rest Position Armature"
( In Data > Armature )
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/1d0aea53-9cdb-4939-ac2c-8225cc3f6bf0)

**Comment by kursad-k** [comment]
That makes sense. I tried to go through the options to see what would be causing this. I totally missed that one. Thanks for the clarification.
