### ISSUE TITLE
Accessors have bad componentType

### ISSUE THREAD

**Issue by Snouf-ID** [KhronosGroup/glTF-Blender-IO#2167]
When I export my 3d model (pbr animated mesh), the GLTF format tells me that the indices are 5123 (FROM_GL_UNSIGNED_SHORT) while the count is 205104.

**To Reproduce**
Waiting for me to cut an owner file.
I added a character with a lot of vertices.
I merged all the parts with ctrl + j then I exported to glb.
This is a character with frame and animation.

**Expected behavior**
As the count is > 65535, I expect to have the type 5125 (UNSIGNED_INT).

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/47319640/1194b0a8-e9e8-4fbd-80a3-17ace46587e4)

**.blend file/ .gltf (mandatory)**
It's coming, soon

**Version**
 - OS: Windows 10
 - Blender Version 4.0.2

**Additional context**
{
	"bufferView":6,
	"componentType":5123,
	"count":205104,
	"type":"SCALAR"
}

**Comment by scurest** [comment]
That's not, on the face, implausible.

Only in the absolute worst case are there as many verts as indices. In the usual case a vert will be shared by many tris (six for the "average" vert in a quad mesh)

![](https://github.com/KhronosGroup/glTF-Blender-IO/assets/11024420/ae78efe1-70e1-485e-9c82-db46c1eafe72)

As a rule of thumb, there are half as many verts as tris, or 1/6 as many verts as indices, which for your example gives 205104 / 6 = 34184, which is very comfortably less than 65535.

If you want to know if the indices fit into a ushort, you should look at the count of the POSITION accessor, not he count of the indices.

**Comment by Snouf-ID** [comment]
You are absolutely right, thank you
