### ISSUE TITLE
Full Collection Hierarchy - "Limit to" conflict

### ISSUE THREAD

**Issue by lgxm3z** [KhronosGroup/glTF-Blender-IO#2175]
**Describe the bug**
Related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/1456

When exporting with limited scope, for example "Selected Objects" and having **Data > Scene Graph > Full Collection Hierarchy** active, you got some errors.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/28831375/ab916b7c-10bb-4f88-ac05-96cf58a8de31)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/28831375/5cd3c0bc-8d05-42ad-84ef-8cdd7b7e20d9)

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/28831375/44c87dd3-94fc-4b8c-801e-6ff6f310a5c6)

**Version**
 - OS: Windows 10 Pro
 - Blender Version 4.1.0 (2024-03-25)

**Comment by lgxm3z** [comment]
@julienduroure  What should be the correct behavior? Just a better error message?

**Comment by lgxm3z** [comment]
It also doesn't work when limited to "Visible Objects"

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/28831375/6a1f24b8-6904-42f8-ac71-96ed7c06d66e)

**Comment by julienduroure** [comment]
Confirmed
