### ISSUE TITLE
Alpha image export baked from RGB Color texture

### ISSUE THREAD

**Issue by Stadrem** [KhronosGroup/glTF-Blender-IO#2176]
**Describe the bug**
If I specify the grayscale texture as alpha and then export it using gltf export, the alpha texture is not created. When I open the glb file with a viewer, etc., the image in the file created in 4.1 is not transparent. 

Even if I set Images to Automatic or PNG in gltf export, the same bug occurs.

But, if I use Alpha with a PNG file where I created the transparent part, it works fine. 

This bug did not exist in Blender 4.0.

**Screenshots**
![0001](https://github.com/KhronosGroup/glTF-Blender-IO/assets/106669174/73d3c317-a552-4f88-a3d4-c192f245eaeb)
Material

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/106669174/f5e078cf-4e17-42d9-af98-f5ee9dc3aa87)
Image captured from glb exported from Blender 4.0.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/106669174/65da4ffb-6fc8-43b5-ba86-405530acc790)
Image captured from glb exported from Blender 4.1.

**.blend file/ .gltf (mandatory)**
![JPG_caustic_001](https://github.com/KhronosGroup/glTF-Blender-IO/assets/106669174/483bcae3-d86c-4b6e-896c-df555d5d4946)
image file

[AlphaBug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14767736/AlphaBug.zip)

**Version**
  - OS: windows 11
  - Blender Version 4.1

**Additional context**

**Comment by julienduroure** [comment]
Hello,

This is not really a bug, but a case that we don't handle in the exporter.
Exporter currently map channels of textures into glTF texture channel (1 to 1)

But this case is not a simple mapping. Some data must be baked (Color => Float)

Settings as enhancement for now

**Comment by globglob3D** [comment]
[Alpha_issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14958745/Alpha_issue.zip)

Here is the .blend file with packed textures.

**Comment by julienduroure** [comment]
In 4.0, the alpha channel was created only from Red channel of the texture.
In 4.1, no alpha is generated.
Agree that the behavior changed. Was not right, and still is not right, not in the same way.
See also https://projects.blender.org/blender/blender-addons/issues/105284
