### ISSUE TITLE
Animation not exported to glTF

### ISSUE THREAD

**Issue by zaqxsw-dev** [KhronosGroup/glTF-Blender-IO#2177]
1. Open attached blend file.
2. Go to File -> Export -> glTF
3. Select Data -> Mesh -> Apply modifiers checkbox
4. Push Export
5. Go to https://gltf-viewer.donmccurdy.com/ and upload gltf file

In the blend file we have 2 animations but in gltf no one(.
[tree.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14773779/tree.zip)

**Comment by julienduroure** [comment]
Hello,

We can't export these animations to glTF, as you are animating a property of a modifier.

Only the following animation can be exported in core glTF specification:
- Location/Rotation/Scale of objects
- Location/Rotation/Scale on armature bones
- Weights on Shape Keys
