### ISSUE TITLE
Incorrect Data for Additional UV Channels

### ISSUE THREAD

**Issue by mgange** [KhronosGroup/glTF-Blender-IO#2185]
Values are not as expected for exported .glb/.gltf files for additional uv channels (they seem to be correct for uv1, but additional channels are incorrect);.

**To Reproduce**
1. In Blender, add additional UV channels to an object; I've then used Geometry nodes 'Store Named Attribute' to pack the channels with test data.
2. Under the 'Geometry Nodes' tab, under Mesh->Face Corners you can confirm the expected values for each channel.
3. Select the object and export GLTF 2.0.
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/397827/8e4bf3d5-ce0b-4250-85fa-a211fecc1ea9)
4. Reading the values in Godot provides incorrect values:
https://github.com/godotengine/godot/issues/89994
5. I also inspected the values with this tool:
https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode
Which also showed the incorrect values.
6. If you then re-import the generated .glb into Blender, note that the values are as expected (so the issue doesn't seem to be Geometry Nodes related, it's most probably import/export related).

**Expected behavior**
Additional uv channel data exports with expected values.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/397827/35293ada-02ac-4c17-a6ac-f20ad5c9ec05)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/397827/d76963b8-7794-408f-a841-0438eba80e35)

See attached .blend file.

**Version**
 - OS: Windows 10.0.22000
 - Blender Version 4.1.0 (Check with most recent Alpha build too)
 
[vert-test3.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14805894/vert-test3.zip)

**Comment by julienduroure** [comment]
Hello,

UVMap are not expressed the same way between Blender and glTF, so data are converted at export, and converted back at import.

On glTF (See [glTF Specification](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_wrapping)):

> the texture coordinate value of (0.0, 0.0) points to the beginning of the first (upper-left) image pixel, while the texture coordinate value of (1.0, 1.0) points to the end of the last (lower-right) image pixel

On Blender: 
- (0,0) is on bottom left
- (1,1) is upper right


That does explain why 
- U values are not modified (left to right)
- V values are modified (up to down in glTF / down to up in Blender)

Not sure what happen in Godot, but here is the explanation about the value you can see in glTF file

**Comment by mgange** [comment]
Thanks for the explanation Julien, however you'll note all the v values are the same in the example, so a directional shift wouldn't account for that? Could there be a bitmask/bitshift issue at play? (uv2: 2.0, 0.6 -> 2.0, **0.4**, 4.0,10.0 -> 4.0, **-9.0**)

Additionally, I tested with the Cesium GLTF Viewer and saw those same "incorrect" values, so I'm pretty sure it's not Godot.

**Comment by julienduroure** [comment]
I am not sure why Godot does not see TEXCOORD_3 and TEXCOORD_4 on your screenshot, but merged in into a single "Custom0" that is not in Blender and glTF file

Any link to Cesium glTF Viewer? Is it an online viewer?

**Comment by mgange** [comment]
Yeah, I think that's an implementation thing on the godot end.

The Cesium Viewer is a VSCode extension; I couldn't find an online viewer that would let me inspect the values.
https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode

**Comment by mgange** [comment]
In Cesium:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/397827/69baad1f-8b41-47d3-b0cd-2ae3a430dc00)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/397827/27979739-b741-4357-9014-343d73ae5e0a)

**Comment by mgange** [comment]
Hi Julien - thanks so much for your help. I see now that UV1 only looked "right" to me because the v value was 0.5.

 Since I'm using the channels to pass data I didn't expect it to change. But it's a coordinate system, after all. I recall now how some viewers (Marmoset) have the option to flip the UV channel - I'll have to see if that's available in Godot. Either way, now that I understand what's happening, it should be inconsequential for me to decode the values on my end.
 
 Thanks again!

**Comment by mgange** [comment]
Whoops. Let's close this.

**Comment by julienduroure** [comment]
If you want to export some custom data, you should use Custom Attributes!
