### ISSUE TITLE
Empty Export

### ISSUE THREAD

**Issue by Skino1337** [KhronosGroup/glTF-Blender-IO#2187]
**Describe the bug**
Exported files with "changing with python script" expoted empty.

**To Reproduce**
Just export to glb/gltf

**Screenshots**
![view](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/802e8f00-a625-4ca4-b7ca-5d4cb63562ce)
![coll](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/73bb0327-02f6-406e-9e68-8f9e0ce335fa)
![gltf](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/ef25f2cc-f47f-45cc-82ff-f8b0ed0c9daa)
![py](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5137675/7dac4ce5-84c3-4f4a-9deb-279adc1905cd)

**.blend file/ .gltf (mandatory)**
[Water.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14823618/Water.zip)

**Version**
OS: Win 11
Blender 4.0.2

**Additional context**
[python script.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14823620/python.script.zip)

**Comment by julienduroure** [comment]
As you can read in log, your mesh data is not valid, so it can't be exported correctly.

> 18:24:01 | WARNING: Mesh zengin.002 is not valid, and may be exported wrongly

**Comment by julienduroure** [comment]
Closing this ticket, as this exporter can't guarantee the export if mesh data is not valid in Blender

**Comment by Skino1337** [comment]
Thanks. Fix this just comment a string:
`    # Be sure that object is valid (no NaN for example)
    res = False # blender_object.data.validate(verbose=False, clean_customdata=False)
    if res is True:
        print_console("WARNING", "Mesh " + blender_object.data.name + " is not valid, and may be exported wrongly")`

**Comment by julienduroure** [comment]
Hello,

This check is useful for lots of other cases where Blender crash when trying to export non valid meshes, so we will not remove this check.
The issue of non valid mesh should be fixed upstream, either by Blender importer, or, in your case, addon script developer must check that it generate valid meshes.
