### ISSUE TITLE
Full Collection Hierarchy gives error when exporting limiting to Renderable Objects

### ISSUE THREAD

**Issue by ydeltastar** [KhronosGroup/glTF-Blender-IO#2192]
**Describe the bug**
Similar to https://github.com/KhronosGroup/glTF-Blender-IO/issues/2175, the exporter crashes with a `AttributeError: 'Collection' object has no attribute 'users_collection'` when `Scene Graph > Full Collection Hierarchy` and `Include > Limit to > Renderable Objects` are enabled.

**To Reproduce**
1. Enable `Scene Graph > Full Collection Hierarchy` and `Include > Limit to > Renderable Objects`
2. Export

**Expected behavior**
No errors.

**.blend file/ .gltf (mandatory)**
It can be reproduced with the default startup scene without modifications.

**Version**
 - OS: Windows 11
 - Blender Version 4.1.0

**Comment by julienduroure** [comment]
Hello,
Thanks for the report.
This is already fixed by #2178
