### ISSUE TITLE
Vertex colors export option missing in 4.1

### ISSUE THREAD

**Issue by karomapu** [KhronosGroup/glTF-Blender-IO#2194]
**Describe the bug**
The option to export vertex colors is missing from the export window. Re-importing the output file in Blender confirms that no vertex color data was exported. In previous versions (4.0.x), the vertex color checkbox is there and works as expected.

**To Reproduce**
1. Open attached file, then go to File > Export > glTF 2.0
2. Under Data > Mesh, the Vertex Color checkbox is missing.
3. Export to glb, then open new blender file.
4. Re-import the exported file into blender, or import provided glb file
5. In vertex paint mode, vertex colors are missing.

**Expected behavior**
Vertex colors are exported properly in resulting .glb file.

**.blend file/ .gltf (mandatory)**
[vertex-color-export-test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14892652/vertex-color-export-test.zip)

**Version**
 - OS: Windows-10-10.0.19045-SP0 64 Bits
 - Blender Version 4.1.0

**Comment by julienduroure** [comment]
Hello,

The way Vertex Color has changed between 4.0 and 4.1.
To be more aligned with Blender viewport, we now export VC only when the VC is used in the node graph.

Just saw that the Blender documentation was not updated

Note that option to export multiple VC without exporting additonal VC as custom properties is under discussion : #2195

**Comment by julienduroure** [comment]
Closing, this ticket, as there is no issue here.

For your export : 

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/09583286-d8c5-4107-bddf-81ae290e24c4)

or 
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/0d45eb07-90d3-4f23-8813-bc411b947f71)

**Comment by karomapu** [comment]
hi, is there any particular reason for this change? I only use vertex colors purely as data, and I don't want it affecting the color output in the material. If I have to use it in the node graph, how can I set it to not affect base color?

**Comment by julienduroure** [comment]
If you want to use purely data without any impact on colors, you should use custom attributes.
VC are used to change colors, not to store customs data, where glTF already have this data management.
You should enable custom attributes export, and VC colors will export as custom attributes

**Comment by bertodelrio256** [comment]
"VC are used to change colors, not to store customs data"

almost every 3d game ever made would disagree
