### ISSUE TITLE
Export: Support for KHR_mesh_quantization (without Draco compression)

### ISSUE THREAD

**Issue by pmatyja** [KhronosGroup/glTF-Blender-IO#2198]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to export mesh using **KHR_mesh_quantization**.

**Describe the solution you'd like**

Ideally it should have a similar menu as current "Draco Compression" where one can adjust attributes and quantization values.

**Describe alternatives you've considered**

We can reuse the current "Compression" menu and add ability to just disable "Draco" compression with a checkbox and allow users to adjust only quantizations.

**Comment by donmccurdy** [comment]
In theory this should work in the v4.1 release with #1945. You'll need a separate installation of [gltfpack](https://meshoptimizer.org/#installing-gltfpack), enabled in the addon preferences, and then enabled again when exporting the scene.

Unfortunately, I'm seeing no effect when enabling gltfpack here... not sure yet if I've set something up incorrectly.

**Comment by scurest** [comment]
Apparently how it works is the normal file is written out to the regular location, and the gltfpacked file is written into a folder named `gltfpacked/` in the same directory. So try looking for it there.

**Comment by pmatyja** [comment]
> In theory this should work in the v4.1 release with #1945. You'll need a separate installation of [gltfpack](https://meshoptimizer.org/#installing-gltfpack), enabled in the addon preferences, and then enabled again when exporting the scene.
> 
> Unfortunately, I'm seeing no effect when enabling gltfpack here... not sure yet if I've set something up incorrectly.

I know that there are external tools like gltfpack, gltf transform, etc. unfortunately even after installing them I see no input field to setup any path :(

**Comment by donmccurdy** [comment]
@scurest you're correct! That's what I get for having too many files on my desktop I suppose.

@pmatyja if you're on Blender v4.1, there should be an input (whether or not gltfpack is installed) in the addon preferences:

![blender gltf addon menu gltfpack](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1848368/e0be4cd6-c4a3-4328-b964-a5e9b8639af7)

Result:

![monkey mesh with quantization](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1848368/746a7d65-fed1-40b2-b8a7-57b828532af2)

**Comment by pmatyja** [comment]
@donmccurdy

I've double checked and I was using shortcut to version 4.0. Now in 4.1 I can see the path but I must be dumb or something but I am still not able to export initial scene with grey box and apply optimizations from `gltfpack`.

gltfpack v0.20: https://github.com/zeux/meshoptimizer/releases/tag/v0.20

![blender-export](https://github.com/KhronosGroup/glTF-Blender-IO/assets/65171809/570b2091-2bf2-4f50-8ebe-c0bf8866c755)

I've opened the system console but there are no errors in there.
Is there any other error log I can/should take a look to see what am I doing wrong?

Sidenote: The path to the `gltfpack` seems to be correct because otherwise a different pop up shows saying the `gltfpack` file is missing.

![exporter](https://github.com/KhronosGroup/glTF-Blender-IO/assets/65171809/4aa917ac-8bc4-4757-bd17-017533fa0730)

**Comment by scurest** [comment]
@pmatyja I can see that the `gltfpacked` folder exists in your screenshot. Did you check inside it?

**Comment by pmatyja** [comment]
> @pmatyja I can see that the `gltfpacked` folder exists in your screenshot. Did you check inside it?

Apart from `gltfpack.exe` file there is nothing else in there :(
Manually invoking `gltfpack` works fine. It kinda looks like the Blender do not invokes `gltfpack` at all.

**Comment by scurest** [comment]
@pmatyja No, your gltfpack.exe is located in `D:\Programy\gltfpack\gltfpack.exe`. The gltfpacked file is written into a folder named `gltfpacked` in the folder where you export to. Did you check _that_ folder?

![mm](https://github.com/KhronosGroup/glTF-Blender-IO/assets/11024420/b933a32d-e6a1-42dc-abf6-949f5779392a)

**Comment by pmatyja** [comment]
(**face palm**) well... it is working. Thanks @scurest  :) 

My assumption was that when I export a file that THIS FILE will be the one with quantizations.
I think... it should at least say something, somewhere that the file will be in a separate folder. Or better yet, allow user to check if they would like to have an original copy or just overwrite the file.

I can imagine more people will be confused by it.

Anyways, again thank you very much. We can close the issue :)

**Comment by scurest** [comment]
I agree, I think everyone here was confused by it. It looks like it would be fairly easy to write it to a temp file in the same dir, run gltfpack, and remove the temp file if gltfpack succeeded.
