### ISSUE TITLE
Exporter: Avoid to export invalid JSON format

### ISSUE THREAD

**Issue by capnm** [KhronosGroup/glTF-Blender-IO#22]
AFAIK the * .gltf file should be in JSON format:
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0
»The format combines an easily parseable JSON scene description with one or more binary files representing geometry, animations, and other rich data. Binary data is stored in such a way that it can be loaded directly into GPU buffers without additional parsing or other manipulation.«

The JSON specification doesn't allow `NaN` as a value or number: https://json.org/

Exporting values as NaN breaks reading the glft file with the standard JSON parsers.
I couldn't trigger such a case with the blender-exporter[2] myself, but others claim that it happens
https://github.com/godotengine/godot/issues/21668
and try to push workarounds for the JSON parsers in the importer software.

In the attachment, only the first test-cube is validated by the JSON parser as correct.
In the blender-importer [1], the second one stops with python `TypeError: list indexes must be integers or slices, not float`, the third one loads without an error, which is in my opinion a mistake.

[test-NaN.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2344880/test-NaN.zip)

I have created an issue only here, but it affects both
[1] https://github.com/julienduroure/gltf2-blender-importer
[2] https://github.com/KhronosGroup/glTF-Blender-Exporter

**Comment by julienduroure** [comment]
I added some checks in the importer, in commit 2c04f2b0d4286d4d61f26e598c158b2385b3523f

**Comment by emackey** [comment]
Thanks for filing this @capnm, you are correct that Godot should not be adding any workarounds for NaNs.  As you've already noticed, such values are disallowed by glTF spec, JSON spec, and the glTF Validator.  Filing bug reports on any importers/exporters that produce or accept such values is appreciated.

**Comment by julienduroure** [comment]
I rename this bug, as it is only an exporter issue (importer part is solved)

**Comment by UX3D-hanselmann** [comment]
fixed in commit https://github.com/KhronosGroup/glTF-Blender-IO/commit/f430acceef80d35651721f1dd210a4fb3332e572
