### ISSUE TITLE
Add KHR_materials_unlit support to importer

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#220]
Following #211, the importer should set up a "background" node when it sees the `KHR_materials_unlit` extension.

![unlitmaterial](https://user-images.githubusercontent.com/1235080/50860041-eae35300-1362-11e9-8f02-3207a4600213.png)

**Comment by emackey** [comment]
New sample model in https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest

**Comment by emackey** [comment]
Implementation node:  If there's a BaseColor texture, it should get attached to the Color input of the Background node, with the BaseColorFactor multiplied in if needed.  ALL other textures and factors (O/R/M, Emissive, Normal) will be ignored (NOT imported) when `KHR_materials_unlit` is set.

**Comment by emackey** [comment]
Is it wrong to connect an Image Texture node or RGB node directly to material output?  I realize it's a type mismatch, but it looks like Blender doesn't mind.

**Comment by julienduroure** [comment]
@emackey This works on 2.80, but doesn't seem to work on 2.79
@donmccurdy 2.79 has shadeless checkbox only blender internal, not for Cycles.

Seems the LightPath trick is the better way for 2.79, and Background node for 2.80

**Comment by donmccurdy** [comment]
My suggestion would be:

Importer:

- Creates a 'shadeless' (Principled BSDF?) material on import in 2.79
- Creates Background node for 2.80+

Exporter:

- Writes unlit material for Background node
- Writes unlit material for Emissive node _if_ material does not also have a Principled BSDF node
- Writes unlit material when shadeless checkbox is selected

In that case the LightPath trick will export correctly (the emissive node alone implies unlit) but it isn't required that users do so. I realize this means the importer is creating a material that only appears unlit in Blender Render mode in 2.79, but it seems like a shame to not use the shadeless checkbox when it's there...

**Comment by julienduroure** [comment]
I updated my branch with nodetree with 2.79, using emission node + lightpath "is camera ray"

**Comment by donmccurdy** [comment]
Thanks!

**Comment by julienduroure** [comment]
Seems we have to reopen this discussion, because of #271 
Seems with our Background node setup, we can't handle alpha in texture.
#271 is already fixed for 2.79

**Comment by donmccurdy** [comment]
Ah that's frustrating. 😞

If it's OK with everyone, I'll write up a summary of our questions and issues with importing and exporting unlit materials (this issue) and AO (#123), share that for your review, and then if agreed we can post in the Blender forums for suggestions on these issues.

**Comment by julienduroure** [comment]
@donmccurdy OK for me.

Waiting a better solution, I propose to implement path light setup for 2.80 too

**Comment by donmccurdy** [comment]
Sure. Per https://github.com/KhronosGroup/glTF-Blender-IO/issues/220#issuecomment-455811913 I don't think that export should require the light path setup; just an emissive material that doesn't contain a Principled node. But if the importer sets the whole light path up that's fine.
