### ISSUE TITLE
Error when exporting in gltf

### ISSUE THREAD

**Issue by marioxaxa** [KhronosGroup/glTF-Blender-IO#2202]
**Describe the bug**
I get this error when I try to export my scene in gltf.

**To Reproduce**
1. Download my scene
2. Open on blender
3. Export to gltf

**Expected behavior**
I expected a clean export

**Error**
`Traceback (most recent call last):                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\__init__.py", line 1131, in execute                                                                                                                       return gltf2_blender_export.save(context, export_settings)                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                            File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 39, in save                                                                                                    json, buffer = __export(export_settings)                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 56, in __export                                                                                                __gather_gltf(exporter, export_settings)                                                                              File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 85, in __gather_gltf                                                                                           active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                             File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 30, in gather_gltf2                                                                                            scenes.append(__gather_scene(blender_scene, export_settings))                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached                                                                                    result = func(*args, **kwargs)                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 84, in __gather_scene                                                                                          node = gltf2_blender_gather_nodes.gather_node(                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 42, in gather_node                                                                                       mesh = __gather_mesh(vnode, blender_object, export_settings)                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 314, in __gather_mesh                                                                                    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached                                                                                    result = func(*args, **kwargs)                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 58, in gather_mesh                                                                                        primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),                                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 135, in __gather_primitives                                                                               return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached                                                                                    result = func(*args, **kwargs)                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 57, in gather_primitives                                                                            blender_primitives, addional_materials_udim = __gather_cache_primitives(materials, blender_mesh, uuid_for_skined_data,                                                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached                                                                                    result = func(*args, **kwargs)                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 124, in __gather_cache_primitives                                                                   blender_primitives, additional_materials_udim, shared_attributes = gltf2_blender_gather_primitives_extract.extract_primitives(                                                                                                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 30, in extract_primitives                                                                   primitive_creator.manage_material_info() # UVMap & Vertex Color                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 398, in manage_material_info                                                                base_material, material_info = get_base_material(material_idx, self.materials, self.export_settings)                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_materials.py", line 542, in get_base_material                                                                   material, material_info = gather_material(                                                                                                        ^^^^^^^^^^^^^^^^                                                                            File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 36, in wrapper_cached                                                                                    result = func(*args, **kwargs)                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_materials.py", line 76, in gather_material                                                                      emissive_factor = __gather_emissive_factor(blender_material, export_settings)                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_materials.py", line 210, in __gather_emissive_factor                                                            return export_emission_factor(blender_material, export_settings)                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                      File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_gather_materials_emission.py", line 22, in export_emission_factor                                           factor = get_factor_from_socket(emissive_socket, kind='RGB')                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_search_node_tree.py", line 253, in get_factor_from_socket                                                              fac = get_const_from_socket(socket, kind)                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                             File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_search_node_tree.py", line 284, in get_const_from_socket                                                               prev_node = previous_node(socket)                                                                                                   ^^^^^^^^^^^^^^^^^^^^^                                                                                     File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_search_node_tree.py", line 330, in previous_node                                                                       prev_socket = previous_socket(socket)                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^                                                                                 File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_search_node_tree.py", line 316, in previous_socket                                                                     socket = [s for s in sockets if s.name == socket_name][0]                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^                                                           IndexError: list index out of range `

**.blend file/ .gltf (mandatory)**
[SitePortifolioVersão3.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14974798/SitePortifolioVersao3.zip)

**Version**
 - OS: Windows 10
 - Blender Version 4.1

**Additional context**
I've been using some addons to get materials

**Comment by julienduroure** [comment]
Hello,
Seems something is wrong with the zip file you attached, I am not able to unzip it correctly.
Can you please try again to upload?

**Comment by marioxaxa** [comment]
Ok. I'm having trouble uploading the zip cause is too big. I've excluded almost everything and I cannot compresses it to bellow 25 MB. Is there a right way to compress a blender file? I'm just compressing it with winrar.

**Comment by julienduroure** [comment]
Not sure why your file is so big.
Because the issue comes from materials, please create a very simple file (only the default cube) and set the material to that cube. Verify that the export still crashes, and then upload this file.

**Comment by marioxaxa** [comment]
So... I kinda figured it out. Apparently the gltf doesn't support some nodes in some materials that I was using, so I excluded that materials.

**Comment by julienduroure** [comment]
More than a month without any news, I will close this ticket.
Feel free to comment with a simple test file if you want me to have a look
