### ISSUE TITLE
gltf file import fail

### ISSUE THREAD

**Issue by dxlyf** [KhronosGroup/glTF-Blender-IO#2205]
**Describe the bug**
This gltf file, Threejs and Babylon, were successfully imported, but not in Blender. It prompts: "Couldn't part glTF. Check that the file is valid"

**To Reproduce**
1. click file
2. import gltf2.0
3. Prompt error

**Expected behavior**
Couldn't part glTF. Check that the file is valid".

**Screenshots**
none

**.blend file/ .gltf (mandatory)**
[AR-地下室.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15040382/AR-.zip)

**Version**
 - OS: window11
 - Blender Version 4.0

**Comment by julienduroure** [comment]
Hello,
You may have not upload the right files, as the provided files is not valid (missing some .bin files), and can't be opened in babyloon and threejs


KO on all of these:
- https://github.khronos.org/glTF-Validator/
- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/

**Comment by dxlyf** [comment]
> Hello, You may have not upload the right files, as the provided files is not valid (missing some .bin files), and can't be opened in babyloon and threejs
> 
> KO on all of these:
> 
> * https://github.khronos.org/glTF-Validator/
> * https://gltf-viewer.donmccurdy.com/
> * https://sandbox.babylonjs.com/

You can take my attachment for testing, my file is in the https://github.khronos.org/glTF-Validator/ Verified, no problem. And I am https://threejs.org/editor/ Can be imported normally

**Comment by julienduroure** [comment]
Hello,
I confirmed that I, of course, tested with the file you provided.

1. Seems like an encoding issue.
2. The uri link is:

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/f9385d41-c7dd-4dd0-8e26-5d303d13fc62)

But there is no file named like this in your zip:

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/fb33aa0a-54bb-4680-89dc-f5eea2830dab)


3. Your file is not valid anyway : 
all sampler data is float on your file, where integer are requested : 

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/b51fe914-bc8b-4659-a038-0bd7cd45a712)

**Comment by dxlyf** [comment]
> Hello, I confirmed that I, of course, tested with the file you provided.
> 
> 1. Seems like an encoding issue.
> 2. The uri link is:
> 
> ![image](https://private-user-images.githubusercontent.com/1696020/323982858-f9385d41-c7dd-4dd0-8e26-5d303d13fc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mzc5MDgsIm5iZiI6MTcxMzUzNzYwOCwicGF0aCI6Ii8xNjk2MDIwLzMyMzk4Mjg1OC1mOTM4NWQ0MS1jN2RkLTRkZDAtOGUyNi01ZDMwM2QxM2ZjNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTQ0MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYyZWU2ODk2NzNkOTE5YzQ3MDA0OGE4ZWFjM2E3N2VjYjg0ZWM5ODEzNWEwYzU3Y2IwYTIxMjZhMDA2NmNkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2omVGzD2zg5D2UdoQA76-1AS8_3d594X_2wOz6z6mds)
> 
> But there is no file named like this in your zip:
> 
> ![image](https://private-user-images.githubusercontent.com/1696020/323983065-fb33aa0a-54bb-4680-89dc-f5eea2830dab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mzc5MDgsIm5iZiI6MTcxMzUzNzYwOCwicGF0aCI6Ii8xNjk2MDIwLzMyMzk4MzA2NS1mYjMzYWEwYS01NGJiLTQ2ODAtODlkYy1mNWVlYTI4MzBkYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTQ0MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhkNDk0NjhiNjJkNGJmNWU4ZTFjZTRkODVmNmUxOWE0NGI3NDgyNmU5YmViYWRjNDFlODA5ZTUyZjhiZDI3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4lnOSC_lm8Pvr4W-jFhS1IdY8kxBmuVp6ZNg4DRV9Ws)
> 
> 3. Your file is not valid anyway :
>    all sampler data is float on your file, where integer are requested :
> 
> ![image](https://private-user-images.githubusercontent.com/1696020/323982488-b51fe914-bc8b-4659-a038-0bd7cd45a712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mzc5MDgsIm5iZiI6MTcxMzUzNzYwOCwicGF0aCI6Ii8xNjk2MDIwLzMyMzk4MjQ4OC1iNTFmZTkxNC1iYzhiLTQ2NTktYTAzOC0wYmQ3Y2Q0NWE3MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMTQ0MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg3MWZiZjE1ZmZmOGY3YjRiYjczMzlmZTViOTY0MTdmNTJlNWUxZjFjZmMyZWIwNGE1Yzg4NmYxMGZlNjE1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xBI93exLCY8zIq4-A4iEJV-xzID4Ix4wHQKpMoK36OA)

Thank you, it is confirmed that the cause is the "sampler" floating-point number, but other software is working properly, which caused me to not carefully check this data. This model is derived from
