### ISSUE TITLE
Vertex Color is exported when no material is present despite "Data > Mesh > Attribute" unchecked

### ISSUE THREAD

**Issue by Olaf-Wolf3D** [KhronosGroup/glTF-Blender-IO#2210]
**Describe the bug**

When a mesh with a color attribute does not have a material, the vertex color is exported despite _Data>Mesh>Attribute_ being **unchecked**.
It was working correctly in Blender 3.6.8 (which still had a "Data > Mesh > Vertex Colors" option).
This new behavior is not documented either (https://docs.blender.org/manual/en/4.1/addons/import_export/scene_gltf2.html#data-mesh).
The breaking change was only mentioned here: https://github.com/KhronosGroup/glTF-Blender-IO/issues/2063#issuecomment-1822293451

**To Reproduce**
1. Create a mesh without a material
2. Set a color attribute
3. Go to "File > Export > glTF 2.0"
4. UNCHECK "Data > Mesh > Attributes"
5. exported file still has COLOR_0 attribute

**Expected behavior**
The vertex color attribute is not exported when "Attributes" is unchecked, regardless of whether there's a material or not. Or any other option to not export vertex colors without adding other data, if "Attributes" is reserved for attributes beginning with an underscore. Otherwise, this is very surprising and illogical behavior.

**.blend file/ .gltf (mandatory)**
[VC-export-bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15075472/VC-export-bug.zip)

**Version**
 - OS: Windows 11
 - Blender Version 4.1.1

**Additional context**
This change messes with our pipeline. I can't just include a blank material to not export VC, because then I'd have to get rid of it **after** I exported the file. Removing the color attribute from files altogether would create other inconveniences and it would be weird to try to find a workaround for this unexpected behavior of the exporter. There has to be a way to not include VC in the export as a setting, rather than having to introduce other unwanted data (material) instead.

I also tried prefixing the color attribute with an underscore, which did nothing.

**Comment by julienduroure** [comment]
Hello,
Seems some users want it, and some others (like you) doesn't.
This will be added in 4.2 with an option to export or not active VC when no material is there.
