### ISSUE TITLE
Question - How to stop export changing tif to png?

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#2212]
**Is your feature request related to a problem? Please describe.**
I need to keep my material texture a tif format

**Describe the solution you'd like**
I need to stop the export to gltf from changing a tif to png.  The Material export setting only has Automatic, and JPEG.  I need a "No Change" option

**Describe alternatives you've considered**
Manually changing the gltf image json

**Additional context**

**Comment by ronh991** [comment]
Follow up - using "keep original" check box gives me this in the gltf

	"images":[
		{
			"mimeType":"image/png",
			"name":"myfile.tif",
			"uri":"myfile.tif"
		}

That just does not look correct to me.

**Comment by julienduroure** [comment]
As far as I know, only jpeg or png are allowed in the specification, so tif are converted at export.

Using "Keep original" was at first added to export to glTF, some glTF file that was imported, without calculate again the shader. That means that we shouldn't have some tif image here.
Seems we need to add some warning and check for this case...

**Comment by DRx3D** [comment]
glTF files are limited to JPEG and PNG images (https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_image_mimetype). The KHR_texture_basisu add KTX to the allowed list. So it is not possible to output legal glTF with TIFF.

Note that "keep original" should not output a MIM type of image/png with files that TIFF.

**Comment by ronh991** [comment]
That is unfortunate.  Agree it's not a legal gltf, but I figure I could use my own extension or hook to texture or image.  I can't because I cannot get the image_data or uri data in my hook.

For reference this is for Microsoft Flight Simulator - and they can use tif files (although they get changed to dds anyway.)

The work around it to manually change the uri to tif, from png as the mime/type is ignored in MSFS.  (or it seems to be)

Can close this issue.  Thanks

**Comment by julienduroure** [comment]
Hello,
Closing this ticket, as the requirement is not compliant with glTF specification.
I opened 2 new tickets:
- #2214 to have better checks on "keep original"
- #2215 to provide some hook, to be able to add some extra or extension with the original image file
