### ISSUE TITLE
Problem exporting gltf Punctual Light and Full Collection Hierarchy

### ISSUE THREAD

**Issue by daniel-dron** [KhronosGroup/glTF-Blender-IO#2216]
**Describe the bug**
Can't export gltf scene when both "Include>Data>Punctual Lights" and "Scene Graph>Full Collection Hierarchy" are enabled.

**To Reproduce**
1. Create new blender scene
2. Add a point light
3. File > Export > GLTF 2.0
4. Enable "Include>Data>Punctual Lights"
5. Enable "Scene Graph>Full Collection Hierarchy"

**Expected behavior**
Scene to be exported with both light information and the scene hierarchy

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/19430633/ccb6630f-5171-42bd-b274-ed36d168d5d6)

**.blend file/ .gltf (mandatory)**
[untitled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15168040/untitled.zip)

**Version**
 - OS: Windows 11 (Intel + Amd gpu)
 - Blender Version 4.1

**Additional context**
Turning "Scene Graph>Full Collection Hierarchy" seems to work, but I do need the full hierarchy.

**Comment by julienduroure** [comment]
Hello,
Thanks for the reporting, but this bug is already fixed in main branch.
Closing this ticket

(See https://github.com/KhronosGroup/glTF-Blender-IO/pull/2190)
