### ISSUE TITLE
Textures Not Included in GLB File

### ISSUE THREAD

**Issue by okamototomoyuki** [KhronosGroup/glTF-Blender-IO#2219]
**Describe the bug**
When I export the attached .blend file to .glb, the textures are not included.

**To Reproduce**
1. Open the attached .blend file in Blender 4.1.
2. Navigate to File > Export > glTF 2.0.
3. Use the following settings and press the Export glTF 2.0 button:
    Format: glTF Binary (.glb)
    Include > Limit to: Active Scene
4. Open the exported .glb file in a viewer such as https://gltf-viewer.donmccurdy.com/.

**Expected behavior**
The textures should be displayed.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/68187390/ec135d03-de67-4ddc-8108-1ed03d3c5597)

**.blend file/ .gltf (mandatory)**
[model.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15178030/model.zip)

**Version**
 - OS: Windows 11 Home 23H2
 - Blender Version: 4.1.1

**Additional context**

**Comment by julienduroure** [comment]
Hello,

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/7b2992b4-5cec-49e5-9981-4ee4dde0d7b6)

Your node tree is not compatible with glTF shader specification.
glTF is either based on PBR setup, or unlit.
Not all nodes can be translated in glTF specification, so we can't export your shader into glTF.

I can recommend you to simplify your setup, or to bake your material into a compatible PBR or unlit setup

You can refer to the documentation to check what is compatible:

https://docs.blender.org/manual/en/4.0/addons/import_export/scene_gltf2.html#exporting-a-shadeless-unlit-material
https://docs.blender.org/manual/en/4.0/addons/import_export/scene_gltf2.html#example

Closing this ticket
