### ISSUE TITLE
Import failure due to missing 'animations' attribute (KHR_animation_pointer)

### ISSUE THREAD

**Issue by The0Dev** [KhronosGroup/glTF-Blender-IO#2220]
Hello! I encountered some issues while trying to import certain assets that use KHR_animation_pointer.

**Describe the bug**
The attached asset cannot be imported due to a missing attribute.

**To Reproduce**
1. Import the asset
2. See the error

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/98645239/2055f7e0-9cb6-4938-b778-256d60db8406)

**Expected behavior**
The asset should be imported properly.

**.blend file/ .gltf (mandatory)**
[anim_pointer_crash.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15178365/anim_pointer_crash.zip)

**Version**
 - OS: Linux
 - Blender Version: 4.2

**Comment by julienduroure** [comment]
Confirmed
