### ISSUE TITLE
Cameras that are made the child of an Collection instance should be exported by the gltf exporter

### ISSUE THREAD

**Issue by levilime** [KhronosGroup/glTF-Blender-IO#2221]
**Is your feature request related to a problem? Please describe.**

I have a scene currently where I would like the camera to follow a [instance](https://docs.blender.org/manual/en/latest/scene_layout/object/properties/instancing/collection.html) and ease animation efforts by making it a child of the collection instance. I'd like to show this scene in glTF. But this camera added as child to the collection instance is not exported in the glTF, although the `Cameras` option is turned on, and the other cameras not part of a collection instance are exported.

**Describe the solution you'd like**

I would like the cameras that are children of the collection instance also to be exported.

**Describe alternatives you've considered**

Alternatively I could:
- Animate the follow animation for the camera that follows the Collection instance, and not have it be a child. Then it will export.
- Use an `object constraint`

**Additional context**

glTF plug in version: `4.1.62`
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5917975/0d5d0ab8-3790-4999-a7e3-6f33c0bc8dfa)

**Comment by levilime** [comment]
Thanks in advance, I love the glTF specification and blender exporter, really cool 🥇

**Comment by julienduroure** [comment]
Confirmed (and not limited to Camera : all children of instanced collection are ignored for now)
