### ISSUE TITLE
When there is a light existing in an Collection Instance and lights export is on, (.blend linked import) exporting of glTF fails

### ISSUE THREAD

**Issue by levilime** [KhronosGroup/glTF-Blender-IO#2222]
**Describe the bug**

**To Reproduce**
1. Open the attached `test.blend`, which has an Collection instance that has a light (`defaultcube.blend`)
2. Export glTF, with:
     - Include -> Punctual Lights checked on
4. Click on Export glTF 2.0
5. See error

**Expected behavior**
The lights are correctly able to export from the collection instance. Possibly flattened in the scene.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/5917975/99435871-a6b8-4d54-940a-003f083372c2)

**.blend file/ .gltf (mandatory)**
[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15236558/Archive.zip)

**Version**
 - OS: macOS
 - Blender Version 4.1

**Comment by julienduroure** [comment]
Hello,
Thanks for the reporting.
This bug was already reported, and already fixed on main branch (that will become 4.2)
Closing this ticket

**Comment by levilime** [comment]
Ah I see, fixed in https://github.com/KhronosGroup/glTF-Blender-IO/pull/2217, great!
