### ISSUE TITLE
GLTF Export Animation Wrong Bone Transforms (Rigify)

### ISSUE THREAD

**Issue by InnPatron** [KhronosGroup/glTF-Blender-IO#2223]
# Problem

* Certain area in exported animation are not correct
* Rig generated from Rigify
  * Relevant bone group: "Dress (Upper)"
  * Area generated with `skin.basic_chain`
    * As far as I can tell, bendy bones in the relavent area have already been disabled (set to `1` segment)
* Uses a custom (but not crazy) export script (`game-export.py`)
  * `export_reset_pose_bones` does not appear to affect the issue (#2104)
* Looks like the deform bones in the original animation behave similarly to the exported version. The exported version looks more exaggerated. Maybe this is a math error in the baking calculations? Something to do with parenting?

Export operation:

```
bpy.ops.export_scene.gltf(
        filepath=exportPath,
        export_format="GLTF_SEPARATE",
        export_bake_animation=True,
        # Does not appear to be the issue?
        export_reset_pose_bones=False,
        use_renderable=True,
        export_def_bones=True,
        export_apply=True,
        export_anim_slide_to_zero=True)
```

## Reproducing

1. Download `min-repo.zip` and export with `export.sh` (calls a custom `game-export.py` script) that outputs to `./export/`
2. Import GLTF file and observe around the armpit area (should only be one action: `idle-stretch_hannah-rig`)

`import-annotated.blend` has what I see under the `ERROR` bone group

Minimum reproduction: [min-repo.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15284877/min-repo.zip)

## Expected Behavior

Animations should match

Original:

![Original](https://github.com/KhronosGroup/glTF-Blender-IO/assets/31705558/3a4fe408-e6d6-4a05-b44e-1d58e6ed0d0f)

Exported:

![Bad Export](https://github.com/KhronosGroup/glTF-Blender-IO/assets/31705558/3050a32e-b63f-4f6b-8113-bcf4948d29d1)

## Machine Config

* Kubuntu 22.04
* GLTF exporter version: 4.0.44
* Blender from Snapstore
  * Blender 4.0.2
  * Build hash: 9be62e85b727

**Comment by InnPatron** [comment]
Looks like setting `export_hierarchy_flatten_bones=True` fixes the issue, but I am not sure why that is the case.

The rig around that area is pretty simple. Trying to remove the retargeted constraint on `sleeve.anchor.B.R` and `sleeve.anchor.B.L` didn't affect anything.

**Comment by julienduroure** [comment]
There are multiple things here:
- Some non uniform scaling can lead to non decomposable matrices, that cannot be written in glTF files. See #1683, for example, for another case of this issue. Using `export_hierarchy_flatten_bones=True` avoid this issue by flatten the hierarchy of bones at export.
- You have some vertices that are influenced by more than 4 bones. By default at export, only the 4 biggest weights are used. You can change this value, or decide to use all influences at export.

Using these options solve your issues: 

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/dcbea82d-ca95-4c97-859c-4b0cf2a1bcdf)


Here is repo.blend with reimport of the export, in wire. Seems that everything is ok:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/1b5b35cb-f0f7-4ace-b0ae-91370aa18cd2)

**Comment by InnPatron** [comment]
Thanks for the reply!

Looks like my export target (Godot) supports 8 max, but I still have too many influences there. I'll rework the rig and bump up the export maximum instead of allowing unlimited influences.
