### ISSUE TITLE
JPEG Quality Bypassed if Textures Already in JPEG

### ISSUE THREAD

**Issue by FabioOrsi** [KhronosGroup/glTF-Blender-IO#2224]
Changing the settings for JPEG Quality makes no difference in the output GLB if all textures are already in JPEG. Apparently, the quality settings are bypassed if the textures are in JPEG.

1. Setup a model with all textures in JPEG.
2. Export it using JPEG compression at different quality levels.
3. Check file size for each.

It would be expected to get different file sizes, but they're all the same.

 - OS: Windows 11
 - Blender Version 4.1.1

**Comment by julienduroure** [comment]
Hello,
Can you please provide a test .blend file?
Behavior depends on channel merging that can be performed or not - depending on your node setup

**Comment by julienduroure** [comment]
More than a month without any answer, closing this ticket.
Feel free to comment and provide the .blend file if you want me to have a look
