### ISSUE TITLE
bpy.context.preferences.addons does not contains every loaded addon

### ISSUE THREAD

**Issue by gmendieta** [KhronosGroup/glTF-Blender-IO#2225]
Blender has two methods to force loading addons during startup. For instance:

1. You can use --addons flag to force loading several addons. **blender.exe --addons A,B,C**
2. You can use a custom python script to force loading several addons using the addon_utils module. This custom script could be executed using **blender.exe --python A.py**

In our case, we use this methods to check if some of our addons are registered and loaded. If they are not, we do load them. This addons register custom hooks to the offiial GLTF exporter. The file __init__.py in the official GLTF addon, in the line 830 aprox uses bpy.context.preferences.addons to check loaded addons and search custom hooks within them. The collection bpy.context.preferences.addons do not contains startup loaded addons.

**Expected behavior**
The addons should be able to register custom hooks from the startup loaded addons

**Version**
 - OS: Windows
 - Blender Version 3.6 LTS

**Comment by gmendieta** [comment]
Just to make it clear, we have modified __init__.py in the next way:
`import sys
        # preferences = bpy.context.preferences
        # for addon_name in preferences.addons.keys():
        import addon_utils
        for addon_module in addon_utils.modules():
            addon_name = addon_module.__name__
            try:
                _, loaded_state = addon_utils.check(addon_name)
                if not loaded_state:
                    continue
                module = sys.modules[addon_name]
            except Exception:
                continue
            print(f'Checking glTF2ExportUserExtension in {addon_name}')
            if hasattr(module, 'glTF2ExportUserExtension'):`

**Comment by julienduroure** [comment]
Hello,

glTF-Blender-IO addon is enabled by default by Blender itself.
I suspect that user defined addons are not loaded before.

Don't think there is something we can do here.
Checking addon loaded or not during loading of any addon is probably not a good idea, as we can't ensure order of loading

**Comment by gmendieta** [comment]
The code i modified belongs to to operator execute method so i think the problem is that user preferences does not contain the loaded addons at startup. Regarding the order of loading i guess that's the reason why GLTF addon checks for loaded addons within invoke and execute methods.
I will check the modified code for a while and lets you know here. 
Thanks

**Comment by julienduroure** [comment]
More than a month without any new information, closing this ticket.
Feel free to comment  if you have some new input information about it
