### ISSUE TITLE
Exported tangents seem to be different from what Blender shows

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/glTF-Blender-IO#2226]
**Describe the bug**

- Exported tangents do not match tangents seen in Blender.
- The attached blend uses shader nodes to visualize tangents.
- The main issues is discontinuity in exported monkey head model tangents.
- The difference in colors in can be ignored, as blender internally might use different up-axis.

**To Reproduce**
1. Load attached blend
2. Examine how it looks lin Blender
3. Export to glTF with tangents
4. See how it looks in (glTF viewer that can show tangents)

**Expected behavior**
Tangents look similar in Blender and glTF viewer

**Screenshots**

This is how attached test asset looks in Blender 4.1.1:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/994606/a4d90912-82c7-4bf1-936b-6c25aafaed3e)

This is how exported glTF looks in erhe - without modifiers - notice Suzanne discontinuity:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/994606/529eddff-bfa6-4d18-ac9c-ca03bc232eef)
This is how exported glTF looks in erhe - with modifiers applied - notice additional discontinuity in all models with mirror modifier:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/994606/fbbfbce6-a994-4275-938e-055554cc3fd1)

**.blend file/ .gltf (mandatory)**
[tangent_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15305778/tangent_test.zip)

**Version**
 - OS: Windows
 - Blender Version 4.1.1

**Additional context**
I would very much like to see what the exported glTF looks in other glTF viewers, but I don't know which ones would support showing tangents like this.
erhe is my own sandbox: https://github.com/tksuoran/erhe

**Comment by tksuoran** [comment]
My default vertex shader - used in issue screenshots above:
```glsl
vec3 tangent = normalize(vec3(world_from_node_cofactor * vec4(a_tangent.xyz, 0.0)));
```
Vertex shader experiment (results below):
```glsl
vec3 tangent = normalize(vec3(world_from_node_cofactor * vec4(a_tangent.xyz * a_tangent.w, 0.0)));
```
The experiment results:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/994606/60b23291-2d86-4ade-bab3-f3f5806cc9f4)

Multiplying `tangent.xyz` with `tangent.w` makes the version that uses mirror modifier look more consistent with the version of models that do not use mirror modifier. But the the discontinuity in Suzanne is still there, also, cube is not fully consistent.

This could just be a coincidence. I don't think the tangent.xyz should be multiplied with tangent.w like that, it is only for bitangent computation.. Right?

**Comment by julienduroure** [comment]
Hello,
Duplicate of #920?

**Comment by tksuoran** [comment]
> Hello, Duplicate of #920?

There are other uses for tangents, not just normal mapping, for example, anisotropic light reflection. But yes, the tangents that the glTF exporter uses dont seem to match with the tangents seen in the shader node visualization.

**Comment by tksuoran** [comment]
It looks like:
- Blender shows tangents generated by cylindrical projection around up axis (maybe because there is no normalmap in use, or something similar)
- glTF exporter gets tangents from some other path, one which uses texture coordinates for tangent generation
I would like to know how Blender has these two different ideas about tangents, and if glTF exporter could somehow access the same set of tangents that Blender shows.
I think the asset attached in this issue _might_ be different issue than #920.

**Comment by scurest** [comment]
> glTF exporter gets tangents from some other path, one which uses texture coordinates for tangent generation

Yes, it gets it by calling `mesh.calc_tangents()`, which uses the active UV map. This script will copy the data from `calc_tangents` to a color attribute "Tangent Color" for visualization. You'll have to apply modifiers for the meshes with modifiers first.

```py
import bpy
from mathutils import Vector

def create_tangent_colors(mesh):
    attr_name = 'Tangent Color'
    if attr_name in mesh.attributes:
        mesh.attributes.remove(mesh.attributes[attr_name])

    attr = mesh.attributes.new(name=attr_name, domain='CORNER', type='FLOAT_COLOR')
    mesh.calc_tangents()
    for i, loop in enumerate(mesh.loops):
        t = loop.tangent
        # Zup2Yup, Blender space -> glTF space
        t = Vector((t.x, t.z, -t.y))
        # Vector [-1,1] -> Color [0,1]
        t = 0.5 * t + Vector((0.5,)*3)
        # Note: sRGB
        attr.data[i].color_srgb = [*t, 1]
    
    mesh.update()

for ob in bpy.context.selected_objects:
    if ob.type == 'MESH':
        create_tangent_colors(ob.data)
 ```

The result is what you've already shown

![](https://github.com/KhronosGroup/glTF-Blender-IO/assets/11024420/224c1d93-1cc1-4dba-bd3d-b6ffd7de8e38)

**Comment by tksuoran** [comment]
I think I got this resolved.

I got confused with Geometry vs. Tangent nodes as seen below:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/994606/58efe12c-10cd-4cba-afbe-319fc889df1c)

Using Tangent node, blender output looks consistent with tangents from glTF exporter.
