### ISSUE TITLE
Materials with roughness texture dont export correctly

### ISSUE THREAD

**Issue by maoliver-amd** [KhronosGroup/glTF-Blender-IO#2228]
**Describe the bug**
When exporting a material that has a single texture attached to the roughness parameter the final exported texture used by GLTF does not include the data from the roughness texture. GLTF export combines both metallicity and roughness into a single texture, however it appears that the roughness texture is not correctly being transferred to the ouput combined GLTF texture

**To Reproduce**
1. Create a material with a texture connected to the roughness parameter
2. Export GLTF
4. Compare exported combined metal+rough texture which will just be an all white texture (roughness should be in the GREEN channel)

**Expected behavior**
Since only the roughness texture is attached the generated texture should have its green channel set to the input texture while all other channels should be set to 255 (assuming 8bit)

**Screenshots**
Example material:
<img src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/101073406/1ecb6221-8461-4ab8-b0d0-296afbb10559" width="400" height="400">
Texture attached to roughness:
<img src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/101073406/ad51291b-8e11-4d68-968f-5c7255b6bd4c" width="400" height="400">
Texture exported with GLTF:
<img src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/101073406/329a49f1-8259-4524-b71b-187f120c020b" width="400" height="400">

**.blend file/ .gltf (mandatory)**
[blenderTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15317248/blenderTest.zip)

**Version**
 - OS: Windows
 - Blender Version: 4.1

**Comment by julienduroure** [comment]
Hello,
Yes, can not find any issue here:
- Your texture is B&W, so alpha is 1 => Roughness is 1.0 in texture ( Green channel)
- Metallic factor is on json 0.777 + texture Red channel 1.0
