### ISSUE TITLE
Deform bones not showing up in UE5 when using Child of Constraint

### ISSUE THREAD

**Issue by Disar** [KhronosGroup/glTF-Blender-IO#2230]
**Describe the bug**
I understand that constraints need to be baked, but the problem is that all of the bones disappear with the exception of none deform bones and the root when i try to load the glb into unreal. Without the constraint it's perfectly fine

**To Reproduce**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7016049/b3d10e8e-19cb-480b-ba15-c47229415605)
In blender the green bones have `child of` set to the red bone. 
Sampling is turned on at export and bake all Objects Animations doesn't make a difference.

**Expected behavior**
All bones should be imported in ue5

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/7016049/eb7d75af-ad74-448a-9d9a-1fdd75211236)

**.blend file/ .gltf (mandatory)**
[gltfexportbones.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15328809/gltfexportbones.zip)

**Version**
 - OS: win11
 - Blender Version 4.1.1
 
**Additional context**
This might be an issue with Unreal but so far it only happens when i try to export skeletal meshes/animations that use a constraint ( child of constraint in this case ). IK constraints work perfectly fine however.

**Comment by julienduroure** [comment]
Hello,
Reimporting in Blender shows that all 10 bones are here.

Checking the exported file shows the 10 joints exported:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/34322d40-1d5f-44b9-8b18-4009dfa5bd4a)

Can't find any issue here, at first look.

**Comment by Disar** [comment]
That's weird, then I don't know. UE5 doesn't throw an error either. It only happens with the constraints 🤔
Ill check later if Godot has the same issue.

**Comment by julienduroure** [comment]
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/68c4e564-877e-43b8-b640-073c76fc111f)

**Comment by Disar** [comment]
sigh, thanks for checking it out.
I guess UE5 is the culprit here, is there anything specific that's different in the file when using/baking with constraints?

**Comment by julienduroure** [comment]
They can have some difference is bone is a deformation bone or not, but we don't check if bones have constraint or not.

**Comment by julienduroure** [comment]
More than a month without any answer, closing this ticket.
Feel free to comment and provide new information if you want me to have a look
