### ISSUE TITLE
[suggestion] add ability to export meshes name using nodes (objects) name

### ISSUE THREAD

**Issue by Vinc3r** [KhronosGroup/glTF-Blender-IO#224]
Usually, Blender user name his objects using the Object Properties tab and not in Mesh tab (it is annoying to copy-paste values, especially in large scenes), and so, logically, the exporter name the node as the object name property, and the mesh as the mesh name property, which give us something like that in the gltf file:

```JSON
    "meshes": [
        {
            "name": "Cube",
            "primitives": [
                ...
            ]
        },
        {
            "name": "Cube.001",
            "primitives": [
                ...
            ]
        },
        {
            "name": "Cube.002",
            "primitives": [
                ...
            ]
        }
    ],
    "nodes": [
        {
            "mesh": 0,
            "name": "yep.000"
        },
        {
            "mesh": 1,
            "name": "something.000"
        },
        {
            "mesh": 2,
            "name": "aWeirdObject.000"
        }
    ],
```

It could be a great thing to add an exporter option in the `Meshes` tab to use object name, isn't it?

![img](https://i.imgur.com/U0YTk1b.png)

which could give us

```JSON
    "meshes": [
        {
            "name": "yep.000",
            "primitives": [
                ...
            ]
        },
        {
            "name": "something.000",
            "primitives": [
                ...
            ]
        },
        {
            "name": "aWeirdObject.000",
            "primitives": [
                ...
            ]
        }
    ],
    "nodes": [
        {
            "mesh": 0,
            "name": "yep.000"
        },
        {
            "mesh": 1,
            "name": "something.000"
        },
        {
            "mesh": 2,
            "name": "aWeirdObject.000"
        }
    ],
```

(Note that to not reinvent the wheel, [Name Stack](https://blendermarket.com/products/name-stack) addon have [such a functionnality](https://i.imgur.com/H8Ulnkk.png))

**Comment by donmccurdy** [comment]
/cc https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/207

I think I agree with @emackey's comment, that the current behavior is correct:

> Currently this exporter copies Blender node names to glTF node names, and copies Blender mesh names to glTF mesh names. It's hard to get any clearer than that. If you care about the mesh names, I feel like you should name the meshes appropriately in Blender. Most people shouldn't though, given that animations target nodes.

I'd prefer not to have an option for something so specific, it seems like a better use case for a separate script or addon. And what happens if a mesh is reused by multiple nodes?

**Comment by Vinc3r** [comment]
The old repo is still taken into account? Sorry for the duplication.

And I'm agree that the current behaviour still should be as it is.
I see this suggestion just as a gltf workflow enhancement. As I never encounter this mesh naming "issue" with other exporting formats, this is why I suggested this idea.

**Comment by donmccurdy** [comment]
> As I never encounter this mesh naming "issue" with other exporting formats....

Note that the issue you're describing has multiple parts beyond just what the exporter writes. If the engine is using mesh names where you expect to see node names, for example, that's perhaps part of the issue? But since the blender names map pretty clearly to glTF names, I don't think we can justify a change here.
