### ISSUE TITLE
Material channel mixup

### ISSUE THREAD

**Issue by UX3D-schmithuesen** [KhronosGroup/glTF-Blender-IO#226]
The blend file has separate grayscale images for `metallic` and `roughness`, but, the roughness ends up in `R` and the metallic ends up in both `G` and `B`, even after the fix in #139.  Not sure why.

_Originally posted by @emackey in https://github.com/KhronosGroup/glTF-Blender-IO/issues/116#issuecomment-445265585_

**Comment by donmccurdy** [comment]
Confirmed, here's a copy of the `.blend`:

[monkey_PBR_005.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2866850/monkey_PBR_005.blend.zip)

I'll move this to milestone VII since it appears to be an important regression, but let me know if it should not be there.
