### ISSUE TITLE
Manage more than 1 COLOR_X attributes

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#227]
Currently, only COLOR_0 is managed.
(see #212 where I found this problem)

Multiple question on how to handle more than one COLOR_X attribute:

- If material has no baseColor, how to handle? Blender can display only 1 vertex color at time
- If material has baseColor, vertex color is used as multiplier factor. Should I multiply each vertex color themself before multiply baseColor ?

@donmccurdy Any thoughts? Should I ask directly on glTF repo ?

**Comment by donmccurdy** [comment]
The spec mentions:

> In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property COLOR_0, then this value acts as an additional linear multiplier to baseColor.

So I think the importer should assume a default baseColor of `#fff` in this case, and multiply it against the first vertex color. Others vertex colors can be kept but not rendered; they may be used as extra data.

@emackey if that sounds right, perhaps the spec should be more explicit about additional vertex colors?

**Comment by emackey** [comment]
That sounds fine to me.  I guess we should ask if anyone is using more than one set of vertex colors.  But yes its seems like it's only meaningful to multiply one set of vertex colors at a time.

**Comment by emackey** [comment]
> If material has no baseColor, how to handle?

Agreed on `#fff` (white), it's the default BaseColorFactor, and it's what you see when the glTF doesn't specify anything else.

**Comment by julienduroure** [comment]
Hello @scurest 
After your changes, merged yesterday, we manage more than one COLOR_x, but not sure how this is handle in material stuff

**Comment by scurest** [comment]
Right now it's exactly as donmccurdy said above. The `COLOR_1`, etc. layers will be imported if they exist, but nothing is done with them. They don't affect the materials in any way.

**Comment by scurest** [comment]
@julienduroure What still needs to be done for this?

**Comment by julienduroure** [comment]
Seems this can be closed
