### ISSUE TITLE
Issue with Metallic PBR on export in 4.2 beta

### ISSUE THREAD

**Issue by StudioGalt** [KhronosGroup/glTF-Blender-IO#2270]
**Describe the bug**
When I try to export my avatar, it gives error with metallic roughness, it is saved in the text file.

**To Reproduce**
Export as GLTF, selected objects (should still be highlighted, if not body, head, armature) and it throws an error due to metallic roughness.

**Expected behavior**
It exports normally in 4.1, albeit with with api output.

**Screenshots**

**.blend file/ .gltf (mandatory)**
A zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.
If you are not allowed to share your file, make sure to create a new one from scratch that shows the issue. You can also try to delete or modify some data (objects, change textures, replace some meshes by some placeholder), to be able to share it without restriction.

**Version**
 - OS: Windows
 - Blender Version blender-4.2.0-beta+v42.965a13867111-windows.amd64-release

[SG ASL Bondage 2024-6-8 Finished w error.zip](https://github.com/user-attachments/files/15753492/SG.ASL.Bondage.2024-6-8.Finished.w.error.zip)

**Additional context**
Very new to GLTF, but hope to add as export option in 4.2

**Comment by julienduroure** [comment]
Hello,
I can not reproduce with the exact same version, on linux.
Can something with a Windows OK can test?

**Comment by julienduroure** [comment]
More than a month without any answer, 
closing this ticket
