### ISSUE TITLE
Export fails with exception

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#2271]
**Describe the bug**
I'm going through some of the older Blender splash screen files and testing whether they export cleanly as glTF by now.

**To Reproduce**
1. Download https://cloud.blender.org/p/gallery/5d2607ee6b3001d49bab798a
2. Open with latest Blender (e.g. 4.3 alpha)
3. Export as GLB

**Expected behavior**
Export works, even when not all scene content is exported

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/93f8877d-247f-4716-bb15-2898db2a8e42)

**Version**
 - OS: Windows 11
 - Blender Version
 - ![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/281fca64-80a8-4247-bff1-2e12e849f1af)

**Comment by julienduroure** [comment]
Confirmed.
Root cause is a lattice with armature.
We need to exclude lattice , this is not an object that we can/want to export

**Comment by julienduroure** [comment]
Here is a simple file that shows the issue
[lattice_skin_error.blend.zip](https://github.com/user-attachments/files/15928430/lattice_skin_error.blend.zip)
