### ISSUE TITLE
glb import error when None is given as a float parameter

### ISSUE THREAD

**Issue by ieskudero** [KhronosGroup/glTF-Blender-IO#2275]
**Describe the bug**
With a model exported with ThreeJS GLTF exporter, there is a case apparently where a float comes as None, and the blender addon crashes on importing the file.

**To Reproduce**
1. Open blender
2. Import the attached .GLB file
4. Check error on console

**Expected behavior**
The importer should maybe convert values as False ->0, True ->1 or None->0 before passing the assert method

**.blend file/ .gltf (mandatory)**
[2024617_301.zip](https://github.com/user-attachments/files/15865470/2024617_301.zip)

**Version**
 - OS: Windows 10
 - Blender Version: 4.1.1

**Additional context**
I don't know if the bug comes from the ThreeJS exporter or in the Blender addon, but it can be fixed parsing values like False, True, None ... to numeric values instead of only checking for type. In this case, I changed the file `glt2_io.py` in the `scripts\addons\io_scene_gltf2\io\com\` folder, from this:
```python
def from_float(x):
    assert isinstance(x, (float, int)) and not isinstance(x, bool)
    return float(x)
```
to this:
```python
def from_float(x):
    if x == False or x == None:
        x = 0
    if x == True:
        x = 1
    assert isinstance(x, (float, int)) and not isinstance(x, bool)
    return float(x)
```

**Comment by julienduroure** [comment]
The glb provided is not a valid glTF/glb file. 
None is not a valid value for float.
Even this can be workaround, we will probably not fix it, as we don't want that some not valid files become the _de facto_ norm.
You should report a bug to the ThreeJS GLTF exporter team.

You can check the validity of a file here: https://github.khronos.org/glTF-Validator/
