### ISSUE TITLE
texture from imported glb/gltf can not be exported to fbx/usd

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF-Blender-IO#2277]
**Describe the bug**
texture from imported glb/gltf can not be exported to fbx/usd

**To Reproduce**
1. Go to menu
2. Click on import then export
3. Click on import with fbx

**Expected behavior**
texture from imported glb/gltf can be exported to fbx/usd

**Screenshots**

**.blend file/ .gltf (mandatory)**
[2.zip](https://github.com/user-attachments/files/15942760/2.zip)

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version 4.3

**Additional context**

**Comment by julienduroure** [comment]
Hello,
I can't see any issue at the import of the glTF file:
- unlit material
- alpha clip

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/b6208ba8-85f0-4fb2-a13c-22c1f73af27d)

Seems the FBX exporter in Blender can't recognize the node setup.
I don't know how/if unlit material are handle in FBX.

This repository is for glTF I/O, you should either:
- request some help on any online forum
- open a ticket on https://projects.blender.org/blender/blender/
