### ISSUE TITLE
Update copyright to 2019

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#228]
Hello,
I don't know was is the way to do, but should we update the copyright to 2019:
- Only on modified files?
- On all files?

and:
- Use copyright 2019?
- Use copyright 2018-2019?

**Comment by emackey** [comment]
@Khronoswebmaster Any thoughts?

**Comment by outofcontrol** [comment]
My understanding is all files should now be updated to 2019. 
/cc @oddhack 

Note: Khronoswebmaster usually gets to me, perhaps in the holiday cleanup I missed it ☹️

**Comment by oddhack** [comment]
I updated it on all of the Vulkan ones. It is probably overkill, but IME it's likely that I'd forget to update files individually as they were edited in the future.

For existing files, the 2019 gets added (e.g. 2018 -> 2018-2019). For files created this year, it's just 2019.
