### ISSUE TITLE
Export fails on image export

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/glTF-Blender-IO#2283]
**Describe the bug**
Image doesnt export - export fails.
This asset was imported using Blenderkit

**To Reproduce**
1. Open zip
2. Export to glTF with default settings
3. Observe error

**Expected behavior**
glTF gets exported

**Screenshots**
![image](https://github.com/user-attachments/assets/f6225b34-5e43-4469-a9aa-7c8a0e9ddc33)

**.blend file/ .gltf (mandatory)**

[old lamp.zip](https://github.com/user-attachments/files/16264099/old.lamp.zip)

**Version**
 - OS: win10
 - Blender Version 4.1

**Comment by julienduroure** [comment]
I can confirm with 4.1
But seems export is OK with 4.2 (released yesterday)

**Comment by marwie** [comment]
Ok, good to know! :)

**Comment by julienduroure** [comment]
Closing this ticket, as this is already fixed
