### ISSUE TITLE
Pairs Importing Issue

### ISSUE THREAD

**Issue by JohnnyG4** [KhronosGroup/glTF-Blender-IO#2290]
When i import something that come with something in pairs (like shoes, gloves, boots, etc.), one part of it (usually the right pair) always end up missing. Can one of you guys see what is going on?
P. S. My best examples are Officer Flint (i used the V2 in this case), Alilkira and Rivet (all of them are from Warfaremachine) which can be found in Smutbase.
![Captura de tela 2024-07-20 095516-edit](https://github.com/user-attachments/assets/c399dd1a-e9d2-4a92-9892-d7234e194828)
![Captura de tela 2024-07-20 111314-edit](https://github.com/user-attachments/assets/276625c6-607d-4eb4-af6a-b21e147cc270)

**Comment by julienduroure** [comment]
Please provide all requested information needed : version used, example file, etc...

**Comment by JohnnyG4** [comment]
Windows 10 22H2, Blender 4.0, i wasn't able to directly add the files so i'm sharing them google drive, tell me if i forgot something. https://drive.google.com/drive/folders/1B7VU5LtHSpyLFiamK44icJ9h3zrwyIkf?usp=sharing

**Comment by julienduroure** [comment]
Hello,

Some of your object are using the mirror modifier, and it seems your don't use the "apply modifier" option to export your mesh
Closing this ticket, as it seems that there is no bug here, only missing an export option.

![image](https://github.com/user-attachments/assets/a69c0326-ee9c-4108-8bac-426fdf877ef5)


![image](https://github.com/user-attachments/assets/45650f7a-549e-46b2-87f4-0afad11fdeac)
