### ISSUE TITLE
Bug while exporting 'full collection hierarchy' elements with animation in .glTF 

### ISSUE THREAD

**Issue by EGFrosch** [KhronosGroup/glTF-Blender-IO#2294]
**Describe the bug**
Can't export object with animation and "full collection hierarchy" in glTF. When trying to export object with the full collection hierarchy it say "AttributeError: 'Collection' object has no attribute 'animation_data' . Did you mean: 'animation_data_clear' " and don't export the element.

**To Reproduce**
1. Create animation (already done in the .zip project)
2. Go to 'export > glTF 2.0 (.glb/.gltf)'
3. Click on 'Data > SceneGraph > Full Collection Hierarchy'
4. Click on Animation and Select Animation mode all other mode than 'NLA Tracks' ('Actions', 'Active actions merged', 'Broadcat actions', 'Scene') → 'NLA Tracks' doesn't stop the export but the animations are not exported
5. Click on 'Export glTF 2.0'

**Expected behavior**
glTF export of a model that include the objects wanted (based on the 'Include' element selected during export)

**Screenshots**
![image](https://github.com/user-attachments/assets/08b0c31c-0eab-48f4-b793-03bd648e9608)
![image](https://github.com/user-attachments/assets/5956b7bc-b9d7-4f83-ba61-3591cf044a33)

**.blend file**
[IssueExportingHierarchy.zip](https://github.com/user-attachments/files/16368223/IssueExportingHierarchy.zip)

**Version**
 - OS: Windows 11 Pro
 - Blender Version : 4.2

**Comment by julienduroure** [comment]
Hello,
Thanks for the reporting.
This bug is already fixed in main branch.
Commit is candidate to be backported to 4.2.x LTS
