### ISSUE TITLE
Emissive strength property modified in place by gltf exporter.

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF-Blender-IO#2305]
When I export a model using the gltf2.0 exporter, materials that have emissive strength >1 seem to sometimes have their emissive strength value modified 'in place' in the model, if the material strength property 'animated' button is enabled/selected.

For example:

1) Set model emission strength of a material to, say, 1.
2) Save .blend model, inspect material, no problem.
3) Change emission strength to, say, 5.
4) Save .blend model, inspect material, no problem.
5) Export .glb, inspect material, oops, emission strength has changed to, say, 4.

The value it changes to seems to be a bit unpredictable, you might have to experiment with the above steps a few times to get it to happen.

This only seems to happen if the little diamond button (apparently 'animated property') next to the strength property is set to 'diamond', not set to 'dot'.

Also, I am using Blender 4.2 which I believe is fairly new so perhaps it's that.

Bye!
Mark

**Comment by julienduroure** [comment]
Hello,
I am not able to reproduce.
Can you please provide me a test file?
In your description (in 5 steps), you didn't insert any keyframes.
A test .blend file will help understand what you are trying to do.

Note that during export, we will bake animation, so any not saved interpolation value (in orange) will be lost.

**Comment by blitz-research** [comment]
OK, my fault, I just tried again and the 'diamond' next to the strength property is a 'dot' by default, I must have accidentally clicked on it when changing the property.
