### ISSUE TITLE
Invisible Action Filter checkboxes

### ISSUE THREAD

**Issue by gguishe** [KhronosGroup/glTF-Blender-IO#2306]
**Describe the bug**
When exporting, if Action Filter is enabled a UIList with Actions is shown, to filter these actions the user must click invisible checkboxes.

**To Reproduce**
1. Add 2 actions to the default cube
2. Open the export window
3. Check Action Filter
4. See that there are no checkboxes (they are invisible)

**Expected behavior**

**Screenshots**

**.blend file/ .gltf (mandatory)**
A zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.
If you are not allowed to share your file, make sure to create a new one from scratch that shows the issue. You can also try to delete or modify some data (objects, change textures, replace some meshes by some placeholder), to be able to share it without restriction.

**Version**
OS - Windows-10-10.0.22631-SP0 64 Bits
Blender Version - 4.3.0 Alpha, branch: main, commit date: 2024-08-07 22:58, hash: `915be63b016f`

**Additional context**

https://github.com/user-attachments/assets/7689c9c9-daaf-43e2-ab3d-9930b8a1054c

**Comment by julienduroure** [comment]
Confirmed
