### ISSUE TITLE
Incorrect wait cursor when exporting

### ISSUE THREAD

**Issue by gguishe** [KhronosGroup/glTF-Blender-IO#2307]
**Describe the bug**
When exporting, the wait cursor used seems to be missing.

**To Reproduce**
1. Export a large file and see that the wait cursor is just a black square.

**Expected behavior**

**Screenshots**

**.blend file/ .gltf (mandatory)**
A zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.
If you are not allowed to share your file, make sure to create a new one from scratch that shows the issue. You can also try to delete or modify some data (objects, change textures, replace some meshes by some placeholder), to be able to share it without restriction.

**Version**
OS - Windows-10-10.0.22631-SP0 64 Bits
Blender Version - 4.3.0 Alpha, branch: main, commit date: 2024-08-07 22:58, hash: `915be63b016f`

**Additional context**

https://github.com/user-attachments/assets/fb68dcbb-03f3-4604-86da-5121d4696cd0

**Comment by marksteward** [comment]
This technically is the wait cursor, it's putting it into a "progress counter" mode, but only ever [sets the progress to 0](https://github.com/KhronosGroup/glTF-Blender-IO/blob/93db353/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py#L397).

**Comment by gguishe** [comment]
I see, technically it should show progress from 0 to 100 (like in the attached image), but it just only shows this black square since is not updated.
![image](https://github.com/user-attachments/assets/e95a50d7-3c93-4f55-8278-b16254f83dff)

In that case the expected wait cursor can be set with just replacing by:
```
context.window.cursor_set('WAIT')
context.window.cursor_set('DEFAULT')
```
