### ISSUE TITLE
GN export includes base mesh

### ISSUE THREAD

**Issue by marksteward** [KhronosGroup/glTF-Blender-IO#2309]
**Describe the bug**
When exporting an object that uses the new Geometry Nodes functionality, the base mesh is exported as well as the output from the modifier.

**To Reproduce**
Export [glTF GN base mesh bug.zip](https://github.com/user-attachments/files/16568189/glTF.GN.base.mesh.bug.zip) as glTF using the saved settings.

Alternatively:

1. Create a new .blend file, and add the the following GN tree to the default cube. Note that the Group Input  geometry is not sent to the output:

![image](https://github.com/user-attachments/assets/a3f008a6-36ce-4334-9330-640d46e19c94)

2. Export as glTF with "Geometry Nodes Instances (Experimental)" ticked.

It exports a cube and a sphere, when it should only export the sphere.

**Version**
 - OS: Windows
 - Blender Version 4.2

**Comment by julienduroure** [comment]
Hello,
Thanks for the report.
I don't think there is any bug here. 
The Geometry Node not only create some instances, but this is also a modifier.
If initial geometry is modified by the node tree, you have to enable "Apply Modifier" option to get it.
Closing this ticket

![image](https://github.com/user-attachments/assets/23aedd5f-bef9-4924-a9d8-c235f91af13f)
