### ISSUE TITLE
Camera Fov Y exported wrong.

### ISSUE THREAD

**Issue by voidstorm** [KhronosGroup/glTF-Blender-IO#2315]
**Describe the bug**
Camera y-fov export is wrong. Instead of exporting it in radians it seems its exported as degrees/100. E.g a fov of 39.9 is exported as 0.3999 instead of 0.69. The erratic behavior is also apparent when re-importing the previously imported gltf file. If you re-import, the fovy that was exported as 39.9 becomes now 22.9 instead.
Changing lens units from/to fov or mm also does not change behavior.

**To Reproduce**
Create a camera, export gltf including cameras. Check json -> value will be wrong. To further confirm, re-import gltf, now the imported camera will also have a wrong fov.

**Expected behavior**
E.g 39.9 should export as 6.999 radians

**Version**
 - OS: Win11
 - Blender Version 4.2

**Comment by julienduroure** [comment]
Hello,

Exporting / Importing camera yfov is not as simple as field of view conversion, as it require also aspect ratio (so render size) and sensor fit

We can find the conversion used here: 

https://github.com/KhronosGroup/glTF-Blender-IO/blob/93db35363d12975da974e1d12f0343932a85dcaf/addons/io_scene_gltf2/blender/com/gltf2_blender_conversion.py#L201

At import, we currently don't fully manage aspect ratio / render size :
https://github.com/KhronosGroup/glTF-Blender-IO/blob/93db35363d12975da974e1d12f0343932a85dcaf/addons/io_scene_gltf2/blender/imp/gltf2_blender_camera.py#L64

**Comment by julienduroure** [comment]
Hello,
More than a month without any answer, closing this ticket
Feel free to comment again if you want to continue the discussion
