### ISSUE TITLE
when only vertices are exported as glb, Vertex color is incorrect

### ISSUE THREAD

**Issue by chen649285912** [KhronosGroup/glTF-Blender-IO#2319]
What I want to do？
I want to export a point cloud model with color in blender, and render it in babylon.js. Like this photo 
![QQ截图20240814164622](https://github.com/user-attachments/assets/dcdcd2e3-046b-4128-ba57-191d179428e3)

1. I generated a mesh point with vertex color data through  geometry node in blender
![2](https://github.com/user-attachments/assets/0c984554-15b5-4f43-b30c-0bf4b92fceb2)

2. Then convert it to a vertex-only mesh, and you can query the vertex to see the color attribute
![3](https://github.com/user-attachments/assets/0014d0e4-6e2c-4379-919f-5baabaab135d)

3.Export glb, use recommended vertex export options (cannot export correctly using various options)
![4](https://github.com/user-attachments/assets/70b57f78-1de6-4cf0-8eb4-86caae04efa3)

4. I put it into the babylon sandbox and found that the vertex color is incorrect
![5](https://github.com/user-attachments/assets/a662b4fc-7f2e-4cba-9605-b5414b52c4ba)

I want to know what this problem is, please check it out, thank you very much！

The following are the test files（Contains glb and blend files）
[test.zip](https://github.com/user-attachments/files/16610389/test.zip)

Version
 -windows 11
 - Blender 4.2
-addon version 4.3.12

I personally speculate that this is because i can only export and import vertex colors based on **face corner-byte color**  in blender. 
If so, I hope that the function of exporting **vertex-color** can be added to meet the demand of exporting point clouds separately.
Thanks again!

**Comment by julienduroure** [comment]
Confirmed.
The exported gltf file is not valid.
I have a fix in progress, but seems I also discovered that it will need more work on alpha VC .

**Comment by chen649285912** [comment]
Thanks, I'll be looking forward to this fix
