### ISSUE TITLE
Problem exporting skinned mesh with bones that have no skins

### ISSUE THREAD

**Issue by setpixel** [KhronosGroup/glTF-Blender-IO#232]
After I export a gltf, my skinned mesh appears to be very odd.

In Blender:
![screenshot 2019-01-15 19 21 16](https://user-images.githubusercontent.com/441117/51218529-de2ea400-18fa-11e9-8021-7296d6e66437.png)

In gltf viewer:
![screenshot 2019-01-15 19 24 08](https://user-images.githubusercontent.com/441117/51218584-2b127a80-18fb-11e9-8e2a-b3a310b93b88.png)

While very visually interesting, this isn't the desired result 😄 

I am manually adding leaf bones to my armature so I can see the lone child bones in my engine.

I can manually "fix" this by reordering the skins, joints list.

`    
"skins" : [
        {
            "inverseBindMatrices" : 14,
            "joints" : [
                54,
                43,
                42,
                41,
                2,
                1,
                0,
                21,
                20, ...
`
If I take the indexes of my new leaf joints and move them to the bottom, it will render properly.

I wonder if the joints are not ordered properly on export?

I'm also curious if this is related to #184 

SOURCE BLENDER: 
[female-adult.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2762044/female-adult.blend.zip)

**Comment by setpixel** [comment]
Hi @julienduroure !

I know the answer is, when it's ready. However, I was wondering about timing on the skinning issues for the exporter. I really want to ship with GLTF rather than FBX files. 

I was looking at where to fix this, but I don't know if I understand the root of the problem. Is there a way I could help? 

Sorry, I know these type of comments are annoying.

**Comment by UX3D-schmithuesen** [comment]
In the neck and the hips, the bones are not connected in your model. That can definitely cause problems.

**Comment by fkaa** [comment]
@UX3D-schmithuesen are offset bones not supported? I thought offset/connected shouldn't matter, since in the end only the (end) joints are exported.

I just tested exporting a simple mesh and indeed adding a single offset bone messes up the resulting transforms completely, which worked for me in the old -Exporter version.

**Comment by capnm** [comment]
I can confirm, the bones and pose get mixed up (right: glTF -> export -> import):

![image](https://user-images.githubusercontent.com/4047289/51904725-abd37b00-23bf-11e9-9d40-9f81ee9a9276.png)

**Comment by UX3D-becher** [comment]
@setpixel could you elaborate on your fix? Maybe even supply both, the broken and fixed .gltf?

**Comment by setpixel** [comment]
@UX3D-becher it was a false claim unfortunately. i thought i fixed it by reordering the skins. the fix i ended up using was exporting the fbx and using a fbx to gltf command line converter - which isnt really a fix. :(

**Comment by UX3D-becher** [comment]
@setpixel with the most recent commit, the model should export correctly

**Comment by setpixel** [comment]
WAT WAT WAT? This is great news. I will give it a test!
