### ISSUE TITLE
Specular not being exported (Blender to Unreal)

### ISSUE THREAD

**Issue by EddyNCNL** [KhronosGroup/glTF-Blender-IO#2322]
Specular values (0) are not being exported from Blender (3.5.0)

- Is this possible in newer versions of Blender perhaps?
- Is there a workaround or some additional checkboxes I'm not aware of that need to be enabled?

I really would like to avoid having to manually add a specular value 0 to all the materials in Unreal.

**Comment by julienduroure** [comment]
For correct Specular export, please use Blender 4.0
Please test with current Blender 4.2

**Comment by EddyNCNL** [comment]
Thanks for your reply!

I've tested Blender 4.2 - they've changed how specular values work but I can confirm 0 Specular IOR in Blender translates to 0 Specular factor in Unreal.

Left Blender, right Unreal.
![image](https://github.com/user-attachments/assets/e9308983-0e6d-4c04-8260-72d931339804)

**Comment by julienduroure** [comment]
Ok, seems we can now close this ticket.
Thanks!
