### ISSUE TITLE
AttributeError: 'ShaderNodeTree' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by DGriffin91** [KhronosGroup/glTF-Blender-IO#2323]
**Describe the bug**
When trying to export the poly haven Hidden Alley scene from blender 4.2 I get the error:
```
File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\io_scene_gltf2\blender\exp\material\gltf2_blender_search_node_tree.py", line 904, in check_if_is_linked_to_active_output
    sockets = group_path[-1].outputs
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ShaderNodeTree' object has no attribute 'outputs'
```

**To Reproduce**
Steps to reproduce the behavior
1. Download the blend file from https://blog.polyhaven.com/hidden-alley/
2. Export as gltf
2. See error in console

**Expected behavior**
For the exporter to not crash.

**.blend file**
https://dl.polyhaven.org/file/ph-assets/Scenes/hidden_alley.zip

**Version**
 - OS: Windows 10
 - Blender Version 4.2

**Comment by julienduroure** [comment]
Confirmed.
Node tree Mesh with issue : Floor_main

**Comment by julienduroure** [comment]
Here is in attachment the minimal file that show the issue (well, the original file was 1.4 Go .... !)
Looks like maybe an issue in Blender file itself, as if you enter node group, remove the BSDF/BSDF link, and add it again : No more crash...
[minimal_bug_shader.blend.zip](https://github.com/user-attachments/files/16650210/minimal_bug_shader.blend.zip)

Investigation in progress

**Comment by julienduroure** [comment]
Investigation progress:
We have an issue on our code, when a socket is linked to 2 output socket of an output group

Unplug/plug again solve the issue because it changes the link order of the socket, and now the "correct" socket goes first, before the second one
