### ISSUE TITLE
RGB based material not exporting color - gltf/glb

### ISSUE THREAD

**Issue by Raphlette** [KhronosGroup/glTF-Blender-IO#2326]
**Describe the bug**
When creating a material with only a RGB node (see image bellow), the baseColorFactor is not being exported anymore (working up until 4.2). 

**To Reproduce**
1. Add a material with only RGB node connected to the material output.
2. Export object to gltf.

**Expected behavior**
The RGB color should be exported as baseColorFactor in the material. 

**Screenshots**
![Material](https://github.com/user-attachments/assets/0ec837c7-7bc8-44a3-8e59-6fcb076fd3c8)
![Gltf comparison](https://github.com/user-attachments/assets/a2784b8b-789f-48ae-9c97-f0883b357587)

**.blend file/ .gltf (mandatory)**
[test_4.2.zip](https://github.com/user-attachments/files/16707315/test_4.2.zip)

**Version**
 - OS: Windows 11
 - Blender Version: 4.2 ~~ forward

**Comment by julienduroure** [comment]
Confirmed the regression.
This case (auto conversion RGB to Shader socket) for unlit was forget in NodeNav
