### ISSUE TITLE
Accessor class to accept single values for `max` and `min`

### ISSUE THREAD

**Issue by Phrogz** [KhronosGroup/glTF-Blender-IO#2335]
**Is your feature request related to a problem? Please describe.**
The `gather_accessor()` function and `Accessor` class require the `min` and `max` fields to be iterable. If I try to create an accessor for a scalar type and pass single values for `min` and `max`, the hook fails, erroring with `'float' object is not iterable`.

**Describe the solution you'd like**
Allow a single scalar value to be passed for these two fields.

**Comment by julienduroure** [comment]
Hello,

gather_accessor() is a cached function, and so it will require tuple to work ruminatively.

We can check how it is done in code here:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/295bbf7eda4c3de5429a01a0d919f42d90aaf5f9/addons/io_scene_gltf2/blender/exp/animation/sampled/object/sampler.py#L94

Closing this ticket, as there is no issue here
