### ISSUE TITLE
ValueError: Object.path_resolve("") could not be resolved

### ISSUE THREAD

**Issue by jcothran** [KhronosGroup/glTF-Blender-IO#234]
In gltf_blender_gather_animation_samplers.py I am getting the attached screenshot error on gltf2 export 

ValueError: Object.path_resolve("") could not be resolved
![screenshot 332](https://user-images.githubusercontent.com/1074974/51295615-6e95e300-19e6-11e9-9a3d-39873b4686cf.png)

    if blender_object.type == "ARMATURE":
        bone = blender_object.path_resolve(get_target_object_path(target_datapath))

This is a minimal starting example that I am trying to set up, with getting a textured plane to correctly export with gltf and display with three.js and then adding a single-bone armature to rotate the plane slightly back and forth in a single animation. I tried setting up a NLA track which I think is 'active' as required to generate the animation but still get the same error.

I'm running blender 2.80 with the latest version from a few days ago of io_scene_glft2

Thanks
[test_simple2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2767147/test_simple2.zip)

**Comment by UX3D-schmithuesen** [comment]
#310 duplicates this so there is another example file to reproduce this bug.
