### ISSUE TITLE
glTF Material Variants are broken

### ISSUE THREAD

**Issue by literallylara** [KhronosGroup/glTF-Blender-IO#2342]
**Describe the bug**
The "Display Variant" button has no effect after creating variants and assigning different material properties to them. Tested on the default cube. Am I doing it wrong?

**To Reproduce**
See video:
<video src="https://github.com/user-attachments/assets/8a3fdefb-e0a9-47d7-90bc-452d7a5508b8"></video>

**Version**
 - OS: macOS
 - Blender Version: 4.2.1 LTS
 - Add-on Version: 4.2.60

**Additional context**
- Previous Blender versions were affected too
- Info panel does not show any errors

**Comment by julienduroure** [comment]
Hello,

You have to use 2 different materials, 1 for each variant.
If you assign the same material in each variant, we you modify the material, it is modified in each variant because there is only 1 material shared by multiple variants.

Closing this ticket
