### ISSUE TITLE
BlenderNodeAnim.get_or_create_action() retrieves incorrect action

### ISSUE THREAD

**Issue by Phrogz** [KhronosGroup/glTF-Blender-IO#2343]
**Describe the bug**
I'm writing an importer extension for animations. Attempting to get an action by name retrieves the wrong action.

The fact that it uses the object name to cache actions seems incorrect to me. A single object can have multiple actions with discrete names, right?

**To Reproduce**
I have added print statements to the `BlenderNodeAnim.get_or_create_action()` method:

```python
    def get_or_create_action(gltf, node_idx, anim_name):
        print(f'!!! get_or_create_action(<glTFImporter>, {node_idx}, "{anim_name}")')
        vnode = gltf.vnodes[node_idx]

        if vnode.type == VNode.Bone:
            # For bones, the action goes on the armature.
            vnode = gltf.vnodes[vnode.bone_arma]

        obj = vnode.blender_object
        print(f'   ...obj.name: "{obj.name}"')

        action = gltf.action_cache.get(obj.name)
        print(f'   ...gltf.action_cache: {gltf.action_cache}')
        print(f'   ...action: {action}')
        if not action:
            name = anim_name + "_" + obj.name
            print(f'   ...creating new action named {name}')
            action = bpy.data.actions.new(name)
            action.id_root = 'OBJECT'
            gltf.needs_stash.append((obj, action))
            gltf.action_cache[obj.name] = action

        return action
```

and I'm importing a glTF object with three named animations, all targeting the same object, with some extensions:

```json
 "animations" : [{"name" : "CubeSlideY",
                  "channels" : [{"sampler":0, "target":{"node":0, "path":"translation"}}],
                  "samplers" : [{"input":4, "interpolation":"CUBICSPLINE", "output":5}]},
                 {"name" : "SlideZAndBlink",
                  "channels" : [{"sampler":0, "target":{"node":0, "path":"translation"}},
                                {"sampler" : 1,
                                 "target" : {"extensions" : {"KHR_animation_pointer" : {"pointer" : "/nodes/0/extensions/EXT_node_visibility/visibility"}},
                                             "path" : "pointer"}}],
                  "samplers" : [{"input":6, "interpolation":"CUBICSPLINE", "output":7},
                                {"input":8, "interpolation":"STEP", "output":9}]},
                 {"name" : "CubeBlink",
                  "channels" : [{"sampler" : 0,
                                 "target" : {"extensions" : {"KHR_animation_pointer" : {"pointer" : "/nodes/0/extensions/EXT_node_visibility/visibility"}},
                                             "path" : "pointer"}}],
                  "samplers" : [{"input":10, "interpolation":"STEP", "output":11}]}],
```

This is the printout results:

```
======== inside gather_import_animations()
!!! get_or_create_action(<glTFImporter>, 0, "SlideZAndBlink")
   ...obj.name: "MyCubeNode"
   ...gltf.action_cache: {}
   ...action: None
   ...creating new action named SlideZAndBlink_MyCubeNode
!!! get_or_create_action(<glTFImporter>, 0, "CubeSlideY")
   ...obj.name: "MyCubeNode"
   ...gltf.action_cache: {}
   ...action: None
   ...creating new action named CubeSlideY_MyCubeNode

======== inside gather_import_scene_after_animation_hook
!!! get_or_create_action(<glTFImporter>, 0, "SlideZAndBlink")
   ...obj.name: "MyCubeNode"
   ...gltf.action_cache: {'MyCubeNode': bpy.data.actions['CubeSlideY_MyCubeNode']}
   ...action: <bpy_struct, Action("CubeSlideY_MyCubeNode") at 0x7405f2d9fc88>
!!! get_or_create_action(<glTFImporter>, 0, "CubeBlink")
   ...obj.name: "MyCubeNode"
   ...gltf.action_cache: {'MyCubeNode': bpy.data.actions['CubeSlideY_MyCubeNode']}
   ...action: <bpy_struct, Action("CubeSlideY_MyCubeNode") at 0x7405f2d9fc88>
```

**Expected behavior**
The method should find the `SlideZAndBlink` action during the first invocation inside `gather_import_scene_after_animation_hook`, and should create a new action for the `CubeBlink` call.

I think the `action_cache` dictionary should be using the `anim_name + "_" + obj.name` as the key to look up in the cache, and restore from the cache. I also do not understand why the action_cache is empty on the second invocation (by the real importer code). [It's the right thing to do in this case, but does not appear to be how the code is supposed to work.]

**Screenshots**

**.blend file/ .gltf (mandatory)**
A zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.
If you are not allowed to share your file, make sure to create a new one from scratch that shows the issue. You can also try to delete or modify some data (objects, change textures, replace some meshes by some placeholder), to be able to share it without restriction.

**Version**
 - OS: linux
 - Blender Version 4.2.1
[gltf-and-importer.zip](https://github.com/user-attachments/files/16858077/gltf-and-importer.zip)

**Comment by scurest** [comment]
`action_cache` only holds the cached actions for one animation at a time. Every time the importer moves on to doing a new animation, it gets cleared.

https://github.com/KhronosGroup/glTF-Blender-IO/blob/295bbf7eda4c3de5429a01a0d919f42d90aaf5f9/addons/io_scene_gltf2/blender/imp/animation.py#L28-L32

**Comment by Phrogz** [comment]
@scurest That explains the behavior, then. That puts a wrench in the plans I had for how to write my importer. I guess this is not a bug, then, just intended undocumented behavior? [I really wish there was documentation explaining which functions are intended to be useful to extension authors, and in which context.] 

Outside of the context of this bug, if you can help: after all of the other animations have already been imported, do you have a suggestion for how I am to find an actions for a specific blender object by name, and create new actions and fcurves if they don't already exist? (Should I be using classes and methods inside the importer? Should I just be using all bpy methods?)

**Comment by scurest** [comment]
I don't think the extension is particularly useful myself. I would just fork the addon and make whatever changes you want.

**Comment by scurest** [comment]
That said there appears to be a hook that runs at the end of the animation

https://github.com/KhronosGroup/glTF-Blender-IO/blob/295bbf7eda4c3de5429a01a0d919f42d90aaf5f9/addons/io_scene_gltf2/blender/imp/animation.py#L119

You could copy any data you need from action_cache into your own object keyed with anim_idx.

**Comment by Phrogz** [comment]
I appreciate your thoughts. I'm not sure how to merge my animation data that might be targeting a separate node's action in here. Anyhow, the Issues section of this repo feels like the wrong place to get personal assistance on using it. I've [taken the discussion to Blender StackExchange](https://blender.stackexchange.com/q/323978/98738); maybe I'll see you there. :)
