### ISSUE TITLE
I cant import glb file into blender Error:Extension PIXIV_texture_basis is not available on this addon version

### ISSUE THREAD

**Issue by Be3up** [KhronosGroup/glTF-Blender-IO#2346]
![изображение_2024-09-09_091303181](https://github.com/user-attachments/assets/a3e4e225-5be9-4a7c-b610-28cf169642dc)
error: Extension PIXIV_texture_basis is not available on this addon version
how fix it?

**Comment by julienduroure** [comment]
Hello,
Blender glTF I/O manages only officialy ratified extensions.
PIXIV_texture_basis is not a ratified extension, and it seems this extensions is declared as required in this file.
So, as is, there is no way to read your file.

**Comment by julienduroure** [comment]
I never heard of PIXIV before your ticket, so I don't know where your file come from.
If you share your file, I maybe able to understand what this extension is about, and open it without any textures.
If this extension is similar to [KHR_texture_basisu](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_texture_basisu), you may be able to convert it to remove this extension with some tools like gltf-transform.

**Comment by Be3up** [comment]
> I never heard of PIXIV before your ticket, so I don't know where your file come from. If you share your file, I maybe able to understand what this extension is about, and open it without any textures. If this extension is similar to [KHR_texture_basisu](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_texture_basisu), you may be able to convert it to remove this extension with some tools like gltf-transform.

i wanna delete texture and make my texture for model
plz help

**Comment by Be3up** [comment]
> До вашего билета я никогда не слышал о PIXIV, поэтому не знаю, откуда взялся ваш файл. Если вы поделитесь своим файлом, возможно, я смогу понять, что это за расширение, и открыть его без каких-либо текстур. Если это расширение похоже на [ KHR_texture_basisu ](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_texture_basisu) , вы можете преобразовать его, чтобы удалить это расширение, с помощью некоторых инструментов, таких как gltf-transform.

[](url)

**Comment by julienduroure** [comment]
> i wanna delete texture and make my texture for model
plz help

It will require to have the file, open it, and modify the provided file, by hand or programmatically.
This is out of the scope of this issue tracker, as there is no bug in the importer.

I do not plan to try to download a file from the website or using your script.
If you want help, you should provide the file

**Comment by Be3up** [comment]
> > я хочу удалить текстуру и сделать свою текстуру для модели 
> > пожалуйста, помогите
> 
> Потребуется иметь файл, открыть его и изменить предоставленный файл вручную или программно. Это выходит за рамки данного средства отслеживания ошибок, поскольку в импортере нет ошибок.
> 
> Я не планирую пробовать скачать файл с сайта или с помощью вашего скрипта. Если вам нужна помощь, вы должны предоставить файл

[https://drive.google.com/file/d/1ajgEZrWS1BqCUACPW6I6L9SmIeYrwhqU/view?usp=sharing](url)
this is file check plz

**Comment by Be3up** [comment]
https://drive.google.com/file/d/1ajgEZrWS1BqCUACPW6I6L9SmIeYrwhqU/view?usp=sharing
i uploaded file on google drive 
this is file check plz

**Comment by Be3up** [comment]
> > i wanna delete texture and make my texture for model
> > plz help
> 
> It will require to have the file, open it, and modify the provided file, by hand or programmatically. This is out of the scope of this issue tracker, as there is no bug in the importer.
> 
> I do not plan to try to download a file from the website or using your script. If you want help, you should provide the file

u checked file?

**Comment by julienduroure** [comment]
Here is the file
Closing this ticket, as there is no bug here

[Uploading PIXIV.blend.zip…]()

**Comment by Be3up** [comment]
hmm
u can say how u fixed?
