### ISSUE TITLE
Importing spot light fails if outerConeAngle is not present

### ISSUE THREAD

**Issue by PassiveModding** [KhronosGroup/glTF-Blender-IO#2349]
**Describe the bug**
When importing a spot light that does not contain an outerConeAngle, import fails on the create_spot method.

Assumed issue is 
https://github.com/KhronosGroup/glTF-Blender-IO/blob/295bbf7eda4c3de5429a01a0d919f42d90aaf5f9/addons/io_scene_gltf2/blender/imp/light.py#L118
When calling calc_spot_cone_inner, the value for outerConeAngle may not exist

**To Reproduce**
1. Create sample .gltf file with a spot light.
2. Import file as gltf

**Expected behavior**
Import should succeed as normal, using the default value of PI/4.0 for outerConeAngle as defined in the KHR_lights_punctual

**Sample**
```json
{
  "extensions": {
    "KHR_lights_punctual": {
      "lights": [
        {
          "spot": {
            "innerConeAngle": 0.10000000149011612
          },
          "type": "spot"
        }
      ]
    }
  },
  "asset": {
    "copyright": "",
    "generator": "SharpGLTF 1.0.0\u002Bf5cd805711f76596a77a71de9cba4717e0edd159",
    "version": "2.0"
  },
  "extensionsUsed": [
    "KHR_lights_punctual"
  ],
  "nodes": [
    {
      "extensions": {
        "KHR_lights_punctual": {
          "light": 0
        }
      }
    }
  ],
  "scene": 0,
  "scenes": [
    {
      "nodes": [
        0
      ]
    }
  ]
}
```

**Version**
 - OS: Windows
 - Blender Version: 4.2.1

**Comment by julienduroure** [comment]
Confirmed
