### ISSUE TITLE
Bones cause mesh scaling issue

### ISSUE THREAD

**Issue by funwithtriangles** [KhronosGroup/glTF-Blender-IO#235]
When exporting a simple cylinder with bones, the cylinder becomes scaled down along one axis. With "skinning" turned off in the export option, it looks fine. 

**In Blender 2.8**
![cylinder-before](https://user-images.githubusercontent.com/1876324/51317034-65406100-1a4e-11e9-9d0f-b12d7bd576e1.PNG)

**In glTF Viewer**
![cylinder-after](https://user-images.githubusercontent.com/1876324/51317033-65406100-1a4e-11e9-868d-ab5cd0927015.png)

**Without bones**
![cylinder-no-bones](https://user-images.githubusercontent.com/1876324/51317035-65406100-1a4e-11e9-99c3-4c33e2a04741.PNG)

**Blender file:**
[cylinder-bones.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2768534/cylinder-bones.zip)

**Comment by julienduroure** [comment]
Not linked to #15 ( seems you edited your first post ...), because #15 is linked to import, and this issue is linked to export

**Comment by funwithtriangles** [comment]
@julienduroure I'd like to have a go at fixing this but might need some guidance. Do you have any suspicions on why this is happening? My guess is that the bone weights are exporting incorrectly for the mesh?

**Comment by UX3D-schmithuesen** [comment]
Seems to have been resolved. I just checked with [our viewer](http://gltf.ux3d.io) and the result looks good:
![image](https://user-images.githubusercontent.com/44766936/51848696-58f5b700-231e-11e9-8629-567b80568514.png)
