### ISSUE TITLE
animation_gather_fcurve_channel_target called twice, instead of animation_gather_fcurve_channel

### ISSUE THREAD

**Issue by Phrogz** [KhronosGroup/glTF-Blender-IO#2351]
**Describe the bug**
Writing an exporter extension, the `animation_gather_fcurve_channel_target` hook gets called twice per gathered action.

* Once in [`exp/animation/fcurves/channel_target.py:gather_fcurve_channel_target()`](https://github.com/KhronosGroup/glTF-Blender-IO/blob/main/addons/io_scene_gltf2/blender/exp/animation/fcurves/channel_target.py#L39)
* Again in [`exp/animation/fcurves/channels.py:gather_animation_fcurves_channels()`](https://github.com/KhronosGroup/glTF-Blender-IO/blob/main/addons/io_scene_gltf2/blender/exp/animation/fcurves/channels.py#L298)

Based on naming conventions alone, I think this is a copy/paste error, and the second one is supposed to be `animation_gather_fcurve_channel`…and possibly is intended to have additional useful information passed along?

**To Reproduce**
1. Write an exporter extension with:  
    ```python
    def animation_gather_fcurve_channel_target(self, blender_object, bone_name, export_settings):
        print(f'####### animation_gather_fcurve_channel_target {blender_object.name}/bone"{bone_name}"')

    def animation_gather_fcurve_channel_sampler(self, blender_object, bone_name, export_settings):
        print(f'####### animation_gather_fcurve_channel_sampler {blender_object.name}/bone"{bone_name}"')
    ```
2. Export a glTF without sampling animations enabled.
3. Notice debug output like:  
    ```
    ####### animation_gather_fcurve_channel_target needle/bone"None"
    ####### animation_gather_fcurve_channel_sampler needle/bone"None"
    ####### animation_gather_fcurve_channel_target needle/bone"None"
    ```

**Expected behavior**
I think a distinct callback was intended for `gather_animation_fcurves_channels`. 

**Version**
 - macOS
 - Blender Version 4.1; still present in `main` codebase.

**Comment by julienduroure** [comment]
Confirmed
