### ISSUE TITLE
Regression on skinned animation export

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#236]
Hi,

I have done several tests exporting a simple scene with a skinned mesh and is failing even for the most simple cases with this exporter, for both Blender 2.79 and Blender 2.8. The same examples worked with the old exporter (glTF-Blender-Exporter).  

The test samples I have done are
1 mesh and 1 skeleton
3 meshes and 1 skeleton
3 meshes and 3 skeletons. This one fails also with the old exporter.

[SeveralSkeletons.tar.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/2769625/SeveralSkeletons.tar.gz)

**Comment by jjcasmar** [comment]
![image](https://user-images.githubusercontent.com/2644001/51333405-e82ce000-1a7d-11e9-9204-8c9be41fc885.png)

**Comment by UX3D-nopper** [comment]
We are aware, that there is an issue with the skinning. So please post problematic scenes to existing skinning issues.

**Comment by jjcasmar** [comment]
Ive added the scenes in a tar.gz file. Is that okay?

**Comment by j-conrad** [comment]
I'm adding an additional Blender scene file and the corresponding exported glTF. Even without the animation on the bones, if I simply pose the skeleton and export there is no resulting deformation nor are the bones themselves rotated at all.

[SkinExportProblems.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2804353/SkinExportProblems.zip)

**Comment by UX3D-becher** [comment]
fixed with #398
