### ISSUE TITLE
4.2.44 introduced a regression in the export process

### ISSUE THREAD

**Issue by hichemfantar** [KhronosGroup/glTF-Blender-IO#2362]
**Describe the bug**
leaves look incorrect

**To Reproduce**
1. export to gltf with default settings
2. leaves look weird in exported file

**Expected behavior**
leaves should look correct like in the blender editor

**Screenshots**

![image](https://github.com/user-attachments/assets/69ff07b6-904a-4771-935a-e4adfb8fd6ae)

![image](https://github.com/user-attachments/assets/0353248f-ea4d-447c-8ae8-eecf1fe70efc)

*blender editor view*

![image](https://github.com/user-attachments/assets/fca0424e-aebb-4d0a-904a-55a6771ca368)
*glb export with 4.2.43*

![image](https://github.com/user-attachments/assets/05368699-9bfc-452f-b7e0-63b9b7af8cc8)
*glb export with >=4.2.44*

**.blend file/ .gltf (mandatory)**

[export-test.zip](https://github.com/user-attachments/files/17155878/export-test.zip)

[blend.zip](https://github.com/user-attachments/files/17155928/blend.zip)

**Version**
 - OS: window 10 22h2
 - Blender Version 4.2.2

**Additional context**
discovered the issue when i upgraded from blender 4.1 to 4.2.2 lts
used git bisect to find the culprit release
4.2.44 commits:
https://github.com/KhronosGroup/glTF-Blender-IO/commit/b4cb347b6fdd35aef18ffac081533d5ff3e43eee
https://github.com/KhronosGroup/glTF-Blender-IO/commit/67f73e6bb846ceebc1d71accc89fee753cbead7d
https://github.com/KhronosGroup/glTF-Blender-IO/commit/f0df348797070ec50ef8d896b9b7dcaccf665128
https://github.com/KhronosGroup/glTF-Blender-IO/commit/986a45ab3cf7f9670d4c0e8f7154f01ba5adffbb

not related but 4.2.44 seems to have fixed https://blenderartists.org/t/transparency-in-texture-become-black-when-exported-gltf/1168672

**Comment by julienduroure** [comment]
Confirmed.
4.2 use a new system when alpha is linked to a Color socket.
Before, it used to use the R channel as new alpha (the first found channel : R)
Now, a RGB to BW is performed ... 
But seems that your file also has alpha.
Depending on image node alpha mode, we need to multiply the result by alpha, as it is done in Blender

**Comment by hichemfantar** [comment]
@julienduroure just to be clear, the bug i have is with the tree leaves, not the vegetation on the container.

the regression is in the case of the tree leaves
