### ISSUE TITLE
KHR_texture_transform with rotation possibily wrong

### ISSUE THREAD

**Issue by timknip** [KhronosGroup/glTF-Blender-IO#2366]
**Describe the bug**
A glTF file with the KHR_texture_transform extension looks good in _some_ (ugh) online viewers but looks wrong after importing into blender.
Viewers showing ok:
-  https://gltf-viewer.donmccurdy.com/
-  https://gltf.report/
Viewers showing the issue:
-  https://sandbox.babylonjs.com/

So basically the question is who's got it right.

**To Reproduce**
1. import this file [xxxx49519510811a3a8e7b686fcfb4152d0ff26f_09.COLOR_MORSECHARCOAL.zip](https://github.com/user-attachments/files/17195003/xxxx49519510811a3a8e7b686fcfb4152d0ff26f_09.COLOR_MORSECHARCOAL.zip)
2. look at the texture which is wrongly applied:
![bad](https://github.com/user-attachments/assets/edec40be-f5db-4db9-893a-e5d2d566f235)

**Expected behavior**
The texture should look good:
![good](https://github.com/user-attachments/assets/f46e8d22-9cb3-45e6-bbba-ae3be177099a)

**Version**
 - OS: win32
 - Blender Version: 3.6 and up (earlier versions not tested)

I suspect the [conversion](https://github.com/KhronosGroup/glTF-Blender-IO/blob/main/addons/io_scene_gltf2/blender/com/conversion.py#L63) to the Mapping node can be wrong in some cases.

Due to inconsistent behavior in different viewers, it's unclear which implementation is correct.

**Comment by scurest** [comment]
https://gltf-viewer.donmccurdy.com/ is known to have a wrong implementation of KHR_texture_transform, see https://github.com/mrdoob/three.js/issues/15831 (note that despite being closed, the issue was never fixed). Since Babylon and Blender agree, they seem likely to be correct.

In practical terms, you should probably avoid rotations since they never received a consistent implementation.

**Comment by julienduroure** [comment]
@donmccurdy Do you have any inputs about that?
Thanks!

**Comment by donmccurdy** [comment]
> In practical terms, you should probably avoid rotations since they never received a consistent implementation.

If I understand correctly, the problem described by https://github.com/mrdoob/three.js/issues/15831 occurs only if the UV transform contains both:

1. non-uniform scaling
2. non-zero rotation

If scaling is uniform, or there's no rotation, then `Scale[s] x Rot[-r] = Rot[-r] x Scale[s]` should be equivalent. Does that sound right? 

I agree that three.js does not implement KHR_texture_transform according to the spec when both conditions above are true, but I don't expect that to change any time soon. It would be a breaking change that affects more than just the three.js glTF loader, and I worry that the fix may be worse than the bug for us, given the shear problem. Perhaps three.js could log a warning when a transform uses both rotation and non-uniform scale.

**Comment by julienduroure** [comment]
Hello,
Thanks for your feedback.
I think we can close this ticket, as there is no bug on Blender side
