### ISSUE TITLE
Unable to export material animation on  emission

### ISSUE THREAD

**Issue by chen649285912** [KhronosGroup/glTF-Blender-IO#2372]
Use blender 4.2.1

I made a material animation based on emission. After exporting it using nla, I found an error. The reference video, error picture and test file are as follows

reference video
https://github.com/user-attachments/assets/82d3245f-9d2b-41b8-8512-0dbad6e5885c

error picture
![QQ截图20241015104502](https://github.com/user-attachments/assets/e065e349-f104-4be4-ad01-d095554ff895)

test file
[test.zip](https://github.com/user-attachments/files/17371843/test.zip)

**Comment by chen649285912** [comment]
This is the export settings used
![image](https://github.com/user-attachments/assets/e142a066-50e2-4df8-b6ed-f2daee52a2a0)

**Comment by julienduroure** [comment]
confirmed
