### ISSUE TITLE
GLTF Export fail on animated camera

### ISSUE THREAD

**Issue by vKreuziger** [KhronosGroup/glTF-Blender-IO#2374]
When I try to export a scene containing an animated camera object (any sort of animation: keyframe, follow track, etc.) the export fails with an error, CC @hybridherbst

**To Reproduce**
1. Open attached .blend file
2. Go to File -> Export -> gltf 2.0 (.gltf/.glb)
3. In the export dialog go to Animation -> Animation Mode: Set to 'Scene'
4. In the export dialog go to Include -> tick 'Cameras'
5. Click 'Export'

**Expected behavior**
A GLB file containing the current scene with the animated camera object should be saved to disk. 

[minimal_example_exporting_camera_animation.zip](https://github.com/user-attachments/files/17378485/minimal_example_exporting_camera_animation.zip)

Here's the error message I get upon exporting: 
![blender_sEaIPOxMh1](https://github.com/user-attachments/assets/0473dace-5093-4f10-8ca1-5579de4a4c57)

**Version**
 - OS: Windows 11
 - Blender Version 4.2.2

**Comment by julienduroure** [comment]
Confirmed

**Comment by julienduroure** [comment]
Should be fixed by #2376
