### ISSUE TITLE
Errors exporting udim textures

### ISSUE THREAD

**Issue by 3DE-Damien** [KhronosGroup/glTF-Blender-IO#2381]
**Describe the bug**
- When I export an object with jpeg udim textures, the exporter crashes.
- UVs sharing vertex on UDIM limits are not correctly exported.
- Geometry using only one UDIM tile (other than 1001) are exported with the 1001 texture tile.

**To Reproduce**
- download and unzip [Blender_gltf_udims.zip](https://github.com/user-attachments/files/17491250/Blender_gltf_udims.zip)
- open gltf_udims.blend
- try exporting the scene or individual cubes

**Expected behavior**
Getting results similar to Blender viewport

**Screenshots**
![Blender Viewport](https://github.com/user-attachments/assets/1eeb6906-d535-4435-a004-7a8f97a67cd0)
![Blender Error](https://github.com/user-attachments/assets/000f5e17-c732-4982-9573-7dc8978ad4fc)
![PNG_Export](https://github.com/user-attachments/assets/4d788d86-6542-41aa-ba0c-979c1fb5fbe8)

**System Information**
Operating system: Windows-10-10.0.19045-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 3060/PCIe/SSE2 NVIDIA Corporation 4.6.0 NVIDIA 565.90

**Blender Version**
Broken: version: 4.2.3 LTS, branch: blender-v4.2-release, commit date: 2024-10-14 15:20, hash: `0e22e4fcea03`
Worked: (newest version of Blender that worked as expected)

**Comment by julienduroure** [comment]
Point 1 and 3 are fixed in #2384 

The second one is much more complicated to manage, as 
- There is some float precision issue
- We need to check, on limit, where should the point goes, (based on edges and faces?)
For this part of the bug report, no short term solution will probably happen.

**Comment by 3DE-Damien** [comment]
Thank you Julien. I can accomodate the second point, I guess.

I would choose the right texture based on face center UVs location. There would be some issues with overflowing faces, but it's not supposed to happen with udims, AFAIK.
