### ISSUE TITLE
Import: exception for 'Node' object has no attribute 'blender_bone_name'

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#239]
```
Traceback (most recent call last):
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 468, in execute
    return self.import_gltf2(context)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 487, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 35, in create
    BlenderScene.create(gltf, scene_idx)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py", line 78, in create
    BlenderSkin.create_vertex_groups(gltf, skin_id)
  File "/home/scurest/.config/blender/2.79/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_skin.py", line 163, in create_vertex_groups
    obj.vertex_groups.new(name=gltf.data.nodes[bone].blender_bone_name)
AttributeError: 'Node' object has no attribute 'blender_bone_name'
```

[Test file](https://github.com/KhronosGroup/glTF-Blender-IO/files/2777901/b00A.zip)

Not sure what's wrong, but maybe caused by a mesh being instantiated on one of the joints of its skin.

**Comment by donmccurdy** [comment]
See https://github.com/KhronosGroup/glTF/issues/1433 — this is valid, and if we interpret a node referencing a mesh to mean that node "is" a mesh, then a node can simultaneously be a mesh, a bone, a camera, and a light. The robust way to deal with that is to consider nodes empties, and whatever things they reference become children without a transform of their own. 

A lot of tools want to avoid overcomplicating the node hierarchy and optimistically flatten, so I'm sure the importer is not the only tool that will have trouble with this asset. I would suggest we handle this as best we can on import, but avoid writing dual-purpose nodes from the exporter like this.

I'm tempted to say this should be tightened up in a future version of the spec, to reduce edge cases.

**Comment by emackey** [comment]
> I'm tempted to say this should be tightened up in a future version of the spec, to reduce edge cases.

Agreed.  It might be helpful to inquire the history of this.  Were multi-purpose nodes intentionally allowed at some point, or were they just an artifact of the schema's ability to assign one of each thing to a node?

**Comment by julienduroure** [comment]
Note for importer implementation: I will work first on a version where node can be multiple "thinks" except joints. This will be the more easy part, even it will not solve this issue.
Then I will work on second part, node being able to be joint and something else

**Comment by scurest** [comment]
Note that this same error occurs if a mesh is skinned by joints not in the same scene. See https://github.com/KhronosGroup/glTF/issues/1558.

**Comment by julienduroure** [comment]
Started a simple implementation on branch importer_multipletype
Only for objects for now (that means that the bug is not solved yet, because this is a object / rig case)
