### ISSUE TITLE
Check with blender for unit of light intensity

### ISSUE THREAD

**Issue by UX3D-becher** [KhronosGroup/glTF-Blender-IO#24]
verify blender cycles is actually using lumen instead of watts (as specified in documentation)

**Comment by donmccurdy** [comment]
At least in the latest version, the UI itself is showing watts:

<img width="277" alt="Screen Shot 2019-06-24 at 9 50 49 AM" src="https://user-images.githubusercontent.com/1848368/60037091-98be9180-9665-11e9-87c6-8551a5fd057f.png">

Seems like we need to do a conversion?

**Comment by julienduroure** [comment]
We know have the answer on #564
