### ISSUE TITLE
'FluidFlowSettings" object has no attribute 'name'

### ISSUE THREAD

**Issue by xLukus** [KhronosGroup/glTF-Blender-IO#2402]
**Describe the bug**
When i try to export this fluid simulation  ing glb file format , i get a python error.

**To Reproduce**
Download the file and play the animation

**Expected behavior**
To export into a glb file without a problem stating FluidFlowSettings object has no attribute 'name'

**Screenshots**

![Screenshot 2024-11-18 191318](https://github.com/user-attachments/assets/c3a5f228-5b76-40f6-9032-3fe5669dca79)

**.blend file/ .gltf (mandatory)**
[LASTTTT - Copy.zip](https://github.com/user-attachments/files/17804822/LASTTTT.-.Copy.zip)

**Version**
 - OS: [windows]
 - Blender Version [4.2.1]

Description:
i created a fluid flow water like simulation and baked it to keyframes without addding a name anywherre.Now finally when i got it working it starting to bug saying i can't export it.

**Comment by julienduroure** [comment]
Confirmed.
On the Sphere Object, the "use Flow" is animated, but this can not be exported in glTF.
There is a bug in the way we are retrieving the channel data_path.

Workaround to export your data:

Remove the animation on the boolean field:
![image](https://github.com/user-attachments/assets/2900feb5-51bd-4e20-9228-a70d885976a8)

**Comment by xLukus** [comment]
Thank you very much!
