### ISSUE TITLE
Normal scale/strength

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#241]
Apologies if this is a duplicate, I couldn't find exactly this issue but I know I've run into it before.

glTF has a parameter [`normalTextureInfo.scale`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#normaltextureinfoscale) that controls the strength of the normal-mapping.  Blender has a parameter called "Strength" in its Normal Map node that appears to control the same thing:

![normal strength](https://user-images.githubusercontent.com/1235080/51488384-68e82680-1d73-11e9-9d3c-2b3da7b27dc6.png)

Looks like neither the importer or exporter copy this value out or back into glTF files.  Can/should this be added to both?

**Comment by julienduroure** [comment]
Done for importer!
