### ISSUE TITLE
FileNotFound Error: Could not find module 'C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\lib\site-packages\extern_draco.dll' (or one of its dependencies).

### ISSUE THREAD

**Issue by JohnBurrill** [KhronosGroup/glTF-Blender-IO#2439]
**Describe the bug**
GLTF file with Draco compression import incomplete

**To Reproduce**

1. In a blender startup scene, go to File>Import>GLTF/GLB (the file navigation dialog will appear)
2. in the file navigation dialog, navigate to the GLTF file (example attached)
3. with the default options, enabled click 'Import'
4. the system console will report the following:

> FileNotFoundError: Could not find module 'C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\lib\site-packages\extern_draco.dll' (or one of its dependencies). Try using the full path with constructor syntax.
> Repository data: C:\Users\johnb\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\blender_org not found, sync required!

**Expected behavior**
The GLTF file imports objects, materials, animation, lighting and camera data into the active collectoin
-as it did in Blender 4.2.2 LTS
**Screenshots**
![image](https://github.com/user-attachments/assets/1e0b1c31-3ff3-470c-b83b-d03d815a2b3e)

**.blend file/ .gltf (mandatory)**
A zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

If you are not allowed to share your file, make sure to create a new one from scratch that shows the issue. You can also try to delete or modify some data (objects, change textures, replace some meshes by some placeholder), to be able to share it without restriction.
[0085-0779-0934_wo_chain.zip](https://github.com/user-attachments/files/18098263/0085-0779-0934_wo_chain.zip)
The zip file containing the blender import example blend files was too large to attach here.  It can be downloaded from this dropbox link:
(url) https://www.dropbox.com/t/zvbGezlGHlzvBaW7

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.82, 2.83, or build date]
 - Blender 4.3.0

**Additional context**
GLTF file was generated from Solidworks 2024 SP5.0

**Comment by julienduroure** [comment]
Hello,

Please update to 4.3.1 that solves the issue.
Closing this ticket, as already solved and already reported multiple times.
