### ISSUE TITLE
Shadeless Material:  support Color only export

### ISSUE THREAD

**Issue by vis-prime** [KhronosGroup/glTF-Blender-IO#2442]
For my car models i used to have a pbr material with fully black color and full roughnesss for parts inside/under the car to get a shadeless look.
Using shadeless material here instead will be better for webgl performance and my application in three.js seems to converting shadeless materials in gltf to its equivalent THREE.MeshBasicMaterial internally.

only problem is the material is always white.

![Screenshot 2024-12-15 151126](https://github.com/user-attachments/assets/c5b10f33-8b53-4924-8409-d38c50d4c954)
**Describe the solution you'd like**
The [docs](https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#exporting-a-shadeless-unlit-material) mentions how to export a unlit texture. A similar case can be added for color too ?
and when image and color are both used then the mix color node set to multiply could be used just like diffuse color

color only concept 
![Screenshot 2024-12-15 150422](https://github.com/user-attachments/assets/1bb3db27-7fae-4dfb-8076-47feec2833e0)

Update

im not sure if gltfloader in three js supports color correctly either i found this class https://github.com/mrdoob/three.js/blob/2898f5b1ba10b1e94174c0a62d072f5f7b80442c/examples/jsm/loaders/GLTFLoader.js#L653

**Comment by scurest** [comment]
This already works when I try it. Testing with Blender 4.3.1.

(Btw, you can just connect the RGB or Texture node directly to the shader node output to get an unlit material too.)
