### ISSUE TITLE
Import: importing vertex colors fails in recent 2.79

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#249]
For this check

https://github.com/KhronosGroup/glTF-Blender-IO/blob/efc84ebf740af8f92f0e5a93ed240d7ced30b186/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py#L168-L170

Blender has used RGBA vertex colors since at least 2.79.4, possibly earlier. Importing a model with vertex colors in recent 2.79 currently raises an exception.

**Comment by julienduroure** [comment]
I don't know if we have to support "recent" 2.79, or only stable version (2.79b and future 2.80).
But if there is a simple fix, I will do it

Julien

**Comment by scurest** [comment]
@julienduroure Thanks! This works if the model has RGBA vertex colors, but it still throws `sequences of dimension 0 should contain 4 items, not 3` for models with RGB colors.

**Comment by julienduroure** [comment]
@scurest Do you have a test file?
