### ISSUE TITLE
GLB models with Draco compression don't load in Blender 2.8

### ISSUE THREAD

**Issue by EtagiBI** [KhronosGroup/glTF-Blender-IO#252]
Hello,

GLB models with Draco compression don't load in Blender 2.8. I get this error:
`RuntimeError: Error: Extension KHR_draco_mesh_compression is not available on this addon version`

Blender 2.8 build: 74db65e5424-win64

**Comment by julienduroure** [comment]
Hello,
this is a known "issue", Draco is not implemented in this addon (importer neither exporter).

There is some plan to implement it. We will keep you informed when we will work on it

**Comment by EtagiBI** [comment]
> Hello,
> this is a known "issue", Draco is not implemented in this addon (importer neither exporter).

Hmm. I was sure it worked in some old builds of Blender 2.8 Beta. Or was it KHR_Texture_Transform?.. Anyway, I do hope that Draco compression will have a high priority in your roadmap. 

Thanks for all your efforts!

**Comment by Zool1987** [comment]
until it's settled in blender 2.8...
How to decode draco_gltf_file or draco_gld_file back through the gltf - pipeline? It turns out to encode, but not back …Is there an online tool for decoding?

**Comment by rmas97** [comment]
Hello, is there any alternative way to decode a Draco compressed file and import it in Blender (2.81a)?
Thank you very much! 

(sorry for  bad english,  is not my native language)

**Comment by donmccurdy** [comment]
You can open a Draco-compressed glTF file in threejs.org/editor/ and export back out to glTF. That would remove any Draco compression on the file.

**Comment by rmas97** [comment]
It worked. Thank you very much for the hint! 
Best regards

**Comment by lanxinger** [comment]
Draco export works now but import is still broken. Is that something on the roadmap?

**Comment by julienduroure** [comment]
Draco importer is not really "broken", because it is only not implemented yet.
Don't think someone worked on it yet, so I can't provide any roadmap. I will let you know when we will be able to provide more information

**Comment by lanxinger** [comment]
Sorry for the wrong wording. Thank you for your quick response. Looking forward to having this ability in the future.

**Comment by donmccurdy** [comment]
Another workaround here, probably simpler than https://github.com/KhronosGroup/glTF-Blender-IO/issues/252#issuecomment-579885205 —

```sh
npm install --global @gltf-transform/cli@alpha

# Make an uncompressed copy of 'compressed.glb'
gltf-transform copy compressed.glb uncompressed.glb
```

^The `copy` command decompresses by default now, but in the future that will probably require a more specific command. After decompressing the file, Blender will be able to read it.

**Comment by resuly** [comment]
> Another workaround here, probably simpler than [#252 (comment)](https://github.com/KhronosGroup/glTF-Blender-IO/issues/252#issuecomment-579885205) —
> 
> ```shell
> npm install --global @gltf-transform/cli@alpha
> 
> # Make an uncompressed copy of 'compressed.glb'
> gltf-transform copy compressed.glb uncompressed.glb
> ```
> 
> ^The `copy` command decompresses by default now, but in the future that will probably require a more specific command. After decompressing the file, Blender will be able to read it.

The alpha version keeps throwing this error. 

![image](https://user-images.githubusercontent.com/3870826/94231671-d89ab580-ff47-11ea-8328-3a265d2d200c.png)

**Comment by julienduroure** [comment]
@resuly You can report bugs on gltf-transform here : https://github.com/donmccurdy/glTF-Transform

Let's try to keep this repo for Blender importer / exporter issues

**Comment by donmccurdy** [comment]
That issue should be fixed if you update to the latest alpha (by re-running the same installation command). Otherwise, as Julien suggests, I'm happy to take bug reports on the repo above. Thanks for letting me know! 👍

**Comment by donmccurdy** [comment]
Fixed at https://github.com/KhronosGroup/glTF-Blender-IO/pull/1268.
