### ISSUE TITLE
Import: AnimatedTriangle sample model doesn't rotate around a complete circle

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#254]
AnimatedTriangle has an issue with antipodal quaternions, cf. https://github.com/KhronosGroup/glTF-Sample-Models/issues/185 and https://github.com/KhronosGroup/glTF/issues/1395.

The way I solved this was to

    for i in range(1, len(quaternions)):
        if quaternions[i].dot(quaternions[i-1]) < 0:
            quaternions[i] = -quaternions[i]

**Comment by julienduroure** [comment]
ReOpened for bone management

**Comment by scurest** [comment]
@julienduroure That's still not right.

When you convert quaternions to Eulers or matrices, you lose the information about whether you had q or -q, so flipping signs before you do that is totally useless. It works for that test file only because it happens to go down the `if not node.parent` branch so it doesn't go through matrices/Eulers. [Here](https://github.com/KhronosGroup/glTF-Blender-IO/files/2829825/RotateNonRoot.zip)'s a file that goes down the `else` branch and still has the problem.

You should do that loop as the last step, to `final_rots` just before you call `fill_fcurves`. And I'm pretty sure if you do that you don't need the Euler round-trip.
