### ISSUE TITLE
Only export deforming bones

### ISSUE THREAD

**Issue by fkaa** [KhronosGroup/glTF-Blender-IO#260]
I have a bit of a problem with exporting my animations, where my non-deforming bones in my rig also gets outputted. Would it be possible to add an option to only export deforming bones, similar to the one in the Blender FBX exporter?

**Comment by Lexpartizan** [comment]
I make simple IK-rig and add non-deform bones for this. Off constraint and load bvh-animation.
Some constraint is on (for fingers, etc)
In Blender all OK. If i export to glb - mesh heavily damaged.
Blend-file and GLB included and named "deform"

If i delete additional non deform bones, export to GLB normal, with mesh all OK.
Blend-file and GLB included and named "non-deform".

if it is still relevant.
[bug glTF.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2969917/bug.glTF.zip)

**Comment by julienduroure** [comment]
See #460 
A PR #479 is currently in test

**Comment by jitspoe** [comment]
I also really need this.  Using rigify ends up exporting a TON of bones, and Godot struggles with all of them.  The better collada exporter has an option for this but I'd prefer to use glTF since the files are like 1/40th the size and better collada doesn't work in 2.8.

**Comment by julienduroure** [comment]
Hello,
I know this is a required feature. This is on our TODO list, but I can't say when it will be implemented.

**Comment by jitspoe** [comment]
I was hoping it would be as simple as checking if bone.use_deform is true before calling gather_joint, but I obviously screwed something up with my first attempt.

**Comment by julienduroure** [comment]
@jitspoe Of course this is not as simple as you said, this would be already done for a long time. 
Bones inherit location, rotation and scale from parents that can be non deformation bones, so some "baking" is needed for these bones

**Comment by donmccurdy** [comment]
> Bones inherit location, rotation and scale from parents that can be non deformation bones, so some "baking" is needed for these bones

Would it be OK to keep the bones, but not include them in the joint list of the skin? So for example:

- bone_1
  - bone_2
    - empty_object
      - bone_3

That would make the export simple enough (I hope), and we probably wouldn't even need an option for this behavior. Whether Godot would perform better with empty objects than with non-deforming bones, I don't know...

**Comment by jitspoe** [comment]
I'm not sure how Godot would handle it.  I think it would be preferable to completely exclude the bones from the export and bake the transforms into the deformation bones.  I know glTF is designed to allow transmission between different applications, but, for many, it's a format that can be imported into a game engine, so we'd like to only have game-relevant information in it.

Doesn't one of the settings bake the animations already?  Does that not bake the full transforms?

**Comment by julienduroure** [comment]
@jitspoe this bake local transformations, but not inheritance from parents. This is the next step

**Comment by jitspoe** [comment]
Might be worth looking at the source to the better collada exporter, as that seems to work well (aside from collada being a terribly bloated format -- also, I don't think it's compatible with 2.8).

https://github.com/godotengine/collada-exporter

**Comment by julienduroure** [comment]
Will be done in #713

**Comment by Lexpartizan** [comment]
Very thanks!
