### ISSUE TITLE
Material is not exported

### ISSUE THREAD

**Issue by mholthausen** [KhronosGroup/glTF-Blender-IO#262]
When creating a scene with a mesh in it, that is assigned with a new Material (either through Material pane or by Python Scripting) with a diffuse color, e.g.:
` 
activeObject = bpy.context.active_object
mat = bpy.data.materials.new(name="Material")
activeObject.data.materials.append(mat)
    bpy.context.object.active_material.diffuse_color = (random.uniform(0, 1), random.uniform(0, 1), random.uniform(0, 1))
`
the assigned material/color is not exported into the glb-File when watching it in the gltf-viewer (https://gltf-viewer.donmccurdy.com/)
Following setup and steps have been processed:
Date: 2019-01-27 19:17
Hash: 690478027bd7
Branch: blender2.7

Running on Linux Mint 19
The worklfow consists of:
1) Importing a shapefile into Blender with the BlenderGIS-Plugin (https://github.com/domlysz/BlenderGIS/tree/Blender28) as mesh where the normals of some triangles are up and some others are down
2) Assigning a material and color to the mesh
4) Exporting the scene as glb
5) Uploading the scene into the glTF-Viewer (https://gltf-viewer.donmccurdy.com/) and the assigned color is missing

In Blender 2.79 with the current master of glTF-Blender-Exporter it works like expected (without double sided, of course)

**Comment by UX3D-schmithuesen** [comment]
Thank's for already telling us your OS and Blender version :+1: 
Please also setup and submit a `.blend` file that produces the problem.

**Comment by UX3D-schmithuesen** [comment]
You have to toggle “Use Nodes” in the Shader Editor. Even in Blender it doesn't use the material if that's off.
![image](https://user-images.githubusercontent.com/44766936/51974214-b35a5900-247f-11e9-8a1d-29b00f37556e.png)

**Comment by mholthausen** [comment]
> You have to toggle “Use Nodes” at the top in the Shader Editor. Even in Blender it doesn't use the material if that's off.
> ![image](https://user-images.githubusercontent.com/44766936/51974214-b35a5900-247f-11e9-8a1d-29b00f37556e.png)

This works. From my point of view, this issue can be set to closed, I guess.
