### ISSUE TITLE
Importer: Put all objects in the active collection

### ISSUE THREAD

**Issue by capnm** [KhronosGroup/glTF-Blender-IO#263]
E.g. the Collada importer does it right (Collection 3):

![image](https://user-images.githubusercontent.com/4047289/51897543-45466100-23af-11e9-9fff-a5ca06f70a4d.png)

**Comment by julienduroure** [comment]
Some thoughts:
- Some glTF files has multiple scenes inside, so there is no "active collection" in that case

A solution may be (for 2.80 only):
- add an importer option to choose to create objects in active collection or to create a new collection to create objects inside
- for new scene created, create a default collection inside

**Comment by emackey** [comment]
Further thoughts about multiple scenes in https://github.com/KhronosGroup/glTF/issues/1542

+1 for putting normal single-scene glTFs into the active collection, without adding any new UI for it.

**Comment by julienduroure** [comment]
I started the work in import_in_collection branch

Still need to be tested carefully with all cases (no scene, 1 scene, multiple scenes, existing yet in blender or not,  ...)

**Comment by julienduroure** [comment]
It's now merged into master, and push into blender repo. Should be available soon inside blender

**Comment by capnm** [comment]
Great, already in productive use :-) I have found only a small issue #337 so far.
