### ISSUE TITLE
Remove old files from Blender source

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#265]
@julienduroure can you help with this one?

Five files were removed from this repo in a cleanup, in 9d3c7b12d15c8590daa48cfa69c3330991c483ac.

But, it the latest install from blender.org still includes these files.  It seems they should be deleted from the Blender distribution as well.

These appear to be the only "extra" files present in the Blender distribution.

```
addons/io_scene_gltf2/blender/com/gltf2_blender_image_util.py
addons/io_scene_gltf2/blender/exp/gltf2_blender_animate.py
addons/io_scene_gltf2/blender/exp/gltf2_blender_filter.py
addons/io_scene_gltf2/blender/exp/gltf2_blender_search_scene.py
addons/io_scene_gltf2/io/com/gltf2_io_functional.py
```

**Comment by julienduroure** [comment]
Done!
