### ISSUE TITLE
Exporter: Exporting results in .test.png files

### ISSUE THREAD

**Issue by moll** [KhronosGroup/glTF-Blender-IO#27]
Hey again!

Image Texture nodes with JPG images as sources for the Principled BSDF node in Blender for some reason result in the export also having `foo.jpg.test.png` files in the output directory.

**Comment by donmccurdy** [comment]
Yep that sounds like a bug. 👍 Any chance you could share a `.blend` file?

**Comment by moll** [comment]
I saw it with at least two files, one old, one new. Are you not experiencing it yourself or is the .blend request preemptive? :)

**Comment by donmccurdy** [comment]
This is my default reply when an issue is reported that I've never seen before, but yeah it turns out i can easily reproduce this on current version. :)

**Comment by UX3D-becher** [comment]
fixed with 0f5abbb2915ea951aae41926a1fb939c40b00c73
