### ISSUE TITLE
Import: alpha not working

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#271]
![fire](https://user-images.githubusercontent.com/11024420/52084788-7a49e380-2568-11e9-85e6-237c9a3993dd.png)

Maybe because of the KHR_material_unlit?

[fire.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2818976/fire.zip)

(This is squished for the same reason as #257).

**Comment by julienduroure** [comment]
ReOpened, this is solved only for 2.79, not for 2.80
