### ISSUE TITLE
Exporter: KHR_materials_pbrSpecularGlossiness not supported

### ISSUE THREAD

**Issue by JernejL** [KhronosGroup/glTF-Blender-IO#272]
I've tried to export this file to gltf multiple times, each time i don't get any images for my materials exported. 
 
I'm using blender 2.79b and fresh copy of gltf-blender-io plugin from yesterday. 
 
Is there anything else that has to be set up for this to work? 
 
All sample files (.blend and the resulting gltf file): 
 
[rocketlauncher.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2824545/rocketlauncher.zip)

**Comment by julienduroure** [comment]
You have to use principle node, like in following image : 
https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/docs/addons_io-gltf2-material-principled.png

**Comment by JernejL** [comment]
Can you please explain, that exactly that means? 
Is there an documentation page explaining what is in the image?

**Comment by julienduroure** [comment]
Draft documentation is here for now: 
https://gltf-blender-io-docs-gbueavkvns.now.sh/addons/io_gltf2
Principled BSDF node is the node used for PBR shading in Blender

**Comment by JernejL** [comment]
Is there a tutorial, which explains how to convert existing model materials to PBR?

**Comment by julienduroure** [comment]
You can find tutorials about Principled shader node on any search engine. (I don't have any specific tuto in mind) or in blender documentation : 
https://docs.blender.org/manual/en/latest/render/cycles/nodes/types/shaders/principled.html

I will close this bug report, don't hesitate to comment if you think there is really a bug

**Comment by emackey** [comment]
This model uses the spec/gloss workflow, and the .blend project uses a material with a node setup that looks like it came almost directly from the importer reading a `KHR_materials_pbrSpecularGlossiness` material.

Does the exporter output the importer's node setup for `KHR_materials_pbrSpecularGlossiness`?

A quick search of the source code reveals a ton of importer logic surrounding spec/gloss, but no obvious export logic.  Even the old custom node for spec/gloss is not working for me.  Seems like the whole feature is missing.

**Comment by emackey** [comment]
@JernejL This is not likely to be a quick fix.  The metallic/roughness PBR workflow, used by the Principled BSDF node, is what will work correctly today.

**Comment by JernejL** [comment]
@emackey i'm not that good with blender, i've used other modelling packages and was really stumped at why my textured materials were not being exported at all, there was no warning during export either and nothing else that provided a clue, i was not even aware of the whole shader materials feature in blender. It seems like there's also a complete lack of up-to-date tutorials on how to set up shader materials in blender 2.79. 
 
I've followed this: https://docs.blender.org/manual/en/latest/render/blender_render/materials/nodes/introduction.html#accessing-the-node-editor 
and after switching material mode and going to compositing screen to edit nodes, there's nothing there, contrary to what the tutorial describes (i am to expect material and output node, but neither is created or shown). 
 
A video tutorial, showing how to convert a classical material to PBR would help a lot. 
 
Btw, the model came from https://sketchfab.com/models/a53d6716c9c24302a6fdd71ff70a7d63 - i downloaded the "autoconverted" gltf file that they provide, they have more models where models imported into blender don't export again, but sometimes they work ok, for example https://sketchfab.com/models/66fd4a4ffcb64edfac68131c5ff4973c works OK (import and export).

**Comment by Ali-RS** [comment]
Seems `KHR_materials_pbrSpecularGlossiness` is not yet taken into account by the exporter, any plan to fix this? 

I think if the importer is going to take it into account then the exporter should do the same.

**Comment by donmccurdy** [comment]
This is complex to implement, and not currently a high priority. Especially since Blender itself focuses on the metal/rough workflow in recent versions. I think it would be useful to have some way (whether in the Blender importer or some other tool) to convert a spec/gloss model to a metal/rough model. I don't think we should be consider spec/gloss a priority target for exporting, though.

**Comment by donmccurdy** [comment]
Quick update here, currently the workarounds for this issue are:

* **(A)** After importing a glTF model using the spec/gloss workflow, reconfigure its nodes to match the addon's documentation so it exports correctly to metal/rough PBR.
* **(B)** Before importing a glTF model using spec/gloss, convert it offline with the `metalrough` command from https://gltf-transform.donmccurdy.com/cli.html, then import to Blender.

**Comment by donmccurdy** [comment]
@emackey would it be OK to close this? I feel like it will be a large enough task to support upcoming metal/rough PBR features in Blender, I'm not sure we should spend the effort to support exporting the spec/gloss workflow, especially when metal/rough is what Blender itself is focused on.
