### ISSUE TITLE
Export with Rigify Armature is broken.

### ISSUE THREAD

**Issue by Angeloss** [KhronosGroup/glTF-Blender-IO#276]
Using Blender 2.8. Some animations are also repeated/broken.

![image](https://user-images.githubusercontent.com/862976/52293180-e13a1480-293b-11e9-832f-9297b66da718.png)

**Comment by donmccurdy** [comment]
Would you be able to share an example `.blend` file? You can attach ZIP archives to GitHub comments. Thanks!

**Comment by Angeloss** [comment]
> Would you be able to share an example `.blend` file? You can attach ZIP archives to GitHub comments. Thanks!

Sure, here it is:
[PlayerCharacter.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2833356/PlayerCharacter.zip)

I forgot to mention that I'm using Blender 2.8 and I'm trying to export to a Game Engine.
Thank you.

**Comment by pjoe** [comment]
FWIW: I just figured out an issue with inverse bind matrices (they did not take the mesh object xform into account). Working on a PR - this may help :)

**Comment by pjoe** [comment]
PR #280

**Comment by setpixel** [comment]
I believe this to be very related to my issue here: https://github.com/KhronosGroup/glTF-Blender-IO/issues/232

**Comment by setpixel** [comment]
@donmccurdy checking now!

**Comment by setpixel** [comment]
Hmm - no it doesn't seem to fix it.
![screenshot 2019-02-07 10 40 41](https://user-images.githubusercontent.com/441117/52422919-09a14a80-2ac5-11e9-8d9e-a51d8b3f950f.png)

**Comment by donmccurdy** [comment]
Ok thanks for checking! Looks like there are additional issues.

**Comment by setpixel** [comment]
I think the issue is around the skin order

**Comment by Angeloss** [comment]
Thanks for checking this guys, you are awesome! [We](http://www.gamecoderstudios.com/) are trying to use gltf to make a game multiplayer game with [godot](https://godotengine.org/).

**Comment by donmccurdy** [comment]
Initially exporting I see this error:
![screen shot 2019-02-08 at 1 06 19 pm](https://user-images.githubusercontent.com/1848368/52506468-860a5b00-2ba3-11e9-83d7-629d26a5f121.png)

That's not the core issue here (there's stuff to fix in the skinning export, for sure) but want to not lose track of it.

**Comment by julienduroure** [comment]
This is now solved
