### ISSUE TITLE
importer: support of KHR_texture_transform

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#277]

**Comment by EtagiBI** [comment]
Hello,

Is it possible to use Blender Importer code to add support of KHR_texture_transform? In Blender 2.79 models with this extension can be exported flawlessly.

**Comment by julienduroure** [comment]
If someone want to test, I implemented it on import_KHR_texture_transform branch
@emackey @donmccurdy

**Comment by emackey** [comment]
@julienduroure I'd like to test it.  Can you open a PR for the branch?

**Comment by julienduroure** [comment]
@emackey Done!
