### ISSUE TITLE
Status on MS VI?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#284]
While Milestone VI (https://github.com/KhronosGroup/glTF-Blender-IO/milestone/6) has been closed, many of its issues are still open. What's the current status of those? Are they still planned, do we need to prioritize just a subset of them for MS VII, or do they all need to be moved to the Community milestone?

/cc @emackey @UX3D-nopper @UX3D-schmithuesen

**Comment by UX3D-nopper** [comment]
Think I moved them all

**Comment by UX3D-nopper** [comment]
The bugs (if caused from "us", not old ones) we will fix, the enhancements are up to the community.

**Comment by UX3D-nopper** [comment]
@donmccurdy Let's have a 1:1 next week, where we can priorize things, okay?

**Comment by donmccurdy** [comment]
Sounds good!

**Comment by setpixel** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/issues/232 😄

**Comment by emackey** [comment]
My personal wish-list is:

* Occlusion Map and Double Sided controlled from a "glTF Export" node (which has inputs but no outputs), https://github.com/KhronosGroup/glTF-Blender-IO/issues/123#issuecomment-460860865

This represents a very important capability that glTF offers, that this exporter does not.  Sample models that use occlusion or double-sided can't round-trip correctly without this.

* Custom normal vector export, #230 

Sample models like the Water Bottle can't correctly round-trip without this, they pick up a seam down the side.

* "Export Selected" refinements, https://github.com/KhronosGroup/glTF-Blender-IO/issues/193#issuecomment-453543304

This would help the plugin feel more predictable and reliable, by giving users better control.

**Comment by titansoftime** [comment]
Any update on the skinning export issues? I have my animator on hold and we are at a standstill.

**Comment by UX3D-nopper** [comment]
I understand your issue but please note, that this is still a Beta Release and should not bes used for production. 
We already discussed this issue and probably a hack could be easily done to solve this issue. But we do not want to do this and implement a proper solution.

**Comment by titansoftime** [comment]
I wish three.js people would have taken that into consideration before dumping their json loader and adopting this as a primary loader. /cry Obviously not your guy's fault.

**Comment by setpixel** [comment]
For anyone that is having skinning issues. We came up with a solution that works!

1. Export FBX

2. Use https://github.com/facebookincubator/FBX2glTF/releases

Example: ./FBX2glTF-darwin-x64 -b --blend-shape-normals --blend-shape-tangents --pbr-metallic-roughness -i shot-generator-models/characters/base/male-youth/male-youth.fbx -o shot-generator-models/characters/base/male-youth/male-youth

The structure is not exactly the same as the exporter, but it works! - blendshapes and all!

It's a good temporary solution until the skinning issue is fixed! Great work guys!!!!!!

**Comment by emackey** [comment]
> please note, that this is still a Beta Release and should not be used for production.

I don't do any skinning, but I use many other aspects of this exporter and have considered it production software for some time now (since the previous one was deprecated some months ago).  If there's still a Beta label on here, we should work towards removing it as soon as is reasonable.

**Comment by UX3D-nopper** [comment]
The beta is mentioned on this GitHub README page and the goal is to be final close before Blender 2.80 gets final. That was the original plan.

**Comment by donmccurdy** [comment]
> * Occlusion Map and Double Sided controlled from a "glTF Export" nod

I believe this should be a relatively lightweight addition – do we just need to look for that `glTF Export` name, the same way we look for the old Metal/Rough node? If so, I or another contributor can probably add that easily.

> * Custom normal vector export...

> * "Export Selected" refinements...

Agreed that both are important. I think the first is likely to be quite complex (I tried to implement it a while ago, and didn't get far). The latter, we or the community can certainly get to in the future.  Tracked in #193.

> Any update on the skinning export issues?

We're working on this (thanks UX3D!) and plan to have a great many of these issues resolved in March. In the meantime, we always appreciate examples of issues, PRs like #280 and #287, and improvements to the CI tests to allow us to prevent these problems in the future.

I've gone through the remaining issues in MS VI and moved most out of the Milestone, leaving mostly Compression- Skinning-related tasks in MS VII. Remaining issues in MS VI (#193 and #154) I consider high-priority and will try to get to myself, though if anyone else can tackle them sooner PRs are welcome. :)
