### ISSUE TITLE
Skinning export regression on "Lain_2" example.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#289]
This was an example we'd tested against (for multiple animation support) in the previous exporter. Currently it's failing - I think some of the open PRs should help, but haven't got it working yet.

[lain-20_blender.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2846879/lain-20_blender.zip)

![screen shot 2019-02-08 at 1 17 24 pm](https://user-images.githubusercontent.com/1848368/52506588-e39ea780-2ba3-11e9-9602-f45ef174adb5.png)

**Comment by donmccurdy** [comment]
This is improved after https://github.com/KhronosGroup/glTF-Blender-IO/pull/412, but not yet fixed.

**Comment by julienduroure** [comment]
Seems issue is now solved
