### ISSUE TITLE
Import: primitives add too many vertices

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#294]
If a primitive has N elements in its POSITION accessor, N vertices always get added to the mesh, even if the indices accessor is, say, [0, 1, 2], so there should actually only be three vertices. This can result in a huge explosion in vertex count.

JoeyVrowl originally noticed this issue and made a test file. See https://github.com/KhronosGroup/UnityGLTF/issues/197, https://github.com/ksons/gltf-blender-importer/issues/29.

![extra-verts](https://user-images.githubusercontent.com/11024420/52544916-7ba1ba00-2d79-11e9-81b7-25f79e02a3d2.png)  
_Taking apart a corner reveals many extra verts._

**Comment by scurest** [comment]
@julienduroure The vertex count looks good! Two things:

1. This breaks the model from #257. Possibly you need to do something for joints/weights/vertex colors too?
2. This doesn't only happen when the indices and vertices have different lengths. A quad has indices [0,1,2,2,3,0] with length six but only makes four vertices.

**Comment by julienduroure** [comment]
OK, should avoid to code late during the night ... I checked for normals & UV, but forget to check skinning ...

**Comment by scurest** [comment]
Skinning is fixed! But not vertex colors :)

**Comment by julienduroure** [comment]
And probably not morphs target too!

**Comment by julienduroure** [comment]
@scurest I pushed some fixes, can you please test again?
Thanks for pointing this :)

**Comment by scurest** [comment]
I can confirm vertex colors are fixed!

Unfortunately I have no models that use morph targets, so I can't confirm they work, but the code for them looks good.
