### ISSUE TITLE
Exporter: skinned mesh gets weird when it's rotated

### ISSUE THREAD

**Issue by soadzoor** [KhronosGroup/glTF-Blender-IO#296]
Hi,

I'm trying to export the "dancing stormtrooper" model that I've found here as a collada (.DAE) file:
https://github.com/EvanBacon/expo-dancing-stormtrooper

If I export it with the latest 2.8 beta, it has this very strange, deformed look:
![capture](https://user-images.githubusercontent.com/10392261/52732172-d298d080-2fbf-11e9-87bf-faafcd2a0978.PNG)

If I change this rotation from `180` to `0`, then it works ok (except that the model is upside-down. But at least it's not deformed.)

![capture2](https://user-images.githubusercontent.com/10392261/52732971-d299d000-2fc1-11e9-8589-47b6ca14c729.PNG)

Additional note: When I imported it as `.DAE`, it was similarly deformed within blender, but I guess `.DAE` is a different department of development, so you guys have nothing to do with that.

Probably a totally different topic: when I export it as `.glb`, it produces a much larger file, than when I export it as `.gltf` + `.bin` + `textures`. Probably it's converting the textures to PNG, or something.

[stormtrooper.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2861523/stormtrooper.zip)

**Comment by AcuarelaVerdemar** [comment]
Similar result but without animation. Just an export with a skinned model and rig.
Here's the model without armature:

![test01](https://user-images.githubusercontent.com/48050522/53480059-ad559900-3a7a-11e9-970a-994df0a95247.jpg)

Here everything included:

![test02](https://user-images.githubusercontent.com/48050522/53480137-da09b080-3a7a-11e9-84c1-1b678eac3bc7.jpg)

Probably not relevant but, as mentioned in another issue, it will be great to be able to export only deforming bones, and not the entire rig setup.

[MaleRig.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2909486/MaleRig.zip)

**Comment by setpixel** [comment]
Hi Friends, is there any idea when the work on the exporter's skinning issues will start? If so, I'd like to help.

**Comment by setpixel** [comment]
i think this is fixed in the latest version fyi

**Comment by UX3D-becher** [comment]
animation is fixed with #412
