### ISSUE TITLE
Is Blender Game material supported?

### ISSUE THREAD

**Issue by DaviesX** [KhronosGroup/glTF-Blender-IO#300]
If not, will it be supported in the future?

**Comment by emackey** [comment]
Unfortunately, Blender Game Engine, along with the old Blender Internal renderer, has been [completely removed from Blender 2.80 and beyond](https://blender.stackexchange.com/a/106988/18161).  This addon is focused on supporting the "Principled BSDF" node and related nodes from Eevee and Cycles, but no further work is happening on BGE (Game).

Sorry for the bad news!

**Comment by DaviesX** [comment]
Ah, thanks for the reply. I didn't know BGE is removing from blender.

**Comment by emackey** [comment]
Yeah, I did like BGE, but it had its limitations being tied to all of Blender.  At this point a dedicated game engine is probably a better choice.  If you're commercial, check out Unity or Unreal, but if you're looking for free/open source, maybe try [Godot](https://godotengine.org/), it takes glTF files as one possible input.
