### ISSUE TITLE
`Background` shader does not export unlit material

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#301]
Using a `Background` shader does not create an unlit material when exported using the latest Blender 2.8 Beta.

The `KHR_materials_unlit` extension is added in the file, but it appears to have no effect.

Node graph:
![image](https://user-images.githubusercontent.com/4733018/52921176-65987a00-32e2-11e9-8e8c-c1b1d484a138.png)

The material appears to be affected by environment and direct lighting, but not by ambient lighting. My impression is that it should not be affected by _any_ lighting.

Without light:
![image](https://user-images.githubusercontent.com/4733018/52921249-1a329b80-32e3-11e9-9ff0-2c771f48459d.png)

With light:
![image](https://user-images.githubusercontent.com/4733018/52921255-24ed3080-32e3-11e9-808b-5b25e0f6c4d0.png)

`blend` and `glb` files:
[background_shader_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2873544/background_shader_test.zip)

Blender version:
![image](https://user-images.githubusercontent.com/4733018/52921345-10f5fe80-32e4-11e9-8fde-433a0b2b97b7.png)

**Comment by UX3D-schmithuesen** [comment]
The “problem” is that the unlit material extension is an empty dictionary which I explicitly excluded from the export with this [commit](https://github.com/KhronosGroup/glTF-Blender-IO/commit/ee76c295fd1a8aea56b9310ddca26ee0eccb455b). I will think of a good solution.
