### ISSUE TITLE
Node rotation not exported if node scale is 0

### ISSUE THREAD

**Issue by Cyp** [KhronosGroup/glTF-Blender-IO#302]
The node rotation is not exported if the node's scale is 0.

A case where this actually causes an issue is where there is a static rotation and an animated scale, and the export happens to be done during a frame where the scale is 0.

This happens since `blender_object.matrix_local` doesn't contain rotation information when the scale is 0, and `gltf2_blender_gather_nodes.__gather_trans_rot_scale` uses `matrix_local`.

I'm not sure what a good clean solution is. Just using `rotation_*` wouldn't work since the `matrix_parent_inverse` has to somehow be taken into account. Not sure it's solvable in general, since the transformation might not even be decomposable. One non-ideal solution might be to detect if a scale axis is 0, and if so temporarily change the scale to 1 and recompute the rotation.

A workaround is to only animate the scale down to 0.00001.

**Comment by Cyp** [comment]
Encountered some blender weirdness — seems 0.00001 is too small. Although now the node has the right transformation, child nodes apparently have completely wrong transformations. The `matrix_local` of the child nodes is wrong. Seems like blender is doing something really weird here, since parent transforms shouldn't have any effect at all on `matrix_local`. Even a scale of 0.01 gives visible artefacts due to horrible precision of `matrix_local` in children.

**Comment by UX3D-schmithuesen** [comment]
@Cyp Is it important for you to export the model at a specific frame? If not, I would suggest that we add the option (maybe even as default) to export the model at frame 0 where everything should have a sane state.

**Comment by UX3D-schmithuesen** [comment]
I noticed that there even is a checkbox in the export settings for this, but only if animations are disabled and even then, it didn't seem to work so we fixed that.

**Comment by Cyp** [comment]
I think exporting at a specific frame (such as 0) makes sense for consistency, since the currently selected frame shouldn't affect the export.

In my case, it happens at frame 0, so exporting at frame 0 wouldn't fix it, but in my particular case, setting the scale to 0.1 turned out to be good enough.
