### ISSUE TITLE
Importer's handling of spec/gloss

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#303]
I tried importing the [SpecGlossVsMetalRough](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough) sample model, but the results don't look correct in Blender.  The two bottles use different techniques, but are supposed to look visually identical:

![specglossvsmetalrough_visualissue](https://user-images.githubusercontent.com/1235080/52971094-2884c400-3384-11e9-9065-2f77c5732f3d.jpg)

## Problem Nodes

Looking at the node graph produced by the importer, I see a couple issues:

- The specular color is not treated with the correct colorspace, per spec.  It should *not* be marked "Non-color data" because there is color in the RGB channels.  It should be a normal "Color" image.
- The roughness values are all zeros.

This screenshot shows nodes & links as created by the importer, organized for presentation here and marked up a bit, but functionally unchanged:

![Imported nodes](https://user-images.githubusercontent.com/1235080/52971183-86b1a700-3384-11e9-97c4-ec4487d8c5f2.png)

I'll present several different options here, starting with one that I think would be the easiest path to improvement.

## Option 1

In the screenshot below, the following edits have been made to the node structure:

* Spec/Gloss image switched to "Color" mode.
* The Alpha channel of the spec/gloss image (which corresponds to Glossiness) is sent through an Invert node (`1.0 - x`), and is used as the Roughness value for both the "Glossy BSDF" and "Diffuse BSDF" nodes.
* The Glossy BSDF and Diffuse BSDF nodes are added together at full strength.  (So a "Mix" shader with a factor was replaced by an "Add" shader, with no factor).

![diffuseglossnodes_simple](https://user-images.githubusercontent.com/1235080/52971348-1a837300-3385-11e9-8aa7-15862ef061da.png)

This node setup works pretty well for models like this one, where bright diffuse and bright specular colors are not used on the same pixel.  Technically, this is not "energy conserving", as it's missing one key formula from the `KHR_materials_pbrSpecularGlossiness` spec.  I'll address that in Option 2.

## Option 2

Building on top of Option 1, this adds 5 additional nodes to the graph.  It makes things fairly complex, but it replicates a [formula from the spec](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness#specular---glossiness) that conserves energy by not allowing the diffuse and specular channels to double-up the reflected amount of light.

The formula in question is:  *c<sub>diff</sub>* = `diffuse.rgb * (1 - max(specular.r, specular.g, specular.b))`

![diffuseglossnodes_energyconserving](https://user-images.githubusercontent.com/1235080/52971712-7995b780-3386-11e9-92c9-cf77262b2d47.png)

In the above node graph, the specular color is separated out into R, G, B components, the max of all 3 components is found, inverted, and multiplied by the diffuse color texture.  The rest of the node graph is the same as Option 1 above.

This node graph produces a result that appears to exactly match the reference.  But it's a very complex node tree, and the exporter has really zero hopes of ever exporting something like this correctly, so I would certainly understand if this path is not followed.  But this one is the most technically correct as far as I know.

## Option 3

Blender Eevee has added a new `Specular` node, specifically for the spec/gloss workflow, that can take the place of all of this.

However, there are serious caveats:

- It's only Blender 2.80 Beta, not 2.79x.
- It's only Eevee, not Cycles.
- It's Beta and subject to change before release.

But there are also some advantages:

- It has a hookup for a baked ambient occlusion map, which we've not seen before in Blender at all.
- Its readability is the highest of any of these options.
- The exporter could easily be upgraded to round-trip something like this.

![eeveespecularnode](https://user-images.githubusercontent.com/1235080/52972106-c0d07800-3387-11e9-872d-f12454a91f33.png)

**Comment by emackey** [comment]
The results of all of these options looks basically the same.  All of our current sample models are properly energy conserving, so I wouldn't expect much visual difference among them.

Option 1
![option1_result](https://user-images.githubusercontent.com/1235080/52973297-94b6f600-338b-11e9-9c89-7d5c76898d70.jpg)

Option 2
![option2_result](https://user-images.githubusercontent.com/1235080/52973305-9aacd700-338b-11e9-9865-8aca7398425e.jpg)

Option 3
![option3_result](https://user-images.githubusercontent.com/1235080/52973308-9e405e00-338b-11e9-9891-dc19689fdf34.jpg)

**Comment by julienduroure** [comment]
Will start working on option 1 soon

**Comment by emackey** [comment]
@julienduroure I just noticed there's a `fix_KHR_specglo` branch from April 10.  Is that a work-in-progress or is it ready for testing?  No rush but whenever it's ready for people to look, can you open a PR?  Thanks.

**Comment by julienduroure** [comment]
Still have to test some corner cases, will do a PR asap
