### ISSUE TITLE
Importer: fps

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#31]
Currently, no checks are done on fps, that can lead to incorrect animations.
2 possibilities:
*  Add a warning when calculated fps in animation doesn't match to scene fps
*  Automatically change scene fps, based on gltf file fps

I think we don't have to change fps automatically. My choice goes to warning user only

**Comment by scurest** [comment]
@julienduroure What is this issue about? I didn't understand it. Currently the FPS is used as the unit conversion between glTF seconds and Blender frames, right?

**Comment by julienduroure** [comment]
Closing this ticket, as there is no bug here
