### ISSUE TITLE
Animated armatures objects are not supported

### ISSUE THREAD

**Issue by artellblender** [KhronosGroup/glTF-Blender-IO#310]
Animated armatures leads to an error, breaking the export.
Please test the following blend file, it contains a simple armature setup (one bone), while the armature object is animated too:
[cube_armature.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2888895/cube_armature.zip)

The function` get_target_object_path()` return `""` when accessing the armature fcurves datapath, which breaks the path_resolve function `bone = blender_object.path_resolve(get_target_object_path(target_datapath))`

I've tried to add an exception, exporting works, but the armature object animation is not exported.

**Comment by UX3D-schmithuesen** [comment]
this duplicates #234 
I will leave it open to keep the extra example for now.
