### ISSUE TITLE
All animations have the same duration

### ISSUE THREAD

**Issue by meroon** [KhronosGroup/glTF-Blender-IO#314]
Hello,

I'm pretty new with Blender and GLTF, so please bear with me. 

I've got a very simple blend file that has 2 actions with different durations. I've setup the actions in 2 NLA channels. When I export the glb file and preview the file, the animations show up. However, they both seem to share the duration of the shortest clip. Is there something I need to do specifically to get the animation duration's to export properly? 

I've attached my blend file [cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2891237/cube.zip)

Thank you!

Edit: I've tried this on 2.79C and 2.8

**Comment by donmccurdy** [comment]
Note the **Limit to playback range** option it the *Animation* settings. With the end time set to 20 (see below) all clips will be limited. However, you should also be able to leave that option enabled, and just expand your playback range to 40 frames – that will give each clip its full length

![screen shot 2019-02-21 at 1 05 49 pm](https://user-images.githubusercontent.com/1848368/53201701-7d6d4800-35d9-11e9-908e-b6ece689b496.png)

**Comment by meroon** [comment]
Uggghhhhhh.......thank you so much.

**Comment by Zenahr** [comment]
> Note the **Limit to playback range** option it the _Animation_ settings. With the end time set to 20 (see below) all clips will be limited. However, you should also be able to leave that option enabled, and just expand your playback range to 40 frames – that will give each clip its full length
> 
> ![screen shot 2019-02-21 at 1 05 49 pm](https://user-images.githubusercontent.com/1848368/53201701-7d6d4800-35d9-11e9-908e-b6ece689b496.png)

How come this determines the action length at export? It would be much less confusing if Blender would by default export an action based on where the last keyed frame ends. This would end the confusion of many users.
