### ISSUE TITLE
Import occlusion map

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#321]
@julienduroure I'm curious if you would be willing to modify the importer to preserve an occlusion map using an empty custom node.  For example, when occlusion is combined with metal/rough, perhaps the importer could produce something similar to this:

![image](https://user-images.githubusercontent.com/4733018/52835512-b0cd4580-30b4-11e9-8581-6d1d04149285.png)

I think I've worked out the code for creating and using a node group like this.  This is what I have so far:

```
    # Put this definition somewhere common, it will likely change to "glTF Settings" or similar.
    gltf_node_group_name = 'glTF Metallic Roughness'

    # The following code runs per-material for materials with occlusion.

    # Check if the custom node group already exists
    if gltf_node_group_name in bpy.data.node_groups:
        gltf_node_group = bpy.data.node_groups[gltf_node_group_name]
    else:
        # Create a new node grouping
        gltf_node_group = bpy.data.node_groups.new(gltf_node_group_name, 'ShaderNodeTree')
        gltf_node_group.inputs.new("NodeSocketFloat", "Occlusion")
        gltf_node_group.nodes.new('NodeGroupOutput')
        gltf_group_input = gltf_node_group.nodes.new('NodeGroupInput')
        gltf_group_input.location = -200, 0

    # Place a new node grouping in the current material
    gltf_settings_node = bpy.data.materials[material_idx].node_tree.nodes.new('ShaderNodeGroup')

    # Set the newly placed node grouping to be the glTF grouping
    gltf_settings_node.node_tree = gltf_node_group
    gltf_settings_node.width = 220
```

From there you would connect the `R` channel of the occlusion image texture to the one socket on the new custom node.

**Comment by emackey** [comment]
Of course this has no effect in Blender preview, since it calculates its own AO.  This would just be for round-trip purposes.

**Comment by donmccurdy** [comment]
+1 for renaming this node to `glTF Settings` or `glTF Export`.

**Comment by julienduroure** [comment]
@emackey @donmccurdy I made a first draft on branch import_ao_node

**Comment by emackey** [comment]
Testing it now, thanks @julienduroure!

First thing I noticed, `Double Sided` doesn't need to be in the custom node group anymore, that got fixed in #304.  I think Occlusion is the only remaining member of that node group.

**Comment by julienduroure** [comment]
@emackey Ok, DoubleSided is now removed

**Comment by julienduroure** [comment]
@emackey Any other review before I merge it?

**Comment by emackey** [comment]
Further review discussion in #437.
