### ISSUE TITLE
Armature animation exports incorrectly

### ISSUE THREAD

**Issue by anim-crash** [KhronosGroup/glTF-Blender-IO#322]
Hi, I have a rigged model in Blender with a pair of animations, and I'm using the GLTF exporter to export this scene to a .glb file. Sometimes the exporter has been crashing, although other times it has worked. But now I seem to have reached a state where it's crashing every time I try to export.

The bottom of the call stack reads:

File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py". line 115, in __gather_output
bone = blender_object.path_resolve(get_target_object_path(target_datapath))
ValueError: Object.path_resolve("") could not be resolved

I downloaded the latest GLTF exporter today, but it shows the same issue.

I've attached the .blend file (which is just a character from a freebie model site with my test anim) and a screenshot of the exporter crash:
[anim_export_crash.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2896894/anim_export_crash.zip)

This seems to be a common problem rather than an issue with just this one .blend file, as a different freebie character model I downloaded from some other author also gets the same crashes on animation export too.

Thanks for your help.

**Comment by anim-crash** [comment]
![crash_call_stack](https://user-images.githubusercontent.com/47635818/53287847-ba704080-3779-11e9-8fb6-016ae0937643.png)

**Comment by anim-crash** [comment]
Just spotted this duplicate complaint from a month ago:

https://github.com/KhronosGroup/glTF-Blender-IO/issues/234

Apparently animated armatures causes the crash. I don't understand animations enough to know how to work around this. Can someone tell me how to clear this animation in Blender?  It would be good to get it fixed, as it seems to be affecting a lot of people, and it's easily reproducable.

**Comment by donmccurdy** [comment]
@UX3D-becher the crash is fixed (thanks!) but this doesn't seem to be animating correctly yet. Should we leave this open so we have the model to test remaining issues against?

**Comment by donmccurdy** [comment]
![220e2bbd-70fc-4461-a412-a69753ef2887-29851-0000470282e000f9](https://user-images.githubusercontent.com/1848368/53521563-5a391180-3a8d-11e9-889c-76bcdbcd34d0.gif)

*(bad GIF quality but the issue is clear enough hah)*

**Comment by UX3D-schmithuesen** [comment]
> the crash is fixed (thanks!) but this doesn't seem to be animating correctly yet. Should we leave this open so we have the model to test remaining issues against?

Oh! The other bug report with this issue worked out fine after our fix so we just closed all apparent duplicates. Apparently, there is more work involved! This might just be related to our overall rigged animation issues that will be tackled next month.
