### ISSUE TITLE
Imported armature issues

### ISSUE THREAD

**Issue by Quinten123** [KhronosGroup/glTF-Blender-IO#324]
[Hummingbird_Gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2899935/Hummingbird_Gltf.zip)

Whenever i import this gltf file the armature comes out weird. Bones are uncorrectly sized, unconnected to the parent, and rotated. 
![screensht_1](https://user-images.githubusercontent.com/42477397/53330092-ef050900-38ed-11e9-8a07-5bbe72353756.JPG)
![screensht_2](https://user-images.githubusercontent.com/42477397/53330097-f3312680-38ed-11e9-8f21-5e52784d75a0.png)

**Comment by julienduroure** [comment]
I don't think there is any issue here.
"bone" object (with a head and a tail) has no equivalent in glTF (where you can find "joint"). That means that :
- There is no size stored in glTF, because a joint is ponctual
- bones are correctly parented, but there is no notion of connection between joints (except parent /  child relationship that are OK in your example file)
- rotation seems to be legit regarding data that are glTF file
- animation seems to be OK

I will set this issue as "enhancement", because we probably could fake some rotation on created bones to have them visually better aligned.

**Comment by Quinten123** [comment]
Thank you, I do hope it will it will be improved, so it's easier to see the structure of the bones and work with them more easily. Right now it's a bit difficult. If you need more gltf files like this i have a bunch more.

**Comment by scurest** [comment]
Bones are rotated and sized plausibly in [gltf-blender-importer](https://github.com/ksons/gltf-blender-importer/issues). At least non-leaf bones

![hum](https://user-images.githubusercontent.com/11024420/53841604-ca9ad380-3f62-11e9-9b2e-a403271df644.png)

Basically, we pick a rotation cr(b) for each bone b, and the local-to-parent T(b) for that bone is replaced with T'(b) = cr(pb)^{-1} T(b) cr(b) where pb is the parent of b. Then when you compose with the parent, T'(pb) T'(b), the cr(pb)^{-1} at the right of T(b) is cancelled out by the cr(pb) on the left of T(pb), and so on up the tree, so it doesn't end up affecting the skin. You have to maintain the relation between T'(b) and T(b) when you animate pose bones too.

This is probably the most annoyingly complicated thing in that importer, but see [this comment about picking the edit bones](https://github.com/ksons/gltf-blender-importer/blob/6ec918eed9ee56d009e5287531805792623caa62/addons/io_scene_gltf_ksons/vnode.py#L300-L376) and [this comment about picking the pose bones during animation](https://github.com/ksons/gltf-blender-importer/blob/6ec918eed9ee56d009e5287531805792623caa62/addons/io_scene_gltf_ksons/animation/node_trs.py#L83-L133).

**Comment by Quinten123** [comment]
Thank you so much! I have tried the importer and everything works fine, even the animations! Now i can work with it alot easier.

Kind regards,

Quinten

**Comment by julienduroure** [comment]
@scurest & @Quinten123

Thanks for pointing me to that algo. 
I was thinking about something like that. I will implement it inside this official addon

Julien
