### ISSUE TITLE
Exporting mesh parented direcly to bone

### ISSUE THREAD

**Issue by baronwatts** [KhronosGroup/glTF-Blender-IO#326]
When exporting multiple meshes using the glTF 2.0 exporter in Blender, I notice that the rotation of the gun mesh needs to be flipped in order for it to work properly. Is this a bug? The gun mesh is parented to the bone.

Blender file:
![bld](https://user-images.githubusercontent.com/14098949/51309158-68fdc480-1a09-11e9-95c8-f4df88757605.jpg)

glTF Viewer:
![gltf-viewer](https://user-images.githubusercontent.com/14098949/51309191-79ae3a80-1a09-11e9-9045-137edefa554b.jpg)

Blender Settings:
![blender-settings](https://user-images.githubusercontent.com/14098949/51309207-816ddf00-1a09-11e9-9ec3-defd97a96a61.png)

[Link to the .blend file](https://discourse.threejs.org/t/exporting-multiple-meshes-using-the-gltf-exporter/5771)

**Comment by julienduroure** [comment]
Probably same issue than #603
Here, location seems broken. In #603, rotation seems KO too
