### ISSUE TITLE
Exporter freezes when exporting with animation

### ISSUE THREAD

**Issue by vtange** [KhronosGroup/glTF-Blender-IO#327]
I have a model I downloaded and re-rigged myself and have been testing with Babylon.js. It is a mostly vertex-painted model with the solidify modifier to add the cartoon outline effect.

It exports and loads fine, armature and all, in Babylon.js. without animations.

![static](https://user-images.githubusercontent.com/4667949/41080547-ebcf8fbc-69db-11e8-9f19-81403fe1ec30.png)

So I added a simple Head Turn animation for starters. Nothing too fancy.

I tried the latest version of Kupoman's gltf exporter as of today and it exports without error but the animations are incorrect - the head distorts instead of turns, and the character doesn't turn her head a full 90 degrees each direction. 

In the older version of this exporter (latest from October 2 2017), it exports without error and seems to animate properly, but many other bones seem to be displaced and there are black artifacts everywhere.

![glitched](https://user-images.githubusercontent.com/4667949/41080791-e4e20288-69dc-11e8-9ec3-8823d25dee70.png)

In the latest version of this exporter, however, it exports fine without animations but the moment I check [export skinning] it will never finish exporting. Blender stops responding and I'm forced to close it.

Oddly enough, the older version of the exporter manages a smaller gltf (5MB) than the newest one (10MB). Is this supposed to happen?

Here is the file for reference:

[GwenSimp - w_head_turn.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2079066/GwenSimp.-.w_head_turn.zip)

**Comment by scurest** [comment]
This model now exports and displays with no obvious visual problem in Three/Babylon. The validator reports that there are still zero weights, but that is tracked by #308.

@donmccurdy
