### ISSUE TITLE
Model exported with 5 identical skins.

### ISSUE THREAD

**Issue by Nehon** [KhronosGroup/glTF-Blender-IO#328]
This one is more tricky and I couldn't dig out a proper lead...
Consider this model
[Jaime.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1235482/Jaime.zip)
It has a fairly complex rig. When I export it I get this files. (note that it's exported with default settings except that selected only is checked, with the mesh selected, export skinning, force sample application is checked, Bake skinning application is checked).
[gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1235499/gltf.zip)
There are 5 identical skins exported. (there should be one.) And only the last one is actually references by the mesh node.
I can't figure out where it comes from.

**Comment by julienduroure** [comment]
This needed to be tested again with blender 2.81 alpha

**Comment by julienduroure** [comment]
Seems to be solved now
