### ISSUE TITLE
Importer: Parent armature with blender style

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#33]
Parent mesh to armature --> This is way it's done in Blender, using armature modifier
We need to parent correctly, keeping offset

**Comment by donmccurdy** [comment]
Note that I don't think the exporter can currently write the parented armature/mesh pair back out correctly — see https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/74. Ideally we'd support this in both importer and exporter, if I've understood the issue correctly.

**Comment by julienduroure** [comment]
This is done in #48 
Closing
