### ISSUE TITLE
GLTF import ignores active collection

### ISSUE THREAD

**Issue by EtagiBI** [KhronosGroup/glTF-Blender-IO#332]
Hello,

As for now GLTF import ignores active collection, so all models go to Scene Collection after export. All other importers take active collection into account, so I assume GLTF importer should follow this workflow as well.

**Comment by julienduroure** [comment]
Hello,
This is a duplicate of #263, so I am going to close this issue, and discussion can continue on #263

Note that code is mostly done on branch import_in_active_collection, and should be merged in next weeks
