### ISSUE TITLE
Emissive texture exported but not used

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#334]
In attempts to export with a material using an emissive texture through the `Emission` shader, the emissive texture is exported but not used.

Blender version:
![image](https://user-images.githubusercontent.com/4733018/53522663-e3117680-3aa8-11e9-9e01-6825ac2663d9.png)

This is my node graph:
![image](https://user-images.githubusercontent.com/4733018/53521878-3b477900-3aa7-11e9-9e6d-6ee410ffac54.png)

What it should look like (and how it appears in Blender):
![image](https://user-images.githubusercontent.com/4733018/53521938-5ca86500-3aa7-11e9-9ead-8b02e4d306b4.png)

How it appears in @donmccurdy's glTF viewer (https://gltf-viewer.donmccurdy.com/):
![image](https://user-images.githubusercontent.com/4733018/53521990-7cd82400-3aa7-11e9-80f4-d15c4b602201.png)

The exported emissive texture:
![image](https://user-images.githubusercontent.com/4733018/53522533-92018280-3aa8-11e9-9604-f50f99e27716.png)

`.zip` contains `.blend`, `.glb`, and the emissive texture as it was exported:
[emissive_texture_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2912282/emissive_texture_test.zip)

I hope I'm not missing something here, but I followed the proposed graph pretty closely.

Thanks!

**Comment by emackey** [comment]
Are you sure you're using the latest source?

The fix just went into Blender earlier today, it probably hasn't built yet.

https://developer.blender.org/rBA82574a386e1ee717e34e960c529e21c8787e04e7

**Comment by emackey** [comment]
#320

**Comment by dsinni** [comment]
I used the latest build from Blender.org at the time of posting, but it looks like it's since been updated. I will try again with the new build.

**Comment by dsinni** [comment]
Just tried in new build. Looking good! That was easy.

Closing. Thanks!
