### ISSUE TITLE
Importer does not always take into account the current scene.

### ISSUE THREAD

**Issue by capnm** [KhronosGroup/glTF-Blender-IO#337]
Blender 2.8 addons dd0dffef42ae64d1bf16e879e3f1470ce3bf5cad

Repro:
* load factory settings
* create a new scene (or alternatively a new collection inside)
* select the new or the scene collection

The importer inserts the content in a selected scene of the first scene and switches the blender UI to it.
It doesn't occur if you rename the first (default) scene.

----

I then tested importing a collada model there and it worked, but importing a gltf model immediately after that, gave the following error:
```
... CRITICAL Data are loaded, start creating Blender stuff
Traceback (most recent call last):
  File "bin/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 458, in execute
    return self.import_gltf2(context)
  File "bin/2.80/scripts/addons/io_scene_gltf2/__init__.py", line 479, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "bin/2.80/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py", line 53, in create
    bpy.ops.object.mode_set(mode="EDIT")
  File "bin/2.80/scripts/modules/bpy/ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1
```

**Comment by julienduroure** [comment]
Can you please provide what glTF files you try to open?
Because the way it's working depend of the name of scenes in glTF files.
I can't reproduce for now, I want to try with your files

**Comment by julienduroure** [comment]
OK, I got it.
Not linked to collection, but to armature stuff.
Trying to import a glTF with armature when there is already another armature in another scene

**Comment by capnm** [comment]
Hmm weird, I can reproduce that with armature-less models:
* open i337-test.blend
* import cone.glb

I see 2 issues:
* the cone is imported in a wrong scene
* the cone is rotated

[i337.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2918413/i337.zip)

addons 044a574f371b51ce1084f393426517709998ccb0
blender -v
```
Blender 2.80 (sub 45)
	build date: 2019-03-01
	build time: 07:47:30
	build commit date: 2019-03-01
	build commit time: 05:59
	build hash: 90526e1606c3
	build platform: Linux
	build type: RelWithDebInfo
```

**Comment by julienduroure** [comment]
About wrong scene : Because your gltf file says that your scene is named "Scene", so because you have a "Scene" scene in your blend file before importing, it will add data to scene "Scene", not your current scene

About rotation: it's maybe linked to a Blender bug that I already found. Need more investigation

**Comment by capnm** [comment]
> ... Because your gltf file says that your scene is named "Scene"

Oh I see ;)
I think the gltf scene name should be (in the single scene case) ignored, otherwise it's not easy to understand or predict what exactly happens after importing an unknown gltf file.

> About rotation

The cone seems to be OK if the scene name collision doesn't happen:
[i337-test-ok.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2918695/i337-test-ok.zip)

**Comment by capnm** [comment]
I have looked a little bit in the code around. I would simply change
https://github.com/KhronosGroup/glTF-Blender-IO/blob/239af04ea39c47ebfc9c171eb89e5ad4a53173f0/addons/io_scene_gltf2/blender/imp/gltf2_blender_scene.py#L32

to

```python
	if scene_idx is not None and len(gltf.data.scenes) > 1:
```

or if someone finds it useful, make it optional.

----

**For comparison the obj importer**.
Gives a nice timing report with `bpy_extras.wm_utils.progress_report` at least for the terminal user:)
```
(  0.0001 sec |   0.0001 sec) Importing OBJ '/intranet/blender-build/issues-pr/glTF/gltf-io-issues/i337b/cone.obj'...
  (  0.0004 sec |   0.0001 sec) Parsing OBJ file...
    (  0.0022 sec |   0.0013 sec) Done, loading materials and images...
    (  0.0093 sec |   0.0084 sec) Done, building geometries (verts:65 faces:62 materials: 1 smoothgroups:1) ...
    (  0.0204 sec |   0.0195 sec) Done.
  (  0.0212 sec |   0.0208 sec) Finished importing: 'cone.obj'
Progress: 100.00%
```

I don't know why they use the `context.view_layer.active_layer_collection.collection`, bpy.context.collection also appears to use the active view layer.
 
```python
...
        progress.step("Done, building geometries (verts:%i faces:%i materials: %i smoothgroups:%i) ..." %
                      (len(verts_loc), len(faces), len(unique_materials), len(unique_smooth_groups)))

        # deselect all
        if bpy.ops.object.select_all.poll():
            bpy.ops.object.select_all(action='DESELECT')

        scene = context.scene
        new_objects = []  # put new objects here
...
        view_layer = context.view_layer
        collection = view_layer.active_layer_collection.collection

        # Create new obj
        for obj in new_objects:
            collection.objects.link(obj)
            obj.select_set(True)

            # we could apply this anywhere before scaling.
            obj.matrix_world = global_matrix

        scene.update()
...
        progress.leave_substeps("Finished importing: %r" % filepath)
...
