### ISSUE TITLE
Exporting only selected objects doesn't quite work for lights

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/glTF-Blender-IO#34]
I've opened the 04_lights.blend scene from glTF-Blender-Exporter repo. I've selected only one light in the scene and then tried to export it. In the exporter options I have both "Export selected only" and "Export KHR_lights" checked.

The output gltf file doesn't have all the information about the light I selected:

[04_lights.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/2411063/04_lights.txt)

When I unckeck "Export selected only" it seems to work fine. But of course it exports all lights.

PS: Posting the same issue here as well because I'm not sure what's the difference between this repo and glTF-Blender-Exporter. Previously created issue here: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/304

**Comment by UX3D-becher** [comment]
This is a bug in the glTF-Blender-Exporter

**Comment by UX3D-becher** [comment]
glTF-Blender-IO will eventually replace glTF-Blender-Exporter, so development efforts shifted from the latter project to the former. 
Have you tried the export with glTF-Blender-IO?

**Comment by godlikepanos** [comment]
I did. When I reported the issue (24 days ago) both glTF-Blender-IO and glTF-Blender-Exporter were affected. 

I'll try to re-test glTF-Blender-IO when I get home and I'll update this ticket. Maybe something changed between those 24 days.
