### ISSUE TITLE
Exported Mesh heavily deformed.

### ISSUE THREAD

**Issue by jbu4github** [KhronosGroup/glTF-Blender-IO#341]
Hello,

I have a blender model (made in 2.80 - wont open in <= 2.79) which heavilly deforms (looks like someone pulled it to pieces) when exported using gltf exporter with skinning. (see .zip attached)

Interestingly the corruption only happens when I subdivide the central bone in the armature, I have checked that all parenting is correct, I deleted all modifiers and vertex groups and animations before applying the automatic armature deform, nothing allows this to export correctly (with the skinning option checked on the export menu)

Checking other issues/bugs I thought perhaps there were too many influences for some vertices after subdividing the bone, but in the former case, there are still 5/6 influencers for some vertices near the head.

I cant find anything like what it could be, so I have to conclude that its the exporter - works fine in blender.

Any help is greatly appreciated :)

[oddish.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2923087/oddish.zip)

**Comment by UX3D-becher** [comment]
fixed with #398
