### ISSUE TITLE
Mesh LOD

### ISSUE THREAD

**Issue by Quinten123** [KhronosGroup/glTF-Blender-IO#342]
Hi,

I was wondering if anyone could check if this gltf file has mutliple mesh LOD's. When i import it I get a decimated model. Is there another LOD version inside the file?

Kind regards,

Quinten
[Whale.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2926714/Whale.zip)

**Comment by donmccurdy** [comment]
Yes, it's using the `MSFT_lod` extension, which is really only supported in Microsoft tools. Although, I can't quite tell what that's doing here – it looks like there's only one mesh, so maybe the LODs just affect the material?

It could also be that the original file had a subdivision modifier on it, which got lost somewhere in conversion.

/cc @bghgary should `MSFT_sRGBFactors` extensions be included in these exports?

**Comment by Quinten123** [comment]
Yea the msft_lod seems to be for texture resolution

**Comment by bghgary** [comment]
> should MSFT_sRGBFactors extensions be included in these exports?

This was used for backwards compatibility when some of our implementations were doing the wrong thing. This is no longer relevant. We will stop writing this out eventually, but it should be harmless.

**Comment by julienduroure** [comment]
Well, seems there is no action on blender importer/exporter here. Closing this ticket
