### ISSUE TITLE
Export several animated objects on a single track/clip

### ISSUE THREAD

**Issue by 3dmediatoonz** [KhronosGroup/glTF-Blender-IO#344]
I have a Blender file with several animated objects linked in a hierarchy (imagine a robot made of about 30 object)... no armature, only links and transforms.

When exported to GLB or GLTF, each single object has a separate animation track, instead of an unique "master track"... but i need an unique track on the exported GLB.

I tried the FBX exporter, and it can join tracks; also i tried to upload to sketchfab and re-download my model, and i got a single track... but i can't have a single track on a directly exported model... 
...any suggestion?

Thanks.

**Comment by donmccurdy** [comment]
Transferring this feature request to the new repository.

**Comment by donmccurdy** [comment]
Let's start with https://github.com/KhronosGroup/glTF-Blender-IO/issues/557 and revisit if other options are needed.
