### ISSUE TITLE
Material export error (parrot model)

### ISSUE THREAD

**Issue by Antokolos** [KhronosGroup/glTF-Blender-IO#345]
Let's take a look at this parrot model:
[parrot.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2495150/parrot.zip)
load it and select the animation called "surprise" in the dope sheet. Take a look at the wings:
![image](https://user-images.githubusercontent.com/7196697/47207455-16325380-d3ad-11e8-9d16-5fb9a3ac9e94.png)
Now export it to GLTF format with the following settings enabled:
![image](https://user-images.githubusercontent.com/7196697/47209211-98247b80-d3b1-11e8-86e6-b79f868c61c2.png)
Place the resulting GLTF file in the Godot game engine, select the animation "surprise" in the AnimationPlayer node and take a look at the wings:
![image](https://user-images.githubusercontent.com/7196697/47209362-ff423000-d3b1-11e8-8295-cf8d31691e38.png)
Tail motion isn't correct too, it seems that the skeleton does not follow the geometry well (somehow it outside the parrot body):
![image](https://user-images.githubusercontent.com/7196697/47207793-f4859c00-d3ad-11e8-9e8d-25c2d01179a0.png)
Maybe it is really a bug in the Godot game engine, but I don't know another way to test the resulting GLTF :)

**Comment by donmccurdy** [comment]
This model now exports correctly if i disable materials. 

With materials enabled, I see the following error:

<img width="763" alt="Screen Shot 2019-06-18 at 3 55 51 PM" src="https://user-images.githubusercontent.com/1848368/59725434-82868080-91e2-11e9-9f98-3969ada5a864.png">

**Comment by donmccurdy** [comment]
The material looks normal enough to me:

<img width="775" alt="Screen Shot 2019-06-18 at 4 02 05 PM" src="https://user-images.githubusercontent.com/1848368/59725460-9336f680-91e2-11e9-8e2f-94e064e62913.png">

**Comment by emackey** [comment]
@donmccurdy That stack trace is what happens currently if you try to export from a `.blend` file that references image files that are not available, such as when the `.blend` file has been moved to a new system without its texture images.

It will be a very common problem, so we should put a better error message there.

**Comment by julienduroure** [comment]
We have a similar issue in #543, where there is a texture node, but without any file set. We should add a error message in that case too
