### ISSUE TITLE
Importing animated glb resulted in deformed mesh.

### ISSUE THREAD

**Issue by tlaukkan** [KhronosGroup/glTF-Blender-IO#349]
I tried importing the following animated glb file resulted in deformed mesh. Worked appropriately with:

https://gltf-viewer.donmccurdy.com/

[quaternius_Male_Casual.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2948158/quaternius_Male_Casual.zip)

**Comment by julienduroure** [comment]
Confirmed,
Will check soon

**Comment by julienduroure** [comment]
I probably identified the source of this issue. 
(Transformations are not transfered from outside of armture to root bone).
Have to find a way to fix it

**Comment by julienduroure** [comment]
Tested with latest master: Seems that there is no more deformation.
Bones length are not scale appropriately , but this is only visual
