### ISSUE TITLE
Exporter: Animation missing.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#35]
Basic example attached; animations are not included on export:

[CubeAction.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2412366/CubeAction.zip)

**Comment by donmccurdy** [comment]
@UX3D-nopper do you think it would be possible to address this by the time of the Blender conference? It would be a major disadvantage over glTF-Blender-Exporter to not have animation.

**Comment by UX3D-nopper** [comment]
Also, please note, that this is something extra we do. So no need for rushing.

**Comment by UX3D-nopper** [comment]
Okay, got it, fixed it here:
9e77e0e

**Comment by UX3D-nopper** [comment]
BTW, for the experimental exporter, we do run unit tests/glTF validator on it.
