### ISSUE TITLE
Exporter raises error when roughness and metallic image textures have different resolution in Blender 2.8

### ISSUE THREAD

**Issue by roxlu** [KhronosGroup/glTF-Blender-IO#350]
Because currently the GLTF 2.0 exporter in Blender 2.8 will combine the  roughness and metallic maps into one PNG (using seperate channels) they should use the same resolution. When you use different resolutions for these the exporter fails. 

Using this node setup: 
https://imgur.com/a/GB94aKp

Crash log: https://gist.githubusercontent.com/roxlu/065707a844b890534eb80801e3164c5b/raw/ed54ccddce18e088f5188f772a647605d17d1829/gistfile1.txt

**Comment by emackey** [comment]
In glTF 2.0, these maps are always combined.  They're part of the same image, and as such they must be the same resolution.

I suppose we could have the exporter up-sample one of the images to match the other, or it could produce a nicer error message.  Would that be worthwhile?  But the resulting file will always have these two channels at the same resolution.

**Comment by UX3D-schmithuesen** [comment]
> it could produce a nicer error message

Sounds worthwhile to me!

**Comment by UX3D-soares** [comment]
We can leave it open for merging images as a future enhancement.

**Comment by scurest** [comment]
This was fixed by #1059.
