### ISSUE TITLE
Rotation animation not playing as expected

### ISSUE THREAD

**Issue by eatschnitzeleveryday** [KhronosGroup/glTF-Blender-IO#351]
I am trying to animate a spinning windmill. 2 key frames: one at Euler X 0° and one at Euler X 360°. It does a full rotation in blender as expected, but upon export the animation doesn't move because 0° apparently equals 360°. If I use a value of 359°, the animation moves by -1° instead of +359°. I didn't have this issue with an older version of the exporter, before multiple animations were implemented.

**Comment by donmccurdy** [comment]
Merging to https://github.com/KhronosGroup/glTF-Blender-IO/issues/558, as this works correctly with sampling enabled.
