### ISSUE TITLE
Importer: animation stash

### ISSUE THREAD

**Issue by mikejsavage** [KhronosGroup/glTF-Blender-IO#354]
[cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2954273/cube.zip)

That file has two animations as you can see from the JSON:

```
"animations":{
        "channels":[...],
        "name":"dash",
        "samplers":[...]
},
{
        "channels":[...],
        "name":"jump",
        "samplers":[...]
}
```

But when you import it into blender they get merged into one:

![image](https://user-images.githubusercontent.com/579299/54159422-a0ab4a80-4455-11e9-96df-3ff96579acb5.png)

I think this is a bug because it means exporting and then reimporting a model will give you a different result to what you started with.

**Comment by scurest** [comment]
They're not merged into one. There are two actions. If you select the cube, open the Dope Sheet, then switch to the Action Editor, you can pick which action you want the cube to use.

![actions](https://user-images.githubusercontent.com/11024420/54181624-225aa280-446d-11e9-84e7-727ba122349d.png)

It is still a bug for the reason you gave though. The importer should push the actions to an NLA track in some way that the exporter can use to reconstruct the same animations as the original glTF file.

**Comment by julienduroure** [comment]
Setting Stash of action into NLA as enhancement
