### ISSUE TITLE
Import: wrong bone during animation?

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#356]
[untitled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2955649/untitled.zip)

![blender](https://user-images.githubusercontent.com/11024420/54183436-289f4d80-4472-11e9-9eff-b07a93e2b37e.png)

Correct version on the right. (Also note this model has the wrong up axis; don't mind that.)

It looks like maybe just one bone is wrong? This doesn't involve any non-unit scalings so it's different than #257, and it doesn't look like the effect from #349 either.

**Comment by julienduroure** [comment]
I can confirm that something is wrong about upleg bones.
Bones in edit mode seems to be ok, but KO after animation

**Comment by julienduroure** [comment]
Problem identified. Will push it tonight
