### ISSUE TITLE
CUBICSPLINE exports the same value for tangents & values

### ISSUE THREAD

**Issue by gszauer** [KhronosGroup/glTF-Blender-IO#361]
Looking at the [Red Fox](http://www.mediafire.com/file/hssb4kgs0uo06pi/Animals+Pack+by+Quaternius.rar) model from [Quaternius](http://quaternius.com/assets.html) asset packs.

I'm using the default settings for the exporter with blender-2.80-798d2cadc307-win64

When i export the animated model after fixing up the bind pose, as described in #360 the final animation scales a bit.

![fox_broken](https://user-images.githubusercontent.com/1061030/54311062-12d47a00-4591-11e9-8ae1-9c0af393b732.gif)

There are two "easy" ways to fix this issue. Export with "Always Sample Animations", or go trough the dope sheet and mark any tracks that are linear data (but use bezier curves) as "linear". The screenshot below uses the second approach

![fox_works_v2](https://user-images.githubusercontent.com/1061030/54310675-28956f80-4590-11e9-9ea1-bdb02fb3643c.gif)

So, in either fix case, the thing that actually works is switching to linear interpolation.

if we look at the y channel of "Bone.001" it contains the following data:

| Frame | Time  | in         | value      | out        |
|-------|-------|------------|------------|------------|
| 0     | 0.000 | 1.14048088 | 1.14048088 | 1.14048088 |
| 1     | 0.333 | 1.14048088 | 1.14048088 | 1.14048088 |
| 2     | 1.066 | 1.14048088 | 1.14048088 | 1.14048088 |

The problem does appears to be that the same value is in everything. The track in question is arranged as a line, i'd expect the tangents to be 0? This is the track in blender:

![track_blend_01](https://user-images.githubusercontent.com/1061030/54311563-13b9db80-4592-11e9-8fb3-d2992706679a.PNG)

With tangents showing

![track_blend_02](https://user-images.githubusercontent.com/1061030/54311578-1c121680-4592-11e9-84d9-2ebaa45c289e.PNG)

And this is the curve as interpolated by the data in the above table:

![interp_wrong](https://user-images.githubusercontent.com/1061030/54311860-b1ada600-4592-11e9-8302-3ff3c4668f9f.PNG)

VS linear interpolation, producing the correct result:

![interp_correct](https://user-images.githubusercontent.com/1061030/54311972-f9343200-4592-11e9-8b2b-46d399bc1fc6.PNG)

I haven't tried this yet, but i suspect i can work around this by:

```
tangent = value - tangent
```

The in tangent of the first frame should be 0 according to [this page](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0)

> Implementation Note: The first in-tangent a1 and last out-tangent bn should be zeros as they are not used in the spline calculations.

**Comment by julienduroure** [comment]
Hello @gszauer . Can you please test again with a recent build, for example Blender 2.82 beta, that you can download on https://builder.blender.org/download/ ?
Thanks

**Comment by gszauer** [comment]
Tested and confirmed to be working.
