### ISSUE TITLE
Environment IBL, Reflection Probe and Irradiance Probes

### ISSUE THREAD

**Issue by sasa42** [KhronosGroup/glTF-Blender-IO#366]
would there be an possibility to export also
EnvironmentIBL 
Reflection Probes
Irradiance Probes

**Comment by donmccurdy** [comment]
@sasa42 the glTF format doesn't currently support these features, (aside from an unofficial extension) but we're looking into them.

Beyond the question of the file format itself, I recently tried to access light probe data through Blender's Python API (which is what exporters would need to use) and wasn't able to find it. If anyone knows, or feels up for the challenge of contributing to the Blender codebase, see https://devtalk.blender.org/t/access-baked-lightprobe-irradiance-volume-data-from-python/6199/2. 😇
