### ISSUE TITLE
Importer does not ignore transform of skinned mesh

### ISSUE THREAD

**Issue by Vega-KH** [KhronosGroup/glTF-Blender-IO#368]
On import, if multiple nodes / meshes share a skin, the transform matrix and TRS are ignored on all except the first.  For example, if the GLTF json code is like this:
```json
{
     "name": "node_0",
     "mesh": 0,
     "rotation": [ 0.0, 1.0, 0.0, 0.0 ],
     "skin": 0
 }
{
     "name": "node_1",
     "mesh": 1,
     "rotation": [ 0.0, 1.0, 0.0, 0.0 ],
     "skin": 0
 }
```
Then the first node (in this case, node_0) will have the rotation added on import, but the second will not.  This causes incorrect skinning.

**Comment by julienduroure** [comment]
Hello, 

Can you please provide a complete glTF or glb file that have this issue?

Thanks

**Comment by donmccurdy** [comment]
This sounds like a possible mistake on the part of the exporter... from the glTF spec:

> Client implementations should apply only the transform of the skeleton root node to the skinned mesh while ignoring the transform of the skinned mesh node.

In the example above, I don't think _either_ of the rotations should be applied. See https://github.com/KhronosGroup/glTF/issues/1285 and https://github.com/KhronosGroup/glTF/issues/1403.

**Comment by Vega-KH** [comment]
I can provide a sample where this is a problem, but I think with the note above by @donmccurdy , the problem may instead be with applying any transform and with the exporter (not Blender, in this case.)  I will verify this is an issue tomorrow and post an example.  

Also, with this limitation in mind, it seems that the exporter may need to ensure that all transforms are applied to skinned meshes before export, or there will be unexpected results.

Thanks for the replies.

**Comment by Vega-KH** [comment]
OK, now that I have learned that the transform SHOULD be ignored on skinned meshes, I am revising the issue.  The problem is that the importer does NOT ignore the transform on the first skinned mesh attached to a skin (strangely, it does ignore it on all subsequent skinned meshes attached to the same skin.)

When viewing with Microsoft 3D viewer, this is how it looks (correct) with the transform ignored on the skinned mesh:

![rig-test-3](https://user-images.githubusercontent.com/3310674/54612928-d89f2880-4a27-11e9-9ca3-8117d41b32a2.jpg)

When importing it into Blender, this is how it looks (incorrect) as the transform is not ignored:

![rig-test-3-blender](https://user-images.githubusercontent.com/3310674/54613080-19973d00-4a28-11e9-9999-c4bc394a0bea.jpg)

Here is the offending bit of JSON:

```json
{
            "mesh" : 0,
            "name" : "Cube",
            "rotation" : [
                0.5,
                0.5,
                0.5,
                0.5
            ],
            "skin" : 0,
            "translation" : [
                0,
                1,
                0
            ]
        },
```

And here is the test file:

[rig-test-3.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2983817/rig-test-3.zip)
