### ISSUE TITLE
Resampled animations should use linear interpolation

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#369]
When sampling is required (either for a technical reason or because the *Always Sample Animations* option is checked), the exporter currently forces STEP interpolation:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/287b4af31313725a0c1197cdfda413b63cae3a15/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_samplers.py#L79-L84

I think it would be better to use LINEAR interpolation here for three reasons:

1. Animation is typically sampled at 24fps, but may be played back at 60+ FPS.
2. Once the *Sampling Rate* option is supported (is it doing anything now?), a user may want to reduce the sampling rate to every N frames, and still have interpolation across those frames.
3. Using CUBICSPLINE for sampled keyframes probably doesn't make sense.

**Comment by emackey** [comment]
100% agree on LINEAR interpolation.  Some systems (particularly Cesium) may play back animations at a much faster or slower rate than they were originally sampled with, and using LINEAR smooths out these motions very nicely.

**Comment by julienduroure** [comment]
Seems this is already commited
