### ISSUE TITLE
python classes generator: add unicode support

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#37]
Currently, unicode string are not supported in python classes, and a manual commit must be done after any re-generation of python classes ( 829062d077a8a825339735899f1835c70ac498f6 ) 

We have to check if this can be handle by an option during generation

**Comment by UX3D-nopper** [comment]
@julienduroure We are using Python 3, so all strings should be unicode by default, right?
http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html

**Comment by julienduroure** [comment]
Hello,

@UX3D-nopper @UX3D-hanselmann 

I found my error.
I did my preliminary tests directly on python, on my laptop, where I didn't notice that it was python 2.7

Sorry about that, there is no need to change generator

**Comment by julienduroure** [comment]
Back to original version on f14beb0815fb458763773dba79af43b9a8d30032
