### ISSUE TITLE
Export Armature Error. Incorrect Bone LocRot

### ISSUE THREAD

**Issue by danvim** [KhronosGroup/glTF-Blender-IO#370]
I have left some comments in another issue (#237). But I've decided to move mine to a new issue to keep the issues and test files organized.

My character file: https://github.com/KhronosGroup/glTF-Blender-IO/files/2854309/character.zip

I have the following in Blender.

![](https://user-images.githubusercontent.com/5255292/52543768-28665080-2de7-11e9-9de1-fb604a671ab6.png)

This is what happened viewing in the GLTF Viewer https://gltf-viewer.donmccurdy.com/:

![](https://user-images.githubusercontent.com/5255292/52543777-4764e280-2de7-11e9-8c36-e630427333cf.png)

I  have also tried joining all the meshes, reassigning weights, applying  modifiers before exporting, and removing constraints and adding bones to  make all bones joined, but the result is still the same.

And in the viewer, when I turned on skeleton viewing, the bones  looked like they are in the correct positions, it's just that the meshes are not.

**Comment by julienduroure** [comment]
This will be solved by #653

**Comment by julienduroure** [comment]
#653 is now merge, should be fixed
