### ISSUE TITLE
Issues with "Bake skinning constraints" option

### ISSUE THREAD

**Issue by swift502** [KhronosGroup/glTF-Blender-IO#373]
Hi,

I have some issues I wanted to share.

1. If I export [this file](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2545811/game_man_sketchbookb1.zip) with [these settings](https://user-images.githubusercontent.com/24359130/47964155-c6eb5480-e035-11e8-938a-5ccb13575c04.png), the exporter overwrites the source animations with the baked ones **in the actual blend file**. That's terrible. It's as if your compiler overwrote your source code with the compiled code. :smiley: 

![image](https://user-images.githubusercontent.com/24359130/47964191-37927100-e036-11e8-8b83-1e5f69053c0b.png)

It seems to be dependent on what bones are selected when exporting. I find that quite confusing.

2. Baking IK animations doesn't seem to work perfectly. Exporting the mentioned file with the mentioned settings, somethings wrong with the **left arm**, and occasionally the legs move in a strange, twitchy way.

FBX (correct)
![](https://thumbs.gfycat.com/MeaslyDesertedCrossbill-size_restricted.gif)

GLB (left arm moves wrong)
![](https://thumbs.gfycat.com/QualifiedThunderousGecko-size_restricted.gif)

Here's the [output files](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2545821/output.zip) if they were any help...

It's subtle, but it really isn't acceptable to have an exporter alter my animations.
There's an IK target for the left elbow that seems to get messed up. I know I could bake the animations by hand, but it would be a waste of time, since the FBX exporter bakes everything perfectly.

Anything I'm doing wrong? Thanks.

**Comment by donmccurdy** [comment]
The "Bake skinning constraints" option has been removed. Exporting with default options, export fails with an error (attached below). Exporting with "Always sample animations" enabled, the export succeeds and appears correct to me, although the whole model is rotated 90º from what I'd have expected.

As we have a lot of open animation issues, I'd consider the failure when sampled animations are disabled to be low priority – more important to get everything running correctly with sampling, I think.

<img width="974" alt="Screen Shot 2019-06-18 at 3 37 15 PM" src="https://user-images.githubusercontent.com/1848368/59724604-4dc4fa00-91df-11e9-9e87-475e03bb7b4e.png">

**Comment by donmccurdy** [comment]
Tracking the remaining issue in https://github.com/KhronosGroup/glTF-Blender-IO/issues/558.
