### ISSUE TITLE
Broken morph target animation

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#374]
From @mrdoob in #52 —

***

Seems like the materials no longer export with the latest version of the exporter 😕

[alligator.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1602155/alligator.blend.zip)

<img width="629" alt="screen shot 2018-01-03 at 5 05 09 pm" src="https://user-images.githubusercontent.com/97088/34546381-4dfbf548-f0a8-11e7-8c47-5da980496107.png">

[alligator_old.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1602159/alligator_old.gltf.zip)

<img width="698" alt="screen shot 2018-01-03 at 5 04 17 pm" src="https://user-images.githubusercontent.com/97088/34546361-3404912c-f0a8-11e7-8679-e963dfa84a9f.png">

[alligator_new.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1602160/alligator_new.gltf.zip)

<img width="677" alt="screen shot 2018-01-03 at 5 04 28 pm" src="https://user-images.githubusercontent.com/97088/34546367-3a8da060-f0a8-11e7-8221-6f49c7fe78a3.png">

**Comment by donmccurdy** [comment]
Export with *Always Sample Animation*" does work, but shouldn't be necessary.

Aside: the model will appear to have inverted normals after export, but I don't think that's an exporter bug.

**Comment by mrdoob** [comment]
> Aside: the model will appear to have inverted normals after export, but I don't think that's an exporter bug.

Yeah, it's a bug in the model.

**Comment by donmccurdy** [comment]
Improved with https://github.com/KhronosGroup/glTF-Blender-IO/pull/412, but still broken.

**Comment by julienduroure** [comment]
@donmccurdy Didn't test with old version, but animation export looks to be OK now with last version.

**Comment by donmccurdy** [comment]
Looks good now, yes!

**Comment by mrdoob** [comment]
Will the fixed version land with 2.8?

**Comment by emackey** [comment]
@mrdoob Yes, generally any fix that lands in master here gets copied (by Julien) to the Blender Addons repository, and is available within about 3 days from the 2.80 [nightly builds](https://builder.blender.org/download/).  Currently, June 20's nightly build is all caught up with everything in master here this morning.
