### ISSUE TITLE
Morph target Normals export issue

### ISSUE THREAD

**Issue by courgeon** [KhronosGroup/glTF-Blender-IO#375]
Hi,
I've noticed a weird behavior when playing with Shape Keys.

When I create a shape, edit it, add a key shape (or several), edit it, then export the gltf file, the base gltf mesh normals data will be those of the last edited shape. 
Morph shape normals will be relative to this one.

However, if I select the original shape "Basis", go in edit mode, and recompute normals, then exporting the gltf will generate the expected behavior with correct normals on both the base mesh and morph shapes.

Here is a simple example, a 3*3 grid. Basic shape is flat, first key shape corners are pull up/down

Rendering the normal buffer in my engine : (Left : export before recomputing normal on basis shape, Right, after recomputing)

Morph coefficient at 0%

![basicshape](https://user-images.githubusercontent.com/5329579/34360383-970f648e-ea60-11e7-8f1f-18990e2ffe10.jpg)

Morph coefficient at 100%

![shapekeyapplied](https://user-images.githubusercontent.com/5329579/34360396-c18d0126-ea60-11e7-94de-e3dfe6c2932b.jpg)

M.

**Comment by scurest** [comment]
This is fixed. If we import the KeyShapeTest.gltf from the .zip above we can confirm the base normals are off. Compare to the normals of a .glb exported and reimported from KeyShapeTest.blend using master

 
![iss](https://user-images.githubusercontent.com/11024420/88574527-15aa0080-d008-11ea-804c-1294c7bfdba7.png)
