### ISSUE TITLE
Correct creating morph animation

### ISSUE THREAD

**Issue by ar53n** [KhronosGroup/glTF-Blender-IO#378]
Hello have any guides for creating morph animation in blender because, when i create animation not work.

I get this errors
ANIMATION_SAMPLER_INPUT_ACCESSOR_TOO_FEW_ELEMENTS | Animation sampler output accessor with 'CUBICSPLINE' interpolation must have at least 2 elements. Got 1.

when enable animation checkbox in gltf viewer i not show animated objects. 

attach example model

[j70_2_0.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1928567/j70_2_0.zip)

**Comment by julienduroure** [comment]
Seems every animation is now exported as it should.
Closing
