### ISSUE TITLE
Increased vertex counts when mesh has UVs

### ISSUE THREAD

**Issue by miirak** [KhronosGroup/glTF-Blender-IO#380]
Okay so I have:

![nevtelen](https://user-images.githubusercontent.com/40399607/43142552-fa79ae38-8f58-11e8-9948-fd1d6e71a596.jpg)

vertices.

After export:
![nevtelen2](https://user-images.githubusercontent.com/40399607/43142580-05bb2ace-8f59-11e8-8cad-ed1afb769e6a.jpg)

28k

**Comment by scurest** [comment]
@donmccurdy Can you check if this is fixed?

**Comment by julienduroure** [comment]
I can confirm that when I disabled UV, normals and tangents, I now get 10500 vertices.
Think we can closed this ticket.
Don't hesitate to comment /  reopen if you still think there is an issue
