### ISSUE TITLE
Exporting Action changes bind pose of armature to first frame

### ISSUE THREAD

**Issue by sketchpunk** [KhronosGroup/glTF-Blender-IO#381]
Trying to export a character with a walking cycle. Problem is that when I export with an action that is active, the mesh's armature resting post changes to the first frame of the animation. This is not the desired result. I need the armature to stay at its default rotation/positions so that I can then setup my own bind pose data for my skeleton animator. If I disable the action, then the armature exports correctly but then the action animation doesn't get exported. This makes it very difficult to use the format to make a game.

Here's my test file.
[bendy_v1_0_1b.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1708541/bendy_v1_0_1b.zip)

**Comment by julienduroure** [comment]
This ticket is quite old, can you please retest with a recent blender build (for example with 2.82 beta that you can download here: https://builder.blender.org/download/ ) ?

**Comment by julienduroure** [comment]
Quite a very old ticket, without any answer.
Closing for now. Don't hesitate to comment and reopen it again if you have some news
