### ISSUE TITLE
Hardware decoded texture formats (KHR_texture_transmission/MSFT_texture_dds)

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF-Blender-IO#382]
I'm wondering if there are any plans regarding hardware decoded texture formats (i.e. exporting DXT compressed textures instead of PNGs) in this exporter? This would simplify workflow for engines that can consume these texture formats by eliminating a post-processing step after exporting the model from Blender.

I think the state of these formats in glTF is that the KHR_texture_transmission extension is still a work in progress, but there currently exists the MSFT_texture_dds extension from Microsoft that allows the use of DDS files in glTF.

**Comment by emackey** [comment]
Currently the plan is to wait for KHR_texture_transmission to be finalized.

**Comment by donmccurdy** [comment]
Closing as this is describing two things we can't really do in this addon. 

Support for KTX2 would be great, but would need to go in Blender itself first.
