### ISSUE TITLE
Export Mesh with more than 65535 vertices with Vertices Color Bug

### ISSUE THREAD

**Issue by NicholasLiang** [KhronosGroup/glTF-Blender-IO#384]
[ExportTest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3001747/ExportTest.zip)

I have two models export from Tilt Brush which use the Vertices color. The exportation successful when the vertices count is less than 65536 in one mesh. If the vertices count excess 65536, the exporter will automatically generate another mesh to store the remaining vertices but the "color_0" attribute will not set and generated with the buffer. The "TEXCOORD_1" which is a "VEC2" will generated instead. Here is two gltf file generated with the exporter with and without a mesh separately. Under the "mesh" section:

[ExportedGLTF.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3001762/ExportedGLTF.zip)

for vertices count more than 65535:
`"meshes" : [
        {
            "name" : "East_Van_Showcase_Skytrain_Icing_mesh.000",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2,
                        "TEXCOORD_1" : 3
                    },
                    "indices" : 4,
                    "material" : 0
                },
                {
                    "attributes" : {
                        "POSITION" : 5,
                        "NORMAL" : 6,
                        "TEXCOORD_0" : 7,
                        "TEXCOORD_1" : 8
                    },
                    "indices" : 4,
                    "material" : 0
                },
                {
                    "attributes" : {
                        "POSITION" : 9,
                        "NORMAL" : 10,
                        "TEXCOORD_0" : 11,
                        "TEXCOORD_1" : 12
                    },
                    "indices" : 13,
                    "material" : 0
                }
            ]
        }
    ],`

for vertices count smaller than 65535:
`  "meshes" : [
        {
            "name" : "East_Van_Showcase_Skytrain_Icing_mesh.000",
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2,
                        "COLOR_0" : 3
                    },
                    "indices" : 4,
                    "material" : 0
                }
            ]
        }
    ],`

One of the short term solution is to separate the mesh to make sure the mesh vertices count under 65535 manually.

Thank you!

**Comment by scurest** [comment]
This appears to be fixed in master.
