### ISSUE TITLE
T62936: gltf export with jpeg textures

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#385]
Blender repo issue : https://developer.blender.org/T62936

T62936: gltf export with jpeg textures

With exporting jpeg textures them assigned as png images and dont founds
this is the file (file provided on blender repo)

If i manually change in gltf text file "png" to "jpg" all works fine (file provided on blender repo)

You may test on this site
https://www.creators3d.com/faq
This is my shader setup

Where i can attach ao texture?

https://dev-files.blender.org/file/data/lc5j3sqo5kpw6j3jrqqi/PHID-FILE-mn5pwq3l5bbybwtzwqkq/Screenshot_20190325_214702.jpg

**Comment by UX3D-soares** [comment]
If I understood correctly, the issue was that the images had the wrong mime-type/file suffix referenced in the gltf-file. I wasn't able to reproduce the error with the zip-files attached. Any chance of seeing the actual .blend-file?

**Comment by julienduroure** [comment]
Can you please ask directly on blender issue tracker, because the user will probably not read it here

**Comment by UX3D-soares** [comment]
The .blend-file can be downloaded here: http://pasteall.org/blend/index.php?id=51463

**Comment by julienduroure** [comment]
I closed the report, because everything works fine with official builds, the user has issue only when he compiles from sources. So this is a building issue, not a glTF bug
