### ISSUE TITLE
Wrong link in README of previous repository

### ISSUE THREAD

**Issue by chardetm** [KhronosGroup/glTF-Blender-IO#388]
I hope this is okay to mention this here, I was on the old repository ([glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter)), and the link supposed to point to this new repository actually points to the old one. I tried to make a pull request there but I can't as the project is archived. It's easy to find the new one with a Google search but I thought it was worth fixing, so that no-one gets confused.

**Comment by donmccurdy** [comment]
Oops thanks, yep that's confusing. I'll fix it.

**Comment by donmccurdy** [comment]
Fixed, thanks! :)
