### ISSUE TITLE
Some models from sketchfab are imported with wrong shader nodes

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#389]
Hi 
For some models like this one from sketchfab : 

https://skfb.ly/6IRWH 

I get this shader node after importing:
 
![Screenshot 2019-03-28 12:23:58](https://user-images.githubusercontent.com/5787647/55140231-2b2dc280-5155-11e9-9bb5-3128bda989ec.png)

As you see base color is mapped to Emission shader and there is a Transparent BSDF instead of PrincipledBSDF. 

And if I export and reimport it I will get this result
![Screenshot 2019-03-28 12:24:37](https://user-images.githubusercontent.com/5787647/55140491-db033000-5155-11e9-867a-a2ec4c1eda70.png)

**Comment by Ali-RS** [comment]
Note, when I import it with this add-on : https://github.com/sketchfab/glTF-Blender-IO/releases/tag/1.0.2 
it imports fine.

**Comment by julienduroure** [comment]
All 3 materials have unlit material extension, so import is fine for me.
Sketchfab importer is a fork of our addon, but fork was done before I implement unlit material here.

Seems that exporter part don't know this node configuration for shadeless materials, so export don't export as unlit materials

**Comment by Ali-RS** [comment]
Not sure if I am understanding it right. So are you saying this shader node setup which is created by importer is correct ? 
https://user-images.githubusercontent.com/5787647/55140231-2b2dc280-5155-11e9-9bb5-3128bda989ec.png   

Can you please share an screenshot from how it looks like for you ? 

I do not know about this unlit material extension, but the game engine I am using does not support this.  So is there an option to disable this extension ?

btw, I am using blender 2.79

**Comment by julienduroure** [comment]
Here is screenshot on 2.79:

![Capture du 2019-03-31 15-47-16](https://user-images.githubusercontent.com/1696020/55289870-58d07100-53cc-11e9-83e3-ae97a8057b53.png)

**Comment by julienduroure** [comment]
With information I have, I can't see any bug.
Don't hesitate to comment if you have new data to provide
