### ISSUE TITLE
Blender 2.8 Multiple Animations Fail in Export

### ISSUE THREAD

**Issue by EricEisaman** [KhronosGroup/glTF-Blender-IO#391]
Errors:
![errors](https://user-images.githubusercontent.com/6116865/55197350-a9578c80-5188-11e9-8ef8-25227714ffaa.png)
Result:
![deformed](https://user-images.githubusercontent.com/6116865/55197157-1880b100-5188-11e9-94bc-d6ecf8caf171.gif)
Blender Windows:
![blender_windows](https://user-images.githubusercontent.com/6116865/55197221-4a921300-5188-11e9-848b-d67e21ec4570.png)
Blender Scene Graph:
![blender_scene](https://user-images.githubusercontent.com/6116865/55197231-5087f400-5188-11e9-9fcb-5916ffad7ff2.png)

The same workflow works well on Blender 2.79 as documented [here](https://docs.google.com/presentation/d/e/2PACX-1vQgPW0diyBC1wp2fSjbmqXyl1I9DHqoRtr9K0YN3WgkZ29A-wSxRUThwfiMqzpcwqLiR3n6utDT3OrX/pub?start=false&loop=false&delayms=60000&slide=id.p).

**Comment by donmccurdy** [comment]
@EricEisaman if you can still reproduce this issue, could you share an example `.blend`?

**Comment by Ukwuani** [comment]
Multiple animation Export fails with a traceback error


![Screenshot from 2019-06-23 06-58-18](https://user-images.githubusercontent.com/25370051/59973644-5e3bf280-959a-11e9-93d6-5246f7214e3d.png)


This is the .blend file 
[charlesgltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3317640/charlesgltf.zip)

**Comment by julienduroure** [comment]
@Ukwuani Seems something went wrong when you uploaded the file, because I can download it. Can you please try again?
Thanks

**Comment by Ukwuani** [comment]
@julienduroure here [Charles.zip](https://github.com/Ukwuani/CharlesAnim/blob/master/charlesgltf.zip)

**Comment by julienduroure** [comment]
@Ukwuani 
Your animations have lots and lots and lots of invalid fcurves (on bone you deleted ?)
And you also have some fcurve with troncated name, like in the following screenshot:
![image](https://user-images.githubusercontent.com/1696020/59979591-16dd5280-95ea-11e9-9a5b-6820674c7f38.png)

I will add some checks to avoid traceback

**Comment by julienduroure** [comment]
Seems issue is now solved, I can export correctly
