### ISSUE TITLE
Material Blend Mode not exported in blender 2.79

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#392]
Setting blend mode in material tab in blender 2.79 is not exported. 
![Screenshot 2019-03-29 12:31:22](https://user-images.githubusercontent.com/5787647/55218084-ac9d5780-521e-11e9-92bc-97093190afdf.png)

I also tested with blender 2.8 and it works fine in 2.8 and I can see these two parameters added in exported gltf file: 

```
"alphaCutoff" : 0.5,
"alphaMode" : "MASK",
```

**Comment by Ali-RS** [comment]
Will appreciate if someone can apply a patch fix for this :)

**Comment by julienduroure** [comment]
Note that glTF support on 2.79 will end after 2.82, and no effort is currently done to fix 2.79 specific issues.
So I will close this ticket after 2.82 release, if nobody propose a PR until that.

**Comment by julienduroure** [comment]
We removed 2.79 support, so closing this ticket
