### ISSUE TITLE
Mapping pbr Materials to "gltf metallic Roughness" nodes

### ISSUE THREAD

**Issue by Kaesebrot84** [KhronosGroup/glTF-Blender-IO#394]
Hi, according to the theory of PBR materials in [this tutorial](https://learnopengl.com/PBR/Theory), for a single material I need following texture maps:

- Albedo
- Normal
- Metallic
- Roughness
- AO (ambient occlusion)

I am creating my materials using the **gltf Metallic Roughness** node. So I wonder how to map my textures (see list above) to the node correctly. So far I am doing the following:

- Albedo &rarr; `BaseColor`
- Normal &rarr; `Normal`
- Metallic &rarr; `MetallicRoughness`
- Roughness &rarr; `RoughnessFactor`
- AO &rarr; `Occlusion` 

Here is what it looks like in the Node Editor:

![gltf metallic Roughness](https://user-images.githubusercontent.com/13865115/55288628-890f1400-53ba-11e9-945d-1f1a82024630.png)

And this is what the exported material looks like:

```json
        {
            "emissiveFactor" : [
                0,
                0,
                0
            ],
            "name" : "Material.002",
            "normalTexture" : {
                "index" : 0,
                "texCoord" : 0
            },
            "occlusionTexture" : {
                "index" : 1,
                "texCoord" : 0
            },
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    1,
                    1,
                    1,
                    1
                ],
                "baseColorTexture" : {
                    "extensions" : {
                        "KHR_texture_transform" : {
                            "scale" : [
                                5,
                                5
                            ]
                        }
                    },
                    "index" : 2,
                    "texCoord" : 0
                },
                "metallicFactor" : 1,
                "metallicRoughnessTexture" : {
                    "extensions" : {
                        "KHR_texture_transform" : {
                            "scale" : [
                                5,
                                5
                            ]
                        }
                    },
                    "index" : 3,
                    "texCoord" : 0
                }
            }
        }
```

The problem here is that the exported material does not contain/reference the Roughness texture. When exporting gltf with separate textures, the Roughness texture is also not referenced under the `images` array.

How do I correctly map my PBR Textures to the **gltf Metallic Roughness** node correctly?

**Comment by julienduroure** [comment]
Can you please indicate what is the version of Blender, and what is the version of the addon you are using?
The glTF metallic Roughness node is not used in this version of the addon.
Check documentation here: https://docs.blender.org/manual/en/dev/addons/io_gltf2.html

**Comment by Kaesebrot84** [comment]
@julienduroure I am using `Blender 2.79 b`. The `Import-Export: gltf 2.0 format`'s Version is `0.0.1`

**Comment by UX3D-becher** [comment]
Principled BSDF is the way to go  :)
Look at issue #123 for the discussion about future support for ambient occlusion
