### ISSUE TITLE
Problem when exporting animated model. It seems like armature bones axis are changed.

### ISSUE THREAD

**Issue by cognatron** [KhronosGroup/glTF-Blender-IO#399]
Hi, 
I'm can't export this model with animations attached because the armature bones seems to be exported with wrong axis. It seems that the problem is related to the "children" bones and not with the "parent" base-bone.

*Model exported without skinning:*

![Exported model without skinning](https://user-images.githubusercontent.com/43038761/55341572-47936d00-547d-11e9-855c-936cb08d68d2.jpg)

*Model exported with skinning:*

![Exported model with skinning](https://user-images.githubusercontent.com/43038761/55341574-482c0380-547d-11e9-84f8-42af7767d9c4.jpg)

This is the animation working properly:
https://skfb.ly/6IrSJ

The .blend file is attached here.
[TrompaBeta-2.8_demo.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3030302/TrompaBeta-2.8_demo.blend.zip)

**Comment by simongloor** [comment]
@cognatron, do your bones look correct when displaying the skeleton? (I suppose you used https://gltf-viewer.donmccurdy.com/ )

I've got the same problem with my model, both when I export it with animations and with only skinning. The bones look fine and animate properly, the skinning is off:
![image](https://user-images.githubusercontent.com/43432178/55384611-749e5900-552b-11e9-8786-9a1fd89bf168.png)

(The model should work as it is fully implemented in my game, using the fbx-export)

**Comment by simongloor** [comment]
I think this might be related to #296
After updating to the latest version the skinning looks fine. Now I only need to fix the animations, but that's a different topic ;)

**Comment by cognatron** [comment]
> I think this might be related to #296
> After updating to the latest version the skinning looks fine. Now I only need to fix the animations, but that's a different topic ;)

Hey, now it works with the new version! 
The only thing I must check now is how to put to work together keyshapes-based animations along with armature actions.

**Comment by cognatron** [comment]
@UX3D-nopper The exported armature-based animations are broken again since the latest exporter updates.

**Comment by cognatron** [comment]
(When using the same .blend file attached.)

**Comment by UX3D-nopper** [comment]
Can you please track down, which commit did break this? If yes, please assign the bug to the person.

**Comment by cognatron** [comment]
@UX3D-nopper I will check that. It looks like the problem is about the "child" bones of the armature.

**Comment by emackey** [comment]
@cognatron Actually could you test the branch in #446 to see if it fixes the issue?

**Comment by emackey** [comment]
Git Bisect names the commit that broke this as fa6e4afffe4c424ded456.

**Comment by cognatron** [comment]
Hey, the export of animation worked well (for this model) at this commit:
e5815d40b040552d8353b5c038f399a73207a2fa

**Comment by donmccurdy** [comment]
What is the issue currently? It looks almost right to me, just rotated 90º or something. Is there more that i've missed?

**Comment by cognatron** [comment]
hi, @donmccurdy . Looks like the head bone is rotated down while the animation is playing. Can you try to export the attached model yourself to see?
![trompa-cap-16jun](https://user-images.githubusercontent.com/43038761/59732405-76211880-9220-11e9-83aa-e9a7e132ef2b.jpg)
![trompa-cap-16jun_2](https://user-images.githubusercontent.com/43038761/59732407-76211880-9220-11e9-9b6e-1c938fea397f.jpg)

**Comment by donmccurdy** [comment]
Ok, yes that is what it looked like when I exported it. Just a bit hard to tell.

**Comment by julienduroure** [comment]
Seems animation does not export at all (animation is exported, but with all same values)

**Comment by julienduroure** [comment]
Seems there is no more orientation issue on this animation export. Closing
