### ISSUE TITLE
Export ignores "Cycles"-curve-modifier

### ISSUE THREAD

**Issue by simongloor** [KhronosGroup/glTF-Blender-IO#400]
Hi there,

I noticed, that the "Cycles"-modifier in the curve editor of Blender is ignored when exporting. Upon further investigation, it seems that it also leads to wrong results.

#### Modifier
![Modifier](https://user-images.githubusercontent.com/43432178/55388504-ba5f1f80-5533-11e9-895d-6f62f800cc3a.JPG)

#### The animation in Blender
![ExpectedResult](https://user-images.githubusercontent.com/43432178/55388554-c8ad3b80-5533-11e9-820a-8e7dd4de6a2c.gif)

#### The animation in [gltf-viewer](https://gltf-viewer.donmccurdy.com/)
![ActualResult](https://user-images.githubusercontent.com/43432178/55388623-e5497380-5533-11e9-8eb4-d13ba39b77a5.gif)

#### Test data for reproduction
[BrokenCycle.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3033035/BrokenCycle.zip)

**Comment by donmccurdy** [comment]
Does enabling `Apply Modifiers` and `Always Sample Animations` in the export settings give you better results here?

**Comment by simongloor** [comment]
Unfortunately not. Here are my settings:
![ExportSettings](https://user-images.githubusercontent.com/43432178/55548616-22e50280-56d4-11e9-8c4a-353f7554437d.jpg)

The problem exists on both, Blender 2.79 and 2.80.

**Comment by simongloor** [comment]
I tested the exporter again with Blender 2.8.1 and it seems to have been resolved.
