### ISSUE TITLE
Custom properties on meshes aren't retained when applying modifiers

### ISSUE THREAD

**Issue by blm768** [KhronosGroup/glTF-Blender-IO#403]
It appears that the exporter doesn't support exporting custom attributes as extras for meshes. Attaching custom properties to the containing object works fine, but properties on the mesh datablock itself seem to be ignored.

Tested in Blender 2.80 beta from a couple of days ago.

I'd be willing to try to scrape together a PR to implement support for exporting custom mesh properties.

**Comment by donmccurdy** [comment]
A PR would be welcome if you could do it, thanks! :)

**Comment by blm768** [comment]
So, as it turns out, mesh extras work just fine by themselves. There only seems to be an issue when "apply modifiers" is turned on. Looks like `to_mesh` drops them. It looks like copying them back over to the generated mesh is easy enough, though.
