### ISSUE TITLE
Exporting rotation doesn't work when at least one scale dimension ist 0

### ISSUE THREAD

**Issue by maccesch** [KhronosGroup/glTF-Blender-IO#409]
This is related to #302 but the core issue hasn't been fixed so I'm opening a new issue.

I need to export an empty object that has scale 0 along the z-axis. This certainly isn't a common use case but I still think it will come up from time to time.

After a little investigation I found that currently translation, rotation, scale is extracted by decomposing the object's matrix:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/d8aa684b87779d43ead627a6463ce2b6d7763f0b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py#L106

This of course doesn't work when some axis is scaled to 0. Blender provides access to it's objects' properties `position`, `rotation_quaternion` and `scale` directly. Is there a specific reason why these aren't used?

The above mentioned function is used in only two places.

The first one is where I suggest we use the object's properties directly (modified by export settings of course):
https://github.com/KhronosGroup/glTF-Blender-IO/blob/b44e4794490f7d526727cf40f2fe20097f961385/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py#L278

and the second one should be left unchanged:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/90b0c1f640c6d1105f9f520d0bf230b3cf8fe87c/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_joints.py#L50

I'm happy to do a pull request. Please let met know.

Thanks.

**Comment by emackey** [comment]
> I'm happy to do a pull request. Please let met know.

Yes please. 😄

**Comment by UX3D-schmithuesen** [comment]
I don't see a reason not to merge your PR, but I was actually not able to reproduce this problem just now. I successfully exported this node on the current master branch:
```
{
    "mesh" : 0,
    "rotation" : [
        0.19306449592113495,
        0.24961179494857788,
        -0.2730344533920288,
        0.9087751507759094
    ],
    "scale" : [
        1,
        0,
        1
    ]
}
```
This should not work, right?

**Comment by UX3D-schmithuesen** [comment]
Okay, the same node gets a different rotation when scale is 0 in two dimensions – I guess, something *is* wrong.
```
{
    "mesh" : 0,
    "rotation" : [
        0,
        0.28867512941360474,
        -0.40824827551841736,
        0.8660253286361694
    ],
    "scale" : [
        1,
        0,
        0
    ]
}
```

**Comment by maccesch** [comment]
I guess it depended on which axis was 0. For us we had issues with the z-axis being 0.

Anyway, thanks for merging.

**Comment by maccesch** [comment]
By the way when importing we have the same issue for the same reason. A matrix decomposition is used there as well. I don't have time unfortunately to fix this too.
