### ISSUE TITLE
T63489: Wrong transparent node setup in GLTF import

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#424]
See Blender issue tracker for info / file / screenshots:
https://developer.blender.org/T63489

**Comment by julienduroure** [comment]
I not agree with the analysis. 
Factor of the mixShader node will do the following : 1 for transparent, 0 for opaque. 
The Add node is used as factor. So if you have an alpha of 0.2, you have to set factor to 0.8. 
The second image is wrong, because add 0.8 and 0.2 --> full transparent because of factor of 1.0

**Comment by nurbs999** [comment]
Hmm, strange. In my threejs scene, where I do the gltf export from, has a almost full transparent object.
![Bildschirmfoto von 2019-04-15 12-06-28](https://user-images.githubusercontent.com/326346/56124532-251e4b00-5f77-11e9-8a00-541770c4b819.png)

**Comment by Zool1987** [comment]
I have the same problem ... And another question on the topic is it possible to use a gradient in texture? Now I only have a blend mode without texture in my shader Principle BSDF...I want to get a glass with a transparency gradient (opaque at the bottom, transparent at the top) With the old shader I did it, but with Principle BSDF does not work = (If you can do this, you can share the node scheme?

**Comment by julienduroure** [comment]
I have to check if we can use transmission value of principled shader instead of mix with transparent node. 
Set as enhancement

**Comment by julienduroure** [comment]
This very recent change in Blender will maybe help us : 
https://developer.blender.org/rB8f71a84496a95528303fbe0bb7c1406060353425

See #462

**Comment by Zool1987** [comment]
It's great that these entrances have appeared, but GLTF exports are not working as expected. Gradient texture with transparency, after export, loses the alpha channel. We are waiting for this fix. 
[alpha_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3178111/alpha_test.zip)
![test](https://user-images.githubusercontent.com/10163448/57704122-fe346100-7669-11e9-9b8b-e382766d72d2.png)
![screen](https://user-images.githubusercontent.com/10163448/57704326-566b6300-766a-11e9-95bb-8b049ff11de9.jpg)

**Comment by julienduroure** [comment]
@Zool1987 These new entrances are not taken into account in this addon yet, so please be patient, we will work on it

**Comment by Zool1987** [comment]
Thank you very much for your work, you are doing a great job!

**Comment by scurest** [comment]
I think the original setup was already correct, but anyway the Alpha socket is used now. Might be able to close this.

![mat12](https://user-images.githubusercontent.com/11024420/75113380-20a0d500-5613-11ea-9c5c-d0f9bb3e2be1.png)
