### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by SteffenDuenner** [KhronosGroup/glTF-Blender-IO#425]
**Describe the bug**
Exported PNGs have their alpha channel deleted on export?!

**To Reproduce**
- Add a grid with UVs
- Assign a principled shader
- Plug a PNG with an alpha channel in base color
- Set blend mode to "Alpha Clip" or whatever
- Export a gltf + bin + textures (just to easily see that the exported PNG has no alpha channel any more. Also works with glb and gltf embedded)
- Import into Blender again (or a viewer of your choice) -> no transparency, the PNG is RGB only

**Expected behavior**
Alpha channel of the PNG controls transparency / opacity

**Version**
 - OS: Linux Mint 19.1 x64
 - Blender Version: Latest own build containing the draco compression and JPG+PNG conversion

**Comment by SteffenDuenner** [comment]
If I reimport the glb / gltf in Blender it sets the blend mode to "Alpha Clip", the only problem is that the alpha channel from the PNG is now gone.

**Comment by julienduroure** [comment]
Can you please provide a glb file generated and the original .blend file ?
Did you test the glb in some external visualisation tool, like https://gltf-viewer.donmccurdy.com ?

**Comment by SteffenDuenner** [comment]
Yes, I always test the files in other viewers (three.j/editor, donmccurdy, babylon sandbox) and none of them shows transparency.

[Transparency_v01.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3072944/Transparency_v01.zip)

Here's the Blender 2.80 file with packed texture and the resulting glb. Exported from the very latest own build of 2.80.

Thanks for having a look :)

**Comment by Zool1987** [comment]
I have the same problem ... And another question on the topic is it possible to use a gradient in texture? Now I only have a blend mode without texture in my shader Principle BSDF...If you can do this, you can share the node scheme?

**Comment by vitorbalbio** [comment]
Hi!
After recent updates the png/alpha export stopped work. I get exactly the same problem as reported above. It's probably caused by this commit: https://github.com/KhronosGroup/glTF-Blender-IO/pull/404

Here's a sample file:
[BugAlpha.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3095041/BugAlpha.zip)

**Comment by julienduroure** [comment]
This very recent change in Blender will maybe help us : 
https://developer.blender.org/rB8f71a84496a95528303fbe0bb7c1406060353425

Cf #462
