### ISSUE TITLE
Texture files get re-encoded

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/glTF-Blender-IO#428]
**Description**
I noticed that upon exporting glTF (at least separate ones) the textures get re-encoded.
This way users have no controll over compression settings and quality.

In case of my demo file, the JPG also increases in size a bit. Since jpegs are lossy, I consider this additional re-encode as quality flaw. Even lossless PNGs might get bigger in size in this step.

I can imagine good reasons for re-encoding (like limiting texture size, make the size a power of two, optimizing PNGs or changing to a better compression), but I think that's not the case here.

**To Reproduce**
Take a look at the provided blend + jpg files and the respective export in the `gltf` subfolder.
The source txt.jpg is not the same as the exported one.

**Expected behavior**
I'd expect the exported files to be precicely the source texture files (in case they are JPEG or PNG files).
If textures get re-encoded, I'd like to have control over the encoding settings (format, quality settings etc.)

**.blend file/ .gltf**
[reencode.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3076461/reencode.zip)

**Version**
 - OS: macOS
 - Blender Version 2.80 beta

**Comment by emackey** [comment]
I think this is a regression, likely introduced here:

https://github.com/KhronosGroup/glTF-Blender-IO/pull/404/files#diff-444226537cdaaa92459dad1cd814237bL162

**Comment by robertlong** [comment]
We've noticed this as well and it has had a big impact on file size. We've wrote up our findings here:

https://github.com/robertlong/GLTFExporterTextureSizes
