### ISSUE TITLE
Any imported GLTF model switches engine to EEVEE

### ISSUE THREAD

**Issue by EtagiBI** [KhronosGroup/glTF-Blender-IO#431]
**Describe the bug**
Any imported GLTF model switches render engine to EEVEE.

**To Reproduce**
1. Open Blender
2. Switch render engine to Cycles
3. Import any GLTF model / scene
4. Check render engine

**Expected behavior**
Render engine shouldn't be switched to EEVEE.

**Version**
 - OS: Windows 10 64-bit
 - Blender Version: 
![image](https://user-images.githubusercontent.com/20855725/56134061-3717e200-5fa7-11e9-8a60-91272b5737aa.png)

**Comment by julienduroure** [comment]
Hello,

This was, at first, something intentional (based on 2.79 where we switch to Cycles), but OK, this is maybe time to enhance that and keep the render engine of user).
Setting this as enhancement, this is something quite easy to implement.

Thanks

**Comment by julienduroure** [comment]
Fixed in 2fbc5ab3d8ef2eeac4968f9bd89123b27f30bb42
