### ISSUE TITLE
Bad Export possibly?

### ISSUE THREAD

**Issue by samanthajo2** [KhronosGroup/glTF-Blender-IO#433]
**Describe the bug**

Exporting these animated models from blender into glTF the animations give the characters wrong scale values. The feet are warped

<img width="277" alt="Screen Shot 2019-04-15 at 20 06 41" src="https://user-images.githubusercontent.com/49654280/56156672-03948200-5fbe-11e9-947a-72d9408d6e49.png">

**To Reproduce**

1. Download [this free 3d characters](https://quaternius.itch.io/lowpoly-animated-animals)
2. Unzip, Load `Pig.blend` into blender and export to gltf
3. Load gltf into three.js, play second animation

See https://jsfiddle.net/samanthajo2/u9q8r7ws/

**Expected behavior**

The feet are not warped

<img width="473" alt="Screen Shot 2019-04-15 at 20 33 43" src="https://user-images.githubusercontent.com/49654280/56156671-03948200-5fbe-11e9-9b92-5940ef8d305d.png">

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.79, 2.80 (2019-03-18)]

**Additional context**

I'm sorry I'm an artist mostly so I don't know if the issue is in the exporter or three.js

**Comment by samanthajo2** [comment]
[Pig.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3081630/Pig.blend.zip)

[gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3081635/gltf.zip)


Here's the blend file if it's helpful and here's the exported files. Maybe someone can try loading them in another gltf supported system to see if it's the exporter or three.js?

**Comment by donmccurdy** [comment]
Same result in https://sandbox.babylonjs.com/ and https://gltf-viewer.donmccurdy.com/, looks like an exporter bug. Thanks for filing!

**Comment by julienduroure** [comment]
Everything seems to be OK now. When exporting, don't forget to enable "Always sample animations" to bake the constraints on your rig.
