### ISSUE TITLE
Custom normals on flat-shaded faces

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#436]
Just creating an issue so we don't forget.

In https://github.com/KhronosGroup/glTF-Blender-IO/pull/414#discussion_r274018041 I noticed a workflow involving bevel with hardened edges that applied custom normals on top of flat-shaded faces (as opposed to customized smooth-shaded faces).  In https://github.com/KhronosGroup/glTF-Blender-IO/pull/414#discussion_r274306611, @pjoe suggested changing the order of checks in the nested `if` statements.

**Comment by pjoe** [comment]
Will try taking a look after Easter 🥚
