### ISSUE TITLE
Rotation of nodes gets set to quaternions even though rotation mode is euler xyz

### ISSUE THREAD

**Issue by leon** [KhronosGroup/glTF-Blender-IO#438]
**Describe the bug**
version: 2.80 (sub 57), branch: blender2.7, commit date: 2019-04-16 20:13, hash: 5d8030b8f3cf, type: Release
build date: 2019-04-17, 01:25:00
platform: Darwin

Rotation of nodes gets set to quaternions even though rotation mode is euler xyz

**To Reproduce**
Open the default blender scene.
export it to gltf

the `nodes` will be

```json
{
"nodes" : [
        {
            "mesh" : 0,
            "name" : "Cube"
        },
        {
            "name" : "Light",
            "rotation" : [
                0.16907575726509094,
                0.7558803558349609,
                -0.27217137813568115,
                0.570947527885437
            ],
            "translation" : [
                4.076245307922363,
                5.903861999511719,
                -1.0054539442062378
            ]
        },
        {
            "name" : "Camera",
            "rotation" : [
                0.483536034822464,
                0.33687159419059753,
                -0.20870360732078552,
                0.7804827094078064
            ],
            "translation" : [
                7.358891487121582,
                4.958309173583984,
                6.925790786743164
            ]
        }
    ]
}
```

**Expected behavior**
that the node rotations would be in format `[0, 0, 0]` instead of [0,0,0,0] when the rotation mode of the node is set to euler xyz

**Comment by julienduroure** [comment]
Hello,

glTF specification supports only quaternion rotation, so rotation can't be written as euler, and must be converted to quaternion to be exported.

Julien

**Comment by leon** [comment]
I'm sorry, my bad.
