### ISSUE TITLE
Exporting does not bake armature constraints into animation

### ISSUE THREAD

**Issue by BlenderSleuth** [KhronosGroup/glTF-Blender-IO#439]
**Describe the bug**
I have been trying to export a basic rigged character with a single stashed walk cycle, animated with IK constraints on the feet. However, even using the "Bake skinning constraints" option, the animation is exported without constraints applied.

**To Reproduce**
1. Download .blend:
[TestPlayer.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3093342/TestPlayer.zip)
2. Export with these options:
![Config2](https://user-images.githubusercontent.com/11659668/56345792-f10b8a00-6203-11e9-82cc-e2d31c3b5807.PNG)
3. Animation not exported correctly
[TestPlayer_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3093311/TestPlayer_glb.zip)

**Expected behavior**
The exported file should contain animations with properly baked constraints

**Screenshots**
![WalkAnimBlender](https://user-images.githubusercontent.com/11659668/56360865-39896e80-6229-11e9-9ec5-6f55d871c14e.png)
![NoWalkAnim](https://user-images.githubusercontent.com/11659668/56346308-2664a780-6205-11e9-9889-67e7fe5be74a.PNG)

**Version**
 - OS: Windows 10
 - Blender Version: 2.80.0 git.860a9f979d60

**Additional context**
Exporting with "Always sample animations" exports with a blank animation
[TestPlayer_sample_anims_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3093324/TestPlayer_sample_anims_glb.zip)

I can make the export work using the Pose->Animation->Bake Action with "Visual Keying" and "Clear Constraints" options, but that requires duplicating the mesh and armature for each export to preserve constraints.

**Comment by julienduroure** [comment]
Probably link to #461

**Comment by BlenderSleuth** [comment]
For the simplest possible blend file that doesn't export correctly with any options (always sample and bake skinning constraints):
[basic.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3220321/basic.zip)
The main thing is the IK constraint not being used

**Comment by BlenderSleuth** [comment]
Ok the latest change #479 fixes the IK constraint issue, so now it's just the multiple actions NLA issue #461

**Comment by LorenzWieseke** [comment]
Still can't manage to export IK Contraint, animation showing up but doesn't do anything.

Exporter on version 1.2.75, Blender 2.83 (but tried other version as well)

[Waferarm_Inside.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4688262/Waferarm_Inside.zip)
