### ISSUE TITLE
Blender import crash due to spelling error

### ISSUE THREAD

**Issue by Applemoose** [KhronosGroup/glTF-Blender-IO#44]
The glTF import is throwing an error due to a spelling error in the file "/glTF-Blender-IO/addons/io_scene_gltf2/blender/imp/gltf2_blender_gltf.py" row 106 "mettalic_factor" instead of "metallic_factor".

**Comment by julienduroure** [comment]
Thanks for the report, this is now fixed in 2b1fa0f0424f85dae8c39f1be95e1d407db95686
