### ISSUE TITLE
Import multiple glb files at a time

### ISSUE THREAD

**Issue by itchyballsack** [KhronosGroup/glTF-Blender-IO#441]
I think the ability to import many files at a time would be really useful

**Comment by julienduroure** [comment]
This is not planned for now, others Blender importers don't allow it, I think we should saty aligned with other ones.
Keeping this issue open as enhancement, because I myself have a script that call official addon to import multiple files at a time. I will maybe publish it, but on my personnal repo, not on official one, and not shipped by default. Still need to convert this script to an addon if possible.

**Comment by itchyballsack** [comment]
> This is not planned for now, others Blender importers don't allow it, I think we should saty aligned with other ones.
> Keeping this issue open as enhancement, because I myself have a script that call official addon to import multiple files at a time. I will maybe publish it, but on my personnal repo, not on official one, and not shipped by default. Still need to convert this script to an addon if possible.

I would be very interested in that script, I'll keep an eye out. Thank you

**Comment by emackey** [comment]
Note that [roundtrip_gltf.py#L29](https://github.com/KhronosGroup/glTF-Blender-IO/blob/4cf8a05f0712af26fee5046dcd8d96bd607256e1/tests/roundtrip_gltf.py#L29) shows how to import a glTF file from inside a Python script.  You could wrap this in a `for` statement or similar.

**Comment by itchyballsack** [comment]
I have absolutely zero programming knowledge but I'll give it a go, thanks!

**Comment by julienduroure** [comment]
Seems FBX allows multiple file import now. Cf https://developer.blender.org/rBAb57772a8831e1f618d37ac4a3386c070dbc425b6

So, I will added it to glTF import too. Planned for 2.82

**Comment by aidelank** [comment]
Any news in this importer? I'm VERY needing it

**Comment by julienduroure** [comment]
Hello,
Note sure to understand your request, as this feature is in Blender since more than 4 years.
