### ISSUE TITLE
A Model That Can Be Exported Only While Draco Is Disabled

### ISSUE THREAD

**Issue by rainclaws** [KhronosGroup/glTF-Blender-IO#445]
**Describe the bug**
I created a file that works fine except that it can't be exported with draco enabled.

**To Reproduce**
- Export multiple, arbitrary models to gltf.
- Merge these files in the same way blender exports multiple meshes. Except for the indices. Assign each mesh its own indices bufferview. This is practically the equivalent of merging files by copy pasting object properties.
- Import it back to blender.
- Export it in various ways. Fbx, gltf, etc. Observe that it works fine. The produced files are compatible with other programs. They can be imported back to blender.
- Try to export it to gltf with draco enabled. Watch it fail with an error about indices.

**Expected behavior**
Since it can be exported as gltf without draco, it should able to be exported with draco.

**Files**

[out-take1.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3103962/out-take1.zip)

out-take1.gltf & out-take1.bin

**Version**
 - OS: Linux
 - Blender v2.80 Beta, 2.7 branch, hash 797539e76ccf, 2019-04-21 20:30

**Comment by UX3D-eckerlein** [comment]
Same issue here #440.

**Comment by joeybarrus** [comment]
This issue appears to be back. Model fails to export when Draco is enabled.

**Version:**
2.92.0 (2.92.0 2021-02-25). 
Mac OSX 11.2.2

**To Reproduce:**



- Export model to GLTF 2.0 with Draco compression enabled.
- Model exports fine without Draco.

Error:

![Screen Shot 2021-03-02 at 2 45 14 PM](https://user-images.githubusercontent.com/4803658/109725416-f5c25880-7b65-11eb-8336-d49ad33559d3.png)

Files:

[hamburger.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6072256/hamburger.blend.zip)

[hamburger.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6072281/hamburger.glb.zip)

**Comment by UX3D-eckerlein** [comment]
I can confirm the bug and will take a look at the exporter

**Comment by UX3D-eckerlein** [comment]
Fixed by #1352
