### ISSUE TITLE
Wrong position of Child object

### ISSUE THREAD

**Issue by cstfan** [KhronosGroup/glTF-Blender-IO#447]
**Describe the bug**
When I parent an object, this child object has a wrong position.

**To Reproduce**
On the version of today's blender
1. Create a first simple object (cube) and move it
2. Create a second simple object and move it
3. Selects both
4. CTRL + p (Set to Parent : Keep Transform)
5. Export gltf
-> The child object (blue cube) does not have the same position when I view the glft file

**Expected behavior**
The child object should have the same position between blender and glft file

**Screenshots**
![image](https://user-images.githubusercontent.com/33685211/56653731-9bfdc700-668e-11e9-8594-19eb77c783cc.png)

**.blend file/ .gltf**
[Blend_gltf_files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3112040/Blend_gltf_files.zip)

**Version**
 - OS: Windows 10 64 bits
 - Blender Version 2.80 (2019-04-24)]

**Comment by Cyp** [comment]
This should be fixed in dadde634dd117df5c1bc0c19978291f30a3f8bd1 of #446.

**Comment by cstfan** [comment]
Great

**Comment by julienduroure** [comment]
#446 is now merge, this should be fixed.
Don't hesitate to comment if there is still an issue

**Comment by cstfan** [comment]
Wonderful it works, I'm going to test with an important scene, thanks for your great work
