### ISSUE TITLE
Additional Support for bpy.types.ShaderNodeGroup

### ISSUE THREAD

**Issue by Menithal** [KhronosGroup/glTF-Blender-IO#449]
`bpy.types.ShaderNodeGroup` are a really handy way to creating groups of preset shader groups for any given scene in Blender. As of the moment however the GLTF Exporter seems to only check for a node group that has the name "gltf Metallic Roughness" which apparently is deprecated `gltf2_blender_get.get_socket_or_texture_slot_old`. Instead it should support what ever node group a user creates (to the extent to gltf2 spec)

**Describe the solution you'd like**
Generate a wrapper from a group input to the group output using the same methods used as in export.

Utilize the wrapper then to bind the textures to gltf2 spec.

**Describe alternatives you've considered**
Use The shader groups input socket names as binding instead of jumping into checking how the shader group is built.

 However, the naming schema should then be documented for other addon or node group creators. And this puts alot of trust into the addon developers into meeting the spec.

**Additional context**
I am developing a addon toolset, that creates a [shader group](https://github.com/Menithal/Blender-Hifi-Addon/blob/blender-2.8/hifi_tools/utils/materials.py#L216) in any scene on load to make it easier for new blender users to bind classical values to materials (Diffuse, Roughness, Alpha, Metallic, Emission) all in a single bundle to match the shading in a Game Engine (for one to one previews in Blender).

This allows them to get eased in, instead of having directly jump into the Shader Editor and start creating more and more Shaders and combing them to get basic functionality.

This issue mostly to start a conversation on the subject, and to see if there are plans of it:
Will submit an exploratory PR later down the line, after I understand the gltf exporter a bit more and how it ticks.

**Comment by donmccurdy** [comment]
This exporter primarily expects a Principled BSDF node, which aligns very well with the glTF material model. See https://docs.blender.org/manual/en/dev/addons/io_gltf2.html.

For properties that aren't supported by Principled BSDF, we've allowed custom nodes named `glTF Metallic Roughness` in the past, which we've recently renamed to `glTF Settings`. I think it is reasonable to require that the node group be named something specific to indicate the intent.

**Comment by Menithal** [comment]
Principled BSDF does not support:
- Alpha / Opacity
- Emissive

Most common ShaderGroup setup would be PFSDF + Alpha Shader with a mixer. This will especially come very apparent when Opacity support to the gltf exporter is implemented. 

To allow everything to atleast preview correctly in blender, [looks like this](https://norteclabs.com/img/examples/AlphaEmissiveDiffuseprincipled.PNG)

That sort of entire setup is absolutely a just a pain to keep on re-setuping per object instead of a simple [One GroupNode](http://norteclabs.com/img/examples/NodeGrou.PNG) that you can use across the Blender Scene in different objects. Alternatively you can always just duplicate the materials, but thats still just copying the setup instead of using a feature.


In anycase, if looking at intent, why instead of using the Group Name to check intent, look at the input nodes for the group node instead? document a naming schema that matches gltf2 definitions, and use that as well.

**Comment by emackey** [comment]
@Menithal I can't see the images you've uploaded, can you drag-and-drop them on the issue here?

Also, as @donmccurdy mentioned, support for node groups is included here.  In spite of the function named `_old`, this functionality isn't going away.  I think the group name is important to check, because multiple node groups can have similarly-named inputs with different functionality.  We allow both the name `glTF Metallic Roughness` and `glTF Settings` now, and I recommend the latter.

**Another option**

One other option I've been thinking about lately, but I don't know how people would feel about this:  It might be possible to add Blender commands to apply glTF-compatible material modifications on demand.  There could potentially be new commands like `glTF: Add Metallic/Roughness` that would wire up the Separate RGB node, and `glTF: Add Emissive Map` that would wire in the Emissive BSDF node with a blank Image Texture node and an Add Shader.  These would modify the currently active material to add support for the requested map to export to glTF.  Thoughts on this (from anyone)?

**Comment by Menithal** [comment]
@emackey  Fixed the Links they are just stuff similar node setup to the ones shown in the blender documentation:

I cannot seem to find any check for `gltf Settings` in Group name currently being looked for in the current master or in the current release of the Blender 2.8 (and the ´gltf2-blender-io` on there) could I get a pointer on where this is done, or is that just "upcoming plans"

I am honestly more into the Node Group approach for general purpose. 

> because multiple node groups can have similarly-named inputs with different functionality.

What if instead you look if the name prefix or postfix containing "gltf" in one format or another instead (such as `Shader Group (gltf)`? and then bind the variable names. Otherwise it feels redundant to have a single empty group named `gltf Settings` that accepts the texture inputs but is just a stub. That just feels like duplication of work.  

Sure It can be done, but _I just love hearing complaints from end users saying something doesn't work because they **forgot a step**_. It can automated to bind on-save though, but at best it still is clunky and would need to remind end users to save prior to export.

-----
 
While adding new commands is prospective, the main issue arises from that is the amount of edge cases you'd have to look into when modifying user's materials. Are you sure you'd want to go that route though? 

You'd also have to take account Add Alpha for the the Blender preview, even if, from what I understand, the alpha is from the Diffuse Texture alpha by default.

-----

Probably more context: Having tools to add material nodes, _doesn't solve the context of the problem:_
A need for a ShaderGroup support for addon developers (like me) who create ShaderGroups in their addons to make pipelines easier for the end users or make the shaders match what ever spec they have elsewhere.

Otherwise add on devs would just end up duplicating code and porting it over to modify it, and that's messy and basically a fork, which this early, should not yet be done..

**Comment by emackey** [comment]
The check for group name happens here:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/9a52b6692f8b52aef115cfa06f0822911b766c40/addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py#L101

with the actual `glTF Settings` name itself defined here:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/9a52b6692f8b52aef115cfa06f0822911b766c40/addons/io_scene_gltf2/blender/com/gltf2_blender_material_helpers.py#L61

This code is only about 2 weeks old at this point, you need a recent build to get it.

The node itself doesn't need to be a stub.  The inside of the node can plug this all into any Blender nodes you like, and output to a material node on the other side.  Some examples of this can be found in the [pbr_node folder](https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/tests/pbr_node), which is part of the test suite here.

**Comment by emackey** [comment]
Here's a screenshot of [pbr_node](https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/tests/pbr_node) with some stuff plugged in:

![pbr_node_sample](https://user-images.githubusercontent.com/1235080/56994897-59485d00-6b6e-11e9-9e57-bb3dede1ad1c.png)

**Comment by donmccurdy** [comment]
> Principled BSDF does not support:
> 
> - Alpha / Opacity
> - Emissive

Our first priority should be to support these features through methods native to Blender 2.8. For example, we can export emissives with an *Emission* node now, and could get alpha from a *Transparent BSDF* node in the future. In general, this exporter should not be training Blender users to do weird things unless absolutely necessary. For baked AO, unfortunately, a hack was necessary.

> It might be possible to add Blender commands to apply glTF-compatible material modifications on demand. There could potentially be new commands like glTF: Add Metallic/Roughness that would wire up the Separate RGB node, and glTF: Add Emissive Map that would wire in the Emissive BSDF node with a blank Image Texture node and an Add Shader.

Any commands we add are enabled by default in Blender 2.8, and we'd want to be pretty conservative about adding that sort of thing... this could be done as a separate addon, I guess, or enabled with an opt-in "Enable shortcuts" setting. Not sure if default addons can have opt-in settings?

**Comment by Menithal** [comment]
> The node itself doesn't need to be a stub. The inside of the node can plug this all into any Blender nodes you like, and output to a material node on the other side.

Thanks, I am gonna look into tweaking the detection slightly. Specifically https://github.com/KhronosGroup/glTF-Blender-IO/blob/f12b8205284d13ebcd294abc525ff54d8d4c1663/addons/io_scene_gltf2/blender/exp/gltf2_blender_get.py#L101

I was thinking that may be the name detection instead should just be looking for "gltf" instead of 'glTF Metallic Roughness'. it is unlikely for a user to have multiple shader nodes with gltf in them. will submit a PR for it once I get going.

That way blender users can use other names than just "gLTF Metallic Roughness" or "gLTF Settings" for bindings, and add-on devs create ease-of-access shader groups like:

- Simplified gLTF
- Advanced gLTF,
- CustomName gltf.

**Comment by donmccurdy** [comment]
Principled BSDF material has since added both Alpha and Emission. Closing this issue.
