### ISSUE TITLE
Exporting multiple actions corrupts them

### ISSUE THREAD

**Issue by SirSilverCharles** [KhronosGroup/glTF-Blender-IO#451]
I have a rig and I stash various actions(animations), I export the glTF and I import it in a blank file, I select the rig and I select one action in the action editor, the action doesn't look right instead it looks blended with something else.

How it should look:
![image](https://user-images.githubusercontent.com/17120210/56934718-bb438c80-6ab2-11e9-9c6b-411a83a84051.png)

How it looks, is sitting as if it ignored some bones position/rotation keyframe, (same with other actions):
![image](https://user-images.githubusercontent.com/17120210/56934730-d0202000-6ab2-11e9-8841-3756978ccff0.png)

I tested many variations: "Always Sample Animations" option as well as other options, adding the actions in new Nla tracks instead of stashing them, I imported in three.js(with same result, so probably the exporter is the problem), I keyframed all the bones at the start of the action, I made sure that the active action is empty before exporting, turning on or off the "Do channels contribute to result" in the Nla track, adding all the actions in a single track instead of separated ones, etc.
If I export only one action it looks correct.

[characterWoodsmall A2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3129600/characterWoodsmall.A2.zip)
Here is the file, just open it export and the in a new blender import it, select the rig and select an action from the "dope sheet"->"action editor"->"browse action to be linked".

This was in Windows 7, and blender-2.80.0-git.a57fec986d2d-windows64

Thanks.

**Comment by julienduroure** [comment]
Multiple checks/issues here :

* Open glb on https://gltf-viewer.donmccurdy.com/ Everything seems to be OK, except Neutral pose --> Exporter issue

* Importer issue: lots of mesh without any armature modifier: Link to #331 ?

**Comment by SirSilverCharles** [comment]
Thanks. Is not only the neutral pose, all the other poses have problems but are less obvious, is clear in the position of the hand mostly.

**Comment by SirSilverCharles** [comment]
I found a workaround: duplicate(alt+D) the rig for each action and only use one action in each rig, the actions export correctly that way.

**Comment by ERS-EIT** [comment]
I have kind of the same problem. If my model has more than one Animation and I do not sample every keyframe, the byte array in the glTF file seems to have intermediate zeroes.
So if I take a look at my keyframes (for a given joint) there are thrice as much scaling vectors in the buffer as I have timestamps. The "thrice" part might be variable. Maybe it is because I have three animations in that particular model.

However, if I enable "sample each frame" on export, I get the right keyframe vectors for scaling, rotation and translation.

**Comment by julienduroure** [comment]
@ERS-EIT Hello,
Can you please share your .blend file?

**Comment by ERS-EIT** [comment]
@julienduroure Sorry I totally messed this one up myself. Nothing's wrong on your side. Please just ignore my comment. Sorry for the trouble I caused.

**Comment by julienduroure** [comment]
NLA problem probably linked to #461

**Comment by oxplay2** [comment]
i just now struggle with this, i will try update exporter to new version to see if it was fixed.

for me it was always sampling "default dope sheet NLA track" only, so every action i had was same animation as "default dope sheet NLA track". if i had no animation in "default dope sheet NLA track", then all animations were empty, doing nothing.

**Comment by julienduroure** [comment]
@oxplay2 What you are describing is same issue as #461 
We are currently testing the fix (#507), so this is not yet in master. Should be done in following days / weeks.

**Comment by oxplay2** [comment]
oh, thanks :) will wait. hope it will be quick.
