### ISSUE TITLE
GLTF exporter is missing option to export primitives with UINT32 indices

### ISSUE THREAD

**Issue by MiikaH** [KhronosGroup/glTF-Blender-IO#457]
Old Blender 2.79 exported had drop menu to select whether you wanted to use unsigned short or unsigned integer indices. 

glTF-Blender-IO exporter doesn't have such option and always splits primitives to `65535` index chunks. This can be problematic because it adds additional overhead for the render engine.

It seems like exporter code is ready to handle full integer indices, but is just lacking an checkbox or drop menu to select which `max_index` to use.

**Comment by emackey** [comment]
I noticed the capability to write true 32-bit seems to be missing, not sure what happened there.

The UI combobox was removed intentionally.  We can't expect all artists to learn enough programming to know about things like integer sizes, and it's wrong to ask them on the UI.

The 16-bit splitting behavior is incorrect, though.  I think that's a holdover from when that 16-bit option on the UI used to be available.  We should probably get rid of the splitting behavior, and always upgrade to 32-bit when there are enough vertices in a primitive to warrant it.

**Comment by lexaknyazev** [comment]
> The UI combobox was removed intentionally...

To keep the functionality without confusing artists, we can make an off-by-default checkbox named like "Split meshes exceeding 65K vertices".

**Comment by SurlyBird** [comment]
Found this while looking at another bug about large meshes getting split. Any ETA on a fix?

**Comment by scurest** [comment]
The exporter no longer splits primitives, so I think this can be closed.
