### ISSUE TITLE
custom split normals data not exported

### ISSUE THREAD

**Issue by Lexpartizan** [KhronosGroup/glTF-Blender-IO#458]
I smoothing mesh with normal editor blend4web.
In blender this mesh look OK.
In exported obj this mesh look OK.
In exported gltf this looks,like normals not editing.
Blend and glb files attached.
Sorry for my english.

[normals not exported.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3170453/normals.not.exported.zip)

**Comment by Cyp** [comment]
Is this a duplicate of #436?

**Comment by Lexpartizan** [comment]
Maybe. My english bad. I Use smooth shading, not flat.

**Comment by donmccurdy** [comment]
Fixed by https://github.com/Cyp/glTF-Blender-IO/commit/c9e33f3c8838cc9c6f6cf51c65e28b5ee073e4f0
