### ISSUE TITLE
KHR_lights_punctual contains too many lights

### ISSUE THREAD

**Issue by infobeisel** [KhronosGroup/glTF-Blender-IO#459]
**Describe the bug**
the exporter seems to write too many entries into the "extensions/KHR_lights_punctual/lights" array. In my case it write 10 entries, although its a scene with one point light and nothing else:
`"extensions" : {
        "KHR_lights_punctual" : {
            "lights" : [
                {
                    "color" : [
                        1,
                        1,
                        1
                    ],
                    "intensity" : 10,
                    "type" : "point",
                    "name" : "Light"
                },
                {
                    "color" : [
                        1,
                        1,
                        1
                    ],
                    "intensity" : 10,
                    "type" : "point",
                    "name" : "Point"
                },
                {
                    "color" : [
                        1,
                        1,
                        1
                    ],
                    "intensity" : 10,
                    "type" : "point",
                    "name" : "Point.001"
                },
                {
                    "color" : [
                        1,
                        1,
                        1
                    ],
                    "intensity" : 100,
                    "type" : "point",
                    "name" : "Light"
                },
                {
                    "color" : [
                        1,
                        0,
                        0.008219769224524498
                    ],
                    "intensity" : 50,
                    "type" : "point",
                    "name" : "Point.001"
                },
                {
                    "color" : [
                        0.007947047241032124,
                        0.007947047241032124,
                        0.007947047241032124
                    ],
                    "intensity" : 100,
                    "type" : "point",
                    "name" : "Light"
                },
                {
                    "color" : [
                        0.028826946392655373,
                        0.028826946392655373,
                        0.028826946392655373
                    ],
                    "intensity" : 10,
                    "type" : "point",
                    "name" : "Point"
                },
                {
                    "color" : [
                        0.010022828355431557,
                        1.5852629431378773e-08,
                        0.0006771537009626627
                    ],
                    "intensity" : 50,
                    "type" : "point",
                    "name" : "Point.001"
                },
                {
                    "color" : [
                        0.004593575838953257,
                        0.005929010454565287,
                        0.009789709001779556
                    ],
                    "intensity" : 50,
                    "type" : "point",
                    "name" : "Point.001"
                },
                {
                    "color" : [
                        0.03310476616024971,
                        3.891099709107948e-08,
                        0.0009548924281261861
                    ],
                    "intensity" : 10,
                    "type" : "point",
                    "name" : "Point.002"
                }
            ]
        }
    },`
**To Reproduce**
create a new blender scene. delete everything from the scene ('A' + 'Del'). Create a point light source. Export to .gltf with "Punctual Lights" option enabled.
**Expected behavior**
As far as i understand there should be only one light entry in the final .gltf file.

**.blend file/ .gltf**
[alight.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3172484/alight.zip)
**Version**
 - OS: Windows 8.1
 - Blender Version 2.80 Beta

**Comment by julienduroure** [comment]
Hello @infobeisel ,
I can not reproduce here.
Can you please test with a recent version of Blender 2.80 beta ?
Please give us the precise version of 2.80 Beta you are using (a new beta is available every day)

Thanks !

**Comment by infobeisel** [comment]
Hello @julienduroure ,
until now i used (from blender's system-info.txt):
`version: 2.80 (sub 57), branch: master, commit date: 2019-04-16 20:13, hash: 5d8030b8f3cf, type: Release
build date: 16/04/2019, 17:08`
now i tried it with
`version: 2.80 (sub 61), branch: blender2.7, commit date: 2019-05-12 22:25, hash: 05f1451d7248, type: Release build date: 12/05/2019, 17:30`
and now after (re)opening blender, creating a new file, deleting everything and adding a point light, it exports only one entry as expected. 

BUT, and probably this would have been the same behaviour in the former version, if you keep open the very same blender instance and scene, and only alterate the point light parameters (e.g. change color), and then export to a new file, it creates 2 entries. If you repeat, it creates 3 entries and so on.

**Comment by julienduroure** [comment]
@infobeisel I can confirm!
Thanks to be able to find how to reproduce it :)
