### ISSUE TITLE
Principled node now has alpha and emission inputs

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#462]
Cf https://developer.blender.org/rB8f71a84496a95528303fbe0bb7c1406060353425

We have to change importer and exporter to take into account this change (this will simply the node setup :) )

**Comment by SteffenDuenner** [comment]
Nice! I was just about to post this commit here :)

**Comment by donmccurdy** [comment]
Wow, yes that potentially helps quite a lot. Do "Alpha Blend" and "Alpha Clip" modes still work as expected?

Was this on a roadmap we could have seen earlier? I'd asked in the dev forums a few months ago and it sounded like the answer was "maybe someday" at the time, might have saved some trouble if we'd known this. 😅

In any case, strong +1 for using the new inputs.

**Comment by julienduroure** [comment]
Was a surprise for me too ;-)

**Comment by emackey** [comment]
Very cool.

Via ZanQdo on the [KhronosDev](https://www.khronos.org/news/permalink/khronos-developer-slack-5bfc62eb261764.20435008) chat:  https://devtalk.blender.org/t/13-may-2019/7076

**Comment by andrewpeterprifer** [comment]
Just ran into this too, any development on this?

**Comment by emackey** [comment]
There's an unfinished pull request in #476 that needs some review feedback addressed before it can proceed.
