### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by dhygns** [KhronosGroup/glTF-Blender-IO#464]
**Describe the bug**
 Importing failed

**To Reproduce**
 Pressed like this and choose one of **.glb** files
![image](https://user-images.githubusercontent.com/16233724/57658008-3de84380-75ab-11e9-8156-a1c34cbd4ac6.png)

**Expected behavior**
It should import successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16233724/57657969-12fdef80-75ab-11e9-9a01-376ca6300149.png)

**Version**
 - OS: _Windows 10 Pro_
 - Blender Version : _2.79_

**Comment by julienduroure** [comment]
This is now fixed
