### ISSUE TITLE
Mismatched input/output elements count of animation sampler.

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF-Blender-IO#465]
**Describe the bug**
For LINEAR and STEP interpolation method, the specification says that:
> The number output of elements must equal the number of input elements.

The exported gltf of the reporting blender scene is not in compliance with it. The sampler has 2 keys but 6 values.

**To Reproduce**
Export the reporting scene.

**Expected behavior**
The number output of elements shall equal to the number of input elements in animation sampler.

**Screenshots**

**.blend file/ .gltf**
[testblend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3176221/testblend.zip)

**Version**
 - OS: Windows 7 x64
 - Blender Version 2.80(beta)

**Additional context**

**Comment by julienduroure** [comment]
Hello,

Your animation in blend file is neither in LINEAR or STEP interpolation. This is bezier interpolation, so CUBISPLINE in gltf. So for each keyframe, there is 3 values, as needed.
