### ISSUE TITLE
ShapeKey keyframe animation issue

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#468]
**Describe the bug**
 1- Shapekey keyframe animation not exported when pushed as NLA track.
 2- If not push it to NLA track, it exports the animation but neither of https://gltf-viewer.donmccurdy.com/ and https://sandbox.babylonjs.com/ is able to play it.

**To Reproduce**
1- add a sphere to scene, from the Physics tab  add a physic "Soft body" to it
2- add a plane, from physics tab  add a physic "Collision" to it
3- simulate soft body animation and export it to mdd animation. (File -> export -> lightwave point catch (mdd))
4- delete plane, and remove any physics from sphere object.
5- select sphere in the scene, import mdd animation data. (File -> import -> lightwave point catch (mdd))

After importing mdd file, it will create keyframe animation with shape keys. Now try to export it to Gltf.

**.blend file/ .gltf**
This is my test blend file which is ready for exporting to gltf: 
[untitled.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3181916/untitled.blend.zip)

**Version**
 - OS: linux mint
 - Blender Version [2.79]

**Additional context**
I am using the latest version of this addon from this commit https://github.com/KhronosGroup/glTF-Blender-IO/commit/70eed19eacfec3e2ca27c9ec0ba02fe1cb91dba2

**Comment by julienduroure** [comment]
Developer notes:
I pushed a first fix (743d6007594786358bfcb56cdd819a09113ea609) about checking force sampling or not.
Remaining fix to be done: When animation on SK, we need to sample all SK, not only SK that are animated. Maybe we can use non_keyed_values or other similar system

**Comment by julienduroure** [comment]
Seems this is already fixed
