### ISSUE TITLE
Animations export broken (example file)

### ISSUE THREAD

**Issue by ERS-EIT** [KhronosGroup/glTF-Blender-IO#470]
In the file...
[trump.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3187156/trump.zip)
...you'll find the source (blend) and the exported target (gltf).

The source has one mesh with one armature controlling it. The armature has some deform and control bones.

When exporting the file with settings...
![exporter_settings01](https://user-images.githubusercontent.com/9727447/57855989-4c716d80-77ec-11e9-8bf5-ffd001a0c64a.png)
![exporter_settings02](https://user-images.githubusercontent.com/9727447/57855995-509d8b00-77ec-11e9-89e9-fb77dee80083.png)
... and playing the file back in [gltf-Viewer](https://gltf-viewer.donmccurdy.com/) , the animations are listed but not played back.

I do not know if that is because the control bones are exported as well.

**Comment by julienduroure** [comment]
This is probably linked to #460

**Comment by julienduroure** [comment]
Issue is now solved
