### ISSUE TITLE
Python API for depsgraph changed, broke tests

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#471]
The latest build of Blender 2.80 has a change to the Python API that [caused a test failure](https://circleci.com/gh/KhronosGroup/glTF-Blender-IO/580#tests/containers/1) in master.

> bpy.context.depsgraph
> AttributeError: 'Context' object has no attribute 'depsgraph'

Comparing the output of `dir(bpy.context)` from a recent build to today's build, `depsgraph` was removed and `evaluated_depsgraph_get` was added.

**Comment by julienduroure** [comment]
@emackey Changes are done on blender add-on repo, I will merge it tonight
