### ISSUE TITLE
Imported normal maps become emissive

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#473]
With the latest build of Blender, the "Normal" input on the Principled BSDF node moved down a couple notches to make room for Emissive etc.  The importer picks the wrong input for normal maps now, it would seem.

/cc @julienduroure 

If I get time I will try to add a test for round-tripping normals, emissive, and the others.  Only ORM is tested at this point.

**Comment by julienduroure** [comment]
With the new 2 inputs of principled node (emission and alpha), index of inputs probably changed ...
