### ISSUE TITLE
Bad animation export (a channel is written twice in gltf file)

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#474]
Exporting following file,

[light_anim.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3193135/light_anim.zip)

glTF file is not valid, a channel is written twice (rotation on node 0

**Comment by julienduroure** [comment]
Both rotation_euler and rotation_quaternion are animated in the file.
This is now a good idea, in Blender side.

Maybe we should add a check (and a warning) to avoid duplicate rotation animation export

**Comment by AurL** [comment]
@julienduroure just my 2 cent on this: wouldn't it be better to just skip/drop/don't export rotations channels that are not the current object's rotation mode here ?

Both cube and spot are in 'QUATERNION' mode so they are linked to the quaternion channels, the euler one being just the result of a misclick on "LocRot" when generating the animation and are just not attached rotations ?

**Comment by julienduroure** [comment]
@AurL You're right, we should keep only the current object rotation mode, and skipping other(s) one(s), Instead of keeping the first one retrieve and ignore other(s) one(s).

Great idea, thanks :)

PS : 
But it will not work with delta transforms (I really don't know if this feature is often used)

**Comment by AurL** [comment]
I don't have a lot of experience with delta transforms but imo it's something that could trigger a baking operation, same for everything that is added on top of raw/base T/R/S keyframe animation like limits/offsets and IKs.
(Our usecase might be different but for our Blender processings in Sketchfab, we usually bake everything to be sure to get the exact visual result for the animations)
