### ISSUE TITLE
T64760 : Alpha export regression

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#478]
Bug from blender repo:
https://developer.blender.org/T64760

**Comment by SurlyBird** [comment]
@julienduroure Any ETA on a fix for this?

**Comment by julienduroure** [comment]
@donmccurdy @emackey :

I didn't work on exporting material yet, maybe yo ucan have a look on it?
Seems to be a **regression**. It is not working anymore on 0.9.4, but works on version (before we include version in asset generator string)

**Comment by julienduroure** [comment]
Note: Generated image has no alpha channel

**Comment by SurlyBird** [comment]
I can fix glTF exports by simply repacking the texture (with alpha) in VS Code, so I'm not blocked, but I definitely would love to see the return of the correct functionality. Thanks for all the hard work on this.

**Comment by julienduroure** [comment]
@emackey : This seems to be linked to texture export you commited/you are involved on. Do you have any time to have a look on it?

Note: We've got another blender issue open regarding alpha export, that is probably same issue : https://developer.blender.org/T65234

**Comment by emackey** [comment]
Also reported in #425.  I'll take a look.
