### ISSUE TITLE
mesh.show_double_sided was removed from blender 2 days ago, crashing the exporter

### ISSUE THREAD

**Issue by sapiensl** [KhronosGroup/glTF-Blender-IO#480]
Hi!

In the newest build of Blender 2.8, the member "blender_mesh.show_double_sided" was removed due to it being "an old legacy option" (see https://git.blender.org/gitweb/gitweb.cgi/blender.git/commit/07c67148e36d95ac185c553ceacbdb6896ae46ca). This causes the exporter to crash.

**To Reproduce**
1. Take any simple blend file, the standard cube does it
2. Try to export the scene with any settings
3. You will get an error stating that the parameter "show_double_sided could not be found"

**Version**
 - Blender 2.8 beta build from today, 2019-05-20

**Additional context**
I hotfixed the problem by changing line 70ish of "blender/exp/gltf2_blender_gather_primitives.py" from:

`mesh_double_sided = blender_mesh.show_double_sided`

to:

`mesh_double_sided = bpy.data.materials[blender_primitive['material']].use_backface_culling`

This might just be the correct solution, but I am not quite sure, since I am pretty unfamiliar with this project. I just thought the info might help.

Cheers!

**Comment by julienduroure** [comment]
Are you sure you are using the last build?
This change is already committed

**Comment by julienduroure** [comment]
See here: https://github.com/KhronosGroup/glTF-Blender-IO/commit/b68e702e0e375399d9476b5cb57f018b89777a21

**Comment by sapiensl** [comment]
oh, thank you very much! Have a nice day!
