### ISSUE TITLE
Support exporting constraints

### ISSUE THREAD

**Issue by meatN** [KhronosGroup/glTF-Blender-IO#481]
In previous version glTF-blender-exporter I use constraint - TracTo for camera object in blender
Export had correct rotation for camera object.
In new version glTF-blender-io  ignore constraint and just save parameter Transform->Rotation of camera object (which is displayed incorrect in both version Blender 2.79 and Blender 2.8 ) 

Does you support constraints (or special only this constraint) in new version?
Or I miss something?

**Comment by donmccurdy** [comment]
The glTF format does not directly store Blender's constraints, but with the right settings it should be possible to 'bake' the animation with the effect of the constraints. Have you tried exporting with *Always Sample Animations* and/or *Bake Skinning Constraints* enabled? If those options don't work, could you share an example `.blend` file? You can attach ZIP files to github issues.

**Comment by meatN** [comment]
[test_constraint.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3199202/test_constraint.zip)

I not use animation or skining (I check this options - it doesn't help) In attachment export with Blender 2.79 + gltf-blender-exporter (with correct camera rotation) and with Blender 2.80 (with incorrect camera rotation)

**Comment by meatN** [comment]
Is any activity on this question? 
I have to use "Apply - visual trasform" option for object with "TracTo" constraint all the time, when I change it position ( I really often use this constraint for camera and lamps)

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
