### ISSUE TITLE
Vertex colors are not exported

### ISSUE THREAD

**Issue by donalffons** [KhronosGroup/glTF-Blender-IO#482]
**Describe the bug**
Vertex colors of the attached model are not exported for the Suzanne model. The vertex colors on the cube work fine.

![Screenshot from 2019-05-20 23-37-53](https://user-images.githubusercontent.com/33040347/58053614-57affa80-7b58-11e9-8d07-33ed4092f978.png)

**To Reproduce**
1. Open "bugreport.blend"
2. Export as GLB/GLTF
[bugreport.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3199917/bugreport.zip)

**Version**
 - OS: Ubuntu 18.04
 - Blender Version: 2.80 2019-05-17

**PS**
You are doing fantastic work with this project! :)

**Comment by samanthajo2** [comment]
Sooooo, is this fix actually applied in the repo?

I cloned the repo just now, copied the addons folder to the correct place, ran blender, it's definitely a newer version than the one I had before as the UI changed. I re-exported some files that had other issues and they no longer have any colors.
