### ISSUE TITLE
Maya exported GLTF2 model breaks

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#483]
**Describe the bug**
Maya exported model works in three.js, but not Blender.

**To Reproduce**
1. Create model in Maya
2. Export using https://github.com/WonderMediaProductions/Maya2glTF/commit/d30636ffa1a47415720cbdb9b1ad51534902c22f
3. Import in Blender https://github.com/KhronosGroup/glTF-Blender-IO/commit/fbb2c50723e5eaa2635672fedfb0f53df7d0798f
4. Breaks in Blender.
5. Open in three.js via Visual Studio Code. Looks fine.

**Expected behavior**

Render like three.js.

**Screenshots**

![Screen Shot 2019-05-20 at 6 48 00 PM](https://user-images.githubusercontent.com/32321/58062623-d17fbe00-7b2f-11e9-8ea1-53bd4c8db04f.png)

![Screen Shot 2019-05-20 at 6 46 05 PM](https://user-images.githubusercontent.com/32321/58062601-c4fb6580-7b2f-11e9-9358-a5717733bd12.png)

![Screen Shot 2019-05-20 at 6 49 19 PM](https://user-images.githubusercontent.com/32321/58062670-fffd9900-7b2f-11e9-9f09-d7977d72057c.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

https://github.com/assimp/assimp-mdb/tree/master/model-db/fbx/sphere_rig_advanced

[sphere_rig_advanced.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3200404/sphere_rig_advanced.zip)

**Version**
 - OS: osx
 - Blender Version 2.80 May 20, 2019

**Comment by fire** [comment]
[sphere_rig_advanced_broken.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3200424/sphere_rig_advanced_broken.blend.zip)

Blend file for the result.

**Comment by julienduroure** [comment]
Confirmed.
Seems rest pose is OK, but problem seems to be on animation data.
Will investigate
