### ISSUE TITLE
Collection object has no attribute 'layers' in gltf_blender_gather_nodes.__filter_node(..): 

### ISSUE THREAD

**Issue by infobeisel** [KhronosGroup/glTF-Blender-IO#484]
when exporting and reaching the last if branch in gltf_blender_gather_nodes.__filter_node, it stops because blender's 2.8 'collection' type has no attribute 'layers'

**To Reproduce**
in my case it only reached that line when i linked a collection from another file into my blend file and then exported it.

Blender Version 2.8 21.05.2019

**Comment by roxlu** [comment]
@julienduroure would this be a super easy fix by just adding a check if the `layers` attribute exists?

**Comment by julienduroure** [comment]
Layers are removed from blender 2.8
@emackey : Do you know why, when you worked on polish exporter options, you kept a reference to layers, even if the option is no more available in UI ?

**Comment by emackey** [comment]
I think that option got overlooked because it is [commented out](https://github.com/KhronosGroup/glTF-Blender-IO/blob/8bc4b5a174ec1a868533782297d0b9668c149f39/addons/io_scene_gltf2/__init__.py#L208-L212) and wasn't visible when I was looking at the export UI.  Safe to remove it.
