### ISSUE TITLE
Export bake skin does nothing

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#485]
Currently, export option "export_bake_skins" does nothing (after search in code, there is only a warning displaying that baking skin is not supported).

I am not sure what it was supposed to do, but it seems that it is really linked to my PR #479, that fix #460 bug.

Problem : 
- When using complex rig, deformation bones have no animation, but there are some constraints on it, or TRS are inherent from parents
- baking only deformation bones are not sufficient, because of inheritance from parents

What I did currently in #479 : When user choose "Always Sample Animations", it samples all bones from the armature. It works well. Solution 1 is to keep as it is in #479, and remove the "bake bone constraints" option.

What can maybe be done: Solution 2: Keep "Always Sample Animations" as it is currently in master (sample only bones when there is animation), and sample all bones from armature when user checked 'Bake Skinning Constraints".

What can be done in a future: 
- export only baked deformation bone. This is not done for now, and will need more work (because of bone inheritance).

@donmccurdy @emackey What do you think ? Regarding number of likes on twitter ( [here](https://twitter.com/julienduroure/status/1130066310736621569) and [here](https://twitter.com/julienduroure/status/1130065862453551104) about these feature, it seems to be a really awaited feature ;-)

**Comment by donmccurdy** [comment]
Do you have a preference between solutions 1 and 2?

My vote would be to remove the "bake bone constraints" option entirely and to focus on making sampled animation work as robustly as possible. I'm not as concerned about removing non-deforming bones in the export, especially if that makes things more complicated now.

**Comment by julienduroure** [comment]
I'm OK with solution 1. I will remove the option later today after merging #479

Export only def bones --> I will not work on it soon. Maybe it can be a long term feature that can be done, but not priority for now.
