### ISSUE TITLE
Validator results not checked carefully enough

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#486]
Well, I'm sorry I didn't notice this before now.  The test suite in this project runs the glTF Validator, and it looks at some keys like `hasTextures` and `primitivesCount` to match expected values.  It also looks for the Validator's promise to be rejected, meaning that the Validator itself crashed or wasn't able to process the file being validated.

One critical piece is missing:  The test suite is not looking at `issues.numErrors` to see if the model actually passed validation with no errors.

The good-ish news is that most of the test models do pass validation in master, even without this check in place.  However, 2 of them do not:

```
scenes/01_morphed_cube.gltf
```

> Animation sampler output accessor of count 18 expected. Found 12.

```
roundtrip/03_all_animations/03_all_animations.gltf
```

> (482 errors, all normal vectors are zero length)

I discovered this while attempting to add a new test model to roundtrip.  The model is round-tripping and losing all of its normal vector information in the process, and I have not yet figured out why.  I'll file a separate issue on the normal vectors once I have more information, but it would appear that at least one of our existing roundtrip models exhibits the problem.

**Comment by emackey** [comment]
I pushed a new branch `test-num-errors` that has the missing check.  It will fail the tests on the first push, because of the previously undetected brokenness.

**Comment by donmccurdy** [comment]
> The model is round-tripping and losing all of its normal vector information in the process,

Hm, maybe related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/482?

**Comment by Cyp** [comment]
My guess is maybe related to #436?
