### ISSUE TITLE
Mesh suffix yields corrupt data

### ISSUE THREAD

**Issue by emkayg** [KhronosGroup/glTF-Blender-IO#493]
Description: 
When a mesh (the mesh itself inside the object dropdown in the outliner) has a .xxx suffix, this yields in skipping this object and a corrupted output.

Additional note: this gets particularly messy and was hard to track down when many objects are selected for export. There may be potential further issues once an item is skipped, compounding errors down the line. But fixing this behaviour would prevent that from surfacing.

To reproduce by simple example:
1. create a cube
2. duplicate the cube (which results in cube.001). Note that changing the top level object name does not suffice to solve this issue, only changing the mesh name itself does).
3. export and observe the only the first cube is actually exported

**Comment by emackey** [comment]
@emkayg I'm having trouble reproducing this in Blender 2.80, May 20th build.  What version are you using?

**Comment by donmccurdy** [comment]
Can't reproduce this either. Note that using "Duplicate Linked" will intentionally export a single copy of the mesh and reuse it. When you say "corrupted output", what do you mean? Do you see a validation problem in the file, or is a mesh just missing? Including the .blend and glTF files in this issue may help (you can attach ZIP archives to comments).

**Comment by emkayg** [comment]
Ugh. Go figure. Was loading a build from a few days ago. Seems fine in the latest. Well, it was fun noticing this behaviour :P Sorry everyone.

**Comment by emackey** [comment]
No worries!

**Comment by donmccurdy** [comment]
Sorry for the confusion! :)
