### ISSUE TITLE
Morphing animation export broken

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#494]
One of our test models, `01_morphed_cube` exports to an invalid glTF file.  The test suite was not catching this problem (reported in #486).  The test suite itself was corrected in #492, but as part of that fix, this problematic model was parked.

The glTF Validator reports the following error on the exported version of this model:

> /animations/0/channels/0/sampler - Animation sampler output accessor of count 18 expected. Found 12.

The model has 3 keyframes, and animates 2 channels with `CUBICSPLINE` animation (which requires 3 values per key).  3 x 3 x 2 == 18, so the Validator is correct in flagging the count of 12 on the accessor.

The fix for this issue should include moving the tests out of the [parked folder](https://github.com/KhronosGroup/glTF-Blender-IO/tree/f535581fe0964f8d7662a5d25bc8822a1ad49a97/tests/parked) and back to their rightful place in the test suite.

**Comment by julienduroure** [comment]
Maybe same issue in #468 ?

**Comment by julienduroure** [comment]
@emackey I opened a PR fixing this issue : #521

**Comment by julienduroure** [comment]
This is now merged
