### ISSUE TITLE
Transformations on export are different than in Blender. 

### ISSUE THREAD

**Issue by ranqiz** [KhronosGroup/glTF-Blender-IO#495]
**Describe the bug**
GLTF exporter doesn't export transformations. Every time it somehow takes a middle of the bounding box center and place it in the center of the world. 
**To Reproduce**

Place a cube on the scene and for example move it on Z axis to 5 units, so it will be without doubt much higher than ground. You can also add to the cube a ground plane. Then export and take a look in any gltf viewer, where the object is (show the grid, to see it)

**Expected behavior**
The object should be in the middle of the world, if more than one, it should be in the center of bounding box center. 
**Screenshots**
Attaching screenshots. 
![Blender](https://user-images.githubusercontent.com/36239294/58208033-39770580-7ce4-11e9-8c33-8ce73f3dc994.jpg)
![Viewer](https://user-images.githubusercontent.com/36239294/58208034-39770580-7ce4-11e9-98b8-a0ba10c66b36.jpg)

**.blend file/ .gltf**
Not needed in this scenario. 

**Version**
 - OS: Windows 10
 - Blender Version [2.8 2019-05-22] Hash- 85322737baec

**Additional context**
GLTF behaving like this is useless in AR.

**Comment by ranqiz** [comment]
Hi Julien, 

Take a look at grid floor on both screens, object is in different place. When I want to have a lamp on the ceiling, after export it is on the floor.  

Attaching files, blend and gltf in zip. Please take a look where the grid is in Blender, and where after export. I mean not grid but model. 

[GLTF_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3209372/GLTF_test.zip)

**Comment by julienduroure** [comment]
I can't reproduce from your blend file.
Did you see that the grid on https://gltf-viewer.donmccurdy.com/ is not displayed on world center? This is a feature on the viewer, but the glb file generated from blender is OK.

And the gltf file you provided is not generated from your .blend file! (Only 1 object in your gltf file, but 2 on you .blend).

If you have an issue with a lamp location, please open an another issue with the corresponding blend file with this lamp, but there is no issue in file you provided.
