### ISSUE TITLE
16bit texture-files over-ridden with 8-bit version, without asking 

### ISSUE THREAD

**Issue by emrum** [KhronosGroup/glTF-Blender-IO#496]
Blender version 2.8 -- 2019-05-20 
--
I tried to export as GLTF with option "Separate gltf + texture".
(in order to make it use existing textures) 
Instead of using the existing PNG files the
exporter over-wrote them with 8-bit version, 
without telling me anything.

**Expected behavior**
Select-box : texture export or use-existing. 
Reference existing textures. 
Ask for metall+roughness maps to be combined into new single texture, 
allow to use them separately. (checkbox: combine channels // use separate image-files) 
Ask before overwriting. 
Use 16bit / 32bit-float textures. 

**Version**
 - OS: ubuntu 18.04
 - Blender Version _ 2.8 -- 2019-05-20 
 - GLTF IO exporter included in release (addon)

**Comment by donmccurdy** [comment]
Merging with https://github.com/KhronosGroup/glTF-Blender-IO/issues/428.

A couple questions, if you'd like to follow up on the other thread –

1) Do you mean that the 16-bit source texture _on disk_ is being overwritten when you export the file? Or that the glTF file is exported with a new, 8-bit version of the same texture, with a different path?
2) Note on glTF and engine support: https://github.com/KhronosGroup/glTF/issues/1561

**Comment by emrum** [comment]
the textures on disk were over-written (by chosing the same directory for export). 
 --

**Comment by emackey** [comment]
@donmccurdy That's correct.  You may recall that you contributed some logic to protect against this, but, that piece of logic [was removed here](https://github.com/KhronosGroup/glTF-Blender-IO/pull/404/files#diff-444226537cdaaa92459dad1cd814237bL162) and has not yet been rewritten.

Until this gets fixed, I recommend always exporting to a dedicated export-only folder.
