### ISSUE TITLE
Metallic Roughness texture changes after export

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#498]
This is how my metallic roughness texture looks like: 
![Warrior_marmoset_Metallic_Roughness](https://user-images.githubusercontent.com/5787647/58374596-19e71380-7f56-11e9-9e1d-a2d06fdcfb1f.png)

after exporting the model to gltf I get this :  
![Warrior_marmoset_Metallic-Warrior_marmoset_Roughness](https://user-images.githubusercontent.com/5787647/58374604-397e3c00-7f56-11e9-831b-6da9e207fd3d.png)

seems it adds color to R channel after export.

I use this example to create my material : 
![addons_io-gltf2-material-principled](https://user-images.githubusercontent.com/5787647/58374635-c0331900-7f56-11e9-8bc6-2364706ef6d1.png)

I am on blender 2.8 with gltf add-on version 0.9.11

**Comment by julienduroure** [comment]
@Ali-RS Can you please share the .blend file?

**Comment by Ali-RS** [comment]
Yes
[test.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3220068/test.blend.zip)

**Comment by Ali-RS** [comment]
@julienduroure I found that it does work fine in v 0.9.1 but broken from v0.9.2.
So it should be one of these commits that breaks it: 
2ea96343df3e4d13b7a16ef4611fd16f6acdc2ff
or
f12b8205284d13ebcd294abc525ff54d8d4c1663

**Comment by julienduroure** [comment]
@emackey : Seems to be related to your commit. Do you have time to have a look on it?

**Comment by emackey** [comment]
If you're not using an occlusion channel, there is no need for this exporter to preserve the red channel.  The exporter will assemble occlusion, roughness, metallic from separate grayscale images if need be, and the final result is expected to be different from the source images.

That said, there is a separate desire to have the exporter preserve original image encoding whenever possible, and that would affect this outcome as well.  There's a long history of that feature getting implemented and then getting broken again, first in the glTF-Blender-Exporter project, and again later in this project, most recently in #404.  We're tracking that problem in #428.

**Comment by julienduroure** [comment]
@emackey: Now that #506 is merged, maybe this ticket can be closed?

**Comment by Ali-RS** [comment]
@julienduroure seems not resolved yet, please see the `Stuff still needs doing:` in this post: 

https://github.com/KhronosGroup/glTF-Blender-IO/pull/506#issue-283435093

**Comment by scurest** [comment]
I re-tested this. It's fixed (see https://github.com/KhronosGroup/glTF-Blender-IO/pull/798#issuecomment-561284590).
