### ISSUE TITLE
Merge animation of rig & shapekeys of corresponding meshes

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#499]
On complex rigs, we often have:
* animation on rig
* animation on shapekeys (directly of by drivers)

On current implementation, multiples animations are created (one for rig, one for weights), because they are on different objects.
We need a way to merge these animations into a simple one if user want it (new option in UI ?)

There is no simple answer, because multiple action can be present in NLA for each type of objects (rig, mesh objects). How to associate them correctly? (for animation on shapekeys without driver, because in case on driver, there is no action about shapekeys)

Note: currently, drivers on shapekeys are not yet implemented (see #377), will work on it soon

**Comment by donmccurdy** [comment]
In glTF-Blender-Exporter, we'd implemented things such that if two NLA tracks had the same name (excluding the default track names) they'd be written to a single glTF animation. That got lost in the 2.8 migration, but I think it was a pretty functional solution.

**Comment by Ybalrid** [comment]
> if two NLA tracks had the same name (excluding the default track names) they'd be written to a single glTF animation

Doing it the way @donmccurdy describe it is a simple yet effective solution to that problem. If that could be implemented in this plugin for 2.80 it would be awesome!

**Comment by julienduroure** [comment]
Closing as duplicate of #557
