### ISSUE TITLE
Exporter: Use Principled BSDF / Deprecate custom glTF node groups

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#5]
Principled BSDF export
- [x] Scalars and vectors
- [x] Extract channels and merge image functionality
- [x] Images, textures and samplers
   - [x] Normal
   - [x] Emissive
   - [x] Base Color
   - [x] Metallic
   - [x] Roughness

**Comment by UX3D-nopper** [comment]
As discussed, having the importer and exporter in one place, this will finally result in a "smooth" round trip import - export.

**Comment by Chaoss86** [comment]
Roughness does not export, have tried almost eeverything I can think of.

**Comment by donmccurdy** [comment]
@Chaoss86 see in-progress docs: https://gltf-blender-io-docs-fuznnktuig.now.sh/addons/io_gltf2. If that node structure is not working for you, could you file a new bug with more details?
