### ISSUE TITLE
Import support for glTF's doubleSided flag

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#501]
Can we add import support for doubleSided for Blender 2.80?

I think this is a one-line change, around line 51 in [imp/gltf2_blender_material.py](https://github.com/KhronosGroup/glTF-Blender-IO/blob/ecb1fc4cd5ab543b5e3e6b92d22e58f422f3862d/addons/io_scene_gltf2/blender/imp/gltf2_blender_material.py#L51)

```
        mat.use_backface_culling = (pymaterial.double_sided != True)
```

This only works in 2.80, of course.  I don't much care about adding support to 2.79, since 2.79 did not have a per-material backface culling flag.

I tried this, but apparently it's not valid Python:

```
        if bpy.app.version < (2, 80, 0):
            # Blender 2.79 did not have a per-material double-sided flag.
        else:
            mat.use_backface_culling = (pymaterial.double_sided != True)
```

Maybe we need a new construct for code that only runs on 2.80?

**Comment by julienduroure** [comment]
Here is the syntax:

```

if bpy.app.version < (2, 80, 0):
            pass # Blender 2.79 did not have a per-material double-sided flag.
        else:
            mat.use_backface_culling = (pymaterial.double_sided
```

**Comment by emackey** [comment]
Thanks!  I'll open a PR with some associated tests when I get a chance.
