### ISSUE TITLE
 Gltf export animation not same as Blender rotation animation 

### ISSUE THREAD

**Issue by optimus007** [KhronosGroup/glTF-Blender-IO#508]
**Gltf export rotation animation not same as Blender rotation animation**

Recently stared working with gltf. Everything was going good until this issue.
was wondering if there are any fixes or workaround this issue
-any kind Rotation animation export gives these problems 
-with bones and without bones same problem.
![Capture](https://user-images.githubusercontent.com/6885294/58633938-989dd100-8307-11e9-8fda-81a9fc1a02ae.PNG)

_tried with **Always sample animation** and it sometimes gives proper result ! sometimes the animation dosen't move or the file will be empty...
i tried again after posting this Post and it seems to be working fine

**Version**
 - OS: win10 64bit
 - Blender Version 2.79 experimental and official build
 -latest gltf addon

**Comment by julienduroure** [comment]
Hello,

Please always provide an example .blend file, without it, we are not able to investigate or reproduce it

**Comment by julienduroure** [comment]
Seems everything looks fine after your last tests, so closing this ticket. Don't hesitate to comment and reopen if needed
