### ISSUE TITLE
How do i export mesh with alpha transparency in blender 2.79

### ISSUE THREAD

**Issue by optimus007** [KhronosGroup/glTF-Blender-IO#510]
I'm using blender 2.79 experimental and official build with latest gltf addon and was wondering if alpha image support is available since documentation only mentions method to add alpha in blender 2.8 

I've tried both previously known methods and they do not work

![clouds](https://user-images.githubusercontent.com/6885294/58683273-823c5780-8391-11e9-8f49-39b46532c42f.png)
![clouds2](https://user-images.githubusercontent.com/6885294/58685564-ccc1d200-8399-11e9-843b-7dcc1a03c654.png)
output tested  in babylon & windows 3d viewer
![clouds1](https://user-images.githubusercontent.com/6885294/58685561-caf80e80-8399-11e9-93a2-9c379845a93d.png)

blend file
[clouds.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3239952/clouds.zip)

**Comment by emackey** [comment]
Not sure what the history is here, at some point this must have been supported at least via the old custom node setup.  But the code today looks like 2.79 users have no option for that:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/ddb58decdbf56d25259487fa668926af2d8a9766/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py#L88-L90

I've been spending every free moment of time on the 2.80 side lately.  If someone wants to take on 2.79 maintenance, feel free.  But it will be diminishing returns, as 2.80 stable is due out this summer, and we still have a lot of work to do before then.

**Comment by Cyp** [comment]
Random untested guess:
```diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
index 8c18c6b..87a29e7 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py
@@ -86,13 +86,13 @@ def __gather_alpha_cutoff(blender_material, export_settings):
 
 
 def __gather_alpha_mode(blender_material, export_settings):
-    if bpy.app.version < (2, 80, 0):
-        return None
-    else:
+    if bpy.app.version >= (2, 80, 0):
         if blender_material.blend_method == 'CLIP':
             return 'MASK'
         elif blender_material.blend_method == 'BLEND':
             return 'BLEND'
+    if gltf2_blender_get.get_socket_or_texture_slot_old(blender_material, "Alpha") is not None:
+        return 'BLEND'
     return None
```

**Comment by emackey** [comment]
Don't change the `if bpy.app.version < (2, 80, 0)` formatting, it's used by a [python script](https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/tools/convert_to_strict_2.80.py) to convert the source code to strict 2.80 code for inclusion in the Blender Addons repository.

But yes, something like the rest of the code you show would likely get the old custom nodes working again.

In other news, there's an `Alpha` hookup on the 2.80 Principled BSDF node now, so the old system of using the Transparent BSDF with a mix shader and all is obsolete in 2.80.  A number of alpha-related things now need updating on both the importer and exporter due to this recent change.

**Comment by optimus007** [comment]
i'm using a old system which doesn't support 2.8...will switch to it once everything is ready...
so no need to fix if its not supported ...
principled bsdf with alpha and emitter nodes inbuilt should simplify everything for the future

**Comment by scurest** [comment]
Since 2.79 support has been dropped, I think this can be closed.
