### ISSUE TITLE
is this an issue with inverse kinematics?

### ISSUE THREAD

**Issue by germanafro** [KhronosGroup/glTF-Blender-IO#512]
**Describe the bug**
the whole model comes out rather scrambled when used in Aframe

**To Reproduce**
1. export to gltf 2
![export settings](https://user-images.githubusercontent.com/29311694/58716173-b8e19480-83c8-11e9-96b2-c852a72ea070.png)
2. import as asset 
`<a-asset-item id="robot_arm1_model" src="assets/robot_arm/robot_arm1.gltf"></a-asset-item>`
3. use asset:
`<a-entity id="arm_model" gltf-model="#robot_arm1_model" scale="0.01 0.01 0.01" animation-mixer></a-entity>`

something very hideous :( 
![broken_arm](https://user-images.githubusercontent.com/29311694/58716552-92702900-83c9-11e9-90fa-333b346a754a.gif)

**Expected behavior**
a proper jointed moving robot_arm extracting an item from a box

**Screenshots**
![proper_arm](https://user-images.githubusercontent.com/29311694/58716318-0f4ed300-83c9-11e9-8352-aecc260a698c.gif)

**.blend file/ .gltf**
[robot_arm1.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3241867/robot_arm1.zip)

**Version**
 - OS: [Win10 / Apache 2]
 - Blender Version [2.79]

**Additional context**
the robot arm is animated using inverse kinematics

**Comment by julienduroure** [comment]
You have to use "force sample animations" if you want bake bone constraints on your animations.

**Comment by EricEisaman** [comment]
What is the method in the current Blender 2.83 where "force sample animations" is not an export setting for the built-in gltf/.glb exporter?

**Comment by julienduroure** [comment]
The new name is "Always sample animation", and is ON by default

**Comment by EricEisaman** [comment]
Thank you @julienduroure .
