### ISSUE TITLE
Animation export is warped

### ISSUE THREAD

**Issue by danielrea** [KhronosGroup/glTF-Blender-IO#513]
Hi,
When I export from blender and try and load in babylon or threejs I get 100's of these errors:

```
      {
        "code": "ACCESSOR_ANIMATION_INPUT_NEGATIVE",
        "message": "Animation input accessor element at index 2 is negative: -1.8666399717330933.",
        "severity": 0,
        "pointer": "/accessors/44"
      },
```

as well as a couple of these

```
      {
        "code": "MESH_PRIMITIVE_UNUSED_TEXCOORD",
        "message": "Material does not use texture coordinates sets with indices (0).",
        "severity": 2,
        "pointer": "/meshes/1/primitives/0/material"
      },
```

My animation is very messed up especially in Threejs it looks like this: 
https://gyazo.com/227afaf814816e2f0c1301e0fe6a846b

however if i keep letting the animation run it fixes itself and then breaks again:
https://gyazo.com/8f0056bf7c9b888e40b4193001614b35

Any help would be greatly appreciated.

**Comment by julienduroure** [comment]
Hello,

As described in the issue template, please provide:
* the .blend file
* the exact version of blender you are using
* the version of the addon you are using

Without it, we are not able to reproduce your issue

**Comment by danielrea** [comment]
Blend File: https://drive.google.com/file/d/1oL20kznEW9MghynAEBAR5ZWlZHR-QnGd/view?usp=sharing

Tried with version 2.79b and also 2.80 with the same issue.

Version of addon is the included version with 2.80 and for 2.79 b was with "version": (0, 9, 14),

**Comment by julienduroure** [comment]
About ACCESSOR_ANIMATION_INPUT_NEGATIVE:
You have some keyframes on negative frames. When you remove them, no more error.

**Comment by danielrea** [comment]
This was fixed for me by using Sample Animations export option with Blender 2.80. 

Thanks for the help.
