### ISSUE TITLE
Sharp edges and autosmooth corrupt export with skinning enabled

### ISSUE THREAD

**Issue by BlenderSleuth** [KhronosGroup/glTF-Blender-IO#516]
**Describe the bug**
When using the  Auto Smooth and marking edges as sharp, as discussed in #73, and exporting with an armature, the exported gltf is corrupted (tested with importing to blender, https://sandbox.babylonjs.com/ and https://gltf-viewer.donmccurdy.com/).

**To Reproduce**
Download basic project:
[autosmooth_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3243581/autosmooth_test.zip)
Export with Apply Modifiers so that the Autosmooth works, and with skinning enabled.
Open in any viewer
See error: in babylonjs it is "Node has skin defined, but mesh has no joints data."

**Expected behavior**
Correctly exported file.

**Version**
 - OS: Windows 10
 - Blender Version: 2.80 caf52e3779a9 (with 0.9.17 exporter)

**Comment by julienduroure** [comment]
Seems this issue is now solved.
Don't hesitate to comment if I missed something

**Comment by BlenderSleuth** [comment]
Yep, perfect. Thanks!
