### ISSUE TITLE
Exporter support extension "MSFT_lod"

### ISSUE THREAD

**Issue by SaschaBrunnerCH** [KhronosGroup/glTF-Blender-IO#523]
**Is your feature request related to a problem? Please describe.**
The [ArcGIS JS API](https://developers.arcgis.com/javascript/latest/guide/visualizing-points-3d/index.html) supports to load gltf. For performance reason this API supports LOD's through the "MSFT_lod" extension.

**Describe the solution you'd like**
It would be great if the exporter supports creating and writing the [extension MSFT_lod](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/MSFT_lod)

**Comment by donmccurdy** [comment]
Unfortunately I don't think we should implement the `MSFT_lod` extension, but should wait until a Khronos (KHR_) or multi-vendor (EXT_) extension has been created. See https://github.com/KhronosGroup/glTF/issues/1045.

**Comment by SaschaBrunnerCH** [comment]
Ok. Thanks for the answer. At the moment it looks that there is no Khronos (KHR_) or multi-vendor (EXT_) extension on the way?

**Comment by donmccurdy** [comment]
There is discussion and a request for feedback in the issue mentioned above. But until the extension is complete we likely wouldn't implement it here, no.

**Comment by SaschaBrunnerCH** [comment]
Thanks for the feedback.

**Comment by xissburg** [comment]
I have implemented MSFT_lod support on my fork https://github.com/xissburg/glTF-Blender-IO/tree/xissburg/MSFT_lod

Instructions are at the bottom of README.

I will not submit a PR because I don't think they want to officially support this extension. However this implementation could be adapted to support a future official LOD spec.
