### ISSUE TITLE
light strength/energy parameter export, unexpected behaviour

### ISSUE THREAD

**Issue by infobeisel** [KhronosGroup/glTF-Blender-IO#528]
when exporting a light, for instance a point light, the intensity/energy/strength parameter is not the one one would expect with the current blender configuration, for example:

working with **Cycles Render** , 
enabling **Use Nodes** on the point light,
**exporting** the scene,

it (correctly) takes the 'Color' value from the Color input in the Emission Node, 
but it takes the **Energy** value from the 'Lamp' parameters. 
I would expect it to use the **Strength** input from the Emission Node, because in this configuration, one can not see and modify the Energy parameter in the blender UI.

 - OS: windows 8.1
 - Blender Version 2.79

**Comment by donmccurdy** [comment]
Let's merge this into https://github.com/KhronosGroup/glTF-Blender-IO/issues/564?

**Comment by julienduroure** [comment]
Should be fixed in 3cf4d007bbf5ae5d9266e4be53e3200fdfcf8fc5
