### ISSUE TITLE
Animation export without target node

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#529]
From #515 

It seems that the following blend file export a target without any node

[open-book-gltf-issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3258214/open-book-gltf-issue.zip)

**Comment by julienduroure** [comment]
Seems that caching system is NOT working properly on bpy.types objects (as @pjoe already suspect it). This is the root cause of this issue.
So we will have to work on a workaround (passing only names ?)

**Comment by emackey** [comment]
The cache is implemented in [gltf2_blender_gather_cache.py](https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py), maybe it could be modified to detect bpy objects and cache by their names?

**Comment by pjoe** [comment]
Yeah a general handling of this would be best. Caching currently seems very fragile, I also had problems with functions taking list or dict params as those cannot work as part of cache keys.
