### ISSUE TITLE
Blender 2.8 GLTF Export Error (New file without changes)

### ISSUE THREAD

**Issue by jinkumak** [KhronosGroup/glTF-Blender-IO#530]
**Describe the bug**
Blender 2.8 GLTF Export Error

**To Reproduce**
1. Open Blender 2.8 
2. Try to GLTF Export 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/26301861/59010002-b8cf1200-886a-11e9-90e6-3756e18e67db.png)

**Version**
 - OS: windows 10
 - Blender Version [ 2.80 ]

**Comment by julienduroure** [comment]
Hello,

Sorry, I can't reproduce with latest build.
Can you please tell me what exact version of blender 2.80 you are using, and what version of the addon you are using.
Please also test with latest build, and with factory settings

**Comment by emackey** [comment]
It looks like you need a newer build of Blender 2.80 Beta.  The bottom of your call stack in your screenshot names a missing material setting `use_backface_culling`, they just added this a week or so ago.

**Comment by jinkumak** [comment]
Thank you for your mail.

    On Friday, 7 June, 2019, 5:12:45 am GMT+9, Ed Mackey <notifications@github.com> wrote:  
 
 
It looks like you need a newer build of Blender 2.80 Beta. The bottom of your call stack in your screenshot names a missing material setting use_backface_culling, they just added this a week or so ago.
