### ISSUE TITLE
Parent of armature get moved when exported SOMETIMES

### ISSUE THREAD

**Issue by felixmariotto** [KhronosGroup/glTF-Blender-IO#533]
**When I export an object parented to an armature with bone, sometimes the object is incorrectly positioned in the GLTF,** unlike the armature which is at the right position. When I say sometimes, I must elaborate : with other files seemingly identical it happens every time I export, and with some files it does not happen...
**This does not happen when I try to export the same bugy file with glTF-Blender-Exporter 1.0**

It is hard to reproduce... So I join here two versions of blend files almost identical, **one with the bug and one without :** 
[GLBs_cubes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3265461/GLBs_cubes.zip)
[BLENDs_cubes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3265462/BLENDs_cubes.zip)

The export should always be like the green and purple version.

WITH BUG
---> In Blender
![blender_witht_bug](https://user-images.githubusercontent.com/46470486/59096119-be048d80-894c-11e9-98c3-6bce99b887d3.png) 
---> In Don mcCurdy's Three.js viewer
 ![gltf_with_bug](https://user-images.githubusercontent.com/46470486/59096142-c6f55f00-894c-11e9-844e-f71b74eac8d0.png)

WITHOUT BUG
---> In Blender
![blender_without_bug](https://user-images.githubusercontent.com/46470486/59096553-a679d480-894d-11e9-85d1-9c0a0c3c8673.png)
---> In Don mcCurdy's Three.js viewer
![gltf_without_bug](https://user-images.githubusercontent.com/46470486/59096554-a974c500-894d-11e9-8a91-0abd0b723651.png)

I used today's version of glTF-Blender-IO, with Blender 2.79b on Windows 10.
I tried the GLTF in [Don mcCurdy's viewer](https://gltf-viewer.donmccurdy.com) and in a personal Three.js viewer.

Here are several related issues :
https://github.com/KhronosGroup/glTF-Blender-IO/issues/447
https://github.com/KhronosGroup/glTF-Blender-IO/issues/237
https://github.com/KhronosGroup/glTF-Blender-IO/issues/370

**Comment by scurest** [comment]
With current master, with_bug.blend works when exporting and viewing with Three

![view](https://user-images.githubusercontent.com/11024420/88576583-46d80000-d00b-11ea-8111-40486937d7be.png)

It does still suffer from #308 though, which makes it not work when imported back into Blender.

**Comment by scurest** [comment]
@julienduroure This works in master.
