### ISSUE TITLE
No modifier applied

### ISSUE THREAD

**Issue by pafurijaz** [KhronosGroup/glTF-Blender-IO#536]
**Describe the bug**
I tried to export the file attached but time ago I had a success the exporting of intersecting planes are not supported in this particular case.

**To Reproduce**
Try to export the file attached, I have more files with problems if is useful I can share..

[Stingray.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3268960/Stingray.blend.zip)

**Version**
 - OS: Linux 
 - Blender Version version: 2.79 (sub 7), branch: blender2.7, commit date: 2019-05-23 08:19, hash: 054dbb833e15, type: Release
build date: 2019-06-05, 00:16:26
platform: Linux

**Comment by julienduroure** [comment]
Fixed by #547
