### ISSUE TITLE
Colors are not exported when using 'Mix' node combining color and image texture

### ISSUE THREAD

**Issue by elbobo** [KhronosGroup/glTF-Blender-IO#538]
Hi, I am trying to create a material that mixes an image with a color. I am using the 'mix' node. The mix works as I would expect in blender but when exporting, the texture remains but the color is lost.

**To Reproduce**
Open attached blender file, you can see material with baseColor of type 'Mix' mixing an image texture with a color. below is what I see in the nodes in shading.

![mix nodes](https://user-images.githubusercontent.com/5732982/59193436-9fd1a400-8b7d-11e9-8792-ce5e88171b00.png)

**Expected behavior**
When I export, I expect the material to be coloured in the way that it is in blender. See screenshots showing the difference.

![materialinblender](https://user-images.githubusercontent.com/5732982/59193450-a829df00-8b7d-11e9-8004-082e7bd4dc11.png)

![materialafterexport](https://user-images.githubusercontent.com/5732982/59193454-ab24cf80-8b7d-11e9-8c62-6d4e7e914c73.png)

Please find zip with blend file and glb export.

[material_mix_colornotexportingexample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3271908/material_mix_colornotexportingexample.zip)

**Version**
 - macOS
 - Blender 2.8

Any advice appreciated. If I am approaching this incorrectly, happy to understand how better to do this, I just want to mix an image texture with a color (FYI, painting the texture has the same result i.e. you can see it in blender but not on export.

**Comment by emackey** [comment]
As a portable format, glTF does not include Blender's entire node system.  glTF includes simple colors or textures for PBR channels such as Base Color, Metallic, Roughness, Emissive, and Normal Map.  So the exporter can handle a couple of different node configurations by locating the correct texture to export, or even merging separate channels (metallic and roughness) together into an image with glTF's supported mapping.

But, this exporter can't accept all custom node mappings.  Sometimes, a custom node mapping can be "baked" (with the Cycles Bake panel) into a single image, and the baked image can then be assigned to a material for export.

There's an ongoing effort to document the capabilities in the [Blender Manual](https://docs.blender.org/manual/en/dev/addons/io_gltf2.html).
