### ISSUE TITLE
Full animation timeline export

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#539]
I am trying to export a blend file which contains several actions. Those actions starts at some random value and end before the end of the timeline, at 100. 

When you play this in Blender, all actions are played until frame 100, extrapolating after the last keyframe, which happens before frame 100. Then, it goes back to frame 1 and starts playing all the animations again, extrapolating the first keyframe if the action doesn't start at frame 1. 

When exporting to glTF, each action is exported individually, so we lose the information about how long the timeline was and losing the possibility to loop as in Blender.

Is there anyway to export Blender actions in a way that allows to loop while keeping insync the animations?

 I attach a link to a video I have recorded with the issue and the blend file I am using. 
https://www.youtube.com/watch?v=WnTNgAMriQg&feature=youtu.be

[out_of_sync.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3272814/out_of_sync.zip)

**Comment by donmccurdy** [comment]
If each action is exported as a separate animation, it's up to the application to decide whether to play all clips at once, whether to loop them, whether to trigger animations from in-game events, etc. From the file you've provided, an engine certainly _could_ loop all the animations in a 100 frame cycle, but it's more common in general viewers to loop each animation separately (based on each animation's length). There are several ways you could work around this:

A. Add a keyframe at f=100 for each action.
B. Merge animations in the engine before playback
C. (in the future) Assign each action to an NLA track with the same name, so they'll be merged into a single animation at export. We don't support this yet, but we plan to.

**Comment by jjcasmar** [comment]
The first solution is the one I'm considering right now. I was thinking on adding an option to the exporter to automatically add a keyframe at the end of the timeline. The problem is that that only works if you have one set of actions. If you have two sets, it may be incorrect.
  
Merging animations in the engine before playback wont work as we have lost the information that the total length is 100 frames. The longest action is 90 frames. 

I was looking for something like the third solution, some way to add several actions into a single animation which is then exported, with each action as a different channel. I will see if I can provide some help in this direction. 

Thanks for your comment

**Comment by donmccurdy** [comment]
> I was thinking on adding an option to the exporter to automatically add a keyframe at the end of the timeline. The problem is that that only works if you have one set of actions. If you have two sets, it may be incorrect.

Hm, I don't think we should have that built into the exporter – NLA tracks are a more appropriate method. But you can certainly add frames yourself before export, and assign different lengths to different actions.

> Merging animations in the engine before playback wont work as we have lost the information that the total length is 100 frames. The longest action is 90 frames.

Right, this assumes that you know something about how you want to play the animation in your application, or store that in a Custom Property and read it from the app, or something like that. Blender's whole concept of actions and timelines and NLA tracks doesn't transfer 1:1 into other programs.

**Comment by donmccurdy** [comment]
Tracking the remaining feature request (merging NLA tracks with the same name) in https://github.com/KhronosGroup/glTF-Blender-IO/issues/557.
