### ISSUE TITLE
AutoSmooth normals do not export correctly

### ISSUE THREAD

**Issue by pennomi** [KhronosGroup/glTF-Blender-IO#540]
**Describe the bug**
The AutoSmooth normals feature does not export correctly, even with "Apply Modifiers" selected.

**To Reproduce**
1. Download and open the attached Blend file.
2. Export as GLB.
3. Open in a GLTF viewer of your choice
4. The file's normals are all smoothed, instead of having sharp edges where the AutoSmooth feature shows they should be in the Blender viewport.

**Expected behavior**
The exported GLB should have sharp edges in the same places that the Blend file does. Old versions of the GLTF exporter had this, but I don't know what version broke it.

**Screenshots**
![a](https://user-images.githubusercontent.com/832972/59212483-d43e6380-8b6f-11e9-8991-993d62d71aba.png)
![b](https://user-images.githubusercontent.com/832972/59212485-d43e6380-8b6f-11e9-8866-7ad8dd159636.png)

**.blend file/ .gltf**
[minimal.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3273036/minimal.zip)

**Version**
 - OS: linux
 - Blender Version: 2.80 (2019-06-02)

**Additional context**
Note that this uses the features in the Object Data tab, under the Normals and Geometry Data sections. We "Clear Custom Split Normals" and then turn on "Auto Smooth". If I press the "Add Custom Split Normals Data" button before exporting, it exports correctly.

A very old version of the 2.7 plugin handled this correctly. The 2.8 version that shipped with a recent beta handled it correctly as long as the "Apply Modifiers" option was ticked. The latest master of this repo doesn't export correctly no matter what options are set.

**Comment by Vinc3r** [comment]
thanks for the "Add Custom Split Normals Data" button tip, a lot more useful than applying an edge split modifier :p
