### ISSUE TITLE
Not have attribute channels

### ISSUE THREAD

**Issue by zebus3d** [KhronosGroup/glTF-Blender-IO#544]
Error: Not have attribute channels.

can fix in file blender/exp/gltf2_blender_gather_imagel.py line 158
add: 

```
if hasattr(result.shader_node.image, 'channels'):
        if result.shader_node.image.channels == 0:
```

**Comment by julienduroure** [comment]
As requested, please provide a file to reproduce the error. Without it, we are not able to work on your issue
