### ISSUE TITLE
Export wrong normals

### ISSUE THREAD

**Issue by meatN** [KhronosGroup/glTF-Blender-IO#549]
**To Reproduce**
1. Import glTF-sample model BrainStem -- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem -- in Blender 2.8 (I use .glb format)  -> all looks good
2. Export this model as .glb format
3. See result in gltf-viewer -- https://gltf-viewer.donmccurdy.com -- -> normals broken

All import and export setting is default
Blender 2.8 version from 13 June

**Comment by julienduroure** [comment]
Hello,
We pushed some fixed yesterday, so can you please test again with build >= June 14th

**Comment by meatN** [comment]
I have tested it right now (From Blender About -> Version 2.80 (2.80 2019-06-14, Blender Foundation))

**Comment by meatN** [comment]
Sorry)) my fault - in new version of Blender export seems to work - I see normals in gltf-viewer
Not see correct normals in my viewer)) but for sure - its my bug

**Comment by julienduroure** [comment]
Ok, thanks !
