### ISSUE TITLE
Unlit materials do not round-trip

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#554]
There was much debate over "Background" vs "Emission" nodes for `KHR_materials_unlit` in #83 and #220.  But it looks like currently we're in a place where the importer uses Emission and the exporter expects Background.

As a result, `KHR_materials_unlit` is lost during round-trip from/to glTF.

In related news, `KHR_materials_unlit` is completely untested by the test suite.

**Comment by donmccurdy** [comment]
My preferred solution would be https://github.com/KhronosGroup/glTF-Blender-IO/issues/220#issuecomment-455811913, with the exception that i'm fine with having the importer use Emission too. So long as it doesn't also create a Principled node on the same material, the exporter should be able to infer that it's unlit.
