### ISSUE TITLE
Merge NLA tracks with the same name.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#557]
When multiple NLA tracks share the same name, they should be exported as a single glTF animation.

**Comment by aguaviva** [comment]
Hmm how do you get multiple NLA tracks share the same name? I find there is no way to do that, If I try to set the name of a track with the same name of an existing one Blender appends ".001" 
![image](https://user-images.githubusercontent.com/5200915/62314479-6c333c00-b493-11e9-87a1-686dfad70d33.png)

**Comment by aguaviva** [comment]
Also there should be 2 options to export the animations
1) export what the timeline currently has (this would be a simple mode)
2) export the NLA tracks  (advanced)

The default should be the mode #1, otherwise many people will think the animations are not working.

**Comment by donmccurdy** [comment]
> how do you get multiple NLA tracks share the same name? 

In the screenshot you've renamed the Action, not the NLA track. NLA tracks can share names:
<img width="284" alt="Screen Shot 2019-08-01 at 1 30 50 PM" src="https://user-images.githubusercontent.com/1848368/62325540-b8b15400-b460-11e9-9e00-0e697b963a36.png">

> Also there should be 2 options to export the animations

I'd be OK with this, assuming we can get "what the timeline currently has" from the Blender API reasonably. I guess that's the active Action on each object, all merged into a single playable animation in the glTF file.

**Comment by SurlyBird** [comment]
> When multiple NLA tracks share the same name, they should be exported as a single glTF animation.

I have two NLA tracks sharing the same name. Still see two separate animations when I load the .glb in BabylonJS. Is this feature working or am I doing it wrong?

**Comment by donmccurdy** [comment]
No, the feature has not been implemented – this issue just tracks the discussion.

**Comment by SurlyBird** [comment]
OK. Thanks, Don! Having a single track for multiple, separate objects will be greatly appreciated (and seems kind of necessary given you can do this exact thing in Maya using the Babylon exporter). Currently there's no easy solution for what seems like bread-and-butter functionality. Short of combining objects, creating an armature and going through the process of skinning and weighting, I can't find a way to get motion on one exported track.

**Comment by dwrodger** [comment]
Is there a timeframe for this feature? Or any insight into how timeframes get decided?

**Comment by julienduroure** [comment]
My goal is to get it before the feature freeze of v2.81, planned for mid-september

**Comment by julienduroure** [comment]
A first draft is available here: #637 
Not ready to be merged yet

**Comment by julienduroure** [comment]
Fixed in 8a38eca

**Comment by Ziflin** [comment]
@julienduroure Did you have a Blender test file that you were using for this? I'm just wanting to understand how to set things up properly,

**Comment by julienduroure** [comment]
Here is a really simple file where an armature and a shapekeys are merge into a single animation at export, because of the name of the track:
[merge_animation.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3700784/merge_animation.zip)

![image](https://user-images.githubusercontent.com/1696020/66368730-b6580280-e999-11e9-8ac4-8b2e5144d5bc.png)
