### ISSUE TITLE
Export: Camera position set to 0,0,0

### ISSUE THREAD

**Issue by Pita** [KhronosGroup/glTF-Blender-IO#572]
**Describe the bug**
When camera export is ticked, the cameras get exported with position 0,0,0

**To Reproduce**
1. Go to gltf export, select Objects > Cameras
2. Look into resulting gltf file, all cameras are exported with 0,0,0 - but orientation and other data seems correct

**Expected behavior**
Getting the correct camera positions

**Version**
 - OS: macOS
 - Blender Version: 2.80 2019-06-21

**Additional context**
This seems to have already been reported here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/173

**Comment by scurest** [comment]
This works for me. This scene

![cam](https://user-images.githubusercontent.com/11024420/60299904-6d50d680-98f3-11e9-8ff8-185e51b3743c.png)

gives

```json
  "nodes": [
    {
      "camera": 0,
      "name": "Camera_Orientation",
      "rotation": [
        -0.7071067690849304,
        0,
        0,
        0.7071067690849304
      ]
    },
    {
      "children": [
        0
      ],
      "name": "Camera",
      "rotation": [
        0.4389207363128662,
        0.45883187651634216,
        -0.29061833024024963,
        0.7157952785491943
      ],
      "translation": [
        7.719948768615723,
        6.530452251434326,
        3.5654592514038086
      ]
    }
  ],
```

**Comment by Pita** [comment]
I realized I get the correct values when I access the parent of the camera object
