### ISSUE TITLE
Bug when try export scene with animated camera with enabled Draco compressor

### ISSUE THREAD

**Issue by Dok11** [KhronosGroup/glTF-Blender-IO#575]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2697890/60397410-b0aa7f80-9b55-11e9-9349-59ae92fcc3ef.png)

**To Reproduce**
1. Download [gltf-bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3342937/gltf-bug.zip)
2. Try export to gltf

**Version**
 - OS: Win10 x64
 - Blender Version 2.8.74

**Comment by Dok11** [comment]
If disable Draco compressor then export will prcocess fine

**Comment by julienduroure** [comment]
@UX3D-nopper @McNopper Can you please check?

**Comment by UX3D-nopper** [comment]
Fix is here https://github.com/KhronosGroup/glTF-Blender-IO/pull/581
