### ISSUE TITLE
Importer Performance

### ISSUE THREAD

**Issue by EtagiBI** [KhronosGroup/glTF-Blender-IO#576]
Hello,

I use a Python script to build a Blender scene from different glTF models. The problem is that it takes a lot of time to import even relatively simple models (~2Mb). 

Are you planning to improve importer performance?

**Comment by julienduroure** [comment]
Some perf enhancement are listed here : #76

**Comment by julienduroure** [comment]
Can you please share an example glb file (~2Mb) that have bad performance.

I here have an example file, that I can't share, that take very long time to import. Only 1 node, but lots of primitives

**Comment by EtagiBI** [comment]
> Can you please share an example glb file (~2Mb) that have bad performance.
> 
> I here have an example file, that I can't share, that take very long time to import. Only 1 node, but lots of primitives

Oh, I don't have those models anymore... From what I've heard, glTF import works much better in stable release of Blender 2.8. Since you're interested, I'll try to make time for some tests this week.

**Comment by julienduroure** [comment]
Closing this ticket (no example file, and some huge improvement are not merged. Should be available in tomorrow's build)

**Comment by EtagiBI** [comment]
It seems that importer's performance is better now, but I'm not sure if 3.5 secs is OK for a 2Mb model (with textures). Here's a sample model:
[16.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3662796/16.zip)

**Comment by julienduroure** [comment]
Another perf improvement will be done this week-end ( see #695 ).
With your file, I go down from 2.25s (current master) to 0.94s (with #695 applied)
