### ISSUE TITLE
Alpha/opacity map image does not export 

### ISSUE THREAD

**Issue by optimus007** [KhronosGroup/glTF-Blender-IO#577]
Alpha/opacity map added to principled node
The image does not seem to exist  in the gltf file after export 
Is this the correct method to export ?
Also it will be helpful for the documentation to have more screenshots on how alpha control and other unique settings works

screencap
![op](https://user-images.githubusercontent.com/6885294/60648338-5f540600-9e5d-11e9-8aeb-1fe4a4b19a5c.PNG)
File:
[cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3358221/cube.zip)

 - OS: windows 10
 - Blender Version [e.g. 2.80.74 ]

**Comment by julienduroure** [comment]
The 2 new fields on principled shader are not yet taken into account. See #462

**Comment by optimus007** [comment]
> The 2 new fields on principled shader are not yet taken into account. See #462

what's the original method?
