### ISSUE TITLE
Not all animations are exported

### ISSUE THREAD

**Issue by samanthajo2** [KhronosGroup/glTF-Blender-IO#578]
**Describe the bug**

There are 6 animations in this file but only 5 get exported

[Pig.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3081630/Pig.blend.zip)

Same file from https://github.com/KhronosGroup/glTF-Blender-IO/issues/433

**To Reproduce**
1. Load into blender
2. File->Export->gltf2.0
3. Check to sample animations
4. Export

**Expected behavior**

6 Animations are exported

<img width="319" alt="Screen Shot 2019-07-05 at 1 06 36" src="https://user-images.githubusercontent.com/49654280/60679212-d1f6cd00-9ec1-11e9-8c59-81b33c39cf9a.png">

In particular of those 6, "Run" is missing

**Version**
 - OS: macOS 10.14.5
 - Blender Version 2.79

**Comment by julienduroure** [comment]
We are currently exporting, for each object:
- active action
- action from NLA tracks

You're "run" action is not the active one, and is not in any NLA track.

We are not exporting all actions, because some actions are not linked to the object. Maybe in the future will can add a check on each action to check if this action is linked to current object.

**Comment by samanthajo2** [comment]
I see. 

Just as a reference I imported the file into Unity and Unreal and both import all 6 animations so maybe importing all 6 is what users are more used to?

**Comment by donmccurdy** [comment]
> Just as a reference I imported the file into Unity and Unreal and both import all 6 animations so maybe importing all 6 is what users are more used to?

This isn't really possible. Unused Actions in Blender are not associated with any particular object, and can't be exported to glTF in isolation... The requirement to export only active Actions, NLA Tracks, and stashed Actions allows the exporter to identify which Actions are associated with which objects.

**Comment by SoapSpangledGames** [comment]
I stashed all of my actions, and the ones that were missing from the export before I stashed them are still missing from the export after I stashed them.

**Comment by julienduroure** [comment]
@SoapSpangledGames please attach a blend file.  We can't investigate without your test case

**Comment by SoapSpangledGames** [comment]
Thank you very much for your quick response. I appreciate it. I've attached my Blender file with all of the animations.

[alpha dragon stashed animations.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5361195/alpha.dragon.stashed.animations.zip)

**Comment by julienduroure** [comment]
In your file:

* Some armature animation are linked to mesh object, so these animations can't be run, they are not exported
* Seems that only FlapWings.001 to FlapWings.005 are missing, but this is empty action, so it's not exported
* 14 other actions are exported

So ... What did you expect to be exported and is currently not?

**Comment by SoapSpangledGames** [comment]
HappyDance
KnockedBackFlying
Perched
VictoryPump

**Comment by julienduroure** [comment]
These actions are not stashed to armature object.
All your action are bone animations, so they need to be stashed to your rig object (MetaRig), not to your mesh object (Cube)

You can see that all bone animations linked to not armature object are wrong (see the red line under each channel):

![image](https://user-images.githubusercontent.com/1696020/95681763-ed32ab00-0be1-11eb-8def-2bdd08b24a40.png)

**Comment by SoapSpangledGames** [comment]
Thank you so much! I stashed all of the animations to my metarig, and they all exported.
