### ISSUE TITLE
Animations have incorrect durations

### ISSUE THREAD

**Issue by samanthajo2** [KhronosGroup/glTF-Blender-IO#579]
**Describe the bug**

Some animations in this file seem to get exported with the wrong durations. This might be related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/578 ?

[Pig.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3081630/Pig.blend.zip)

Same file from https://github.com/KhronosGroup/glTF-Blender-IO/issues/433

**To Reproduce**
1. Load into blender
2. File->Export->gltf2.0
3. Check to sample animations
4. Export
5. Load into viewer and look at Walk anim. It will have a long pause

**Expected behavior**

I'm not sure what the exporter is looking at but assuming it's first frame and last frame then for the 6 animations

```
            First   Last   Num      Expected   Actual
            Frame   Frame  Frames   Duration   Duration in File
  Death:      0     15     15       0.625      1.0833333730697632
  Idle:       0     150    150      6.25       6.25
  WalkSlow:   0     48     48       2          2
  Jump:       0     36     36       1.5        1.5
  Walk:       0     32     32       1.33333    2.6666667461395264
  Run:         missing(see other bug)
```

**Version**
 - OS: macOS 10.14.5
 - Blender Version 2.79

**Comment by julienduroure** [comment]
I can't see any bug here, and you "last frame" values are wrong :
For "death" action, max frame is 26 :
![image](https://user-images.githubusercontent.com/1696020/60685562-03f93680-9ea4-11e9-9d9a-5904670382ba.png)

For "Walk", last frame is 64 :
![image](https://user-images.githubusercontent.com/1696020/60685584-212e0500-9ea4-11e9-9549-f8d09f0fb75c.png)

Don't hesitate to comment and reopen if I missed something, but it seems that you didn't check all channels when you was looking for last frames

**Comment by samanthajo2** [comment]
Sorry about that. Thank you for checking
