### ISSUE TITLE
Blender Metallic = 0 setting not exported as "metallicFactor" : 0,

### ISSUE THREAD

**Issue by MarioDelgadoSr** [KhronosGroup/glTF-Blender-IO#588]
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3386368/test.zip)

Steps to reproduce:

- Starting with a simple (default cube) scene developed with 2.79b. 
- Open 2.79 developed .blend file in 2.8 beta; confirm cube material has Metallic property =  0.
- glTF Export
- Material attributes are:
````
        {
            "doubleSided" : true,
            "extras" : {},
            "name" : "Material",
            "pbrMetallicRoughness" : {}
        }
````

Same scenario, but start the scene in 2.8 beta and export the scene results in the following Material attributes:
````
{
            "doubleSided" : true,
            "name" : "Material",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.800000011920929,
                    0.800000011920929,
                    0.800000011920929,
                    1
                ],
                "metallicFactor" : 0,
                "roughnessFactor" : 0.4000000059604645
            }
        }
````

**Comment by emackey** [comment]
Hi @MarioDelgadoSr, for control over PBR materials, this exporter requires use of certain inputs to the Principled BSDF node, in the shader graph ("Node graph" in Blender 2.79 Cycles engine).  Other kinds of materials are not well supported here.

For details, see [the glTF page of Blender Manual](https://docs.blender.org/manual/en/dev/addons/io_gltf2.html).
