### ISSUE TITLE
Skeleton not exported

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#59]
Hi 
I am using the current master branch for this add-on 

Here is my rig structure 

![1](https://user-images.githubusercontent.com/5787647/47717339-b9f7eb00-dc5a-11e8-9ba8-adbf94b4e3f1.png)

I export it to gltf with default settings, but after I load it again there is no rig on model 

![2](https://user-images.githubusercontent.com/5787647/47717317-acdafc00-dc5a-11e8-8250-2a34af5c5fd5.png)

Will appreciate any help.

**Comment by julienduroure** [comment]
Hello,

Please provide your blend file and/or your gltf file. It's difficult to check what's wrong only with screenshots.

**Comment by Ali-RS** [comment]
Okay,
You can get blend file [here](https://drive.google.com/file/d/155rA_WoXzkL6EI6YUQAIRSa82Pa6N3xP/view?usp=sharing)

**Comment by Ali-RS** [comment]
when I export with this addon : https://github.com/KhronosGroup/glTF-Blender-Exporter
it works fine.

**Comment by UX3D-becher** [comment]
Looks like a bug in the exporter. The output .glTF has no skins

**Comment by UX3D-becher** [comment]
cc94870 fixes the skins not beeing exported.
The validator still does not accept the exported glTF, as it can not decompose the inverse bind matrices of some bones. 
When importing the above glTF, the importer fails with a seemingly unrelated error, @julienduroure maybe you can verify this?

**Comment by julienduroure** [comment]
Hi @UX3D-becher, 
Seems something is wrong on your export hierarchy. All children of "root" node (node 79, children are node id 63 to 78) has no children at all. That means that I can't find any bones starting from root.

**Comment by Ali-RS** [comment]
Any news? Is there a problem with my model?

**Comment by UX3D-becher** [comment]
Should now reimport as expected

**Comment by Ali-RS** [comment]
Thanks for the fix.

**Comment by Ali-RS** [comment]
Hmm... now  I get this error upon export 
![screenshot_2018-11-02_09-48-29](https://user-images.githubusercontent.com/5787647/47897157-ba27fe80-de85-11e8-84e5-d5c1d53002af.png)

**Comment by Ali-RS** [comment]
Anybody have confirmed this yet ?

**Comment by UX3D-becher** [comment]
Yes, i can confirm the error, it is a bug in the exporter.

**Comment by UX3D-becher** [comment]
8fbe41dc16a687e974d0f5d1bbd26c34b7ba616e should fix the issues with rigged animation exports

**Comment by Ali-RS** [comment]
Thank you :)
