### ISSUE TITLE
Duplicate node with animation

### ISSUE THREAD

**Issue by meatN** [KhronosGroup/glTF-Blender-IO#595]
Add simple animation to node
In exported section - nodes - I see this node twice (first - had parent -> scene, second without any parents)
In exported section - animations - I see animation channels with second node 

[test-animation.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3409386/test-animation.zip) - contain .blend , .gltf, .bin

Blender 2.80 Release Candidate - Download 18 Jule 2019

This bug does not reproduce in previos version (Blender 2.80 Beta - 2019-06-13)

**Comment by julienduroure** [comment]
Thanks for reporting. This bug is already fixed in newer build.
Can you please re-test with current build, and/or with RC2 that will come in following days

**Comment by meatN** [comment]
Ок, thanks
