### ISSUE TITLE
Import lattice deformation from Blender

### ISSUE THREAD

**Issue by Dragon3DGraff** [KhronosGroup/glTF-Blender-IO#597]
**Describe the bug**
I made a simple 3d model in Blender and made animation of it - just movement across one axis. I imported it to three.js using gltf format and played animation. Everything is ok.
But after I made deform animation using lattice deformation and tried to import - it don’t play. I baked animation in Blender but got strange result.

**Expected behavior**
The same animation like in Blender

**Screenshots**
it's better seen in video
https://www.youtube.com/watch?v=Xwt8FFMZe8s

**.blend file/ .gltf**
[Test1.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3432840/Test1.zip)

**Version**
 - OS: [Win7 32]
 - Blender Version [blender-2.80rc2-windows32]

**Additional context**
First I asked on three.js forum
https://discourse.threejs.org/t/import-lattice-deformation-from-blender/8691/2

**Comment by julienduroure** [comment]
Unfortunaly, we can't manage all constraints / modifiers in exporter.
glTF 2.0 can export rigs & shapekeys.
If you really want to export this animation, you can probably bake it first
