### ISSUE TITLE
Duplicated shape keys & unknown nodes on mesh with multiple materials.

### ISSUE THREAD

**Issue by tiancaipipi110** [KhronosGroup/glTF-Blender-IO#598]
Same as title. 
If we use more than 1 material on the same mesh, it'll export another set of shape key on unknown nodes. 
[cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3438515/cube.zip)
![whatsup](https://user-images.githubusercontent.com/35275506/61998759-8eba0380-b0e7-11e9-82b9-f93c0d320f58.jpg)

**Comment by julienduroure** [comment]
Can't see any problem here. Each primitive have its own targets array with 1 element, and mesh.weights has also only 1 element.
@donmccurdy Seems https://gltf-viewer.donmccurdy.com/ displays an entry for each primitive, for each morph target.

**Comment by tiancaipipi110** [comment]
@julienduroure Please see markup and let me know if that clears it up.
![markup](https://user-images.githubusercontent.com/35275506/62407219-3acb8500-b5e7-11e9-9f5b-dfd684901282.jpg)

**Comment by julienduroure** [comment]
@tiancaipipi110 in glTF specification, morph target are defined at primitive level. So, if you have 2 materials on a mesh, you will have 2 primitives, so for each shapekeys, you will have 2 morph targets

**Comment by tiancaipipi110** [comment]
@julienduroure I c, thought it was a bug. Thanks.
