### ISSUE TITLE
Custom normals are not exported

### ISSUE THREAD

**Issue by HungryProton** [KhronosGroup/glTF-Blender-IO#599]
**Describe the bug**
Meshes lose their custom normals after exporting them from Blender 2.8 RC3

**To Reproduce**
1. Add a mesh (for example, the default monkey Suzanne)
2. Under the Mesh tab, turn on Auto Smooth
3. Add a 'Normal Edit' modifier, leave everything on default
4. Apply the modifiers
5. Export the object

**Expected behavior**
When loading the resulting glb/gltf file, custom normals should be apparent, instead they still look like the default ones.

**Screenshots**
Same object exported to Collada and gltf :
![image](https://user-images.githubusercontent.com/52043844/62005937-8dfe8d00-b13a-11e9-8d0a-b911035daf40.png)

The custom normals as seen from Blender 2.8 :
![image](https://user-images.githubusercontent.com/52043844/62005928-6f989180-b13a-11e9-9fe3-944e92546cd4.png)

Export options used :
![image](https://user-images.githubusercontent.com/52043844/62005983-02393080-b13b-11e9-9f36-a5d39609174c.png)

**.blend file/ .gltf**
Minimal blend file :
[custom_normal_minimal.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3439107/custom_normal_minimal.zip)

Resulting glb file after export:
[exported_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3439123/exported_glb.zip)

**Version**
 - OS : Windows 10 64bits
 - Blender Version : 2.8 RC3

**Additional context**
+ I previewed the exported glb file in the following applications:
  - Godot engine
  - https://sandbox.babylonjs.com/
  - https://gltf-viewer.donmccurdy.com/
None of them could display the custom normals. 
+ I tried exporting the same object to a dae file and it worked in Godot.
+ I tried both glb and gltf format, but there were no custom normals in both cases.

**Comment by mjdave** [comment]
I've also just hit what is probably the same bug. The "Auto Smooth" setting is being ignored completely now. This wasn't the case in the old version of the exporter I was using (from over a year ago).
