### ISSUE TITLE
Blender 2.8 conversion and integration

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#6]
- [x] Separate 2.79 and 2.80 code
- [x] Implement 2.80 code
- [x] Integrate into 2.80 repository

**Comment by julienduroure** [comment]
Some info about what will change (not final doc of course):
https://wiki.blender.org/wiki/Process/Addons/Guidelines/UpdatingScripts

**Comment by julienduroure** [comment]
Current status about timing (about 2.8)
* Beta release for Blender Conference (end of October). Probably that API will change until this beta release, but we can start working on it before, based on document previously posted.
* Final release start of 2019
