### ISSUE TITLE
Errors exporting Principled BSDF with textures

### ISSUE THREAD

**Issue by revyTH** [KhronosGroup/glTF-Blender-IO#60]
Hi, I am trying to export a Principled BSDF material with textures (diffuse, metalness, roughness, normals) in glTF format but got errors. I've attached the textures used.
[Metal_Steel_Brushed_001.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2538402/Metal_Steel_Brushed_001.zip)

<img width="1241" alt="material" src="https://user-images.githubusercontent.com/26633801/47850390-51814900-ddd5-11e8-8cf7-60dd0ffd4e01.png">
<img width="999" alt="export" src="https://user-images.githubusercontent.com/26633801/47850391-51814900-ddd5-11e8-9790-deff31f05280.png">
<img width="1218" alt="stacktrace_1" src="https://user-images.githubusercontent.com/26633801/47850388-51814900-ddd5-11e8-804b-f6d157b55e80.png">
<img width="1214" alt="stacktrace_2" src="https://user-images.githubusercontent.com/26633801/47850389-51814900-ddd5-11e8-849b-9a68ddb02a12.png">

**Comment by UX3D-nopper** [comment]
Probably our exporter should also tolerate these settings.

**Comment by donmccurdy** [comment]
Which setting do you believe is causing the issue? The "Normal Map" node?

**Comment by UX3D-becher** [comment]
The reason for the error is that each of the textures for metallic and roughness are RGB textures with luminance as metallic / roughness. We assumed that only a single channel of such a texture would be responsible for metallic / roughness. 
To fix it we would need to convert the a multichannel metallic / roughness input to grayscale before creating the MetallicRoughness texture.

@revyTH if you need a quick fix, add a Separate RGB node after the metallic and roughness textures and connect only one channel to the respective Principled BSDF sockets.

**Comment by mobec** [comment]
Could you provide a .blend or .gltf file for which the problem occurs?

**Comment by UX3D-becher** [comment]
Could you provide a .blend or .gltf file for which the problem occurs?

**Comment by revyTH** [comment]
done!

[cube2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2543196/cube2.zip)

**Comment by UX3D-becher** [comment]
now the textures export correctly. 

The empty node warnings come from the lights. I think it is more intuitive to leave them in, as at some point the KHR_lights_extension will use them
