### ISSUE TITLE
Cameras, lights and objects' animations are exported as a different animations sections in the gltf

### ISSUE THREAD

**Issue by aguaviva** [KhronosGroup/glTF-Blender-IO#600]
**Describe the bug**
cameras, lights and objects motion is exported as different animations in the gltf file. 

**To Reproduce**
1) Load the animation_test.blend file(see zip file), it has a test scene where the cameras, the lights and the objects are animated. 
2) Export it as a GLTF file (see the gltf already in the attached zip file) 
3) Notice the animation section contains 3 different animations, one for each type of node (cameras, lights and objects)
>"animations" : [ { ... },{ ... },{ ... } ]

**Expected behavior**
there should only be 1 animation section for all the cameras, lights and objects.
>"animations" : [ { ... } ]

I'd be nice to have a checkbox to choose between separating the animations by node type or having them all merged (this should be the default behaviour).

**.blend file/ .gltf**
[media-test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3451920/media-test.zip)

**Version**
 - OS: Win10
 - Blender Version 2.8 RC3 although I have seen this in older version of Blender.

**Comment by aguaviva** [comment]
An update, I noticed each animated object is now in its own animation track. The default behaviour would be to have all the objects in the same animation track (unless separated by actions, not sure how Blender separates animations though)

**Comment by julienduroure** [comment]
With already planned to merge animation, based on track name in NLA. See #557 
This should answer your requirement
