### ISSUE TITLE
mistake to export a glb file in blender on the mesh 

### ISSUE THREAD

**Issue by Lanceloth25** [KhronosGroup/glTF-Blender-IO#601]
does anyone know why the glb file does not respect the weight when I export it in version 2.79 of blender if it already accommodates the orientation of the bones to global ........ ???
[https://discourse.threejs.org/t/skining-glb-blender/8794](https://discourse.threejs.org/t/skining-glb-blender/8794)

**Comment by julienduroure** [comment]
Hello,
Can you please provide the .blend file ?
Thanks !

**Comment by Lanceloth25** [comment]
Hello friend, I annex 2 files one is in version 2.79 and the other 2.8, in 2.8 it is already corrected the model but the animation is not appreciated the model in the gltf viewer only if you stop the animation is appreciated the model, but it shows well in the windows 3d viewer and in 2.79 it comes out with deformation in the maya since it does not respect the weights of the maya of the model as it shows in the blender file, you glide the glbs.
[files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3464131/files.zip)



> Hello,
> Can you please provide the .blend file ?
> Thanks !

**Comment by Lanceloth25** [comment]
thank you for your help :3

**Comment by julienduroure** [comment]
Sorry, I didn't get was you mean.
Please make simple sentences ending with a dot, not a big paragraph.
Explain for each file, what action you performed, how you see the result is not correct, if possible with screenshots.
Thanks !

**Comment by Lanceloth25** [comment]
> Sorry, I didn't get was you mean.
> Please make simple sentences ending with a dot, not a big paragraph.
> Explain for each file, what action you performed, how you see the result is not correct, if possible with screenshots.
> Thanks !

**Comment by Lanceloth25** [comment]
> Sorry, I didn't get was you mean.
> Please make simple sentences ending with a dot, not a big paragraph.
> Explain for each file, what action you performed, how you see the result is not correct, if possible with screenshots.
> Thanks !

ok, what I mean is that in version 2.8 of blender the animation is not appreciated in the gltf viewer but in the windows 3D viewer yes and the model goes well in the mesh, and in 2.79 if you export and appreciate the animation but with error in the armpits of the mesh as it is marked in the images ...
thank you
[screnshots.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3473575/screnshots.zip)

**Comment by Lanceloth25** [comment]
and the exportation to glb use de default setting in the 2 gltf exporters in blender 2.79 and 2.8
