### ISSUE TITLE
Quaternion not unit

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#605]
In https://sandbox.babylonjs.com/,

The following blend file export said that quaternion is not unit
[quaternion_check.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3463451/quaternion_check.blend.zip)
[quaternion_check.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3463452/quaternion_check.glb.zip)

**Comment by kythyria** [comment]
Not just animation. Blender doesn't normalise rotations if the rotation type is set to quaternion in the Item sidebar, so if you export without selecting something else for that object, the unnormalised quaternion will be written.

It's easy to do by accident: just enter an unnormalised quaternion by hand.
