### ISSUE TITLE
Importing this GLB + exporting as GLTF causes changes.

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/glTF-Blender-IO#607]
Ideally doing an import+export is an idempotent operation but tangents are lost and the textures look different.

https://github.com/Yzou-NaO/glTF-Model

**Comment by donmccurdy** [comment]
There’s an option in the export settings to enable tangents - they’re not preserved through a round trip, I don’t think, but can be regenerated at export.

**Comment by julienduroure** [comment]
I confirm that tangents import are not yet implemented

**Comment by julienduroure** [comment]
Tangents are now imported as custom attributes
