### ISSUE TITLE
Vertex alphas are not exported

### ISSUE THREAD

**Issue by Ldash4** [KhronosGroup/glTF-Blender-IO#610]
**To Reproduce**
1. Create cube
2. Add vertex colors, as well as vertex alpha values. I used [this addon](https://blenderartists.org/t/vertex-color-master/697617) to edit alpha.
3. Export mesh
4. Open mesh in debugger. I used [this](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode).
5. The vertex colors are there as expected, but all of the alpha values are set to one.

**Expected behavior**
The alpha values should match those set in Blender.

**Screenshots**
The colored cube.
![image](https://user-images.githubusercontent.com/30183784/62559355-1be52100-b87b-11e9-84f8-1acb27b738c9.png)
The cube with alpha represented in greyscale.
![image](https://user-images.githubusercontent.com/30183784/62559387-33240e80-b87b-11e9-8a26-ecb43fd80efa.png)
The vertex data as seen in a debugger.
![image](https://user-images.githubusercontent.com/30183784/62559409-41722a80-b87b-11e9-834d-84f40982751d.png)

**.blend file & .gltf**
[vertex_alpha.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3473311/vertex_alpha.zip)

**Version**
 - OS: Arch Linux
 - Exporter version: 0.9.36
 - Blender Version: 2.80

**Comment by Taroslord** [comment]
I'm using Blender 3 and try to export vector info to alpha. Is this still not possible? Or do I something wring in my setup?
![image](https://user-images.githubusercontent.com/55150926/145385279-2943c35d-37a1-41db-9605-995fc44ceec4.png)
