### ISSUE TITLE
Cant export gltf object with animations in corrupted blender project

### ISSUE THREAD

**Issue by Nizaxx** [KhronosGroup/glTF-Blender-IO#615]
**Describe the bug**
So the problem appeared when i exported once object at 60 sampling rate and since that whenever i want to export object with animations its giving me error-logs and file isnt exported.

I tried to reproduce this problem from a scratch but it didnt work out exactly like in my corrupted project. Heres how im trying to export gltf https://streamable.com/75mn2 with failure and visible logs.

**To Reproduce**
1. File -> Export -> GLTF...
2. Choose: 
- General (Selected objects, +Y Up), 
- Meshes (UVs, Normals, Materials),
- Animation ( Use Current Frame, Animations, Limit to Playback..., Sampling Rate:1, Always Sample Animations )

**Expected behavior**
Properly exported gltf file

**Screenshots**
Video: https://streamable.com/75mn2
![image](https://user-images.githubusercontent.com/10244054/62779279-08bc9600-bab3-11e9-823d-1166adfaeb9f.png)

**.blend file/ .gltf**
[ObjOnTexture.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3486357/ObjOnTexture.zip)

**Version**
 - OS: [Windows10 Home]
 - Blender Version [2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: f6cb5f54494e, type:  build date: 2019-07-29, 09:44 AM platform: Windows]

**Additional context**

**Comment by julienduroure** [comment]
You have a strip in NLA without any action on it.
Adding a check on that

**Comment by julienduroure** [comment]
Closed by 6ab5c9b
