### ISSUE TITLE
Importing glft+bin fails, but importing gltb works fine

### ISSUE THREAD

**Issue by schiette** [KhronosGroup/glTF-Blender-IO#616]
**Describe the bug**

We have a gltf+bin that we cannot import. However, when we convert this file into a gltb it imports fine. Are we doing something wrong, or does the importer not support gltf+bin?

**To Reproduce**

Try importing the gltf+bin in attachment
Then try to import the gltb in attachment

Files in attachment

[Proxy.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3486511/Proxy.zip)

**Version**
 - OS: Windows 10 pro
 - Blender Version 2.8

**Comment by julienduroure** [comment]
Confirmed, I need to had some checks

There is a bug in your exporter, because uri of file are not written correctly in your gltf file.
See screenshot : 

![image](https://user-images.githubusercontent.com/1696020/62795005-ed16b700-bad5-11e9-95e9-2617ab11d5bc.png)

**Comment by schiette** [comment]
@julienduroure 
very interesting. We removed the spaces in the texture paths and everything works fine now.
thanks for helping us find the issue!

**Comment by lexaknyazev** [comment]
@julienduroure 
As per the spec, `uri` can use "percent-encoding", so the importer should accept it.
```python
import urllib.parse
urllib.parse.unquote('MOSS%20TEXTURE.jpg')
```
```
'MOSS TEXTURE.jpg'
```

**Comment by schiette** [comment]
I have reported this issue to the 3ds max gltf exporter developers: https://github.com/BabylonJS/Babylon.js/issues/6705

**Comment by schiette** [comment]
@julienduroure  The developers in the exporter thread are referencing the URI specs for gltf (https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris). Can you comment on this? Which is correct here? Should the blender importer be able to handle this, or is the max exporter not according to the specs?

**Comment by julienduroure** [comment]
I just pushed a fix on blender glTF importer to take into account uri escaped chars
