### ISSUE TITLE
Draco compression corrupt armature animations

### ISSUE THREAD

**Issue by Nizaxx** [KhronosGroup/glTF-Blender-IO#617]
**Describe the bug**
Exporting gltf with draco compression on object with armature animation causes random jitter of verticies
Video: https://streamable.com/3ju4b (he should jump and move his fins up while jumping) from https://gltf.insimo.com/

**To Reproduce**
1. Download my project file
2. Select armature object and penguin object (penguin as first)
3. Export as gltf with those options 
![image](https://user-images.githubusercontent.com/10244054/62810699-15ff7200-baff-11e9-85ea-4ec7d4e4a62e.png)
4. Import gltf file here https://gltf.insimo.com/

**Expected behavior**
Properly exported animation like without draco compression or error message that draco cant handle armature(?)

**Screenshots**
Corrupted animation: 
![image](https://user-images.githubusercontent.com/10244054/62810854-adfd5b80-baff-11e9-9cf1-d5ab6a9122fe.png)

**.blend file/ .gltf**
blend and draco-gltf and no-draco-gltf
[RecoverForAnim.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3488156/RecoverForAnim.zip)

**Version**
 - OS: [Windows10 Home]
 - Blender Version [2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: f6cb5f54494e, type: build date: 2019-07-29, 09:44 AM platform: Windows]

**Additional context**

**Comment by julienduroure** [comment]
@UX3D-nopper Can you please have a look on it?

**Comment by julienduroure** [comment]
@UX3D-eckerlein Any news ?

**Comment by cstfan** [comment]
Hi everyone,

I almost have the same problem with Blender 2.80 final version and Blender 2.81 beta with version 1.01 of glTF exporter. For me, with Draco Compression, the animation armature doesn't play when I drag and drop glb file on [Sandbox Babylon.JS](https://sandbox.babylonjs.com/l)

[Sources files here](https://drive.google.com/drive/folders/1bwc8mxEP6aEhRumUOfqFDy9AfmpBHKF-?usp=sharing)

Thank you very much for your work

**Version**
OS: [Windows 10 Pro]
Blender Version 2.81 [commit date: 2019-10-07 14:47, hash: a856c5eccffb]

**Comment by julienduroure** [comment]
@UX3D-nopper and @UX3D-schmithuesen Any news ?

**Comment by UX3D-nopper** [comment]
We and/or @UX3D-eckerlein is activly working on this - like the rest of Draco issues.

**Comment by UX3D-eckerlein** [comment]
About to be fixed with #813.

**Comment by cstfan** [comment]
Hi,
I just tested with version 2.82 Alpha - 416e66c7fe21 of Blender and it's good.
Great.
