### ISSUE TITLE
Problem with importing 

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#62]
Hi 
After exporting model to gltf file I am getting following error reimporting it with this add-on  

![screenshot_2018-11-05_09-45-25](https://user-images.githubusercontent.com/5787647/47981222-40d81800-e0e0-11e8-9c98-36c5cef3d7b3.png)

You can download it [here](https://drive.google.com/file/d/1PTWYpSoexFoI1UfqF9u5eZAdmskHhHVZ/view?usp=sharing)

**Comment by julienduroure** [comment]
Hello,

Thanks for reporting this bug. I can confirm it. 
This is linked to importer, and will be fixed soon
