### ISSUE TITLE
Shape Keys applied to wrong target in Blender 2.8

### ISSUE THREAD

**Issue by jbking93** [KhronosGroup/glTF-Blender-IO#620]
Exporting a GLB out of Blender applies the blend shape attributes to the wrong morph target. 

In my example, the "Glee Eyes" target is being applied to the "Super Open" target. We have tried removing the "Super Open" target completely and re exporting and it just gets applied elsewhere.

Blend and GLB file: https://drive.google.com/drive/folders/14YZx1q0INs-SvKSFIdRv8dy_2QTbapA0?usp=sharing

**Comment by julienduroure** [comment]
Confirmed. What I suspect is that the problem come from inactive shapekeys ( Super Open and Frown).

Can you please confirm that everything is OK if you delete these 2 shapekeys (delete only 1 is not enough) ?

**Comment by jbking93** [comment]
Am checking right now, thankyou for such a swift reply to this!

**Comment by jbking93** [comment]
It seems to move the behaviour to the Left Wink, updated file in original link

**Comment by julienduroure** [comment]
Confirmed that something is really weird. Will check
