### ISSUE TITLE
Orthographic Camera Lens and FOV exported wrong

### ISSUE THREAD

**Issue by UX3D-schottenheimer** [KhronosGroup/glTF-Blender-IO#624]
**Describe the bug**
The orthographic camera isn`t exportet right. It Ignores the Resolusion and the orthographic size.

**To Reproduce**
1. Create Blend file with plane
2. Add a texture to the plane (preferably something you can see easy if it is stretched)
3. Create a camera and switch its type to orthographic.
4. Export
5. The issue is seen in several gltF viewers.

**Expected behavior**
I expect that my Resolution and my camera size will be the same as I assigned in blender

**Screenshots**
This is how it looks in perspective
![image](https://user-images.githubusercontent.com/49145554/63432144-d864e800-c420-11e9-85dc-51dc8ddf05e9.png)

This is how it looks with the orthographic camera
![image](https://user-images.githubusercontent.com/49145554/63432172-eca8e500-c420-11e9-89e4-1457942c9562.png)

**.blend file/ .gltf**
https://drive.google.com/file/d/1lOF9cn86ByZjQQ4LEyQHb1xpnSwktaUD/view?usp=sharing

**Version**
 - OS:Windows 10 64 Bit
- Blender V 2.8

**Additional context**

**Comment by UX3D-becher** [comment]
The conversion between blenders orthographic size and glTFs xmag/ ymag values requires additional care, as xmag and ymag lead to an orthographic window spanning [-xmag, xmag] x [-ymag, ymag]
