### ISSUE TITLE
T69089 : blender v2.81 : libextern_draco.so is missing

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#627]
See https://developer.blender.org/T69089

Seems update to python 3.7.4 broke the generation of .so lib

**Comment by julienduroure** [comment]
Can you please have a look @UX3D-nopper @McNopper ?

**Comment by julienduroure** [comment]
Seems glTF is hardcoding the Blender and Python version, this should be avoided.

**Comment by capnm** [comment]
I was just about to write a patch for Draco, but then realized that the Blender version is hard-coded elsewhere as well. So it is rather for someone who knows the project structure:

git grep '2.80/'
```
.gitignore:7:2.80/*

README.md:11:| 2.80    | https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html |

addons/io_scene_gltf2/io/exp/gltf2_io_draco_compression_extension.py:31:    python_lib = Path('2.80/python/lib')

docker-compose.yml:7:      - "./addons:/root/.config/blender/2.80/scripts/addons:ro"

tools/convert_to_strict_2.80.py:48:OUTPUT = root + "/../2.80/"
```

**Comment by julienduroure** [comment]
Don't worry about gitignore and tools. I think the most important is the draco file. 
Can someone can confirm about docker, for tests ?
