### ISSUE TITLE
version of min Blender is 2.80 in master

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#63]
Hello,

In bl_info data of __init__.py, blender version is set to (2, 80, 0)
But in master, should be 2.79

**Comment by UX3D-becher** [comment]
Blender 2.79 will only output a warning when adding an addon with a higher blender version while blender 2.80 does not load an addon with lower a version number. As we want to have 2.79 and 2.80 in the same branch, I don't see an alternative to setting it to (2, 80, 0).

**Comment by julienduroure** [comment]
Thought 2.80 branch is not merged with master yet, so we can keep it with 2 differents values

**Comment by UX3D-becher** [comment]
I merged the 2.8 branch into master last week, also some of the CI tests now at least locally run on blender 2.8. So I'd say we keep (2, 80, 0)? 
Otherwise we would have to continuously merge any master changes to the 2.80 branch to check if it breaks something with blender 2.80

**Comment by UX3D-becher** [comment]
With 8462542 the Circle CI config now also performs the export tests on a blender 2.8 build of last week

**Comment by julienduroure** [comment]
seems I missed this merge. Sorry about that.
