### ISSUE TITLE
Simple CC0 model for testing issues with bone-object parenting

### ISSUE THREAD

**Issue by capnm** [KhronosGroup/glTF-Blender-IO#632]
We use a simple bone parenting heavily with kids to make animations for games.
I extracted a model (with current Blender v2.81) to demonstrate and help to fix the issues:
[TransportRobot_a-02.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3537178/TransportRobot_a-02.zip)

----

Here is the model triangulated and with cleared animation data + the exported glTF file:
[TransportRobot_a-02_tris.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3537181/TransportRobot_a-02_tris.zip)

![compare_blender2 81_gltfViewer](https://user-images.githubusercontent.com/4047289/63637473-b071c080-c67c-11e9-9314-ce975d588cf7.jpg)

Re-imported glTF file:
![glTF_reimport](https://user-images.githubusercontent.com/4047289/63665595-46683100-c7cc-11e9-976d-6c88de214587.jpg)

----

This is the same model with an animation. IK is used – the option "always sample animation" has been enabled:
[TransportRobot_a-02_tris_anim.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3537183/TransportRobot_a-02_tris_anim.zip)

![TransportRobot_a 02](https://user-images.githubusercontent.com/4047289/63637525-44dc2300-c67d-11e9-9c6d-8104a13b55c0.gif)

@donmccurdy this is also related to  #603

**Comment by capnm** [comment]
## Comparison with the (currently usable) blender → fbx → fbx2gltf → glTF workflow
The glTF files:
[TransportRobot_a-02_tris_defom_bones_noleaf_out.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3539438/TransportRobot_a-02_tris_defom_bones_noleaf_out.zip)

![gltf_viewer](https://user-images.githubusercontent.com/4047289/63666259-0b1b3180-c7cf-11e9-895c-72b42152bd1e.jpg)

![fbx_workflow](https://user-images.githubusercontent.com/4047289/63666280-1f5f2e80-c7cf-11e9-95b7-52740dc8f4a6.jpg)

**Comment by capnm** [comment]
Sketchfab Test https://skfb.ly/6MQZY

**Comment by julienduroure** [comment]
Closing, this is only a test case for #603 , discussion can continue on #603, not here
