### ISSUE TITLE
Traceback exporting classroom when animation export is enable

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#639]

**Comment by julienduroure** [comment]
Simplier blend file to reproduce the error:

An animated object is present in 2 differents scene

[object_2_scenes_animated.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3556834/object_2_scenes_animated.blend.zip)

**Comment by Taroslord** [comment]
Same problem here. Any progress?

I've prepared another example, too: https://github.com/KhronosGroup/glTF-Blender-IO/issues/323#issuecomment-707860938

**Comment by julienduroure** [comment]
Seems to be fixed in #1378

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
