### ISSUE TITLE
No tiling on roughness

### ISSUE THREAD

**Issue by Gutz-Pilz** [KhronosGroup/glTF-Blender-IO#642]
**Describe the bug**

**To Reproduce**
have made several materials  - all with roughness
but tiling applied to roughness wont be exported!

heres my initial Blen Material Setup 
![2019-08-30 21_31_27-Blender](https://user-images.githubusercontent.com/3322071/64047145-7bbea700-cb5d-11e9-9321-60ab5662c296.png)

**Expected behavior**
Albedo and Normal are tiled.
In my logic Roughness should also be tiled 10x - but it isnt...
even if i make a separate node for the roughness it wont work

![grafik](https://user-images.githubusercontent.com/3322071/64047174-9c86fc80-cb5d-11e9-97da-e3c242b4cc6c.png)

**Screenshots**

**.blend file/ .gltf**
[roughnesTilingIssue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3561272/roughnesTilingIssue.zip)

**Version**
 - OS: doesnt matter...
 - Blender Version 2.80

**Comment by julienduroure** [comment]
@Gutz-Pilz You didn't provide the texture images. Can you please packed them into blend file or zip them and upload here? Thanks

**Comment by Gutz-Pilz** [comment]
@julienduroure my bad
[roughnesTilingIssue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3562185/roughnesTilingIssue.zip)
