### ISSUE TITLE
Blender 2.81 release

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#645]
- [x] Update Release notes: https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Add-ons
- [x] Update doc
- [x] Check T69857 and remove workaround if fixed
- [x] Set Always sample animation default to True
- [x] Change version to 1.0.0

For info, here are current milestones :

Release date for 2.81 is currently set to 14 November 2019
Cut-off date (major changes and features in by) 13 September 2019
Stabilizing branch creation 1 October 2019
Master branch will be open from then on, i.o.w. no freeze while 2.81 is being stabilized

**Comment by julienduroure** [comment]
Added a check on status of blender bug https://developer.blender.org/T69857
Remove commit 51ee88f1af6753abccf89f0a6c83482bdde7d70a if blender bug is solved

**Comment by julienduroure** [comment]
Release note are up to date (sept. 19)

**Comment by julienduroure** [comment]
Is someone here have time to update documentation?
@donmccurdy @emackey @pjoe @scurest

**Comment by emackey** [comment]
What's needed on doc?  New screenshots of texture transform nodes, I know.  Anything else?

**Comment by julienduroure** [comment]
Merging animation for example.
Here is the current release note, listing all features/fixes (all of these don't need doc update) : https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Add-ons

**Comment by scurest** [comment]
Umm, I tried writing a little bit on the Animation -> NLA Strips option. Is that kind of what you wanted?

[Diff](https://github.com/KhronosGroup/glTF-Blender-IO/compare/master...scurest:nla-strip-anim-docs?expand=1)  
[Rendered](https://github.com/scurest/glTF-Blender-IO/blob/887124a75567a34c380273d960334e5d69cf48d9/docs/blender_docs/io_scene_gltf2.rst#animation)

**Comment by julienduroure** [comment]
Seems we are ready for 2.81 :)
