### ISSUE TITLE
Discussion: 1.0.0 version

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#649]
See this commit:
https://developer.blender.org/rBA53aec1ccff1b7e6356836a29b36115b475f0c3d2#change-gcpnsXYYwN6d

Be carefull, we need to include some tests on blender version to keep compatibility with 2.79 version .... And this will not work anymore with current stable 2.80

**Comment by emackey** [comment]
If we have strong reason to drop support for 2.79 sooner than planned, we can open that discussion with Khronos and probably reach agreement without too much trouble.

My own recommendation would be, when the time comes, to make a Git branch & tag for the last known version of this addon to support both 2.79x stable and 2.80 stable, and call that our final release of the addon for those versions.  The `master` branch could then let go of both of those versions and move to 2.81 only, which would include reducing the test suite to target 2.81 exclusively.

A couple of good effects would come from this:  We could clean up some code for "double-sided" support that supports radically different APIs in 2.79 vs 2.80.  Also, all of the export-only samples in the test suite are Blender 2.79 projects, we don't have any way currently to include 2.80-specific Blender projects in there without breaking the 2.79 tests.  And yes, it would mean that the 2.80 conversion script could finally be retired, as master itself would be permanently converted to 2.81-specific source code.

The downside is that any remaining 2.79 users would have to either continue using the final version of the addon for that version, or upgrade to a newer Blender.  But this is already true for all of Blender's other features as well.  It's basically inevitable, it's just a question of timing.  And if we're being forced to drop 2.80 compatibility from master, it might make sense to let go of 2.79 compatibility at the same time.

**Comment by emackey** [comment]
We may want to bump the version number to `1.0.0` prior to dropping support for 2.80 and 2.79.

This was last discussed in https://github.com/KhronosGroup/glTF-Blender-IO/pull/421#issuecomment-483350462, but at the time the addon didn't have a stable release yet.  Perhaps we can agree it's ready for `1.0.0` now?

**Comment by julienduroure** [comment]
I think this is too early to drop 2.79
I think we have to wait (at least) release of 2.81

For 1.0.0, I think we have to merge #653, #637 and a first round of performance on bone animation export before bump to 1.0.0

**Comment by julienduroure** [comment]
Change is now committed, keeping this ticket open to talk about versioning and blender 2.79 support dropping

**Comment by julienduroure** [comment]
Hi all,
Any news on testing #653 , #637 and #664 ?
Deadline for freezing new features for v2.81 is coming, and I really want these to be included (if tests are OK).
Maybe #653 and #664 can go after feature freeze as they are perf / fix. But #637 is more a new feature.

@donmccurdy ?

**Comment by emackey** [comment]
@julienduroure I don't have enough experience with anim/skins to review these, and it seems like Don may be swamped at work.  If you feel these are all stable, maybe merge them all in now, so that other users have time to test and report bugs before the 2.81 release.  Worst case scenario we could back one out if users find serious problems prior to release.

**Comment by julienduroure** [comment]
Ok, it's maybe time to change to 1.0.0
What do you think about that? 
@donmccurdy @emackey

**Comment by emackey** [comment]
Sounds good to me.  Will that make it in time for 2.81?

**Comment by julienduroure** [comment]
We are still in time.
Here is the current milestone plan : https://developer.blender.org/project/view/88/

**Comment by emackey** [comment]
Let's do it.

**Comment by julienduroure** [comment]
Last question before moving to v1.0.0: Setting "always sample animation" on by default?

**Comment by emackey** [comment]
Ouch.  I'm not using the animation system, so I'll ask for @donmccurdy's recommendation.  But generally this feels like it's increasing the output size to cover up some export issues.  Maybe the exporter should get better at recognizing when it can't correctly export un-sampled animations?  But I'm OK if this is a needed quick-fix for 2.81.

**Comment by donmccurdy** [comment]
Heh I'm pretty late on the reply and this is already done, it looks like, but yes — I think enabling it by default is probably the right call for now.

> Maybe the exporter should get better at recognizing when it can't correctly export un-sampled animations? 

Maybe. My hunch is that this could be quite difficult, but PRs improving our un-sampled export would certainly be welcome.

Moreover, output size is no less important even in the cases where sampling is (and always will be) necessary, like for models using IK constraints. There are already tools like gltfpack that can resample animation while minimizing effect on the animation curve (e.g. removing redundant keyframes). Perhaps basic resampling could be added directly to this exporter at some point, to be applied after Blender's own sampling.
