### ISSUE TITLE
Geometry huge compared to exporter

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/glTF-Blender-IO#65]
Please see the attached zip which contains a .blender with textures, and two folders containing the exported gltf: 1) via the IO plugin (with materials coming through) and 2) via the Exporter plugin (no materials e.g. without the cycle nodes)

The geometry or maybe some root scaling of the IO export is off - menorah looks huge! :)

[menorah-example.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2556025/menorah-example.zip)

**Comment by UX3D-schmithuesen** [comment]
Checking today with the most recent `Blender 2.80` beta, there seems to be no difference in the dimensions of the mesh so I would call this issue closed. There is still some issue with the skeleton, might be related to #75 and I noticed that the export just fails in `Blender 2.79` so I created #115.
