### ISSUE TITLE
Armature Export glTF Issues (Blender 2.80)

### ISSUE THREAD

**Issue by MaxKriegerVG** [KhronosGroup/glTF-Blender-IO#650]
Hi,

Saw that there were a few reports of this already, but I'm also experiencing issues wrt exporting animations with armatures to glTF format from Blender 2.80.

I've attached an FBX export to demonstrate that the animation from this .blend file is exporting properly. However, when I export glTF (in .glb format) and then re-import into Blender, model/bone location is all over the place. (note that I've tried various export configurations - this looks to have to do with skinning, which has also been reported in the issues section here several times).

First is original, second is re-import.

![image](https://user-images.githubusercontent.com/34134756/64213228-24c91280-ce7a-11e9-8b15-b57ded3c71d8.png)

![image](https://user-images.githubusercontent.com/34134756/64213238-2db9e400-ce7a-11e9-824b-36f776f0af8d.png)

I've attached the aforementioned FBX, the original .blend, as well as the .glb export file, so that you can look at all three. Note that this is not my model, it's a [Creative Commons model from Sketchfab](https://sketchfab.com/3d-models/illusion-of-the-future-aibo-ers-type-110-c7e78f0320294da5937da6322fce3bdf) that I'm trying to manually export due to the Sketchfab glTF auto-export not properly exporting the animation data.

[aibo_fbx.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3571899/aibo_fbx.zip)

[aibo_blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3571901/aibo_blend.zip)

[aibo_glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3571914/aibo_glb.zip)

**Comment by julienduroure** [comment]
Seems #653 Solves the issue.
Here is the generated glb with #653 applied: 
[aibo110.4.glb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3576309/aibo110.4.glb.zip)

**Comment by julienduroure** [comment]
Fixed now
