### ISSUE TITLE
Animated model import/export creates weird animations

### ISSUE THREAD

**Issue by jee7** [KhronosGroup/glTF-Blender-IO#652]
**Describe the bug**
Importing a GLB file with existing animations creates new and weird animations instead of the existing ones.

**To Reproduce**
1. Take the Soldier.glb from the Three.js repo.
https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Soldier.glb
[Soldier.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3575101/Soldier.zip)

2. Open it in this GLTF Viewer (https://gltf-viewer.donmccurdy.com/), see 4 animations: TPose, Idle, Walk and Run.
![image](https://user-images.githubusercontent.com/3455815/64266289-07a94800-cf3d-11e9-8479-4a215aa61a8e.png)

3. Import it to Blender 2.80 and look at the NLA tracks, there are tons of weirdly named animations instead:
![image](https://user-images.githubusercontent.com/3455815/64266346-21e32600-cf3d-11e9-8bd8-ae3bf5fd523d.png)

4. Export it from Blender (without changing anything) and look at it in GLTF Viewer. There are then those weirdly named animations instead of the prior TPose, Idle, Walk and Run.
![image](https://user-images.githubusercontent.com/3455815/64266464-4e973d80-cf3d-11e9-8836-bc0431c97fb8.png)

**Files**
[Soldier.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3575101/Soldier.zip)

**Version**
 - OS: Windows 8.1 Pro
 - Blender Version 2.80 (sub 75)

**Comment by julienduroure** [comment]
First analysis : There is lots of animation because some animation are multi-object animations.
glTF animations can have multiple targets, where blender animation can be only on 1 object (object or armature).

Next analysis steps:
- Why some node created has empty, where names seems to indicate that this is joint (this is why we have some multi-object animations)
- #655 can help re-exporting with right number of animations (this will also need #637 to work)

**Comment by julienduroure** [comment]
Found the root cause:

> "skins": [
    {
      "inverseBindMatrices": 424,
      "joints": [
        3,
        4,
        5,
        6,
        7,
        8,
        10,
 [.....]
        66
      ],
      "name": "vanguard_Mesh",
      "skeleton": 3
    },
    {
      "inverseBindMatrices": 560,
      "joints": [
        7,
        8
      ],
      "name": "vanguard_visor",
      "skeleton": 3
    }

Currently, multiple armature sharing some bones are not supported.
Plus, I'm not sure the status of "skeleton" property, that currently is not part of joints list. @donmccurdy : I know that there is a lot of discussion about that, but not sure if something is decided about that ?

**Comment by julienduroure** [comment]
Probably link to #331 discussion

**Comment by scurest** [comment]
This is working. The exporter creates the same four animations and they work correctly in the viewer.

![bab](https://user-images.githubusercontent.com/11024420/75127292-ec193180-5683-11ea-96e8-add51bbb144a.png)

**Comment by jee7** [comment]
@scurest How did you manage to get this? I tried with Blender 2.82 now and what I'm getting is:
1) The animations shown in the NLA editor still seem weird.
![image](https://user-images.githubusercontent.com/3455815/75153993-5ded8b80-5715-11ea-8f32-2af66b97439e.png)

2) After export the names are correct, yes.
![image](https://user-images.githubusercontent.com/3455815/75154028-6d6cd480-5715-11ea-9025-8ecd7495b4e2.png)

3) But the animations I'm getting in the viewer are broken. I think all the animations play the Idle animation, but clip it according to the time. For example, the Run animation is 0.7 seconds, so it plays the Idle animation for that time.
![image](https://user-images.githubusercontent.com/3455815/75154106-9c834600-5715-11ea-9f04-59038b91bd48.png)

**Comment by scurest** [comment]
@jee7 You need to use the master branch of this repo. In particular to fix "all animations are clipped versions of Idle" you'll need the fix for #942 which went in, uhhh, 19 hours ago. Might see if its in the [Blender nightlies](https://builder.blender.org/download/) yet.

**Comment by jee7** [comment]
Ah, I see. Okay. Will try later with newer Blender versions then. Thanks.

**Comment by CrezyDud** [comment]
buggd again :(

**Comment by julienduroure** [comment]
@CrezyDud You are commenting a quite old report already solved.
If you have some issue, please open a new ticket with all requested information to be able to understand and reproduce your issue, including a test file.
