### ISSUE TITLE
Actions created in the shapekey editor are not exported when pushed down to the NLA

### ISSUE THREAD

**Issue by elbobo** [KhronosGroup/glTF-Blender-IO#656]
Hi,

I understand that in order to export a model with multiple animations, the animations must be created in the action editor, saved and pushed down (or stashed) to the NLA.

This process works fine if the animation is loc rot scale or armature driven. However, if your animation is made from shapekeys, these keyframes do not appear in the action editor and can only be seen in the shapekey editor. When they are pushed down to an NLA strip from the shapekey editor however, they are not exported.

Some investigations suggest that if there are action editor actions pushed down, the shapekey ones are also then exported although I do not seem to be able to do this consistently.

Please find attached 2 .blend files (and their .glb exports) that show the difference. "Movementsandshapes" show how the shapekey actions are exported when combined with actions from the action editor. "Shapesonly" shows only shapekey actions and the export does not contain animations.

What I would expect is that all pushed down strips would be exported, regardless of where they are created. But maybe I shouldn't expect that? Is there another way to achieve what I am trying to do? Is there a way, for example, to move actions created in the shapekey editor to the action editor?

Any advice much appreciated.

MacOS
 - Blender 2.8

[shapesonly.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3576358/shapesonly.zip)
[movementsandshapes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3576359/movementsandshapes.zip)

**Comment by julienduroure** [comment]
Hello,
Thanks for your report. Can you please test with a daily build of blender (https://builder.blender.org/download/), because it seems that this is already solved in a version > official 2.80

If I missed something, don't hesitate to comment, we will reopen this ticket

**Comment by elbobo** [comment]
That solves it! Fantastic, thank you very much.
