### ISSUE TITLE
Scene - Root Nodes

### ISSUE THREAD

**Issue by hodasemi** [KhronosGroup/glTF-Blender-IO#666]
As stated in the standard (https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#scenes), the scene should contain indices of all root nodes. 
But in my case there is just the total amount of nodes listed. Since the skin has no skeleton I see no way to obtain root nodes.

[blender_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3589494/blender_test.zip)

**Comment by julienduroure** [comment]
Hello,
Your gltf file does not contains all nodes in your scene:
![image](https://user-images.githubusercontent.com/1696020/64519374-49970d00-d2f4-11e9-9ed9-552cc67c713f.png)

--> The root is node 16

If you are talking about joints data, skeleton property is currently not mandatory in glTF2.0 specification.
With scene node hierarchy, you can be able to have joint/bone hierarchy too.
