### ISSUE TITLE
Animation problems when using armatures with equal bone names (Armature copies)

### ISSUE THREAD

**Issue by Taroslord** [KhronosGroup/glTF-Blender-IO#668]
**Describe the bug**
I've created an armature for an animation, that have to be exported to glTF. The armature is animated. The whole scene has several copies of the animated armature.  In Blender every object copy with its animation will be played fine.

As soon as I export my scene to glTF only the first Armature object will be animated. The other objects do nothing, instead of playing their animations.

I've figured out the reason. The problem are the Bone names. As soon as equal bone names will be used multiple times, only the first found Armature animation will be played.

Hierarchy Example that results in problems:
Armature->Bone->Bone.001 (All is fine here, this armature will be played)
Armature.001->Bone->Bone.001 (This is a copy of the 1st armature and will not be played, because the bone names in the hierarchy are the same as the original.

Current workaround is to rename the bone names manually. This example works e.g.:
Armature.001->Bone1->Bone1.001 (The bones are renamed and all animations will be played now.)

I use the following website to test my exported glTF files: https://gltf-viewer.donmccurdy.com/
I've prepared an example .blend file and some glTF examples for you to check my problem. 

**To Reproduce**
Steps to reproduce the behavior. Please use my .blend file:
1. Select both cubes, including the armatures.
2. Export them to glTF (.glb).
3. Use the mentioned glTF preview website to proof the export: Only the first animated cube object will be played. The copy doesn't work. (Shot 1 below)

4. Go back to Blender and change the Bone names of the 2nd cube (cube.001). (Shot 2 below)
5. Export both cubes again now, including the armatures.
6. Result in the glTF player: All works fine and both animations play.

**Expected behavior**
What I expect for the future:
When exporting multiple armatures with equal bone names (This happen every time when you copy armatures in Blender!), then the glTF exporter should be able to rename the bones automatically to individual bone names or does something else to fix this problem.

**Screenshots**
Shot 1:
https://www.christoph-werner.de/wp-content/uploads/2019/09/glTF_problem01.jpg

Shot 2:
https://www.christoph-werner.de/wp-content/uploads/2019/09/glTF_problem02.jpg

**.blend file/ .gltf**
Here is the zipped folder containing a .blend file and the exported glTF files.
https://drive.google.com/file/d/1bR2nGo1rEU4IYKYDYRZj3r5OImOh4RV9/view?usp=sharing

**Version**
Blender version: 2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: f6cb5f54494e, type: build date: 2019-07-29, 09:44 AM
Platform: Windows

**Comment by julienduroure** [comment]
Seems the bug come not from Blender.
Reimporting glb in Blender --> both armatures are animated
Import in https://sandbox.babylonjs.com/ --> Both armatures are animated.

@donmccurdy: Seems the bug come from Three.js

**Comment by Taroslord** [comment]
But the same scene will not be played in my mentioned viewer here:
https://gltf-viewer.donmccurdy.com/
There it works only if the bones has different names.

In your viewer it is played. So can the bug be maybe in the viewer I'm using and not in Blender?

Thank you
Chris

**Comment by julienduroure** [comment]
> In your viewer it is played. So can the bug be maybe in the viewer I'm using and not in Blender?

Yes, this is what I was saying: threejs is the engine used to display gltf files in viewer you used. Sorry if it was not clear.

**Comment by Taroslord** [comment]
No problem. Thank you.
