### ISSUE TITLE
Import: multi-object animations

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#671]
I was trying out the mult-object animation stuff in the importer and assuming I understand it correctly, I found some issues.

### Track names are not unique per animations

Here's a [test file](https://github.com/KhronosGroup/glTF-Blender-IO/files/3603573/MultObjAnim.zip). It's just BoxAnimated from the sample model with three copies of the same animation (which animates two objects); two are named "A", and one is unnamed. It imports like this

![bl](https://user-images.githubusercontent.com/11024420/64750166-b15c7c00-d4dd-11e9-91f7-4502be984edd.png)

So the tracks from the two animations named "A" have the same name and there's no way to tell them apart. On the other hand, the tracks from the unnamed animation are named with the action name, so there's no way to tell that they're part of the same animation.

So I think there should be a preprocessing pass that picks a unique name for each animation in the glTF that can be used as the track name every time it's actions get pushed.

### Actions for different objects get pushed onto an object's NLA stack

Again, in the above image, every object has the actions for every _other_ object pushed onto it, not just it's own. 

### The wrong actions get restored

The importer restores the action from the bottom-most (first) track after importing. In this case, because of the above point, it means that the purple box (inner_box) plays the blue box's action (A_Node) instead of it's own (A_inner_box). It should look like this, but it currently doesn't

![](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/screenshot/screenshot.gif)

Other sample animations suffer similarly (ex. VC).

Restoring the first track's action might also wind up playing actions from two different animations if, say, not all objects are animated by every animation.

So I think the right thing to do is to pick one animation (say the first one) and always restore the actions needed to play that one.

### No way to play animations?

Is there a way to actually _play_ an animation encoded as a set of identically-named tracks in Blender? Short of manually selecting them all the right actions? If not, could the addon add a widget somewhere that would do that automatically for you?

**Comment by julienduroure** [comment]
Hello,

- [ ] 1: Track names are not unique per animations: Great enhancement ideas. Added on my TODO list
- [ ] 2: Actions for different objects get pushed onto an object's NLA stack : Clearly a bug
- [ ] 3: The wrong actions get restored: consequence of bug 2. Will be solved after solving 2., and can be enhanced by 4.
- [ ] 4: restore the first glTF animation: welcome enhancement that will clarify things 
- [ ] 5: Do think there is any simple way to do it by default in Blender. An addon can help. Not sure this should be included within the importer/exporter, but in a first step, I can create a separate addon.

Thanks for pointing these stuff out!

**Comment by scurest** [comment]
Let me know if I can help with any of it.
