### ISSUE TITLE
2.81 now has a Vertex Color node

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#675]

**Comment by scurest** [comment]
Does it supply white (1,1,1,1) when there aren't vertex colors?

**Comment by julienduroure** [comment]
Yes, it does.
2.80 does it too

This is only a new node in tree to retrieve data
![image](https://user-images.githubusercontent.com/1696020/64903413-811d0500-d6b8-11e9-9ad0-7d88d62c8582.png)

**Comment by scurest** [comment]
My Blender gives black when the vertex color layer doesn't exist. What version do you have? I have 2.80.75.

![cube](https://user-images.githubusercontent.com/11024420/64903970-e6a4cd80-d687-11e9-8bf1-af96d64cd1f9.png)

**Comment by julienduroure** [comment]
Ah, ok, you mean accessing a vertex layer that doesn't eixts -> you're right, it's black. But seams logic: no data --> 0.0

(I thought you mean accessing vertex color for vertices that you didn't paint, on a existing layer)

**Comment by scurest** [comment]
The alpha socket could help #355, but it's too bad it's still black :/ If it would give white you could write a material that was indifferent to whether the polys it's applied to have color. The importer wouldn't have to split one glTF material into multiple Blender materials (`material` and `material_COLOR_0`). Everyone's used white as the default vertex color forever, including Blender when you create a new vertex color layer, so it's annoying it's different in a shader node.

I wonder if there's a chance they'd change it before 2.81.
