### ISSUE TITLE
Always sample animations crashes app

### ISSUE THREAD

**Issue by funwithtriangles** [KhronosGroup/glTF-Blender-IO#679]
**Describe the bug**
Tried to export with a model using lots of animations (one being quite long)

**To Reproduce**
1. Open jboy.blend
2. Export glTF using "always sample animation"

**Expected behavior**
Should export without a long delay. Instead it hangs for a long time.

**glTF**
[jboy.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3628358/jboy.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.80 (latest build)

**Comment by julienduroure** [comment]
Please test with latest build. You are using a version that is 3 months old, when 2.80 was not yet release.
Application don't crash with up to date addon + blender.

More general info : Bad idea in Blender to have not default transformation on armature object, and on deformed mesh.
Still have an issue with that to export. Will investigate, but maybe applying transforms will solve it

**Comment by funwithtriangles** [comment]
Hey, thanks for getting back so quick! 

So I just downloaded the latest version of Blender and it is still crashing for me. I'm assuming this means I've got the latest version of the addon too?

**Comment by julienduroure** [comment]
Please send a screenshot of your crash traceback and screenshot of your splashscreen

**Comment by funwithtriangles** [comment]
Latest build (2.81) fixed the crash, thanks!
