### ISSUE TITLE
After merge of PR #48, export of imported file fails

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#68]
After merge of PR #48 , exporting file that are an imported gltf file is broken.
Failed because of MULTIPLY nodes created for take into account the Base Color Factor.

**Comment by UX3D-hanselmann** [comment]
Can you share the exact nodes configuration you are using, or a .blend/.gltf file for this, please?

**Comment by julienduroure** [comment]
In this file: 
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BoxVertexColors/glTF/BoxVertexColors.gltf

baseColorFactor is not exported correctly
(baseColorFactor is Color1 of MULTIPLY node)

**Comment by UX3D-becher** [comment]
Are there any other cases where such 'advanced' nodes are used by the importer?
