### ISSUE TITLE
animation export: input accessor and output accessor have different count values

### ISSUE THREAD

**Issue by infobeisel** [KhronosGroup/glTF-Blender-IO#688]
When exporting an animation (with "Always Sample Animations" **disabled**) the resulting gltf file contains more data values than keyframe values, i.e., if there is only two keyframes and the only property that changes is the x axis translation, the accessor describing the keyframes has a count value of 2 and the accessor describing the actual translation keyframedata has a count value of 6:
`
{
            "bufferView" : 4,
            "componentType" : 5126,
            "count" : 2,
            "max" : [
                1.6666666666666667
            ],
            "min" : [
                0.041666666666666664
            ],
            "type" : "SCALAR"
        },
        {
            "bufferView" : 5,
            "componentType" : 5126,
            "count" : 6,
            "type" : "VEC3"
        },
`
As far as i understand these count values need to be the same as they are in [this ](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_006_SimpleAnimation.md#the-accessor-objects-for-the-animation-data) example, so for each keyframe entry there is a translation vector.

I also think, but this is just a guess, that the data itself is not correct: in the example above, the exported buffer contains a zero vector , then the vector of the first keyframe, again a zero vector, and then the vector of the second frame (and then potentially another zero vector). the data apparently is not interleaved, as the corresponding bufferView does not have a byteStride property.

... Maybe the float count is written instead of the vector count (2 vectors times 3 components = 6) ? 
When exporting with "Always Sample Animations" **enabled**, it seems to write correct count values (everywhere just the number of frames of the animation).

1. animate the default cube to just move along the x axis, storing 2 keyframes
2. export to .gltf with "Always Sample Animations" disabled
3. open the gltf file, find the Accessors and see data similar to the description above.

**Expected behavior**
i would expect the exporter to export count values of 2 everywhere, like this:
`
{
            "bufferView" : 4,
            "componentType" : 5126,
            "count" : 2,
            "max" : [
                1.6666666666666667
            ],
            "min" : [
                0.041666666666666664
            ],
            "type" : "SCALAR"
        },
        {
            "bufferView" : 5,
            "componentType" : 5126,
            "count" : 2,
            "type" : "VEC3"
        },
`

windows, blender 2.8 , exporter from this github, commit b7f96f95b301d6e42413e40c097a433288e87958

**Comment by julienduroure** [comment]
Hello,

By default, blender use bezier intepolation / CUBICSPLINE in gltf.
So animation in/out tangent are also exported. That's why we have 3 more times output than input keyframes.
See  specification:

> "CUBICSPLINE" The animation's interpolation is computed using a cubic spline with specified tangents. The number of output elements must equal three times the number of input elements. For each input element, the output stores three elements, an in-tangent, a spline vertex, and an out-tangent. There must be at least two keyframes when using this interpolation.

**Comment by infobeisel** [comment]
thank you
