### ISSUE TITLE
Detect automatically if "always sample animation" need to be used

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#691]
Some checks that could be done:

- if some deformation bones are not animated and non deformation bones are animated
- If some deformation bones have constraints

**Comment by scurest** [comment]
Euler rotations?

**Comment by julienduroure** [comment]
Not sure we need to keep this ticket open, as sampling is default now, and we don't have any concerns about bad detection of force sampling when user disable it.
