### ISSUE TITLE
Manage animation by evaluation time

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#692]
Cf https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2692489/animationTest.blend.zip

**Comment by kungfooman** [comment]
This seems to be the continuation of this closed issue: https://github.com/KhronosGroup/glTF-Blender-IO/issues/176

Animating e.g. a bunch of cubes along a curve would be highly dynamic but it doesn't work so far.

Linking to this blenderartists post: https://blenderartists.org/t/export-bezier-curve-animation-as-gltf-and-or-fbx/1151423/4

I am running into this issue aswell, I just want to make an animation using Blender's `Object Constraint` called `Follow Path`:

![curvecubes](https://user-images.githubusercontent.com/5236548/129526285-ffa6d371-0b78-4e02-81e4-950f475870fd.gif)

Blender file: 
[curvecubes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6990453/curvecubes.zip)

Exporting this results in: 
![image](https://user-images.githubusercontent.com/5236548/129526503-78cc0201-4698-4de7-af5b-f185ed43ddc5.png)

Will this "curve animation workflow" ever be supported by glTF or is this just about meshes?

**Comment by julienduroure** [comment]
@kungfooman glTF specification do not support curves, only meshes. So there is no easy way to export your example without any conversion.
As described in blenderartist, you may have to manually bake to a list of shapekeys to be able to export, or bake manually animation if meshes are not deformed.
I still have to have a look on your example file, to avoid this traceback
