### ISSUE TITLE
Gltf2 Import Error Aquarius

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#698]
**Describe the bug**

Animated model is broken.

**To Reproduce**
1. Go to https://sketchfab.com/3d-models/aquarius-astellia-622bde32272d4545b89cc09113ca7439
2. Click on download fbx
3. Open in Maya 
4. Use maya2gltf develop branch https://github.com/WonderMediaProductions/Maya2glTF/commit/523fd6d1148a99dc4b6e732d10c73a44f6071e97
5. Export gltf2  with 0.01 scaling and -glb
3. Import gltf2 animation
4. Animations are broken.

**Expected behavior**
Correct animations.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/32321/65824253-b67a3480-e21a-11e9-8f70-69cbd0bd8f60.PNG)

![Capture2](https://user-images.githubusercontent.com/32321/65824262-d4479980-e21a-11e9-8efc-c39b6e7863b0.PNG)

**.blend file/ .gltf**

[aquarius-astellia.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3666195/aquarius-astellia.zip)

[export.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3666235/export.gltf.zip)

**Version**
 - OS: Windows
 - Blender Version 2.8.0
 - gltf2-io e5e86a87f6cc8fe736c5918fc8acc60fc2394d37
 - maya2gltf develop branch https://github.com/WonderMediaProductions/Maya2glTF/commit/523fd6d1148a99dc4b6e732d10c73a44f6071e97

**Comment by julienduroure** [comment]
Link to the fact that a node B_root, has some children that are bones (Bone_Wea and Dummy_Wea), and some not (Bip001). Bip001 is animated, but because all bones are in an armature, the entire armature is moved because the parent of armature (Bip001) is animated
