### ISSUE TITLE
Gltf2 Import Error Kera

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#699]
**Describe the bug**

Animated model is broken.

**To Reproduce**
1. Go to https://sketchfab.com/3d-models/kera-the-archer-desert-fox-animated-2f1f09ce84da452b90939b54e6bc2c0a
2. Click on download gltf
3. Import gltf2 animation
4. Animations are broken.

**Expected behavior**
Correct animations.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/32321/65824296-5c2da380-e21b-11e9-93e7-649688f7834b.PNG)

![Capture2](https://user-images.githubusercontent.com/32321/65824302-7c5d6280-e21b-11e9-975a-49235f71c280.PNG)

**.blend file/ .gltf**

[kera-the-archer-desert-fox-animated.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3666198/kera-the-archer-desert-fox-animated.zip)

**Version**
 - OS: Windows
 - Blender Version 2.8.0
 - gltf2-io e5e86a87f6cc8fe736c5918fc8acc60fc2394d37

**Comment by julienduroure** [comment]
Seems to be linked to object parenting to bones
Body animation seems to be OK, only props have problems
(Still need enhancement about bone scale)
