### ISSUE TITLE
Exporter: KHR extensions, add hooks for Vendor extensions

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-IO#7]
- [x] KHR_lights_punctual
- [x] KHR_materials_unlit
- [x] KHR_texture_transform
- [x] Refactor to have hooks/callbacks

**Comment by donmccurdy** [comment]
Which new `KHR_` extensions do we think should be included here? +1 for KHR_texture_transform and KHR_lights_punctual from me. Others (draco, blending, technique_webgl) might be nice to have (if finished in time) but would require more discussion first.

**Comment by UX3D-nopper** [comment]
KHR_texture_transform and KHR_lights_punctual will be in. Also, we want to refactor the code, that it is easier to "hook" into the code, that future extensions can be easier implemented. It has to be avoided, that one has to change stabel code.

**Comment by emackey** [comment]
Will vendors be able to add their own Blender plugins, that somehow communicate data to export into the glTF's extensions objects?  Or would every supported glTF extension need to be included here in this repo?

**Comment by UX3D-nopper** [comment]
It has to be added to this repo, but they should be in their own packag and/or file.

**Comment by UX3D-becher** [comment]
Extensions can easily be added to the exporter by implementing the __gather_extensions function in the appropriate module. 
For example the KHR_unlit extensions for materials is implemented in __gather_extensions of the gather_material module as follows
```python
def __gather_extensions(blender_material, export_settings):
    extensions = {}
    if blender_material.use_shadeless:
        extensions["KHR_materials_unlit"] = {}
    return extensions if extensions else None
```
Return ``None`` instead of an empty dict to avoid empty dicts in the exported glTF file.
