### ISSUE TITLE
Gltf2 Import Error Bench

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#702]
**Describe the bug**

Animated model is broken.

**To Reproduce**
1. Go to https://sketchfab.com/3d-models/holotech-bench-67ff23c44c4c42f089917904981377fc#download
2. Click on download gltf
3. Import gltf2 animation
4. Animations are broken.

**Expected behavior**
Correct animations.

**Screenshots**

[Hid bones temporarily] 

![Capture](https://user-images.githubusercontent.com/32321/65837099-71044880-e2a8-11e9-86b3-786eca621c75.PNG)
![Capture2](https://user-images.githubusercontent.com/32321/65837104-7f526480-e2a8-11e9-9ff6-8ca1c511bc75.PNG)

**.blend file/ .gltf**

See sketchfab site.

**Version**
 - OS: Windows
 - Blender Version 2.8.0
 - gltf2-io e5e86a87f6cc8fe736c5918fc8acc60fc2394d37

**Comment by julienduroure** [comment]
Not sure there is a bug here. But scale is huge, some nodes have 100 / 100 / 100
Set scale of 0.001 / 0.001 / 0.001 on root node, and animation seems to be OK.
Can you please check it?

**Comment by fire** [comment]
It's too difficult to work with, I'll find another test asset.
