### ISSUE TITLE
Gltf2 Import Error Witch

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#703]
**Describe the bug**

Animated model is broken.

**To Reproduce**
1. Go to  https://sketchfab.com/3d-models/witchapprentice-c015ab905a26410092db35c946a68032
2. Click on download fbx
3. Open in Maya 
4. Use maya2gltf develop branch https://github.com/WonderMediaProductions/Maya2glTF/commit/523fd6d1148a99dc4b6e732d10c73a44f6071e97
5. Export gltf2  with 0.01 scaling and -glb
3. Import gltf2 animation
4. Animations are broken.

**Expected behavior**
Correct animations.

**Screenshots**

![Capture2](https://user-images.githubusercontent.com/32321/65837259-0bb15700-e2aa-11e9-8d8c-992e1bdf24a0.PNG)
![Capture](https://user-images.githubusercontent.com/32321/65837260-0bb15700-e2aa-11e9-8bd7-a6d52138ed26.PNG)

**.blend file/ .gltf**

[witchapprentice.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3667885/witchapprentice.zip)

[witchapprentice.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3667887/witchapprentice.blend.zip)

**Version**
 - OS: Windows
 - Blender Version 2.8.0
 - gltf2-io e5e86a87f6cc8fe736c5918fc8acc60fc2394d37
 - maya2gltf develop branch https://github.com/WonderMediaProductions/Maya2glTF/commit/523fd6d1148a99dc4b6e732d10c73a44f6071e97

**Comment by julienduroure** [comment]
Seems to be OK in pose mode, maybe linked to animation only

**Comment by julienduroure** [comment]
Has also same problem than #698 with some node that animate all armature
