### ISSUE TITLE
Gltf2 Import Error Kgirls

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#704]
**Describe the bug**

Animation does not play correctly.

**To Reproduce**
1. Download gltf https://sketchfab.com/3d-models/kgirls01-d2f946f58a8040ae993cda70c97b302c#download
2. Import gltf in blender
3. Play animations

**Expected behavior**

Play the animation correctly.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/32321/65838302-aca60f00-e2b6-11e9-8d85-6a89171f5b58.PNG)

**.blend file/ .gltf**

[kgirls01.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3667996/kgirls01.zip)

[kgirls01.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3667998/kgirls01.blend.zip)

**Version**
 - Windows 10
 - Blender Version 2.8.0
 - gltf2 io e5e86a87f6cc8fe736c5918fc8acc60fc2394d37

**Additional context**

**Comment by julienduroure** [comment]
Hello,
Not sure to understand what exactly is wrong with this animation, as there is no big artefact (using latest blender build).
Please be more precise on what is wrong

**Comment by fire** [comment]
The model is shifted from the origin. It is under the origin.

**Comment by julienduroure** [comment]
Seems the root node is shifted

![Capture](https://user-images.githubusercontent.com/1696020/65855712-e67f2000-e35f-11e9-983a-519b31a8ef7b.PNG)

I don't know what viewer you are using, but I know some of them set camera view based on bounding box of the scene, so any shift is not viewable with these viewer.

(BTW, your glTF file has a very hude number of error in glTF-validator)
![image](https://user-images.githubusercontent.com/1696020/65855817-35c55080-e360-11e9-8393-ae0933a02e4c.png)

**Comment by fire** [comment]
I did not personally make this model, so feel free to close this issue if it's intractable.
