### ISSUE TITLE
Bone with "Local Location" unticked is exported incorrectly

### ISSUE THREAD

**Issue by rdb** [KhronosGroup/glTF-Blender-IO#705]
**Describe the bug**
When the "Local Location" checkbox for a bone is unticked, the bone is displayed in a different position in Blender.  However, this change is not reflected in the exported glTF file.  In fact, the checkbox seems to be entirely ignored, as the exported glTF file is identical no matter the state of this checkbox.

**To Reproduce**
Steps to reproduce the behavior: (or just grab the .zip file below)
1. Create a bone with some attached geometry and position it somewhere
2. Untick the Local Location checkbox
3. Export
4. Observe that the bone's position in the exported .gltf doesn't match the .blend file

**Expected behavior**
I expected the exporter to take the setting into account and match Blender's positioning behaviour.

**Screenshots**
<img src="https://user-images.githubusercontent.com/194842/65891613-1c92c300-e3a5-11e9-85a6-f4960d5e3c31.png" width="263" />

**.blend file/ .gltf**
[local_location.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3671859/local_location.zip)

**Version**
 - OS: Linux
 - Blender Version: 2.80

**Comment by julienduroure** [comment]
I confirm that this option is not yet implemented in exporter

**Comment by julienduroure** [comment]
Will be fixed by #1378

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
