### ISSUE TITLE
Always Sample Animations is Required

### ISSUE THREAD

**Issue by titansoftime** [KhronosGroup/glTF-Blender-IO#711]
So the animations now export correctly and look as expected! Hurrah! Very nice.

However this requires checking "Always Sample Animations" in the export options, which pretty much doubles to triples file size.

Since it is necessary (or is it in just some cases?), perhaps this should be defaulted to enabled?

I'm glad this is my only remaining issue with the exporter, but it is not exactly insignificant for web applications.

If needed here are my test files:
[TestFiles.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3682874/TestFiles.zip)

I have to mention that when using the old three.js setup with the .json files, my files size was about 400KB. The exported gltf is almost 1MB. The glb is 715KB. Perhaps the json file is smaller due to float precision limitation (I would export with a setting of 6). Not sure how that works with binary data though.

When I converted that json file to glb via the three2gltf workaround the file size ended up being a 400kb glb, which works great. I made sure this was not due to mergingVertices which only minimally affects this model.

If this is already known and being worked on, feel free to close.

**Comment by julienduroure** [comment]
This is something already known.
You can follow discussion here: #558
