### ISSUE TITLE
Set forward vector

### ISSUE THREAD

**Issue by Wahooney** [KhronosGroup/glTF-Blender-IO#712]
Being able to select the forward vector (without adding rotation to the matrices), would be helpful for engines that have unconventional forward vectors (ie. UE4s X-forward)

Thanks.

**Comment by julienduroure** [comment]
This is against glTF 2.0 specification:

> glTF uses a right-handed coordinate system, that is, the cross product of +X and +Y yields +Z. glTF defines +Y as up. The front of a glTF asset faces +Z.
