### ISSUE TITLE
Import even when extensions are not supported

### ISSUE THREAD

**Issue by schiette** [KhronosGroup/glTF-Blender-IO#716]
We usually have to work with GLTF files that have custom extensions in them. Right now, these have to be removed manually from the gltf file before the importer will import them.

Would it be possible to have an option 'ignore extensions' that would skip all these extensions on import?
[Example File With Extension.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3697861/Example.File.With.Extension.zip)

**Comment by julienduroure** [comment]
Your example file is not a valid glTF file, because specification says:

> All values in extensionsRequired must also exist in extensionsUsed

And this is not the case in the provided file

**Comment by schiette** [comment]
Agreed, but even when I added in the extensionsUsed, the file wouldn't import.

**Comment by donmccurdy** [comment]
I believe the importer is doing the correct thing in refusing to import models with unknown extensions in the `extensionsRequired` list. That list is, specifically, meant to indicate that the model cannot be correctly imported if the extension isn't recognized.

If you would like for the model to work correctly in these tools, you'll need to only include the extension in `extensionsUsed`, and design the extension for graceful fallback.

**Comment by schiette** [comment]
@donmccurdy  I understand your position, but unfortunately we don't have control over the authoring app. 

The fix is straightforward, but labor intensive (manually stripping out all extension sections in the gltf).

I'll try talking to the creators of the exporter, but I'm afraid it will yield little result.

**Comment by julienduroure** [comment]
Closing this ticket, as the addon is aligned with glTF2.0 specification requirements
