### ISSUE TITLE
Incorrect Rotation In Exported Animation

### ISSUE THREAD

**Issue by Ziflin** [KhronosGroup/glTF-Blender-IO#721]
The included example shows a simple animation of a small (pointed) "box" moving up, rotating, then moving down. However when exported as a glTF (.glb) there is visible rotation occurring on the small box as it moves up. This can be viewed in https://gltf-viewer.donmccurdy.com/ and event re-importing the file back into Blender. It's also occurring in my glTF importer.

The problem appears to be caused from setting the interpolation mode to Bezier (default in Blender). The exporter sets the interpolation mode to "CUBICSPLINE" and for some reason on the first few keys (where the rotation _value_ is actually <0,0,0,1>), the in/out _tangent values_ are non-zero.

If I change the keys to be Linear in Blender, this behavior does not occur.

**To Reproduce**
Steps to reproduce the behavior: [TestAnimation.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3703945/TestAnimation.zip)

(Using Blender 2.80 release)

1. Import the included TestAnimation.glb file into https://gltf-viewer.donmccurdy.com or re-export the included TestAnimation.blend file.
2. Play the SmallCubeAction and note the small cube rocks back as it translates up despite the rotation keys having no rotation in Blender.
3. Also note there is no weird rotation as the box translates back down.

**Expected behavior**
The small box should not have rotation as it translates up. It should look the same as it does when the box translates back down to its initial position matching the animation seen in the original Blender file (TestAnimation.blend).

**Comment by julienduroure** [comment]
Thanks for reporting, but this bug is already fixed in master.
You can test it downloading a current build on builder.blender.org
Note that "always sample animation" is on by default now. You will have to uncheck it, in "animation" tab of exporter option.

**Comment by Ziflin** [comment]
@julienduroure Great thanks! Sorry, I thought I'd searched for a previous bug about it.
