### ISSUE TITLE
GLTF - Morph Target Animation - import bug

### ISSUE THREAD

**Issue by Bug-Reaper** [KhronosGroup/glTF-Blender-IO#724]
**the bug**
Trying to import .gltf file with a complicated shape key lip sync animation.

The .gltf file imports the animation with keyframe data, but rather than importing the animation once on the parent node, the animation is duplicated several times and imported on each child mesh containing shape keys used in that animation.

TLDR: Complex shape key animations with multiple mesh targets seem to import improperly on from a .gltf file

**To Reproduce**
Import the .gltf files attached in the zip to this post.

**Expected behavior**
There should be one animation on the parent node which targets multiple meshes for shape key transformations.

**.blend file/ .gltf**
[goodGLTFSample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3710986/goodGLTFSample.zip)

**Version**
 - Arch Linux 5.3.1
 - Blender Version 2.8.0~~

**Comment by julienduroure** [comment]
Well ... Both your files have a huge number of errors ...
I don't know what exporter you used, but seems data you are trying to import in Blender are maybe not what you are thinking.

Please provide some more valid files if you still have errors with correct files.

Waiting these files, closing this ticket.

gltf file : 44 errors
![image](https://user-images.githubusercontent.com/1696020/66458532-4cac2700-ea73-11e9-9721-0930998e9d80.png)


glb file: 224 errors
![image](https://user-images.githubusercontent.com/1696020/66458602-6f3e4000-ea73-11e9-8f84-a1aeed351db5.png)

**Comment by Bug-Reaper** [comment]
Hey there, I was using the threejs GLTFExporter. I've been fixing some related bugs over in that [repo](https://github.com/mrdoob/three.js/issues/17579).

Anyway, I was able to generate a .gltf file which produces no errors.
[goodGLTFSample.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3710912/goodGLTFSample.zip)

There is a single animation on the root parent node. However when imported to blender, that animation is duplicated across the many child meshes targeted in that shape key animation.

![Screenshot_2019-10-10_00-00-01](https://user-images.githubusercontent.com/31227781/66546071-f8478c80-eaf0-11e9-9910-f76054413542.png)


I believe that blender should import this as a single animation, considering that is how it is stored in the .gltf file.



@julienduroure let me know if I should open a new issue or if it would be better to re-open this one?
Also, if you know offhand which files process importing shape key animations, let me know and I'll be happy to start investigating further.

**Comment by julienduroure** [comment]
Hello,

I can't see any bugs here. 
Animation target all mesh nodes, not only the root parent, because this is morph animation.
In blender, each mesh objet must have its own animation, this is how blender works.
In blender 2.81 (alpha) NLA, you can this that all these animations are owned by the same glTF animation, based on the track name "Animation1"

![image](https://user-images.githubusercontent.com/1696020/66555039-4b9bf800-eb4e-11e9-9bf0-7e7dd2a2549a.png)
