### ISSUE TITLE
Use of principled shader wrapper

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#725]
Blender has a wrapper util for principled shader.
See https://developer.blender.org/T70666

Can be great to use it and enhance it with our needs too.

Link to #462

**Comment by donmccurdy** [comment]
Is this still relevant? What is the `node_shader_utils.py` utility and its applicability here?

**Comment by julienduroure** [comment]
Closing this ticket, as we never implented it, and now we have develop a system that retrieve all needed info about the Principled Shader
