### ISSUE TITLE
Export Custom Properties on Animation Actions

### ISSUE THREAD

**Issue by Ziflin** [KhronosGroup/glTF-Blender-IO#727]
Currently the glTF exporter does not export custom properties added to animation "Actions" in Blender.

It would be very nice if action animations exported their custom properties similar to the Objects/Nodes do already. We have additional values that we'd like to add to these actions in Blender and import into our application.

The attached example file "ActionCustomProperties.blend" has an included script that can be run from the Scripting workspace/tab. After running this script, switching to the Animation workspace should show an "Action Properties" panel ("n" hotkey if it's hidden) to the right of the timeline.

There are already two custom properties set "ActionProperty1" and "ActionProperty2".  Ideally these would be exported in the animation's "extras" JSON block in the same manner as other custom properties are currently done.  This would allow us to add our own panel of custom properties to actions and read them from an exported glTF file.

[ActionCustomProperties.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3720172/ActionCustomProperties.zip)

**Comment by julienduroure** [comment]
Should be done after #709 that will provide utils to manage exporting for actions

Note: We will have to manage merging these extras fields when merging animation (based on track name of NLA)
