### ISSUE TITLE
Bezier Animation to Cubic Spline Animation conversion error.

### ISSUE THREAD

**Issue by tbutynAvalon** [KhronosGroup/glTF-Blender-IO#735]
When animating an object in blender the user has the option to select an object's key frames in the Graph Editor, Right-Click to open the f-curve context menu, then set the interpolation mode to Bezier which will make the animation key frames CUBICSPLINE in the gltf file. I've been successful in reproducing the LINEAR interpolation mode in a model viewer I work on but I've run into a bug while trying to reproduce the CUBICSPLINE interpolation mode.

The bug is that CUBICSPLINE includes 3 vectors per key frame, 1 vector is simply the LINEAR interpolation vector, but the 2 supplementary vectors are always identical and are calculated using the left control point. The scale of the right control point has no effect on the exported gltf file even though scaling the right control point definitely has an effect on the animation.

I've wrote a simple python script to parses two gltf files. One that has a right control point scaled by 1.0 and another gltf that has the same right control point scaled by 0.1. The python script will find all the differences. It shows that there are no differences in the buffer of the gltf file. A repository containing the python file illustrating the problem along with the 2 blender and 2 gltf files can be found here (https://github.com/tbutynAvalon/gltf_cubic_spline_bug)

**To Reproduce**
1. Clone the repository on the page: https://github.com/tbutynAvalon/gltf_cubic_spline_bug
2. Open the 2 blender files and playback the animation to observe the difference in animation. 
3. Run the python script and observe that the gltf files are the same.
4. (optional). Set a break point after buffer_views0_1 has been populated and observe that
buffer_views0_1[0] == buffer_views0_1[2]
buffer_views0_1[3] == buffer_views0_1[5]
buffer_views0_1[6] == buffer_views0_1[8]
where i is a multiple of 3:
buffer_views0_1[i] == buffer_views0_1[i+2]
Change the right control point in the blender file and export to get more interesting values for this optional step.

**Expected behavior**
I think what should happen is buffer_views0_1[i] != buffer_views0_1[i+2] and buffer_views0_1[i+2] is supposed to describe the right control point or some converted representation of the right control point.

**Screenshots**
N/A

**.blend file/ .gltf**
repository: https://github.com/tbutynAvalon/gltf_cubic_spline_bug

**Version**
 - OS: Windows
 - Blender Version 2.80 (2019-03-18)

**Additional context**
N/A

**Comment by julienduroure** [comment]
You are using a version that is 7 month old. 
Please test again with recent build. (Official 2.80, or better, 2.81 on builder.blender.org

**Comment by tbutynAvalon** [comment]
I recreated this bug in Blender 2.81 Beta and Blender 2.82 Alpha. I updated the files in the repository to contain the blender 2.81 versions on the .blender and .gltf files. A .gltf file has diff between 2.80 and 2.81 but the two separate files within a version remain identical.

**Comment by scurest** [comment]
This is copy-paste error

https://github.com/KhronosGroup/glTF-Blender-IO/blob/1f350035f1b219e27038547062ad3f06175f6f9c/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_sampler_keyframes.py#L112-L114

**Comment by julienduroure** [comment]
Please do not fix it in master, I will manage to get in 2.81

**Comment by tbutynAvalon** [comment]
Thank you! I appreciate the effort you all put into making blender better.
