### ISSUE TITLE
bpy.ops.export_scene.gltf function sometimes not creating glb object

### ISSUE THREAD

**Issue by Serob** [KhronosGroup/glTF-Blender-IO#736]
**Describe the bug**
I want to convert .obj to .glb.
I call ```bpy.ops.export_scene.gltf(filepath=output_glb, export_format="GLB", export_tangents=False,
	                         export_image_format="JPEG", export_cameras=False, export_lights=False)```to export glb file. Sometimes (I could not find the reason) it just do not export file, no exception, nothing. Just file that should be created does not exist.
After this behavior I call the same method on the same project and it works fine. What can cause this issue. How can we avoid it?

**To Reproduce**
Call `bpy.ops.export_scene.gltf` several times, and one time it may not export the file.

**Expected behavior**
The```bpy.ops.export_scene.gltf(filepath=output_glb, export_format="GLB", export_tangents=False,
	                         export_image_format="JPEG", export_cameras=False, export_lights=False)```  call should create a .glb file.

**Version**
 - OS: [Windows 10]
 - Blender Version: [2.79b]

**Comment by julienduroure** [comment]
Unfortunately, it will be probably difficult to reproduce, don't have any issue here.
Can you please test to reproduce on 2.80 or newer ?

**Comment by Serob** [comment]
> Unfortunately, it will be probably difficult to reproduce, don't have any issue here.
> Can you please test to reproduce on 2.80 or newer ?

We have restrictions and need to use blender 2.79.
What I have found during tries, is that sometimes it gives error: `AttributeError: Calling operator "bpy.ops.export_scene.gltf" error, could not be found. `
I have checked, the add-on is installed and enabled form blender.

**Comment by Serob** [comment]
So after some testings I could find the issue reason finally: Blender (in this particular case) uses different settings on _"run as admin"_ and regular modes, I have enabled the add-on in regular mode, but sometimes run the script in admin mode. I do not know if this behavior is caused by Blender or the OS, but **enabling the add-on in admin mode** solved the problem.

**Comment by julienduroure** [comment]
So ... Probably not linked to this addon.
Note that we will stop maintaining 2.79 at 2.82 release (currently planned during February 2020)
