### ISSUE TITLE
Winding direction is wrong

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#737]
glTF 2.0 spec defines the front face using a CCW winding direction. 
The exporter fails to export correctly a simple cube. Normals computed using the CCW winding direction point towards the inside of the cube. 

As by default materials are marked as doubleSided, this normally doesn't matter as both faces are going to be rendered, but in some cases it can give weird results. For example, exporting the default scene enabling the lights will show artifacts and a very different lighting setup in babylon.js

![image](https://user-images.githubusercontent.com/2644001/67018636-cee3bd80-f0fb-11e9-91ea-802e9a5f4772.png)

**Comment by jjcasmar** [comment]
I attach a scene I have been playing with to understand this issue 
[Scene.tar.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/3739824/Scene.tar.gz)

**Comment by jjcasmar** [comment]
@julienduroure @emackey

**Comment by emackey** [comment]
Can you include a .blend file for this?

My first suspicion is that Blender's normals are flipped in your blend file.  Blender 2.80 doesn't visually show this as well as 2.79 used to.  But you can enable the normal vector display at the bottom of the "viewport overlays" pulldown when in Edit Mode.

**Comment by emackey** [comment]
![RecalcNormals](https://user-images.githubusercontent.com/1235080/67036644-fe89ca00-f0e9-11e9-8ee2-2d9ebae23cfe.png)

**Comment by scurest** [comment]
@emackey  
1. Start with an empty file.
2. Add a cube.
3. Export as .glb with default settings.
4. Import that .glb back in.
5. Compare normals.

![compare](https://user-images.githubusercontent.com/11024420/67037111-82d84f00-f0e2-11e9-90fc-da72947aa413.png)

You can tell they're backwards from the shading, but I also cut away some tris so you can see the normals.

**Comment by emackey** [comment]
@scurest I'm shocked.  Also I can't reproduce that on my current setup.  What OS, Blender version, addon version/branch are you using to reproduce?

**Comment by scurest** [comment]
Blender: (2, 80, 75)  
Add-on: 1f35003 (current master)  

More tests show this doesn't happen if you triangulate the mesh first. Therefore possibly [this issue](https://developer.blender.org/T70594)? We use `tessellate_polygon` to triangulate n-gons and my Blender is from August, so it wouldn't have that fix.

**Comment by jjcasmar** [comment]
I am using Blender 2.81 alpha (2019-10-06 14:05) and for the exporter current master. As scurest mentioned, it doesn't happen if I triangulate the mesh first. 

Normals looks okay. No need to provide a .blend file, just export the default scene (cube, light and camera)

**Comment by scurest** [comment]
This fixes it

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
index 08270b3..a31616d 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py
@@ -617,6 +617,11 @@ def extract_primitives(glTF, blender_mesh, blender_object, blender_vertex_groups
             triangles = tessellate_polygon((polyline,))
 
             for triangle in triangles:
+                # Triangle winding-order is reversed in old versions of Blender
+                # See https://developer.blender.org/T70594
+                if bpy.app.version < ?????:
+                    triangle = (triangle[1], triangle[0], triangle[2])
+
                 for triangle_index in triangle:
                     loop_index_list.append(blender_polygon.loop_indices[triangle_index])
         else:
````

I just don't know how to find out what the first Blender version the fix went into is.

**Comment by jjcasmar** [comment]
Latest blender 2.81 (2019-10-16 16.56) works well.

**Comment by emackey** [comment]
Yeah, I was finally able to reproduce with an older Blender build from Oct 3rd.

I'm not sure we need a code change here yet though.  Still investigating.

**Comment by julienduroure** [comment]
This :
https://developer.blender.org/rBA64d638b2adda6cc5581913ad7af3627764ca57db

You can't use a current master addon with old blender version, as order changed

**Comment by emackey** [comment]
Yes, but this affects Blender 2.79.  So I think we do need a version-check block around that code change from 2fb64552718.

**Comment by scurest** [comment]
Poking around on a Github mirror of the Blender source code...

* https://github.com/sobotka/blender/commit/0905af68ecd446210b5938a1374245fe3555aecd (13 days ago) Blender version bump (281, 13) -> (281, 14).

    DOES NOT have the fix for `tessellate_polygon`: https://github.com/sobotka/blender/blob/0905af68ecd446210b5938a1374245fe3555aecd/source/blender/blenlib/intern/scanfill.c#L910

* https://github.com/sobotka/blender/commit/4b570f5b575e5a004326b8a6aa724bb0d26906a3 (7 days ago) Blender version bump (281, 14) -> (281, 15).

    DOES have the fix for `tessellate_polygon`: https://github.com/sobotka/blender/blob/4b570f5b575e5a004326b8a6aa724bb0d26906a3/source/blender/blenlib/intern/scanfill.c#L910

Conclusion: Triangles need to be reversed for versions < (2, 81, 15).
