### ISSUE TITLE
Fitting Blender release cycle

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#746]
With the new Blender release cycle, between bcon3 and bcon5 (just like right now), taking example of the 2.81 release:
https://wiki.blender.org/wiki/Process/Release_Cycle
https://developer.blender.org/project/view/88/

In Blender repo
- master is future 2.82
- beta of next release, 2.81, is on blender-v2.81-release

Here, I replicated this schema:
- master is future 2.82
- blender-v2.81-release is used for fixing bugs only for 2.81

My main concerns is about versionning of the addon. Because version increases in master, when I made a fix in blender-v2.81-release branch, I can't increase the addon version number, because this number is already taken in master. I find quite strange to use the next available number, because it means that this particular version does not include features from version with lower number.

Example:
- Addon is in version 1.0.0
- branch blender-v2.81-release is created
- a new feature A is added to master, version 1.0.1
- a new feature B is added to master, version 1.0.2
- a fix is added to blender-v2.81-release, how to name it? I don't like 1.0.3, because it doesn't include A and B.

I think, (but it's too late for 2.81 release), that we should manage it this way:
- Addon is in version 1.0.0
- branch blender-v2.81-release is created
- bump version to 1.1.0 is master, without any other changes
- a new feature A is added to master, version 1.1.1
- a new feature B is added to master, version 1.1.2
- a fix is added to blender-v2.81-release, named 1.0.1

Any thoughts?

**Comment by Vinc3r** [comment]
Your last points looks OK, but what if 2.81 version comes to 1.0.9? Is it suitable to use also letters, like official Blender versions? (2.79, 2.79a, 2.79b) This could allow 1.0.9a, 1.0.9b, etc if needed.

**Comment by julienduroure** [comment]
Version for addon are only numerical, so we can't use 1.0.9a
But, we can go up to 9, so next version will be 1.0.10

**Comment by Vinc3r** [comment]
Yep... simply as that ^^

**Comment by emackey** [comment]
Let's bump master to 1.1.0 to avoid any more collisions, and continue to bump the minor (2nd) version number with each new Blender release branch we track.

If the 2.81 release branch needs another change, its version can jump to 1.0.12.

**Comment by donmccurdy** [comment]
I'm OK with this, but we should note that it does break the usual versioning practice of semver, where the values are `<major>.<minor>.<patch>`. If we were following that strictly, all feature additions would be a `minor` version increase, and all bug fixes would be a `patch` version increase.

So just to clarify – changes on master will always be `minor` version increases, even if they're just bugfixes, and changes on a prior release will always be `patch` version increase. That seems fine to me – adding new features to old releases is probably not a priority anyway.

**Comment by emackey** [comment]
> So just to clarify – changes on master will always be `minor` version increases

Sorry, no, I meant that new Blender versions (specifically, the arrival of new Blender release branches) would trigger minor version increases, and the typical bugfix would be a patch version increase within the current branch.

The idea for this came about because we have separate branches for 2.81 and 2.82 (in master), and they are both getting patch version increments, so we need them to exist at different minor versions.

**Comment by donmccurdy** [comment]
Works for me!
