### ISSUE TITLE
Rigged example export failing.

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#75]
https://www.patreon.com/posts/free-animated-22105894

^This .blend file exports correctly to FBX, and the FBX correctly converts with FBX2glTF. When exported directly to glTF from this exporter, however, the meshes are misplaced and rotated. I'm not sure how it relates to the content of the `.blend` file, but the (working) output of FBX2glTF is structured with meshes nested under bones:

<img width="340" alt="screen shot 2018-11-08 at 8 29 54 am" src="https://user-images.githubusercontent.com/1848368/48212704-fc8f8680-e330-11e8-8f9b-b1ff39481b88.png">

**Comment by emackey** [comment]
Could this be related to https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/332 ?

Would be great to get a model with multiple game-like animations like this into the samples repo.

**Comment by donmccurdy** [comment]
Entirely possible. I think https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/74 also looks related.

Also linking https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/253 which isn't obviously connected here, but is similar conceptually – rigs that are "valid" in Blender often export incorrectly, the exporter is opinionated about how rigs must be configured. 

We did manage to get a working export via FBX2glTF: https://threejs.org/examples/?q=skinn#webgl_animation_skinning_morph

**Comment by UX3D-becher** [comment]
We just verified that the blend file is also broken with an old version of the exporter, so we will try to fix it next month. Our tests indicate that it is not a problem with multiple animations, but with skinning.

**Comment by donmccurdy** [comment]
Removing the 'enhancement' label here - I think this is a bug rather than a new feature request.

**Comment by julienduroure** [comment]
Closing, seems animations export fine now
