### ISSUE TITLE
Huge inefficiency in size with embedded textures

### ISSUE THREAD

**Issue by munrocket** [KhronosGroup/glTF-Blender-IO#750]
**Describe the bug**
I created a model with .glb format and embedded textures through blender and all was ok, before I realized that my 600kb texture on the model head increasing total size in 6mb.

**To Reproduce**
1. Download files from archive
2. Import test02.glb
3. Off/on material on head
3. Export with UVs, material etc.
3. See huge difference in size 2.5mb vs 8.6mb

**Expected behavior**
Predictable size with embedded textures or good tutorial about export.

**Screenshots**
![](https://habrastorage.org/webt/eh/c-/ly/ehc-lyzzhmgusd3dogcc-jtwf5m.jpeg)

**.blend file/ .gltf**
[arhive](https://drive.google.com/file/d/1WiQ1OCmgUVQWn7zllDZ1MD6dFhkIhsSX/view?usp=sharing)

**Version**
 - OS: [linux]
 - Blender Version [2.80]

**Comment by lexaknyazev** [comment]
`test02.glb` file (that is 8MB) contains two textures: an original `HEAD_BaseColor2.glb` (646KB) and a normal map (2048x2048, 5.21MB).

**Comment by munrocket** [comment]
@lexaknyazev your answers not informative. And and you moving issues quietly without any comment.
