### ISSUE TITLE
Proposal about draco compression for CAD models

### ISSUE THREAD

**Issue by munrocket** [KhronosGroup/glTF-Blender-IO#751]
I tested draco compression for CAD models and noticed that we can gain more compression after merge all meshes. Here a [model](https://drive.google.com/open?id=1Eg_iY1wP5VNG7DA5sDrlvmUSMkFkUJRi) without textures where you can gain x5 optimization with merging (15mb vs 3mb).

My proposal is to have an option (or by default) to merge all meshes before compress. And after decompress split polygons to several meshes by saved begin/end indices. This needs some investigation but it's clear that for some models it will be much better.

Another way how to achieve optimization is to declare instancing array for gltf. Maybe you have already functions to do this, but my blender exporter does not support this.

**Comment by munrocket** [comment]
@lexaknyazev why this issue transferred to blender?

**Comment by lexaknyazev** [comment]
Because of 
> My proposal is to have an option (or by default) to merge all meshes before compress.

At the current point, such action could be performed only by tools (such as Blender-IO) that interact with Draco.

Splitting meshes back on decompression would require a new glTF extension (if it's even possible given how Draco works).

**Comment by munrocket** [comment]
Don't move proposals anymore please.

**Comment by munrocket** [comment]
@lexaknyazev they are going to merge instancing as a new extension.

**Comment by donmccurdy** [comment]
@munrocket I'd suggest opening an issue on https://github.com/google/draco, instead. What you describe is a possible solution, but I'd prefer to ask the Draco team what they think of the problem and what solution they'd suggest. Without their recommendation, I don't think we are likely to make changes to Draco compression in either the glTF spec or the glTF Blender addon.

You may also want to look at the (proposed) MESHOPT_compression extension: https://github.com/KhronosGroup/glTF/pull/1702. It does compression at the bufferView level, meaning that meshes do not have to be merged to be compressed as a group. I'm not sure what results it will give on your model, but it appear to do pretty well on CAD stuff: https://github.com/KhronosGroup/glTF/issues/1699#issuecomment-565499098. The "gltfpack" tool will let you test the proposal already.

**Comment by munrocket** [comment]
Sorry, I am probably not competent enough to open an issue. But models like [this](https://sketchfab.com/3d-models/melodia-city-hotel-a2fb8e4065ce470296d6d801daa37f18) should gain advantage of this. Main problem that sometime network bandwidth more important than gpu capability and gpu instancing. You can open this model as an example on your phone from sketchfab. Anyway I just wanted to share my experience with gtTF.

**Comment by donmccurdy** [comment]
^For an example like the one you shared there, I'd suggest using the [gltfpack](https://github.com/zeux/meshoptimizer#gltfpack) tool without even enabling the compression. It won't be quite as small as what Draco provides (5.1 MB vs 4.6 MB, after gzip) but it optimizes the result for runtime quite well, and most of the remaining size is just textures anyway. In three.js on my old laptop, I can render the original model at ~18 FPS, and 60 FPS (my browser's limit) after optimizing with gltfpack.

It does merge meshes, though — there's an option to disable that, which doesn't affect the file size much, but does lose all the framerate improvements.

**Comment by munrocket** [comment]
Thank you, I will share this solution. GLTFpack also support Basis for texture compression.
