### ISSUE TITLE
Changing Y axis animation in blender results in no change in the exported gltf file.

### ISSUE THREAD

**Issue by tbutynAvalon** [KhronosGroup/glTF-Blender-IO#752]
**Describe the bug**
I'm trying to support gltf animation in a model viewer I work on. I have been struggling to reproduce the animations faithfully as they are presented in blender. In this particular report I produce two cubes, each with three animation key frames. The animation key frames only modify the Y axis rotation. The first cube has three rotations of 0deg -> 0deg -> 0deg. The second cube has three rotations of 0deg -> 45deg -> 0deg. The two exported gltf files contain the same data so it is impossible to represent this animation in a model viewer.

**To Reproduce**
1. Clone the repository on the page: https://github.com/tbutynAvalon/gltf_rotation_animation_bug
2. Open the 2 blender files and playback the animation to observe the difference in animation.
3. Run the python script and observe that the gltf files are the same.
4. (optional). If you want you can export the .blend files but the gltf files are also in the repo.

**Expected behavior**
I expected that changing the Y rotation would result in a change in the exported gltf file.

**.blend file/ .gltf**
[gltf_rotation_animation_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3779666/gltf_rotation_animation_bug.zip)

**Version**
 - OS: Windows
 - Blender Version 2.82 alpha (2019-10-16)
- Also on Blender Version 2.80 ()

**Comment by julienduroure** [comment]
Confirmed.
Linked to setting single keyframe on euler rotation

**Comment by julienduroure** [comment]
#753 will solve the issue, but I need to perform lots of non regression tests to be sure that there is no issue
