### ISSUE TITLE
Animation export error

### ISSUE THREAD

**Issue by Yzou-NaO** [KhronosGroup/glTF-Blender-IO#756]
**Describe the bug**
I tried to export a .glb from .blend, but it missed some animation. It seems correct using the previous blender version 2.80.

**.blend file/ .gltf**
[head.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3781645/default.zip)

**Version**
 - OS: macOS
 - Blender-IO Version 1.0.11

**Comment by julienduroure** [comment]
Confirmed that some animation is missing when "always sampled animation" is checked. This option is checked by default in 2.81. 
Your workaround for your project in this particular case, waiting the bug to be fixed --> uncheck this option

(Note that animate the armature object is not really a good idea in Blender)

**Comment by Yzou-NaO** [comment]
Thank you so much for the speedy reply.

**Comment by Peach1** [comment]
Any updates on this? I've noticed this error too; Any idea *where* in the code causes `Always Sample Animations` to skip some animations?

`Always Sample Animations` enables `export_settings['gltf_force_sampling']`,

So my guess is somewhere in `blender/exp/gltf2_blender_gather_animation_channels.py`, there might be an issue with `bake_range_start` or `bones_to_be_animated` or something else

https://github.com/KhronosGroup/glTF-Blender-IO/blob/406a409d4740e6a67ec3e8699c7dec40afe5067e/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_channels.py#L54-L80

**Comment by julienduroure** [comment]
The problem on original test file is that the armature object is animated itself, that is a very bad idea to animate the armature object. 
When "always sample" is checked, all fcurves are ignored, and all bone animation are baked, but animation of armature itself is also ignored. 
Need to code a workaround to sample armature object fcurves if exist.

**Comment by julienduroure** [comment]
Fixed by #893
