### ISSUE TITLE
Feature request: An option to export textures into "textures" folder

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#759]
Hi

Upon export, if "gltf Separate" option is selected, by default textures will be exported next to .gltf file. Can you please change this behavior or add an export option to create a new folder "textures" next to .gltf file and export textures into that folder?

Edit: 
Or even better, let the user to specify the relative path for exporting textures. As gltf already supports relative path in image "uri".

**Comment by Vinc3r** [comment]
That would be a nice feature!
