### ISSUE TITLE
Linked geometry is exported as separate meshes, when armature is added.

### ISSUE THREAD

**Issue by ibozhilov** [KhronosGroup/glTF-Blender-IO#760]
**Describe the bug**
I have a scene with two cubes that share the same mesh data. When exported to gltf I get two nodes and one mesh as expected. However, if I get back to the scene, add armature for each of the objects and parent them, the export results in two meshes. The interesting part is that the two meshes share the same accessor for indices, but have different accessors for position,normal and texcoord, though they have the same data within.

**To Reproduce**
1. Start with empty scene
2. Add Mesh -> Cube
3. Select the Cube and duplicate it linked. This way you should have two objects(cubes) on the scene sharing the same mesh.
4. Export to gltf and you will have the expected behavior having two nodes with just one mesh.
5. Add two armatures. Parent each of the armatures to a corresponding cube.
6. Export to gltf and you will have two meshes with duplicated accessors and data. 

**Expected behavior**
As the two cubes share the same mesh data and are linked within Blender, they should share the same mesh in gltf, too.

**.blend file/ .gltf**
Attaching the two gltf files as well as the blend file used for the export. [duplicated_meshes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3803283/duplicated_meshes.zip)

**Version**
 - OS: Ubuntu 19.04
 - Blender Version 2.80 (sub 75)

**Comment by julienduroure** [comment]
This is linked how data are managed for skinned meshes.
Each object is written in Armature space, so because the 2 objects are linked to different armature, these 2 objects/meshes may not have same position/normal/texcoord

**Comment by ibozhilov** [comment]
@julienduroure Could you point me to somewhere I can read how data is managed for skinned meshes. So the mesh data is not absolute, but relative to the armature, is that right?

**Comment by julienduroure** [comment]
Hello,
You can check here: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins
And the following conversations:

* https://github.com/KhronosGroup/glTF-Blender-IO/issues/566
* https://github.com/KhronosGroup/glTF/issues/1665
