### ISSUE TITLE
glTF2 Export Error Mannequin

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#765]
**Describe the bug**
Exported female fails.

**To Reproduce**
1. Open blend file
2. Export as glTF glb

**Expected behavior**

Exported mannequin should appear like the blender window.

**Screenshots**
![Screenshot from 2019-11-08 13-08-25](https://user-images.githubusercontent.com/32321/68510629-e0b30f00-0228-11ea-9d41-83772ff6a3dc.png)

![Screenshot from 2019-11-08 13-11-28](https://user-images.githubusercontent.com/32321/68510806-515a2b80-0229-11ea-9056-d05e4639ffb8.png)

![image](https://user-images.githubusercontent.com/32321/68510835-6040de00-0229-11ea-8a0e-cbd702834a71.png)

For the version number. 

![Screenshot from 2019-11-08 13-26-55](https://user-images.githubusercontent.com/32321/68511754-79e32500-022b-11ea-8ea9-2f193a9a14ad.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

[mannequin.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3826263/mannequin.zip)

**Version**
- Fedora 31
- Blender 2.81 (nightly)

**Misc**
Originally from https://www.deviantart.com/namito111/art/Blender-Art-Mannequin-v5-1-440732215

namito111 - You are free to re-distribute or distribute a modified version

**Comment by julienduroure** [comment]
Found the issue. Constants on bones are not evaluated on not animated armature.
This is the case on the provided model (reset pose bone is not identical to rest pose because of these constraints).
So a possible workaround for now is to add a keyframe on every bones:

![image](https://user-images.githubusercontent.com/1696020/68512750-8b531e00-0279-11ea-87b4-de82974f9cfb.png)

**Comment by fire** [comment]
Doing that only displays half the body when exported to glb. However, it was helpful.

![Screenshot from 2019-11-08 14-03-08](https://user-images.githubusercontent.com/32321/68513716-933aa000-0230-11ea-97cf-8abbfdf2ef29.png)

**Comment by julienduroure** [comment]
@fire You have to enable "apply modifier" if you want to display both half of the model. By default modifiers (so your mirror modifier) is not applied

**Comment by fire** [comment]
Thanks, that worked.

I believe the FBX exporter has a force start/end keying option.

![Screenshot from 2019-11-08 14-18-30](https://user-images.githubusercontent.com/32321/68514467-a9e1f680-0232-11ea-9ff2-ab7a3e221344.png)

**Comment by fire** [comment]
I'm not having trouble with this model and a workaround was done.

**Comment by julienduroure** [comment]
Well, there is a workaround, but initial issue is still there and needs to be fixed.
I reopened this issue to be sure to not forget it.

**Comment by julienduroure** [comment]
This will be solved by #1378

**Comment by julienduroure** [comment]
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2
