### ISSUE TITLE
Export Particle System to EXT_mesh_gpu_instancing

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#766]
I'm considering an experimental implementation of [KHR_instancing](https://github.com/KhronosGroup/glTF/pull/1691) (**DRAFT**), using [Blender's Particle Systems](https://docs.blender.org/manual/en/latest/modeling/modifiers/simulate/particle_instance.html) as the source. The glTF extension is not certainly not meant to reproduce the full functionality of a particle system in any particular software (that would be ... challenging 😅) but it does provide a very efficient way to have large quantities of the same mesh in a scene, with per-instance transforms and other custom data attached.

Proposal:
- Export a Particle System emitting a Mesh as a static KHR_instancing batch.
- Include [Custom Data Layers](https://docs.blender.org/manual/en/latest/modeling/modifiers/simulate/particle_instance.html#custom-data-layers) to write custom attributes on the batch (`_INDEX`, `_VALUE`) so that shaders in the viewing application can add variance to materials, identify instances, etc.

I have no plan to include animation at this time; baking and efficiently storing the various animation types and simulations that can be applied to Particle Systems is well beyond what I want to attempt right now.

Example (viewer) implementation in three.js:

![68440494-19e37480-0180-11ea-8a5e-11a2d71001c5](https://user-images.githubusercontent.com/1848368/68550958-a11d2c00-03bc-11ea-8e2d-312f9c07ea5d.png)

**Comment by julienduroure** [comment]
Not sure this is a good timing to start working on particles in blender, a complete rewriting is currently in progress. Particle system will become a node base system. Not sure about the current plan, but some experimental builds are already available

**Comment by donmccurdy** [comment]
Thanks, that's good to know! I'd love to hear how the node-based particle system might work, if there are threads or discussions somewhere.

This wouldn't require all that much of the Particle System API surface, mostly just need to get the positions of each particle...

```python
for p in ob.particle_systems.active.particles:
    rot = p.rotation
    loc = p.location
    scl = p.size
    # ...
```

... but all the same, no point in merging anything like this to the addon until things have stabilized.

**Comment by donmccurdy** [comment]
👀 https://www.youtube.com/watch?list=PLyGoWAGEPJ1DLzhm1_dhuLVe7wT1kBFNP&time_continue=113&v=A05UghlpVPs&feature=emb_logo

**Comment by donmccurdy** [comment]
Getting weird results: https://devtalk.blender.org/t/manipulating-particles-in-python/7552/15?u=donmccurdy

Not sure if that's because of the rewrite in progress, or if I'm using the API wrong. :/

**Comment by donmccurdy** [comment]
Update: I implemented a draft of the KHR_instancing extension, in this branch:

https://github.com/KhronosGroup/glTF-Blender-IO/compare/master...donmccurdy:feat-khr-instancing

The issue mentioned above was resolved by switching from *Hair* to *Emitter* mode, and setting *Frame Start* and *End* both to 1, which seems like a bug, but I'm not sure. The results look consistent in Blender and three.js:

| engine | screenshot |
|---|---|
| blender | ![blender instancing](https://user-images.githubusercontent.com/1848368/71598855-63f03300-2afd-11ea-91bc-46006074819d.png) |
| three.js | ![three.js instancing](https://user-images.githubusercontent.com/1848368/71598857-66eb2380-2afd-11ea-8927-1e92d11beb90.png) |

I'm not 100% sure whether it's the right design, to export particle systems this way. It's convenient and efficient, but the documentation would have to be very clear about which particle system options are supported — the vast majority would not be, as animation isn't in spec or likely to be portable across tools. On the other hand, Blender has custom index and weight values per particle (which I haven't figured out how to export yet) and those would allow users to reconstruct animation in shaders within their engines.

Another option, not implemented — Blender has a separate "instancing" mechanism for objects scattered around a scene to reuse mesh or other data. We export those without duplicating the geometry already (great!) although it could be even more efficient with `KHR_instancing`. However, `KHR_instancing` would lose these objects' positions in the scene graph. I think that type of opinionated optimization might be more appropriate for a post-export optimization tool, like gltfpack or glTF-Pipeline.

**Comment by PirateJC** [comment]
> Another option, not implemented — Blender has a separate "instancing" mechanism for objects scattered around a scene to reuse mesh or other data. We export those without duplicating the geometry already (great!) although it could be even more efficient with KHR_instancing. However, KHR_instancing would lose these objects' positions in the scene graph. I think that type of opinionated optimization might be more appropriate for a post-export optimization tool, like gltfpack or glTF-Pipeline.

I'd love to add my vote for this. Blender's Object Scatter add-on allows for a very artist friendly workflow for instancing objects while being able to easily "paint" the instances where you'd like them to go. It would be amazing if the gltf exporter could read that scatter data (duplicators) and do the necessary conversions to gltf.

Thanks for all the work on this!

**Comment by takahirox** [comment]
FYI: I wrote an addon that allows to export instanced geometries created with Geometry Nodes, not particle systems, as glTF with `EXT_mesh_gpu_instancing` extension.

https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing

It's still an early prototype and I'm not sure if this is the best approach, and I'm not sure how the extension should be imported yet tho.

https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing/issues/2

**Comment by julienduroure** [comment]
This is now available as an option to export Geometry Nodes Instances as EXT_mesh_gpu_instancing
Closing this ticket, as Particle system is replaced by GN in Blender
