### ISSUE TITLE
Basic Transparency Error in gITF 

### ISSUE THREAD

**Issue by byronmuller2019** [KhronosGroup/glTF-Blender-IO#768]
Hello I just apply a basic blue material in blender and add a transparency
![Zproblem01](https://user-images.githubusercontent.com/57678408/68691288-1f9ed880-0539-11ea-86df-e57c95b89dae.jpg)

in blender looks normal and fine but when I export tu gITF file and I open the file in a web viewer like https://gltf-viewer.donmccurdy.com/

the file looks like this
![Zproblem02](https://user-images.githubusercontent.com/57678408/68691555-9045f500-0539-11ea-908a-760b3958582b.jpg)

why looks that the transparency .... i just a basic material, can you help me on this?

i dont have experiencie in blender but i need it to export in gITF 

i hope you can help me

**Version**
 - OS: [windosw 10)
 - Blender Version 2.8

**Comment by julienduroure** [comment]
Hello,

Please provide the .blend file as requested. Without it, we can't find where is the issue.
Thanks!

**Comment by byronmuller2019** [comment]
sorry yes this is the blend file and the gITF file

[bluebodyBLEND.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3837291/bluebodyBLEND.zip)
[bluebodygITFl.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3837298/bluebodygITFl.zip)
thank so much for the help

**Comment by julienduroure** [comment]
Your zip files does not contains any .blend file ...

**Comment by byronmuller2019** [comment]
[blueblend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3837556/blueblend.zip)

I zipped again i dont know what happen

**Comment by donmccurdy** [comment]
I don't think this is an exporter issue; unfortunately rendering multiple nested transparent objects is not a basic matter in any realtime engine. 

In this example you'll see better results on https://sandbox.babylonjs.com/ than https://gltf-viewer.donmccurdy.com/, but neither is going to be perfect. If you know the particular engine or viewer you're going to be using for this model, you may be able to tweak settings there to get the result you want. For example, disabling `depthWrite` or `depthtest` in three.js for specific materials can get rid of most of these artifacts, but with some side effects. Merging meshes may get rid of some remaining issues.

**Comment by julienduroure** [comment]
Agreed with Don's analysis.
You can see same artefact by checked "Show Backface" in blender material

![image](https://user-images.githubusercontent.com/1696020/68710486-f6f9fb80-0597-11ea-8000-1f34099b76ae.png)

**Comment by byronmuller2019** [comment]
> 
> 
> I don't think this is an exporter issue; unfortunately rendering multiple nested transparent objects is not a basic matter in any realtime engine.
> 
> In this example you'll see better results on https://sandbox.babylonjs.com/ than https://gltf-viewer.donmccurdy.com/, but neither is going to be perfect. If you know the particular engine or viewer you're going to be using for this model, you may be able to tweak settings there to get the result you want. For example, disabling `depthWrite` or `depthtest` in three.js for specific materials can get rid of most of these artifacts, but with some side effects. Merging meshes may get rid of some remaining issues.

ok I understand thanks that help a lot... which would be the best realtime engine to transparency? to include in iOS app?

**Comment by byronmuller2019** [comment]
> 
> 
> Agreed with Don's analysis.
> You can see same artefact by checked "Show Backface" in blender material
> 
> ![image](https://user-images.githubusercontent.com/1696020/68710486-f6f9fb80-0597-11ea-8000-1f34099b76ae.png)

ok thanks a lot i understand the issue :)
