### ISSUE TITLE
Linked geometry is exported as separate meshes, when modifier is added

### ISSUE THREAD

**Issue by mikepan** [KhronosGroup/glTF-Blender-IO#778]
**Describe the bug**
I have a scene with multiple objects all sharing the same mesh data. When exported to glb, they use the same mesh which is expected.  But if I add a subd modifier to all the objects, even if 'apply modifier' is disabled on export, it still creates multiple copies of the mesh.

**To Reproduce**
1. Start with empty scene
2. Add Mesh -> Monkey
3. Select the Monkey and duplicate it linked (Alt+D). This way you should have two objects in the scene sharing the same mesh.
4. Export to gltf and you will have the expected behavior having two nodes with just one mesh.
5. Add two a subd modifier to both monkey.
6. Export to gltf with 'Apply modifier' turned OFF, and you will still have two meshes with duplicated accessors and data.

**Comment by julienduroure** [comment]
Confirmed.
If "apply modifiers" is checked, we can't be sure that geometry is identical between instances.
But if "apply modifiers" is unchecked, we can instantiate mesh data

**Comment by mikepan** [comment]
I just noticed that instancing also fails when there is any vertex group attached to a mesh. Can you confirm if your latest commit fixed that too?

**Comment by julienduroure** [comment]
I confirm the bug, but current PR doesn't fix it (yet)
