### ISSUE TITLE
Wrong size for morph target output with more than one morph track

### ISSUE THREAD

**Issue by pouleyKetchoupp** [KhronosGroup/glTF-Blender-IO#782]
**Describe the bug**
When exporting a model with more than one morph target, the output of the morph animation tracks doesn't contain enough values for all the morph targets, as defined in the specifications.

*gltf 2.0 Specifications:*
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0
>A Morph Target animation frame is defined by a sequence of scalars of length equal to the number of targets in the animated Morph Target. These scalar sequences must lie end-to-end as a single stream in the output accessor, **whose final size will equal the number of Morph Targets times the number of animation frames.**

I've tested with the fix from #641 and it doesn't solve the problem.

**To Reproduce**
1. Export the attached model file to .gltf
2. Open the exported .gltf
3. Observe 6 values in the morph tracks output instead of 12

**Expected behavior**
The exported data should follow the specifications and export `num morph target` times `num frames` values in the output accessor for morph animation tracks.

**.blend file/ .gltf**
[gltf_morph_bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3873599/gltf_morph_bug.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.80

**Comment by julienduroure** [comment]
Since 2.80 (and since #641 too), some fixes has been done on morph target.
Can you please test again with a recent build (2.81 beta version) ?

**Comment by scurest** [comment]
That paragraph in the spec is very confusing and should be changed IMO. For a CUBICSPLINE curve, there are three "animation frames" of data per keyframe: one for the in-tangents, one for the ordinals, one for the out-tangents. So for a CUBICSPLINE curve there are going to be (number of morph targets) × 3 × (input accessor count) values in the output accessor.

The next paragraph clarifies how CUBICSPLINE curves are packed

> When used with CUBICSPLINE interpolation, tangents (a<sub>k</sub>, b<sub>k</sub>) and values (v<sub>k</sub>) are grouped within keyframes:
>
> a<sub>1</sub>,a<sub>2</sub>,...a<sub>n</sub>,v<sub>1</sub>,v<sub>2</sub>,...v<sub>n</sub>,b<sub>1</sub>,b<sub>2</sub>,...b<sub>n</sub>

So looking at your file, it uses a CUBICSPLINE curve with 2 values in the input accessor, the targeted mesh has two morph targets, and so the output correctly has size 2 × 3 × 2 = 12.

Cf. #688

**Comment by pouleyKetchoupp** [comment]
@julienduroure I can confirm it's fixed in 2.81 beta. Thanks!
