### ISSUE TITLE
Skeleton Data and Model Data is crushing while exporting

### ISSUE THREAD

**Issue by yufae** [KhronosGroup/glTF-Blender-IO#783]
Hello, I have a blend file includes an object with skeleton and one animation. I can export fbx file and it works perfectly and I can even convert fbx file to usdz file and it also works perfectly but when I want to export it as  glb/gltf file the right arm of the object and the skeleton crash.
I couldn't find the problem.

Could you Please help on this issue.

Here is the blend file
[akin5.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3875319/akin5.blend.zip)

 - OS: masOS Mojave 10.14.4
 - Blender Version 2.8

**Comment by julienduroure** [comment]
Hello,
Did you test with latest build of blender (blender 2.81 beta) ?

**Comment by yufae** [comment]
I did now. but it totally crashes. Gltf validator gives the errors below.

Thanks.


Error | Message | Pointer
-- | -- | --
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 127 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 143 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 207 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 223 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 239 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 319 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 335 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 367 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 383 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 399 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 415 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 431 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 511 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 527 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 543 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 559 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 575 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 591 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 607 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 623 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 639 is not decomposable to TRS. | /accessors/6
ACCESSOR_INDECOMPOSABLE_MATRIX | Matrix element at index 655 is not decomposable to TRS. | /accessors/6

**Comment by yufae** [comment]
Do you have any other idea?

Thenks

**Comment by julienduroure** [comment]
This is a known issue, because of scale on the armature object.
This is allowed in Blender, but always a bad idea.

Waiting this feature is implemented, there is a workaround, quite long to perform:
* Apply scale on armature object
* This will mess up all translation animation bones
* So go to GraphEditor
* Set 2D cursor to 0 / 0
* change visibility to display only location of all your bones
* Scale your curve, on T axis only, by 0.001 (because this was your initial scale on armature)
* This should work (needed to be done on each action if multiple action on blend file

**Comment by julienduroure** [comment]
Well, in your case, no bone has some location animation, so after applying scale on armature, you can scale location of your mixamorig:Hips bone by 1000 (on X / Y and Z)

**Comment by julienduroure** [comment]
This was fixed in master
