### ISSUE TITLE
Draco debug output spam in terminal

### ISSUE THREAD

**Issue by capnm** [KhronosGroup/glTF-Blender-IO#806]
**Version**
OS: linux
Blender 2.81 + gltf tip 1.1.6,
didn't tested, but probably also in blender alpha.

**Describe the bug**
If you move the mouse pointer over the Geometry tab, the terminal will be flooded with:
```
… bin/2.81/python/lib/python3.7/site-packages/libextern_draco.so' exists, draco mesh compression is available
```
![image](https://user-images.githubusercontent.com/4047289/69889364-c8e31e00-12f0-11ea-9a72-d29f24e4add1.png)

**Comment by julienduroure** [comment]
Confirmed, I already noticed that, but I never take the time to fix it (yet)
