### ISSUE TITLE
Tests are KO: Seems daily build are now tar.xy format

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#810]

**Comment by scurest** [comment]
Here

https://github.com/KhronosGroup/glTF-Blender-IO/blob/08aa869c42b33a707eb09bfed3459b52b64eabb5/.circleci/config.yml#L42

try changing `tar -jx` to `tar -ax`.

`-a` should auto-detect the compression type from the file extension.

**Comment by julienduroure** [comment]
I changed from -jx to -Jx ...
Let's see if it solved it or not

**Comment by scurest** [comment]
-J should work as long as it stays .tar.xz.

Apparently GNU tar can't autodetect the type when reading from stdin. If we want it to autodetect we'd have to wget the URL to a file, and feed the file to tar.
