### ISSUE TITLE
Draco error using instances

### ISSUE THREAD

**Issue by LorenzWieseke** [KhronosGroup/glTF-Blender-IO#816]
**Describe the bug**
I was happy to see that since the last version I can now export ik rigs to glb without needing to bake the animation and also not needing to apply roation, so fist of all THANKS A LOT FOR THAT !

So now everything works fine without draco, but as soon as I use draco with instances I get the following error :

![draco_error](https://user-images.githubusercontent.com/29607121/70151524-01e21080-16ac-11ea-9509-f53fbea41527.jpg)

**To Reproduce**
Open file :
[Draco_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3922381/Draco_test.zip)

Export with draco and see error

**Version**
 - OS: Windows
 - Blender Version 2.81

**Comment by julienduroure** [comment]
@UX3D-nopper Can you please have a look?

**Comment by UX3D-nopper** [comment]
We will cross check it.
