### ISSUE TITLE
 Build modifier animation

### ISSUE THREAD

**Issue by itakawa** [KhronosGroup/glTF-Blender-IO#821]
It may be a problem with my Blender usage, but I want to generate a build modifier animation.
For example, an animation of an attached file.

**Comment by itakawa** [comment]
[font.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3935679/font.zip)

**Comment by julienduroure** [comment]
There is nothing in glTF to animate this kind of animation. Sorry about that.
Only following can be animated:
* location / rotation / scale of objects and bones
* shapekeys animation --> Mesh should always have to same number of vertices.

In case of build modifier, vertex count change over the time --> This cannot be "translated" into glTF
