### ISSUE TITLE
Exporting Mesh + Animation causes node's transform to be of the first frame

### ISSUE THREAD

**Issue by sketchpunk** [KhronosGroup/glTF-Blender-IO#823]
Ideally, I would like the transform of the bone nodes to be whatever it is at the time. If I have it set as the resting pose, I expect it to be exported that way but it doesn't. If an animation exists, it reposes the armature to whatever the first frame is.

Now I did find a work around. In the animation tab of the exporter, there is the option to use the current frame, that gives me what I want but the option name and its placement is confusing. Since its the animation tab, and the option is label "Use the current frame", I expect it to export the current animation frame, which is what you get when its checked OFF. Checking ON kinda does the opposite, which i think should be how it should work with it Off.

Ideally it would be nice to have an option that gives you the choice of what you want the bone node transforms to be. Like Current Pose, Animation First Frame, Resting Pose.

I dont use GLTF to export scenes, I use it to export individual assets for webgl. So would be nice for the exporter to have features for that use case.

**Comment by julienduroure** [comment]
We can now close this (quite old) ticket.
Rest pose is now used by default for transforms of bone nodes.
When using "Use current frame", the current frame TRS is used as transforms for bone nodes.
