### ISSUE TITLE
import file resolution lower than web viewers

### ISSUE THREAD

**Issue by anonMcAnonface** [KhronosGroup/glTF-Blender-IO#826]
hi, when I import my GLTF file in blender it comes in with a lot lower resolution than what I see on web viewers. why is that?

**Comment by anonMcAnonface** [comment]
well i also just now tried to export that same file back out from blender and it matches the input file in web viewers, so now my question is why does blender show the file at lower resolution?

**Comment by julienduroure** [comment]
Hello,

Not sure what you mean exactly by "resolution", but if you mean the visual size of your model : Most of online viewer do autozooming to the model, where Blender doesn't. There is no bug here.

I can't check in detail, because you don't fill the required information that you have in template when you create the issue (for example an sample .blend file and/or .glb file).

**Comment by emackey** [comment]
@anonMcAnonface Is there a sample model you can share, or screenshots to clarify the problem?

**Comment by anonMcAnonface** [comment]
hello, sure take a look at the model attached
[fountain_meadow_2ndver.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3952050/fountain_meadow_2ndver.gltf.zip)

**Comment by anonMcAnonface** [comment]
What I mean is that I load the GLTF file into blender and zoom in on it (or just press 7). Then compare that with some web viewers for GLTF (I like the babylonJS Sandbox). You will see that details in the model are readily apparent in the web viewer but in blender they look 'low res'.

**Comment by emackey** [comment]
What version of Blender, and what viewport mode are you in?  Try Blender 2.81, and click the "Viewport shading: Material Preview" button in the upper-right section of the 3D view.  It's the sphere with the checkerboard on it.

**Comment by anonMcAnonface** [comment]
Ah ok, thank you! Will try that. I am currently using 2.81 but I have to switch back to 2.79. I cannot get the boolean operation to work correctly in 2.81. It is a different issue, I may open a new ticket?

**Comment by emackey** [comment]
You can always open a new ticket, but I don't think what you're seeing here is any kind of bug with the glTF-Blender-IO addon.  It's just that Blender displays the landscape without a texture on it, by default.  So you're seeing the "resolution" of the actual vertices, which is far less than the resolution of the pixels in the texturemap.  2.79 had a viewport shading mode too, across the bottom, that you might be able to change to see the texturemap.
