### ISSUE TITLE
Shape Keys not working properly

### ISSUE THREAD

**Issue by calvertcreates** [KhronosGroup/glTF-Blender-IO#827]
**Describe the bug**
When exporting a face mesh with shape keys using glTF 2 in Blender 2.81a, I do not see the data for each shape key in glTF separated.

I've included the Blender test file along with the glTF exports without the min/max data and a converted FBX to glTF file using [FBX2glTF ](https://github.com/facebookincubator/FBX2glTF )that does include that data.

**To Reproduce**
1. Go to File > Export glTF
2. Match Export settings in the screenshot below
3. Click export
4. Open file in your code editor and see the difference in what's exported between both glTF files

**Expected behavior**
We expect to see the min and max shape key data for each shape key.

**Screenshots**

**Export settings**
Note: Using glTF Separated
![image](https://user-images.githubusercontent.com/9643084/70650385-fd25db00-1c1c-11ea-875a-34149a96c0e5.png)

**Files**
[Blender Test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3952034/Blender.Test.zip)
[Exports.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3952036/Test.zip)

**Version**
 - OS: Windows 10 1903
 - Blender Version 2.81a

**Comment by julienduroure** [comment]
Hello,
I am not sure to understand exactly the issue. Do you mean the "min" and "max" field in accessors? 
I opened the 2 gltf file provided and I checked how many "min" fields are in file. Both files have 104 occurences. So I probably didn't understand what is your issue. Don't hesitate to add some information, screenshots or example !

Thanks

**Comment by calvertcreates** [comment]
Hey @julienduroure, thanks for taking a look. 

So we're using ARkit to play shape keys on a face mesh with shape keys in our app with glTF. When we export using Blender glTF (since 2.80) we are not able to playback those shape keys with the data exported. We've tried a bunch of different things but have only been able to see shape keys playback when being put through FBX2glTF linked earlier. When looking at the direct blender export and the fbx2gltf converted files there is a difference in data and how it's organized.

![ezgif com-resize](https://user-images.githubusercontent.com/9643084/70730853-b646ec80-1cd3-11ea-82b2-d2ff2834036d.gif)
In the above video, you can see the glTF file that was converted with FBX2glTF. The images move along the shape keys on the face properly. 

![ezgif com-resize(1)](https://user-images.githubusercontent.com/9643084/70730999-fb6b1e80-1cd3-11ea-8fa9-9d2e97252fb6.gif)
In this video it's the export directly from Blender 2.81a (also tried 2.80 and 2.81) and the shape keys are not being recognized. The images are not moving with the shape keys.

When bringing it up in the glTF slack I was told it might be a bug, so I made a ticket. I'm trying to figure out if it's a bug or there is something we can do to directly export glTF from Blender 2.8+ with working shape keys. 

I hope the above is helpful, also happy to jump on a quick google hangout if that's easier too.

**Comment by julienduroure** [comment]
I exported and try to view it using an online viewer : https://gltf-viewer.donmccurdy.com/
All shapekeys seems to be available in both objects, and seems to be OK for SK I tested

**Comment by calvertcreates** [comment]
Thanks for testing and confirmation. I'm going to close this for now.
