### ISSUE TITLE
KHR_materials_unlit

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#83]
It appears that we've lost support for `KHR_materials_unlit` in this repository. Previously unlit materials could be created with the Blender Render "shadeless" checkbox. I'm not sure what, if anything, can be done to create shadeless materials in Cycles or Eevee, but at least for Blender Render we should still support the shadeless checkbox.

Related: https://blender.community/c/rightclickselect/Djbbbc/

**Comment by UX3D-nopper** [comment]
We check this.

**Comment by UX3D-becher** [comment]
We can also use this as an example on how to implement custom extensions

**Comment by donmccurdy** [comment]
Thanks! Minor: I don't think there's any need for the unlit extension to be in `extensionRequired`.

**Comment by dsinni** [comment]
Is there any plan to add `KHR_materials_unlit` as an export option? Is this possible?

**Comment by donmccurdy** [comment]
Probably not an export option I think.. Rather:

(A) use Emissive node alone to create an unlit `KHR_materials_unlit` material.
(B) use Emissive node with Principled BSDF node (and an Add node) to export PBR with an emissive channel.

**Comment by donmccurdy** [comment]
also note tools like https://glb-packer.glitch.me can unlit-ify an existing model

**Comment by dsinni** [comment]
Right on. Thanks, @donmccurdy!

**Comment by donmccurdy** [comment]
It looks like https://github.com/KhronosGroup/glTF-Blender-IO/commit/c71104ea181984b6eefdef7d1a22fe4db28b4201 restores some code from 2.79 that checked for the `use_shadeless` option on the material, but unfortunately I'm not sure how to mark a material as shadeless in Blender 2.8 — the checkbox is gone. Would it be possible to consider a material "shadeless" if an Emissive node is connected directly to the output? For example:

![screen shot 2018-12-01 at 6 07 48 pm](https://user-images.githubusercontent.com/1848368/49334994-afea4480-f598-11e8-936a-f45f111ef573.png)

Adding an Emissive and a Principled BSDF node should give a true emissive PBR material, as before:

![screen shot 2018-12-01 at 6 04 25 pm](https://user-images.githubusercontent.com/1848368/49334998-c2647e00-f598-11e8-87be-3febc92dff09.png)

@UX3D-becher does this seem workable? Or can you think of a better way to mark materials as shadeless? It would be helpful if Blender still had some checkbox for this...

**Comment by donmccurdy** [comment]
Not sure if it's really correct (I can't do this through the menu, only using nodes) but both of these seem to work in Blender:

![screen shot 2018-12-01 at 11 32 13 pm](https://user-images.githubusercontent.com/1848368/49337043-72e67800-f5c1-11e8-80ba-a34e3bae642f.png)

![screen shot 2018-12-01 at 11 31 57 pm](https://user-images.githubusercontent.com/1848368/49337044-75e16880-f5c1-11e8-8b92-c6801bbc30d9.png)

Guess we could just support that? Might be helpful to get Blender devs' suggestions. 🤔

**Comment by UX3D-nopper** [comment]
Think this is what you want to have:
![grafik](https://user-images.githubusercontent.com/27856744/49337804-64c44600-f619-11e8-9b28-df781a76a1c3.png)

**Comment by dsinni** [comment]
@donmccurdy When I try the `RGB` method, I can't get the correct color to export.

@UX3D-nopper Your suggested `Light Path` node configuration mostly worked, however I'm getting the following error from the glTF Validator: 

```
{
    "uri": "emissive_export_test.glb",
    "mimeType": "model/gltf-binary",
    "validatorVersion": "2.0.0-dev.2.6",
    "validatedAt": "2018-12-02T20:59:33.774Z",
    "issues": {
        "numErrors": 1,
        "numWarnings": 0,
        "numInfos": 0,
        "numHints": 0,
        "messages": [
            {
                "code": "ARRAY_LENGTH_NOT_IN_LIST",
                "message": "Invalid array length 4. Valid lengths are: (3).",
                "severity": 0,
                "pointer": "/materials/0/emissiveFactor"
            }
        ],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "Khronos Blender glTF 2.0 I/O",
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "glb",
                "byteLength": 612
            }
        ],
        "hasAnimations": false,
        "hasMaterials": true,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": false,
        "hasDefaultScene": true,
        "primitivesCount": 1,
        "maxAttributesUsed": 2
    }
}
```

It appears that all of these configurations result in a "lit" material, though, as in they are still affected by light. If it's fully emissive, shouldn't it not be affected by light, or am I mistaken?

**Comment by donmccurdy** [comment]
@dsinni just to clarify, none of this is implemented in the exporter except the Principled BSDF + Emissive example in https://github.com/KhronosGroup/glTF-Blender-IO/issues/83#issuecomment-443476099, which gives you an emissive PBR material without the performance benefit of an unlit material. We're discussing how to implement it, and what the exporter should look for, since the "Shadeless" checkbox no longer exists.

**Comment by donmccurdy** [comment]
Copying over some good points from @dsinni in https://github.com/KhronosGroup/glTF-Blender-IO/issues/111#issuecomment-444222581 — 

***

I'm not sure if this is the correct place for this, but I think it is worth noting that, currently, even if you disconnect the `Principled BSDF` shader, Blender 2.8 or the exporter still seems to include it, presumably on export.

Disconnected with `Roughness: 0`:
![image](https://user-images.githubusercontent.com/4733018/49466228-8403d480-f7cd-11e8-86c4-5985bd264ea8.png)

Gloss:
![image](https://user-images.githubusercontent.com/4733018/49466308-bc0b1780-f7cd-11e8-9071-5f8bd3910c72.png)

Disconnected with `Roughness: 1`:
![image](https://user-images.githubusercontent.com/4733018/49466713-bd890f80-f7ce-11e8-8449-20bb3f733507.png)

Matte:
![image](https://user-images.githubusercontent.com/4733018/49466761-dd203800-f7ce-11e8-9403-f876d914344f.png)

If the `Principled BSDF` shader's `Base Color` is a color other than black, the results are more obvious.

I've been noticing a bit of node/shader weirdness in the Blender Beta, so not sure which is responsible in this case.
