### ISSUE TITLE
Material node group - texture not exported

### ISSUE THREAD

**Issue by FraYoshi** [KhronosGroup/glTF-Blender-IO#830]
**Describe the bug**
When exporting meshes with materials, this is exported with textures
When exporting meshes with materials in which there's a node group, the textures are ignored

**To Reproduce**
1. create 2 objects
2. apply texture and material on each one (different textures).
3. create a node group for the shader in one the materials (i.e. the principled BSDF)
4. export the 2 objects as glTF Separate
5. note that the texture on the material with the node is not exported.

**Expected behavior**
The material node to be executed also for the node part and both the texture exported.

**Screenshots**
![Screenshot_2019-12-12_18-08-44](https://user-images.githubusercontent.com/14005514/70738084-4d339900-1d14-11ea-8102-59c41fc1325f.png)

**.blend file/ .gltf**
[glTF-node-group-export.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3957272/glTF-node-group-export.blend.zip)

**Version**
 - OS: Arch Linux x86_64
 - Kernel: 5.4.2-arch1-1
 - Blender Version 2.81.a-2

**Additional context**
I want to export for Godot.

**Comment by FraYoshi** [comment]
Packed the 2 texture into the blend file.

**Comment by emackey** [comment]
Hi, glTF is a runtime format that does not support every available configuration of Blender nodes.

Please see the documentation for supported glTF material settings:

https://docs.blender.org/manual/en/2.81/addons/import_export/io_scene_gltf2.html#exported-materials

**Comment by FraYoshi** [comment]
Thank You,
I suppose the solution would be to have a plugin to ungroup the materials before the export :)
