### ISSUE TITLE
Material is not exported to .gltf file.

### ISSUE THREAD

**Issue by FrankenApps** [KhronosGroup/glTF-Blender-IO#833]
**Describe the bug**
The material is not exported into the .gltf file.

**To Reproduce**
Export as .gltf (options don't seem to matter).

**Expected behavior**
The material should be exported.

**Screenshots**
![mat](https://user-images.githubusercontent.com/17967303/70865114-f5866f00-1f59-11ea-9d01-81dac4f58f55.png)
![mat2](https://user-images.githubusercontent.com/17967303/70865115-f5866f00-1f59-11ea-8239-5cd624a19975.png)

**.blend file/ .gltf**
The material should be accessible through the .blend file.
[material_problem.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3965094/material_problem.zip)

**Version**
 - OS: Win10
 - Blender Version 2.80

**Additional context**
I have not created this material, so I can not give any additional infos. It seems its a bit older, but since it works fine in blender, I think it should also be exported correctly. 
The problem might be related to the fact, that the image "WoodFine0007_L.jpg.001" is used as a color in the material.

**Comment by donmccurdy** [comment]
The variety of materials that can be created in Blender are (vastly) more numerous than what can be exported to any prortable format implemented across multiple tools, like glTF. This particular material is a custom node graph:

<img width="947" alt="Screen Shot 2019-12-15 at 5 26 41 PM" src="https://user-images.githubusercontent.com/1848368/70865672-51ec8d00-1f60-11ea-91ac-78566811b221.png">

To export this to glTF, you'll need to alter the material according to the documentation here: https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html. With a Principled BSDF node, you should be able to get the same visual result.

**Comment by emackey** [comment]
Thanks @donmccurdy.  The 2.81 link changed slightly:

https://docs.blender.org/manual/en/2.81/addons/import_export/io_scene_gltf2.html
