### ISSUE TITLE
Exporter is deleting animation data

### ISSUE THREAD

**Issue by adevart** [KhronosGroup/glTF-Blender-IO#835]
**Describe the bug**
If you animate an object and animate shape keys on the same object, the exporter erases the keyframes on the object.

**To Reproduce**
Start with a cube, set keyframe on say Y translation. Set keys at frame 0 and 50.
Go into the object data properties panel and add shape key (basis key and animation key).
Select the animation shape key and modify the object shape. Then set keyframes on the shape key (e.g value 0 at 0, value 1 at 50).
Save the Blender file.
Export as GLTF with type gltf embedded.
After exporting, saving and reloading the Blender file will show the object's translation keyframes have been deleted by the exporter.
You can also verify this by exporting twice. The first gltf export has both sets of keyframes, the second one only has the shape keys.

**Expected behavior**
Expected outcome is that the exporter doesn't remove animation keys in the Blender scene.

**Version**
 - OS: macOS 10.14
 - Blender Version 2.81

**Comment by julienduroure** [comment]
I cannot reproduce.
Can you please test with latest build (you can download it at https://builder.blender.org/download/ )

**Comment by adevart** [comment]
That's interesting, I tried 2.81a and it doesn't seem to export the translation keys in the first export so two successive exports are the same and only contain the shape key animations (should be both translation and shape keys) but the translation keyframes are removed from Blender for me.

before exporting:
https://ibb.co/mb4rv68
after exporting:
https://ibb.co/YRzzg1m

**Comment by scurest** [comment]
On line 60 here...

https://github.com/KhronosGroup/glTF-Blender-IO/blob/fd2896b1a22bcc61b6835871928e67b0ef9a0618/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animations.py#L59-L64

When you try to assign a shapekey action (`blender_action.id_root == 'KEY'`) to an object's `animation_data.action`, the assignment doesn't go through, so `animation_data.action` doesn't change, buuut its `.users` count is still decremented.

In this case, the CubeAction gets its user count decremented to 0, so it gets erased when doing a save-reload.
