### ISSUE TITLE
Take into account feedback from Blender Developers

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#84]
Cf feedback on : 
https://developer.blender.org/D3929

**Comment by julienduroure** [comment]
I handle import part of cleanups required

**Comment by UX3D-becher** [comment]
We applied the smaller ones of the suggested changes, to resolve the larger ones regarding the main __init__.py some refactoring of the exporter classes would be in order.

**Comment by julienduroure** [comment]
Hello @UX3D-becher,

Do you plan to commit more feedback changes within one week?
If not, I will submit a new version to developer.blender.org, but you will have to add some TODO for changes not planned to be done this week (see Campbell comment : https://developer.blender.org/D3929#89890)

**Comment by UX3D-becher** [comment]
I already added the TODOs, I think you can submit
