### ISSUE TITLE
No way to play imported animations

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#840]
There should be some way to play the animations that were imported. Cf #671.

edit: in case it helps anyone, I am using [this script](https://gist.github.com/scurest/ed3d80213fcf422bf4314eb4f9f514c6) for now

edit: for animations with one track, you can also just star that track. This should work for most character models.

**Comment by donmccurdy** [comment]
Since there's more detail in https://github.com/KhronosGroup/glTF-Blender-IO/issues/671, would you like us to reopen that issue and track remaining tasks there?

**Comment by scurest** [comment]
It's probably better to have a separate issue.

**Comment by donmccurdy** [comment]
That's fine, some of the details in that issue are important. Copying over:

> Is there a way to actually play an animation encoded as a set of identically-named tracks in Blender? Short of manually selecting them all the right actions? If not, could the addon add a widget somewhere that would do that automatically for you?

I'd prefer to avoid modifying Blender's UI through this addon — if that's even allowed? The addon is enabled by default, so from a user's perspective it would just be a new piece of native Blender UI, and I'm sure the Blender team would have some opinions about that. 🙂

A separate addon that can independently manage NLA tracks with similar names could be an option. Or, from [these](https://blender.stackexchange.com/a/752/43930) [suggestions](https://www.oneminutevideotutorials.com/2018/10/30/best-practices-for-creating-new-scenes-in-blender/), the importer could create separate scenes with linked object data — a scene for every animation. That seems very likely to complicate or inflate the export, though. :/

**Comment by scurest** [comment]
You could add an operator without putting in anywhere in the UI I guess (you'd have to call it from the operator search (F3)). The discoverability would be poor, but at least it'd exist.

I don't like the idea of using a scene per animation, but how would it even work? The animation_data is per object, not per scene. The only stuff that's per scene is, like, the markers and the frame start/end and stuff. From your first link AFAICT it looks like each animation would be picked out by one subrange of the timeline instead of our tracks-with-the-same-name thing?

> I'm sure the Blender team would have some opinions about that.

Did the Blender team have any kind of opinion about how we do animations in general? The need to organize multiple actions into one "animation" is definitely not unique to glTF.

**Comment by julienduroure** [comment]
Hello,
I don't like the idea of creating a new scene.
Modifying UI is allowed, but I don't like the idea, but we can add some new UI, for example in NLA (or GraphEditor or DopeSheet) property tabs or NLA tools. Having only an operator is also a possible way of doing, but is not really easy to find.
We eventually can add an option in addon preferences to enable/disable the new UI panel. Disabled by default, this will not change the default Blender layout.

**Comment by donmccurdy** [comment]
Ok, I'm happy to retract the idea of new scenes for each animation. 😅

> From your first link AFAICT it looks like each animation would be picked out by one subrange of the timeline instead of our tracks-with-the-same-name thing?

I think that practice is a holdover from workflows based on FBX, where support for multiple animations in a single file was inconsistent at best... I'm hoping we can avoid that here.

> Did the Blender team have any kind of opinion about how we do animations in general?

No idea, I haven't asked yet.

> Having only an operator is also a possible way of doing, but is not really easy to find.

How would that work? 

> ...we can add some new UI, for example in NLA (or GraphEditor or DopeSheet) property tabs or NLA tools.

Interesting... this is probably worth doing some mockups and getting feedback before we do a PR, but I'm open to the idea then.

**Comment by scurest** [comment]
You can usually make an animation play like this.

![Star all named tracks](https://user-images.githubusercontent.com/11024420/144963372-06f3d9b7-8aaa-414a-b79c-0d0cc2e5afc1.png)

I guess that's good enough.
