### ISSUE TITLE
Athena - Import Difference between Three.js and glTF-Blender-IO 

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#847]
**Describe the bug**
I'm trying to write a GLTF2 exporter. So the output is somewhat out of specification and rough, but the animation in this file plays differently in Blender compared to Three.js.

**To Reproduce**
1. Go to blender
2. Import gltf.
3. See that the female character's hair moves and not the entire body.

**Expected behavior**
The animation should play like in Codium's three.js.

**Screenshots**
![Screenshot from 2019-12-30 09-01-00](https://user-images.githubusercontent.com/32321/71592064-9ab94f80-2ae3-11ea-9ce6-a79e34a7c593.png)
![Screenshot from 2019-12-30 09-00-01](https://user-images.githubusercontent.com/32321/71592065-9b51e600-2ae3-11ea-87be-6cc8b2157b3e.png)

**.blend file/ .gltf**

[athena.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4010424/athena.zip)

**Version**
 - OS: Linux
 - Blender Version 2.81

**Additional context**
The main difference is three.js works and Blender import doesn't. So this import problem is blocking my use case of doing gltf2 exports to Blender.

**Comment by fire** [comment]
This version passes the vscode gltf2 validation.

[athena_v2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4011093/athena_v2.zip)

[athena_report.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4011096/athena_report.zip)

**Comment by donmccurdy** [comment]
Thanks for the fixed version! We can't guarantee that models failing validation will appear the same as in other engines, or at all, so that is appreciated.
