### ISSUE TITLE
Mannequin Top to Bottom - Import Difference between Three.js and glTF-Blender-IO 

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#850]
**Describe the bug**
I'm trying to write a GLTF2 exporter. The animation in this file plays differently in Blender compared to Three.js.

**To Reproduce**
1. Go to blender
2. Import gltf.
3. See that the entire level moves instead of the character.

**Expected behavior**
The animation should play like in Codium's three.js.

**Screenshots**

VSCodium's three.js

![Screen Shot 2020-01-01 at 9 42 59 AM](https://user-images.githubusercontent.com/32321/71644301-21546500-2c7b-11ea-8d34-631eac3d5554.png)

![Screen Shot 2020-01-01 at 9 49 48 AM](https://user-images.githubusercontent.com/32321/71644377-1cdc7c00-2c7c-11ea-920e-49493ddf0fb0.png)

VSCodium with Three.js
[Screen Recording 2020-01-01 at 9.46.33 AM.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4014343/Screen.Recording.2020-01-01.at.9.46.33.AM.zip)

Blender
[Screen Recording 2020-01-01 at 9.45.47 AM.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4014342/Screen.Recording.2020-01-01.at.9.45.47.AM.zip)

**.blend file/ .gltf**

[manne.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4014345/manne.blend.zip)

[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4014340/Archive.zip)

Has gltf2 validation report with 0 failures and some warnings.

**Version**
 - OS: Mac
 - Blender Version 2.81

**Additional context**
The main difference is three.js works and Blender import doesn't. So this import problem is blocking my use case of doing gltf2 exports to Blender.

**Comment by julienduroure** [comment]
This will be solved by #1378
