### ISSUE TITLE
export_user_extension missing hook for Scenes

### ISSUE THREAD

**Issue by jasowill** [KhronosGroup/glTF-Blender-IO#859]
Love this extension support! Currently the export_user_extension provides hooks for just about everything someone could want.  It does appear to be missing support for Scene objects.  Can this be added?

The particular use case desired here, is for adding extras for each scene that will provide an aspect ratio based on its current render_resolution values.

**Comment by jjcasmar** [comment]
Done in https://github.com/KhronosGroup/glTF-Blender-IO/pull/861
