### ISSUE TITLE
Custom normals from "Apply Modifiers" not used

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#860]
When using the "Apply Modifiers" checkbox during glTF export, some modifiers (such as the Bevel modifier's "Harden Normals" checkbox) can create custom normals that are not used during export.

It seems likely that the exporter is checking the original Blender object, not the temporary object with all modifiers applied, for the presence of "Custom split normal data", and getting the wrong answer.

Here's a test scene (made in Blender 2.81a).  The selected object has a Bevel modifier that uses hardened normals:

[HardSurfaceTest.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4027920/HardSurfaceTest.blend.zip)

When "Harden Normals" is turned off or not respected, the bevels interact with the triangulation and cause problems:

![HardenNormals_bad](https://user-images.githubusercontent.com/1235080/71851229-10a15600-30a4-11ea-98af-d094a99b0bab.png)

But, when "Harden Normals" works, the result is nice:

![HardenNormals_good](https://user-images.githubusercontent.com/1235080/71851260-24e55300-30a4-11ea-9e10-863aae7bd92b.png)

One workaround is simple, if the user is willing to switch to a "destructive" workflow:  Just manually apply the Bevel modifier prior to export.  Then, the custom normals are generated prior to export, and things work correctly.

But for a non-destructive workflow, a user may wish to keep their original modifier stack (which may include more than just a Bevel) and use the "Apply Modifiers" checkbox in the exporter.

The exporter should detect that the process of applying those modifiers to a temporary object has produced custom split normal data on that temporary object, and export the newly minted custom normals to glTF.

**Comment by julienduroure** [comment]
@emackey I didn't check in details, but the modifier should probably be added to the list of modifiers that can generate some custom normals, here : https://github.com/KhronosGroup/glTF-Blender-IO/blob/f782b04736ff5c68657832ddf3fa18175b294f07/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py#L253

**Comment by julienduroure** [comment]
@emackey You can test with #874
