### ISSUE TITLE
[Question] How the exporter changes colorspace for images

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#863]
I am creating an extension which uses a texture. That texture should be in linear space. If the user provides it in sRGB space, how should I converted? How is the exporter handling this for the pbr textures? What happens if the base color is connected to a texture mark as linear? I havent been able to find any relevant code doing some colorspace conversion, so is the exporter assuming that the textures are provided in the correct space and that the user has configured correctly the color space in the Texture node?

**Comment by Vinc3r** [comment]
I don't know about this exporter, but if this can help, I'm developping an addon helping with gltf workflow, and I've a function to fix colorspace value: https://github.com/Vinc3r/ReTiCo/blob/master/retico/materials.py#L85

**Comment by scurest** [comment]
> I haven't been able to find any relevant code doing some colorspace conversion, so is the exporter assuming that the textures are provided in the correct space and that the user has configured correctly the color space in the Texture node?

That's correct. It doesn't change the colorspace. It always just copies through the image you give it.

**Comment by jjcasmar** [comment]
So the user must provide the textures in the correct space and select the correct color space in the ImageTexture node. Thanks for the info.
