### ISSUE TITLE
Two extra files

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#878]
Today's build of Blender 2.82 Beta includes two files that are not on the 2.82 release branch here:

```
addons/io_scene_gltf2/blender/exp/gltf2_blender_generate_extras.py
addons/io_scene_gltf2/blender/imp/gltf2_blender_texture.py
```

These were deleted in 669688148a58 and 72acfb7f325b95 respectively.

**Comment by julienduroure** [comment]
I will delete them this week-end.
Note that this can be avoided by updating tools/convert to script 2.80 script, but because this script will be changed / deleted very soon after 2.79 support reval, let's continue to delete them manually when needed.

**Comment by scurest** [comment]
Can't you fix it by just deleting the `2.80` folder at the start of the script?

**Comment by julienduroure** [comment]
@scurest Yes, of course, this was my plan. But because this script will be soon deprecated (because of 2.79 support removal), not sure I will perform the change.

**Comment by julienduroure** [comment]
Done here:
https://developer.blender.org/rBA4d2fbf4bb56f6a8af61dc06f116b8779f7efc19a for 2.82
https://developer.blender.org/rBA1e165b809b66fbf19778dbb6f1a3f4e64efef031 for master merge
