### ISSUE TITLE
Transform +Y Up is not apply to armature bone

### ISSUE THREAD

**Issue by k8w** [KhronosGroup/glTF-Blender-IO#879]
**Describe the bug**
1. Export glTF, with `+Y Up` enabled
2. The rotation of the bone is not change (as the whole scene)

**Expected behavior**
The bone rotation is transformed by the `+Y Up`.
Just like it in export fbx, there is a setting `Armature/Primary Bone Axis`

**Version**
 - OS: [e.g. macOS, linux] Win10
 - Blender Version [e.g. 2.79, 2.80 (2019-03-18)] 2.81a

**Comment by julienduroure** [comment]
Seems this ticket is quite old, and no more up to date with recent development.
If there are still some issue regarding orientation, please create a new ticket
