### ISSUE TITLE
Refactor __init__ operators and export_settings

### ISSUE THREAD

**Issue by UX3D-becher** [KhronosGroup/glTF-Blender-IO#88]
The gltf and glb operators should be merged as mentioned in #84 
Also export_settings should be a class instead of a dict. Some members could be removed

**Comment by donmccurdy** [comment]
This was completed earlier.

**Comment by donmccurdy** [comment]
> Also export_settings should be a class instead of a dict. Some members could be removed

... well, that part wasn't done. If someone has suggestions for the best way to refactor this, a new issue or a PR would be welcome.
