### ISSUE TITLE
Animation keyframes are exported for empty tracks

### ISSUE THREAD

**Issue by Psychpsyo** [KhronosGroup/glTF-Blender-IO#881]
The exporter currently exports keyframes in the default position for bones that aren't affected by an animation.

How to reproduce:
-Create an armature with at least two bones
-Animate one of them
-Export as .glb
-Import that file
-The bone that wasn't animated now has keyframes

Expected behavior:
The bone that didn't have any keyframes before exporting shouldn't have any after doing so either.

(Blender Version 2.81a)

Why is this an issue?
This becomes problematic when trying to mix the exported animations elsewhere.
If I animated a character that has seperate animations for the legs and the arms so he can do things with his arms while running or standing, the arm animation now also includes the legs standing still. So when it gets mixed with the running animation the running doesn't move as much anymore.

**Comment by julienduroure** [comment]
This is currently the expected behaviour, when "always sampled animation" is checked (and this is checked by default). Because some deformation bones can have no animation, but these bones need to be animated in glTF to export correctly the animation.
If all your deformation bones are animated (so you don't use constraints), you can try exporting with "sampled animation" unchecked.

**Comment by julienduroure** [comment]
Did you solve your issue, testing with "sampled animation" unchecked?
Can this ticket be closed?

**Comment by Psychpsyo** [comment]
Yes, that did fix it. This can be closed.

**Comment by julienduroure** [comment]
Ok, thanks!

**Comment by kungfooman** [comment]
> Did you solve your issue, testing with "sampled animation" unchecked?

Lifesaver! I tried around for some time to get an additive animation going and this setting was the last issue 👍 

I basically just made a simple additive greet animation (just animated the arm):

<img width="913" height="182" alt="Image" src="https://github.com/user-attachments/assets/178fc863-60c2-497d-bdbb-19d74b92001b" />

And after exporting it was all mixed up with other animations.

```js
/**
 * @param {Character} character
 */
function playGreetAnim(character) {
  const {animations, mixer} = character;
  const greetAnimation = animations.find(animation => animation.name === "greet");
  if (!greetAnimation) {
    return false;
  }
  const additiveGreetAnimation = THREE.AnimationUtils.makeClipAdditive(greetAnimation);
  const currentActions = mixer._actions.filter(action => action.isRunning());
  const currentAction = currentActions.length > 0 ? currentActions[0] : null;
  const greetAction = mixer.clipAction(additiveGreetAnimation);
  greetAction.setLoop(THREE.LoopOnce);
  greetAction.clampWhenFinished = true;
  greetAction.blendMode = THREE.AdditiveAnimationBlendMode;
  if (currentAction) {
    greetAction.reset().fadeIn(0.2).play();
  } else {
    greetAction.play();
  }
  return true;
}
```

(not the most optimized code, but just happy that it works now)

This is the option in Blender 3.3.1 just for reference:

<img width="264" height="512" alt="Image" src="https://github.com/user-attachments/assets/3ae2ee00-5990-479f-a4ef-49ce52c96c3b" />
