### ISSUE TITLE
Export: proposal for image format options

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#882]
I want to propose changes to the behaviour of the image format options in the exporter

### Automatic (the default)

Basically I want to propose doing this

````py
if export image corresponds to an existing image:
    if existing_image.file_format == 'JPEG':
        file_format = 'JPEG'
    else:
        file_format = 'PNG'
else:
    file_format = 'PNG'
````

IOW, this option would always favor PNGs except that (quoting from #203)

> if the exporter already has access to a source PNG or JPG, it should be just copying the already-compressed data from there directly

This fixes two things:

* Currently this option does not make good use of an already-compressed JPEG. It will only encode an existing image as a JPEG if its _name_ ends with `.jpg`/`.jpeg`. It would be better not to use the name, but to look at the `image.file_format` field.

    This can make a big difference in performance. For Sponza for instance

    * exporting with Automatic, all the JPEGs are re-encoded as PNGs
        * export time: 32s
        * resulting filesize: 116M
    * exporting with JPEG Format (.jpg), all JPEGs just copied over
        * export time: 22s
        * resulting filesize: 45M
* When an image needs to be packed from channels, the packed image can sometimes be a JPEG if one of the constituents is (note: only sometimes!). This is lossy and causes channel-bleed (#818). I think a better default is to prefer being lossless.

### PNG format (.png)

Remove it. Since Automatic would favor PNGs, it's main difference would be that it re-encodes JPEGs as PNG. It would basically become a "make my file bigger" option.

### JPEG format (.jpg)

This is okay, no change.

**Comment by emackey** [comment]
I like this idea.  In particular I think there should never be a case where an existing JPG needlessly becomes a PNG without any channel reassignments.

**Comment by donmccurdy** [comment]
Agreed. 👍

**Comment by scurest** [comment]
Okay, cool. I put up a PR for it.

**Comment by emackey** [comment]
Fixed in #883.

**Comment by HumanRobot3D** [comment]
> When an image needs to be packed from channels, the packed image can sometimes be a JPEG if one of the constituents is (note: only sometimes!). This is lossy and causes channel-bleed (#818). I think a better default is to prefer being lossless.

If all constituents are JPEG I think the resulting packed image should be JPEG too.

https://github.com/KhronosGroup/glTF-Blender-IO/issues/1318

**Comment by donmccurdy** [comment]
More recent discussion in: https://github.com/KhronosGroup/glTF-Blender-IO/pull/1099
