### ISSUE TITLE
Use same way of reporting in both importer & exporter

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#89]
Currently, there is some different way of reporting in importer and exporter.
Review from Blender devs proposed a third way (ProgressReport from bpy_extras.wm_utils.progress_report).

We need to discuss what is the better way, and implement it in entire addon code

**Comment by donmccurdy** [comment]
Do any of the options allow end-users to see hints/errors/warnings without starting Blender from the CLI? If there is a way, that would probably be my vote.

**Comment by UX3D-becher** [comment]
Maybe for some problems we can use https://docs.blender.org/api/2.78a/bpy.types.Operator.html#bpy.types.Operator.report

ProgressReport does not seem to be documented anywhere

**Comment by julienduroure** [comment]
This is now implemented \o/
