### ISSUE TITLE
Exported PNG transparency is messed up when texture is connected to "Alpha" socket

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#895]
Exported texture transparency is messed up when the texture is connected to the "Alpha" socket of "Principled BSDF" shader. 

Material setup: 

![Screenshot_2020-01-27_15-22-56](https://user-images.githubusercontent.com/5787647/73172736-f5f95480-4118-11ea-9dd7-7a57a3073c06.png)

Original PNG texture:

![Material_59 003_baseColor](https://user-images.githubusercontent.com/5787647/73172765-03aeda00-4119-11ea-8b6f-5119e831e5c3.png)

Output PNG texture: 

![Material_59_003_baseColor](https://user-images.githubusercontent.com/5787647/73172826-2214d580-4119-11ea-9ae7-28972aec3c03.png)

.blend file: 
[untitled.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4116950/untitled.blend.zip)

Linux OS
Blender v 2.81
Gltf Addon v1.2.6

**Comment by julienduroure** [comment]
Hello,
The 1.2.6 version should not be "out of the box" be installed in 2.81 version, except if you install manually a newer version than the addon version packaged with Blender. Can you please confirm that you indeed install a newer version manually?

If this is the case, can you please test if you get the same result with 2.82 beta? (that you can download on builder.blender.org)

**Comment by Ali-RS** [comment]
Note, I updated my first post. (It seems the same behavior happens even if the texture is not packed) 

> Can you please confirm that you indeed install a newer version manually?

Yes, I installed a newer version manually from the master branch.

> If this is the case, can you please test if you get the same result with 2.82 beta? 

Yes, I get the same result.

**Comment by Ali-RS** [comment]
Seems it is broken somewhere between 1.1.29 and 1.1.34.

**Comment by julienduroure** [comment]
@scurest seems to be linked to perf commits you did. Can you please have a look?

**Comment by scurest** [comment]
This fixes it

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py
index e99d71b..c389ba1 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py
@@ -160,6 +160,8 @@ def __get_image_data(sockets_or_slots, export_settings) -> ExportImage:
                         'G': Channel.G,
                         'B': Channel.B,
                     }[elem.from_socket.name]
+                if elem.from_socket.name == 'Alpha':
+                    src_chan = Channel.A
 
             dst_chan = None

````

I'd like to look a little further into why the old code didn't need this though.

**Comment by scurest** [comment]
Actually I can reproduce this as far back as 0.9.79 (that's as far back as I can go before I would need to start using older versions of Blender).

@Ali-RS Does it work for you in 1.1.29?

**Comment by Ali-RS** [comment]
Thanks for the quick fix :)
