### ISSUE TITLE
camera fov doesn't get exported correctly 

### ISSUE THREAD

**Issue by aguaviva** [KhronosGroup/glTF-Blender-IO#896]
**Describe the bug**
camera fov doesn't get exported correctly 

**To Reproduce**
Create a camera, set a specific fov, for example 40. Check the fov in the GLTF file, the value exported is the value set in Beldner, that is 40 but divided by 100. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5200915/73176209-2b4b7580-410c-11ea-810e-8fe2f924e0d0.png)

**Version**
 - Blender 2.81

**Comment by julienduroure** [comment]
Hello,
This field, yfov,  is the vertical field of view, defined in radian, not in degree.
This field depends on your aspectRatio and your Sensor Fit value, that you don't display in your screenshot.

**Comment by aguaviva** [comment]
ah you are right! thanks!
