### ISSUE TITLE
Textures not imported with GLTF model

### ISSUE THREAD

**Issue by Casuallynoted** [KhronosGroup/glTF-Blender-IO#899]
**Describe the bug**
I have a set of GLTF models all exported from the same tool. Each of them is made to the GLTF 2.0 spec, but for some reason blender doesn't import the textures- only the material names.

**To Reproduce**
1. Open Blender 2.81a
2. Import roc_r0_fld01_0x28d90001.gltf (Or any GLTF file from this tool that I've tried)
3. File imports, but render mode produces just a white appearance and texture info is not in material.
4. Exporting does not preserve texture information.

**Expected behavior**
All other tools I've used to process/view these GLTFs import the textures perfectly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6272557/73296116-12f45d00-41d7-11ea-8cbe-f3c717117e9e.png)

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.
https://drive.google.com/file/d/1-UpeDjKqn5ZPwviY4L1XHYgbZ-Bgo33j/view?usp=sharing

Apologies in advance for all the .meta files, I'm using this for a Unity project

**Version**
 - OS: Windows
 - Blender Version 2.81a

**Comment by donmccurdy** [comment]
I'm not sure what the takhlaq/GlTFExporter tool is, but it is creating invalid glTF files. You can run the `.gltf` file through https://github.khronos.org/glTF-Validator/ for a full report. Two primary issues:

* The model reports a `KHR_pbrSpecularGlossiness` extension, and there is no such thing. This is probably a typo, and should be `KHR_materials_pbrSpecularGlossiness`.
* The model reports a `MSFT_texture_dds` extension, which is a Microsoft-specific extension almost exclusively supported by Microsoft Mixed Reality toolkits, for DDS compressed textures. This extension is not supported by the Blender importer, you'll need to use PNG or JPG textures instead.

**Comment by donmccurdy** [comment]
I'm also not sure how well Blender itself supports DDS textures... See https://blender.stackexchange.com/a/111117/43930, that may be a more fundamental issue if there are still rendering problems.

**Comment by Casuallynoted** [comment]
> 
> 
> I'm not sure what the takhlaq/GlTFExporter tool is, but it is creating invalid glTF files. You can run the `.gltf` file through https://github.khronos.org/glTF-Validator/ for a full report. Two primary issues:
> 
>     * The model reports a `KHR_pbrSpecularGlossiness` extension, and there is no such thing. This is probably a typo, and should be `KHR_materials_pbrSpecularGlossiness`.
> 
>     * The model reports a `MSFT_texture_dds` extension, which is a Microsoft-specific extension almost exclusively supported by Microsoft Mixed Reality toolkits, for DDS compressed textures. This extension is not supported by the Blender importer, you'll need to use PNG or JPG textures instead.

Thank you so much for the info! I've relayed the info to the creator of the tool, and we have a new version of the file exported using PNG and with the typo fixed. However it still imports without textures. I'll include an updated version of the file here-

https://drive.google.com/file/d/1ULJTtK2AQrRjOfXQOpoiz6iLFGRhQsGG/view?usp=sharing

**Comment by Casuallynoted** [comment]
Wait got it, it's cause of the extension! Fixed, I believe!

**Comment by Casuallynoted** [comment]
I mistakenly said earlier that I thought I had fixed it but sadly I didn't. I thought perhaps removing the extension altogether for DDS would allow PNGs to be loaded but right now Blender still is giving me no textures. Sorry for the hasty misinformation on that one!

**Comment by emackey** [comment]
This addon doesn't do a great job with `KHR_materials_pbrSpecularGlossiness` (see #303 for example).  The next incarnation of glTF's PBR model is planned to be extensions to the core metal/rough material, and `KHR_materials_pbrSpecularGlossiness` will likely get left behind as a legacy option for older tools.  Is there any way the converter could be upgraded to use glTF's core material model?

**Comment by Casuallynoted** [comment]
> 
> 
> This addon doesn't do a great job with `KHR_materials_pbrSpecularGlossiness` (see #303 for example). The next incarnation of glTF's PBR model is planned to be extensions to the core metal/rough material, and `KHR_materials_pbrSpecularGlossiness` will likely get left behind as a legacy option for older tools. Is there any way the converter could be upgraded to use glTF's core material model?

Sadly, I don't believe so for this model. What's weird is even when I import to Unity now it also doesn't import textures. It did before. Is there something wrong with the GLTF that might prevent it from loading PNGs in general?

**Comment by lexaknyazev** [comment]
@Casuallynoted 
Just so you know, there are several other issues with this asset that may affect its loading:
- The `MSFT_texture_dds` is not actually used but it is still declared.
- There are lots of non-normalized normal vectors. This may affect correctness of applied lighting.
- There are lots of empty nodes, unused textures, and unused texture coordinates. This may affect loading performance.

All these issues can be verified offline by using the official validation tool. Current release can be downloaded [here](https://github.com/KhronosGroup/glTF-Validator/releases/tag/2.0.0-dev.3.2).

**Comment by donmccurdy** [comment]
A couple more notes:

The `MSFT_texture_dds` reference prevents my viewer (gltf-viewer.donmccurdy.com/) from opening the file, other than that it does load there.

> Is there any way the converter could be upgraded to use glTF's core material model?

Although the model uses `KHR_materials_pbrSpecularGlossiness`, it doesn't need it — there are no spec/gloss factors or textures in any of the materials, and all diffuse textures are also referenced as base color textures. Deleting all the `KHR_materials_pbrSpecularGlossiness` references should not affect this model.

That said, all the materials include `"metallicFactor": 1`. You probably don't want that to be so high, 0 would be a better default.

With all of those issues fixed, I am able to open the model in Blender and see textures. But (at least on my laptop...) Blender is clearly unhappy about something, as the textures seem to flicker and disappear sometimes. I think it's struggling with the size of the scene, or number of distinct objects, or something like that?

Opening in my viewer, better results, but still very low framerate:

<img width="855" alt="Screen Shot 2020-01-29 at 10 35 41 AM" src="https://user-images.githubusercontent.com/1848368/73387696-c582f900-4285-11ea-85f8-064c1b83b3d9.png">

Here's the version of the file patched by hand:

https://drive.google.com/open?id=1DuD4f4ZqP3uPcWHSMjRRB6FJxextE9IE

**Comment by donmccurdy** [comment]
^Aside, if you have a smaller file created with this same tool, it might be easier to help you as this one is very large and a bit harder to work with. :)

**Comment by julienduroure** [comment]
This ticket is quite old. Can it be closed?
We don't received any simple test case.
Have you still any problems with recent Blender version?

**Comment by yvesgurcan** [comment]
It seems that this issue wasn't resolved and should be re-opened. I came across the same issue where textures are not loaded with this asset: https://wetransfer.com/downloads/373ba60787f779432b1a78d63e2fca3f20200930180439/16c903ae4c427b6b0cac1052129aa7dc20200930180505/a49262. It's a fairly simple 3D model I found for free. When I export the `.gltf` file, the result is always untextured.

**Comment by donmccurdy** [comment]
The issue with that model is really https://github.com/KhronosGroup/glTF-Blender-IO/issues/272 — this addon does not support spec/gloss PBR materials.

I put together a tool that converts spec/gloss PBR to metal/rough PBR, which this extension does support. It's not perfect yet, but does handle a lot (including your example). See the `metalrough` command on https://gltf-transform.donmccurdy.com/cli.html.

![Screen Shot 2020-09-30 at 11 21 57 AM](https://user-images.githubusercontent.com/1848368/94724453-2a0fbf80-030f-11eb-83e5-1e6ea3693336.png)

**Comment by yvesgurcan** [comment]
Thank you! Converting the asset with `gltf-transform metalrough` did the trick. I wasn't familiar with specular and gloss physically based rendering. I learnt something today :)

**Comment by TristonH55** [comment]
did this issue get fixed as i have the same issue 
first image is what i want 
https://gyazo.com/035312252537f029fb40c6c876ac1f7b
second image is what i get:
https://gyazo.com/1b7afe388254ed69b611c11912686b91

**Comment by donmccurdy** [comment]
We haven't identified any bug to be fixed here. There are certain limitations with regard to what can be imported or exported, which are unlikely to change. It may also be that your material is not set up correctly. If you would like to open a new issue with details (the file and steps to reproduce) we may be able to help you identify what is happening in your case.

**Comment by TristonH55** [comment]
ok but i cant send you the blender  file on here.  is there a discord to chat on with you. that way i can send you a blender file

**Comment by donmccurdy** [comment]
Sorry, I'm not able to provide 1:1 support.

**Comment by TristonH55** [comment]
ok understand. 
made a quick video with whats happening https://www.youtube.com/watch?v=aMvOXqwpheA

**Comment by donmccurdy** [comment]
There are many ways to configure materials in Blender, but very few of them can be exported to other software. I don't see your model's material configuration in this video, but to export to glTF you would need to use the Principled BSDF material and configure its inputs in the supported arrangements here: https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html

**Comment by TristonH55** [comment]
so i updated my blender to the new v3 and when i try now i get https://gyazo.com/d9fab12d4146fbf8196169ce4152de03

**Comment by donmccurdy** [comment]
If you're able to share steps to reproduce the error, please open a new issue.  It's related to animation export I think.

The materials supported for export to glTF has not changed much in Blender 2.90 vs Blender 3.0, so I don't think that any version upgrade is necessary for the material question you shared before.

**Comment by TristonH55** [comment]
where can i get some help with this issue as its still not working for me, cant seem to find any help on this topic . 
Daz to blender then saving as GLTF the file that is output is white without materials/textures or colour. However all the nodes look like they are there as i can see the BSDF box. https://www.youtube.com/watch?v=3TLxpdo8O7M
