### ISSUE TITLE
How to manage sync with blender code?

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#90]
See question here:
https://developer.blender.org/D3929#90250

(For now, I just write here the last commit on github that is included in blender, just in case we will need it: 321b04d49a4ef87dbb85974f6486fa624a3f5788)

**Comment by donmccurdy** [comment]
@julienduroure do you have a preference on how to manage this, and how we can help?

**Comment by julienduroure** [comment]
Currently, I merge this repo into blender repo time to time (every 3/4 days). I'm using some scripts available in tool/ dir to convert from 2.79+2.80 to pure 2.80 code.

It's not a problem for me, so I think we can close this issue
