### ISSUE TITLE
CI: tests are down

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#903]
The format of the download URL on builder.blender.org changed again. Now looks like

```
/download/blender-2.82-8285a12f4ed4-linux64.tar.xz
```

**Comment by julienduroure** [comment]
Probably linked to this commit:
https://developer.blender.org/rB8285a12f4ed40901ba191a9b5b237ebdeab295c4

**Comment by emackey** [comment]
Thanks @scurest and @julienduroure
