### ISSUE TITLE
Traceback errors on export from Blender 2.8

### ISSUE THREAD

**Issue by dsinni** [KhronosGroup/glTF-Blender-IO#91]
First, I'd like to say that you folks are doing killer work, and I enthusiastically look forward to being able to use this regularly with the `Principled BSDF` shader in the upcoming Blender release.

That said, I'm not sure how well the exporter should be working currently, as I understand it's still in development, as is Blender `2.8`, which makes it difficult for me to pinpoint the source of the errors.

I can't seem to export a simple cube to `gltf` or `glb` using the latest versions of both the exporter and Blender `2.8` with the settings below:

![image](https://user-images.githubusercontent.com/4733018/48974286-3bf0ef00-f022-11e8-962f-00ba210ac575.png)

I use practically the same workflow and settings with Blender `2.79b` and the `glTF-Blender-Exporter`, except I use the included `glTF Metallic Roughness` PBR nodes. In this case, I'm trying to use Blender's `Principled BSDF` shader and I'm getting the following errors:

![image](https://user-images.githubusercontent.com/4733018/48974385-feda2c00-f024-11e8-849f-8db2ece8daed.png)

This seems to be happening specifically when I check `Export selected only`, which I use often in my workflow.

---

I'm getting similar errors when trying the other options:

![image](https://user-images.githubusercontent.com/4733018/48974405-1e258900-f026-11e8-8db6-1a639c9efa89.png)

![image](https://user-images.githubusercontent.com/4733018/48974407-3a292a80-f026-11e8-8b91-e8aa15af91aa.png)

---

![image](https://user-images.githubusercontent.com/4733018/48974438-904a9d80-f027-11e8-91a0-0b4ba9d8aef9.png)

![image](https://user-images.githubusercontent.com/4733018/48974436-7f019100-f027-11e8-9728-7a798eeebb8f.png)

---

The only combination that appears to work is this:

![image](https://user-images.githubusercontent.com/4733018/48974448-f800e880-f027-11e8-8a96-9a02dc662f6a.png)

However, it only seems to work the first time. After trying to re-export with those same settings, the resulting file is corrupt. It also exports all layers and doesn't let you select objects, which isn't typically ideal.

---

Here is a zip with the `.blend` file and a sample of the corrupt file:
[exporter_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2612738/exporter_test.zip)

---

Blender version:
![image](https://user-images.githubusercontent.com/4733018/48974279-0d731400-f022-11e8-8327-68d25bccd1a7.png)

Exporter version:
![image](https://user-images.githubusercontent.com/4733018/48974331-347e1580-f023-11e8-81b1-398182a490be.png)

OS: Windows 10 x64

**Comment by julienduroure** [comment]
Multiple bugs/enhancement here : 

- [ ] importer bug with multiple root nodes
- [ ] importer enhancement when no nodes in gltf file
- [ ] Exporter Selection check
- [ ] Exporter layer/collection check
- [ ] Exporter 2 times in a row

**Comment by emackey** [comment]
I get the same error if I start Blender 2.8 and try to export the default cube.

> `2.80\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 52, in __filter_node`
> `    if export_settings[gltf2_blender_export_keys.SELECTED] and not blender_object.select:
AttributeError: 'Object' object has no attribute 'select'`
>
> `location: <unknown location>:-1`

**Comment by julienduroure** [comment]
@emackey This error is already fixed in master and in blender 2.8 git. This will be available in tomorrow's build

Still have to work on layer export option (see my TODO list on first comment of this issue )

**Comment by koloved** [comment]
Thank  you! =)

**Comment by UX3D-becher** [comment]
In the most current commit 1ea67904175854feeebd70cec20d7222f8b4aa97  the issue with exporting two times in a row should be resolved. Also I removed the non functioning option to not export all layers

**Comment by dsinni** [comment]
Nice! Thanks, @UX3D-becher.

I'm assuming `Export selected only should also now work as expected?

Will test shortly.

**Comment by dsinni** [comment]
Most of this appears to be working correctly now as far as I can tell. Kudos!

I noticed that the latest Blender 2.8 build now includes the importer/exporter, but I still needed to update it to get the bug fixes.

Should I close this?

**Comment by dsinni** [comment]
Right on. Thanks, @julienduroure!

**Comment by julienduroure** [comment]
Is now in Blender repo

**Comment by NightOwlVR** [comment]
Hi people! I am also using Blender 2.8 with the Verge3D add-on and getting the keyword argument error. What does this mean and how can I fix it? I was able to export before with the same settings but looks like something has gone wrong somewhere down the line and cannot figure out what! Please see my attached screenshot.

![keyword argument error](https://user-images.githubusercontent.com/39202853/53986688-c3b4c200-4116-11e9-9563-bf9e600745a2.jpg)

**Comment by emackey** [comment]
@NightOwlVR Looks like you've attached a new problem to an old, resolved, closed issue.  Can you open a new issue for that, and upload a zipped blend file to go with it?  Thanks.

**Comment by emackey** [comment]
@NightOwlVR Also we're the open-source plugin, which is different from Verge 3D.  You may need to file your issue with Soft8soft tech support if you're using their plugin instead of ours.

**Comment by NightOwlVR** [comment]
Oh yes, I see. Thanks for the reply! I will try to make a new post.

**Comment by NightOwlVR** [comment]
@emackey how do I open a new issue?
