### ISSUE TITLE
Question about vertex count increasing after exporting

### ISSUE THREAD

**Issue by Ali-RS** [KhronosGroup/glTF-Blender-IO#912]
Hi

Will appreciate if someone can help me with this issue 

I imported a cube model from a .fbx file into Blender, it shows cube has 56 vertices. After exporting to .gltf number of vertices becomes 80. I thought this is due to discontinuous UVs of the model.

![Screenshot_2020-02-03_20-48-38](https://user-images.githubusercontent.com/5787647/73675323-6e3ab980-46c7-11ea-9fcd-b7cfdfcd5b99.jpg)

So I snapped the separate UV vertices positions (bottom face) to the position of top face UVs (at center) and then merged them with (UV -> Weld/Align -> Merge UV by distance) and applied a triangulation modifier on the model and exported it, 

![Screenshot_2020-02-03_20-49-45](https://user-images.githubusercontent.com/5787647/73675347-7bf03f00-46c7-11ea-8cd2-012a57858657.jpg)

but yet I see the number of vertices is 80. I am not a Blender expert and probably I am doing something wrong.

I also tried to export it to .obj file and seems to work fine for .obj and the number of vertices is 56.

Here are the blender files: 
[files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4149109/files.zip)

(One of them is the original file and the other one is UV fixed and triangulated)

Using Blender v2.81 and addon v1.2.17 (installed manually from master branch).

Regards

**Comment by scurest** [comment]
> I thought this is due to discontinuous UVs of the model.

You were right :) In glTF every vert has a unique UV, unlike Blender or .obj or .dae where it has one UV per face it's in. (This is how graphics APIs like OpenGL work.)

So open up the UV editor and turn on _UV Sync Selection_. If you select _one_ vert in the 3D View and _more than one_ vert is selected in the UV Editor, that vert will get split into multiple verts (one per distinct UV coordinate) when exporting.

![uv-dis](https://user-images.githubusercontent.com/11024420/73680340-acad8580-4681-11ea-86f2-04422745c15f.png)

Snapping the UVs from the bottom face to the UVs from the top face doesn't do anything. Separate verts in Blender are always separate in glTF. You could decrease it by one by welding the two UV-verts in the picture above together (with UV -> Weld/Align -> Weld), but some amount of splitting is always going to happen when exporting to glTF.

**Comment by Ali-RS** [comment]
Ah, I see, that explains it. Thank you so much for your explanation :)
