### ISSUE TITLE
JPG Compression Slider

### ISSUE THREAD

**Issue by cptSwing** [KhronosGroup/glTF-Blender-IO#915]
It'd be great to have control over the quality of jpg files that get exported as gltf/glb (converted from png in my case). As it stands, it's an obtuse setting I haven't been able to change anywhere.

**Comment by julienduroure** [comment]
This is now possible. Until now, blender API didn't have any option to set the compression quality.

See #1794

**Comment by julienduroure** [comment]
Closing, as this feature is now implemented
