### ISSUE TITLE
Exporting object with correct UV map defined in Shader Editor [DRACO]

### ISSUE THREAD

**Issue by Nizaxx** [KhronosGroup/glTF-Blender-IO#916]
**Describe the bug**
Exporter is creating GLTF object with first UV map from the list "UV maps" ignoring "UV map" node in material in Shader Editor WHEN draco compression is turned on

**To Reproduce**
Compare applied texture on exported objects with and without draco compression 

**Expected behavior**
Result should look like without draco compression

**Screenshots**
![image](https://user-images.githubusercontent.com/10244054/74027863-5013d880-49a9-11ea-9eb7-0f710e50f48b.png)

**.blend file/ .gltf**
blend file with 2 gltf samples (correct and wrong result)
[github-issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4170623/github-issue.zip)

**Version**
- OS: [Windows10 Home]
- Blender Version [2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: f6cb5f54494e, type: build date: 2019-07-29, 09:44 AM platform: Windows]

**Additional context**

**Comment by julienduroure** [comment]
Can you please test with a recent version of blender, for example blender 2.82 beta (stable version will be release next week).
You can download them here : builder.blender.org

**Comment by julienduroure** [comment]
@McNopper Can you please have a look?

**Comment by UX3D-nopper** [comment]
My team will have a look at it.

**Comment by Nizaxx** [comment]
> Can you please test with a recent version of blender, for example blender 2.82 beta (stable version will be release next week).
> You can download them here : builder.blender.org

sorry. Same problem still exists at [2.82 (sub 7), branch: master, commit date: 2020-02-12 16:20, hash: 77d23b0bd76f, type: Release build date: 2020-02-13, 01:56:46 platform: Windows]
Heres GLTF file from that version + texture which for some reason is missing in blend file in previous zip. Problem exists not only with DRACO but also without it (sorry also for that)
[github-issue2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4263140/github-issue2.zip)
And I want to add that correct UV map is applied in windows 10 3D viewer
![image](https://user-images.githubusercontent.com/10244054/75471540-af567e80-5992-11ea-8297-67edfc1a6654.png)
version:
![image](https://user-images.githubusercontent.com/10244054/75472226-6bb04480-5993-11ea-81b6-4b1b4c5309e2.png)
same file at https://gltf-viewer.donmccurdy.com/
![image](https://user-images.githubusercontent.com/10244054/75472051-3d326980-5993-11ea-9706-2a41fff45ece.png)

**Comment by Rawdreen** [comment]
> > Can you please test with a recent version of blender, for example blender 2.82 beta (stable version will be release next week).
> > You can download them here : builder.blender.org
> 
> sorry. Same problem still exists at [2.82 (sub 7), branch: master, commit date: 2020-02-12 16:20, hash: 77d23b0bd76f, type: Release build date: 2020-02-13, 01:56:46 platform: Windows]
> Heres GLTF file from that version + texture which for some reason is missing in blend file in previous zip. Problem exists not only with DRACO but also without it (sorry also for that)
> [github-issue2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4263140/github-issue2.zip)
> And I want to add that correct UV map is applied in windows 10 3D viewer
> ![image](https://user-images.githubusercontent.com/10244054/75471540-af567e80-5992-11ea-8297-67edfc1a6654.png)
> version:
> ![image](https://user-images.githubusercontent.com/10244054/75472226-6bb04480-5993-11ea-81b6-4b1b4c5309e2.png)
> same file at https://gltf-viewer.donmccurdy.com/
> ![image](https://user-images.githubusercontent.com/10244054/75472051-3d326980-5993-11ea-9706-2a41fff45ece.png)

Try method explained in #993 issue.

**Comment by Rawdreen** [comment]
Hi @Nizaxx !
Try method explained in #993 issue. It might work for you.
