### ISSUE TITLE
Animation exporter is dependent on editor state

### ISSUE THREAD

**Issue by j-conrad** [KhronosGroup/glTF-Blender-IO#923]
When exporting animation with NLA tracks, the result varies depending upon the current state of the Action Editor/NLA Editor. This causes unexpected results because the exporter itself changes the state of the editor(s) upon completion and doesn't reset the exported object(s) back to their initial state.

**To Reproduce**
1. Open the included blend file: _SkinnedMesh.blend_
2. Select the Armature if it isn't already
3. Note that the Action Editor window is empty, and the active action in the NLA Editor window displays _No Action_
![image](https://user-images.githubusercontent.com/31968496/74489853-7b9c3480-4e7b-11ea-96d9-a6f4a2a097d3.png)

3. Export the file as a .glb (leave all the default settings)
4. Open the exported .glb in Don McCurdy's glTF viewer:  https://gltf-viewer.donmccurdy.com/
5. Note that the ZigZag animation is a clean loop, while the other 'Bend' animations start with the mesh in a bent position. This is expected.
6. Go back to Blender and note what happened after exporting: The Action Editor window is now populated with one of the actions (in my case, _'Bend_Right'_), and the active action in the NLA Editor window displays this animation (again, _'Bend_Right'_)
7. If you were to export again, your exported .glb would be incorrectly starting in this 'bend right' pose:  
![image](https://user-images.githubusercontent.com/31968496/74490147-7986a580-4e7c-11ea-9f95-91e1b3ec6d5a.png)
8. The user now must do a couple things to export correctly again. They must first clear the Action Editor window:
![image](https://user-images.githubusercontent.com/31968496/74490229-b2bf1580-4e7c-11ea-810d-17450f8e4d75.png)
Still, the mesh is in the incorrect pose. Fortunately, in this case, the ZigZag animation starts in the 'rest' position which means you can toggle the Star icon in the NLA editor to reset it:
![image](https://user-images.githubusercontent.com/31968496/74490335-19443380-4e7d-11ea-97eb-19ec51e68ea0.png)
9. Now, when exporting, the .glb will be correct. But the fact that the exporter can put the .blend file into a potentially 'broken' state can cause problems, especially when workflows are shared amongst multiple users (and especially users who may be unfamiliar with the exporter's quirks).

**Expected behavior**
The exporter should return the .blend file to the state it was in prior to exporting.

**.blend file/ .gltf**
[SkinnedMesh.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4227888/SkinnedMesh.zip)

**Version**
 - OS: Windows
 - Blender Version 2.81

**Comment by julienduroure** [comment]
Hello,
Thanks for the reporting.
Can you please share the original .blend file?
Please test with a recent version of Blender, because some bugs are already fixed since 2.81 release. You can download recent version here: builder.blender.org (or wait a few hours, 2.82 should be release today)

**Comment by j-conrad** [comment]
I did include the .bend file in the initial bug report.
I just tested this with Blender 2.82 and got different results:

The aforementioned 'dirtying' of the .blend file doesn't happen, however, it seems to now export with one of the animations (Bend_Left) not working when I open this resulting .glb in the viewer.

It may be worth keeping this bug open so the resulting .glb files may be compared between the two versions of Blender, rather than filing a new one.

**Comment by julienduroure** [comment]
Except if I miss something, but you provided only the .glb file, not the .blend file.
We really need it to investigate.

**Comment by j-conrad** [comment]
Whoops, so I did. I just updated the .zip in the original post above to contain both files.

**Comment by julienduroure** [comment]
I am not sure to understand what is wrong with the left animation. Looks good to me, except if I missed something. Can you please explain, or screenshot what is wrong?

**Comment by j-conrad** [comment]
What I'm seeing with the 2.82 export is the mesh starting in a 'bent' state even though no animations are enabled in the viewer. I exported with the object in the 'upright' pose.
![image](https://user-images.githubusercontent.com/31968496/74995496-e9110d80-5405-11ea-899b-c76d29d21b5c.png)

**Comment by j-conrad** [comment]
Ok... I think I figured this out. Somewhere along the way, I disabled the "Always sample animations" flag in the exporter. I am able to consistently make this work correctly. Although I'm not exactly clear on when or why I would turn that flag on or off...
Any explanation would be appreciated, but otherwise, this bug can be closed.

**Comment by julienduroure** [comment]
If "always sample animations" is enabled, any bone will be backed and a keyframe is calculated fir every frame.
If "always sample animations" is disabled, only bones with animation will be converted to animation in glTF. That means that if you are using bone constraints, your animation export can be wrong.
