### ISSUE TITLE
Division by zero when exporting object parented to bone scaled to 0

### ISSUE THREAD

**Issue by ZanQdo** [KhronosGroup/glTF-Blender-IO#924]
**Describe the bug**
Object bone-parented to bone
Bone has animation in which, at some frames, scales to 0
This causes a division by zero error on exporting

**To Reproduce**

Simply export this file

[PoseBoneScaleZero.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4202941/PoseBoneScaleZero.zip)

You should get the following error:

` 191, in __gather_children
    bone_tail = [0, blender_bone.length / blender_bone.matrix.to_scale()[1], 0]
ZeroDivisionError: float division by zero`

**Version**
Operating system: Windows-10-10.0.18362-SP0 64 Bits
Graphics card: GeForce GTX 1080 with Max-Q Design/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 441.87

**Blender Version**
Broken: version: 2.83 (sub 2), branch: master, commit date: 2020-01-29 19:38, hash: `rBc3001812dc02`

**Comment by julienduroure** [comment]
I fixed the division error in branch fix_924, but seems there a Blender API error returning the local scale of object when parent scale is 0.
I opened a bug report for that: https://developer.blender.org/T74112

**Comment by julienduroure** [comment]
Well, seems the bug will not be fixed in Blender, we will have to find a workaround here to fix it
