### ISSUE TITLE
Import: unsupported texture wrap modes

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#926]
Only the texture wrap modes CLAMPxCLAMP and REPEATxREPEAT are supported, because those are the only options for wrapping on a Texture Image node.

TextureSettingsTest.gltf

![texture-setting](https://user-images.githubusercontent.com/11024420/74592791-6a256a80-4fea-11ea-8f36-e3584dc1c2e3.png)

**Comment by scurest** [comment]
The [way I solved this in gltf-blender-importer](https://github.com/ksons/gltf-blender-importer/pull/34) was to add nodes to the shader graph in between the UV transform and the Image Texture node to perform the wrapping manually for the other wrap modes.

I just saw Blender 2.82 added Wrap (works for REPEAT) and Pingpong (works for MIRRORED_REPEAT) Math nodes which now make this really easy.

![newtex](https://user-images.githubusercontent.com/11024420/74592937-d359ad80-4feb-11ea-840e-648fe6df1897.png)

Faking it with nodes like this has very small errors near the very edge of the texture compared to the real thing when using linear-filtering (because properly speaking the wrap mode should affect filtering). Otherwise, it works fine.

[Here](https://github.com/KhronosGroup/glTF-Blender-IO/compare/master...scurest:wrap-modes)'s a branch that implements this if you want to try it.

What's everybody think?

**Comment by emackey** [comment]
It's impressive.  Somehow I don't think it will be easy to get the exporter doing that too, but maybe just import support for that one is good?

**Comment by scurest** [comment]
>   Somehow I don't think it will be easy to get the exporter doing that too

That's why I didn't mention it before, but I don't think it would be too hard for the exporter to guess it actually. Sketch:

````py
# Gather wrap mode from Image Texture's extension property
wrap_s = CLAMP_TO_EDGE if img_texture_node.extension == 'EXTEND' else REPEAT
wrap_t = CLAMP_TO_EDGE if img_texture_node.extension == 'EXTEND' else REPEAT

# Gather wrap mode from this node setup
# [Separate XYZ] => [Math] => [Combine XYZ] => [Image Texture]
#                => [Math] =>
result = gltf2_blender_search_node_tree.from_socket(
    img_texture_node.inputs['Vector'],
    gltf2_blender_search_node_tree.FilterByType(bpy.types.ShaderNodeCombineXYZ)))
if result:
    com_xyz = result[0]

    def gather_wrap(from_socket, default):
        find_node = lambda node:
            isinstance(node, bpy.types.ShaderNodeMath) and \
            node.operation in ['PINGPONG', 'WRAP']
        result = gltf2_blender_search_node_tree.from_socket(from_socket, find_node)
        if result:
            return MIRRORED_REPEAT if result[0].operation == 'PINGPONG' else REPEAT
        return default

    wrap_s = gather_wrap(com_xyz.inputs[0], default=wrap_s)
    wrap_t = gather_wrap(com_xyz.inputs[1], default=wrap_t)
````
