### ISSUE TITLE
Invalid normals exported with skinning

### ISSUE THREAD

**Issue by u3shit** [KhronosGroup/glTF-Blender-IO#927]
**Describe the bug**
I'm trying to export a sample human blend file to gltf and noticed that the normals are all over the place (both if I import it back to blender, use an online gltf viewer on in my game engine), especially around the limbs and head. Searching for the issue, I saw that there were problems with auto smoothing, so I tried to disable, enable, change the angle, but it didn't seem to help. The only thing that fixed the normals is completely removing the armature modifier.

As an unrelated note, the base model also appears to have 90 degrees rotated, maybe normal calculation doesn't take this into consideration?

**To Reproduce**
1. Download animated human from http://quaternius.com/assets.html or http://www.mediafire.com/file/5lb27hroq86pkov/Animated_Human_by_%2540Quaternius.zip/file
2. Export to gltf/glb using the default settings
3. Import back

**Expected behavior**
Correct normals are exported.

**Screenshots**
Original model:
![human_normal](https://user-images.githubusercontent.com/17014489/74593989-94e6e180-5031-11ea-8200-474ead8ea761.png)

After importing the exported glb back. Notice how the normals that are mostly parallel to the x axis look normal, but others are wrong.
![human_after_import](https://user-images.githubusercontent.com/17014489/74593996-a4fec100-5031-11ea-8754-13066c10499d.png)

The exported model in babylonjs (skinning disabled before load). It looks like the normal debug doesn't apply the transformations, but it's still visible that the normals around the arm are mostly parallel to the arm.
![human_babylonjs](https://user-images.githubusercontent.com/17014489/74594043-150d4700-5032-11ea-8566-095c64c2bd7f.png)

**.blend file/ .gltf**
Link above.

**Version**
 - OS: linux x64
 - Blender Version 2.82 (release)

**Comment by julienduroure** [comment]
Hello,
Did you try with 'apply modifiers' at export?
Maybe linked to #877

**Comment by u3shit** [comment]
Hello,
Unfortunately apply modifiers doesn't seem to do anything, the normals are still wrong. Also tried disabling Y up, but that didn't help either, only that the model is now upside-down.

**Comment by julienduroure** [comment]
Confirmed.
Here is a simple file for tests/debug
Linked to the fact that original armature has a not initial rotation

[normal_bug.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4229027/normal_bug.blend.zip)
