### ISSUE TITLE
animation not beign exported

### ISSUE THREAD

**Issue by Favkis** [KhronosGroup/glTF-Blender-IO#928]
I export animation, but it's not beign exported

I have around 30 animations in model, when I export new one this happens: 
![image](https://user-images.githubusercontent.com/46406204/74602562-061ea700-50bb-11ea-88ff-d947091e0178.png)

Here's animation list in blender:
![image](https://user-images.githubusercontent.com/46406204/74602567-12a2ff80-50bb-11ea-88e8-da021941e577.png)

There's no dodge aniamtion being exported, is there a limit for actions or something? 

blender 2.81 in steam

**Comment by donmccurdy** [comment]
See https://docs.blender.org/manual/en/2.81/addons/import_export/io_scene_gltf2.html — actions must either be stashed or marked as NLA tracks to be associated with an object for export

**Comment by julienduroure** [comment]
Seems this was not an issue!
Don't hesitate to comment if we misunderstood something
