### ISSUE TITLE
Animation not exported correctly when exporting without sampling

### ISSUE THREAD

**Issue by u3shit** [KhronosGroup/glTF-Blender-IO#938]
**Describe the bug**
This is a bit weird. If I export the blend file to a gltf embedded, first with the default settings, I get a working gltf file. Next I export without `Always Sample Animations`, the file becomes ~50KB smaller while the animation still looks correct in babylonjs. However, if I restart blender, export the same unmodified blend file without animation sampling, it will only export the first frame of the animation. In this case even re-exporting with sampling doesn't help, I have to reload the original blend if I want the animation to work.

**To Reproduce**
1. Open the blend file
2. Export to .gltf (embedded variant, not sure if this matters) using the default settings
3. Open in babylonjs, animation plays
4. Export to .gltf again, but with `Always Sample Animations` disabled -> animation still working
5. Restart blender or reload the blend file
6. Export to .gltf, with `Always Sample Animations` disabled
7. Open in babylonjs, animation is a still frame

**Expected behavior**
Animation export should work even if I export with `Always Sample Animations` disabled first.

**Screenshots**
Original blend file:
![human2](https://user-images.githubusercontent.com/17014489/75081886-48a80f80-5511-11ea-9f07-7b07cdc14f89.png)

Reimporting the gltf in blender. Every channel is a constant:
![screen](https://user-images.githubusercontent.com/17014489/75081857-1dbdbb80-5511-11ea-9a96-4fb0792634be.png)

**.blend file/ .gltf**
[test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4238563/test.zip)
This is a modified version of the file I used in #927. I've tried to reproduce the problem with a simpler model, but with that the problem didn't surface and my blender-fu is quite limited.

**Version**
 - OS: linux
 - Blender Version 2.82

**Comment by julienduroure** [comment]
Confirmed.
The fact that it works the second time too is a cache bug that will be solved with #935 
So ... I can confirm the bug, when "always sampling" is disabled

**Comment by donmccurdy** [comment]
@julienduroure does https://github.com/KhronosGroup/glTF-Blender-IO/pull/939 fix the cache issue, or the export with "always sample" disabled?

**Comment by julienduroure** [comment]
@donmccurdy #939 fixes the export with always sample disabled (and when sample is needed anyway).
Cache issue was fixed by #935
