### ISSUE TITLE
All animations are the same when re-exporting

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#942]
When re-exporting an imported model with multiple animations, the animations will all be the same as whatever animation was already playing in the timeline.

You can test this with eg. the Fox sample model. Import it, export it, then open it in the glTF Viewer. All the animations will be truncated versions of the Survey animation.

I bisected to ba44b7e which started checking action.id_root.

So this is because I never set `action.id_root = 'OBJECT'` in the importer when creating actions (morph target animations do already get id_root set).

I'll PR a fix.

**Comment by scurest** [comment]
@julienduroure That was fast, thanks :)

I looked into this a little more. The Collada importer sets the id_root to 'OBJECT' but the FBX importer doesn't seem to, so I don't think we'll be able to export stashed actions that came from an FBX import. Maybe we should eventually try to see if we can handle actions with `id_root == ''` too...

**Comment by julienduroure** [comment]
IIRC, the check was added to ignore actions on shapekeys.
There is probably other way(s) to check if an action is object/armature or SK animation.
