### ISSUE TITLE
Possible bug in ortographic camera export

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#944]
I am not sure if this is really a bug, but in the ortographic camera exporter, there is something like this

```
        orthographic.xmag = blender_camera.ortho_scale
        orthographic.ymag = blender_camera.ortho_scale
```
both have the same value

This looks odd to me, but I am not sure if its really a bug or not. Can someone have a look, please?

**Comment by scurest** [comment]
It looks plausible to me and seems to work in the glTF Viewer. What's odd about it?

![cam6](https://user-images.githubusercontent.com/11024420/75304310-a46fe280-5808-11ea-81ca-9cf94655aef4.jpeg)
![cam16](https://user-images.githubusercontent.com/11024420/75304318-a8036980-5808-11ea-9cb5-f0acbca18035.jpeg)

**Comment by donmccurdy** [comment]
See https://github.com/KhronosGroup/glTF/issues/1663. I think I tested my viewer against exports from Blender, so we might be wrong together on this one. :) Let's wait for clarification on the GitHub issue...

**Comment by scurest** [comment]
Well, the spec says what the viewProjection matrix should be so we shoudl be able to test it.

In Blender, let's do *File > Defaults > Load Factory Settings* to get the default scene with a cube, a light, and a camera. Do *View Camera*. Set the camera to Orthographic. It looks like this

![camview](https://user-images.githubusercontent.com/11024420/75311455-6d0b3100-581c-11ea-8858-33606a81b6b1.png)

[Here](https://jsfiddle.net/9p3tqym4/)'s a JSFiddle that draws the cube with WebGL.

* world space vertices get transformed into view space with the inverse of the camera's world transform (I got it with  `D.objects['Camera'].world_matrix().inverted()`)
* view space vertices get transformed into clip space by the [projection matrix from the glTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#orthographic-projection)

It looks like this

![fiddle](https://user-images.githubusercontent.com/11024420/75311674-3550b900-581d-11ea-919f-8e5406bd49e1.png)

Are these the things we want to get to be the same?

**Comment by scurest** [comment]
@donmccurdy The Viewer looks like this (I resized it so the aspect ratio would be the same)

![viewer](https://user-images.githubusercontent.com/11024420/75312948-0b999100-5821-11ea-9305-1e39bdcf960f.png)

which does look like its off by a factor of two from the fiddle.

If I set a breakpoint in `OrthographicCamera.updateProjectionMatrix` it looks like the first entry in Three's projection matrix is `1 / (xmag / 2)`. The matrix in the spec has `1/xmag`. Can you check it out?

**Comment by scurest** [comment]
Also, any other viewers that will let us look through a camera?

**Comment by jjcasmar** [comment]
I can test with kuesa. What seems odd to me is that xmag and ymag are always the same, ortho_scale.

**Comment by jjcasmar** [comment]
This is what I see with Kuesa.
![image](https://user-images.githubusercontent.com/2644001/75328016-97d9a180-587d-11ea-9e39-7d89e26db2f5.png)

and this with babylon.js
![image](https://user-images.githubusercontent.com/2644001/75328037-9f00af80-587d-11ea-8ae0-b502e7a0c650.png)

aspect ratio is nearly 1920x1080, as in Blender

**Comment by scurest** [comment]
@jjcasmar Thanks, that matches the fiddle too.

I tested with [this viewer](https://github.com/bwasty/gltf-viewer) and got the same thing

![rust-gltf-viewer](https://user-images.githubusercontent.com/11024420/75326911-1b28d200-5841-11ea-8565-698321c81423.png)

So going by all these...

It looks like we need to halve the ortho_scale

```py
orthographic.xmag = blender_camera.ortho_scale / 2
orthographic.ymag = blender_camera.ortho_scale / 2
```

This appears to work when the resolution is square. When its not, we need to do something with the aspect ratio too (not sure what yet).

**Comment by jjcasmar** [comment]
doesnt look strange to you that xmag and ymag are always the same?

**Comment by scurest** [comment]
I see why they'd be different if the resolution isn't square now. Otherwise...?

Do you mean, like, you're expecting `ortho_scale_x` and `ortho_scale_y` or something?

**Comment by jjcasmar** [comment]
Yes. If not, why do we actually have two values in gltf?

**Comment by scurest** [comment]
Well, for non-square aspect ratios I guess.

**Comment by scurest** [comment]
This closer but still not exact

````diff
diff --git a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cameras.py b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cameras.py
index c992639..5ae0360 100644
--- a/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cameras.py
+++ b/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cameras.py
@@ -70,8 +70,16 @@ def __gather_orthographic(blender_camera, export_settings):
             znear=None
         )
 
-        orthographic.xmag = blender_camera.ortho_scale
-        orthographic.ymag = blender_camera.ortho_scale
+        width = bpy.context.scene.render.pixel_aspect_x * bpy.context.scene.render.resolution_x
+        height = bpy.context.scene.render.pixel_aspect_y * bpy.context.scene.render.resolution_y
+        if width >= height:
+            orthographic.xmag = 1
+            orthographic.ymag = height / width
+        else:
+            orthographic.xmag = width / height
+            orthographic.ymag = 1
+        orthographic.xmag *= blender_camera.ortho_scale / 2
+        orthographic.ymag *= blender_camera.ortho_scale / 2
 
         orthographic.znear = blender_camera.clip_start
         orthographic.zfar = blender_camera.clip_end

````

![cam-com-horiz](https://user-images.githubusercontent.com/11024420/76077784-01853a00-5f67-11ea-93ed-919861ffb67e.png)
![cam-com-vert](https://user-images.githubusercontent.com/11024420/76077791-04802a80-5f67-11ea-94f0-4eaca52dc476.png)

**Comment by scurest** [comment]
Cf #624

**Comment by jjcasmar** [comment]
Is there any news on this?
