### ISSUE TITLE
Manage action.id_root = ""

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#948]
Following #942 and #943 , we need to find a way to change/enhance the way we check animation here :
https://github.com/KhronosGroup/glTF-Blender-IO/blob/19665b05a59550dee1aeaf24d548e2ce8477f4ba/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animations.py#L51

Seems that id_root is always set to "OBJECT" or "KEY" when creating "by hand" in the UI, but sometimes the field is empty (for example when importing fbx file).

What I am proposing:
* Open a bug report for fbx importer
* in glTF exporter: Check the value of id_root. If set --> no change regarding the way it's handle for now in master. If id_root is empty, we need an extra search to be able to determinate if the action is an object/armature animation, or if this is a morph animation.

**Comment by scurest** [comment]
Since `__get_blender_actions` knows whether each action was found on an object or a shapekey, it could return that piece of data along with the action and track name, and then `gather_animations` could check that instead of id_root.

**Comment by julienduroure** [comment]
Yes, LGTM
