### ISSUE TITLE
Generate json pointer 

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#951]
I am implementing a first draft of EXT_property_animation. My idea is to have a proff of concept of the extension working and then try to move the extension so it can be ratified. 

The extension allows to animate any property using json pointers. It is something like this:
```
"animations" : [
    {
        "extensions" : {
            "EXT_property_animation" : {
                "channels" : [
                    {
                        "sampler" : 0,
                        "target" : "/materials/1/pbrMetallicRoughness/roughnessFactor"
                    },
                    {
                        "sampler" : 1,
                        "target" : "/materials/1/pbrMetallicRoughness/baseColorFactor"
                    }
                ]
            }
        }
    ]
```

Right now, the exporter generates a python scene which represents the glTF scene, and then is converted to json. In the python scene, a glTF.Node references a glTF.Mesh. When it is converted to json, that reference is converted to an index.

I would like to know if its possible to also convert it to a json pointer to ease the implementation of EXT_property_animation

**Comment by donmccurdy** [comment]
Related: https://github.com/KhronosGroup/glTF-Blender-IO/pull/776

**Comment by jjcasmar** [comment]
The extension itself will be implemented as a gltf hook

**Comment by donmccurdy** [comment]
> I would like to know if its possible to also convert it to a json pointer to ease the implementation of EXT_property_animation

Sorry, I think the answer here is no, nothing currently exists that generates JSON pointers. Probably this addon can make some guarantees about the order in which objects will be written to JSON, once they are in the Python scene, but I don't think we can do more than that.
