### ISSUE TITLE
Export: NLA strip animations sometimes aren't named with their track name

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#953]
Sometimes (when the NLA strip animation consists of a single action I think), an exported NLA strip animation will be named after an action instead of after the track name.

For example, if you import CesiumMan, you get one NLA strip animation. The track is named "Anim_0" and the action is named "Anim_0_Node_21".

If you then export, you get an animation named "Anim_0_Node_21".

Round-trip a few more times and you wind up with an animation named "Anim_0_Node_21_Node_21_Node_21".

The name should stay "Anim_0" across round-trips.

**Comment by scurest** [comment]
Actually sorry, this is fixed when there's only one NLA strip animation, but it's gotten worse when there's more than one. If I test with the Fox sample, it imports like this:

![fg](https://user-images.githubusercontent.com/11024420/76786195-cc59c280-6784-11ea-8c40-b0a14cc93674.png)

If I then export and reimport (comparison is before and after fb509b1)

![comp](https://user-images.githubusercontent.com/11024420/76786724-ae409200-6785-11ea-9b47-25774cdbaa02.png)

So "Walk_root" and "Survey_root" aren't fixed, and "Run_root" has become "Walk"!

**Comment by julienduroure** [comment]
Should be fixed in #980

**Comment by scurest** [comment]
Yeah, it's working here.
