### ISSUE TITLE
Curves with bevel and NURBS,

### ISSUE THREAD

**Issue by pafurijaz** [KhronosGroup/glTF-Blender-IO#954]
**Is your feature request related to a problem? Please describe.**
Hi, I often use curved objects to create handrails and other NUBRS surfaces and lofts.

**Describe the solution you'd like**
When I export the models in GLB I have to convert to mesh NURBS and beveled curves first and then do the export in GLB, this does not happen when I export to OBJ, that menage very well this kind of geometry in Blender.

**Describe alternatives you've considered**
It would be nice if this process were done during the export phase, the program would have to evaluate the curves and objects and then do the conversion before exporting to GLB. Maybe add an option like applying modifiers to geometry with the label convert **curves and surfaces**.

**Additional context**
Beveled curve for handrail before exporting.
![Istantanea_2020-02-28_12-10-05](https://user-images.githubusercontent.com/11751383/75544452-4a4b6900-5a24-11ea-9528-d1c33de5fd7f.png)

no handrail geometry after exporting into glb.
![Istantanea_2020-02-28_12-18-49](https://user-images.githubusercontent.com/11751383/75544627-a9a97900-5a24-11ea-9a7d-376b40fddcb2.png)

**Comment by emackey** [comment]
We have an "Apply Modifiers" checkbox on export here, but I don't think Blender offers a modifier that converts text/curves to meshes as part of the modifier stack.  That might make a good feature request for the Blender team, and would be useful outside of this addon.

**Comment by donmccurdy** [comment]
Good to know that the OBJ addon manages it, maybe there's some code we can reuse...

**Comment by pafurijaz** [comment]
> We have an "Apply Modifiers" checkbox on export here, but I don't think Blender offers a modifier that converts text/curves to meshes as part of the modifier stack. That might make a good feature request for the Blender team, and would be useful outside of this addon.
The internal OBJ python add-on already do that without converting those geometry before, it's done when you select up the option apply modifiers.

**Comment by pafurijaz** [comment]
One last thought the export dont support the also linked objects to scene and any other instances inside scene, that is very frustrating because the obj exporter support all these type of geometry linked or instanced. And saving these scene into obj I loose all pbr shading.

**Comment by julienduroure** [comment]
@pafurijaz Please do not mixup all subjects. This ticket is about curves and nurbs.
Instance issue is already known, and PR is quite ready to be merged ( #950  )

**Comment by will-ca** [comment]
@donmccurdy 

For reference, the OBJ addon does *really well* with converting different types of objects. It even exports nested, instanced collections with different transformation (including negative scale) correctly every time I've used it— In this regard, it even outperforms Blender's own `ALT`+`C`/`CTRL`+`A` "`Convert to mesh`"/"`Visual Geometry to Mesh`" and "`Make Instances Real`" features, in practice.

Any add-on or built-in feature that successfully borrows its code to replicate its accuracy in that regard would be good, from my experience.
