### ISSUE TITLE
Support a glTF material blender node

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#955]
At the moment, glTF exporter uses Principled BSDF blender node to generate a glTF material. I think this can be confusing for several reasons:
- Principled BSDF has a lot of inputs that are not used at all. This can confuse artists that think they have access to a lot more that they really have. 
- Occlusion is not supported in the Principled BSDF in the same way as in glTF and we need a "hack" to make it work (according to https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#baked-ambient-occlusion)
- glTF supports baseColorFactor and baseColorTexture, but when using the Principled BSDF, you can only set one, the factor or the texture. This makes it impossible to animated the baseColorFactor if you have a baseColorTexture (thinking about EXT_property_animation)

I think the workflow can be simplified if we have blender nodes that matches 1:1 the glTF materials. This blender nodes can be easily implemented in python and I already have some experience doing it (I have been working with KDAB to support some custom material as shown here https://youtu.be/yVj1yqOEcXY?list=PL6CJYn40gN6gJJzt9-s8Ny0Qua5-ms-we&t=341)

The material exporter would also be simplified a lot if using custom nodes.

**Comment by scurest** [comment]
Cf #846

**Comment by donmccurdy** [comment]
We spent a while going this direction before the Principled BSDF material was available, and I'm not particularly eager to go back that way if we can avoid it:

> Principled BSDF has a lot of inputs that are not used at all.

Many of these are on the [glTF PBR roadmap](https://github.com/KhronosGroup/glTF/milestone/2). The Principled BSDF material actually matches our long-term plans extremely well, given that we're not specifically designing for it. Clearcoat and clearcoat roughness should be ready [very soon](https://github.com/KhronosGroup/glTF-Blender-IO/pull/931).

> Occlusion is not supported in the Principled BSDF in the same way as in glTF.

That's inconvenient, I agree, but it's more important to me that we support Blender's best practice workflows than that we cover every feature glTF can offer. If the requirement of a custom node seems like a "hack" for AO, I'm not sure how relying on a custom node for the entire material is better?

> glTF supports baseColorFactor and baseColorTexture, but when using the Principled BSDF, you can only set one, the factor or the texture.

This can be solved in other ways, like a multiply node. When we previously had a custom node, it was actually quite confusing to users that there were separate baseColor and baseColorTexture inputs – people were surprised they couldn't plug a texture into baseColor. 😁

> The material exporter would also be simplified a lot if using custom nodes.

I'd be pretty strongly against removing support for the Principled BSDF node. It's going to be an important part of the Blender world for the foreseeable future, and it matches glTF's goals quite well. 

One additional problem that we didn't have in the past, but probably would now: the addon is enabled by default. Users would previously discover our addon on GitHub and install it, and find the custom nodes in the repository at that time. Now, the addon is "just there", users don't find our repository to download our custom nodes or to read our manual. And we can't/shouldn't create new custom nodes that are available by default in Blender, especially when they do practically the same thing as the Principled BSDF node.

I think it might be worth requesting some better way of rendering Baked AO in the blender developer channels. Other than that, I think the rest of the issues can be solved in other ways.

**Comment by jjcasmar** [comment]
> This can be solved in other ways, like a multiply node. When we previously had a custom node, it was actually quite confusing to users that there were separate baseColor and baseColorTexture inputs – people were surprised they couldn't plug a texture into baseColor.

I am not sure a multiply node is a good idea. I timplies start adding nodes to the shader graph, and specifying which combinations are supported. Its a big graph to compute a baseColorFactor allowed or only a a texture multiplied by a color?

**Comment by donmccurdy** [comment]
I guess I should also say — we do still support the custom node from previous versions of the exporter, too.  It’s not the workflow I’d want to recommend for most users, but it’s available if you prefer it.

**Comment by jjcasmar** [comment]
> This can be solved in other ways, like a multiply node. When we previously had a custom node, it was actually quite confusing to users that there were separate baseColor and baseColorTexture inputs – people were surprised they couldn't plug a texture into baseColor. grin

I wouldn't take that road. One of the main issue of using a shader graph is that only a very small subset is supported in glTF. You would need to start documenting what kind of graphs are supported and start solving issues for people trying to do much more than what the exporter can handle. 

Using a custom node solves this issue (at least, it alleviates it). You want a standard material, add a standard node, nothing more, nothing else. You want a KHR_materials_unlit, you add that node.

I understand that the Principled BSDF is going to be an important part of Blender, but glTF can't support a complex material (like multiplying the color of two textures and feed that to the base color input). Therefore, if an artist is creating a scene that its going to be exported to glTF,  he needs to adapt anyway to what glTF can support. 

> I think it might be worth requesting some better way of rendering Baked AO in the blender developer channels. Other than that, I think the rest of the issues can be solved in other ways.

If I understand correctly what the AO map should do, you could use a `Mix Shader` after the principled bsdf, no? Something like this:
![image](https://user-images.githubusercontent.com/2644001/75636458-4d5e7900-5c1f-11ea-9f2d-e08cd50cff2b.png)
![image](https://user-images.githubusercontent.com/2644001/75636468-62d3a300-5c1f-11ea-9469-b7aa3e0ff67b.png)

**Comment by jjcasmar** [comment]
I forgot to explain my suggestion for the base color factor/texture. The idea would be to have a base color factor socket and a base color texture selector, instead of having a base color factor socket and a base color texture socket. As you said, that can open a can of worms trying to connect what you shouldnt where you shouldn't. I would suggest something like this:

![image](https://user-images.githubusercontent.com/2644001/75636620-9400a300-5c20-11ea-94b8-d4104fbff1fb.png)

Notw how the textures are not socket, but selectors. This implements a CustomShaderNodeGroup (or something like that). In the inside (although you can use tab to see it), there is a NodeTree with `Image Texture` nodes. The texture is controlled by the outter image selector. 

I think this would really simplify producing glTF assets.

**Comment by donmccurdy** [comment]
> If I understand correctly what the AO map should do, you could use a Mix Shader after the principled bsdf, no?

It doesn't do the right thing, unfortunately. We'd need a socket on the Principled BSDF node, really. But it's close enough for some users.

> One of the main issue of using a shader graph is that only a very small subset is supported in glTF.

That's somewhat unavoidable. Unless we make a custom node with _no_ sockets, users will need to understand what they can and can't export. And in the long-run it isn't impossible to take a complex node graph and bake it to a texture — it's just hard. The NVIDIA MDL Distiller and [another addon](https://blenderartists.org/t/addon-glb-texture-tools-scene-optimization-quick-export-web-preview/1207509) do essentially the same thing.

> Note how the textures are not socket, but selectors.

I'll defer to @emackey on this, as we may need to preserve backward compatibility, but if you want to improve the custom node that we already have, I think that's OK. 

However, I'm not willing to remove support for Principled BSDF. It's the most important material workflow for us right now.

**Comment by jjcasmar** [comment]
> It doesn't do the right thing, unfortunately. We'd need a socket on the Principled BSDF node.

Why is it incorrect? What should it do? In Kuesa we are doing the following:
```   
 // cLinear is the result of the lighting
 // Apply ambient occlusion and emissive channels
    cLinear *= ambientOcclusion;
    cLinear += emissive.rgb;

    return cLinear;
```

> We can't point most users to a custom node just for this file format, just because there are a few things that Blender's default materials don't do the way we'd like them to.

I understand this, but what is the difference between saying "your material is not going to work, is too complex, you can only do these things" and "use this custom node that just works"

> That's somewhat unavoidable. Unless we make a custom node with no sockets, users will need to understand what they can and can't export.

In fact this is something that I have already tried to do, without success. Do you know if its possible? https://blender.stackexchange.com/questions/162333/remove-input-socket-of-shader-node-keeping-default-value

Okay, Ill consider this closed as there is a strong opinion against it. I leave it open anyway as I have asked some questions

**Comment by scurest** [comment]
> Why is it incorrect? What should it do?

If you do it after the Principled node, the occlusion affects the emissive. Since emissive is part of the Principled node, if you do occlusion afterwards you're doing

    cLinear += emissive.rgb;
    cLinear *= ambientOcclusion;
    // which is the same as
    cLinear *= ambientOcclusion;
    cLinear += ambientOcclusion * emissive.rgb;

**Comment by jjcasmar** [comment]
Ah you are right! That could be solved premultiplying the emissive in a custom node and feeding that to an internal Principled BSDF :p

**Comment by donmccurdy** [comment]
Additionally, AO is supposed to affect only indirect light. See:

- https://github.com/KhronosGroup/glTF/issues/915#issuecomment-441305821
- https://github.com/KhronosGroup/glTF/issues/915#issuecomment-447610714
- https://github.com/KhronosGroup/glTF/issues/915#issuecomment-460360473

> I understand this, but what is the difference between saying "your material is not going to work, is too complex, you can only do these things" and "use this custom node that just works"

We have that custom node, and we support the workflow you're suggesting with it. But we aren't going to remove support for Principled BSDF, which is better for the majority of users. I think those are the two key points on this issue, so I'll close it, but suggestions for improving the custom nodes we do support are fine with me.
