### ISSUE TITLE
Improve consistency of addon's Python API

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#956]
Reported on Twitter, https://twitter.com/mcclure111/status/1233959819767427073, it seems that other I/O addons have some conventions on parameter naming that we've missed: `export_selected` should be ~~`use_selected`~~ `use_selection` , for one. We should fix that, and check if there are others that could be more consistent.

I think I would start with the FBX addon's naming as a guide, since its options and features are most similar to ours.

**Comment by donmccurdy** [comment]
Perhaps keeping the old `export_selected` supported for a few releases, with a warning, for backward compatibility.

**Comment by julienduroure** [comment]
I just created #957 to start the discussion, and how backward compatibility can be done

**Comment by donmccurdy** [comment]
I'd like to keep this open for now - `use_selected` is the reported property, but there are likely several others we could check consistent naming for.

**Comment by donmccurdy** [comment]
The options we want to match would be these: https://docs.blender.org/api/current/bpy.ops.export_scene.html. In general, we'd want `use_*` instead of `export_*`.

**Comment by julienduroure** [comment]
Is there still some cases we need to rename here?

**Comment by julienduroure** [comment]
Seems we can close this now
