### ISSUE TITLE
[Doubt] How is tangents generated for cubicspline animations

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#960]
I am implement EXT_property_animation as part of a custom extension and I am not sure I understand the logic for converting the bezier control points to glTF cubicsplines. Could someone explain it to me, please?

something that annoys me is that in blender you have 6 values to control each bezier keyframe (time and value for the sample and the 2 control points) while in glTF we only have 4 values (timestamp, value, in-tangent and out-tangent). That makes the space of possible curves smaller. Is this correct? If so, how is the conversion done?

**Comment by donmccurdy** [comment]
There can be quite a lot of things in authoring tools, like Blender, that don't translate easily into runtime-ready keyframes. Another major one is IK constraints, which modify data between keyframes in complex ways.

The most common general solution, as far as I know, is to resample the animation (perhaps at 30fps) with linear interpolation. Tools like gltfpack can prune and optimize the animation from there, to remove unneeded frames with minimal impact on visual output.

**Comment by jjcasmar** [comment]
I understand that blender can do much more and some decision must be made, but still, the exporter can output cubicspline animations. As I want to match the output when using the property animation extension, I want to understand how they are generated. By looking at the code is not clear to me the math happening

**Comment by scurest** [comment]
I also want to know. It's this right?

https://github.com/KhronosGroup/glTF-Blender-IO/blob/4936b5b2779c3500e834d7fba253100627c10b33/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_animation_sampler_keyframes.py#L296-L299

The glTF out-tangent is just the right derivative of the interpolated curve at the keyframe so the obvious thing to do is to use the right derivative of the Blender curve, which is just the slope of the line from the point on the curve to the handle:

    rise/run = (keyframe_pt.handle_right[1] - keyframe_pt.co[1]) /
               (keyframe_pt.handle_right[0] - keyframe_pt.co[0])

**Comment by jjcasmar** [comment]
@emackey I algo opened that question, but more on the line of how to convert cubic spline to bezier (as it can be done exactly) . Here I want the other way round, how to get the best approximation of a bezier using a cubic spline and how is the exporter generating the tangents (and why you took that decisions if you know them :-) )

**Comment by emackey** [comment]
Having explored glTF's `CUBICSPLINE` interpolation just recently for a new implementation, I don't think it's up to the task of replicating what Blender does without animation sampling.  I think this primarily for two reasons:

- As mentioned above, glTF is only storing the slope and not the weight (or strength? magnitude?) of the tangent vector, and my un-scientific testing and graph plotting suggests that the space of possible curve definitions is dramatically reduced without that information.
- In the case of rotations specifically, glTF appears to be storing slopes of tangents to individual `x, y, z, w` values in a rotation quaternion, and expecting implementations to interpolate them separately and then normalize the resulting quaternion.  A typical Blender user is placing these tangents on Euler axis angles, not quaternion components, and I would not expect there to be a 1:1 mapping between them.

So, I suspect that this addon's choice of sampling animations by default is really the only reasonable way to handle Blender's CubicSpline keyframes.  However, it creates a ton of redundant data for linear and step (Constant) keyframes.

What would people think of this proposal?

1. Get rid of the UI checkbox asking to "Always sample animations" or not.
2. Any channels that are all "Constant" keys export non-sampled (1:1) as glTF STEP animation.
3. Any channels that are all Linear keys export non-sampled (1:1) as glTF LINEAR animation.
4. Everything else gets sampled the way "Always sample animations" currently works.

Note that some of this logic is already in place.  For example even if "Always sample animations" is turned off currently, you can still end up with sampled animations if you've mixed your keyframe types on a track, or added "Quadric" or other odd keys in there.

So what I'm really proposing is, the addon can easily determine when it's safe to NOT sample animations for STEP and LINEAR, and do so, and it should automatically sample everything else.

We would lose the ability to convert Blender CubicSpline to glTF CUBICSPLINE, but the two are not really using the same math, in spite of having the same name.

**Comment by emackey** [comment]
(One doubt about the above:  A long-spinning wheel with linear rotation probably benefits a lot from sampling being enabled.)

**Comment by jjcasmar** [comment]
I think that is a good approach. 

I would also like to suggest a BEZIER_SPLINE interpolation extension also to handle this cases and not just hermite interpolation. 

> We would lose the ability to convert Blender CubicSpline to glTF CUBICSPLINE, but the two are not really using the same math, in spite of having the same name.

In fact they dont have the same name. Blender is called BEZIER and in glTF is called CUBIC.

**Comment by scurest** [comment]
> the addon can easily determine when it's safe to NOT sample animations for STEP and LINEAR, and do so, and it should automatically sample everything else

That's #691, but it's not very easy. In addition to rotations, there's all kinds of complicated relationships like inherit_rotation where, say, the Blender location is constant, but the glTF translation needs to vary in time. Just looking at the keys in the fcurve isn't enough.

**Comment by fire** [comment]
Godot Engine's cubic spline implementation is currently broken, so the gltf2 interpolates rather than use the built in cubic functionality.

**Comment by donmccurdy** [comment]
This issue is a bit open-ended; unless there's something actionable we can do here I will close it. Spec discussion may continue on https://github.com/KhronosGroup/glTF/issues/1778.
