### ISSUE TITLE
Blender 2.82a

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#962]
It looks like there will be a Blender 2.82a patch release soon.

https://developer.blender.org/T74274

I'd like to propose including the fix for #930 and #932 in the 2.82a patch, would this be possible?

**Comment by julienduroure** [comment]
Seems legit.
I will merge #932 tonight, and propose to include it on 2.82a

**Comment by emackey** [comment]
Thanks!

I got the issue link from meeting notes:  https://devtalk.blender.org/t/2-march-2020/11911

**Comment by julienduroure** [comment]
Proposition sent: https://developer.blender.org/T74274#885925

**Comment by julienduroure** [comment]
Note that it seems that the fix is now added in the commit list to be backported in 2.82a

**Comment by julienduroure** [comment]
Corresponding commits are now cherry-picked in blender repo branch.
--> I need to do the same here, to have fix in 2.82 branch too

**Comment by julienduroure** [comment]
Done!
