### ISSUE TITLE
Activating the star icon on track in NLA Editor causes all exported animations to be duplicates of action in that track

### ISSUE THREAD

**Issue by aalwardt** [KhronosGroup/glTF-Blender-IO#964]
Clicking the Solo (star icon) on a track in the NLA editor affects the export of other animations. All animations exported become duplicates of the animation in the track that's been marked as Solo.

**To Reproduce**

1. Load facialAnimationBones.blend
2. Activate the star icon for either the ShakeTrack or NodTrack in the NLA Editor.
3. Export the gltf file. Both the NodAction and ShakeAction animations exported will be duplicates of whichever track was marked with the star icon.

**Expected behavior**
When clicking the star icon to suppress the other NLA tracks in Blender, I would expect it to have no effect on the exported animations.

**Screenshots**
Screenshot showing the NLA editor with one of the star icons activated:
![NLAEditor](https://user-images.githubusercontent.com/26095070/76225565-1413a380-61f3-11ea-9b02-cd3a1f31db88.png)

**.blend file**
[facialAnimationBones.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4307241/facialAnimationBones.zip)

**Version**
 - OS: Arch Linux
 - Blender Version 2.82

**Comment by julienduroure** [comment]
Confirmed.
Star tracks are not checked for now.
