### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#97]
The [Blender release notes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Import_Export#glTF) currently link to the documentation from glTF-Blender-Exporter, which focus on the (no longer necessary) custom Cycles nodes. We should create new documentation within this project, covering at least:

- Principled BSDF supported features and node arrangements 
- Transparency and alpha
- Animation
  - How to export multiple animations
  - Which armature/skinning configurations are supported
- How to test a model and report bugs

**Comment by donmccurdy** [comment]
Draft documentation: https://gltf-blender-io-docs-gbueavkvns.now.sh/addons/io_gltf2.html

A few TODOs:
- [ ] Documentation reflects the reorganized export options (https://github.com/KhronosGroup/glTF-Blender-IO/pull/122)
- [ ] The suggested "unlit" workflow does not actually work right now. I'm not sure what is the right solution there.
- [ ] I haven't tested the animation workflows recently, but we should confirm the three options described (`(a) make it the active Action on the object, (b) create a single-strip NLA track, or (c) stash the action`) are still correct.
- [ ] @julienduroure could you suggest descriptions for the Importer options?

**Comment by donmccurdy** [comment]
Updated documentation: https://gltf-blender-io-docs-fuznnktuig.now.sh/addons/io_gltf2

@julienduroure thanks for adding the importer option descriptions!

@julienduroure @UX3D-nopper Could you take a look at this and suggest any changes you'd prefer? The draft is pushed to https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/docs/io_gltf2.rst. I've omitted the Unlit workflow, since that is still in progress. Once everything looks good I'll try merging the docs into the Blender repo.

**Comment by julienduroure** [comment]
Currently, only KHR_materials_pbrSpecularGlossiness is supported by importer. I saw that Norbert added details about importer/exporter support, but removed them later.

**Comment by donmccurdy** [comment]
@julienduroure Not sure I understand, do you mean that spec/gloss is supported by the importer and not the exporter? Or that the importer supports spec/gloss, but not metal/rough and unlit?

**Comment by julienduroure** [comment]
@donmccurdy I was talking about extension supported by importer. That means that importer supports metal/rough (core glTF) & spec/gloss (KHR_materials_pbrSpecularGlossiness extension), but not unlit, not ponctual lights, not texture transfom.

Hope I will have time in January to add these supports

**Comment by donmccurdy** [comment]
I see, thanks! I'll update the docs.

**Comment by julienduroure** [comment]
For info, I just get commit rights on Blender documentation.
I have to setup stuff before be able to commit, but should be done in following days/weeks

**Comment by julienduroure** [comment]
Note that I still don't have wiki account, so change logs are still linking to wrong url, but I will ask someone to change it, or to create me a wiki account

**Comment by donmccurdy** [comment]
Awesome, thank you! :)

I'm not sure what to write for Unlit documentation at the moment; I think we'll want the exporter to treat an Emissive node – in a material _without_ a Principled node – as unlit. Once that change is in the importer and exporter should be roundtrip compatible and we can document it.

**Comment by donmccurdy** [comment]
@julienduroure do you think it's worthwhile to keep the documentation in GitHub (https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/docs/blender_docs/io_gltf2.rst), in addition to the Blender repository? The RST formatting doesn't look quite right on GitHub, and the images aren't visible, so I'm wondering if having docs only in the Blender repository might be easier.

**Comment by donmccurdy** [comment]
Docs are live! 🎊

https://docs.blender.org/manual/en/dev/addons/io_gltf2.html
