### ISSUE TITLE
Batch Export Crashes Blender

### ISSUE THREAD

**Issue by vini-guerrero** [KhronosGroup/glTF-Blender-IO#979]
**Describe the bug**
Creating a simple addon for batch export gltf collection into multiple files.
Blender self closes.

**To Reproduce**
1. Install addon (https://gist.github.com/vini-guerrero/61cf40fe59e12d1e32f226ed9d926072)
2. Select collection to export
3. Select path destination to export
4. Click Export assets

**Expected behavior**
Export individual gltf assets in folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/18181786/76773283-0032e900-6781-11ea-8d75-68ebeab9cb61.png)
![image](https://user-images.githubusercontent.com/18181786/76773419-2fe1f100-6781-11ea-9694-856e0382ebe6.png)

**.blend file/ .gltf**
Can't share this particular file but any file with multiple objects in a collection is crashing for batch export.

**Version**
- OS: macOS Mojave 10.14.6
- Blender Version 2.82 Stable

**Additional context**
Using Python API to Export in Addon:
`bpy.ops.export_scene.gltf(filepath=fileName, export_format="GLB", export_selected=True, export_tangents=False, export_image_format="JPEG", export_cameras=False, export_lights=False)`

Log attached.
[Addon.crash.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/4338900/Addon.crash.txt)

**Comment by julienduroure** [comment]
Can't reproduce. Everything went right, and exported correctly without crash. Please check your blender installation...

**Comment by vini-guerrero** [comment]
Tested on a Linux machine, also self closes, same issue.

**Comment by julienduroure** [comment]
Tested on linux here --> No crash

**Comment by julienduroure** [comment]
Is someone else able to reproduce this crash?

**Comment by vini-guerrero** [comment]
Tested with different settings and running Blender from command line, as well as using Blender alpha version, still can't batch export on macOS 😔

**Comment by julienduroure** [comment]
Can this ticket be closed? Is someone else can reproduce?

**Comment by vini-guerrero** [comment]
Just re-tested it with latest Blender v2.83. Issue is now fixed, thanks for the follow up on this @julienduroure
