### ISSUE TITLE
Export Extras not working

### ISSUE THREAD

**Issue by ZanQdo** [KhronosGroup/glTF-Blender-IO#98]
The zip contains a blend file made with 9abcf56fa88 from windows from https://builder.blender.org/download/

It has a cube with a property named "Foo" containing a string "Bar"

Zip also has a sample of exported GLTF with the option Export Extras enabled

[Cube.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2617961/Cube.zip)

However the generated file lacks the exported property.

**Comment by ZanQdo** [comment]
I can confirm the latest version from github works! Thanks

**Comment by julienduroure** [comment]
Is now merged in Blender 2.8 repo
