### ISSUE TITLE
Can't export animation to gltf file.

### ISSUE THREAD

**Issue by weerowee** [KhronosGroup/glTF-Blender-IO#985]
**Describe the bug**
I try to export my blender file to gltf file but animation doesn't exist.

**To Reproduce**
1. Export to GLB/GLTF

**Expected behavior**
It didn't have any animation in the gltf file

**.blend file/ .gltf**
[greenhouse_s.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4352154/greenhouse_s.blend.zip)

**Version**
 - OS: [macOS]

 - Blender Version [2.81a]

**Comment by donmccurdy** [comment]
Some context: we discussed this on https://discourse.threejs.org/t/cant-export-animation-coming-from-blender/13589/5, I tested with Actions pushed down as NLA tracks but they didn't export either way. Not sure yet why the actions don't export.

**Comment by julienduroure** [comment]
![image](https://user-images.githubusercontent.com/1696020/77040939-41154280-69b9-11ea-89b5-5946badcd0ab.png)

It seems that when an animation has some non valid channels, all the animation is ignored.
IIRC, it was a choice to not export action at all, instead of take the risk to export half the action, and having something wrong

**Comment by weerowee** [comment]
> ![image](https://user-images.githubusercontent.com/1696020/77040939-41154280-69b9-11ea-89b5-5946badcd0ab.png)
> 
> It seems that when an animation has some non valid channels, all the animation is ignored.
> IIRC, it was a choice to not export action at all, instead of take the risk to export half the action, and having something wrong

if you dont mind , can i ask how to fix this i'm not really inclined in bender .

**Comment by weerowee** [comment]
Fix it!!!!!! by deleting the disable in viewport and  disable in renders channel in animation dope sheet 
![Screen Shot 2020-03-19 at 16 54 45](https://user-images.githubusercontent.com/58925154/77044325-8ca00e80-6a02-11ea-8f65-5a02249e7c1f.png)

**Comment by julienduroure** [comment]
Ok, thanks !
Closing this ticket
