### ISSUE TITLE
file has a huge size compared to fbx and export time so long

### ISSUE THREAD

**Issue by koloved** [KhronosGroup/glTF-Blender-IO#99]
just a cube with 3.5 ml polygons
export glb - 746 mb, 10 minute ++
export fbx - 155 mb, ~1 minute

its not a bug, but it is impossible to work with this format

**Comment by donmccurdy** [comment]
We'll look into this. In the meantime, you can significantly reduce the export size by disabling any of the following mesh data you do not need:

- normals
- tangents
- UVs

In addition, compression can be applied to a glTF file using tools like [glTF-Pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/), which should reduce the size of the geometry by 85-95%.

**Comment by koloved** [comment]
I would even say the size is not important, as the time for export / import

**Comment by UX3D-schmithuesen** [comment]
@koloved  Can you please attach an example file? Even if the export time was higher than for fbx, it was still less than factor 5 and the glb was actually smaller than the fbx in my test.

**Comment by koloved** [comment]
@UX3D-schmithuesen 
gltf - 1 hour and more! =) 
fbx - less 5 seconds

the file  (apply modif, select only) - [file](https://dropmefiles.com/yK93f)

**Comment by emackey** [comment]
@koloved This was just fixed today in #158.  It will probably be a day or two before you see the fix appear in the next Blender build.

With the latest fixes, and "apply modifiers" checked, the export here now takes about 45 seconds on my machine.  I confirmed that FBX (with the modifier manually applied) takes less than 5, so, there's still room for performance improvements here, but at least the hour-long hang is fixed.

**Comment by UX3D-schmithuesen** [comment]
File size is also **just** double for me so I wouldn't say that things are problematic anymore.

**Comment by anto2102** [comment]
personnaly i will not use glTF while it's not fully implemented into Maya
( i mean with a working exporter and a importer )

**Comment by donmccurdy** [comment]
@anto2102 the most effective place to comment on this issue would probably be https://forums.autodesk.com/t5/maya-ideas/gltf-support/idi-p/7958727.

**Comment by shawticus** [comment]
Just wanted to leave a note -- maybe there's a regression, but on Blender 2.82 on Ubuntu, importing a 50mb FBX and rexporting out gets us a 500 MB file. The file has lots of blendshapes, though (it's a face).
Weirdly had the same experience on another dataset where we converted an OBJ to GLTF and it went from 10 mb to 100 mb, which should literally never happen. Wonder if this is a GLTF lib issue, not a blender issue.

**Comment by donmccurdy** [comment]
Please share example files — there are many reasons a file’s size may change.

**Comment by shawticus** [comment]
@donmccurdy 
Seems to be related to Blender, not GLTF

**Comment by v-prgmr** [comment]
> Just wanted to leave a note -- maybe there's a regression, but on Blender 2.82 on Ubuntu, importing a 50mb FBX and rexporting out to GLTF gets us a 500 MB file. The file has lots of blendshapes, though (it's a face), maybe it is something to do with blendshape data specifically, because I also just kicked out some static scene GLTFs with no issues.
> Weirdly had the same experience on another dataset where we converted an OBJ to GLTF using the Cesium tool, and it went from 10 mb to 100 mb, which should literally never happen. Wonder if this is a GLTF lib issue, not a blender issue.

I am having a similar issue. I have a 17 MB .glb which i import into blender to adjust and change the origin. On export the same model now has a file size of 90+ MB. It would be great if you (@shawticus ) could give any pointers regarding what settings to look for in Blender.

**Comment by donmccurdy** [comment]
@v-prgmr if this is still happening on a recent version of Blender, could you file an issue with an example `.glb` attached? Thanks!

**Comment by v-prgmr** [comment]
> @v-prgmr if this is still happening on a recent version of Blender, could you file an issue with an example `.glb` attached? Thanks! We cannot investigate these issues without examples to reproduce the problem.

@donmccurdy Will do so 👍 
Thanks for the quick response

**Comment by donmccurdy** [comment]
(for future readers: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1166)
