### ISSUE TITLE
Import camera names

### ISSUE THREAD

**Issue by pixue** [KhronosGroup/glTF-Blender-IO#992]
All names of cameras imported from gltf/glb files are lost.

**To Reproduce**
1. Import a gltf or glb with cameras defined.
2. All camera names are lost
![Blender282a](https://user-images.githubusercontent.com/1937898/77534527-1c2d3d80-6e99-11ea-844a-002561b1ad8e.png)

**Expected behavior**
Camera names defined, not generic names like PerspectiveCamera, PerspectiveCamera001, ...

**Test files gltf&glb**
[Test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4380711/Test.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.82a

**Additional context**
My input is a gltf/glb that potentially can have a lot cameras defined and an array of camera names to render, so it's important to identify each camera easily.

Test files are created using ThreeJS editor, adding a camera and customizing its name. Then I export to gltf and glb.

![Captura el 2020-03-25 a las 12 41 30](https://user-images.githubusercontent.com/1937898/77533228-c5beff80-6e96-11ea-9a61-fb3aace8ffbd.png)

https://sandbox.babylonjs.com/ loads well the camera name
![Captura el 2020-03-25 a las 12 37 48](https://user-images.githubusercontent.com/1937898/77533223-c3f53c00-6e96-11ea-8c94-fc902828fa32.png)

I see that the name is stored in a object inside "nodes" array of gltf file.

**Comment by scurest** [comment]
More precisely: The camera names are imported. The node where the camera is instantiated however, gets the name of the camera, rather than the name from its `node.name`.

**Comment by pixue** [comment]
Thanks!
